### ISSUE TITLE
256-bit keysize for java.security.KeyPairGenerator

### ISSUE THREAD

**Issue by tpapanna** [AdoptOpenJDK/openjdk-build#1014]
IBM JDK used to accept 256-bit keysize for KeyPairGenerator. But openJDK has a restriction of key size to be in the range from 512 to 1024. 
Now that IBM is recommending customers to use openJDK, Is there any way openJDK allows 256-bit keysize, if not when can we expect this to be supported in OpenJDK.

**Comment by keithc-ca** [comment]
Isn't the current thing that (RSA at least) should be 2048 bits? 256 bits would be rather insecure.

**Comment by adamfarley** [comment]
The mailing list for OpenJDK security issues can be reached here:

https://mail.openjdk.java.net/mailman/listinfo/security-dev

If you sign up and send them your issue, you can get a view on whether the community intends to support this smaller key size.

Also, after reviewing the code, it seems like it is the specific implementation of the KeyPairGenerator class that allow/disallow limits on the key size, so anyone investigating that would need to know which specific algorithm you're using.

**Comment by karianna** [comment]
Closing this as providing support for 256-bit key sizes is no longer deemed to meet the security baseline.

**Comment by tpapanna** [comment]
> Isn't the current thinking that (RSA at least) should be 2048 bits? 256 bits would be rather insecure.

I agree it is less secure but due to some restrictions from server side we are unable to increase the key size.
