### ISSUE TITLE
OpenJDK 12+33 keeps crashing; wrong crash report URL

### ISSUE THREAD

**Issue by ChristophKaser** [AdoptOpenJDK/openjdk-build#1027]
**Platform:**
Hotspot OpenJDK 12+33
**Architecture:**
Windows x64 (zip-File, not Installer)

I keep getting crashes every few hours with the Openjdk12+33 build. Older OpenJDK versions like jdk-11.0.1_13 work fine.

> A fatal error has been detected by the Java Runtime Environment:
> 
>  Internal Error (c:/cygwin64/tmp/openjdk-jdk12u-windows-x64-hotspot/workspace/build/src/src/hotspot/share/runtime/mutex.cpp:1073), pid=5736, tid=2600
>  guarantee(no_safepoint_check || Self->is_Java_thread()) failed: invariant
> 
> JRE version: OpenJDK Runtime Environment (12.0+33) (build 12+33)
> Java VM: OpenJDK 64-Bit Server VM (12+33, mixed mode, sharing, tiered, compressed oops, g1 gc, windows-amd64)
> Core dump will be written. Default location: C:\WINDOWS\system32\hs_err_pid5736.mdmp
> 
> An error report file with more information is saved as:
> C:\WINDOWS\system32\hs_err_pid5736.log
> 
> If you would like to submit a bug report, please visit:
>   https://github.com/eclipse/openj9/issues

The bug report URL seems to be false: This is a hotspot build, but it references the OpenJ9 bugtracker. 

I am unsure whether this is the right place to report the crash: Should it be raised in the openjdk bugtracker instead? If this is the right place, would it be helpful to upload the mdmp-File? It is rather large (8 GB after compression).

The crash log is here:
[hs_err_pid2532.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3062490/hs_err_pid2532.log)

**Comment by gdams** [comment]
Looks like we are adding the param to all builds and not just openj9 https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L227

**Comment by ChristophKaser** [comment]
For the record, the crash itself also happens with the jdk.java.net build and might be this one:
https://bugs.openjdk.java.net/browse/JDK-8219321
