### ISSUE TITLE
Left over artifacts should be cleaned up or not collected

### ISSUE THREAD

**Issue by ali-ince** [AdoptOpenJDK/openjdk-build#1029]
Windows - Any

I found a [build](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/247) that not only includes binaries (artifacts that are named as `*2019-04-10-03-27*`) that were generated by the build itself but also binaries from a previous build (artifacts that are named as `*2019-04-09-17-51*`).

**Comment by gdams** [comment]
@johnoliver think this is fixed now? We only keep the latest artefact. Can it be closed?

**Comment by M-Davies** [comment]
ping @johnoliver ref George's comment [above](https://github.com/AdoptOpenJDK/openjdk-build/issues/1029#issuecomment-549326700)

**Comment by M-Davies** [comment]
For lack of reply, I'm going to close this. OP can always reopen if this proves to still be a problem
