### ISSUE TITLE
No OpenJDK 11 LTS Windows installers

### ISSUE THREAD

**Issue by Inverness** [AdoptOpenJDK/openjdk-build#1038]
Is there a reason for Windows installers not being available for OpenJDK 11 HotSpot?

I am looking for Windows installers for LTS versions 8 and 11. I'm glad to see an installer is available for 8, and I see there is one available for 12, but I do not see one for 11.

Using 12 is not desirable because long term support is exactly what I want. This must include a Windows installer that makes it simple to install and update a JDK 11 installation over time.

**Comment by karianna** [comment]
We have installers in the nightlies and the next 11.0.3 release will have a windows installer.

For support expectations (including Commercial) please see https://www.adoptopenjdk.net/support.html
