### ISSUE TITLE
What is the difference between Adopt and OpenJDK distributions?

### ISSUE THREAD

**Issue by PeterJakubik** [AdoptOpenJDK/openjdk-build#1042]
Hello
I apologize for this dumb question, but I am confused with this new Java versioning.

Suppose I want to use Java 11 (LTS) server side.

- OpenJDK provides its own Java 11 ditribution on [openjdk on jdk.java.net](https://jdk.java.net/11/). What is the difference between this and AdoptOpenJDK Java 11 distribution?
- When there is some security Bug in OpenJDK (Oracle patches only the latest open jdk) and hopefully someone will backport this fix to older OpenJDK versions. Does AdoptOpenJDK just take that fix from OpenJDK ? If the fix will be provided by AdoptOpenJDK will this fix be also available in OpenJDK?

Thanks for clarification
Peter

**Comment by karianna** [comment]
There's very little difference - Adopt has a couple of extra patches which makes life a bit easier in PRD deployments (like backporting certificates from 11 to 8 for SSL connections).

Yes we pick up all of the patches including security from upstream.
