### ISSUE TITLE
how should i install this in my custom docker environment?

### ISSUE THREAD

**Issue by fede-green** [AdoptOpenJDK/openjdk-build#1043]
Hello, 

trying installing jdk 8 on my docker machine. Running this:

```
git clone https://github.com/AdoptOpenJDK/openjdk-build
cd openjdk-build
./makejdk-any-platform.sh --docker jdk8u
```

i am getting the following error: 

```./makejdk-any-platform.sh --docker jdk8u
Starting ./makejdk-any-platform.sh to configure, build (Adopt)OpenJDK binary
Parsing opt: --docker
Possible opt arg: jdk8u
Working dir is ./build/
[debug] COPY_MACOSX_FREE_FONT_LIB_FOR_JDK_FLAG=true
[debug] COPY_MACOSX_FREE_FONT_LIB_FOR_JRE_FLAG=true
JDK Image folder name: j2sdk-image
JRE Image folder name: j2re-image
Searching for JDK_BOOT_DIR
readlink: missing operand
Try 'readlink --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
```
any suggestion?

thanks

**Comment by MeFisto94** [comment]
Searching the repo for `readlink` gives only this as result:
https://github.com/AdoptOpenJDK/openjdk-build/blob/95dc19f9b5a9ecc02addae45312d047ad154cfe8/sbin/common/common.sh#L129

Install a JDK on your system, so `which javac` suceeeds and building works again (Just tried that, had the same problem).

**Comment by karianna** [comment]
What O/S are you running? what happens when you run:

`which javac` and subsequently `readlink -f $(which javac)`?

**Comment by M-Davies** [comment]
Hi @fede-green . Have you tried Martijn's comment [above](https://github.com/AdoptOpenJDK/openjdk-build/issues/1043#issuecomment-538451491)?

**Comment by karianna** [comment]
This was resolved some time ago (we enhanced the detection)
