### ISSUE TITLE
win32 jdk8 pipeline tested the wrong build

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#1045]
**Platform:**
win32

**Architecture:**
x86

I submitted an openjdk8u pipeline build (https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/537) for win32 with these parameters:
```
targetConfigurations	{
   "x32Windows": [
        "openj9"
    ]
}

releaseType: Nightly Without Publish
overridePublishName:
scmReference: openj9-0.14.0
additionalConfigureArgs: --with-milestone=fcs
```
The build job created this jdk:
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-201904171532-b03)
Eclipse OpenJ9 VM (build openj9-0.14.0-rc1, JRE 1.8.0 Windows Server 2012 R2 x86-32-Bit 20190417_205 (JIT enabled, AOT enabled)
OpenJ9   - bad1d4d06
OMR      - 4a4278e6
JCL      - 0ade4cc962 based on jdk8u212-b03)
```
When the downstream job to execute the openjdk tests ran it downloaded the latest nightly build to run the tests against rather than the jdk which was built in the pipeline.  This appears to be the relevant part of the job:
```
19:04:44  + ./openjdk-tests/get.sh -s /cygdrive/c/Users/jenkins/workspace/openjdk8_j9_openjdktest_x86-32_windows -t /cygdrive/c/Users/jenkins/workspace/openjdk8_j9_openjdktest_x86-32_windows/openjdk-tests -p x32_windows -r nightly -j 8 -i openj9 --openj9_repo https://github.com/eclipse/openj9.git
19:04:44  get jdk binary...
19:04:44  curl -OLJks  https://api.adoptopenjdk.net/v2/binary/nightly/openjdk8?openjdk_impl=openj9&os=windows&arch=x32&release=latest&type=jdk&heap_size=normal
19:04:46  unzip file: OpenJDK8U-jdk_x86-32_windows_openj9_2019-04-12-05-08.zip ...
19:04:48  Run C:\Users\jenkins\workspace\openjdk8_j9_openjdktest_x86-32_windows/openjdkbinary/j2sdk-image/jre/bin/java -version
19:04:49  openjdk version "1.8.0_212"
19:04:49  OpenJDK Runtime Environment (build 1.8.0_212-201904110335-b01)
19:04:49  Eclipse OpenJ9 VM (build master-8aaaa8c9d, JRE 1.8.0 Windows Server 2012 R2 x86-32-Bit 20190410_198 (JIT enabled, AOT enabled)
19:04:49  OpenJ9   - 8aaaa8c9d
19:04:49  OMR      - 2abc34c9
19:04:49  JCL      - cda1580f83 based on )
```

**Comment by karianna** [comment]
This may be related to the renaming fix we are currently working on.

**Comment by M-Davies** [comment]
@karianna @lumpfish Can this be closed? The latest [JDK8/J9/x32_Windows](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows/200/console) test run is using the [correct upstream JDK](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/554)

**Comment by karianna** [comment]
> @karianna @lumpfish Can this be closed? The latest [JDK8/J9/x32_Windows](https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows/200/console) test run is using the [correct upstream JDK](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/554)

Yes this is working now.
