### ISSUE TITLE
MSI Installer Doesn't Remove Previous Builds of OpenJDK / JRE Runtime

### ISSUE THREAD

**Issue by PatchMyPC** [AdoptOpenJDK/openjdk-build#1052]
When installing the latest build, the previous versions aren't removed for the JRE.

For example, if JRE 8 Update 202 was installed and you upgrade to 212 it leaves the previous version installed as well.

Is there a command line in the MSI you can enable to auto remove previous builds during an upgrade?

**Comment by karianna** [comment]
see https://github.com/AdoptOpenJDK/openjdk-installer/issues/88
