### ISSUE TITLE
System.getProperty("java.vm.vendor") return null

### ISSUE THREAD

**Issue by yansendao** [AdoptOpenJDK/openjdk-build#1061]
**Platform:**
* windows 
**Architecture:**
* x86-64

Please describe the issue that you are having with our binaries and if possible how to recreate it.

test command:
java.exe -cp . VendorTest

![image](https://user-images.githubusercontent.com/36258307/56881874-6c86fa00-6a94-11e9-8591-7222b9cb093a.png)

oraclejdk:

![image](https://user-images.githubusercontent.com/36258307/56881847-55480c80-6a94-11e9-83d7-6649302005cb.png)

test example:
```java
public class VendorTest {
    public static void main(String[] args) throws Exception {
        System.out.println(System.getProperty("java.vm.vendor"));
    }
}
```

[VendorTest.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/3126316/VendorTest.txt)

**Comment by yansendao** [comment]
![image](https://user-images.githubusercontent.com/36258307/56882342-e53a8600-6a95-11e9-9a6a-be8eb94e809c.png)

**Comment by karianna** [comment]
Also, see #465

**Comment by yansendao** [comment]
Amazon jdk seems to be OK.

![image](https://user-images.githubusercontent.com/36258307/56900340-2e0b3280-6ac8-11e9-8f99-78c4e41fa4cf.png)

**Comment by svaens** [comment]
Actually, i'm here for a similar reason; 
For build 
1.8.0_202 / AdoptOpenJdk / 25.202-b08
I check the vendor via:
System.getProperty("java.vm.vendor")
and I get the string:
"Oracle Corporation"

Not null.... but also unexpected. No?

**Comment by torrin47** [comment]
If it was fixed in version 1.8.0_202 / AdoptOpenJdk / 25.202-b08, why is it still empty in version 1.8.0_222 / AdoptOpenJdk / 25.222-b10? Was the fix rolled back?

```
D:\Public\Server\Apps\ArcGIS\Server\framework\runtime\jre\bin>java.exe -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)

D:\Public\Server\Apps\ArcGIS\Server\framework\runtime\jre\bin>java.exe -XshowSettings:propertie 2>&1 | findstr vendor
    java.specification.vendor = Oracle Corporation
    java.vendor = AdoptOpenJDK
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.sun.com/bugreport/
    java.vm.specification.vendor = Oracle Corporation
    java.vm.vendor =

```

**Comment by karianna** [comment]
@johnoliver Can you check?

**Comment by sxa555** [comment]
This is still broken in 8u232

**Comment by sxa555** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-build/issues/1020

**Comment by M-Davies** [comment]
Hi @yansendao . #1020 was merged so could you give this another go with one of our latest JDK's https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot

**Comment by sxa** [comment]
Looks like it was fixed between 8u242-b08 and 8u252-b09 so this is resolved
