### ISSUE TITLE
Failures in publishing of builds to github

### ISSUE THREAD

**Issue by dinogun** [AdoptOpenJDK/openjdk-build#1072]
**Platform:**
linux

**Architecture:**
x86_64

The sha file in the checksum link is not created for x64 nightly builds. Eg check this [API](https://api.adoptopenjdk.net/v2/info/nightly/openjdk11?openjdk_impl=hotspot&type=jdk&release=latest&heap_size=normal&arch=x64&os=linux). The [checksum_link](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-05-04-16-25/OpenJDK11U-jdk_x64_linux_hotspot_2019-05-04-16-25.tar.gz.sha256.txt) from the above API is invalid.

**Comment by dinogun** [comment]
Docker builds are failing because of this.

**Comment by gdams** [comment]
I'm voting that we first remove the binary with the missing sha256.

**Comment by karianna** [comment]
> I'm voting that we first remove the binary with the missing sha256.

These are just nightlies right?

**Comment by gdams** [comment]
> These are just nightlies right?
correct

**Comment by gdams** [comment]
same happened here with a ppc64le build https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk11u-2019-05-06-04-12

**Comment by sxa555** [comment]
There's something more fundamental wrong here.
[jdk11u-2019-05-03-02-47](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk11u-2019-05-03-02-47) - Looks ok
[jdk11u-2019-05-04-16-25](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk11u-2019-05-04-16-25) - missing several platforms and also the sha for xLinux as per this description
[jdk11u-2019-05-06-04-12](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk11u-2019-05-06-04-12) - Only has arm32/arm64 and some bits of ppc64le (Missing SHA)

**Comment by sxa555** [comment]
[Release job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool) (restricted access) has failed for the last three nights
```
INFO: timed out accessing https://uploads.github.com/repos/AdoptOpenJDK/openjdk11-binaries/releases/17161973/assets?name=OpenJDK11U-jdk_ppc64le_linux_openj9_2019-05-06-04-12.tar.gz; will try 2 more time(s)
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
```

**Comment by sxa555** [comment]
(Hope you don't mind me renaming the title of your issue @dinogun but it seems a bit wider than your original description!)

**Comment by M-Davies** [comment]
@sxa @dinogun Is this still an issue?

**Comment by sxa** [comment]
A random checksum link in the API looks OK to me currently, therefore closing.
