### ISSUE TITLE
JDK 12 build is failing

### ISSUE THREAD

**Issue by fbascheper** [AdoptOpenJDK/openjdk-build#1074]
According to the [build farm of JDK12](https://ci.adoptopenjdk.net/view/git-hg/job/git-hg/job/git-hg-jdk12u/) this build has been failing since April 16. 

I'd like to help out, but I need some assistance getting started.

**Comment by fbascheper** [comment]
Current steps taken:
* I've forked the repo into my own GitHub account
* Cloned [the forked repo in my own GitHub account](https://github.com/fbascheper/openjdk-build)
* ````
   cd git-hg
   bash ./mercurialToGit.sh jdk-updates/jdk12u
   ````
* The script fails with
   ```` 
   Cloning into 'jdk12u'...
   Warning: Permanently added the RSA host key for IP address '140.82.118.3' to the list of known hosts.
   git@github.com: Permission denied (publickey).
   fatal: Could not read from remote repository.
   
   Please make sure you have the correct access rights 
   and the repository exists.
   + exit 1
   ```` 
* Reason: line 61 has a hardcoded repo I don't have access to
   `` git clone git@github.com:AdoptOpenJDK/openjdk-"$GITHUB_REPO".git "$GITHUB_REPO" || exit 1``

To be able to work on this, please add this repo as an environment variable instead of hardcoding it.

**Comment by johnoliver** [comment]
added the -r/--repo argument to the script

**Comment by karianna** [comment]
#1089 will land shortly

**Comment by adamfarley** [comment]
Reopening this as there were quality concerns over the merge, which blocked "#1089 will land shortly".

**Comment by adamfarley** [comment]
Closing on johno's recommendation.
