### ISSUE TITLE
Anypoint Studio - Mulesoft

### ISSUE THREAD

**Issue by rassad** [AdoptOpenJDK/openjdk-build#1079]
can not find the following file when i try to install Mulesoft Anypoint Studio
org.eclipse.e4.core.di.InjectionException: java.lang.NoClassDefFoundError: javax/annotation/PostConstruct

**Comment by karianna** [comment]
@rassad What version of AdoptOpenJDK are you using?  Does this occur with Oracle's Java?

**Comment by rassad** [comment]
I utilized a different version of adoptopenjdk and it worked with anywherestudio (mulesoft product).
