### ISSUE TITLE
Nightly builds failing with FlowNode not found error

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#1083]
Seems to affect all releases.

Nightly builds are failing with
```
Creating placeholder flownodes because failed loading originals.
java.io.IOException: Tried to load head FlowNodes for execution Owner[build-scripts/openjdk8-pipeline/566:build-scripts/openjdk8-pipeline #566] but FlowNode was not found in storage for head id:FlowNodeId 1:206
```
e.g. https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/566/console

**Comment by johnoliver** [comment]
this looks to be working ok now

**Comment by aaronjhoffman** [comment]
@johnoliver What did you do to fix this? I'm having the same exact issue.

**Comment by AdamBrousseau** [comment]
This error appears in the console logs for the jobs if 
 Jenkins master has been restarted during the build. So the answer really depends on why your master is being restarted.
