### ISSUE TITLE
Heads-up: 8u222-b03 will include cacerts backport from JDK 11

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-build#1086]
See: http://hg.openjdk.java.net/jdk8u/jdk8u-dev/jdk/rev/cac1aa619936

It'll be included in the next tagged build in jdk8u/jdk8u. I expect this to cause issues for the hg-git mirror job. ETA a week from now.

**Comment by karianna** [comment]
More like our build script that does this already - @johnoliver here's your heads up!

**Comment by ecki** [comment]
Will you remove the option from the adoptopenjdk build script then?

**Comment by karianna** [comment]
> Will you remove the option from the adoptopenjdk build script then?

Once we confirm it's the same list, yes

**Comment by gdams** [comment]
@karianna can this be closed now?

**Comment by karianna** [comment]
@johnoliver Should we remove the option from the build scripts?

**Comment by sxa555** [comment]
File in jdk8u is the same as the one that was in jdk11u (until today - was removed in https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/f27021a230a82a2d5eeda7859fb08586a0872456 thus causing breaks on Windows JDK8u builds today
