### ISSUE TITLE
JDK_BOOT_DIR heuristic doesn't handle paths that contain spaces

### ISSUE THREAD

**Issue by stacktracer** [AdoptOpenJDK/openjdk-build#1093]
**Platform:** Win10 (Cygwin)

**Architecture:** x86-64

I'm running on Cygwin, with ```JAVA_HOME=/cygdrive/c/Program Files/AdoptOpenJDK/jdk-8.0.212.03-hotspot```. The makejdk-any-platform.sh script fails with: 
```
Running gradle with /cygdrive
ERROR: JAVA_HOME is set to an invalid directory: /cygdrive
```

Solved by quoting the dirname and readlink args in the setBootJdk() function in configureBuild.sh:
```
    if [[ "${BUILD_CONFIG[OS_KERNEL_NAME]}" == "darwin" ]]; then
      BUILD_CONFIG[JDK_BOOT_DIR]="$(dirname "$(dirname "$(readlink "$(which javac)")")")"
    else
      BUILD_CONFIG[JDK_BOOT_DIR]="$(dirname "$(dirname "$(readlink -f "$(which javac)")")")"
    fi
```

**Comment by karianna** [comment]
@stacktracer Are you able to submit a PR?

**Comment by M-Davies** [comment]
Ping @stacktracer . Can you submit a PR for this? If not, I'd be happy to take it up

**Comment by stacktracer** [comment]
@M-Davies go for it. I intended to come back to this, but evidently that's not going to actually happen.
