### ISSUE TITLE
Add the OpenJ9 Win64 Large Heap (XL) package to the builds

### ISSUE THREAD

**Issue by DanHeidinga** [AdoptOpenJDK/openjdk-build#1099]
OpenJ9 project users have requested the Large Heap (XL) packages on Windows as well.  

These packages are built and tested at OpenJ9 and we'd like to have them included in the regular Adopt pipelines.  Adopt provides the XL packages on both OSX and Linux today.

Can Adopt add the Windows XL packages for JDK 8, 11 & 12?

**Comment by karianna** [comment]
Does the windows host need any other requirements?

**Comment by DanHeidinga** [comment]
Nothing extra required on the machine.  Any machine that builds the regular package can build the XL version as well

**Comment by DanHeidinga** [comment]
A big thank you to everyone involved in getting this done!

**Comment by karianna** [comment]
@DanHeidinga Well let's see if it works first :-D
