### ISSUE TITLE
Consider outputting the result of configure into a file (much like we do for meta data)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#11]
This might be also partly a openjdk-website issue or at least a GitHub openjdk-build wiki issue? - people will want to know where the binaries are built and with exactly what versions of which libs and it's also a nice shout out to say who's helping out!

**Comment by tellison** [comment]
Yep, can go on the openjdk website, or the adopt wiki.  I'd argue that it is not interesting enough to users to feature on the adoptopenjdk (a.k.a. getopenjdk<g>) website.

**Comment by gdams** [comment]
started doing that here: https://github.com/AdoptOpenJDK/openjdk-build/wiki/Build-Machines

**Comment by karianna** [comment]
Related to #14

**Comment by sxa555** [comment]
@gdams Did that wiki page get moved or did it ultimately become https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/inventory.yml?

**Comment by karianna** [comment]
The output of Configure should hopefully do the trick + some extra Meta info from infra

**Comment by M-Davies** [comment]
@karianna Do you feel this feature would this feature would be better placed on the website or wiki? I'm not sure where to raise a follow up issue for this

**Comment by karianna** [comment]
I think having the output of configure in the metadata of the build would actually be a good thing.  That way it would be automatically accessible from the API/Website as well (since we already expose that file - I think)

**Comment by M-Davies** [comment]
Follow up https://github.com/AdoptOpenJDK/openjdk-website/issues/740

**Comment by karianna** [comment]
I'm reopening this as I the Add java version and configure to VersionInfo #1918 PR closed this (but is not related).  We still need to actually push the results of the configure step into the meta data file

**Comment by M-Davies** [comment]
> actually push the results of the configure step into the meta data file

Shouldn't that be done on the API side? Unless you are wanting the configure_args & java version to be in the metadata and not the VersionInfo?

**Comment by karianna** [comment]
I'm thinking in the metadata yes.  I'm not sure that our API should be returning that info directly.  Probably worth a discussion in the build channel
