### ISSUE TITLE
Jenkins jobs hold onto executors unnecessarily 

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#1100]
Jenkins executors are a limited and precious resource, grabbing an executor via a `node()` block in pipeline code allows you to do "material work". Anything not requiring a node should not be run in a node block. Jenkins pipelines run in a lightweight executor on master already, so anything run outside of a node block will be executed on master. A classic example is launching downstream jobs and waiting for them to return. During this waiting period, it is unnecessary to hold onto an executor. After looking at the pipeline source I see a number of places where nodes are being held onto when they don't need to be.

- https://github.com/AdoptOpenJDK/openjdk-build/blob/9751419bc6d65bf606252950c58792622b857406/pipelines/build/common/openjdk_build_pipeline.groovy#L176
- https://github.com/AdoptOpenJDK/openjdk-build/blob/cde8eced3223ceebdafba0421730801fbbf668d2/pipelines/build/common/build_base_file.groovy#L278
- possibly these https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/openjdk8_pipeline.groovy#L132

**Comment by AdamBrousseau** [comment]
Thanks for making this change @M-Davies . However I think you've missed the cases in the openjdkX_pipeline.groovy files. Unless I'm misunderstanding but it appears that it holds on to an executor on master for the duration of the entire build.

**Comment by M-Davies** [comment]
@AdamBrousseau I'm going through testing removing that node block at the moment. Thanks for the heads up

**Comment by M-Davies** [comment]
Testing complete, it appears to work without the node block https://github.com/AdoptOpenJDK/openjdk-build/pull/1981
