### ISSUE TITLE
Jenkins pipelines need timeouts

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#1101]
I see lots of jobs currently running that will not finish and have been running for several days.
Adding timeouts to your pipeline code will allow these to clean themselves up automatically without manual effort. Usually I use layers of timeouts which allow me to control timeout for not only the entire build but more granularity at each stage or downstream job for example.

**Comment by M-Davies** [comment]
As a starting base, it would be good to get a sense of scale to understand exactly what timeouts we need for each stage, of which there are three obvious ones:
- [openjdk_build_pipeline.groovy UP TO make-adopt-build-farm.sh](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L500) is basically the setup script for `make-adopt-build-farm.sh`. This doesn't take very long in comparison to the actual build, probably only about an hour max
- [openjdk_build_pipeline.groovy INCLUDING make-adopt-build-farm.sh](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L485) This is the actual build and will take quite a while, probably a few hours
- [openjdk_build_pipeline.groovy AFTER make-adopt-build-farm.sh](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L486) This stage consists of parsing the outcome of the build, running the installer/sign jobs and archiving the artefacts that were created from it (as well as some small cleanup steps). The first two parts don't take very long (30mins?) but archiving can take up to and beyond as long as the build took if there are a lot of files to copy across. This should be given a timeout of 2-3 hours just off a quick guess.

I'd like to encourage some more discussion and opinions on this before I investigate this further however

**Comment by M-Davies** [comment]
In reply to discussions on slack, we do have https://github.com/AdoptOpenJDK/openjdk-build/issues/1634 which tracks nightly failures. Timeouts could be recorded in here and issues raised if they keep occurring.

Regarding the current timings, an idea is to be more generous with them. The average times for the pipelines are as follows:
| Version  | Total Time |
| ------------- | ------------- |
| JDK8  | 9hrs 32mins |
| JDK11  |  |
| JDK14  | 6hrs 5mins |
| JDK15  | 2hrs 29mins |

# Average Platform Times
JDK8
<img width="1581" alt="Screenshot 2020-05-21 at 09 19 26" src="https://user-images.githubusercontent.com/25231953/82538863-48d19e80-9b44-11ea-9846-72938374bc8e.png">

JDK11


JDK14
<img width="1472" alt="Screenshot 2020-05-21 at 09 21 58" src="https://user-images.githubusercontent.com/25231953/82539032-a1a13700-9b44-11ea-8af4-ce2101de539e.png">

JDK15
<img width="787" alt="Screenshot 2020-05-21 at 09 25 06" src="https://user-images.githubusercontent.com/25231953/82539213-fd6bc000-9b44-11ea-988f-4d68a135e99b.png">

The average times seem a little off to how long a pipeline actually takes to complete successfully so it would be best to make the timeouts on a platform by platform, version by version basis OR just make one big timeout (12 hours?) for all of them.
