### ISSUE TITLE
Jenkins pipelines need timestamps 

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#1102]
I noticed none of the Jenkins pipelines currently have timestamp blocks. Timestamp blocks are an easy addition to pipeline code that adds invaluable information to the console output. Generally I wrap my entire build process in a timestamp block to ensure everything is timestamped.

**Comment by M-Davies** [comment]
I'll take this up. I'm working on this in parallel to https://github.com/AdoptOpenJDK/openjdk-build/issues/1101
