### ISSUE TITLE
git-hg 3.0

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#1107]
After a discussion with @andrew-m-leonard and @johnoliver we will attempt to do the following:

1. For `git-hg-jdk8u` - Document how the script really works in the README and in the Jenkins job configuration.  For example, the `move-release-to-next-tag` option needs to be manually executed, it creates a branch with that tag and that is what a subsequent build would need to build from.

2. For `git-hg-aarch64-jdk8u` - See 1.

3. For jdk11u, jdk12u, jdk+ - archive the existing `dev` branch and use a new 'merge' technique (as opposed to the 'rebase' technique).  The first new run of this will recreate the `dev` branch.

4. Potentially update Jenkins release build scripts to make sure folks choose release branches for the jdk8u releases as opposed to the `dev` or `master` branch.

5. Improve git-hg diff jobs and do an actual diff between the release branch we created and what's in mercurial.  The recommendation is to use `bash diff <a> <b>` as git's diff tries to do ancestor searches etc.

Assign List

- [x] - Document git-hg-jdk8u usage - Martijn 
- [x] - Document git-hg-aarch64-jdk8u usage - Martijn 
- [x] - Redo git-hg for 11+ - Andrew
- [x] - Update build scripts - Martijn / John
- [x] - Improve Git Diff scripts - TBD
- [x] - Document 11+ usage - Martijn

**Comment by andrew-m-leonard** [comment]
@karianna @johnoliver Hi guys, could you review this proposal for the new jdk11+ merge script please?

**Comment by karianna** [comment]
C&P from Slack so far

```
martijnverburg [17:52]
Thanks,  Andrew - it seems that `master` would lag as we’re only updating `dev` nightly?
We use master as a ‘this is the same as canonical upstream’ or ‘upstream without our patches applied’ sanity check
leonarda [18:17]
So master would be up to date, but "dev" would lag
does that seem reasonable? we could always merge HEAD to "dev", but that makes "releasing" more difficult as we have to release from a specifically merged tag from "dev", which if we continuously merge HEAD we may have skipped over...
it's not then impossible, just makes release branching a bit more tricky
martijnverburg [18:23]
So for our nightly builds (non-release) which branch would hold the latest from mercurial + our patch? Do we need a 3rd branch?
```

**Comment by andrew-m-leonard** [comment]
Updated above strategy comment with latest: https://github.com/AdoptOpenJDK/openjdk-build/issues/1107#issuecomment-498329062

**Comment by karianna** [comment]
In conversation with @johnoliver we discussed how we could keep the existing repo (so that we didn't lose release binaries).  We thought we would be able to clone/archive the `source` code and run the new scripts on the existing repo.

**Comment by johnoliver** [comment]
think we are done on this? @andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
git-hg mirroring for jdk11+:
- openjdk-jdkNNu git repo mirror:

**Comment by andrew-m-leonard** [comment]
Think this is all done
