### ISSUE TITLE
Cisco ASDM does not work with OpenJDK 8 (deploy.jar missing)

### ISSUE THREAD

**Issue by le-jawa** [AdoptOpenJDK/openjdk-build#1109]
**Windows, Linux & Mac:**

**x64:**

Not sure if this is a problem for Cisco or OpenJDK; it depends on where the actual problem is.  ASDM requires Java 8, but does not work with OpenJDK 8.  If the libraries required for ASDM are not intended to be there (ie, Oracle intentionally did not include them), then oh well I guess.  Hopefully we can convince Cisco to support OpenJDK if that's the case.  However,  if this is something that should be there now, or in the near future, then yes, a lot of system/network admins out there would love to see this fixed.

I've attached the console log with the stack trace from ASDM.  

[ASDM-java-log.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/3238166/ASDM-java-log.txt)

**Comment by karianna** [comment]
Which version of OpenJDK are you using?  Is it AdoptOpenJDK's binary?  If so can you also try with an alternative provider (e.g. Azul's Zulu) and see if you get the same error?

**Comment by le-jawa** [comment]
Martin, 
Thanks for getting back with me.  Yes, it was AdoptOpenJDK’s build of Java 8; I even tried both VMs and both the JRE and JDK packages.  All had the same problem.  

I’ve seen some of the builds from other providers; I’ll give those a try and put the results here.

**Comment by le-jawa** [comment]
karianna,
Sorry to be so long getting back.  

I tried out Zulu, Corretto (Amazon) and Liberica (Bell SW).  Zulu and Corretto behaved exactly as AdoptOpenJDK's build (The login screen showed, then when login is attempted, I got an error box stating that the device can't be reached.)  Liberica wouldn't even run ASDM at all.

**Comment by karianna** [comment]
@le-jawa, Hmm, interesting - is there a `${java.home}/lib/deploy.jar` file in the AdoptOpenJDK installation?  Is there one in the Oracle one?

**Comment by le-jawa** [comment]
@karianna It is in the Oracle installation (both JRE and JDK), but is neither in AdoptOpenJDK JRE nor JDK.

**Comment by le-jawa** [comment]
Hey guys,
This bug is still labelled "Waiting on OP".  Was there something else you needed from me?

**Comment by karianna** [comment]
My bad - I've removed that label.  I'll ping the build channel to see if anyone has any insights.

**Comment by le-jawa** [comment]
@karianna 
Thanks for all the work on this so far.  Is there any news?

**Comment by karianna** [comment]
Nothing so far but I've put the July Milestone on so we keep it close to the top

**Comment by nvaert1986** [comment]
I've got the exact same error. I've tried using Cisco ASDM 9.12.2 with both the openjdk and regular variant of ASDM (as there are 2 versions now), but both throw the same error. I've also tried the 9.10 and 9.8 versions, but those throw the same exception too.

I'm running on Gentoo BTW and I'm using the portage version of the package, which is the HotSpot version and it throws the exception below.

P.S.: I've got the exact same error with the icedtea-jre-bin and icedtea-jdk-bin versions, which oracle-jre-bin works just fine.

java.lang.ClassNotFoundException: com.sun.deploy.trace.Trace
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1562)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.cisco.launcher.i.a(Unknown Source)
	at com.cisco.launcher.i.if(Unknown Source)
	at com.cisco.launcher.i.a(Unknown Source)
	at com.cisco.launcher.s.if(Unknown Source)
	at com.cisco.launcher.Launcher.main(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:574)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:936)

**Comment by nvaert1986** [comment]
Is there any update on this? Is there any way I can provide more useful / debugging information or assist?

**Comment by karianna** [comment]
> Is there any update on this? Is there any way I can provide more useful / debugging information or assist?

I've pinged the build channel again - this does seem to be a wider OpenJDK challenge though (since all providers are impacted)

**Comment by le-jawa** [comment]
@karianna 
Since this is such a broad issue, is there someplace else where we should report this?  (I didn't see a public bug report page for OpenJDK itself, but perhaps I missed something.)

**Comment by karianna** [comment]
You can try on the openjdk mailing lists  openjdk.java.net has a link to those.  Actually this looks a lot like a Java Web Start concern so I'll try the ITW channel.

**Comment by hendrikebbers** [comment]
Cisco reacted on this issue and has provided an alternative version of ASDM that does not need Oracle JRE. The release notes mentions a bundled OpenJRE (whatever that exactly is). You can find the release notes here: https://www.cisco.com/c/en/us/td/docs/security/asdm/7_12/release/notes/rn712.html#reference_kmz_hf1_ghb
