### ISSUE TITLE
Unable to execute JAR files using OpenJDK-11.03

### ISSUE THREAD

**Issue by saikiran40cs** [AdoptOpenJDK/openjdk-build#1115]
**Platform:**
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)

**Architecture:**
64 bit OS - Windows 10

Please describe the issue that you are having with our binaries and if possible how to recreate it.

Whenever trying to run a package JAR (Created from Maven Eclipse Project) it gives an Invocation Exception suggesting errors in the JDK

**Comment by karianna** [comment]
@saikiran40cs Can you give us the exact command that you're trying to execute and the error log?

**Comment by saikiran40cs** [comment]
The command used is as follows
java - jar automation.jar

Output
MavenInvoker exception
However the logs also show the same error

When I run the same using Oracle jdk it works flawlessly. Please help me in resolving this issue

**Comment by karianna** [comment]
@saikiran40cs Are you able to upload the jar somewhere so we can take a look?

**Comment by saikiran40cs** [comment]
@karianna Thank you for the help. It was classpath exception which was creating issue.

Now i'm able to run the tests using OpenJDK . Hail Adopt OpenJDK
