### ISSUE TITLE
Linux arm32 build only has the JDK

### ISSUE THREAD

**Issue by jkinross** [AdoptOpenJDK/openjdk-build#1121]
The Linux arm32 builds only have the JDK. Should there and/or will there be a Linux arm32 JRE build.

**Comment by M-Davies** [comment]
Hi @jkinross . We are now producing Arm32 JRE's for [JDK8](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot) and [JDK11+](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot).

**Comment by karianna** [comment]
> Hi @jkinross . We are now producing Arm32 JRE's for [JDK8](https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot) and [JDK11+](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot).

Closing
