### ISSUE TITLE
Build Beta JFR builds for OpenJDK 8

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#1128]
See https://github.com/AdoptOpenJDK/TSC/issues/84

**Comment by M-Davies** [comment]
[We are building JFR for JDK8](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot-jfr/). Triage for that has begun here: https://github.com/AdoptOpenJDK/openjdk-tests/issues/1750

@karianna Can this be closed?
