### ISSUE TITLE
32-bit Windows OpenJ9 builds for Java 8

### ISSUE THREAD

**Issue by se35710** [AdoptOpenJDK/openjdk-build#1136]
**Platform:**
Windows

**Architecture:**
i386

No builds listed in [API](https://api.adoptopenjdk.net/v2/info/nightly/openjdk8?openjdk_impl=openj9&os=windows&release=latest&type=jdk) nor in [Github](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u-2019-07-02-06-29)

**Comment by sxa555** [comment]
This looks like another "directory has failed to delete properly" problem on Windows - will address once machine is quiesced.

**Comment by sxa555** [comment]
Fixed - the problematic directory was not present on the filesystem on [build-softlayer-win2012r2-x64-1]/(https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-1/) so had got into a very odd state which prevented me taking any explicit action on the system to resolve it. Have rebooted and the build has run through. Assuming there are no further problems, should come up on the next nightly if not before.
