### ISSUE TITLE
Netbeans method profiler crashes JVM (8.0 as well as 11.0.3)

### ISSUE THREAD

**Issue by positron96** [AdoptOpenJDK/openjdk-build#1148]
**Platform:**
Windows 10

**Architecture:**
OS: x64, Java: x64

I recently upgraded my OS to Windows 10 and reinstalled everything, Java was installed from adoptOpenJDK. Now all attempts to profile methods of a java application on my PC using Netbeans leads to JVM crash. 

I've tried 
 * Netbeans 11.0
 * Netbeans 8.2,

 * JDK 11.0.3+7 
 * JDK 8.0_212-b03 (both from adoptOpenJdk)

and every combination of IDE + JDK leads to crash of JVM a fraction of second after I start methods profiling of any Java application. I get a hs_err_pid file, inside it says to report bugs here. I am attaching two of the files for netbeans 11 and JDK 8 and JDK 11.

[hs_err_pid2532.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3359032/hs_err_pid2532.log)
[hs_err_pid2176.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3359033/hs_err_pid2176.log)

I've also reported the bug in Netbeans bugtracker: https://issues.apache.org/jira/browse/NETBEANS-2798

**Comment by karianna** [comment]
Hi @positron96 What happens when you use an Oracle JDK or an alternative OpenJDK from say Azul?

**Comment by positron96** [comment]
I will try in a day or two. Cannot use Oracle jdk though since it's not free anymore (isn't it?)

**Comment by positron96** [comment]
Well, Zulu (Zulu11.31+11-CA) (11.0.3+7) (build 11.0.3+7-LTS)) crashes as well.

**Comment by karianna** [comment]
@positron96 OK, in that case, can you please report this upstream in the OpenJDK project.

In the https://mail.openjdk.java.net/mailman/listinfo/serviceability-dev mailing list

**Comment by positron96** [comment]
ok
