### ISSUE TITLE
Looking for Linux 32 bit JRE (jdk8u212-b04)

### ISSUE THREAD

**Issue by ARavichand** [AdoptOpenJDK/openjdk-build#1162]
Hi,

We are looking for Linux 32 bit JRE. We have not found the 32 bit Linux JRE for download. But in the Support Matrix we have gone through the below statement :
" Note: Any other Linux distributions that have a minimum glibc version 2.12 on x86 or version glibc version 2.17 on other architectures are expected to function without problems."

As per the above note, we tried 64 bit Linux JRE on Linux x86 (32 bit), but it was not working. Could you please suggest us where we need to pick the 32 bit JRE. Please provide us any suggestion or Links.

Thanks,
Ravichand

**Comment by karianna** [comment]
#986
