### ISSUE TITLE
ESCEPTION_ACCESS_VIOLATION jlinked 11.0.3+7 32 bits

### ISSUE THREAD

**Issue by torakiki** [AdoptOpenJDK/openjdk-build#1165]
**Platform:**
Windows 10
adoptjdk 11.0.3+7 32 bits

**Architecture:**
32 bits

I run jlink as part of a build script to create a runtime containing only the needed modules. I used this build script for a while on 64 bits platforms and everything works fine. Now I'm trying to create a 32 bits version, I downloaded the 32bits version of the jdk but when I run the command `java` in the resulting jlinked runtime, I get the following error report:
[hs_err_pid4692.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3392536/hs_err_pid4692.log)
`java` command runs fine when run from the original (not jlinked) jdk or from adoptjdk 11.0.3+7 jre. Also, everything works fine on a different 64 bits machine using adopjdk 64 bits.

**Comment by karianna** [comment]
Are you able to try with an alternative OpenJDK provider (e.g. Azul's Zulu) and see if it's a common upstream issue?

**Comment by torakiki** [comment]
I get the same error
[hs_err_pid7988.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3392858/hs_err_pid7988.log)

**Comment by karianna** [comment]
Hi @torakiki - In that case, I'd report this upstream at OpenJDK proper (with both log files and the full explanation that this is occurring with multiple vendors).  `jigsaw dash dev at openjdk dot java dot net` is the mailing list you wan (you may need to sign up first)

**Comment by karianna** [comment]
Fixed as part of 11.0.4
