### ISSUE TITLE
JVM 11.0.3+7 crash

### ISSUE THREAD

**Issue by s3b-** [AdoptOpenJDK/openjdk-build#1166]
**Platform:**
 Windows Server 2012 R2 64 bit 
**Architecture:**
OpenJDK11U-jdk_x64_windows_hotspot_11.0.3_7

I tested SonarQube 7.9.1 on my virtual machine. After I started SonarQube I ran an analysis. I stopped the SonarQube server by pressing CTRL-C and restarted it. During startup, the VM crashes when it tries to read the elasticsearch database. If I delete the database, there is no crash and SonarQube starts. But if I restart it, the same problem occurs. 

I can't reproduce it on my machine (WIN10), though.

I tested it with Zulu and Oracle's JDK - it crashes with these, as well.

[crash-log-elasticsearch.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/3392614/crash-log-elasticsearch.txt)

**Comment by karianna** [comment]
Hi @s3b-, In that case, you'll want to report this upstream to the Jackson JSON library in the first instance.  They may have used an illegal byte code weave.  They'll report it to OpenJDK proper if they think it's a genuine VM bug.
