### ISSUE TITLE
Solaris OpenJDK - can it be used on the UltraSparc IV+ / JS9

### ISSUE THREAD

**Issue by tomeppsva** [AdoptOpenJDK/openjdk-build#1170]
The build for Solaris is using the V9.  Can it be used on a newer processor?

**Comment by karianna** [comment]
@tomeppsva I'm personally not too sure - are you able to quickly test it out?

**Comment by tomeppsva** [comment]
Unfortunately, it's at a client site who is looking to use the OpenJDK, so, alas, no.

**Comment by karianna** [comment]
OK I've asked our solaris channel

**Comment by gdams** [comment]
Our Solaris expert replied with this:

Should work on any SPARC processor supported by Solaris 10/11 or illumos - anything from the UltraSparc II through to the things currently for sale. (All 64-bit sparc cpus are sparcv9.)

**Comment by gdams** [comment]
Closing for now. Please let us know if you have any issues.
