### ISSUE TITLE
apt-get update failing for ubuntu installation of adoptopenjdk

### ISSUE THREAD

**Issue by wallbank** [AdoptOpenJDK/openjdk-build#1179]
Issue occurs on multiple Ubuntu agents. Looks like the repo is not correct. Worked for me on the 18th July AEST and now failing on the 19th.

sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/

sudo apt-get install -y software-properties-common
Reading package lists... Done
Building dependency tree       
Reading state information... Done
software-properties-common is already the newest version (0.96.20.8).
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.

sudo apt-get update
Hit:1 https://deb.nodesource.com/node_11.x xenial InRelease
Hit:2 https://dl.yarnpkg.com/debian stable InRelease                                                                     
Get:3 https://download.docker.com/linux/ubuntu xenial InRelease [66.2 kB]                                                
Hit:4 http://azure.archive.ubuntu.com/ubuntu xenial InRelease                                                            
Get:5 http://azure.archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]              
Get:6 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]          
Get:7 http://azure.archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]             
Ign:8 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial InRelease                         
Get:9 http://azure.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [989 kB]
Get:10 http://azure.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [756 kB]             
Get:11 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release [4,436 B]                                       
Get:12 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release.gpg [821 B]                                      
Get:13 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [700 kB] 
Get:14 https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial/main amd64 Packages [3,367 B]
Get:15 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [449 kB]
Fetched 3,295 kB in 3s (913 kB/s)  
Reading package lists... Error!
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/adoptopenjdk.jfrog.io_adoptopenjdk_deb_dists_xenial_main_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.

**Comment by aahlenst** [comment]
Sorry about that. That seems to happen sometimes. The Artifactory indices have been recreated. It's working now, at least on my machine.

**Comment by karianna** [comment]
@wallbank Can you try again and close this issue if resolved?

**Comment by wallbank** [comment]
Thanks @karianna for jumping on this so quickly. It is working for us now also. Cheers.

**Comment by shanielh** [comment]
I'm getting this now on one of my machines: 

```
Err https://adoptopenjdk.jfrog.io trusty/main amd64 Packages
  gnutls_handshake() failed: Handshake failed
Ign https://adoptopenjdk.jfrog.io trusty/main Translation-en
W: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/trusty/main/binary-amd64/Packages  gnutls_handshake() failed: Handshake failed
```

The thing is that `apt-get update` works on other machine @ the same time.

**Comment by aahlenst** [comment]
We don't support Trusty Tahr. I doubt we have ever published packages for it. At least there's no directory for it on Artifactory, hence the error.

Generally speaking, we support distributions for as long as they are supported by their vendor. Canonical stopped the standard support on 2019-04-25.

**Comment by shanielh** [comment]
Oh, Thanks 👍

**Comment by TUp1** [comment]
Been running into this issue again.

Reading package lists... Done
W: **The repository 'https://adoptopenjdk.jfrog.io/adoptopenjdk/deb xenial Release' does not have a Release file.**
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by aahlenst** [comment]
@TUp1 Please see https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1399 for the current incident.
