### ISSUE TITLE
jdk-12.0.2+10 fails to start on aarch64

### ISSUE THREAD

**Issue by mbien** [AdoptOpenJDK/openjdk-build#1184]
**Platform:**
uname -a
Linux 4.19.0-5-arm64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19) aarch64 GNU/Linux
**Architecture:**
raspberry pi 3b+ running in 64bit mode with debian mainline kernel

the builds jdk-12+33, jdk-12.0.1+12 and latest JDK 11 worked fine while jdk-12.0.2+10 crashes right away.

reproduce with:
`java -version` in shell

result:
JVM crash by SIGSEGV, no version printed

**Comment by jerboaa** [comment]
Please attach the hs_err.log file, if there is one. Usually there is for SEGVs.

**Comment by mbien** [comment]
sorry, didn't realize you could attack files via drag&drop

[hs_err_pid1519.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3418798/hs_err_pid1519.log)

**Comment by mbien** [comment]
i tested the latest jdk13 build and it seems to work fine.

https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-linux-aarch64-hotspot/24/

**Comment by karianna** [comment]
@jerboaa - Is this something the RH experts can look at?

**Comment by sxa555** [comment]
Closing this as JDK12 is out of support and the JDK13 build looks good. We are not likely to rebuild JDK12 even if a fix is produced.
