### ISSUE TITLE
adopt open jdk 8u212  jvm options does not working?

### ISSUE THREAD

**Issue by kmdrp** [AdoptOpenJDK/openjdk-build#1185]
**Platform:**
CentOS Linux 7 _64

**Architecture:**
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b04)

Please describe the issue that you are having with our binaries and if possible how to recreate it.

I had these option for tomcat startup 
-Xms1024M \
-Xmx2048M \
-XX:MetaspaceSize=256M \
-XX:MaxMetaspaceSize=512M \

and I check jvm status with our monitoring system 

I found an something weird 
Although I set my jvm options like that , Full GC was regulary occured when heap memory was fulled of 1.5G 

So, I change JDK binary to Oracle JDK 8u202 for comparison and I didn't find any problem

**Comment by karianna** [comment]
@kmdrp Can you try again with the latest 8u222-b10 release?

**Comment by kmdrp** [comment]
thanks 
I will try it soon and Share the result here
but G1GC didnt show the issue like that So Using G1GC is the better choice I think

**Comment by kmdrp** [comment]
@karianna 
I tried again with same configuration at same server with the latest 8u222-b10 release
but there was no big difference 

I share my test result for you 

Test 1 
JDK :  adoptopenjdk 8u212b04
TEST TIME : 5h 14min  
RESULT :  Full GC was occured 13 times => 2.48times/hour

Test 2
JDK : adoptopenjdk 8u222b10
TEST TIME : 12h 
RESULT: Full GC was occured 31 times => 2.58times/hour

[VM OPTIONS]
-Xms1G -Xmx2G -XX:MetaspaceSize=256M -XX:MetaspaceMaxSize=512M -XX+UseParallelGC

[Sever Conditions]
4Core CPU(Intel Xeon E312) , 4G RAMS

**Comment by karianna** [comment]
Ah OK - can you send me your GC log?  Add `-Xloggc:<filename> -XX:+PrintGCDetails -XX:+PrintTenuringDistribution` to the java process to create one

**Comment by kmdrp** [comment]
@karianna  I'm going to try more test I will share test result to you

**Comment by karianna** [comment]
@kmdrp Any luck?

**Comment by kmdrp** [comment]
@karianna 
sorry I'm late :>
I tried many test with 8u222 as you said
and 8u222 seemed woking good 
it has any problem with vm options and stable performace 

I checked my vm options are working successfully

So do you know why 8u212 had such problem?

**Comment by karianna** [comment]
> @karianna
> sorry I'm late :>
> I tried many test with 8u222 as you said
> and 8u222 seemed woking good
> it has any problem with vm options and stable performace
> 
> I checked my vm options are working successfully
> 
> So do you know why 8u212 had such problem?

I'm really not sure sorry - I tested on a local CentOS 7 here but couldn't reproduce the issue.  Glad you got u222 to work!
