### ISSUE TITLE
TSC (Technical Steering Committee)

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#119]
myself and @karianna have started discussion about some form of committee to ensure that AdoptOpenJDK is driven forwards in a way that most suits the org. Node.js have a TSC which is in charge of this and you can read about that [here](https://nodejs.org/en/foundation/tsc/).

To me there are a few key things to be considered when creating a committee such as the TSC.

#### How many members?
So I think that for now we should have a small handful of members, perhaps 6?

#### How do people join?
To start the ball rolling I think that we should create an issue where we can nominate members and we can then have an anonymous poll for people to vote. Once the TSC is setup, members should be able to nominate other org members for consideration in the monthly meetings. 

#### Are there restrictions?
To avoid giving one company too much power, I think the first rule should be that only 1/3 of members can be from one company.

#### What does being a TSC member mean?
I feel that the TSC members should have monthly meetings to discuss progress. They should represent a wide spectrum of skills used in the AdoptOpenJDK org. They should be in charge of deciding the the direction in which the AdoptOpenJDK org grows. They should handle the admin side of the GitHub org (creating/deleting repos, adding/blocking users etc).

What I want to make clear is that this wouldn't be an "exclusive" club. All meetings should be published to the rest of the org so that members can follow progress. The aim of the TSC is to represent the org so the members should be approachable and open to accepting ideas from the wider community

**Comment by karianna** [comment]
The meetings would also be completely open to the public / community.

**Comment by gibfahn** [comment]
>The meetings would also be completely open to the public / community.

In Node we tend to find that too many people on the call breaks the web conferencing tool you use (Hangouts/Cisco/whatever), so we live-stream the meetings on youtube, and allow people to post questions on the meeting issue or in IRC. We upload them afterwards as well obviously.

**Comment by sxa555** [comment]
@karianna @gdams Any reason to keep this open now that we've got https://github.com/AdoptOpenJDK/TSC/issues/9 to track progress on the TSC project?

**Comment by gdams** [comment]
closing
