### ISSUE TITLE
jdk13u does not produce any JREs

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-build#1191]
In https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk13-pipeline/lastSuccessfulBuild/artifact/target/linux/x64/hotspot/ and https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk13-pipeline/lastSuccessfulBuild/artifact/target/linux/x64/openj9/, I just see JDKs.

Is this just temporary, an error or are they gone for good?

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/1192

**Comment by sxa555** [comment]
JDK13 JREs are now there at the above links - closing
