### ISSUE TITLE
Investigate making #getopenjdk Slack channel published somewhere

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#12]
Valid Smoke filled room concerns from mailing list bound folks

**Comment by gdams** [comment]
https://wiredcraft.com/blog/using-slack-as-a-public-chat/

**Comment by sunnychanwork** [comment]
How about Slack-IRC gateway?

https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP

**Comment by tellison** [comment]
Have set-up slackarchive.io to see how well that works...

**Comment by karianna** [comment]
@tellison - Was that with the adoptopenjdk gmail user?  I can sign up if that helps?

**Comment by tellison** [comment]
@karianna that was with my personal account as I figure out whether it works well.  Will report back here with a suggestion to use or not once I've tried it.

**Comment by tellison** [comment]
Seems good.  @karianna is signing us up as a "Premium" subscriber so that we can archive the historical chat and have a custom domain URL (slackarchive.adoptopenjdk.net).

Closing this as done, feel free to reopen if further tasks exist.
