### ISSUE TITLE
Make it easy to add extra flags at makejdk

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#121]
We should be able to pass any extra configure args trivially 

See http://mail.openjdk.java.net/pipermail/distro-pkg-dev/2015-June/032392.html which mentions -with-extra-cflags, --with-extra-cxxflags and --with-extra-ldflags

I shouldn't need to modify sbin/build.sh in order to add extra configure args

something like makejdk-any-platform.sh -copts <extra arguments and values here>

**Comment by gdams** [comment]
I think that `export CONFIGURE_ARGS_FOR_ANY_PLATFORM=""` already does this

**Comment by gdams** [comment]
added that var to the manpage https://github.com/AdoptOpenJDK/openjdk-build/pull/125

**Comment by neomatrix369** [comment]
@gdams thanks for picking that up - i think documenting this would mean less or no queries in this area

**Comment by neomatrix369** [comment]
`makejdk-any-platform.sh` has hard-coded flags for the various platforms as we (on advise from @tellison) wanted to be able to have one and only one way to build the OpenJDK either local machine or CI system for any specific platform which always worked for everyone - we should continue this. For special cases if users wish to still override those flags, they can now with the help of the documentation very well do that.

**Comment by karianna** [comment]
I guess we could make it easier for users to add flags as long as our Jenkins build doesn't change.  @tellison thoughts?

**Comment by sxa555** [comment]
I believe https://github.com/AdoptOpenJDK/openjdk-build/commit/74bdae78bacc9472d7c1a9879da1a9ef21b61854 addressed this with a new `-ca``parameter, therefore closing
