### ISSUE TITLE
Docker builds failing on MacOS

### ISSUE THREAD

**Issue by kittylyst** [AdoptOpenJDK/openjdk-build#1216]
**Platform:** MacOS 10.14.6

**Architecture:** x64

**Related:** 1073

The command:

```
./makejdk-any-platform.sh --docker jdk8u
```
fails out of the box.

Adding --debug-docker and --ssh

causes the Docker container to start, but the build command now fails.

Setting:

```
build@cc958f466f61:/openjdk/build$ JAVA_HOME=/usr/lib/jvm/zulu-7-amd64/jre
build@cc958f466f61:/openjdk/build$ export JAVA_HOME
build@cc958f466f61:/openjdk/build$ java -version
openjdk version "1.7.0_232"
OpenJDK Runtime Environment (Zulu 7.31.0.5-CA-linux64) (build 1.7.0_232-b6)
OpenJDK 64-Bit Server VM (Zulu 7.31.0.5-CA-linux64) (build 24.232-b6, mixed mode)
```

enables the build to find a JVM, but this still fails:

```
build@cc958f466f61:/openjdk/build$ /openjdk/sbin/build.sh
/openjdk/sbin/common/common.sh: line 55: name: unbound variable
Running gradle with /usr/lib/jvm/zulu-7-amd64/jre
bash: ./gradlew: No such file or directory
```

**Comment by johnoliver** [comment]
this is probably because the pipelines directory required at https://github.com/AdoptOpenJDK/openjdk-build/blob/fd939c142a0370cda48eebca9f5dee9d22f0dfc1/sbin/build.sh#L46 is not brought into the docker container

**Comment by sxa555** [comment]
@willsparker Perhaps we could include the testing of builds in docker as part of the playbook testing too
