### ISSUE TITLE
Configure: always cites a JDK_BOOT_DIR problem

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#122]
Even if the problem is a missing C++ compiler, we still get the JDK_BOOT_DIR problem - only seeing this on AIX so far

**Comment by gdams** [comment]
this applies to all platforms

**Comment by gdams** [comment]
here is the code https://github.com/AdoptOpenJDK/openjdk-build/blob/3a4c61c119fae1d770e4149969832638e3465a3e/sbin/build.sh#L172-L177
