### ISSUE TITLE
d2d1.dll missing in windows JDK11 build for Docker Container

### ISSUE THREAD

**Issue by gamma** [AdoptOpenJDK/openjdk-build#1220]
**Platform:**

Windows Server 2019 / 1809 with Dockerized environment

**Architecture:**

x64

The JDK11 provides several .dll files it relies on. The d2d1.dll library is not one of them and it seems that the windowservercore images do not include them (anymore).

Without this library the awt.dll does not work - which is still needed for certain headless operations.

See also: https://github.com/ojdkbuild/ojdkbuild/issues/88

**Comment by karianna** [comment]
Not sure if this belongs here or in the Docker repo but let's see.

**Comment by gamma** [comment]
It looks like an upstream bug at https://bugs.openjdk.java.net/browse/JDK-8229800
