### ISSUE TITLE
Freemarker 2.3.28 is not longer at mirrorservice.org

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1227]
Happening on macos, ppc64le and maybe other builds.
 https://www.mirrorservice.org/sites/ftp.apache.org/freemarker/engine/2.3.28/binaries/apache-freemarker-2.3.28-bin.tar.gz no longer exists (the `2.3.28` directory is not there) but  https://www.mirrorservice.org/sites/ftp.apache.org/freemarker/engine/2.3.29/binaries/apache-freemarker-2.3.29-bin.tar.gz is available

Some release notes are at https://freemarker.apache.org/docs/versions_2_3_29.html

Options would appear to be:
1. Switch to 2.3.29
2. Use our own hosted copy of 2.3.28
3. Use a mirror that hosts older versions

**Comment by sxa555** [comment]
Kicked off new JDK13 pipeline https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk13-pipeline/46/

**Comment by sxa555** [comment]
@andrew-m-leonard https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-mac-x64-openj9/47/console appears to have broken - can you look at why that might be please?

**Comment by karianna** [comment]
> @andrew-m-leonard https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-mac-x64-openj9/47/console appears to have broken - can you look at why that might be please?

Looks like the echo code was copied from another function that uses the ${url} parameter (but this function doesn't).

I think removing ${url} from line 201 would allow this to continue

**Comment by sxa555** [comment]
Now working after the latest PR has been merged.
