### ISSUE TITLE
Pipeline build failure on macos jdk13 mac-x86-openj9

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-build#1231]
Nightly build failed after the freemarker/checksum patch
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-mac-x64-openj9/50/
Checking the console logs there was no error thrown, the process just terminated for some reason, thought I should raise an issue about it. Was a problem before build 45 as well, before the freemarker issues.

**Comment by adam-thorpe** [comment]
Built last night, will close and keep an eye on it

**Comment by adam-thorpe** [comment]
Failed again last night with the same issue, seems to be an intermittent problem

**Comment by adam-thorpe** [comment]
Ran the make-adopt-build-farm.sh script locally on my mac with the same environment variables and got past the failing section.
Seems to get stuck somewhere here
```
echo "NOTE: This can take quite some time!  Please be patient"
    git fetch -q --tags ${BUILD_CONFIG[SHALLOW_CLONE_OPTION]}
    local openJdkVersion=$(getOpenJdkVersion)
    if [[ "${openJdkVersion}" == "" ]] ; then
     # shellcheck disable=SC2154
     echo "Unable to detect git tag, exiting..."
     exit 1
    else
     echo "OpenJDK repo tag is $openJdkVersion"
    fi
```

**Comment by karianna** [comment]
I think you'll need to take the `-q` to see what's going on.

**Comment by adam-thorpe** [comment]
Passing builds (and my local):
```
checking for ZLIB... no
checking for gzsetparams in -lz... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
```

Failing builds:
`checking for ZLIB... yes`

**Comment by sxa555** [comment]
@adam-thorpe It looks like this has succeeded on build-macstadium-macos1012-1 recently as https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk13u/job/jdk13u-mac-x64-openj9/114/consoleFull was run on  there. The `-2` machine is no longer available to us now, so luckily it's now fixed. Are you in agreement (Last night's build failed but that's a general issue not specific to this machine or issue)

**Comment by adam-thorpe** [comment]
Yes this issue was probably fixed at some point so I'll close this now, and I'll have a brief look through some of my older issues if there are any more that need closing.
