### ISSUE TITLE
Add Java Mission Control to the Build Farm

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#1233]
See https://github.com/AdoptOpenJDK/TSC/issues/98

- [x] Build JMC Core
- [x] Test JMC Core
- [ ] Deploy JMC core to Artifcatory / Maven Central

- [ ] Create Eclipse Update site for JMC? Maybe artifactory?
- [ ] Deploy JMC eclipse plugin to eclipse update site

- [ ] Convert all of this to a proper Jenkins pipeline

**Comment by karianna** [comment]
Note to self - once we install maven as a proper ansible dependency then clean up:

```
* lrwxrwxrwx   1 root    root          51 Aug 21 20:28 mvn -> /home/jenkins/maven_temp/apache-maven-3.6.1/bin/mvn
* /home/jenkins/maven_temp
```

**Comment by sxa555** [comment]
Moving this to January but us there a status update/outlook on this one that we can add to the issue?

**Comment by sxa555** [comment]
Question on ETA was asked today in slack: https://adoptopenjdk.slack.com/archives/C09NLQQAV/p1583182831069800

**Comment by aahlenst** [comment]
Superseded by #2037.
