### ISSUE TITLE
Signing failures on some (Windows) builds

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1235]
The `sign_build` job is showing intermittent failures that's breaking the nightly pipelines. Since this has been a problem two nights in a row it's not just a one off failure to connect to the timestamp server.

https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/

Creating this issue to log instances of failures to understand the scope of the problem:

https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/4876/ (Windows, JDK11, Aug21)
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/4877/ (Windows, JDK11, Aug21)
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/4878/ (Windows, JDK11, Aug21)
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/sign_build/4890/ (Windows, JDK13, Aug22)

**Comment by sxa555** [comment]
Running https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/561/console to see if it happens again with most of the windows jobs

**Comment by karianna** [comment]
> Running https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/561/console to see if it happens again with most of the windows jobs

Looks like they all passed.  and the previously failed links have all rolled over so will have to close this for now and look when it happens again.

**Comment by M-Davies** [comment]
JDK11-windows pipeline broke with signing failure last night. Maybe an intermittent issue since builds have been passing since #1425 was merged. Will see if it happens again tomorrow

**Comment by sxa555** [comment]
Do you mean the win32 one? That's a different error from any I've seen before although hopefully a one-off:

```
Error information: "SignerTimeStamp() failed." (-2147012894/0x80072ee2)
SignTool Error: An unexpected internal error has occurred.
Build step 'Execute shell' marked build as failure
```

**Comment by M-Davies** [comment]
I'm referring to this one https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/426/

If that's the same build you're looking at, I can't see that error message

**Comment by M-Davies** [comment]
Signing build passed last night
