### ISSUE TITLE
Multiple windows build failures

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1236]
Various windows builds failing on git errors e.g.
```
Resetting the git openjdk source repository at /tmp/openjdk-jdk8u-windows-x86-32-hotspot/workspace/build/src in 10 seconds...
Pulling latest changes from git openjdk source repository
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/370/console ([azure-2](https://ci.adoptopenjdk.net/computer/build-azure-win2008r2-x64-2/))
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/361/console ([azure-1](https://ci.adoptopenjdk.net/computer/build-azure-win2008r2-x64-1/))

**Comment by sxa555** [comment]
I've cleared out the workspaces on those machines (Well renamed `jdk8u` to a directory referncing this issue number) and re-running the JDK8u jobs at https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/679/

**Comment by sxa555** [comment]
Seems to be working now in the latest pipeline - closing.

**Comment by M-Davies** [comment]
@sxa555 This has popped up again on [build-azure-win2008r2-x64-2](https://ci.adoptopenjdk.net/computer/build-azure-win2008r2-x64-2/)
