### ISSUE TITLE
Contribute "Downstream Jobs Status" add-on to build pipeline job summary

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1237]
Internal OpenJ9 jenkins CI has a very useful home built plugin to display downstream job status summary within the top-level pipeline job summary. I would like to contribute this to Adopt and implement it in the jdknn-pipline job summaries. This will mean we will very easily be able to see the downstream build & test individual job statuses for your individual build.
See attached screenshot example:
![Screenshot 2019-08-21 at 15 45 12](https://user-images.githubusercontent.com/31470007/63523145-7a540580-c4f1-11e9-88a6-98af74c92d18.png)

**Comment by AdamBrousseau** [comment]
It's external too :)
https://ci.eclipse.org/openj9/job/Pipeline-Build-Test-All/618/

**Comment by karianna** [comment]
Sounds good to me - do you have permissions to build the plugin or a place I can install it from?

**Comment by andrew-m-leonard** [comment]
Following discussions on slack with @smlambert , she's made us aware that trss already has a similar feature, "Grid" view here: https://trss.adoptopenjdk.net/tests/Test
Probably best to use/support the trss option for the moment and see how we get on rather than re-invent...
