### ISSUE TITLE
Still having issue with hardened runtime

### ISSUE THREAD

**Issue by MoxxiManagarm** [AdoptOpenJDK/openjdk-build#1241]
**Platform:**
MacOs Mojave 10.14.5

**Architecture:**

I loaded the newest JDK 11.0.4 +11.4 in hope to finally get my notarization issues resolved.
(also tested with +11.2 and found the same)

Signing the files:
`find ${JDK_DIR} -type f -exec codesign --deep --force --timestamp --options runtime --strict --entitlements "${ENTITLEMENTS_DIR}" --sign "${CERT_DEV_ID_APPLICATION}" '{}' \;`

I also checked the installed App, the entitlements are there.
`codesign --display --entitlements :- MyApp.App`

But still when I try to run the Application it fails with 
`Error occurred during initialization of VM
Could not reserve enough space in CodeHeap 'non-nmethods' (2496K)`

I also checked entitlements directly on bin/java, also entitlements are successfully attached.

Entitlements file:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.security.cs.allow-jit</key>
        <true/>
        <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
        <true/>
        <key>com.apple.security.cs.disable-executable-page-protection</key>
        <true/>
        <key>com.apple.security.cs.disable-library-validation</key>
        <true/>
        <key>com.apple.security.cs.allow-dyld-environment-variables</key>
        <true/>
    </dict>
</plist>
```

**Comment by sxa555** [comment]
Notarization / signing so tagging the main issue for this: https://github.com/AdoptOpenJDK/openjdk-build/issues/1130

**Comment by sxa555** [comment]
@MoxxiManagarm can you verify whether the latest nightly JDK11 builds resolve this please?
https://adoptopenjdk.net/nightly.html?variant=openjdk11

**Comment by MoxxiManagarm** [comment]
@sxa555 Ok I will try

**Comment by MoxxiManagarm** [comment]
@sxa555 At least the application is starting now with hardened runtime enabled, the heapspace error does not occure. The functionality will now be tested. Is there any timeline at which time the features of the nightly build will be released?

**Comment by sxa555** [comment]
I'll close this on the basis that it is successfully working in the nightlies. I would hope we'll get it working by the next quarterly release, but I'm not the person working on getting it working so I can't say more than that - as mentioned before #1130 is the place for discussion on it going forwards :-)
