### ISSUE TITLE
Enable dtrace support

### ISSUE THREAD

**Issue by sauliusvl** [AdoptOpenJDK/openjdk-build#1242]
Currently OpenJDK is built without `dtrace` support since `--enable-dtrace=auto` and `systemtap` is not installed in the build farm.

Without it JVM flags such as `-XX:+DTraceAllocProbes`, `-XX:+DTraceMonitorProbes` etc. do not work and using tools such as [grav](https://github.com/epickrram/grav) is not possible.

Other OpenJDK distributions seem to enable it by default (e.g. CentOS, [Fedora](http://blogs.microsoft.co.il/sasha/2016/03/31/probing-the-jvm-with-bpfbcc/)), as it shouldn't have any performance impact unless the `DTrace*Probes` flags are enabled. In terms of binary size, enabling it added an extra megabyte to the final tarball on my laptop (a 0.5% increase).

I'd be welcome to submit a PR for this.

**Comment by henrik242** [comment]
Sounds sane. You'd probably get more traction if you submit a PR?

**Comment by sxa555** [comment]
Would also need modifications to the ansible playbooks in the infrastructure repositories to install the appropriate `systemtap` packages

**Comment by sauliusvl** [comment]
I think these two PRs should be enough, unless I'm missing something?

**Comment by karianna** [comment]
> I think these two PRs should be enough, unless I'm missing something?

I think the `--enable-dtrace=auto` parameter needs to be added to our build farm scripts?

**Comment by sauliusvl** [comment]
> I think the `--enable-dtrace=auto` parameter needs to be added to our build farm scripts?

My understanding is that this is the default value and it should be enabled once the dependencies are installed? (https://github.com/AdoptOpenJDK/openjdk-jdk/blob/master/make/autoconf/hotspot.m4#L157)

Of course specifying it explicitly might be nicer, where would be the best place to do it?

**Comment by karianna** [comment]
> > I think the `--enable-dtrace=auto` parameter needs to be added to our build farm scripts?
> 
> My understanding is that this is the default value and it should be enabled once the dependencies are installed? (https://github.com/AdoptOpenJDK/openjdk-jdk/blob/master/make/autoconf/hotspot.m4#L157)
> 
> Of course specifying it explicitly might be nicer, where would be the best place to do it?

The makejdk-any-platform shell script is the likely place to put it, thanks!

**Comment by sxa555** [comment]
Autodetection is working :-) https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-hotspot/302/console has picked up `/usr/bin/dtrace` on  a machine that has the `sdt` package installed

**Comment by sxa555** [comment]
I suspect if we want to ensure it's always included in the adoptopenjdk builds we should set `--enable-dtrace=yes` somewhere in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/linux.sh

**Comment by sauliusvl** [comment]
great! I've added an explicit `auto` configuration setting here: https://github.com/AdoptOpenJDK/openjdk-build/pull/1244/commits/46604aabee8180b6b9fb342286ddfa0724732f7b, but if you know a better place to set it to `yes`, I can change it - I'm not exactly sure what configurations work, i.e. what about mac/OpenJ9?

**Comment by sxa555** [comment]
I suspect macos would work ok but i haven't tried it. OpenJ9 should tolerate the option but I don't believe there are any trace points within the JVM that will benefit from it over and above whatever base OpenJDK points are in there.

**Comment by sxa555** [comment]
Enabled under https://github.com/AdoptOpenJDK/openjdk-build/pull/1244 https://github.com/AdoptOpenJDK/openjdk-build/pull/1273 - should be good now (excluding JDK8) Hopefully it works as I've not explicitly tested it other than checking the options seem to be getting added :-) Any problems with the enabling, feel free to reopen!

**Comment by sauliusvl** [comment]
> Enabled under #1244 #1273 - should be good now (excluding JDK8) Hopefully it works as I've not explicitly tested it other than checking the options seem to be getting added :-) Any problems with the enabling, feel free to reopen!

It does work!
```bash
$ ./bin/java -version
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+7-201909121809)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+7-201909121809, mixed mode)

$ readelf -n lib/server/libjvm.so | head -n 18

Displaying notes found in: .note.gnu.build-id
  Owner                 Data size	Description
  GNU                  0x00000014	NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: d2410e6fcefa58d38c333ba230feafe2d77b5c7e

Displaying notes found in: .note.stapsdt
  Owner                 Data size	Description
  stapsdt              0x00000050	NT_STAPSDT (SystemTap probe descriptors)
    Provider: hotspot
    Name: class__loaded
    Location: 0x00000000005df25f, Base: 0x0000000000f67c18, Semaphore: 0x0000000000000
    Arguments: 8@%rdx -4@%eax 8@152(%rdi) 1@%sil
  stapsdt              0x00000050	NT_STAPSDT (SystemTap probe descriptors)
    Provider: hotspot
    Name: class__unloaded
    Location: 0x00000000005df678, Base: 0x0000000000f67c18, Semaphore: 0x0000000000000
    Arguments: 8@%rdx -4@%eax 8@152(%r12) 1@$0
```

Thanks for making this possible!
