### ISSUE TITLE
Aix ppc64 hotspot/openj9 jdk8 build failure at Adopt

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-build#1247]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/

Failing since 421. Seems to have problems compiling the String class, consistent on both hotspot and openj9.
Part error :
```
## Starting corba
Compiling 6 files for BUILD_LOGUTIL
/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-hotspot/workspace/build/src/corba/src/share/classes/com/sun/tools/corba/se/logutil/IndentingPrintWriter.java:35: error: cannot access Object
public class IndentingPrintWriter extends PrintWriter {
       ^
  class file for java.lang.Object not found
/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-hotspot/workspace/build/src/corba/src/share/classes/com/sun/tools/corba/se/logutil/IndentingPrintWriter.java:38: error: cannot find symbol
    private String indentString = "" ;
            ^
  symbol:   class String
  location: class IndentingPrintWriter
/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-aix-ppc64-hotspot/workspace/build/src/corba/src/share/classes/com/sun/tools/corba/se/logutil/IndentingPrintWriter.java:40: error: cannot find symbol
    public void printMsg( String msg, Object... data )
                          ^
  symbol:   class String
```

**Comment by karianna** [comment]
adamfarley  I did some googling, and had a theory.
28m
adamfarley  This one passed, using what appears to be an OpenJDK 7 Hotspot build:
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/350/consoleFull
27m
adamfarley  This one failed, using an IBM Java 8 build:
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/351/consoleFull
27m
adamfarley  Some folks on a forum once complained about this issue being present in the IBM Java 8 build at some point.
27m
adamfarley  Perhaps building with IBM Java 8 could be related to this issue?
26m
adamfarley  Not sure why we're building with an IBM build tbh. Any clue why that is?
18m
adamfarley  I can't tell what machine they're running on, as both claim to be running on "Jenkins" (master).
Also, here's the boot JDK path for both.
Passed:
--with-boot-jdk=/home/bootjdk/j2sdk-image/
Failed:
--with-boot-jdk=/usr/java8_64
So the next question: Who changed that and why? (edited)
17m
martijnverburg  that seem odd to me as well (using Openj9)
16m
adamfarley  It has "IBM" in the version string. Thought that'd been removed from OpenJ9.
11m
adamfarley  Yeah, here's the version from a recent OpenJ9 build:
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-201908300342-b03)
Eclipse OpenJ9 VM (build master-c49db014e, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190830_401 (JIT enabled, AOT enabled)
OpenJ9   - c49db014e
OMR      - 5628a974
JCL      - efd729851b based on jdk8u232-b03)
And here's the boot JDK that's in the failed AIX build:
java version "1.8.0_211" Java(TM) SE Runtime Environment (build 8.0.5.37 - pap6480sr5fp37-20190618_01(SR5 FP37)) IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20190617_419755 (JIT enabled, AOT enabled) OpenJ9   - 354b31d OMR      - 0437c69 IBM      - 4972efe) JCL - 20190606_01 based on Oracle jdk8u211-b25 
10m
adamfarley  Looks like, for reasons strange and confusing, we're now trying to build AIX builds at adopt by using an IBM Java 8 build.
Not OpenJDK 8 on OpenJ9.
<1m

**Comment by sxa555** [comment]
Ref the user of IBM JDK Shouldn't make any difference to be fair, but it predated having an adopt 8 build I believe. @William Parker  changed the playbooks last week to install an adopt 8 boot JDK on AIX instead of the IBM one but that won't replace an existing one on the machines. I'm more surprised it's not using the IBM JDK7 to bootstrap 8 to be honest as the playbooks do install that where it can

**Comment by adam-thorpe** [comment]
Hotspot build is now using openjdk version "1.7.0-internal" and is stable, openj9 is still using IBM J9 VM

**Comment by adam-thorpe** [comment]
Builds seem stable
