### ISSUE TITLE
Aix ppc64 hotspot jdk11 build failure at Adopt

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-build#1248]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/286/

Build seems really inconsistent with new problems every day.
Latest error:
```
Building targets 'product-images legacy-jre-image test-image' in configuration 'aix-ppc64-normal-server-release'
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
Compiling 2 files for BUILD_JVMTI_TOOLS
Creating hotspot/variant-server/tools/adlc/adlc from 13 file(s)
Compiling 1 files for BUILD_JFR_TOOLS
/opt/freeware/bin/bash: fork: retry: Resource temporarily unavailable
/opt/freeware/bin/bash: fork: retry: No child processes
```
```
* For target hotspot_variant-server_tools_adlc_objs_arena.o:
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-222 (S) cannot fork process - Resource temporarily unavailable
* For target hotspot_variant-server_tools_adlc_objs_forms.o:
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-222 (S) cannot fork process - Resource temporarily unavailable
* For target hotspot_variant-server_tools_adlc_objs_formsopt.o:
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-222 (S) cannot fork process - Resource temporarily unavailable
* For target hotspot_variant-server_tools_adlc_objs_main.o:
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-222 (S) cannot fork process - Resource temporarily unavailable
* For target hotspot_variant-server_tools_adlc_objs_output_h.o:
/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-222 (S) cannot fork process - Resource temporarily unavailable
```

**Comment by sxa555** [comment]
No obvious processes chewing up resources on that machine so unclear what the problem is - rerunning at https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot/287/

**Comment by sxa555** [comment]
Same failure in 287 - reason unclear

**Comment by karianna** [comment]
adamfarley  I did some googling, and had a theory.
28m
adamfarley  This one passed, using what appears to be an OpenJDK 7 Hotspot build:
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/350/consoleFull
27m
adamfarley  This one failed, using an IBM Java 8 build:
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-hotspot/351/consoleFull
27m
adamfarley  Some folks on a forum once complained about this issue being present in the IBM Java 8 build at some point.
27m
adamfarley  Perhaps building with IBM Java 8 could be related to this issue?
26m
adamfarley  Not sure why we're building with an IBM build tbh. Any clue why that is?
18m
adamfarley  I can't tell what machine they're running on, as both claim to be running on "Jenkins" (master).
Also, here's the boot JDK path for both.
Passed:
--with-boot-jdk=/home/bootjdk/j2sdk-image/
Failed:
--with-boot-jdk=/usr/java8_64
So the next question: Who changed that and why? (edited)
17m
martijnverburg  that seem odd to me as well (using Openj9)
16m
adamfarley  It has "IBM" in the version string. Thought that'd been removed from OpenJ9.
11m
adamfarley  Yeah, here's the version from a recent OpenJ9 build:
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-201908300342-b03)
Eclipse OpenJ9 VM (build master-c49db014e, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190830_401 (JIT enabled, AOT enabled)
OpenJ9   - c49db014e
OMR      - 5628a974
JCL      - efd729851b based on jdk8u232-b03)
And here's the boot JDK that's in the failed AIX build:
java version "1.8.0_211" Java(TM) SE Runtime Environment (build 8.0.5.37 - pap6480sr5fp37-20190618_01(SR5 FP37)) IBM J9 VM (build 2.9, JRE 1.8.0 AIX ppc64-64-Bit Compressed References 20190617_419755 (JIT enabled, AOT enabled) OpenJ9   - 354b31d OMR      - 0437c69 IBM      - 4972efe) JCL - 20190606_01 based on Oracle jdk8u211-b25 
10m
adamfarley  Looks like, for reasons strange and confusing, we're now trying to build AIX builds at adopt by using an IBM Java 8 build.
Not OpenJDK 8 on OpenJ9.
<1m

**Comment by M-Davies** [comment]
This problem has popped up again in the nightlies (same pipeline). I took a look at the nightlies since 01/12/2019...
- Machine `build-osuosl-ppc64-aix-71-2` has been failing with `/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-222 (S) cannot fork process - Resource temporarily unavailable` (last passing build on this machine was 01/12/2019)
- Machine `test-osuosl-ppc64-aix-71-1` has been passing without this error several times during this period 
- See https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/

There are a few significant details between these two machines that might be causing this:
- Boot JDK's differ (1.8.0 on failing machine vs 1.7.0 on passing machine).
- Xlc is setup using Java 6 on the failing machine (Java 7 on the passing one)
```
Building up the configure command...
no ccache in /opt/freeware/bin /bin /usr/local/bin /opt/IBM/xlC/13.1.3/bin /opt/IBM/xlc/13.1.3/bin /opt/freeware/bin /usr/local/bin /opt/IBM/xlC/13.1.3/bin /opt/IBM/xlc/13.1.3/bin /usr/bin /etc /usr/sbin /usr/ucb /usr/bin/X11 /sbin /usr/java6/jre/bin /usr/java6/bin
```
- Aix version 7.1.0 on failing machine (7.2.0 on passing)
- `checking for number of cores... 20` on failing machine (80 on passing)
- Bash version is also different but I doubt this makes a difference in this case

@sxa555 @karianna anything here that could be causing the problem?

**Comment by karianna** [comment]
> This problem has popped up again in the nightlies (same pipeline). I took a look at the nightlies since 01/12/2019...
> 
> * Machine `build-osuosl-ppc64-aix-71-2` has been failing with `/opt/IBM/xlC/13.1.3/bin/.orig/xlC_r: 1501-222 (S) cannot fork process - Resource temporarily unavailable` (last passing build on this machine was 01/12/2019)
> * Machine `test-osuosl-ppc64-aix-71-1` has been passing without this error several times during this period
> * See https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/
> 
> There are a few significant details between these two machines that might be causing this:
> 
> * Boot JDK's differ (1.8.0 on failing machine vs 1.7.0 on passing machine).
> * Xlc is setup using Java 6 on the failing machine (Java 7 on the passing one)
> 
> ```
> Building up the configure command...
> no ccache in /opt/freeware/bin /bin /usr/local/bin /opt/IBM/xlC/13.1.3/bin /opt/IBM/xlc/13.1.3/bin /opt/freeware/bin /usr/local/bin /opt/IBM/xlC/13.1.3/bin /opt/IBM/xlc/13.1.3/bin /usr/bin /etc /usr/sbin /usr/ucb /usr/bin/X11 /sbin /usr/java6/jre/bin /usr/java6/bin
> ```
> 
> * Aix version 7.1.0 on failing machine (7.2.0 on passing)
> * `checking for number of cores... 20` on failing machine (80 on passing)
> * Bash version is also different but I doubt this makes a difference in this case
> 
> @sxa555 @karianna anything here that could be causing the problem?

That is quite a difference between the hosts. I think @sxa555 has since corrected this.

**Comment by sxa555** [comment]
The AIX 7.2 host is no longer in use for building. That was the machine with XLC16, and has been replaced by [build-ibm-ppc64-aix-71-1](https://ci.adoptopenjdk.net/computer/build-ibm-ppc64-aix-71-1/)

If there are any further issues, please raise another issue. If we get the `fork` error please capture instances in #1450 

I will have to check the boot JDK thing though as it should always be JDK7 for JDK8 builds
