### ISSUE TITLE
TLS 1.3 support for Java 8

### ISSUE THREAD

**Issue by benji** [AdoptOpenJDK/openjdk-build#1254]
Oracle released support for TLS 1.3 in Java 11 only: http://openjdk.java.net/jeps/332

Some JDK distributions like Azul have TLS 1.3 support:
https://www.azul.com/press_release/azul-systems-brings-updated-transport-layer-security-to-java-se-8/

Maybe this project maintained by Azul Systems can be used: https://github.com/openjsse/openjsse
Maven: https://search.maven.org/search?q=g:org.openjsse

**Comment by benji** [comment]
To add support using Azul's OpenJSSE lib:

1) include the openjsse jar in the classpath

2) add the OpenJSSE provider to java.security (first position):
```
security.provider.1=org.openjsse.net.ssl.OpenJSSE
...
```

**Comment by PeterLenahan** [comment]
According to this page:   https://java.com/en/jre-jdk-cryptoroadmap.html 
Java 8 now supports TLS v1.3 


2020-07-14 | 8u261 b12 | TLS 1.3 | Added support for TLS 1.3

**Comment by aahlenst** [comment]
That's about Oracle JDK. Reading https://bugs.openjdk.java.net/browse/JDK-8245466, the backport is proposed at OpenJDK but not yet implemented. But maybe I'm missing something.

**Comment by aahlenst** [comment]
TLS 1.3 should have landed in 8u and is targeted for release in October:
https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-August/012568.html

It should appear in one of the next nightly builds if it hasn't already.

**Comment by IEnoobong** [comment]
Hi @aahlenst running 
```java
public static void main(String[] args) throws NoSuchAlgorithmException, KeyManagementException {
        SSLContext context = SSLContext.getInstance("TLS");
        context.init(null, null, null);
        String[] supportedProtocols = context.getDefaultSSLParameters().getProtocols();
        System.out.println(Arrays.toString(supportedProtocols));
    }
```
Prints, `[TLSv1.2, TLSv1.1, TLSv1]`

But my Java version should have TLSv1.3, any ideas what's wrong please?

```
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.282-b08, mixed mode)

```
