### ISSUE TITLE
CPU usage of raspberry PI is too high in the Linux arm32 Platform 

### ISSUE THREAD

**Issue by Ankitdpatel071** [AdoptOpenJDK/openjdk-build#1257]
**Platform:Linux arm32 (OpenJDK 8 (LTS))**

**Raspberry pi: **

I used the "OpenJDK8U-jre_arm_linux_hotspot_8u222b10" package in the raspberry pi.
However, CPU usage has become high for Java application which are using the adoptopenjdk 8 (Linux arm32).

Please let me know a solution.

**Comment by sxa555** [comment]
What do you consider to be "too high"? Is this compared to another JVM? Another type of computer? Which application?

**Comment by sxa555** [comment]
That JVM is built without a JIT so is running in interpreted mode, which will be slow

**Comment by Ankitdpatel071** [comment]
Thank you for your reply.

I compare CPU usage with Oracle Java.
Please refer the following detail.
Using Oracle 8 Java: CPU usage around 10%
Using Adoptopenjdk 8 Java: CPU usage around 40%

Both above tested in the Raspberry pi 3+.
Please let me know a solution.

**Comment by sxa555** [comment]
I think this is a result of the builds coming from the main openjdk8 codebase and not the alternate repository which contains the full aarch32 support. We should address this. I've for a test build including a working client VM if you want to try it for now though

**Comment by sxa555** [comment]
I'm not gonig to keep it in this location long term, and it's totally unsupported/untested etc. but you can grab it from https://ci.adoptopenjdk.net/userContent/arm32.tmp/jre8u-arm32.tgz (Image is a bit bigger than the normal one but it'll suffice for testing!)

**Comment by sxa555** [comment]
aarch32 build from the new repository is failing due to a missing `hotspot/src/cpu/aarch32/vm/aarch32.ad`

https://adoptopenjdk.slack.com/archives/C51GP8337/p1570807421001700

**Comment by sxa555** [comment]
@jerboaa Do you know anything about this? The files exist in the JDK9 repo at https://hg.openjdk.java.net/aarch32-port/jdk9u/hotspot/file/e11b6a559b8d/src/cpu/aarch32/vm but seemingly not in the jdk8u one we have mirrored. Do you know of any trick to let this codebase build?

**Comment by jerboaa** [comment]
@sxa555 So you've got the right mirror it appears. But what makes you think that aarch32 JIT build actually needs an `aarch32.ad` file. From what I see from the fedora build, that is not needed. In fact, the fedora sources don't have an `aarch32.ad` file either yet build fine:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1409553

Could this be an issue with AdoptOpenJDK build scripts making a wrong assumption somewhere? Are you building with `--with-jvm-variants=client`?

**Comment by andrew-m-leonard** [comment]
@jerboaa pretty sure when I built this I didn't use --with-jvm-variants=client  ! not sure I really know what that means....! but I guess it's probably the reason for the build failure

**Comment by jocull** [comment]
> If I'm not mistaken aarch32 is C1 only (no C2 JIT compiler)

How can you tell any of these things from a JDK on your system? For example AdoptOpenJDK 13 ARMHF

I noticed using `jstat` uses 100% of a single core, and that's how I wound up here.

**Comment by jocull** [comment]
> That JVM is built without a JIT so is running in interpreted mode, which will be slow

I'm confused - this is a "Hotspot" VM and is installed as `adoptopenjdk-8-hotspot-armhf`.

But the version reports this, which backs up the claim that it doesn't have hotspot compilation support at all.

```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK Zero VM (AdoptOpenJDK)(build 25.232-b09, interpreted mode)
```

What am I missing?

**Comment by aahlenst** [comment]
@jocull That the package generator does not verify what it is being fed. You could pass it a build with OpenJ9 and it would happily produce a package that has HotSpot in its name.

**Comment by JakubVanek** [comment]
> > If I'm not mistaken aarch32 is C1 only (no C2 JIT compiler)
> 
> How can you tell any of these things from a JDK on your system? For example AdoptOpenJDK 13 ARMHF
> 
> I noticed using `jstat` uses 100% of a single core, and that's how I wound up here.

100% CPU usage might be related to this: https://github.com/AdoptOpenJDK/openjdk-build/issues/1287
