### ISSUE TITLE
Should be an easy way to "clean up" a development environment

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#126]
While `make clean` will remove artifacts from a build process, our scripts may be downloading and installing a variety of dependencies (e.g. Freetype)

We should provide a simple way to have a fresh environment without cloning the entire repository again. It would remove any existing dependencies that were brought in and built as part of our scripts.

Case in point, I copied the contents of my working directory (called "mybackup") to a colleague's to work on
```
/freetype-2.4.0/objs/type42.lo:# /ramdisk0/mybackup/adam-openjdk-build/freetype-2.4.0/objs/type42.lo - a libtool object file
```

May well be other references to things on my path too that a "clean" script should deal with to prevent path conflicts

**Comment by a-roberts** [comment]
Note that as we are pulling in and building freetype, for now it may simply be a case of calling `make clean` on the freetype source folder as well if such a folder exists

**Comment by karianna** [comment]
Jenkins has a cleanWorkspace option and local builds, you can just remove the `workspace` dir
