### ISSUE TITLE
RPM installation on Centos, RHEL, or Fedora is missing installation step

### ISSUE THREAD

**Issue by frant-hartm** [AdoptOpenJDK/openjdk-build#1262]
The documentation section "RPM installation on Centos, RHEL, or Fedora is missing installation step" is missing 2nd step calling yum, e.g.:

```
yum install adoptopenjdk-8-hotspot
```

https://adoptopenjdk.net/installation.html?variant=openjdk8&jvmVariant=hotspot#x64_linux-jdk

**Comment by sxa555** [comment]
Thanks for reporting this @frant-hartm :-)
