### ISSUE TITLE
Broken JDK8 pipeline builds due to --enable-dtrace

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-build#1269]
Changes made in commit: https://github.com/AdoptOpenJDK/openjdk-build/commit/9e9a5e05b6e7635057a7a88a1358dbb031d1fac7 seem to have broken the JDK8 nightly builds across all platforms eg. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/343/console

```
Running custom generated-configure.sh
configure: error: unrecognized options: --enable-dtrace
configure exiting with result code 1
```

**Comment by sxa555** [comment]
Not specific to openj9 - the macos hotspot builds have the same issue.

Slightly surprised by this as I'd hope the `auto` option would result in it just being disabled on platforms where it wasn't valid
