### ISSUE TITLE
Smarter build process (recognising what's already present)

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#127]
We pull in numerous dependencies e.g. alsa, freetype, and we even clone our repository again just to get cacerts out - every time!

Need to detect for the presence of such folders/files already and not do these steps all over again. Lost track of how many times I've said "oh no, it's configuring and building freetype again!"

**Comment by neomatrix369** [comment]
I'm with you on this, we have already started via PR #117 and there's one more to follow, is it an idea to move some of them to the Ansible scripts so the machine already has them pre-baked. Also running cron jobs that update these dependencies regularly - might be useful to do this.

**Comment by karianna** [comment]
Duplicate of #60
