### ISSUE TITLE
JavaFX runtime inclusion in AdoptOpenJDK 8 LTS?

### ISSUE THREAD

**Issue by JAIMY86** [AdoptOpenJDK/openjdk-build#1270]
Dear Team,

Is there any plan to include Java FX runtime with AdoptOpenJDK 8 LTS release?

If yes, could you please provide possible timeline?

Many thanks for your support.

Regards,
Jaimy

**Comment by karianna** [comment]
At this stage no. OpenJFX for Java 8 is not being actively maintained.  We will improve our instructions on how to do it manually though.
