### ISSUE TITLE
Release older versions of OpenJDK8

### ISSUE THREAD

**Issue by bdw429s** [AdoptOpenJDK/openjdk-build#1276]
Are there any plans still to build older releases of JDK8?  I asked about this early on and I believe the answer was "yes, soon" but it seems that the oldest release on the API is still jdk8u172-b11.  The reason I ask is because a few users of my CLI tool use it to run some very old licensed versions of CF app servers that require Java 8 update 92 or prior to operate.  I realize their needs are edge cases, but I'd like to give an a solid answer about whether my CLI will ever be able to auto-download jdk8_92 or not.

The demand for this is not huge, but I do have some users who would find it handy.  They are aware that they are using old insecure versions of Java but they have no choice while they work to migrate off of older app servers.  

I would also suggest a flag added to the API perhaps that marks builds known to be insecure so that Adopt can have "due diligence" in warning users if they choose to use an older JDK build.

**Comment by karianna** [comment]
Raised on the TSC channel

**Comment by karianna** [comment]
Hi @bdw429s - This did get voted down in terms of us providing one at Adopt, but we are very happy to help you build your own using our scripts.  Please drop the build channel a line next week and we can guide you through it.

**Comment by bdw429s** [comment]
@karianna Thanks for the update.  Like I said on Slack, creating my own personal build is of no use as this functionality is for the users of my CLI tool which pulls OpenJDK versions directly from the AdoptAPI.  If these versions are not available on the Adopt API, then there is no way to access them via my CLI.  I do not build nor host OpenJDK builds for my users.  They are all pulled from the API and from Adopt's binary storage.  Now, my users could potentially build openjdk themselves locally, but what would the point of that be?  It would be less work for them to scour the internet for an old Oracle installer since the convenience of the CLI handling the acquisition of the JDK would already be thrown out the window!

I am disappointed by the decision, but I understand.  I'll let my users know that they will not be able to automate the installation of older JDK8 builds via the Adopt API and will have to manually procure an installer.

**Comment by karianna** [comment]
> @karianna Thanks for the update. Like I said on Slack, creating my own personal build is of no use as this functionality is for the users of my CLI tool which pulls OpenJDK versions directly from the AdoptAPI. If these versions are not available on the Adopt API, then there is no way to access them via my CLI. I do not build nor host OpenJDK builds for my users. They are all pulled from the API and from Adopt's binary storage. Now, my users could potentially build openjdk themselves locally, but what would the point of that be? It would be less work for them to scour the internet for an old Oracle installer since the convenience of the CLI handling the acquisition of the JDK would already be thrown out the window!
> 
> I am disappointed by the decision, but I understand. I'll let my users know that they will not be able to automate the installation of older JDK8 builds via the Adopt API and will have to manually procure an installer.

Hi Brad, thanks for understanding, we're sorry we weren't able to help out this time!
