### ISSUE TITLE
The redirected default printer not return on Citrix Xendekstop and RDP Session

### ISSUE THREAD

**Issue by borsatos** [AdoptOpenJDK/openjdk-build#1277]
**Platform:**
Windows 10 LTSC 2019 and Windows Server 2016/2019

**Architecture:**
x64

**Version:**
openjdk version "1.8.0_222"

Hi support,

the problem occurs in Citrix or RDP session when you set a default printer redirected.

1. Logon to session Citrix or RDP
2. set a local or network default printer
3. run the code "PrintServiceLookupTest".
4. set a redirected default printer
5. run the code "PrintServiceLookupTest".

**Code:**

```
public class PrintServiceLookupTest {
       public static void main(String[] args) {
             javax.print.PrintService service = javax.print.PrintServiceLookup.lookupDefaultPrintService();
             if (service != null) {
                    String printServiceName = service.getName();
                    System.out.println("Stampante di default (" + printServiceName+")");
             } else {
                    System.out.println("Nessuna stampante di default trovata");
             }
       }
}
```

The registry key used for local or network printers is:

HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows\Device

The registry key used for redirect printers is:

HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows\SessionDefaultDevices\ "session" \Device

In these links you can find workarounds, but only until you change your default printer

- https://social.msdn.microsoft.com/Forums/en-US/59199e98-4db0-4a73-90ef-52ba8f072153/default-printer-registry-key-not-set-correctly-on-windows-server-20162019?forum=servervirtualization

- https://social.technet.microsoft.com/Forums/ie/en-US/a56e481e-6bd5-44dc-8873-d2c58e7e1948/bug-hkcu-default-printer-registry-key-isnt-set-properly-in-windows-server-2016?forum=ws2016

- https://discussions.citrix.com/topic/396513-windows-server-2016-and-xenapp-715-cu2-default-printer-registry-key-not-set-when-launching-published-app/

**Comment by karianna** [comment]
@borsatos Is this AdoptOpenJDK 1.8.0_222?  Have you also tried with the adoptopenjdk.net/upstream.thml build?

**Comment by borsatos** [comment]
Hi,

I used OpenJDK8U-jdk_x64_windows_hotspot_8u222b10.

Your link not found (404 Sorry, we can't find that page!) 

Regards

**Comment by karianna** [comment]
OK, I think this needs to be reported upstream - I'll ping a reporter.

**Comment by jerboaa** [comment]
@borsatos upstream builds are here:
https://adoptopenjdk.net/upstream.html

I'm missing expected vs. actual output for a proper bug report in upstream JBS. Please add that info, @borsatos.

**Comment by borsatos** [comment]
Hi jerboaa,

I set default printer "Invia a OneNote 16 (from WKST015)"

*** 
### Afterwards my registry keys:

reg query "HKCU\Software\Microsoft\Windows NT\CurrentVersion\Windows" /s

HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows
    Device    REG_SZ    Microsoft Print to PDF,winspool,Ne02:
    IsMRUEstablished    REG_DWORD    0x1
    LegacyDefaultPrinterMode    REG_DWORD    0x1

HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows\SessionDefaultDevices

HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows\SessionDefaultDevices\S-1-5-5-0-1606469
    Device    REG_SZ    Invia a OneNote 16 (from WKST015),winspool,Ne00:

***
### Afterwards my test

C:\>C:\Java\OpenJDK8U-jre_x64_windows_8u222b10\openjdk-8u222-b10-jre\bin\java.exe -jar C:\Java\PrintServiceLookupTest.jar
**Print Service Default Name is (Microsoft Print to PDF)**
Print Service Name List
Name = Coda_Toshiba on csesrvprint (from WKST015)
Name = Invia a OneNote 16 (from WKST015)
Name = Microsoft Print to PDF (from WKST015)
Name = Send To OneNote 2016 (from WKST015)
Name = Send To OneNote 2016
Name = PDFCreator
Name = Microsoft XPS Document Writer
Name = Microsoft Print to PDF
Name = Fax

C:\>C:\Java\OpenJDK8U-jre_x64_windows_8u232b05_ea\openjdk-8u232-b05-jre\bin\java.exe -jar C:\Java\PrintServiceLookupTest.jar
**Print Service Default Name is (Microsoft Print to PDF)**
Print Service Name List
Name = Coda_Toshiba on csesrvprint (from WKST015)
Name = Invia a OneNote 16 (from WKST015)
Name = Microsoft Print to PDF (from WKST015)
Name = Send To OneNote 2016 (from WKST015)
Name = Send To OneNote 2016
Name = PDFCreator
Name = Microsoft XPS Document Writer
Name = Microsoft Print to PDF
Name = Fax

C:\>C:\Java\OpenJDK11U-jre_x64_windows_11.0.4_11\openjdk-11u-11.0.4_11-jre\bin\java.exe -jar C:\Java\PrintServiceLookupTest.jar
**Print Service Default Name is (Microsoft Print to PDF)**
Print Service Name List
Name = Coda_Toshiba on csesrvprint (from WKST015)
Name = Invia a OneNote 16 (from WKST015)
Name = Microsoft Print to PDF (from WKST015)
Name = Send To OneNote 2016 (from WKST015)
Name = Send To OneNote 2016
Name = PDFCreator
Name = Microsoft XPS Document Writer
Name = Microsoft Print to PDF
Name = Fax

C:\>C:\Java\OpenJDK11U-jre_x64_windows_11.0.5_7_ea\openjdk-11u-11.0.5_7-jre\bin\java.exe -jar C:\Java\PrintServiceLookupTest.jar
**Print Service Default Name is (Microsoft Print to PDF)**
Print Service Name List
Name = Coda_Toshiba on csesrvprint (from WKST015)
Name = Invia a OneNote 16 (from WKST015)
Name = Microsoft Print to PDF (from WKST015)
Name = Send To OneNote 2016 (from WKST015)
Name = Send To OneNote 2016
Name = PDFCreator
Name = Microsoft XPS Document Writer
Name = Microsoft Print to PDF
Name = Fax

***
**The problem still occurs.**

**Comment by jerboaa** [comment]
@borsatos Thanks. It's still not clear to me what the *actual* vs. *expected* behaviour is. I.e. show us what you'd want to happen *and* what actually happens. Ideally via reproducer output.

**Comment by borsatos** [comment]
Hi jerboaa,

I would like the Java function "javax.print.PrintServiceLookup.lookupDefaultPrintService" to report the default printer of my user.

In ICA/RDP session I set redirected printer as default printer but "javax.print.PrintServiceLookup.lookupDefaultPrintService" not return correct printer.

***
if I ask Windows 10 what is my defualt printer, I have this result

PS C:\> Get-WmiObject -Query " SELECT * FROM Win32_Printer" | Where-Object {$_.Default -eq "true"} | Select Name

**Invia a OneNote 16 (from WKST015)**


***
if I ask Java function what is my defualt printer, I have this result

C:>C:\Java\OpenJDK11U-jre_x64_windows_11.0.4_11\openjdk-11u-11.0.4_11-jre\bin\java.exe -jar C:\Java\PrintServiceLookupTest.jar
**Print Service Default Name is (Microsoft Print to PDF)**

***
I'd like Java to bring back the printer of windows

**Comment by jerboaa** [comment]
@borsatos 

Does this only happen on a Citrix/RDP session or can this be reproduced on a plain Windows system as well?

**Comment by borsatos** [comment]
Hi jerboaa,

**only Citrix or RDP Session**, because the registry where Windows 10 LTSC 2019 / W2016 / W2019 saves the Default Printer are different for local/network printers or redirected printers in Citrix/RDP Session.

The registry key used for local or network printers is:

HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows\Device

The registry key used for redirect printers is:

HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows\SessionDefaultDevices\ "session" \Device

**Comment by jerboaa** [comment]
Reported upstream as:
https://bugs.openjdk.java.net/browse/JDK-8231352

**Comment by borsatos** [comment]
Thank you

**Comment by vsaroka** [comment]
Hi @jerboaa,

> Reported upstream as:
> https://bugs.openjdk.java.net/browse/JDK-8231352

the ticket is assigned to Philip Race, but not targeted to any version as far as I see. Our customer would like to have the fix for this issue ASAP, he had also Oracle support ;). But I do not know, if Oracle can manage the fix.
Can you please say, if you know, in which version and when the fix might be appears? In any case we will try to do one of the workaround ;).

Thanks in advance,
Waleri

**Comment by borsatos** [comment]
I opened this ticket to oracle support.
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8232511

As a workaround, you create an .EXE (C++) that monitors the key : 
HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows\SessionDefaultDevices\ "session" \Device 
and changes the key:
HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\Windows\Device

Registry Change Notification API
https://docs.microsoft.com/en-us/windows/desktop/api/winreg/nf-winreg-regnotifychangekeyvalue

The .EXE must run at the user logon
