### ISSUE TITLE
TSC suggestion: reelection of members annually

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#128]
I've been involved in OSS projects before where the most influential folks move on to other projects and their influential positions could be assumed by others that become more active, IMO we should have the reelection every year and the nomination process/voting should start one month before the announced results. 

This ensures only the most active folk here have technical influence and provides an incentive for those to help others and act altruistically in aid of this community

**Comment by karianna** [comment]
@a-roberts Can you shift this to the TSC project?

**Comment by a-roberts** [comment]
Yeah should have been under TSC but they're at [this PR](https://github.com/AdoptOpenJDK/TSC/pull/1) now anyway
