### ISSUE TITLE
jdk13 linux arm32 100% CPU in "Service Thread"

### ISSUE THREAD

**Issue by insideo** [AdoptOpenJDK/openjdk-build#1287]
**Platform:** Raspberry Pi 2 / 3

**Architecture:** arm32

All java processes consume 100% of a core in "Service Thread". To reproduce, launch any long-running java process (such as jshell), and in another terminal, run "top -H" to view CPU usage by thread.

This does not occur on jdk 11 or jdk 12. I suspect this likely occurs upstream as well, but hard to be sure.

**Comment by JakubVanek** [comment]
I can reproduce the situation with https://ci.adoptopenjdk.net/view/ev3dev/job/eljbuild/job/stretch-13/5/ on Odroid-XU4 in Debian Stretch for armel.
![cpu](https://user-images.githubusercontent.com/6003171/65885650-4a730a00-e39b-11e9-9931-b65ac0dcf20b.png)

**Comment by JakubVanek** [comment]
The problematic thread is implemented here: https://github.com/openjdk/jdk13/blob/jdk-13-ga/src/hotspot/share/runtime/serviceThread.cpp
Latest change according to GitHub is this: https://github.com/openjdk/jdk13/commit/ae6dee44edc9dc43083705ef72b58caa0f1ee398. The change name looks suspicious, however I have no idea if it is actually related to the bug.

**Comment by insideo** [comment]
Flew this up the flagpole with hotspot-dev, which resulted in this issue being opened upstream:

https://bugs.openjdk.java.net/browse/JDK-8231612

No ETA on a fix as it appears to be a gcc bug, but compiling with "-fno-tree-pre" seems to be the workaround. Can we get this added to the arm32 builds?

**Comment by sxa555** [comment]
According to that openjdk bug a fix will be done in the compiler and is targetted for gcc 10 https://gcc.gnu.org/bugzilla/show_bug.cgi?id=92462

**Comment by littlefreaky** [comment]
The openjdk bug has now a changeset attached: https://hg.openjdk.java.net/jdk/jdk/rev/c97cf6fefbc1
It seems they work around the GCC problem that way.
