### ISSUE TITLE
TSC suggestion: briefly mention goals for candidates

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#129]
When nominating members I'd like us to know a little more about their intentions for the project - be it evangelism, platform support, performance testing, etc

This would be as simple as...

Hi, I'm `...` and I'd like to be on the TSC. I'd like to see the project focusing on infrastructure improvements, platform support, and collaboration with organisations such as `...` in order to achieve `...`

**Comment by karianna** [comment]
@a-roberts Can you shift this to the TSC project?

**Comment by a-roberts** [comment]
Yeah should have been under TSC but they're at [this PR](https://github.com/AdoptOpenJDK/TSC/pull/1) now anyway
