### ISSUE TITLE
debian stretch jdk11 build missing /bin/java

### ISSUE THREAD

**Issue by Firedrops** [AdoptOpenJDK/openjdk-build#1290]
I am trying to install java 11 in a [Google cloud-sdk](https://hub.docker.com/r/google/cloud-sdk/dockerfile) docker based on debian stretch.

My steps:
```
git clone https://github.com/AdoptOpenJDK/openjdk-build.git
cd /openjdk-build
./makejdk-any-platform.sh jdk11u
```
End bit of console output:
```
...

Welcome to Gradle 5.2.1!

Here are the highlights of this release:
 - Define sets of dependencies that work together with Java Platform plugin
 - New C++ plugins with dependency management built-in
 - New C++ project types for gradle init
 - Service injection into plugins and project extensions

For more details see https://docs.gradle.org/5.2.1/release-notes.html

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.2.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

BUILD SUCCESSFUL in 29s
3 actionable tasks: 2 executed, 1 up-to-date
/openjdk-build/sbin/build.sh: line 420: /bin/java: No such file or directory
```

Am I doing something wrong?

**Comment by karianna** [comment]
Are you able to SSH into that container and see if it has a `JAVA_HOME` or execute `which java`?

**Comment by Firedrops** [comment]
> Are you able to SSH into that container and see if it has a `JAVA_HOME` or execute `which java`?

`which java` returns `/usr/bin/java`
how do you check if it has a `JAVA_HOME`?

**Comment by karianna** [comment]
Right, that's correct, you need a Java 10 (preferred) or Java 11 boot JDK in order to build Java 11.  Interestingly it takes Java to build Java :-)

**Comment by Firedrops** [comment]
is this something that can be done simply by using this tool's java 10 version first?
```
git clone https://github.com/AdoptOpenJDK/openjdk-build.git
cd /openjdk-build
./makejdk-any-platform.sh jdk10u
```

**Comment by karianna** [comment]
@Firedrops you could grab a pre-built Java 10 using the curl or wget command through our API api.adoptopenjdk.net and then set the BOOT_JDK variable to that

**Comment by Firedrops** [comment]
Thank you, that sounds like it'll save some time. I've been trying to get this code to work, but somehow the thing being downloaded is only ~9 bytes big (a text file?). This template is adapted from what I use to automatically get github releases.
```
curl -s 'https://api.adoptopenjdk.net/v2/info/releases/openjdk10' | grep binary_link | grep OpenJDK10_x64_Linux | head -n 1 | awk '{print $2}' | xargs curl -L -o /OpenJDK10u.tar.gz
```
Right before the `xargs...`, the piped string is `https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2%2B13.tar.gz`, which appears correct. If I manually `wget` that URL, I also get served the correct file. Do you know why `xargs curl` isn't working in this case?

**Comment by JeffCarpenter** [comment]
@Firedrops when I run `curl -s 'https://api.adoptopenjdk.net/v2/info/releases/openjdk10' | grep binary_link | grep OpenJDK10_x64_Linux | head -n 1 | awk '{print $2}' | xargs echo` I get a comma at the end, ie:

```https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Linux_jdk-10.0.2%2B13.tar.gz,```

Without the comma it should work fine.

**Comment by karianna** [comment]
@Firedrops - I'll close this issue for now - please direct further Q's to our adoptopenjdk.nret/slack.html forum!

**Comment by Firedrops** [comment]
Thanks for the help everyone (on slack too)!

Just reporting back with code that fully work, YMMV on the dependencies. I only added what were still missing on my docker image.
```
RUN curl -s 'https://api.adoptopenjdk.net/v2/info/releases/openjdk10' | grep binary_link | grep OpenJDK10_x64_Linux | head -n 1 |  awk '{print $2}' | xargs echo | rev | cut -c 2- | rev | xargs curl -L -o /OpenJDK10u.tar.gz
RUN tar -zxvf OpenJDK10u.tar.gz && \
	mv jdk-10* jdk10 && \
	rm OpenJDK10u.tar.gz && \
	chmod a+x /jdk10/bin/java
ENV JAVA_HOME=/jdk10 BOOT_JDK=/jdk10 PATH=$JAVA_HOME/bin:$PATH
#J11 builder dependencies, move to start if works.
RUN apt install -y libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libcups2-dev libasound2-dev
RUN git clone https://github.com/AdoptOpenJDK/openjdk-build.git && \
	cd /openjdk-build && \
	./makejdk-any-platform.sh -J /jdk10 --configure-args --disable-warnings-as-errors jdk11u && \
	cd /
```
