### ISSUE TITLE
BUILD_CONFIG[JDK_PATH] variable is configured wrong when running a build in a Docker container

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-build#1293]
**Platform:**
macOS Mojave
**Architecture:**
x86_64

When debugging the Dockerfiles, I ran into the following error. 
```
Should have the source, I'm at /openjdk/build/src
ls: cannot access '/openjdk/build/src/build/*/images/jdk-bundle/jdk-*.jdk': No such file or directory
```
When building JDK8,11,12 and 13 in a Docker container
The actual directory is at `/openjdk/build/src/build/*/images/jdk`, which points to an issue with 
https://github.com/AdoptOpenJDK/openjdk-build/blob/4d1e8bcb9eb1a932901ca526826ed9f8c2e1108f/sbin/build.sh#L447
and
https://github.com/AdoptOpenJDK/openjdk-build/blob/4d1e8bcb9eb1a932901ca526826ed9f8c2e1108f/configureBuild.sh#L127

It seems that `configureBuild.sh` is being ran on the host system and assigning `BUILD_CONFIG[JDK_PATH]` not on the docker container.

**Comment by sxa555** [comment]
@Willsparker Can you confirm that this is no longer an issue now that the PR was landed so this can be closed?

**Comment by Willsparker** [comment]
@sxa555 The PR isn't currently merged. However, I've checked #1347 with jdk8-hotspot and it does fix the issue :-)

**Comment by sxa555** [comment]
It is now.:-D
