### ISSUE TITLE
No system dump produced by the JVM

### ISSUE THREAD

**Issue by ed03875** [AdoptOpenJDK/openjdk-build#1297]
Platform and OpenJDK JRE version
Windows 10 and Longhorn using OpenJDK 8  OpenJ9 version "1.8.0_202-b8

Summary
We experienced and repeatable access violation exception in jncrypto.dll.   This  JVM crash highlighted a larger issue no Java  dumps.  While testing we found that the HTTP process from our application was going away.  There was nothing in the postmortem  that our product produces other than the HTTP process was missing.  There were no Java dumps present on the machine. This required attaching a debugger to the missing process and reproducing the issue.  This is a support nightmare.  Is there a signal handling problem associated with  OpenJDK 8 OpenJ9 ? Luckily the problem must have been resolved in OpenJDK 8  OpenJ91.8.0_222-b10 because it went away when we upgraded.

Details
This issue occurred on Windows 10 and Longhorn using the following JVM
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (build 1.8.0_202-b08)
Eclipse OpenJ9 VM (build openj9-0.12.1, JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20190205_265 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb40
OMR      - d2f4534b
JCL      - d002501a90 based on jdk8u202-b08)

The crash was  in  jncrypto.dll
Exception thrown was an access violation in the Jncrypto.dll
The stack is shown below 
thread id: 7736
   registers:
    cs     = 0x0000000000000033   ds     = 0x000000000000002b   es     = 0x000000000000002b   fs     = 0x0000000000000053
    gs     = 0x000000000000002b   ss     = 0x000000000000002b   flags  = 0x0000000000010204   rax    = 0x0000000000000020
    rcx    = 0x0000000000a10600   rdx    = 0x0000000000a17980   rbx    = 0x00007ffbfacc13a8   rsp    = 0x000000c034fff2a0
    rbp    = 0x000000c034fff350   rsi    = 0x0000000000000001   rdi    = 0x0000000000000006   r8     = 0x0000000004d793c0
    r9     = 0x0000000000000001   r10    = 0x0000000000000000   r11    = 0x000000c034fff320   r12    = 0x000000c034fff470
    r13    = 0x0000000000a17980   r14    = 0x000000c034fff540   r15    = 0x000001c8025f563c   rip    = 0x00007ffbfacc13c8
   native stack sections:
    0xc034fff2a0 to 0xc035000000 (length 0xd60)
   native stack frames:
    bp: 0x000000c034fff2a0 pc: 0x00007ffbfacc13c8 C:\Program Files\HCL\Domino\jvm\bin\jncrypto.dll::Java_jdk_crypto_jniprovider_NativeCrypto_CBCInit+0x20
    bp: 0x000000c034fff2f0 pc: 0x00007ffbf9212fe3 C:\Program Files\HCL\Domino\jvm\bin\compressedrefs\j9vm29.dll::J9_CreateJavaVM+0x8b973
   properties:
	Affinity=0x000000000000000F             	CreateTime=132138990915683123           
	CreateTime_Formatted=2019/09/25 11:31:31	DumpError=0x00000000                    
	DumpFlags=0x00000000                    	ExitStatus=0x00000103                   
	ExitTime=0                              	KernelTime=0                            
	StartAddress=0x000000006C171DBC         	UserTime=2187500                        
	priority=0                              	priorityClass=32                        
   associated Java thread: 
    name:          IST-1e38
    Thread object: com/lotus/sync/util/ThreadPoolThread @ 0xffa493e0
    Daemon:        false
    ID:            81 (0x51)
    Priority:      5
    Thread.State:  RUNNABLE 
    JVMTI state:   ALIVE RUNNABLE 
    Java stack frames: 
     bp: 0x0000000000a17980  method: void jdk/crypto/jniprovider/NativeCrypto.CBCInit(long, int, byte[], int, byte[], int)  (Native Method)
      objects: 0xff359fb0 0xff371990 0xff371968
     bp: 0x0000000000a179c0  method: void com/sun/crypto/provider/NativeCipherBlockChaining.init(boolean, String, byte[], byte[])  source: NativeCipherBlockChaining.java:155
      objects: <no objects in this frame>
     bp: 0x0000000000a17a20  method: void com/sun/crypto/provider/CipherCore.init(int, java.security.Key, java.security.spec.AlgorithmParameterSpec, java.security.SecureRandom)  source: CipherCore.java:658
      objects: 0xff325f00
     bp: 0x0000000000a17a60  method: void com/sun/crypto/provider/AESCipher.engineInit(int, java.security.Key, java.security.spec.AlgorithmParameterSpec, java.security.SecureRandom)  source: AESCipher.java:346
      objects: <no objects in this frame>
     bp: 0x0000000000a17ab8  method: void javax/crypto/Cipher.implInit(javax.crypto.CipherSpi, int, int, java.security.Key, java.security.spec.AlgorithmParameterSpec, java.security.AlgorithmParameters, java.security.SecureRandom)  source: Cipher.java:805
      objects: <no objects in this frame>
     bp: 0x0000000000a17b40  method: void javax/crypto/Cipher.chooseProvider(int, int, java.security.Key, java.security.spec.AlgorithmParameterSpec, java.security.AlgorithmParameters, java.security.SecureRandom)  source: Cipher.java:863
      objects: 0xff289de8 0xff27db68 0xffb12e10 0xff289e20 0xffac16f0 0xff2e5358
     bp: 0x0000000000a17b80  method: void javax/crypto/Cipher.init(int, java.security.Key, java.security.spec.AlgorithmParameterSpec, java.security.SecureRandom)  source: Cipher.java:1395
      objects: 0xff289de8
     bp: 0x0000000000a17bd8  method: void sun/security/ssl/CipherBox.<init>(sun.security.ssl.ProtocolVersion, sun.security.ssl.CipherSuite$BulkCipher, javax.crypto.SecretKey, javax.crypto.spec.IvParameterSpec, java.security.SecureRandom, boolean)  source: CipherBox.java:237
      objects: 0xffa480e0
     bp: 0x0000000000a17c28  method: sun.security.ssl.CipherBox sun/security/ssl/CipherBox.newCipherBox(sun.security.ssl.ProtocolVersion, sun.security.ssl.CipherSuite$BulkCipher, javax.crypto.SecretKey, javax.crypto.spec.IvParameterSpec, java.security.SecureRandom, boolean)  source: CipherBox.java:263
      objects: 0xff287d80
     bp: 0x0000000000a17c70  method: sun.security.ssl.CipherBox sun/security/ssl/CipherSuite$BulkCipher.newCipher(sun.security.ssl.ProtocolVersion, javax.crypto.SecretKey, javax.crypto.spec.IvParameterSpec, java.security.SecureRandom, boolean)  source: CipherSuite.java:519
      objects: <no objects in this frame>
     bp: 0x0000000000a17ca0  method: sun.security.ssl.CipherBox sun/security/ssl/Handshaker.newWriteCipher()  source: Handshaker.java:837
      objects: 0xff1c3898
     bp: 0x0000000000a17cd8  method: void sun/security/ssl/SSLSocketImpl.changeWriteCiphers()  source: SSLSocketImpl.java:2135
      objects: 0xffa495a0 0xffa64f40 0xffa495a0
     bp: 0x0000000000a17d20  method: void sun/security/ssl/Handshaker.sendChangeCipherSpec(sun.security.ssl.HandshakeMessage$Finished, boolean)  source: Handshaker.java:1145
      objects: 0xff1c3898 0xff285738
     bp: 0x0000000000a17d50  method: void sun/security/ssl/ClientHandshaker.sendChangeCipherAndFinish(boolean)  source: ClientHandshaker.java:1280
      objects: 0xff1c3898 0xff285738
     bp: 0x0000000000a17db8  method: void sun/security/ssl/ClientHandshaker.serverHelloDone(sun.security.ssl.HandshakeMessage$ServerHelloDone)  source: ClientHandshaker.java:1190
      objects: <no objects in this frame>
     bp: 0x0000000000a17e18  method: void sun/security/ssl/ClientHandshaker.processMessage(byte, int)  source: ClientHandshaker.java:369
      objects: <no objects in this frame>
     bp: 0x0000000000a17e48  method: void sun/security/ssl/Handshaker.processLoop()  source: Handshaker.java:1037
      objects: 0xff1c3898
     bp: 0x0000000000a17e78  method: void sun/security/ssl/Handshaker.process_record(sun.security.ssl.InputRecord, boolean)  source: Handshaker.java:965
      objects: <no objects in this frame>
     bp: 0x0000000000a17ee8  method: void sun/security/ssl/SSLSocketImpl.readRecord(sun.security.ssl.InputRecord, boolean)  source: SSLSocketImpl.java:1064
      objects: 0xffa495a0 0xff20ee10 0xffa593d0 0xffa495a0
     bp: 0x0000000000a17f18  method: void sun/security/ssl/SSLSocketImpl.performInitialHandshake()  source: SSLSocketImpl.java:1367
      objects: 0xffa495a0 0xffa593b0
     bp: 0x0000000000a17f48  method: void sun/security/ssl/SSLSocketImpl.startHandshake(boolean)  source: SSLSocketImpl.java:1395
      objects: 0xffa495a0
     bp: 0x0000000000a17f68  method: void sun/security/ssl/SSLSocketImpl.startHandshake()  source: SSLSocketImpl.java:1379
      objects: <no objects in this frame>
     bp: 0x0000000000a18018  method: com.lotus.sync.servlet.ConnectionHTTPSender$SocketHolder com/lotus/sync/servlet/ConnectionHTTPSender.getSocketHolder(boolean)  source: ConnectionHTTPSender.java:369
      objects: 0xffa49680 0xffa49510 0xffa495a0
     bp: 0x0000000000a18080  method: void com/lotus/sync/servlet/ConnectionHTTPSender$SendMessageRunnable.run()  source: ConnectionHTTPSender.java:718
      objects: 0xffa49190
     bp: 0x0000000000a18128  method: void com/lotus/sync/util/ThreadPoolThread.run()  source: ThreadPoolThread.java:479
      objects: 0xffa493e0

HCL Domino loads the JVM as part of a process

When the JVM crashes there are no dumps produced. 
In this case there was an exception thrown in  the jncrypto.dll

 I was able to catch the crash by attaching to the process with a debugger and reproducing the crash.  This is a support nightmare because customers will not be able to do this.

**Comment by M-Davies** [comment]
@pshipton Could someone at OpenJ9 take a look at this? I recognise it's a little old but it may still affect modern OpenJ9

**Comment by pshipton** [comment]
@DanHeidinga fyi

@ed03875 
- Do diagnostic files get produced for other problems which aren't related to jncrypto.dll?
- Are any -Xdump options used when loading the JVM? 
- Has the JVM been stripped down to remove j9dmp29.dll?
- Does adding `-Xdump:java:events=vmstart` to the JVM invocation produce a javacore file? If so, can we take a look at it.

**Comment by ed03875** [comment]
@pshipton 
I have not seen a diagnostic file produced by OpenJDK which is still a concern
There were no -Xdump options used in this case
The JVM was not stripped down at all
We have long since moved on from this problem since it no longer occurred in the next release.

**Comment by pshipton** [comment]
@ed03875 pls close this issue if it is no longer relevant.
