### ISSUE TITLE
Build FAQ

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#130]
This can include any platform specific nuances we encounter that folks should be aware of when building OpenJDK. While we should be as easy to use as possible (such that you don't need an FAQ!), there may still be occurrences when people trip up and they'll look here first before digging into a README or the man entry. A mailing list would still be the best place to ask INfrequently asked questions. We would want to either add this as a menu item next to Issues at the top of this Github page or to add it to our existing wiki.

Some examples already include

**Problem**: checking sizeof int* fails on AIX
**Solution** Make sure you have xlc and xlC on your path and that you're not using gcc

**Problem**: undefined symbols building the VM for libpthread on AIX 7.2
**Solution** TBD

**Problem**: I can't build as Object isn't found
```
## Starting corba
Compiling 6 files for BUILD_LOGUTIL
/ramdisk0/adam/adam-openjdk-build/openjdk/corba/src/share/classes/com/sun/tools/corba/se/logutil/IndentingPrintWriter.java:35: error: cannot access Object
public class IndentingPrintWriter extends PrintWriter {
       ^
  class file for java.lang.Object not found
```
**Solution** TBD

**Problem**: Can't build on Mac: bash: ./configure: No such file or directory
**Solution**: `export MACOSX_DEPLOYMENT_TARGET=10.8`

**Comment by gdams** [comment]
we could host http://www.phpmyfaq.de/ on one of our machines. something like faq.adoptopenjdk.net

**Comment by karianna** [comment]
Could this just be a link to our Wiki on this repo?

**Comment by gdams** [comment]
I suppose it's more a fact of whether we can produce a useful forum that allows customers to come and ask questions and find solutions. The question is whether GitHub issues is adequate for this?

**Comment by karianna** [comment]
I'd have thought a GitHub Wiki would be adequate?  Or actually host some GitHub pages content?

**Comment by sxa555** [comment]
Marking as important just because this should be a quick one to come to a decisions to. I think personally a wiki FAQ type document would be preferable so that people can see all potential issues at once before running into each of them (like falling from a tree and hitting each branch on the way down!)

**Comment by karianna** [comment]
Build scripts are self-documenting and Jenkins pipeline jobs have their parameters well explained.
