### ISSUE TITLE
gradleJavaHome failing on Debian (JAVA_HOME not set)

### ISSUE THREAD

**Issue by MeFisto94** [AdoptOpenJDK/openjdk-build#1308]
So my build failed with the words that /bin/java cannot be found:
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L420
This is because indeed no $JAVA_HOME is present, but gradle still started up (`which java` works etc).

So it might be desireable to either check `/usr/lib/jvm/java-*-openjdk-*/` or do a `which java` and follow the symlinks to the end (on debian, there is `/etc/alternatives/java` between `/usr/lib/jvm` and `/usr/bin/java`.

I agree that JAVA_HOME should be set, but as it occurs it's not done automatically by Debian and that little conveniance would be awesome.

**Comment by adam-thorpe** [comment]
To add to this, it may be nice to use the value passed by --jdk-boot-dir, to use as JAVA_HOME if it is not already set? That way a user wouldn't have to explicitly set JAVA_HOME if they are setting this variable and this problem would not occur. Unless there is a reason old versions of java (eg. java 7 used to build jdk 8) is not compatible with gradle.

**Comment by sxa555** [comment]
I think gradle is quite sensitive to the java version, but it would be good to investigate this. This would be a good enhancement if gradle is the only thing depending on it.
