### ISSUE TITLE
Unable to access packages in module java.base while using openjdk 1.11.0

### ISSUE THREAD

**Issue by kaushalrai7797** [AdoptOpenJDK/openjdk-build#1312]
I was trying to gradle build my code using openjdk 1.11.0. The build failed after giving this type of error multiple times :
Symbol is declared in module ‘java.base’ which does not export package ‘sun.net.util’

**Comment by tellison** [comment]
Hi @kaushalrai7797 , that is a user error showing that Java is behaving as designed.  Please find a user community (such as [Stackoverflow](https://stackoverflow.com/questions/tagged/java)) to discuss how to use Java.
