### ISSUE TITLE
SIGSEGV (0xb) in C  [libc++abi.dylib+0x30b4] for osX 10.15 Catalina

### ISSUE THREAD

**Issue by petrychenko** [AdoptOpenJDK/openjdk-build#1315]
**Platform:**
OS:uname:Darwin 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64
**Architecture:**
x86_64

[hs_err_pid30602.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3705099/hs_err_pid30602.log)

After upgrade to os X 10.15 Catalina, previously working program failed with SIGSEGV. 
**How to reproduce**:
create a basic maven project with 2 dependencies:
```
    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>1.0.0-beta4</version>
    </dependency>
    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-native-platform</artifactId>
      <version>1.0.0-beta4</version>
    </dependency>
```
and one class:
```
public class Main{

  public static void main( String[] args ){
    INDArray s = Nd4j.zeros(1, 1);
    System.out.println( s.isMatrix() );
  }

}
```
.
Under Os X 10.15 Catalina, **expected result:**
```
false

Process finished with exit code 0
```

**Actual result:**
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff666980b4, pid=31244, tid=10243
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libc++abi.dylib+0x30b4]  __cxxabiv1::__si_class_type_info::has_unambiguous_public_base(__cxxabiv1::__dynamic_cast_info*, void*, int) const+0x4
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/ivanpetrychenko/src/testAdotOpenJdk/hs_err_pid31244.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

**Comment by petrychenko** [comment]
I'm not sure if it is normal or not, I'm not the author of this library.
But as this code works for Oracle JDK, and for AdoptOpenJDK before update to Catalina, it seems it is acceptable.
The same bug is reported to deeplearning4j: https://github.com/eclipse/deeplearning4j/issues/8156 .

**Comment by ticofab** [comment]
I am having exactly the same issue since upgrading to Catalina yesterday, adding my specs in case it can be useful. Haven't tried with Oracle JDK.
```
08:59:16.436 INFO  o.n.linalg.factory.Nd4jBackend - Loaded [CpuBackend] backend
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff6e8160b4, pid=8675, tid=35587
#
# JRE version: OpenJDK Runtime Environment (11.0.4+11) (build 11.0.4+11)
# Java VM: OpenJDK 64-Bit Server VM (11.0.4+11, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libc++abi.dylib+0x30b4]  __cxxabiv1::__si_class_type_info::has_unambiguous_public_base(__cxxabiv1::__dynamic_cast_info*, void*, int) const+0x4
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/fabiotiriticco/Development/programming/ticofab-rep/experiments/deeplearning/planes/hs_err_pid8675.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

[hs_err_pid8675.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3716098/hs_err_pid8675.log)

MBP 15 in ch 2019, processor 2,3 GHz 8-Core Intel Core i9

**Comment by drbitzer** [comment]
Same error for me for macOS 10.15 on a 2015 MBP 13" i5

**Comment by kyndi-barryevans** [comment]
Still an issue: macOS 10.15 (19A602) Darwin 19.0.0

14:33:15.855 [main] INFO  o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff686400b4, pid=14351, tid=0x0000000000000e03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libc++abi.dylib+0x30b4]  _ZNK10__cxxabiv120__si_class_type_info27has_unambiguous_public_baseEPNS_19__dynamic_cast_infoEPvi+0x4
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
[hs_err_pid14351.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3741335/hs_err_pid14351.log)

**Comment by ff-will** [comment]
Same error here. I tried 
- Oracle JDK 8
- AdoptOpenJDK 8
- AdoptOpenJDK 11
Worked fine before upgrading to Mac OS 10.15. So I don't think it's an AdoptOpenJDK problem...

**Comment by fjauer** [comment]
Same here

**Comment by karianna** [comment]
Can folks try the latest builds that came out this week?

https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot#x64_mac
https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot#x64_mac

**Comment by ff-will** [comment]
@karianna Just tried it with OpenJDK11: Still the same. Not surprised though as this really seems to be a problem in the deeplearning4j library.

**Comment by petrychenko** [comment]
Still the same, and still works under Orcale JDK
393 [main] INFO  o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff686c10b4, pid=95582, tid=9987
#
# JRE version: OpenJDK Runtime Environment (11.0.5+10) (build 11.0.5+10)
# Java VM: OpenJDK 64-Bit Server VM (11.0.5+10, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [libc++abi.dylib+0x30b4]  __cxxabiv1::__si_class_type_info::has_unambiguous_public_base(__cxxabiv1::__dynamic_cast_info*, void*, int) const+0x4

**Comment by PMacho** [comment]
Just tried the quickstart with the latest version of AdoptOperJDK 11:
[hs_err_pid15516.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3774601/hs_err_pid15516.log)

**Comment by mimkorn** [comment]
Same here.
I tried AdoptOpenJDK 8, 11, 13
Catalina 10.15

**Comment by ticofab** [comment]
might be solved as mentioned here: https://github.com/eclipse/deeplearning4j/issues/8156
