### ISSUE TITLE
Tidy up script docker and non-docker builds

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#132]
After working #131, and looking at the `build.sh` and `makejdk.sh` scripts, it appears that both of them kind of duplicates the steps. Not too happy with the solution in #131 but this will get us going for a bit.

There is potentially an issue with duplication and inconsistency between the two types of builds - ideally they both should go through the same work-flow.

@a-roberts @gdams we should look at this as well whilst doing the cleaning up process - its prone to bugs, like this one we just cleared.

**Comment by karianna** [comment]
Done in re-write
