### ISSUE TITLE
[JDK13] Crash with Minecraft 1.14.4 + OptiFine Ultra F4 pre8

### ISSUE THREAD

**Issue by Leo40Git** [AdoptOpenJDK/openjdk-build#1320]
**Platform:** Windows 10

**Architecture:** x64

This is using the installer version of AdoptOpenJDK 13 HotSpot.

**Crash log:** [crash-2019-10-11_13.35.26-server.txt](https://github.com/sp614x/optifine/files/3717084/crash-2019-10-11_13.35.26-server.txt)

**How to recreate:**
1. Grab the latest development version of [MultiMC](https://github.com/MultiMC/MultiMC5) (`0.6.7-develop-1394` at the time of writing).
2. Create a 1.14.4 instance.
3. Install OptiFine 1.14.4 F4 pre8 using [these steps](https://github.com/MultiMC/MultiMC5/wiki/MultiMC-and-OptiFine#the-jar-mod-way-any-version).
4. Run the game.
5. Create a Survival world.
6. Get some wood.
7. Try to craft some planks.
8. *Crash!*

Related issue on OptiFine's repo: https://github.com/sp614x/optifine/issues/2964 (according to the author, this seems to be a problem with OpenJDK)

**Comment by Leo40Git** [comment]
Issue successfully reproduced in the binary release.

**Comment by sxa555** [comment]
Apparently @Willsparker is a minecraft person so if he gets some time and no-one else gets round to looking at this he'll see if he can replicate it locally :-)

**Comment by Leo40Git** [comment]
Original issue just got reproduced with Oracle's JRE. Should this be closed?

**Comment by Willsparker** [comment]
@Leo40Git Yep, if it's not an AdoptOpenJDK specific issue :-)
