### ISSUE TITLE
Cannot run JDK13 AIX Hotspot

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#1327]
**Platform:**

AIX 7.1.4.30

**Architecture:**

Power8

**Please describe the issue that you are having with our binaries and if possible how to recreate it.**

https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/download/jdk-13%2B33/OpenJDK13U-jdk_ppc64_aix_hotspot_13_33.tar.gz

SDK Crashes when running `java -version`. I can run other JDK versions without issue.
```
-bash-4.4$ /usr/java13_64/bin/java -version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (threadCritical_aix.cpp:45), pid=19726432, tid=258
#  guarantee(ret == 0) failed: fatal error with pthread_mutex_lock()
#
# JRE version:  (13.0+33) (build )
# Java VM: OpenJDK 64-Bit Server VM (13+33, mixed mode, tiered, compressed oops, g1 gc, aix-ppc64)
# Core dump will be written. Default location: /home/u0020236/adam/core or core.19726432
#
# An error report file with more information is saved as:
# /home/u0020236/adam/hs_err_pid19726432.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-build/issues
#
IOT/Abort trap (core dumped)
```
[hs_err_pid17039550.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3734365/hs_err_pid17039550.log)

**Comment by RealCLanger** [comment]
Hi,

this could well be a wrong version of the c++ runtime library. I have to ask around about the OS requirements for hotspot VMs that got compiled with XlC 16.

Cheers
Christoph

**Comment by AdamBrousseau** [comment]
cc @vsebe I know you've been working on xlc 16 changes, does this look familiar?

**Comment by vsebe** [comment]
The OpenJ9 machines have xlc 13 and xlc 16 installed. If you set xlc16 (`/opt/IBM/xlC/16.1.0/bin:/opt/IBM/xlc/16.1.0/bin`) first on the PATH, does the error still occur?
Try an OpenJ9 jdk (check Artifactory).

**Comment by sxa555** [comment]
JDK13 at adoptopenjdk is currently built on a machine running AIX 7.2 (TL2SP2) and it certainly works ok on my other 7.2 box (which has XLC16 installed, but not as the default in the PATH)

**Comment by sxa555** [comment]
Bear in mind that there may be other similar symptoms when we move up to 7.1TL5SP5 for OpenJ9 as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1006

**Comment by sxa555** [comment]
@AdamBrousseau Do the latest JDK13 nightlies work on 7.1.0.4? They are now built on 7.1 TL5SP5 so curious to know

**Comment by sxa555** [comment]
@AdamBrousseau Do the latest nightlies suffer the same problems? Now that we're building JDK13 on 7.1TL5SP5 it might stand more of a chance of running on 7.1.0.4 :-)

**Comment by AdamBrousseau** [comment]
On last release (jdk-13+33) on 7.1.4.3 I still get the same error.
On 7.1.5.5 I also get the error.
With latest nightly build I get proper version on both 7.1.4.3 and 7.1.5.5
```
> ./jdk-13.0.1+9/bin/java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 13.0.1+9-202001030621)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13.0.1+9-202001030621, mixed mode)
```
So I think we can close this?

**Comment by sxa555** [comment]
Sounds about right - the machines are built on the earlier version now, so should be ok for the next quarterly release. Thanks for confirming - I think I'll close this now :-)
