### ISSUE TITLE
java parameter "-splash" not working on macos

### ISSUE THREAD

**Issue by mbbee** [AdoptOpenJDK/openjdk-build#1333]
**Platform:** macos  (Catalina)
**Architecture:** x64
The splash screen parameter works well on windows or linux, but **not** on macos.
The startup just hangs / is stuck.

**Comment by karianna** [comment]
I'm afraid not (and Zimbra is also now out of support).

**Comment by mbbee** [comment]
Ahh, this is a know bug with SWT:
-splash and -XstartOnFirstThread do not work together
https://bugs.openjdk.java.net/browse/JDK-8068815
