### ISSUE TITLE
OpenJDK 8 broken font rendering e.g. for Google font "Great Vibes"

### ISSUE THREAD

**Issue by BuZZ-dEE** [AdoptOpenJDK/openjdk-build#1337]
**Platform:** Debian GNU/Linux 9.9 (stretch), Ubuntu 18.04, Arch Linux

**Architecture:** amd64

Please see the following images for Google font "[Great Vibes](https://fonts.google.com/specimen/Great+Vibes)":

**OpenJDK 8** **_broken_** font redering:

![openjdk-8-font-incorrect](https://user-images.githubusercontent.com/125954/67096926-6529e900-f1b9-11e9-82ba-1e672216225d.png)

![openjdk-8-font-incorrect-marked](https://user-images.githubusercontent.com/125954/67101295-a58d6500-f1c1-11e9-9cc8-8dc72eb6da19.png)

**OracleJDK 8, OpenJDK 10, 11, 13** correct font rendering:

![openjdk-13-font-correct](https://user-images.githubusercontent.com/125954/67096942-6d822400-f1b9-11e9-8f39-43175ffe1189.png)

**Example code**:

Wrong rendering **_not_** visible:
```java
javax.swing.JButton button = new javax.swing.JButton("Open");
java.awt.Font font = new java.awt.Font("Great Vibes", Font.PLAIN, 64);
button.setFont(font);
```
![OpenJDK-8-font-size-128-wrong-rendering-not-visible png](https://user-images.githubusercontent.com/125954/67099592-8b05bc80-f1be-11e9-995b-b535ac0dda12.png)

Wrong rendering visible:
```java
javax.swing.JButton button = new javax.swing.JButton("Open");
java.awt.Font font = new java.awt.Font("Great Vibes", Font.PLAIN, 128);
button.setFont(font);
```
![OpenJDK-8-font-size-128-wrong-rendering-visible](https://user-images.githubusercontent.com/125954/67099600-8e994380-f1be-11e9-8c5a-024eb3b1809b.png)

**Comment by BuZZ-dEE** [comment]
As it turns out, it is related to the [font version](https://github.com/corretto/corretto-8/files/3748490/Great.Vibes.ttf.zip) we are using.

[broken font version:](https://github.com/corretto/corretto-8/files/3748490/Great.Vibes.ttf.zip)
![openjdk-8-25 222-b05_rendering_incorrect_great-vibes](https://user-images.githubusercontent.com/125954/67167520-6155bc80-f39b-11e9-8cd4-afdf1cf2757c.png)

[correct font version](https://github.com/corretto/corretto-8/files/3748496/greatvibes.zip) downloaded from [here](https://github.com/google/fonts/archive/master.zip)
![openjdk-8-1 8 0_222-b05_rendering_correct_great-vibes](https://user-images.githubusercontent.com/125954/67167522-6581da00-f39b-11e9-966f-bbe0bfa8e453.png)

**Comment by BuZZ-dEE** [comment]
https://github.com/corretto/corretto-8/issues/176

**Comment by BuZZ-dEE** [comment]
@karianna why you closed this issue?

**Comment by karianna** [comment]
@BuZZ-dEE - I think I interpreted your previous message incorrectly!  I thought you fixed it by a 3rd party upgrade of a font library.

**Comment by gdams** [comment]
This is to do with the fact that we don't ship Marlin renderer in jdk8 (Azul and Oracle do) This is expected behaviour and is not a bug. There are already multiple issues in this repo about this. Please follow https://github.com/AdoptOpenJDK/openjdk-build/issues/1119 for updates. Closing

**Comment by BuZZ-dEE** [comment]
@gdams Are you sure, that this problem has to do with Marlin renderer? I tried to use [Marlin-renderer 0.9.4.2](https://github.com/bourgesl/marlin-renderer/releases/tag/v0_9_4_2):

```
java -Xbootclasspath/a:${PATH_TO_MARLIN}/marlin-X.Y.Z-Unsafe.jar \
     -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine \
     ...
```

and the problems still exists:

[FontRederingErrorDemo.zip](https://github.com/AdoptOpenJDK/openjdk-build/files/3805373/FontRederingErrorDemo.zip)

**Comment by BuZZ-dEE** [comment]
Backport of 8057986: freetype code to get glyph outline does not handle initial control point properly #183
https://github.com/corretto/corretto-8/pull/183

**Comment by BuZZ-dEE** [comment]
fixed in jdk8u242-b08

thank you
