### ISSUE TITLE
jdk-11.0.4+11.4 installled, but build 11.0.4+11 reported? [mac installer]

### ISSUE THREAD

**Issue by uqix** [AdoptOpenJDK/openjdk-build#1345]
Steps to reproduce:
1. install jdk-11.0.4+11.4 for Mac
2. check version, the build date is supposed to be `24 August 2019`
```sh
~$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

**Comment by gdams** [comment]
@uqix we've tried that before but unfortunately it's not supported upstream. Closing as this wouldn't be possible without a considerable amount of work upstream
