### ISSUE TITLE
Debian Packages in Repo have wrong version for 8u232

### ISSUE THREAD

**Issue by patric42** [AdoptOpenJDK/openjdk-build#1346]
The current 8u232 release's deb version is

1.8.0-232-b09-2

instead of

8u232-b09.openj9-0.17.0-1

That way, debian users won't be able to update, as the new version is treated as old.

Thanks!

**Comment by karianna** [comment]
Unsure if it's a build or installer issue - but we'll keep it here for now.

**Comment by aahlenst** [comment]
Packages with the correct version numbers have been released.
