### ISSUE TITLE
JMC archive does not contain top level folder

### ISSUE THREAD

**Issue by hdafgard** [AdoptOpenJDK/openjdk-build#1352]
**Platform:**
Linux

**Architecture:**
x86_64

The .tar.gz archives generated for JDK Mission Control do not contain a top-level folder, so running tar extract in the wrong place can cause a bit of a mess for an unsuspecting user. This should be tidied up to conform to most users expectations.

**Comment by gdams** [comment]
@hdafgard is this still a problem or has it been fixed in subsequent releases?

**Comment by hdafgard** [comment]
Downloading from https://adoptopenjdk.net/jmc.html right now still does not contain a top level folder.

**Comment by reinhapa** [comment]
@hdafgard question is how this archive is being created within the jmc build in the first place... I just use the resulting binary there..

**Comment by hdafgard** [comment]
IIRC Eclipse Tycho is responsible for generating the packaged builds.

**Comment by reinhapa** [comment]
Opened [JMC-6852](https://bugs.openjdk.java.net/browse/JMC-6852) with PR

**Comment by reinhapa** [comment]
@hdafgard  Fixed on 8.0.0-SNAPSHOT so far. Is there a need to back port to 7.x.x also?
