### ISSUE TITLE
Times differ for 2014 Sao_Paulo TZ between 8u222_b10 and 8u232_b9 / 8u242_b8

### ISSUE THREAD

**Issue by bryan-coleman** [AdoptOpenJDK/openjdk-build#1366]
In jdk 8.222_b10 using tzdata-2019a:
  2014-02-15 23:59:59 BRST: 1392515999000
  2014-02-15 23:00:00 BRST: 1392512400000
  2014-02-15 23:00:00 BRT:   1392516000000
  2014-02-16 00:00:00 BRST: 1392516000000
  2014-02-16 00:00:00 BRT:   1392519600000

In jdk 8.232_b09 using tzdata-2019c:
  2014-02-15 23:59:59 BRST: 1392519599000
  2014-02-15 23:00:00 BRST: **1392516000000**
  2014-02-15 23:00:00 BRT:   1392516000000
  2014-02-16 00:00:00 BRST: **1392519600000**
  2014-02-16 00:00:00 BRT:   1392519600000

To recreate:

```
        TimeZone tz = TimeZone.getTimeZone("America/Sao_Paulo");
        SimpleDateFormat parser = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss zzz");
        parser.setTimeZone(tz);

        String[] strings = {"2014-02-15 23:59:59 BRST", "2014-02-15 23:00:00 BRST", "2014-02-15 23:00:00 BRT", "2014-02-16 00:00:00 BRST", "2014-02-16 00:00:00 BRT"};

        try {
            for (String s : strings) {
                System.out.println(String.format("%-24s: %s", s, parser.parse(s).getTime()));
            }

        } catch (ParseException e) {
            e.printStackTrace();
        }
```

Verifying tzdata between versions 2019a and 2019c:
  tzdata-2019a
    zdump -V -c 2014,2015 America/Sao_Paulo
      America/Sao_Paulo  Sun Feb 16 01:59:59 2014 UT = Sat Feb 15 23:59:59 2014 -02 isdst=1 gmtoff=-7200
      America/Sao_Paulo  Sun Feb 16 02:00:00 2014 UT = Sat Feb 15 23:00:00 2014 -03 isdst=0 gmtoff=-10800
      America/Sao_Paulo  Sun Oct 19 02:59:59 2014 UT = Sat Oct 18 23:59:59 2014 -03 isdst=0 gmtoff=-10800
      America/Sao_Paulo  Sun Oct 19 03:00:00 2014 UT = Sun Oct 19 01:00:00 2014 -02 isdst=1 gmtoff=-7200

  tzdata-2019c
   zdump -V -c 2014,2015 America/Sao_Paulo
    America/Sao_Paulo  Sun Feb 16 01:59:59 2014 UT = Sat Feb 15 23:59:59 2014 -02 isdst=1 gmtoff=-7200
    America/Sao_Paulo  Sun Feb 16 02:00:00 2014 UT = Sat Feb 15 23:00:00 2014 -03 isdst=0 gmtoff=-10800
    America/Sao_Paulo  Sun Oct 19 02:59:59 2014 UT = Sat Oct 18 23:59:59 2014 -03 isdst=0 gmtoff=-10800
    America/Sao_Paulo  Sun Oct 19 03:00:00 2014 UT = Sun Oct 19 01:00:00 2014 -02 isdst=1 gmtoff=-7200

The tzdata appears to be identical.

Any thoughts on why java is behaving differently between the two versions?

**Comment by bryan-coleman** [comment]
In jdk-8.0.242.08-hotspot:

2014-02-15 23:59:59 BRST: 1392519599000
2014-02-15 23:00:00 BRST: **1392516000000**  # this time is still inconsistent with version 222
2014-02-16 00:00:00 BRST: 1392519600000
2014-02-15 23:00:00 BRT: 1392516000000
2014-02-16 00:00:00 BRT: 1392519600000

**Comment by aahlenst** [comment]
If this is still an issue with the latest version (8u261) downloaded from https://www.oracle.com/java/technologies/java-se-glance.html, report it to https://bugreport.java.com/bugreport/ and update the issue here once the report has been accepted.
