### ISSUE TITLE
Checksum file missing for jdk-11.0.5+10 s390x build

### ISSUE THREAD

**Issue by dinogun** [AdoptOpenJDK/openjdk-build#1367]
**Platform:**
Linux

**Architecture:**
s390x

Checksum file is missing for `jdk-11.0.5+10` for the `hotspot` `s390x` [build](https://api.adoptopenjdk.net/v2/info/releases/openjdk11?openjdk_impl=hotspot&os=linux&release=latest&type=jdk&arch=s390x).

The [checksum URL](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jdk_s390x_linux_hotspot_11.0.5_10.tar.gz.sha256.txt) in the above link says `file not found`.

This is causing the Docker builds to ignore this platform.

**Comment by lumpfish** [comment]
I've verified that the checksum in these files:

https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/620/artifact/target/linux/s390x/hotspot/OpenJDK11U-jdk_s390x_linux_hotspot_11.0.5_10.tar.gz.sha256.txt
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/620/artifact/target/linux/s390x/hotspot/OpenJDK11U-jre_s390x_linux_hotspot_11.0.5_10.tar.gz.sha256.txt

is correct for the s390x-hotspot releases downloaded from here: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/jdk-11.0.5%2B10/

So those files need to be added to the https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/jdk-11.0.5%2B10/ release.

**Comment by lumpfish** [comment]
Also the testimage checksum file is missing.

**Comment by lumpfish** [comment]
@sxa555 has uploaded the files to https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/jdk-11.0.5%2B10/ , all should be OK now.
