### ISSUE TITLE
Build artefacts need better top-level directory name

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#137]
When downloading a build from the website, such as [the current suggested build for Linux x86_64](https://github.com/AdoptOpenJDK/openjdk-releases/releases/download/jdk8u162-b00/OpenJDK8_x64_Linux_jdk8u162-b00.tar.gz), the archive contains a directory structure starting `./j2sdk-image`.

This top level directory structure should begin with a meaningful directory name, e.g. `jdk1.8.0_131` to denote the release level.

**Comment by gdams** [comment]
closing as this is now complete
