### ISSUE TITLE
Fatal Error on Win 10 using 11.0.5+10

### ISSUE THREAD

**Issue by sormuras** [AdoptOpenJDK/openjdk-build#1378]
**Platform:** OS: Windows 10 , 64 bit Build 18362 (10.0.18362.329)

**Architecture:**
- `PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD`
- `Host: AMD Ryzen 7 3700X 8-Core Processor             , 16 cores, 63G,  Windows 10 , 64 bit Build 18362 (10.0.18362.329)`
- `vm_info: OpenJDK 64-Bit Server VM (11.0.5+10) for windows-amd64 JRE (11.0.5+10), built on Oct 19 2019 12:23:57 by "" with MS VC++ 15.8 (VS2017)`

Running the following command line, from this [project](https://github.com/sormuras/bach-air):

```
java
  --module-path=
    bin/build/test/modules/it.jar;
    bin/build/main/modules;
    bin/build/test/modules;
    lib
--add-modules=it
--module=org.junit.platform.console org.junit.platform.console
--select-module=it
```

leads to the attached fatal error.

- [hs_err_pid7900.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3837142/hs_err_pid7900.log)

Here are two more error log files:

- [hs_err_pid11364.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3837147/hs_err_pid11364.log)
- [hs_err_pid6712.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3837148/hs_err_pid6712.log)

I tried running the same command using **Oracle** JDK 11.0.5 on ... it halts/fails too, without writing a fatal error log. Same for OpenJDK 13.0.1 ~~and OpenJDK 14-ea+22~~.

**Comment by sormuras** [comment]
OpenJDK 11.0.2 (archived) also produced a fatal error log:

- [hs_err_pid6292.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3839597/hs_err_pid6292.log)

**Comment by sormuras** [comment]
I found a related reason, why some JDK distros fail without writing a fatal error log: my `%TEMP%` and `%TMP%` environment variable point to `Z:\TEMP`, with `Z:` being an in-memory disk. The driver of that disk stopped mounting that virtual device for some unknown reasons, but after recreating it, most JDKs don't bail out anymore.

- [x] OpenJDK 14-ea+22

Re-trying more JDKs later...

**Comment by sormuras** [comment]
Here's a failing run on GitHub Actions using "Java 13" from Azul, iirc.

https://github.com/sormuras/bach-air/runs/300680416#step:4:73

**Comment by sormuras** [comment]
Finally, here's a single run that failed on 11 and 13: https://github.com/sormuras/bach-air/runs/300828140

**Comment by karianna** [comment]
https://bugs.openjdk.java.net/browse/JDK-8234076

**Comment by sormuras** [comment]
Problem still persists after upgrading Windows to `Version 10.0.18363.476`, aka V1909.

- [hs_err_pid8088.log](https://github.com/AdoptOpenJDK/openjdk-build/files/3843375/hs_err_pid8088.log)

**Comment by sormuras** [comment]
Investigating potential root cause at https://github.com/remkop/picocli/issues/863

**Comment by sormuras** [comment]
FYI: https://mail.openjdk.java.net/pipermail/core-libs-dev/2019-November/063573.html

Closing this issues, as AdoptOpenJDK is not the root of the bug.
