### ISSUE TITLE
Pin versions we mention in Docker files

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#14]
Our Docker file (currently only for Ubuntu 14 04) isn't guaranteed to produce the same builds on a daily basis - we're using, for example, 14 04 as the version for Ubuntu - and whatever 14 04 is now won't be the same as it will be when there's another security update. The same goes for any other dependencies we install - we're providing no version information and we're not tracking any of it either AFAIK.

One idea is to add the full version hash for each dependency we download to ensure we're producing the exact same binaries each time unless we want there to be a change - and we should also include a complete listing of all the versions used in the libraries we use and/or bundle. 

This would involve adopting a promotion strategy whereby, once it's agreed to do a release for a given platform (perhaps amongst us in this community), the versions are all checked and potentially updated.

If we don't and we're providing binaries for OpenJDK (potentially to be used in production), we expose ourselves to problems later on should there be any version specific bugs or incompatibilities (I'm especially interested since Ubuntu 17 04 will be released soon).

**Comment by karianna** [comment]
@a-roberts I haven't looked at the details yet but could we have an immutable vagrant base/build?  We could have for example builds based on 14.04 / 16.04 etc.

**Comment by neomatrix369** [comment]
@a-roberts Good point about docker-ubuntu, and also about builds requiring to be identical and unique.
For the docker part, we could build our own fixed image with version info stamped and use that instead, just like @karianna is suggesting using vagrant builds (did some work on this in the paste https://github.com/neomatrix369/adopt-openjdk-kiss-vagrant).

**Comment by gdams** [comment]
@a-roberts I'm tempted to NOT produce our builds using docker, now that we have our own jenkins server with full admin access to all build machines there seems no need (we can only build x Linux in docker anyway). Currently our Linux build is in docker but our s390 and mac builds are not so it would make sense to standardise this

**Comment by tellison** [comment]
The Jenkins builds don't need to use Docker where we have root access to configure the machine as we see fit, but I think there is still value in retaining the Docker env so the build can be reproduced on a local machine or more restricted system.

This issue is part of a wider discussion about the Standard Build Environment we need to define for the community builds.  That warrants a separate issue.

**Comment by karianna** [comment]
On reviewing with John - even that the Docker file says `16.04` for Ubuntu means you could get a different 16.04.  I'm not convinced we want to pin versions but we do want to audit - see #11

**Comment by gdams** [comment]
closing for now, we no longer produce any builds using a docker based environment
