### ISSUE TITLE
AIX not packaging results correctly

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#140]
AIX appears to be building ok, but the tidy-up and archiving are failing

Note the `find: bad option -delete` and `./j2sdk-image: No such file or directory` output below from [a recent job](https://ci.adoptopenjdk.net/job/openjdk_build_ppc64_aix/27/).

```
Finished building OpenJDK for target 'images'
Built the JDK!'/home/jenkins/workspace/openjdk_build_ppc64_aix/openjdk/build/aix-ppc64-normal-server-release/images/j2sdk-image' foundopenjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2017_06_28_06_23-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)Removing unneccessary files now...
find: bad option -delete
./j2sdk-image: No such file or directory
tar: can't change directories to Your final .tar.gz is here at /home/jenkins/workspace/openjdk_build_ppc64_aix/openjdk/build/aix-ppc64-normal-server-release/images
/home/jenkins/workspace/openjdk_build_ppc64_aix/sbin/build.sh: line 272: cd: /home/jenkins/workspace/openjdk_build_ppc64_aix/OpenJDK8_ppc64_AIX_201728060603.tar.gz: Not a directory
Archiving artifacts
```

**Comment by tellison** [comment]
Reported by @simonis

**Comment by neomatrix369** [comment]
Happy to help @gdams investigate this issue, this was agreed on the back of PR #131

**Comment by neomatrix369** [comment]
@gdams I think we can close this one, we have resolved it last week - you ok we close it?

**Comment by neomatrix369** [comment]
The only issue there is the below error message:
```find: bad option -delete```

@tellison had suggested we do this:
```find .. | xargs rm```
In his words: to be portable across the OSes

**Comment by gdams** [comment]
I'm going to close this issue as the find warning isn't blocking the builds
