### ISSUE TITLE
Problems downloading freetype in build scripts

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-build#1401]
See: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9/395/console

Causing problems on all platforms when downloading freetype (consistent with wget as well)
`curl: (7) Failed connect to download.savannah.gnu.org:443; No route to host`

A curl error code 7 occurs when a connection is unavailable to a host or proxy, so this is before any checksum checks. Site seems to be accessible and I had no problems downloading the source so I would assume this is a problem with DNS/proxy setup?

**Comment by sxa555** [comment]
Appears to be fine in the subsequent run so I assume the download servers were offline last night.
