### ISSUE TITLE
IBM bidiTools support

### ISSUE THREAD

**Issue by tejaswinivish** [AdoptOpenJDK/openjdk-build#1403]
Hi , 
We are using IBM JDK for our build and we are using IBM bidiTools for Bi-Directional text support. Now are planning to move our build to openJDK11 and I did not find these classes included in the JDK. Are there any equivalent implementation or alternatives available in OpenJDK? If not is there any plan to include IBM tools?
Below are the classes which we are using currently
com.ibm.bidiTools.bdlayout.BidiFlag
com.ibm.bidiTools.bdlayout.BidiFlagSet
com.ibm.bidiTools.bdlayout.BidiText

**Comment by pshipton** [comment]
@andrew-m-leonard a JCL feature request.

**Comment by andrew-m-leonard** [comment]
This feature was an IBM extension developed for IBM JDK. As I understand it, the way it was implemented is not suitable as it stands for basing on openjdk, so some significant development would be required to provide such a feature on OpenJDK.
Currently there are no plans for this feature.

It maybe worth experimenting with OpenJFX which I think provides a bidi binding...?

**Comment by karianna** [comment]
@tejaswinivish - I think this request should be taken to Eclipse OpenJ9 or perhaps IBM support.
