### ISSUE TITLE
DockerFileCheck job is not correctly picking up changes

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1406]
I've put in a change to the Dockerfiles relating to ccache https://github.com/AdoptOpenJDK/openjdk-build/pull/1405

I've tested it in https://ci.adoptopenjdk.net/view/work%20in%20progress/job/DockerFileCheck/73 (job was modified in that run to pull from my fork) and it didn't pick up the change (Look at https://ci.adoptopenjdk.net/job/DockerfileCheck/label=infra-vagrant-1,variant=j9,version=jdk13u/73/consoleFull and it still has `ccache` in the `apt-get install` line)

If I run the adjusted `Dockerfile` on a new machine it runs correctly, picking up and using `ccache 3.4.2` from `/usr/local/bin`

This suggests that something else needs to be cleared out between runs to ensure the tests are picking up everything correctly (maybe a new option if it causes a significant performance hit)

FYI @Willsparker

**Comment by Willsparker** [comment]
I imagine it's something to do with the `setupGit` function. It's meant to pull any changes, however it appeared to fail:
```
fatal: destination path '/home/jenkins/workspace/DockerfileCheck@2/label/infra-vagrant-1/variant/j9/version/jdk13u/DockerBuildFolder/jdk13u-openj9' already exists and is not an empty directory.
```
The condition checks for `$jdkVersion-$buildVariant/docker`, so a previous run may have caused `jdk13u-openj9` to be made but not git clone properly.
