### ISSUE TITLE
Add a requirements section to README

### ISSUE THREAD

**Issue by galderz** [AdoptOpenJDK/openjdk-build#1415]
A requirements section should be added to the README.

First, the first I run this I got:

```
Searching for JDK_BOOT_DIR
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
```

I had `JAVA_HOME` set and `java` was present in path, what is `/usr/libexec/java_home` looking for exactly? Is that only covering java versions installed via Apple or something along those lines? I worked around it by giving it `--jdk-boot-dir`

Then, I'm seeing:

```
Autoconf is not found on the PATH, and AUTOCONF is not set.
You need autoconf to be able to generate a runnable configure script.
You might be able to fix this by running 'brew install autoconf'.
Error: Cannot find autoconf
```

So `autoconf` should be one of those requirements?

I can help with this

**Comment by sxa555** [comment]
Out machines are set up using ansible playbooks, so they provide most of the information you want want as prereqs. For HotSpot they are as per the upstream OpenJDK project, and for OpenJ9 they are at https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V8.md (which I believe is a supserset of that required for the HotSpot builds.

I'm not personally a macos expert but it sounds like there's a definite opportunity for autodetecting the right thing on there that we're currently missing.

**Comment by galderz** [comment]
I think the problem with `/usr/libexec/java_home` is that it only detects those Java versions that have been installed via Apple. I had installed mine directly from AdoptOpenJDK and that wasn't being found, even though my `JAVA_HOME` and `javac` where there... I wonder if the code should fallback on looking for `javac`, like it does for other envs, if `/usr/libexec/java_home` fails?

**Comment by sxa555** [comment]
@galderz I presume this can be now closed with your PR being in - If you disagree feel free to repoen this :-)
