### ISSUE TITLE
RPM repository is not provided for Fedora 31

### ISSUE THREAD

**Issue by danielsun3164** [AdoptOpenJDK/openjdk-build#1418]
**Website Issues:** https://adoptopenjdk.jfrog.io/adoptopenjdk/rpm/fedora/

Only verison 29 and 30 is provided, please provide version 31 also, thank you.

**Comment by sxa555** [comment]
Already in progress and [awaiting TSC approval](https://github.com/AdoptOpenJDK/TSC/issues/127), so I'm going to close this as a duplicate for now

**Comment by aahlenst** [comment]
Packages are available.

**Comment by danielsun3164** [comment]
I could connect to the repository now, thank you very much for your quick response.
