### ISSUE TITLE
jdk11 sdk java version got 'openjdk version "11.0.6" 2020-01-14

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#1427]
**Platform:**
All
**Architecture:**
All

Recent jdk11 sdk java version got the 'openjdk version "11.0.6" 2020-01-14

``` ./java -version
openjdk version “11.0.6” 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+2-201911191938)
Eclipse OpenJ9 VM AdoptOpenJDK (build master-39fe8cb07, JRE 11 Mac OS X amd64-64-Bit Compressed References 20191119_384 (JIT enabled, AOT enabled)
OpenJ9   - 39fe8cb07
OMR      - b372b24c8
JCL      - 5daf47df6d based on jdk-11.0.6+2) 
```
 
Hotspot jdk11 java version

```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+3-201912021909)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+3-201912021909, mixed mode)
``` 
 Is this expected or a known issue ?

**Comment by sxa555** [comment]
I think this is es expected - the underlying openjdk codebases hard code the version number (and planned GA date) into the codebase - see https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/094f272cbead1e57205eb573a2fd313ec7122547 for the lastest commit to bump it to the version your seeing in the output.

So it's indicating the release date of `11.0.6` - it just looks a little odd in a pre-release build as it's in the future :-)
