### ISSUE TITLE
Signing Error on JDK11-windowsX32-hotspot nightlies

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1428]
- Related to https://github.com/AdoptOpenJDK/openjdk-build/issues/1235
- Job Link: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-hotspot/341/console
- JDK11-windowsX32-hotspot nightly build fails on the signing stage of the pipeline.
- This may be fixed in PR #1425

**Comment by sxa555** [comment]
Fix has worked - from a build tonight:
```
Done Adding Additional Store
Successfully signed and timestamped: ./hotspot/jtreg/native/redefclass006.dll

Done Adding Additional Store
Error information: "SignerTimeStamp() failed." (-2147012894/0x80072ee2)
SignTool Error: An unexpected internal error has occurred.
WARNING: Failed to sign ./hotspot/jtreg/native/redefclass008.dll at 09:44:35: Possible timestamp server error - RC 0 ... Retrying in 10 seconds
Done Adding Additional Store
Successfully signed and timestamped: ./hotspot/jtreg/native/redefclass008.dll

Done Adding Additional Store
```

**Comment by M-Davies** [comment]
See https://github.com/AdoptOpenJDK/openjdk-build/issues/1235#issuecomment-563950429
