### ISSUE TITLE
asmtools.jar UnsupportedClassVersionError with Java 8

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#1453]
Trying to build testing for Java 8 results in the following today. It was working last night (EST).
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Personal/447
```
15:50:47  jasm_generator:
15:50:47      [mkdir] Created dir: /home/jenkins/jenkins-agent/workspace/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Personal/openjdk-tests/functional/Java8andUp/bin/j9vm/test/invoker
15:50:47       [exec] Error: A JNI error has occurred, please check your installation and try again
15:50:47       [exec] Exception in thread "main" java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=org/openjdk/asmtools/Main, offset=6
15:50:47       [exec] 	at java.lang.ClassLoader.defineClassImpl(Native Method)
15:50:47       [exec] 	at java.lang.ClassLoader.defineClassInternal(ClassLoader.java:398)
15:50:47       [exec] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:359)
15:50:47       [exec] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
15:50:47       [exec] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
15:50:47       [exec] 	at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
15:50:47       [exec] 	at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
15:50:47       [exec] 	at java.security.AccessController.doPrivileged(AccessController.java:770)
15:50:47       [exec] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
15:50:47       [exec] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
15:50:47       [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
15:50:47       [exec] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
15:50:47       [exec] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
15:50:47       [exec] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
15:50:47       [exec] Result: 1
```

I suspect this problem is related to https://github.com/AdoptOpenJDK/openjdk-build/issues/1445

**Comment by pshipton** [comment]
@sxa555 @ashu-mehra

**Comment by sxa555** [comment]
This will have been due to https://github.com/AdoptOpenJDK/openjdk-build/issues/1445 where I bumped up the compiler used to 11 to resolve it without really knowing what I was doing because no-one else was addressing the failure. If someone with more knowledge of the domain can intervene that will help us resolve it in a better way.

@smlambert can you suggest the correct solution based on the error message that suggests it's looking for java9 or later yto build with?

**Comment by pshipton** [comment]
@sxa555 it would be great if you can back out the bad change until the proper solution is determined. The OpenJ9 project can't run any jdk8 functionality testing until this is resolved.

**Comment by sxa555** [comment]
What specifically is the OpenJ9 project picking up? If I back out what I did the asmtools build will fail as it has been for the last five weeks, and the "last good" build will be the one built with JDK11 this week. I need advice from someone who understands this dependency as to what the correct course of action is. just reversing what I did won't resolve this.

If you are picking up "last good" I could in theory revoke the change, break the build, delete all my JDK11-built ones and then hope your builds will pick up the last good one built with JDK8 from whatever code was in there from mid-November

**Comment by sxa555** [comment]
asmtools build link for reference: https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/

**Comment by pshipton** [comment]
I see reference to openjdk-tests/TKG/../TKG/lib/asmtools.jar which I assume got updated by the asmtools job and would need to be reverted to one that works.

**Comment by sxa555** [comment]
Where is that relative to? `openjdk-tests` and `TKG` are different repositories under github.com/AdoptOpenJDK so I can't figure out what location that is. Neither has an `asmtools.jar` in it. The job I referenced has an `asmtools.jar` artifact but that's not in the path you mentioned

**Comment by sxa555** [comment]
I have backed out the change so it is attempting to build with java 8 again so the original problem is back in https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/205/console

**Comment by pshipton** [comment]
If the `-source 9` and/or `-target 9` is removed, perhaps the build would work with java 8 and fix the problem.

The following output from the working build (https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/204/) is a hint of what is going on. If you can find the script which does this and see what it's actually doing, then it's hopefully obvious how to move back to the previous working version.
```
BUILD SUCCESSFUL
Total time: 8 seconds
Moving down to ../../asmtools-7.0-build
Asmtools artifact = asmtools-7.0
Archiving asmtools*.jar file
Moving into asmtools-7.0-build/dist
tar-ing asmtools-7.0.zip into asmtools-7.0.tar
asmtools-7.0.zip
Moving asmtools-7.0.tar to ../..
gzipping asmtools-7.0.tar
Creating checksums for asmtools.jar and asmtools-7.0.tar.gz
Moving into asmtools
```

**Comment by pshipton** [comment]
I would be a good idea to cache the artifacts from the last working build https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/188/ before they are flushed from the history by newer builds.

**Comment by pshipton** [comment]
Found this https://github.com/AdoptOpenJDK/TKG/blob/899b2e59dc3389b3bef505d4bbee493b01c3eef2/scripts/getDependencies.pl#L107-#L113

**Comment by llxia** [comment]
> I see reference to openjdk-tests/TKG/../TKG/lib/asmtools.jar which I assume got updated by the asmtools job and would need to be reverted to one that works.

In openj9, we have a stage job [test.getDependency ](https://ci.eclipse.org/openj9/job/test.getDependency/ ), which gets all test dependent jars. And it runs the script to get asmtools.jar from`lastSuccessfulBuild ` https://github.com/AdoptOpenJDK/TKG/blob/899b2e59dc3389b3bef505d4bbee493b01c3eef2/scripts/getDependencies.pl#L108
Then all test builds copy from test.getDependency job.

If this issue is fixed, we need to rerun the stage job [test.getDependency ](https://ci.eclipse.org/openj9/job/test.getDependency/ ) in openj9.

**Comment by sxa555** [comment]
171 was already permanently saved, however I've done the same to 188 (Yesterday I increased the number of builds kept so we have a bit more of a window now anyway.

`-target 9` comes from the upstream `asmtools` project - it's NOT something we do. We build from the tip of their repository.

http://hg.openjdk.java.net/code-tools/asmtools/rev/f64487642f6d will be the change that changed the behaviour.

**Comment by pshipton** [comment]
If you can somehow restore the https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/ `Last Successful Artifacts` to the artifacts from https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/188/, hopefully that will fix it until Jan.

**Comment by sxa555** [comment]
FYI If I patch `build.xml` back to say `1.8` it fails to build now as per https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/206/console

**Comment by sxa555** [comment]
The only practical way I can do that is to delete the ones I built with JDK11 as per my second comment

**Comment by sxa555** [comment]
I've deleted 201 202 204

**Comment by llxia** [comment]
I will relaunch the ` test.getDependency ` in openj9 and stop the auto job scheduling.

**Comment by llxia** [comment]
rerun above 447:
https://ci.eclipse.org/openj9/job/Test_openjdk8_j9_sanity.functional_ppc64le_linux_Personal/448/

`jasm_generator ` passed compilation.

**Comment by pshipton** [comment]
Trying a jdk8 functionality test build https://ci.eclipse.org/openj9/view/Test/job/Grinder/593

**Comment by sxa555** [comment]
Looks to have passed. I'll close this and use 1445 to resolve it going forward

**Comment by pshipton** [comment]
The previous build worked, although it may have been too much of a subset to show the problem. Trying a full sanity.functional build https://ci.eclipse.org/openj9/view/Test/job/Grinder/594/

**Comment by pshipton** [comment]
The full build worked, so I stopped it.
