### ISSUE TITLE
ppc64_linux big endian support?

### ISSUE THREAD

**Issue by pshirshov** [AdoptOpenJDK/openjdk-build#1455]
Hi!

I'm playing with a G5 Mac and noticed that there is no modern Java available for it.
I've found this bug: https://github.com/AdoptOpenJDK/openjdk-build/issues/561 , so, from what I can understand, you need a PPC64 host, I may provide one.

I've tried to build it on my own, though failed immediately on jdk9 because of fatal deprecation warnings.

Not sure why did it fail. From what I understand this should turn off fatal warnings:

```
./makejdk-any-platform.sh -J /usr/lib64/openjdk-8/ --make-args 'COMPILER_WARNINGS_FATAL=false' jdk9u
```

By the way, there are OpenJDK builds which work on PPC64 BE: https://sap.github.io/SapMachine/

So, it should be an observable job to support it in Adopt.

**Comment by sxa555** [comment]
Can you post the error you received? Bear in mind that many Linux distributions (including Debian and Ubuntu) don't have an official PPC64-BE distribution any more, and while CentOS 7 does, even if we found someone willing to maintain it, we'd still have to source appropriate hardware from somewhere.

**Comment by pshirshov** [comment]
> Can you post the error you received?

May do it bit later. Though it was all about deprecation warnings (in glibc headers as far as I can remember).

> Bear in mind that many Linux distributions (including Debian and Ubuntu) don't have an official PPC64-BE

I've been playing with Gentoo :)

> we'd still have to source appropriate hardware from somewhere.

These machines are damn cheap on ebay, sometimes it's even possible to buy a PPC Xserver.

> if we found someone willing to maintain it,

I don't think it's very important but it's just sad that these (still perfectly capable) machines are getting obsolete just because of the lack of software updates.

**Comment by gdams** [comment]
@sxa555 the OSUOSL does actually host ppc64 big endian hardware that we have access to. Justifying big endian to the project was harder though as it was not widely supported anymore.

**Comment by gdams** [comment]
TSC discussed this, general consensus was to not support ppc64_linux big-endian as it's not an officially supported platform in the OpenJDK code.
