### ISSUE TITLE
Configure OpenJ9 xlinux builds for jdk8 jdk11 with --enable-jitserver

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#1464]
Pls configure OpenJ9 xlinux builds for jdk8 and jdk11 with --enable-jitserver
This includes both the head stream and the January (OpenJ9 0.18.0) release.

https://github.com/eclipse/openj9/pull/8147
https://github.com/eclipse/openj9/issues/7841

@mpirvu fyi

**Comment by andrew-m-leonard** [comment]
does that include xLinuxXL ?

**Comment by andrew-m-leonard** [comment]
Requires "protoc"
Current Ubtuntu 16.04 distribution is not late enough either, 2.6.1, needs 3.5.1. Not sure what slaves have?

**Comment by pshipton** [comment]
At the OpenJ9 project we are using protobuf 3.7.1 to build it.

**Comment by mpirvu** [comment]
Indeed we standardized protobuf 3.7.1 across all linux platforms.
Moreover, if build machines have an older version of protobuf, it needs to be uninstalled because we've seen that it can cause linking problems.

**Comment by pshipton** [comment]
@mpirvu can you please answer about whether --enable-jitserver should be done for xLinuxXL builds? (Note it's enabled at OpenJ9).

**Comment by mpirvu** [comment]
> does that include xLinuxXL
For uniformity we should probably do xLinuxXL as well, though JITServer typically helps with small containers whereas xlinuxxl is normally used for applications with very large heaps.

**Comment by andrew-m-leonard** [comment]
Adopt slaves have protoc 3.5.1

**Comment by sxa555** [comment]
> Indeed we standardized protobuf 3.7.1 across all linux platforms.

That's a new requirement on or systems then as we explicitly set it to 3.5.1 which I believe is the one that your configure check looks for. @jdekonin based on @pshipton's comment above have you put a different version on the OpenJ9 machines than what's [in our playbooks](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Protobuf/tasks/main.yml)?

**Comment by AdamBrousseau** [comment]
Spot checking a few x/p/z internal and external it seems x has 3.5.1 and p/z have 3.7.1

**Comment by sxa555** [comment]
For the purposes of this x is the only important one, so you have the same as us ...

**Comment by mpirvu** [comment]
x can work well with protobuf 3.5.1.  It was suggested to move xlinux up to 3.7.1 so that all platforms have the same version, but this is not strictly required

**Comment by andrew-m-leonard** [comment]
seem to be linking issues: https://github.com/eclipse/openj9/issues/8267

**Comment by sxa555** [comment]
Fixed - now building at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9-linuxXL/455/console

Bear in mind that only the first build box is configured appropriately for this at present, so I've removed the `gcc73` tag from the other one which will stop OpenJ9 builds running on it.

**Comment by mpirvu** [comment]
@sxa555 I was wondering about the status of this issue. Are the nightly xlinux builds done at adoptopenjdk supposed to have JITServer code compiled in now?

**Comment by andrew-m-leonard** [comment]
not until we implement this issue

**Comment by sxa555** [comment]
@mpirvu The quarterly releases will have that option enabled - nightlies will follow shortly after. This support was added at the last minute and therefore we had an effective code freeze on adjustments to the build scripts during the release cycle

**Comment by mpirvu** [comment]
Thanks @sxa555

**Comment by andrew-m-leonard** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/1482/files
