### ISSUE TITLE
Incorrect year in binary names

### ISSUE THREAD

**Issue by grahampugh** [AdoptOpenJDK/openjdk-build#1466]
**Platform:**
Mac
**Architecture:**
X64
Please describe the issue that you are having with our binaries and if possible how to recreate it.

The releases for AdoptOpenJDK 11 are named incorrectly on github: the 2019-12-31 build is mis-tagged as jdk11u-2020-12-31-15-31. There are a few others mislabelled as 2020 too. This plays havoc with automation scripts that grab the latest release.

**Comment by sxa555** [comment]
@johnoliver spotted this yesterday afternoon too. Thanks for raising the issue

**Comment by johnoliver** [comment]
@sxa555 I think this is different, this issue is the Nov 31st year rollover issue we had, we should just delete https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk11u-2020-12-31-15-31

**Comment by tellison** [comment]
+1 from me to removal

**Comment by sxa555** [comment]
That was horrible. The releases were presumably a bit too bug and github timed out trying to delete them so I had to start removing each file individually. Now done though.
