### ISSUE TITLE
Enable building OpenJDK HEAD at AdoptOpenJDK

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk-build#1467]
Right now the latest upstream OpenJDK HEAD tree isn't being built at AdoptOpenJDK AFAIK. There should be a build job building latest jdk/jdk tree.

Perhaps start with Hotspot builds only as a start.

**Comment by jerboaa** [comment]
I'll be working on this in the next few weeks.

**Comment by jerboaa** [comment]
Checklist so far:

- [ ] Ensure openjdk14-binaries and openjdk15-binaries repositories exist. https://github.com/AdoptOpenJDK/TSC/issues/131
- [ ] Update latest JDK version to 15
- [ ] Create JDK 14 pipeline build jobs
- [ ] Create JDK 15 pipeline build jobs

**Comment by sxa555** [comment]
@jerboaa As your going through this (or afterwards, whatever!) can you make a note of everything you do so we can add it to the docs (https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md) for others to replicate please? That was the one section of there I knew was missing and I hadn't put anything together for yet ;-)

**Comment by jerboaa** [comment]
> @jerboaa As your going through this (or afterwards, whatever!) can you make a note of everything you do so we can add it to the docs (https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md) for others to replicate please? That was the one section of there I knew was missing and I hadn't put anything together for yet ;-)

OK. I'll take notes and put something together once this actually works.

**Comment by jerboaa** [comment]
Patch to support building JDK 15 locally with AdoptOpenJDK build scripts. https://github.com/AdoptOpenJDK/openjdk-build/pull/1484

**Comment by karianna** [comment]
Can this now be closed?

**Comment by jerboaa** [comment]
> Can this now be closed?

No, not yet. There is no jdk-head pipeline as of yet. See the checklist above.

**Comment by jerboaa** [comment]
JDK 15 (HEAD) build pipeline changes proposed here: https://github.com/AdoptOpenJDK/openjdk-build/pull/1501

I'd appreciate reviews! Thanks.

**Comment by jerboaa** [comment]
With #1501 merged, I'll close this ticket.

**Comment by jerboaa** [comment]
For reference current JDK HEAD pipeline (running nightly) is here:
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/
