### ISSUE TITLE
Request to archive OpenJDK source tips file as part of binary tar

### ISSUE THREAD

**Issue by llxia** [AdoptOpenJDK/openjdk-build#1476]
We have `source_tips` and `source-revision-tracker` in the build tree for SHA info.

```
For JDK 8u hotspot, it is in build/linux-x86_64-normal-server-release/source_tips:
$ cat build/linux-x86_64-normal-server-release/source_tips
 .:d4ae3d8b2cd2 corba:d4d4f7f07a86 hotspot:127e100fb80e jaxp:cc46d0ec5597 jaxws:3a911ec83c7e jdk:6f7954907722 langtools:92a07f0a1bb1 nashorn:319c1b31d551
For JDK 11+, this should be in build/linux-x86_64-normal-server-release/support/src-rev Example:
$ cat build/linux-x86_64-server-release/support/src-rev/source-revision-tracker
.:hg:3009b27660be+
```

However,  the file is not in the AdoptOpenJDK Jenkins Build Artifacts. For example, https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/

We would like to request to archive the source tips file as part of binary tar, so the downstream builds can get this information. This is needed as part of AQA BoM https://github.com/AdoptOpenJDK/openjdk-tests/issues/1169

**Comment by llxia** [comment]
fyi @smlambert @jerboaa

**Comment by austin0** [comment]
Looked into this a bit, jdk8u only supports mercurial `hg` so `source_tips` is currently never used (https://github.com/AdoptOpenJDK/openjdk-build/pull/2036 exists to fix this). However jdk11/15/etc can retrieve info for both mercurial and git, so `source-revision-tracker` contains this git sha of the mirror repo. OpenJ9 has their own patch to get the sha of OpenJDK/OpenJ9/OMR for source revision. Main takeaway is that eventually the contents of source_tips and source-revision-tracker both make their way into the `SOURCE = ""` tag in the release file i.e. 
```
IMPLEMENTOR="AdoptOpenJDK"
IMPLEMENTOR_VERSION="AdoptOpenJDK"
JAVA_VERSION="11.0.8"
JAVA_VERSION_DATE="2020-07-14"
MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.vm.ci jdk.management jdk.unsupported jdk.internal.vm.compiler jdk.aot jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.internal.le jdk.internal.opt jdk.internal.vm.compiler.management jdk.jartool jdk.javadoc jdk.jcmd jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.pack jdk.rmic jdk.scripting.nashorn jdk.scripting.nashorn.shell jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported.desktop jdk.xml.dom jdk.zipfs"
OS_ARCH="x86_64"
OS_NAME="Linux"
SOURCE=".:git:9e9102503256"
```

Is this easy enough to parse or would there still be a benefit to archiving the individual files?

**Comment by llxia** [comment]
@austin0 Where is the release file located?

**Comment by austin0** [comment]
It's directly inside the root folder after you untar the binary.

<img width="449" alt="Screen Shot 2020-08-25 at 15 09 01" src="https://user-images.githubusercontent.com/23284299/91185088-48b5e180-e6e5-11ea-9148-e90d86466747.png">

**Comment by llxia** [comment]
Thanks @austin0 . From the test perspective, we do not need this file to be archived separately.
