### ISSUE TITLE
add support for Android....

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#149]
I have done some research and it looks like OpenJDK can be built on Android, This seems like a pretty interesting project to get involved with... Assuming that my research is correct we should explore getting this working. CC @neomatrix369

**Comment by neomatrix369** [comment]
@gdams looks pretty interested, how do we go about building this on our local environment and on the CI? Do you have access to some sort of Android emulator environment?

Please share anything you have on this topic - I'd like to be involved.

**Comment by neomatrix369** [comment]
Found a resource for Android Docker images - https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=android&starCount=0 (Docker Hub)

**Comment by M-Davies** [comment]
@neomatrix369 @gdams any more movement on this?

**Comment by karianna** [comment]
This is to do with the OpenJDK mobile project, if we have users asking us to build that we can in the future, but closing for now.
