### ISSUE TITLE
Symbol resolution failure running java -version with OpenJDK8_ppc64_AIX_jdk8u141-b15

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#150]
I downloaded the latest binary of OpenJDK8_ppc64_AIX_jdk8u141-b15
and tried to run java -version on several aix ppc64 machines that I have access to (each with slightly different versions of AIX), and encountered a variety of symbol resolution failures.  

Here are some examples (AIX5.2/AIX6.1/AIX7.1 respectively):

aix52vm5% ./java -version
exec(): 0509-036 Cannot load program java because of the following errors:
rtld: 0712-001 Symbol ___strcmp64 was referenced
      from module java(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol ___strcpy64 was referenced
      from module java(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol __pth_init was referenced
      from module java(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol __pthread was referenced
      from module java(), but a runtime definition
      of the symbol was not found.
rtld: 0712-002 fatal error: exiting.

----------------------------
aix61compvm15% ./java -version
exec(): 0509-036 Cannot load program java because of the following errors:
        0509-130 Symbol resolution failed for java because:
        0509-136   Symbol ___strcmp64 (number 9) is not exported from
                   dependent module /usr/lib/libc.a[shr_64.o].
        0509-136   Symbol ___strcpy64 (number 12) is not exported from
                   dependent module /usr/lib/libc.a[shr_64.o].
        0509-192 Examine .loader section symbols with the
                 'dump -Tv' command.

-------------------------------
aix71p7vm35% ./java -version
Error: dl failure on line 893
Error: failed /openjdk/jdk8u141-b15/jre/lib/ppc64/server/libjvm.so, because       0509-130 Symbol resolution failed for /openjdk/jdk8u141-b15/jre/lib/ppc64/server/libjvm.so because:
        0509-136   Symbol __setjmp (number 50) is not exported from
                   dependent module /usr/lib/libc.a[shr_64.o].
        0509-022 Cannot load module /openjdk/jdk8u141-b15/jre/lib/ppc64/server/libjvm.so.
        0509-026 System error: Cannot run a file that does not have a valid format.
        0509-192 Examine .loader section symbols with the
                 'dump -Tv' command.

Do I need a particular machine configuration or to setup?

**Comment by sxa555** [comment]
@smlambert I would expect problems on anything before AIX7, but what's the output from "oslevel -s" on your 7.1 machine? It works ok on mine:

```$ ./java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2017_07_19_05_28-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)
$ oslevel -s
7100-03-05-1524```

**Comment by smlambert** [comment]
Ok, thanks, I see that 7100-04-00-0000 does work:

aix71p8vm1% ./java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2017_07_19_05_28-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

but the machine I originally tried on was 7100-01-03-1207.

**Comment by sxa555** [comment]
Adding the important tag mostly because we need to conclude whether it should work on earlier versions or if we're just going to support the later OS releases based on the information in https://github.com/AdoptOpenJDK/openjdk-build/wiki/%5BWIP%5D-Minimum-OS-levels - my gut feel is the latter unless there is demand for anything else.

**Comment by karianna** [comment]
Fixed some time ago
