### ISSUE TITLE
Investigate & implement "concurrent" AdoptOpenJDK "build pipeline" support

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1500]
Summary
-----
Currently, little experimentation has been conducted on the AdoptOpenJDK build pipelines to see if they can run synchronously on the master node. The general belief is that they cannot due to shared workspaces but I would like to conduct some testing to ensure that this is true. If the pipelines can be run concurrently, it would speed up both release and nightly build/testing jobs greatly.

I would like to test Adopt's build pipeline on ~Wednesday 29th January 2020 from 2pm to 6pm GMT (TBC on Slack)~ for the 1st of 2 phases. This is to investigate the current limits of the adopt pipeline and see where it can be improved. 

Objectives
-----
- [ ] Run a series of jobs concurrently at Adopt to see where the limitations lie. These include:
  - Running two jdk11-openj9 builds (no tests) concurrently **(1st Phase)**
  - Running two jdk11-hotspot builds (no tests) concurrently **(1st Phase)**
  - Running two jdk11-openj9 builds (with tests `sanity.functional`, `sanity.openjdk`) concurrently **(2nd Phase)**
  - Running two jdk11-hotspot builds (with tests `sanity.functional`, `sanity.openjdk`) concurrently **(2nd Phase)**
- [ ] Review/Discuss the above results. If the builds/tests pass, then the jobs could probably run concurrently in some limited situations. If there is an unexpected failure: 
- [ ] Investigate how adopt pipeline concurrency can be achieved based off of the results produced above.

**Comment by M-Davies** [comment]
The master node is currently full so will delay this until it has been cleaned up

**Comment by M-Davies** [comment]
Master node has been cleaned up. Running two phase one builds `jdk11-x64Linux-openj9`
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/730/console
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/731/console

**Comment by M-Davies** [comment]
For https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/730/ and https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/731/ concurrency running was enabled. 

- Both builds ran fine on the master node but created the same downstream job on `build-digitalocean-centos69-x64-1` even though they are supposed to be separate pipelines. During abortion, the `refactor_openjdk_release_tool` was scheduled correctly (one for 730, one for 731) 
- `Warning: (create_job_from_template.groovy, line 51) concurrentBuild is deprecated`. It appears we are using an old version of concurrency configuration. This may not affect this test but still should be looked at https://issues.jenkins-ci.org/browse/JENKINS-53359 in case it does. 
- Both jobs regenerated themselves after creation but they reference platforms and implementations that were not specified in the parameters (`linux-x64-openj9` was the only parameter)? 
```
Existing items:
    GeneratedJob{name='build-scripts/jobs/jdk11u'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9'}
Unreferenced items:
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-hotspot'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-aix-ppc64-openj9'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-hotspot'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9-linuxXL'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-arm-hotspot'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-ppc64le-hotspot'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-ppc64le-openj9'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-ppc64le-openj9-linuxXL'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-s390x-hotspot'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-s390x-openj9'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-s390x-openj9-linuxXL'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-x64-hotspot'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-linux-x64-openj9-linuxXL'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-mac-x64-hotspot'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9-macosXL'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-windows-x64-hotspot'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-windows-x64-openj9'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-windows-x64-openj9-windowsXL'}
    GeneratedJob{name='build-scripts/jobs/jdk11u/jdk11u-windows-x86-32-hotspot'}
```
This may cause concurrency issues when the jobs clean old configs (and maybe, each others new configs) and then try to run their respective pipelines. There is an old issue open for this https://github.com/AdoptOpenJDK/openjdk-build/issues/1328

cc @karianna

**Comment by M-Davies** [comment]
In order to avoid regenerating the jobs and causing conflicts during concurrent builds, @andrew-m-leonard has suggested moving [createJob()](https://github.com/AdoptOpenJDK/openjdk-build/blob/5e8e4b5b14e111837dca2a7c3a2c64c9f0aa236f/pipelines/build/common/build_base_file.groovy#L236) into a seperate jenkins job that is triggered if there are any changes to the job configurations. This way, all downstream jobs will be generated using the parameters passed in from the upstream job (rather than the default configuration currently in `BUILD_CONFIG`). If there are any changes to the configurations, the default job configs will be regenerated using this jenkins job and then passed to the downstream job after checking they are compliant and won't cause race conditions.
There are two potential ways we could go about doing this:

1) Modify [build_base_file.groovy](https://github.com/AdoptOpenJDK/openjdk-build/blob/5e8e4b5b14e111837dca2a7c3a2c64c9f0aa236f/pipelines/build/common/build_base_file.groovy) to check if there is a new contribution to any of the [jobConfigs](https://github.com/AdoptOpenJDK/openjdk-build/tree/5e8e4b5b14e111837dca2a7c3a2c64c9f0aa236f/pipelines/jobs/configurations) OR [pipeline_template](https://github.com/AdoptOpenJDK/openjdk-build/blob/5e8e4b5b14e111837dca2a7c3a2c64c9f0aa236f/pipelines/jobs/pipeline_job_template.groovy). This would involve a check to make sure the commit sha's from the start and current stage of the pipeline match and if they do not, regenerate the job configs to ensure they remain the same throughout the whole pipeline **[1]**. 

2) Move `createJob()` out of the `build_base_file` into its own job template to ensure it remains completely separate from the pipeline. So the pipeline would run `build_base_file` up to where `createJob` currently is and then wait for this new jenkins job to complete before executing the downstream builds. This new job would do the steps described in **[1]** except using a [github-hook](https://stackoverflow.com/questions/47152744/trigger-jenkins-build-if-only-a-specific-file-is-changed) to ensure that the job will only kick off if there are any changes to the configs. It would run on a seperate master machine that would pass the configuration back upstream to the pipeline when it's done. 

@andrew-m-leonard @johnoliver I'm not sure what would be the more suitable route to go down for attempting this. Route 2 sounds cleaner and more user friendly to view on Jenkins itself but it will use up precious machine resources and may end up with more spaghettified code compared to Route 1 (which would just be adding a check between two commit SHA's)

**Comment by johnoliver** [comment]
@M-Davies I think I agree that 2 does sound cleaner, and if you feel that there is a way of structuring things that is less spaghetti feel free to propose it, I do agree that the current structure of this repo/build is not the most intuitive.

To clarify option 2 I think what you are getting at is just that you have a regenerate job, and that runs every time there is a commit in the build repo, that regenerates all the individual build jobs. Is that correct? When you say:

"So the pipeline would run build_base_file up to where createJob currently is and then wait for this new jenkins job to complete before executing the downstream builds"

That makes it sounds like the regeneration would still be part of every nightly/release run, just as a separate job rather than being 1 script. Would that not still have the same issues that we currently have?

**Comment by M-Davies** [comment]
Adding a method to the job helper that queries jenkins whether a pipeline job is in progress or queued up https://github.com/AdoptOpenJDK/openjdk-jenkins-helper/pull/27

This will be used in the regeneration job

**Comment by M-Davies** [comment]
^^ WIP PR for the config regeneration job

**Comment by M-Davies** [comment]
Current stage: 
- WIP PR: https://github.com/AdoptOpenJDK/openjdk-build/pull/1547
- 2 Jenkins helper PR's to assist the PR above
  - ~`jobIsRunning()`https://github.com/AdoptOpenJDK/openjdk-jenkins-helper/pull/27~ MERGED
  - `getJobFolder()` https://github.com/AdoptOpenJDK/openjdk-jenkins-helper/pull/29
- Working with @andrew-m-leonard to get a test job on jenkins up and running using the code from my fork https://github.com/M-Davies/openjdk-build/tree/concurrent_test to ensure that the Regenerate stage of the WIP PR will work

**Comment by M-Davies** [comment]
Current stage:

- Test job is running at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/morgan_pipeline_generator/ using the master file https://github.com/M-Davies/openjdk-build/blob/concurrent_test/pipelines/build/regeneration_pipeline.groovy as a starting point. 
- The aim of it is to have all possible job dsl configurations generated using this job and removing the old `createJob()` method that already does this in the build_base_file. So when the pipeline eventually hits the spot where it would need to create the job, it should instead find that it has already been done for it. 
- The job relies on a heavy use of the Jenkins API to pull in all of the pipeline details and downstreamJob names which I feel is both a drawback and a boon for it (Sacrificing a single point of failure for up to date data on what the Adopt Jenkins is running at the time).
- My current testing is experimenting with iterating through the `openjdk_pipeline.groovy` files so the right configuration is loaded at the right time. I hope to have this job in delivered form mid-end of next week.

**Comment by M-Davies** [comment]
This is near to being completed. Just need to sort out how to pass the [parameters](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/786/parameters/) into the [IndivdualBuildConfig](https://github.com/M-Davies/openjdk-build/blob/266e07875f433e0dcf8002b46c6b5e812b706569/pipelines/build/common/config_regeneration.groovy#L102) for each job. Otherwise we would just end up with a static job everytime 😅
