### ISSUE TITLE
JDK8 configure argument --with-macosx-codesign-identity not supported

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-build#1502]
All builds in the jdk8 pipeline are failing with:
```
Running ./configure with arguments 'bash ./configure --verbose  --with-milestone=fcs --with-user-release-suffix=202001280430 --with-vendor-name=AdoptOpenJDK --with-update-version=242 --with-build-number=b08 --with-boot-jdk=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home --with-macosx-codesign-identity="" --enable-ccache --with-debug-level=release --disable-zip-debug-info --disable-debug-symbols --with-x=/usr/include/X11 --with-alsa=/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/./build//installedalsa --with-jvm-variants=server  --with-freetype=/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/./build//installedfreetype '
Should have the source, I'm at /Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src
Currently at '/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-hotspot/workspace/build/src'
Running generated-configure.sh
configure: error: unrecognized options: --with-macosx-codesign-identity
configure exiting with result code 1
```

**Comment by M-Davies** [comment]
`--with-macosx-codesign-identity` is set https://github.com/AdoptOpenJDK/openjdk-build/blob/f8e552c615c8d6a21bef970b55ea471734679be0/sbin/build.sh#L85

May have been caused by https://github.com/AdoptOpenJDK/openjdk-build/commit/f8e552c615c8d6a21bef970b55ea471734679be0#diff-70562ee8a1ade1c466965b291bbacf4a since `BUILD_CONFIG` was changed to use the feature number instead of the jdk version

**Comment by adam-thorpe** [comment]
No this line was recently added to support mac code signing. It would look like it is not intended for jdk8 but there is nothing in the code that prevents it so I would assume that a simple check is needed

**Comment by adam-thorpe** [comment]
The problem originates back before that commit

**Comment by Willsparker** [comment]
Came from here : https://github.com/AdoptOpenJDK/openjdk-build/pull/1463 I think :-)

**Comment by gdams** [comment]
hmm yeah, we should only run this function if you're on jdk11 https://github.com/gdams/openjdk-build/blob/a8cee3828352e9e6381d7f37752984d432490cbe/sbin/build.sh#L83-L86

**Comment by gdams** [comment]
that arg only get's added on jdk11 https://github.com/AdoptOpenJDK/openjdk-build/pull/1463/files#diff-521c2d1e3ad3ed50a7d814ac9f305739R60

**Comment by gdams** [comment]
I'll take a look
