### ISSUE TITLE
Feat: Notification on pipeline/grinder completion

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1504]
Summary
-----
Using the [Jenkins plugin](https://jenkins.io/doc/pipeline/steps/slack/#slacksend-send-slack-message) on Slack, it should be possible for our Grinders and Pipelines to send a notification to the AdoptOpenJDK slack channel when a job is complete. This is more of a quality of life improvement than something of great necessity, the life improvement being that you will be alerted when your build has completed.

Objectives
-----
- [x] ~Identify whether Adopt's slack space supports direct messages from Jenkins. This is true for Enterprise level slack workspaces but unknown for the [standard](https://adoptopenjdk.slack.com/plans/standard?entry_point=team_menu_plan_info) subscription that Adopt has. This will be tested soon. If the Adopt slack cannot support DM's, then it's unlikely that Grinder jobs will benefit from this feature.~ https://github.com/AdoptOpenJDK/openjdk-build/issues/1504#issuecomment-579691786
- [ ] Create two new parameters for Grinders and jdk-pipeline jobs. One will contain the slack channel/user that will be receiving the message. The other will be a checkbox that, if true, will notify the user on a successful build as well as a failed one.

**Comment by jerboaa** [comment]
Have good old email notifications been considered?

**Comment by M-Davies** [comment]
> Have good old email notifications been considered?

That's might be a backup if the Adopt slack doesn't support DM's for grinders 😄. Using email would slightly negate the point of implementing this since it doesn't provide an instant ping for the user.

**Comment by AdamBrousseau** [comment]
>Create two new parameters

You could use 1 param and simply check if it's set. 
ie.
```
if (SLACK_HANDLE) { // or params.SLACK_HANDLE
   slackSend ...
}
```
I know the test team (cc @smlambert ) are trying to limit or reduce the amount of params the test pipelines use.

**Comment by M-Davies** [comment]
>  Identify whether Adopt's slack space supports direct messages from Jenkins. This is true for Enterprise level slack workspaces but unknown for the standard subscription that Adopt has. If the Adopt slack cannot support DM's, then it's unlikely that Grinder jobs will benefit from this feature.
> 

The adopt slack does not have a high enough payment plan to support DM's but does support channel notifications. Therefore, I don't think there would be much point implementing this for grinders. The email idea has merit, I think that would need some more discussion on how it would be implemented. 

Pipelines however, may still benefit from this as it would be good to have a channel at Adopt for when release and nightly builds are completed. Not just for the initiator of the job, but also those who will be looking to triage the results.  

Following on from what @AdamBrousseau mentioned, what is your opinion on the usefulness after this finding @smlambert ?

**Comment by smlambert** [comment]
I personally dislike automated Slack messages and end up having to mute channels that they are sent to.  It is also true that given our test pipeline script already has TOO many parameters, I had made the bold statement that for any new one we consider adding, we would have to consider removing one.   ;)

That being said, I will like to see what you are proposing and how it may be tuned to suit the folks who may want to get pummelled with slack messages versus just checking in to the job they launched (push vs pull).

**Comment by M-Davies** [comment]
Current stage: Investigate alternative methods that cut down on message spam. Instigate discussions within the adopt community of an alternative or less intrusive solution

- Email -> Same principle, using email. Simpler, personalised and likely jenkins compatible. Hard to implement, defeats the point of instant feedback a little bit, still have a spam problem (less than slack however).
- TRSS view of running/recently-completed jobs -> Easy to implement (just add a new page to trss, move some code around and good to go), no spam. Unsure whether it can be customized on a user to user basis, no instant notification of a finished job. With TRSS being down at the moment, it may not be implemented properly for a little while.
- Jenkins view of running/recently-completed jobs -> Only requires installing a new plugin that enables filtering jobs by those which you have started, no programming or 3rd party necessary, integrated within jenkins. Already at optimum plugin capacity, may not work in the way we want it to.

**Comment by M-Davies** [comment]
I'm going to shelve this as I don't really see the need for it and there's a lot more high priority work on for me at the moment. Regarding the alternatives above: 
- Email seems a bit too finky and we're basically moving the problem of spam
- TRSS seems to do a decent job of showing test failures already. A view could be added for grinders but I doubt it would really be used and is more of an issue for TRSS than build
- We already have a view of [running jobs for a version](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/) and you can usually find your name in there relatively easily. Besides, I don't think adding another plugin to jenkins is a good idea anyway
