### ISSUE TITLE
Openj9 11.0.6 for Windows x86 is missing (hotspot still provides one)

### ISSUE THREAD

**Issue by patric42** [AdoptOpenJDK/openjdk-build#1506]
Hi,

I'm wondering that, despite the effort the OpenJ9 team made for supporting 32bit Windows with the splitheap option (which makes it rather unique for using large heaps on that platform), exactly that build is missing for the Java 11 platform.

Could this be added again?

Thanks!

**Comment by karianna** [comment]
@lumpfish  - Can you comment?

**Comment by lumpfish** [comment]
@patric42 - you are correct that Windows x86-32 is not a platform supported by openj9 jdk11.
A complete list of supported platforms for each jdk release can be found at the Eclipse OpenJ9 web site here: https://www.eclipse.org/openj9/docs/openj9_support/

Enabling such support would need to start with a commitment from the Eclipse OpenJ9 community, perhaps raising a request via https://github.com/eclipse/openj9/issues.

What is your use case for needing openj9 jdk11 support on Windows x86?

**Comment by patric42** [comment]
Hi Simon,

on 29.01.20 at 12:07, Simon Rushton wrote:
> Enabling such support would need to start with a commitment from the Eclipse OpenJ9 community,
> perhaps raising a request via https://github.com/eclipse/openj9/issues.

Ok, I'll ask there for the reasons. Thank you :-)

> What is your use case for needing openj9 jdk11 support on Windows x86?

We are in the process of updating some of our applications to Java 11, but we still have some
customers on Windows x86. Given the usefulness of OpenJ9 on 8u on that platform I had hoped that one
day we'll might just bump the JVM to 11 and never look back (we have a webstart-alike program
starter with which we can deploy any JRE with the app).

So you can imagine my disappointment when I realized that for some reason, the OpenJ9 version of the
11 wasn't available on Windows x86.

It wasn't the bigger, 64 bit machines with more RAM which profited most of the OpenJ9, but the
smaller, slower machines with less RAM and x86 Windows OSes, which suddenly had a fast startup and
performant client, able to use more than 300MB RAM on that OS (issue of RAM fragmentation, which
OpenJ9 approached with a split heap).

And some of these machines are hard to replace... you get the picture. Corporate environments *sigh*

Anyways, thanks for the help,

/Patric

**Comment by MariusVolkhart** [comment]
@patric42 I came here wanting the same. See https://github.com/eclipse/openj9/issues/8773
