### ISSUE TITLE
Building and providing OpenJDK hsdis binaries

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#151]
Wiki for info: https://github.com/AdoptOpenJDK/jitwatch/wiki/Building-hsdis

How to build it on:
- Linux: https://www.chrisnewland.com/building-hsdis-on-linux-amd64-on-debian-369
- Windows: http://dropzone.nfshost.com/hsdis.htm
- MacOSX: https://www.chrisnewland.com/building-hsdis-amd64dylib-on-mac-osx-376

Ideally, we intend to build hsdis on the below platforms:

Windows (.dll)
Linux (.so)
OSX (.dylib)
FreeBSD (?)

_Note: there is something to note about the licensing of the binaries:
OpenJDK hsdis is GPLv2+CE, while GNU binutils is GPLv3 - users are responsible for ensuring the correct licensing is in place._ 

_Keeping licensing ethics in mind we must notify this on the download page when they are about to download it._

**Comment by neomatrix369** [comment]
Recently, there has been requests for this - we could consider un-iceboxing it

**Comment by karianna** [comment]
I'm afraid we've got other core issues to resolve first, but if a volunteer wants to jump on it then please go ahead!

**Comment by neomatrix369** [comment]
No worries, will figure out something

**Comment by adamfarley** [comment]
Is anyone still interested in making this happen someday, or can it be closed?

**Comment by aahlenst** [comment]
Providing downloads at Eclipse is likely going to be a challenge because of the binutils license (GPLv3). So let's close and if someone really wants it, we can still dust it off.
