### ISSUE TITLE
Pipelines at Adopt are being given incorrect version number to schedule tests

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-build#1511]
```
Requested test job that does not exist or is disabled: Test_openjdk-1_j9_sanity.openjdk_x86-64_mac
[Pipeline] }
[Pipeline] echo
Requested test job that does not exist or is disabled: Test_openjdk-1_j9_sanity.system_x86-64_mac
[Pipeline] }
[Pipeline] echo
Requested test job that does not exist or is disabled: Test_openjdk-1_j9_extended.system_x86-64_mac
[Pipeline] }
[Pipeline] echo
Requested test job that does not exist or is disabled: Test_openjdk-1_j9_sanity.perf_x86-64_mac
```
All versions are returning -1 instead of version number, I highly suspect this problem is in this method, will investigate and put in a fix

https://github.com/AdoptOpenJDK/openjdk-build/commit/f65ae15988a92a7f33d4c8fad6d6029f6b983615#diff-75a7dffda798a34c1274f4a064617cb2R67

**Comment by jerboaa** [comment]
If it's the line you've mentioned then I don't understand how it did work before. The premise is that `matcher.matches() == false`. In that case it would have thrown an error before, right?

**Comment by adam-thorpe** [comment]
Yeah I'm not too sure, I don't know groovy but couldn't see any other lines that would cause a problem so I'm trying to run the method and see what it outputs

**Comment by adam-thorpe** [comment]
Okay it's definitely this method, new method returns -1, old method returns 8 with "jdk8u" as input

**Comment by adam-thorpe** [comment]
I think the problem was the matches.matches is looking for a full match, you needed a find which is just going to look for a single or more digits

**Comment by jerboaa** [comment]
> I think the problem was the matches.matches is looking for a full match, you needed a find which is just going to look for a single or more digits

Ah, yes. Nice find (pun not intended).
