### ISSUE TITLE
MacOS jdk8 build failure with --with-sysroot enabled

### ISSUE THREAD

**Issue by adam-thorpe** [AdoptOpenJDK/openjdk-build#1525]
Failing since: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/447/ with
```
OpenJ9 compile complete
/usr/bin/make -s VERBOSE="-s" LOG_LEVEL="warn" -I /Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-openj9/workspace/build/src/make/common -f /Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-openj9/workspace/build/src/closed/OpenJ9.gmk SPEC=/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/spec.gmk stage_openj9_build_jdk
error: invalid or inappropriate API flag(s) specified
error: invalid or inappropriate API flag(s) specified
error: invalid or inappropriate API flag(s) specified
error: invalid or inappropriate API flag(s) specified
make[1]: *** [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/jdk/lib/compressedrefs/libcuda4j29.dylib] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/jdk/lib/compressedrefs/libj9dmp29.dylib] Error 1
make[1]: *** [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/jdk/lib/libjsig.dylib] Error 1
make[1]: *** [/Users/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/jdk/lib/j9vm/libjvm.dylib] Error 1
make: *** [j9vm-compose-buildjvm] Error 2
```
I believe tweaks made in https://github.com/AdoptOpenJDK/openjdk-build/commit/f5d645fe4aef9f628e8acc6e03fbf8c5b6e56f6c have caused this, perhaps how `--with-sysroot` is used in jdk8?

**Comment by sxa555** [comment]
@keithc-ca?

**Comment by keithc-ca** [comment]
I doubt it's related to `--with-sysroot`. Perhaps the version of `codesign` in Xcode 7.2 doesn't understand these options?
```
codesign --sign "$(MACOSX_CODESIGN_IDENTITY)" \
	--entitlements $(TOPDIR)/make/data/macosxsigning/entitlements.plist \
	--options runtime \
	--timestamp
```
As I understand it, those options are now required.

**Comment by karianna** [comment]
@gdams - Probably introduced by the codesign patch - can you take a look?

**Comment by gdams** [comment]
oh right, so @keithc-ca we cannot currently use that codesign arg on jdk8 as `--options runtime` is only available on macOS 10.13+. Assuming that OpenJ9 JDK8 needs to be built on Xcode 4 (same as hotspot) we won't be able to use this logic just yet. The last step here is to get JDK8 to compile on a newer Xcode version.

**Comment by keithc-ca** [comment]
I was going to prepare a PR to disable code signing for Java 8, but I see @gdams beat me to it.

BTW, I tried to find documentation for `codesign` from older versions of Xcode but failed. Does anyone know where to find that information?

**Comment by adam-thorpe** [comment]
So does this mean jdk8 builds of openj9 are not code signed?
