### ISSUE TITLE
makejdk.sh fails on Windows7/Docker-for-Windows

### ISSUE THREAD

**Issue by tneward** [AdoptOpenJDK/openjdk-build#153]
This could easily be due to missing requirements on the host, but I can't see what's failing.

Windows7, Docker for Windows installed. Docker works fine (I can docker pull openjdk images and run them without issue.)

Cloned this repo. Opened Docker-Terminal prompt, cd into repo root, issued "makejdk.sh" at the command line. When it reaches the step "Successfully tagged openjdk_container:latest", it issues the SECURITY WARNING about building a Docker image from Windows, and then fails with "standard_init_linux.go:187: exec user process caused "no such file or directory" ".

Seems pretty obvious that the process is looking to execute something that isn't on my PATH (or isn't installed?); some searching through generic Docker error messages suggests that might also be related to a /-vs-\ error, but I can't figure out what steps to take from here.

Is there something obvious I'm missing?

**Comment by karianna** [comment]
@tneward Can you try again with the latest scripts?  We think this should be resolved.

**Comment by gdams** [comment]
ping @tneward. Can this be closed?

**Comment by M-Davies** [comment]
@tneward . Can this be closed?

**Comment by karianna** [comment]
Closing, @tneward can reopen if he needs to (Hey Ted!)
