### ISSUE TITLE
AdoptOpenJDK 8u242 JIT enabled aarch32 build missing (Raspberry Pi)

### ISSUE THREAD

**Issue by justinyunke** [AdoptOpenJDK/openjdk-build#1531]
Hi --

The current AdoptOpenJDK arm (aarch32) release for 8u232 is unusable on the Raspberry Pi, causing a CPU 100% issue similar to that documented here: https://github.com/AdoptOpenJDK/openjdk-build/issues/1287

The daily build (8u252 series) does not experience this issue.

Can we please see an 8u24x or fixed 8u23x release in your repositories soon?

-- Justin

**Comment by karianna** [comment]
@gdams - did we miss this in the latest release?

**Comment by sxa555** [comment]
@karianna We are still missing JDK8/HS/arm32 (subject of this issue), JDK8/HS/aarch64 (I've been managing the resolution to a broken mirror for that one) and JDK13/HS/AIX

**Comment by sxa555** [comment]
We enabled the JIT on arm32/JDK8/HS and need to properly go through the contents of https://github.com/AdoptOpenJDK/openjdk-tests/issues/1548 to ensure it's safe before looking to release that one.

**Comment by justinyunke** [comment]
Thanks for answering so quickly.  Please post to this issue thread if there's something I can do to help.  I have Pi Zero/Pi 2/Pi 3/Pi 4 platforms on which I can build/run tests.

**Comment by karianna** [comment]
> We enabled the JIT on arm32/JDK8/HS and need to properly go through the contents of [AdoptOpenJDK/openjdk-tests#1548](https://github.com/AdoptOpenJDK/openjdk-tests/issues/1548) to ensure it's safe before looking to release that one.

Perhaps we could give @justinyunke an RC binary for him to test on his hardware?

**Comment by karianna** [comment]
I'm following up on AdoptOpenJDK/openjdk-tests#1548 - I'm personally OK with releasing this since it seems to be more about intermittent hardware failures than anything else.

**Comment by sxa555** [comment]
Currently awaiting advice from @johnoliver on the mirroring since I can't build the JIT-enabled version at the correct level from our mirror of the source repository. If we can't get this resolved soon I might just release a non-JIT version again :'(

**Comment by sxa555** [comment]
In the absence of an alternative solution being  forthcoming I have reverted the build jobs back to using the main JDK8u repository and will attempt to push out an 8u242 without a JIT (Consistent with previous releases) ASAP

**Comment by sxa555** [comment]
We've released 8u242 but without a JIT again as we can't easily build the GA level with JIT support unfortunately.

**Comment by sxa555** [comment]
@karianna Since we haven't got a JIT-enabled GA JDK8/aarch32 build at the moment, the original problem description still stands, so I'm not sure it's appropriate to close this.

**Comment by karianna** [comment]
@sxa We can close this now correct?  We have test failures, but there is a working binary?

**Comment by aahlenst** [comment]
We have a working binary since 8u272, yay!

```
$ jdk8u272-b10-aarch32-20201026/bin/java -version
openjdk version "1.8.0_272"
OpenJDK Runtime Environment (build 1.8.0_272-b10)
OpenJDK Client VM (build 25.272-b10, mixed mode)
```

**Comment by justinyunke** [comment]
**What is the most efficient way to get this into the Raspberry Pi OS buster package repo** to replace the currently-supported "stable 8u212-b01-1+rpi1?

If it's a matter of contacting the Raspberry Pi OS maintainers, I'll put in the effort if someone can give me a push.  Here are the current results for "openjdk-8":

openjdk-8-dbg/stable 8u212-b01-1+rpi1 armhf
  Java runtime based on OpenJDK (debugging symbols)

openjdk-8-demo/stable 8u212-b01-1+rpi1 armhf
  Java runtime based on OpenJDK (demos and examples)

openjdk-8-doc/stable 8u212-b01-1+rpi1 all
  OpenJDK Development Kit (JDK) documentation

openjdk-8-jdk/stable 8u212-b01-1+rpi1 armhf
  OpenJDK Development Kit (JDK)

openjdk-8-jdk-headless/stable 8u212-b01-1+rpi1 armhf
  OpenJDK Development Kit (JDK) (headless)

openjdk-8-jre/stable 8u212-b01-1+rpi1 armhf
  OpenJDK Java runtime, using Hotspot JIT

openjdk-8-jre-headless/stable 8u212-b01-1+rpi1 armhf
  OpenJDK Java runtime, using Hotspot JIT (headless)

openjdk-8-jre-zero/stable 8u212-b01-1+rpi1 armhf
  Alternative JVM for OpenJDK, using Zero/Shark

openjdk-8-source/stable 8u212-b01-1+rpi1 all
  OpenJDK Development Kit (JDK) source files

**Comment by sxa** [comment]
Let me see what I can do - it probably is worth persuing this now that we are fully operational with a JIT ... Didn't make much sense previously.

**Comment by aahlenst** [comment]
Our Debian repos work great on Raspbian. What's the problem apart from AdoptOpenJDK not being part of the official package feeds? And that's unlikely to change because Linux distributions usually do  ot accept binary packages.

**Comment by justinyunke** [comment]
Tried following the instructions on the AdoptOpenJDK page (https://adoptopenjdk.net/installation.html) to add the repo and got "Error: could not find a distribution template for Raspbian/buster".  For the benefit of those that stumble upon this post, can you provide steps on how to add the Debian repo?  I believe I tried this a while back and assumed it didn't work for Raspberry Pi OS (nee Raspbian) so I gave up.

**Comment by sxa** [comment]
If all else fails, add this line to /etc/apt/sources.list, the `apt-get update` and you should be good to go I thnk:
```
deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb buster main
```

**Comment by aahlenst** [comment]
I've prepared a PR to improve the instructions for all the Debian and Ubuntu flavours: https://github.com/AdoptOpenJDK/openjdk-website/pull/842
