### ISSUE TITLE
Windows sign_build jobs failing

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#1538]
Windows builds are failing at the sign_build step with the following:
```
Scheduling project: build-scripts » release » sign_build
Starting building: build-scripts » release » sign_build #7405
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
Execution error: null
[Pipeline] End of Pipeline
Finished: FAILURE
```
e.g see https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/478/console

I don't have the authority to see the sign_build job output to analyse the problem further.

**Comment by sxa555** [comment]
I've rebooted the machine - there was a built zip file that had a lock on it and couldn't be removed, preventing workspace cleanup.
