### ISSUE TITLE
windows x64 and linux x64 openJ9 builds are missing from the nightly build download page

### ISSUE THREAD

**Issue by cathyzhyi** [AdoptOpenJDK/openjdk-build#1544]
there is macOS, linux ppc, linux s390 but no linux x64. https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9
**API Issues:** https://github.com/AdoptOpenJDK/openjdk-api
**Website Issues:** https://github.com/AdoptOpenJDK/openjdk-website

**Comment by avermeer** [comment]
Hello,

Windows x64 is also missing, can it be added?

Kind regards,
Alexandre

**Comment by karianna** [comment]
Last Linux x64 was on the 3rd of Feb.  Windows x64 was 31st of Jan

**Comment by karianna** [comment]
The builds are not in GitHub either post those dates, so it's pointing to a build issue.

**Comment by karianna** [comment]
I can see that the builds are nominally successful though - https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/472/consoleFull as an example from yesterday.

**Comment by karianna** [comment]
the release tool has failed several times due to known out of disk issues on master, but I wonder if some sort of semi-permanent bug has been introduced with all of those failures.

**Comment by karianna** [comment]
OK, I'm guessing there's a naming regex bug that's not being caught in sbin/Release.sh.  The documentation in the file refers to API v2 as well, so maybe there's a  realign to v3 that needs to happen.  Over to @gdams and @johnoliver

**Comment by lumpfish** [comment]
May be related to https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/117 ?

**Comment by avermeer** [comment]
Still no new AdoptOpenJDK OpenJ9 nightly build available since 7th of Feb, what's happening?

**Comment by sxa555** [comment]
@avermeer Apologies from the project for the delay in this. Until we get a response from the two people assigned to this, you can obtain the nightlies directly from our github repository at https://github.com/AdoptOpenJDK/openjdk11-binaries/releases - the API appears not to be picking them all up properly from there at present for some reason

**Comment by pshipton** [comment]
Apparently it's fixed now? The latest nightly are available from https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9

**Comment by avermeer** [comment]
yes, outstanding, i'll check this ASAP !
