### ISSUE TITLE
11.0.6-hotspot fails with EXCEPTION_ILLEGAL_INSTRUCTION in Win2008R2 in HyperV

### ISSUE THREAD

**Issue by ceisserer** [AdoptOpenJDK/openjdk-build#1546]
**Platform:**
Windows-2008R2 in HyperV Environment
Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz

**Architecture:**
amd64

The current hotspot-based builds of AdoptOpenJDK (64-bit) don't work at all on Windows-2008R2 in a virtualized environment using HyperV. They immediatly abort with EXCEPTION_ILLEGAL_INSTRUCTION, even when only executing "java -version":
[hs_err_pid19752.log](https://github.com/AdoptOpenJDK/openjdk-build/files/4204407/hs_err_pid19752.log)

Please not 2008R2 on HyperV has AVX/AVX2 and a few now-common-instructions disabled (coreinfo output of guest OS attached), maybe the build doesn't cope with this well.
[coreinfo.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/4204408/coreinfo.txt)

 The OpenJ9 builds work as exected.

**Comment by jerboaa** [comment]
This looks like it's https://bugs.openjdk.java.net/browse/JDK-8238246

**Comment by ceisserer** [comment]
indeed it does, thank you for the pointer.

**Comment by jerboaa** [comment]
Feel free to try EA builds of this week when they become available:
https://adoptopenjdk.net/upstream.html?variant=openjdk11&ga=ea
