### ISSUE TITLE
Adopt Nightly Build+platform and tests+platform pipelines scheduling for optimum executor

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1549]
**Vision:** How best optimize to run these pipelines when build and test machines are free, which makes a more efficient way to run these build pipelines. So if we can be more specific to the timeline we run the nightly builds.

**Action:**  We all need to agree to the right solution on this as a community.

**Findings from my Investigation:** 
Each Pipeline is scheduled on a daily bases,
The configuration for each pipeline is set to @daily. As per the flag,

-  OpenJDK 11 pipeline scheduled for everyday at Europ time 20:06 pm and expect to finish the next day early morning at 4.09 am, which is as per UK time 19:06 pm-3.09am GMT.

- OpenJDk8 pipelines are scheduled morning 5:26 am- next day 9:11am. which means 8 runs after 9 hours difference to openJDk 11.

However, the issue arises when these build does not start or finish at the scheduled time.

AdoptOpenJDK have build Pipelines calendar which is very handy to see the scheduled jobs,
https://ci.adoptopenjdk.net/view/Build%20and%20Test%20Pipeline%20Calendar/#date=2020-01-30|view=week-view
How we might be able to fix this?

Jenkins has predefined aliases to schedule build:
@hourly, @daily, @weekly, @monthly, @midnight
@hourly --> Build every hour at the beginning of the hour --> 0 * * * *
@daily, @midnight --> Build every day at midnight --> 0 0 * * *
@weekly --> Build every week at midnight on Sunday morning --> 0 0 * * 0
@monthly --> Build every month at midnight of the first day of the month --> 0 0 1 * *

Jenkins used a cron expression, and the different fields are:
MINUTES Minutes in one hour (0-59)
HOURS Hours in one day (0-23)
DAYMONTH Day in a month (1-31)
MONTH Month in a year (1-12)
DAYWEEK Day of the week (0-7) where 0 and 7 are Sunday
Example
If you want to schedule your build every 5 minutes, this will do the job : */5 * * * *
If you want to schedule your build every day at 8h00, this will do the job : 0 8 * * *

To allow periodically scheduled tasks to produce even load on the system, the symbol H (for “hash”) should be used wherever possible.
For example, using 0 0 * * * for a dozen daily jobs will cause a large spike at midnight. In contrast, using H H * * * would still execute each job once a day, but not all at the same time, better using limited resources.

**The solution** might be to change the configuration https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/build_base_file.groovy

H(0-30) 23 * * * - OpenJDK11 (Average takes full run 8 hrs 3 min)
That means by approximately by 8am UK time It should complete.

H(0-30) 3 * * * - OpenJDK8 (Average takes full run 6 hrs 39 min)
That means by approximately 9am UK time It should complete.

H(0-30) 20 * * * - OpenJDK14 (Average takes full run  2 hr 37 min)
That means by approximately 23pm UK time It should complete.

H(0-30) 17 * * * - OpenJDK15 (Average takes full run 1 hr 30 min)
That means by approximately 7pm UK time It should complete.

I understand we need a great discussion in this and see what best we can fix with.

**Comment by karianna** [comment]
@sxa555 - Can this be closed now given the PR?

**Comment by sxa555** [comment]
JDK11 ran tonight at the original time, therefore we should leave this open until verified

**Comment by sxa555** [comment]
I think they're running an hour later than the times specified above, but that should be ok, so I'll close this issue

**Comment by archanaNogriya** [comment]
Thanks @sxa555  and everyone.
