### ISSUE TITLE
Improve Capacity usage on AIX boxes

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1559]
Ref https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1151

We resolved this resource limit problem by reducing the amount of RAM which the builds script uses for it's calculation. This isn't ideal, and I suspect a preferable solution would be to make use of the `NUM_JOBS` variable to cap the number of things that can be run in parallel, as this can be controlled more effectively on a per-machine basis using the `NUM_PROCESSORS` variable we have on most of the machines in jenkins (Although at the moment I'm not sure if this is used by the build processes other than for [arm32](https://github.com/AdoptOpenJDK/openjdk-build/blob/333235e6f4e2f24c6706567446b7e23e9b91061f/configureBuild.sh#L249))

**Comment by aixtools** [comment]
Commenting - because it is still open (here). Maybe it just needs closing. However, now that the ramdisk is not supposed to be used - the 16G that was used for the RAM disk is available for other work - maybe allowing more memory again.

**Comment by karianna** [comment]
Yeah can close this and open a new one if required.
