### ISSUE TITLE
JDK 11 glibc minimal version requirements

### ISSUE THREAD

**Issue by zuismanm** [AdoptOpenJDK/openjdk-build#1561]
Hi.
At wicki of open JDK 11 I have found only requirement for minimal OS version (for example RH 7.4 s390). 
As much as I understands - in general those are versions of build machines of AdoptOpenJDK  project. But I do not see in any place list of packages, on which JDK depends, and their versions. For exaple - for sure glibc runtime have to be installed. But what is minimal version? It depends on - which glibc-dev package version is installed on build machine.
Is this information available anywhere?
It would be helpfull (IMHO) to put somewhere in wiki full list of development packages (with their versions) installed on build machines

**Comment by karianna** [comment]
See https://adoptopenjdk.net/supported_platforms.html
