### ISSUE TITLE
Enable Support for OpenJDK9 in API and Website

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#157]
I believe that all of the work has been for this? Assigning to @Joe-Brady / @EnriqueL8 to confirm

**Comment by EnriqueL8** [comment]
Yeah , just need to add a new variant to the `config.json`

**Comment by gdams** [comment]
looks like a comment here about updating some lines https://github.com/AdoptOpenJDK/openjdk-website/blob/d20637f3737b63b4ece060ef7c371b9d0b034880/src/js/nightly.js#L40-L43

**Comment by EnriqueL8** [comment]
Yes , I have seen that we have to change the name of the current repo `openjdk-nightly` to `openjdk8-nightly` and create a `openjdk9-nightly` repo.

**Comment by gdams** [comment]
we now have a nightly release in https://github.com/AdoptOpenJDK/openjdk9-nightly/. Can we ensure that the website/API are showing this

**Comment by gdams** [comment]
API and Website have both now been updated
