### ISSUE TITLE
Nightly builds jdk8u-2020-12-30-13-36 named incorrectly

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#1578]
**Platform:**
All
**Architecture:**
All

Presumably these binaries were named and tagged incorrectly (https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u-2020-12-30-13-36).

The text associated with the release says "adoptopenjdk-github-bot released this on Dec 30, 2019" (not 2020).

**Comment by sxa555** [comment]
It's this: https://github.com/AdoptOpenJDK/openjdk-build/pull/1459
I thought I'd manually deleted the affected nightlies but apparently not - I'll go on a clear-up ...

**Comment by sxa555** [comment]
Have cleared that one - @lumpfish did you say you'd seen any others? Not too easy to find them

**Comment by lumpfish** [comment]
There are some suspect entries in this view: https://github.com/AdoptOpenJDK/openjdk11-binaries/tags

**Comment by sxa555** [comment]
Done - hadn't considered tags :-)
