### ISSUE TITLE
build scripts "leaking" files in /tmp (public_key.gpg)

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1580]
These are being left around on build machines which prevents other users from running build jobs on the machine as it can't write to that file. We should either ensure they are removed immediately afterwards, or give it a unique name for each run.

Seen while validating the RISC-V builds as part of #1576 as we were validating the work as a different user ID on the build machines

**Comment by Willsparker** [comment]
Could an alternative of this be that we store this within the workspace?
