### ISSUE TITLE
Latest Hotspot builds determing wrong jdk build tag

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1584]
**Platform:** All

**Architecture:** All

Hotspot builds at the moment are determing the “wrong” tag for the jdk level the code is actually at jdk-11.0.7+5, but the build logic thinks it is jdk-11.0.7+2 ….
The issue I think is caused by the combination of the branch history and tagging and I think the fact the build machines do a shallow clone… The logic to find latest tag using rev-list --topo-order is unfortunately not always reliable because it does a left branch search, this is why for OpenJ9 we ended up changing the logic to do a chronological tag sort by name

**Comment by andrew-m-leonard** [comment]
The logic can also only reliably be done on a full clone, so you can work out which tags are on which branches...

**Comment by sxa555** [comment]
Not sure if @andrew-m-leonard or anyone else did anything specifically to address this but the builds now appear to be coming out with the correct level, therefore closing - if there is still work to do feel free to reopen
