### ISSUE TITLE
https://github.com/AdoptOpenJDK/openjdk-jdk14 JDK14 mirror out of date

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1585]
Is looks as though the https://github.com/AdoptOpenJDK/openjdk-jdk14
JDK14 mirror is only at build level jdk-14+34, whereas OpenJDK is at jdk-14+36...

**Comment by sxa555** [comment]
Looks like https://github.com/AdoptOpenJDK/openjdk-build/pull/1483 was merged but nothing put in place to run it :'(

**Comment by karianna** [comment]
Jenkins job now setup https://ci.adoptopenjdk.net/job/git-hg/job/jdk14-repo-sync/
