### ISSUE TITLE
New enable-dtrace options causes AIX builds to fail

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1586]
Ref: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/508/console
```
checking for dtrace tool... not found, cannot build dtrace
checking sys/sdt.h usability... no
checking sys/sdt.h presence... configure: error: Cannot enable dtrace with missing dependencies. See above. 
no
checking for sys/sdt.h... no
checking if dtrace should be built... no, missing dependencies
configure exiting with result code 1
[Pipeline] }
```
Apparently the new version of the option (required by JDK15) is not the same as the old `auto` option so https://github.com/AdoptOpenJDK/openjdk-build/pull/1563 has likely been the cause of this. We should switch to enabling this in the `platform-specific-configuration` scripts instead of globally in `build.sh`

**Comment by karianna** [comment]
@M-Davies - Is this something to add to your PR here?
