### ISSUE TITLE
Builds should archive debugimage archives

### ISSUE THREAD

**Issue by keithc-ca** [AdoptOpenJDK/openjdk-build#1596]
OpenJ9 builds also produce `build/.../images/debug-image` containing debug information relating to native code. That folder contains platform-specific (`.debuginfo`, `.pdb`, `.dSYM` or `.diz`) files in locations that relate to the corresponding executable or shared library in a jdk.

Copying the `debug-image` folder over top of the jdk makes symbols available to greatly ease the task of debugging an issue with native code.

Archives of this information are already made available in nightly and pull-request builds at ci.eclipse.org/openj9 (e.g. [1]); it would be helpful to make them available via adoptopenjdk.net as well.

[1] https://ci.eclipse.org/openj9/view/Build_Nightly/job/Build_JDK11_x86-64_linux_Nightly/lastSuccessfulBuild/

**Comment by pshipton** [comment]
JDK8 should also be configured with the `--disable-zip-debug-info` option so the debug image contains .debuginfo and .pdb files instead of .diz files which the user (developer) would have to unzip before they can be used with a debugger.
https://github.com/eclipse/openj9/pull/8808/

**Comment by pshipton** [comment]
FYI https://github.com/eclipse/openj9/issues/8874. The OpenJ9 project is going to include the debug-image into the testimage archive, to reduce the number of different files that need to be specified and expanded when running the tests. We are looking at modifying the test scripting to recognize the presence of the debug-image and copy/move the files to the correct place in the JVM build so they are used if a crash occurs when running the tests.
https://github.com/AdoptOpenJDK/openjdk-tests/blob/6d4670a158607cb0e0fd30e76b5c6a0f03a7a74d/get.sh#L273

**Comment by pshipton** [comment]
@keithc-ca what would it take to have a Hotspot build create a debug-image as well?

**Comment by keithc-ca** [comment]
> @keithc-ca what would it take to have a Hotspot build create a debug-image as well?

I expect the additions for OpenJ9 would also work for hotspot. We introduced a new main target ([1]) which invokes a new makefile ([2]). The changes are similar, but not identical, in other versions.

[1] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/custom/Main.gmk#L72-L75
[2] https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/closed/DebugImage.gmk

**Comment by sxa555** [comment]
@johnoliver Can you take a look at this please - the OpenJ9 team want it available for the April release

**Comment by karianna** [comment]
@keithc-ca - is https://github.com/AdoptOpenJDK/openjdk-build/pull/1597 the PR that resolves this (in part?)

**Comment by keithc-ca** [comment]
> @keithc-ca - is #1597 the PR that resolves this (in part?)

Yes, that's the expectation.

**Comment by sxa555** [comment]
@karianna We'll also need API/website updates to fulfil the other parts of this

**Comment by pshipton** [comment]
I'm not sure why #1597 closed this. I think there are still parts remaining as Stuart mentioned in the previous comment.

**Comment by karianna** [comment]
Linked PRs auto close issues.  The API and website issues should be added to their respective repos and the top priority project added to them.

**Comment by pshipton** [comment]
I can't add the top priority project, but I've created
https://github.com/AdoptOpenJDK/openjdk-api/issues/195
https://github.com/AdoptOpenJDK/openjdk-website/issues/696
