### ISSUE TITLE
strip-debug & only-keep-debug not found on aarch64

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1607]
**Platform:**
linux

**Architecture:**
aarch_64 & aarch_64_xl

Ref https://github.com/AdoptOpenJDK/openjdk-tests/issues/1680
Commands `only-keep-debug` and `strip-debug` are not found when building jdk11/j9/aarch64

```
gmake[7]: only-keep-debug: Command not found
../omrmakefiles/rules.mk:293: recipe for target '../../libomrsig.so' failed
gmake[7]: [../../libomrsig.so] Error 127 (ignored)
strip-debug ../../libomrsig.so
gmake[7]: strip-debug: Command not found
../omrmakefiles/rules.mk:293: recipe for target '../../libomrsig.so' failed
gmake[7]: [../../libomrsig.so] Error 127 (ignored)
add-gnu-debuglink=../../libomrsig.so.dbg ../../libomrsig.so
/bin/sh: add-gnu-debuglink=../../libomrsig.so.dbg: No such file or directory
gmake[7]: [../../libomrsig.so] Error 127 (ignored)
../omrmakefiles/rules.mk:293: recipe for target '../../libomrsig.so' failed
```

**Comment by keithc-ca** [comment]
This should be addressed by https://github.com/eclipse/openj9/pull/8813 and, for the 0.20.0 release by https://github.com/eclipse/openj9/pull/8851.

**Comment by sxa555** [comment]
I'm not seeing a jdk14/j9/aarch64 bulid job at adoptopenjdk - where was that from?

**Comment by M-Davies** [comment]
Ah my apologies. That was supposed to be JDK11 😅

**Comment by sxa555** [comment]
Builds 237 and later seem ok so i'm going to close this
