### ISSUE TITLE
Symantec Download Insights blocks/quarantine adoptOpenJDK binary on Windows platform

### ISSUE THREAD

**Issue by mbvreddy** [AdoptOpenJDK/openjdk-build#161]
Executables and libraries of JDK binary generated on Windows platform are not signed. Due to this, Symantec Download Insights (part of Symantec EndPoint) quarantine the executables and libraries whose default action is to delete the file.

Steps to recreate
1. Ensure that Symantec EndPoint Manager is installed on Windows machine
2. Download adoptOpenJDK binary for Windows
3. Extract the archive.
4. Boom! too many number of Symantec windows appear.

Workaround:
Default level of sensitivity of Download Insight is '5'. Change it to '1'.

Solution I would think is to sign the JDK executable and libraries. This require us to procure a certificate.

**Comment by gdams** [comment]
@mbvreddy great timing here! I have just ordered a code signing certificate for windows which I aim to receive tomorrow and setup our installers. The next step will be actually signing the JDK executable's and libraries but I want to see what our installers built in code signing function can do as it may be able to handle this for me :)

**Comment by mbvreddy** [comment]
List of files Symantec quarantined is attached 

[Quarantined Files.xlsx](https://github.com/AdoptOpenJDK/openjdk-build/files/1277370/Quarantined.Files.xlsx)
