### ISSUE TITLE
Update RELEASING.md with details of build script updates

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#1613]
The openj9 jdk14 release file names were incorrect because changes needed to be made to various build scripts to change the download file name prefix from OpenJDK14 to OpenJDK14U.

This requirement is not mentioned in the RELEASING.md file.

The document should include details of which build scripts to be changed for the release engineer to either implement or check.

**Comment by sxa555** [comment]
I would suggest this issue is covered under the same general topic of #1581

**Comment by M-Davies** [comment]
A few PR's have gone in recently to make updating the scripts easier for those releasing
- https://github.com/AdoptOpenJDK/openjdk-build/pull/1822 removes the reliance on having to update hardcoded java head values
- https://github.com/AdoptOpenJDK/openjdk-build/pull/1872 which has renamed the config files to whatever the current version string (u or not) is. This does not solve how to know if the version is in an update repo however (how do we know when it gets moved @karianna ?). Also see https://github.com/AdoptOpenJDK/openjdk-build/pull/1919 which allows the pr_tester to detect whether the java version is in an update repo or not.

@lumpfish Could you take a look at the current [release document](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md) and let me know if there's anything in it at the moment that's confusing?

**Comment by karianna** [comment]
> * #1872 which has renamed the config files to whatever the current version string (u or not) is. This does not solve how to know if the version is in an updated repo however which is an open issue #1654 (how do we know when it gets moved @karianna ?).

You have to be monitoring the OpenJDK mailing lists basically for when they make the announcement to shift.

**Comment by sxa** [comment]
> You have to be monitoring the OpenJDK mailing lists basically for when they make the announcement to shift.

Sounds like we should put in a link to the mailing list then

**Comment by karianna** [comment]
jdk-dev and jdk-updates-dev and jdk8u-dev are the three to watch

**Comment by lumpfish** [comment]
I see the latest releasing document https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md now has this sentence, which I think relates to what had not been done giving rise to the file naming problem described in this issue.

"At some point the JDK N version will get to be maintained in an update repository. At that point a switch-over of job names from jdkXX to jdkXXu has to happen."

I don't think this adequately describes what needs to be done when that switch (from jdknn to jdknnu) occurs yet:
- How to we decide 'this is the time to make the switch' (what needs to be monitored)?
- Are there prereq changes before the pipelines can be changed (e.g. the repository mirroring scripts / jobs)?
- Where are the places jdknn must be changed to jdknnu?

When we first discovered this issue, the question was raised while the problem was being investigated why we ever added the 'U' suffix to the file names, and there was a general feeling that we shouldn't bother.  Was that ever resolved?

**Comment by M-Davies** [comment]
Pretty sure I can answer the last two bullet points. I've yet to understand `How to we decide 'this is the time to make the switch'` however. When do we make the decision to do so @karianna ?

**Comment by lumpfish** [comment]
Regarding "when to make the switch" - I think that for the most recent release it was done between the openj9 release builds being created and the hotspot builds being created (and that what what gave rise to the issues we saw later).  Of course the jdknnu repository must exist before the switch can be made, but if we can assume that this is done before the initial release, then the answer may simply be "before we start building the first release".

**Comment by karianna** [comment]
> Pretty sure I can answer the last two bullet points. I've yet to understand `How to we decide 'this is the time to make the switch'` however. When & How do we make the decision to do so @karianna ?

Basically when the `jdk<version>u` repo gets created - this will all happen at Skara going forward now so it should be easier.  The next one of these will be jdk15u (date TBD)

**Comment by lumpfish** [comment]
So this gets us back to the original issue.  If we create a release before the switch to jdknnu has been made then the build files do not contain the 'U' suffix, which seems to be what users are currently expecting.  So the choices would appear to be:
1. Do not release until the switch to jdknnu has been made
2. Drop the 'U' suffix from the build file names (which would affect users initially, but I think would mean that the release could be created before the switch is made).
The openj9 jdk is not built from the same git hg clone as the hotspot jdk, so is only affected by this as a 'side effect' of the settings (jdknn vs jdknnu) in the pipelines.
