### ISSUE TITLE
Configure OpenJ9 plinux builds for jdk8 jdk11 with --enable-jitserver

### ISSUE THREAD

**Issue by mpirvu** [AdoptOpenJDK/openjdk-build#1614]
Please configure OpenJ9 plinux builds for jdk8 and jdk11 with --enable-jitserver
This includes both the head stream and the April (OpenJ9 0.20.0) release.

eclipse/openj9#8426

**Comment by mpirvu** [comment]
Note: to avoid issues related to protobuf library installation it's better to wait until PR https://github.com/eclipse/openj9/pull/8832 is delivered (which should happen soon)

**Comment by sxa555** [comment]
@mpirvu What issues do you think might occur if that PR is not merged?

**Comment by sxa555** [comment]
@adam-thorpe Can you take this one (or at least prep the PR)

**Comment by mpirvu** [comment]
> What issues do you think might occur if that PR is not merged?

In the past we had issues related to the protobuf library, either because it was not installed (new machine) or because it was installed on top of an older version (the older version needs to be unistalled first)

**Comment by adam-thorpe** [comment]
@mpirvu https://github.com/eclipse/openj9/pull/8832 is merged, are we okay to go ahead with https://github.com/AdoptOpenJDK/openjdk-build/pull/1619 ?

**Comment by mpirvu** [comment]
@adam-thorpe  Nightly builds have removed protobufs so #1619 can proceed.
Im in the process of doing the same for openj9 0.20 release. The PR is here https://github.com/eclipse/openj9/pull/8940 and is waiting for some omr prerequisite

**Comment by mpirvu** [comment]
@adam-thorpe PR eclipse/openj9#8940 has been merged so we could start building with --enable-jitserver on plinux for 0.20.0 release branch as well. Thank you

**Comment by sxa555** [comment]
@mpirvu The adopt scripts don't distinguish between branches so any changes for a JDK major release will take effect across branches
