### ISSUE TITLE
AdoptOpenJDK v14 – for *32-Bit* Windows

### ISSUE THREAD

**Issue by lordmulder** [AdoptOpenJDK/openjdk-build#1616]
Hello,

can we please have 32-Bit (x86) builds of AdoptOpenJDK v14?

(we still need it, because some customers may still use a 32-Bit version of Windows)

_Azul has it, by the way:_
https://www.azul.com/downloads/zulu-community/?version=java-14&os=windows&architecture=x86-32-bit&package=jdk

Thank you and best regards
MuldeR

**Comment by sxa555** [comment]
We've added support for it (and 32-bit Linux/ARM) https://github.com/AdoptOpenJDK/openjdk-build/pull/1612 but have not yet done a release based on it

**Comment by lordmulder** [comment]
What about 32-Bit Windows? Can we expect 32-Bit builds of OpenJDK v14 for Windows?

Thank you and best regards
MuldeR

**Comment by lordmulder** [comment]
> What about 32-Bit Windows? Can we expect 32-Bit builds of OpenJDK v14 for Windows?

Sorry, I think I misread your answer. So, support for 32-Bit Windows has already been added.

**Comment by sxa555** [comment]
Correct :-)
@gdams and @karianna are looking at getting it out - I'd expect we can get it out in the next day or so unless any further complications arise.

**Comment by karianna** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk14-pipeline/72/
