### ISSUE TITLE
MacOS Nortarization fails due to JDK8

### ISSUE THREAD

**Issue by NishikaDeSilva** [AdoptOpenJDK/openjdk-build#1621]
Hi, 

We are building MacOS installers for our products which contains JDK 8 distribution inside. Notarisation the installer fails due to this JDK. I tried to manually sign it but it was no use.

1. Is there a JDK build which supports macOS notarisation and hardened runtime ?
2. If not, how can I sign this JDK so that notarising the installer won't fail ?

**Comment by aahlenst** [comment]
All information is in https://github.com/AdoptOpenJDK/openjdk-build/issues/1130, specifically in https://github.com/AdoptOpenJDK/openjdk-build/issues/1130#issuecomment-601271189 for JDK 8. [14+36](https://adoptopenjdk.net/releases.html?variant=openjdk14&jvmVariant=hotspot) is notarized. Nightly builds of 11 are, too.
