### ISSUE TITLE
Nightly builds do not have the correct download links

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#1635]
e.g. aarch64 openj9 build on https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9 seems to be serving up the `debugimage` build, not the JDK

**Comment by sxa555** [comment]
EDIT: Just occurred to me - "jdk" is no longer first alphabetically - are we just serving up the first matching binary for the platform in each release?

**Comment by karianna** [comment]
Was an API issue, now resolved.
