### ISSUE TITLE
Publish an early access driver for OpenJ9 AArch64 in the 11.0.7 (April) release

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#1643]
OpenJ9 is adding a new platform, AArch64 in the April 11.0.7 release. This platform has some outstanding issues to be resolved to address functional problems and performance, but we'd like to include it as part of the release tagged as an early access (ea) driver, like 11.0.7-ea+10.

**Comment by sxa555** [comment]
Three options:
1. Release it as the same time but as a separate release named with a .ea suffix
2. Build it as a normal nightly build but call it an "early access" in the same way we do with milestone builds where it it just written up and linked to as such (wouldn't be part of the release) - we could even have a page similar to the upstream RedHat ones that link to "current pre-release builds"
3. Modify the website (and API) to have pages that link to beta/pre-release builds in addition to nightly and "full GA" ones

**Comment by DanHeidinga** [comment]
We had discussed how to make it clear that the platform was an early access platform.  We're planning to modify the filename to include "ea" and to have the `java -version` output indicate it's an early access platform.

**Comment by karianna** [comment]
> Three options:
> 
> 1. Release it as the same time but as a separate release named with a .ea suffix
> 2. Build it as a normal nightly build but call it an "early access" in the same way we do with milestone builds where it it just written up and linked to as such (wouldn't be part of the release) - we could even have a page similar to the upstream RedHat ones that link to "current pre-release builds"
> 3. Modify the website (and API) to have pages that link to beta/pre-release builds in addition to nightly and "full GA" ones

I _think_ with 1. we can execute this as a pipeline with it as the only job and use the override configuration parameters to push out the 'correct' thing in terms of the filename.

**Comment by sxa555** [comment]
Correct @karianna - if the AdoptOpenJDK project is happy with that as a solution, then that is what I expected we would do (along with setting whatever parameters are needed to get the `java -version` output set as per Dan's comment above

**Comment by DanHeidinga** [comment]
Quoting an internal slack discussion - adding `ea` to the version output should be doable by configuring with `--with-version-pre=ea --without-version-opt`.

/cc @andrew-m-leonard @lumpfish

**Comment by lumpfish** [comment]
I've run a private build with the ```--with-version-pre=ea --without-version-opt```
options. This is the java -version output.
```
openjdk version "11.0.7-ea" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7-ea+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0-m2, JRE 11 Linux amd64-64-Bit Compressed References 20200402_557 (JIT enabled, AOT enabled)
OpenJ9   - c93e4dabc
OMR      - 1b6abd044
JCL      - 644e9abfc0 based on jdk-11.0.7+9)
```
Regarding the release name, these would appear to be the obvious choices:
1. jdk-11.0.7-ea+9_openj9-0.20.0
2. jdk-11.0.7+9_openj9-0.20.0-ea

**Comment by karianna** [comment]
@johnoliver - Can you comment on the API factor.

**Comment by johnoliver** [comment]
adding a pre/optional argument isnt an issue, the api will show that in the version, we do already use the term ea for nightly builds so may be confusing. In terms of how it will effect the api, if nothing is changed it will look like any other ea/nightly release just with a different version string, assuming that the release it is in is marked as a pre-release.You could filter out things with that optional tag in the UI, we could exclude them entirely from the api and you download them manually  from github

**Comment by lumpfish** [comment]
The intention is that the build would be a release, not pre-release (see the Description).

What would be changed (for the aarch64 platform only) would be the release tag as the build appears in https://github.com/AdoptOpenJDK/openjdk11-binaries/releases, so it would be jdk-11.0.7+9_openj9-0.20.0 for all platforms except aarch64 and something else (e.g. jdk-11.0.7-ea+9_openj9-0.20.0 or jdk-11.0.7+9_openj9-0.20.0-ea) for aarch64.

My question is, if the release were tagged jdk-11.0.7-ea+9_openj9-0.20.0 or jdk-11.0.7+9_openj9-0.20.0-ea and the latest (for instance) jdk11 release was requested via the API, would those builds be returned for that platform?

It looks like the build file names also include the tag (with certain special characters replaced) - e.g. https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B9_openj9-0.20.0-m2/OpenJDK11U-debugimage_aarch64_linux_openj9_11.0.7_9_openj9-0.20.0-m2.tar.gz

**Comment by johnoliver** [comment]
If they are included in a "release" that is marked as a release (i.e not pre-release), then yes it would be returned in "ga" queries, if the release is a pre-release then it will be returned in "ea" queries.

**Comment by lumpfish** [comment]
Following a web meeting, the following was decided:
1. The AArch64 build would be built with the options
```
--with-version-pre=ea --without-version-opt
```
which will result in java -version output similar to
```
openjdk version "11.0.7-ea" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7-ea+9)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.20.0-m2, JRE 11 Linux amd64-64-Bit Compressed References 20200402_557 (JIT enabled, AOT enabled)
OpenJ9   - c93e4dabc
OMR      - 1b6abd044
JCL      - 644e9abfc0 based on jdk-11.0.7+9)
```
2. The metadata associated with the build already extracts the build version string from line two of the output - i.e. "11.0.7-ea+9".
3. The build for AArch64 will be added to the git binaries repository under the regular release tag - i.e. jdk-11.0.7+9_openj9-0.20.0 along with all the other paltforms
4. The AdoptOpenJDK website will be amended to recognise the "-ea" in the openjdk_version metadata string and place a visual flag against the build to alert the user to its "ea" status.

**Comment by gdams** [comment]
website PR https://github.com/AdoptOpenJDK/openjdk-website/pull/700

**Comment by gdams** [comment]
> The build for AArch64 will be added to the git binaries repository under the regular release tag - i.e. jdk-11.0.7+9_openj9-0.20.0 along with all the other platforms

@lumpfish I'm pretty sure this will only work if it's released under a different release tag containing `-ea` we'll have to check on the day when the binaries get submitted to see what the API returns us

**Comment by lumpfish** [comment]
I understood from @johnoliver 's comments above that it will all work as envisaged as AArch64 is built separately (with the different config options) but with the same release tag.
The metadata
```
{
   "adopt_build_number" : null,
   "build" : 9,
   "major" : 11,
   "minor" : 0,
   "openjdk_version" : "11.0.7-ea+9",
   "optional" : null,
   "pre" : "ea",
   "security" : 7,
   "semver" : "11.0.7-ea+9"
}
```
is associated with each individual build (i.e. platform) rather than the release - is that correct?  If so then the only difference between the AArch64 release and the other platforms will be
```
   "openjdk_version" : "11.0.7-ea+9",
``` 
So if a user requested 'latest' via the API that's what they'd get (without necessarily knowing it had 'ea' status), but if the downloaded the build from the website they would see the new marker.

@gdmas - what is it about the API which concerns you?

**Comment by gdams** [comment]
okay let's see how it works, I might be wrong. We could try and produce an EA for the previous release tag as a test?

**Comment by lumpfish** [comment]
I don't think an AArch64 build for the previous release would be viable as a release (even 'ea').

**Comment by lumpfish** [comment]
Regarding the "pre" tag, it is created when the "-ea" string is found in the java -version output, so a GA build will not carry the tag at all.  So checking for pre=ea is all that is necessary in the web pages for tagging the builds (openjdk_version need not be checked).

**Comment by gdams** [comment]
complete
