### ISSUE TITLE
Define and document transition of jdkNN to jdkNNu 

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#1654]
Prior to creating hotspot jdk14 GA builds, the switch was made from pulling the openjdk code from the jdk14 repository to the jdk14u repository,

The way the Jenkins jobs work this change also changed the way the binary output files were named - from OpenJDK14.xxxxx to OpenJDK14U.xxxxx.

openj9 is built from their 'extensions' repository (which takes the GA code from the jdk14 repository and switches to the jdk14u repository after the GA builds are released).

The openj9 builds were created before the Jenkins scripts were changed to get the (hotspot build) code from the jdk14u repository - hence those build files were already name OpenJDK14.xxxxx when that changed was made.

The end result was that the hotspot and openj9 build files for the GA had different build prefixes.

The discrepancy had to be resolved by rebuilding the openj9 release.

This issue is to:
1. Ensure that the policy and timing of switching between the jdkNN and jdkNNu repository is understood and added to the steps in RELEASING.md
2. Propose the removal of the link between the openjdk repository from which the code is being taken (jdkNN / jdkNNu) and the resulting build files names - i.e. name the build files OpenJDKnn.xxxxx throughout the entire life cycle of the release.

**Comment by sxa555** [comment]
Related: #1581

**Comment by M-Davies** [comment]
> Ensure that the policy and timing of switching between the jdkNN and jdkNNu repository is understood and added to the steps in RELEASING.md

Fixed by #1965 

> Propose the removal of the link between the openjdk repository from which the code is being taken (jdkNN / jdkNNu) and the resulting build files names - i.e. name the build files OpenJDKnn.xxxxx throughout the entire life cycle of the release.

That query is probably best for the general discussion on the refactoring of folder names. I'll copypasta that over quote to https://github.com/AdoptOpenJDK/openjdk-build/issues/1016 and close this as a dup of #1613 and #1016 respectively
