### ISSUE TITLE
OpenJ9 configure arguments broken on JDK14

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1656]
**Platform/Architecture**
windows_x64 OpenJ9 builds

- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-windows-x64-openj9/
- Failing since 03/04/2020
```
Running custom generated-configure.sh
configure: error: unrecognized options: --with-version-opt, --without-version-pre, --with-version-build, --with-vendor-version-string, --disable-warnings-as-errors
```

**Comment by M-Davies** [comment]
Tested all potential options on local instance and all exist so likely a machine issue. 

For the record, the configure options are not being recognised on `build-softlayer-win2012r2-x64-1`

**Comment by andrew-m-leonard** [comment]
note that's a jdk14u build however console log thinks it is building jdk8u, hence why options not valid...
```
OpenJDK repo tag is jdk8u252-b08
Version: 252 
Should have the source, I'm at /tmp/openjdk-build/workspace/build/src
OpenJDK repo tag is jdk8u252-b08
```

**Comment by sxa555** [comment]
@gdams could this be a result of the different way we now use a shortened workspace path name?

**Comment by andrew-m-leonard** [comment]
This line does not check source out for JDK14:
https://github.com/AdoptOpenJDK/openjdk-build/blob/820ec4633433c821ba7634c93a3b7d50ec38b3bd/sbin/prepareWorkspace.sh#L50

**Comment by andrew-m-leonard** [comment]
Not sure why that line checks the version... why not do it for all..?

**Comment by sxa555** [comment]
@johnoliver ?

**Comment by johnoliver** [comment]
I agree I am not sure why we need to check the version there, so I would remove that version check

**Comment by karianna** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/1657

**Comment by karianna** [comment]
@M-Davies Can you try a new run and see what happens please?

**Comment by sxa555** [comment]
@M-Davies @lumpfish I've kicked off a 14 pipeline without publish or tests so we we can see how it goes https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk14-pipeline/105/

**Comment by M-Davies** [comment]
Looks like https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-windows-x64-openj9/32/consoleFull is running fine. Its passed the configure stage and is building. Thanks for this :-)
