### ISSUE TITLE
Stackoverflow error running gradle during builds on build-azure-win2012r2-x64-1

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1659]
Some reference links: [JDK11/js#508](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/508/console) | [JDK11/J9XL#276](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9-windowsXL/276/consoleFull) | [JDK11/hs#510](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/510/console) | [JDK14/J9#36](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-windows-x64-openj9/36/console) - all failing on [build-azure-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/build-azure-win2012r2-x64-1/) which is a new machine added as part of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1239

```
Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip
...................................................................................

Welcome to Gradle 5.2.1!

Here are the highlights of this release:
 - Define sets of dependencies that work together with Java Platform plugin
 - New C++ plugins with dependency management built-in
 - New C++ project types for gradle init
 - Service injection into plugins and project extensions

For more details see https://docs.gradle.org/5.2.1/release-notes.html

To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.2.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Task :clean UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :compileGroovy
> Task :compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> java.lang.StackOverflowError (no error message)
```

**Comment by gdams** [comment]
rebooted the machine and it seems happier now. closing
