### ISSUE TITLE
Wrong link "Build Farm Definition"

### ISSUE THREAD

**Issue by asbachb** [AdoptOpenJDK/openjdk-build#1663]
https://github.com/AdoptOpenJDK/openjdk-build#build-farm link `Build Farm Definition` resolves to 404.

**Comment by sxa** [comment]
Looks like it was removed under https://github.com/AdoptOpenJDK/openjdk-build/pull/1084 - should possibly point to the top level [readme](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/README.md), or [my FAQ](https://github.com/AdoptOpenJDK/openjdk-build/pull/1457) once I get it finalised (hopefully soon - it's near the top of my list again to complete it)

Which raises an obvious question for @asbachb - was there some particular piece of information you were looking for? Always useful to know what people might want in an FAQ :-)

**Comment by asbachb** [comment]
Basically I was looking if there's a possibilty to enable fastdebug builds in the Jenkins jobs.

**Comment by sxa** [comment]
A great question! Check out https://github.com/AdoptOpenJDK/openjdk-build/issues/146 where it has been discussed previously (and there's a link at the bottom of that to how to build one yourself) although that is an ideal FAQ candidate - thanks!

**Comment by asbachb** [comment]
Yeah that issue or to be more precise that comment (https://github.com/AdoptOpenJDK/openjdk-build/issues/146#issuecomment-440826007) was the reason I looked around ;)

**Comment by M-Davies** [comment]
Can this be closed? It looks like `build-farm` doesn't exist in the README anymore
