### ISSUE TITLE
Newest Java Versions fail to load 3rd party dylib

### ISSUE THREAD

**Issue by MoxxiManagarm** [AdoptOpenJDK/openjdk-build#1671]
**Platform:**
verified on MacOs 10.13, 10.14 and 10.15

**Architecture:**
64bit

In production we currently use 11.0.4_11, everything is working fine. Due to notarization issues we try to upgrade the version to the latest 11.0.7_10, I reported this issue previously within the common notarization issue thread when we tried with nightly builds. But I am not sure, if it is related to notarization, hence I now created ths separated issue.

I can confirm with 11.0.7_10 notarization passes and the application comes up successfully. All hardened runtime entitlements were added. However, we have small part of application, which tries to access a 3rd party dylib, which is installed on the location `/usr/local/lib` (which is a standard location according to [UsingDynamicLibraries](https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html)). We have no influence on that point, it is a driver of an USB device. With 11.0.4_11 this library can be loaded successfully. With our notarized application based on 11.0.7_10 loading the dylib fails, stating the following

```
Error loading native library
java.lang.UnsatisfiedLinkError: Unable to load library 'ctapi':
dlopen(libctapi.dylib, 9): image not found
dlopen(libctapi.dylib, 9): image not found
Native library (darwin/libctapi.dylib) not found in resource path (./Resources/Java/<jarname>.jar)
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:397)
        at com.sun.jna.Function.getFunction(Function.java:102)
```

All application code stayed unchanged for this, only the java version was changed along with the codesigning for notarization.

**Comment by gdams** [comment]
@MoxxiManagarm can you provide me with some steps to recreate this issue locally?

At a guess, I am wondering whether you need to add an entitlement that allows java to use dynamic libs but it's hard to tell.

**Comment by MoxxiManagarm** [comment]
@gdams Unfortunately I have no mac station for myself currently. Just let me mention, that all hardened runtime entitlements are already included in our application. As application code it should be enough to add JNA dependency (`'net.java.dev.jna', name: 'jna' & 'jna-platform', version: '5.4.0'`) and call `Function.getFunction("ctapi", "CT_init");`

The desired lib is a insurance cardreader driver, which you can install (https://www.germantelematics.de/wp-content/uploads/2014/12/gt_ctapi_osx_maverick.zip)

After installation libctapi.dylib can be found within the `/usr/local/lib` path.

**Comment by MoxxiManagarm** [comment]
We bundle java and start our application with its bundled version. I also tried to start our application with a locally installed 11.0.7_10. The behavior is the same.

**Comment by MoxxiManagarm** [comment]
I am closing the issue. We found a solution in the easily overlooked statement from the dlopen man page.
> Note: If the main executable is a set[ug]id binary **or codesigned with entitlements**, then all environment variables are ignored, and only a full path can beused.

This means not the version was the causing issue, but the hardened runtime, which came along with it. However, as a fix we explicetely set the required path `/usr/local/lib`  into the jna property `jna.library.path`.

**Comment by tmair-red** [comment]
@davinchia The reason for it is the following.
JNI uses the `dlopen` system call to load the library. When an application is _codesigned with entitlements_ then the `dlopen` system call will ignore all environment variables. That means that also the default library locations will not be tried. Therefore the only solution is to specify the absolute path for the 3rd party library.

**Comment by davinchia** [comment]
@tmair-red Thanks for the explanation.

I usually operate higher-up the Java stack and this is my first time diving into the Java's low-level bits so please excuse my ignorance. 

Two clarifications to help me connect the dots if you don't mind: 
1) What application are you referring to when you say `an application is codesigned with entitlements`? Is it the JVM executing  the JNI code? i.e. my local Java 11 JVM is codesigned with entitlements while my local Java 8 JVM is not, thus Java 11 requires the full path while Java 8 does not.
2) I understand codesigned with entitlement is a Mac requirement, does this mean this should only affect Java 11 on the Mac?

**Comment by tmair-red** [comment]
> * What application are you referring to when you say `an application is codesigned with entitlements`? Is it the JVM executing  the JNI code? i.e. my local Java 11 JVM is codesigned with entitlements while my local Java 8 JVM is not, thus Java 11 requires the full path while Java 8 does not.

Yes exactly. The java 11 Binary is cdesigned with entitlement. This is a requirement Apple introduced in Februrary. All binaries that went through the Apple siginign process before that are still running fine (therefore the Java 8 JVM is still running fine) but all applications signed after February need to turn on codesigning with entitlements.

> * I understand codesigned with entitlement is a Mac requirement, does this mean this should only affect Java 11 on the Mac?

Yes, this specific issue only occurs on MacOS.

**Comment by davinchia** [comment]
@tmair-red thanks for the explanation!

**Comment by MoxxiManagarm** [comment]
> @MoxxiManagarm I recently ran into the same `image not found` error while trying to upgrade from Jave 8 (OpenJDK 1.8.0.211) to 11 (OpenJDK 11.0.8) on Catalina. In my case it was a JNI call from an application we wrote to a shared `dylib` located in `/usr/local/lib`. Surprisingly, providing the fullpath `/usr/local/lib/lib.dylib`, instead of just the leaf name `lib.dylib` fixed this.

I am glad to see this issue helped others along the way :-)
