### ISSUE TITLE
Triage corretto jdk8u/jdk11u xlinux sanity.openjdk test failures

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#1674]
Corretto has its own test pipelines now, see the top-level targets that are launched at the end of these build pipelines:

------

jdk11u:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-corretto/27/console

sanity.system : passes
extended.system : passes
sanity.perf (running as functional tests) : passes
sanity.openjdk : [10 test cases](https://ci.adoptopenjdk.net/job/Test_openjdk11_corretto_sanity.openjdk_x86-64_linux/2/testReport/) failing 

------

jdk8u:
sanity.system : passes
extended.system : passes
special.functional : passes
sanity.openjdk : [7 test cases](https://ci.adoptopenjdk.net/job/Test_openjdk8_corretto_sanity.openjdk_x86-64_linux/1/testReport/) failing 

Need to triage the test failures, identify which are already reported and report any new ones to the correct repo for fixing.

**Comment by smlambert** [comment]
If the build pipelines are pulling jdk source from https://github.com/corretto/corretto-11 (which looks like may be the case if look at the console output of a build run and not a jdk11u mirror as the adopt builds use), test pipelines should be pulling test material from the same repo (with matching tag/SHA as is used by the build, https://github.com/corretto/corretto-11/tree/develop/src/test).  

This issue is a request to pass enough info to test pipelines so they know where to pull test material from.

**Comment by sophia-guo** [comment]
Looks like openjdk-build uses BUILD_CONFIGURATION [    "VARIANT" ] = 
 "corretto", to choose correto repo, similar to openj9 extension repo.:

```
  # Location of Extensions for OpenJ9 project
  if [[ "${BUILD_CONFIG[BUILD_VARIANT]}" == "${BUILD_VARIANT_OPENJ9}" ]]; then
    suffix="ibmruntimes/openj9-openjdk-${BUILD_CONFIG[OPENJDK_CORE_VERSION]}"
  elif [[ "${BUILD_CONFIG[BUILD_VARIANT]}" == "${BUILD_VARIANT_SAP}" ]]; then
    # TODO need to map versions to SAP branches going forwards
    # sapmachine10 is the current branch for OpenJDK10 mainline
    # (equivalent to jdk/jdk10 on hotspot)
    suffix="SAP/SapMachine"
  elif [[ "${BUILD_CONFIG[BUILD_VARIANT]}" == "${BUILD_VARIANT_CORRETTO}" ]]; then
    suffix="corretto/corretto-${BUILD_CONFIG[OPENJDK_CORE_VERSION]:3}"
  else
    suffix="adoptopenjdk/openjdk-${BUILD_CONFIG[OPENJDK_FOREST_NAME]}"
  fi
```

https://github.com/AdoptOpenJDK/openjdk-build/blob/master/configureBuild.sh#L150
And corretto's default branch is `develop`. If tests for hotspot also work for corretto simply passing that build information to test pipeline should be good (Though may need extra parameter for test pipeline).

**Comment by smlambert** [comment]
related to https://github.com/AdoptOpenJDK/openjdk-build/issues/1674#issuecomment-655724014, https://github.com/AdoptOpenJDK/openjdk-tests/issues/1872

**Comment by sophia-guo** [comment]
The information is set by shell script setRepository() set Branch(). That is  dynamically generated and consumed by build jdk process. Jenkins pipeline has no idea about those generated information. In this way developers can also build jdk natively on the local system (no jenkins needed). 

I think there are a few solutions, all of them have cons and pros.

1. Duplicate this logic in jenkins pipeline so build and downstream builds can also consume it. ( For now it seems only test builds need it. If it is the case the logic can be limited to runTests()). 

- cons: redundant
 
2. Store the generated `OPENJDK BUILD CONFIGURATION` as Properties Files so downstream builds can consume those information.

```
19:39:29  # ============================
19:39:29  # OPENJDK BUILD CONFIGURATION:
19:39:29  # ============================
19:39:29  BUILD_CONFIG[ADOPT_PATCHES]="true"
19:39:29  BUILD_CONFIG[BRANCH]="develop"
19:39:29  BUILD_CONFIG[BUILD_FULL_NAME]="linux-x86_64--server-release"
19:39:29  BUILD_CONFIG[BUILD_VARIANT]="corretto"
19:39:29  BUILD_CONFIG[CLEAN_DOCKER_BUILD]="false"
```

- cons: may need to update script, which is unnecessary for local run.

3. Add some default variable yaml file to set those information

- cons: redundant?

4. Passing build args to test builds and test build need to generate those information using a similar logic.

- cons: anything update, both openjdk build project and openjdk-tests project need to be updated.

**Comment by sophia-guo** [comment]
I will just choose option1 as this change will limit to runtest pipeline code, which won't affect other pipeline or underline base script.
