### ISSUE TITLE
There is no OpenJ9 debug image for MacOS jdk8

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#1677]
**Platform:**
MacOS jdk8

There is no debug image for MacOS jdk8, either in the nightly builds or the OpenJ9 0.20.0 release.

**Comment by pshipton** [comment]
@keithc-ca

**Comment by andrew-m-leonard** [comment]
I suspect maybe related to the issue raised about jdk11 JRE size ...?

**Comment by sxa** [comment]
The issue which Andrew is referring to is [this one](https://github.com/AdoptOpenJDK/openjdk-build/pull/1161) and was mitigated by [this PR](https://github.com/AdoptOpenJDK/openjdk-build/pull/1672) - FYI @gdams

**Comment by sxa** [comment]
This seems macos specific so it's unlikely that the above change was related to it (Not impossible though...)

**Comment by keithc-ca** [comment]
I think I've identified the problem. [This filter](https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/closed/DebugImage.gmk#L62) doesn't match any files and so no debug-image folder is created. I should have a fix shortly.
