### ISSUE TITLE
Do we have an OpenJdk installer available for z/OS ?

### ISSUE THREAD

**Issue by kolmisra** [AdoptOpenJDK/openjdk-build#1679]
I do not see any installer for z/OS in https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9.
To run java Application in z/OS i need a JDK for z/OS .
Please help me where can I find one?

**Comment by sxa** [comment]
OpenJDK does not support z/OS, and AdoptOpenJDK does not provide them. Sorry. You will have to contact IBM who is the only vendor of a JDK for z/OS
