### ISSUE TITLE
Installer build break

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1683]
Installer jobs are causing the nightly builds to fail. I don't have the perms to see or diagnose the problems. 
```
Execution error: script returned exit code 1
```

May also be due to a network glitch that has also killed some of the testing jobs https://github.com/AdoptOpenJDK/openjdk-build/issues/1683#issuecomment-617063871

**Comment by M-Davies** [comment]
Seems to be across all platforms and JDK versions, including next

**Comment by sxa** [comment]
It looks like you are talking about jobs such as https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-hotspot/486/console
The linked installer job is https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_linux/9597/ which appears to have completed successfully

**Comment by sxa** [comment]
It looks like the associated test jobs, such as https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_ppc64le_linux/202/console failed though

```

01:49:48  getJtreg:
01:49:48      [mkdir] Created dir: /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_ppc64le_linux/jvmtest/openjdk
01:49:48       [echo] Getting Jtreg from https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz
01:54:59       [exec] curl: (28) Operation timed out after 300967 milliseconds with 0 out of 0 bytes received
01:54:59  
01:54:59  BUILD FAILED
01:54:59  /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_ppc64le_linux/openjdk-tests/TKG/scripts/build_test.xml:58: The following error occurred while executing this line:
01:54:59  /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_ppc64le_linux/openjdk-tests/openjdk/build.xml:196: The following error occurred while executing this line:
01:54:59  /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_ppc64le_linux/openjdk-tests/openjdk/build.xml:42: exec returned: 28
01:54:59  
01:54:59  Total time: 5 minutes 1 second
01:54:59  1
01:54:59  compile.mk:42: recipe for target 'compile' failed
01:54:59  make[1]: *** [compile] Error 1
01:54:59  make[1]: Leaving directory '/home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_ppc64le_linux/openjdk-tests/TKG'
01:54:59  makefile:60: recipe for target 'compile' failed
01:54:59  make: *** [compile] Error 2
[Pipeline] }
```

**Comment by M-Davies** [comment]
Correct. My assumption is that it's the installer as the build itself completed successfully. 

Looking at some of the test failures, it looks like there might have been a network glitch last night on the jtreg side so it could be that the job died halfway through due to the internet dropping out https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_linux/206/console

**Comment by M-Davies** [comment]
Ah. Just seen you commented the exact same thing 😄

**Comment by M-Davies** [comment]
@sxa Could we kick off a new respin of nightlies to verify it was just a glitch?

**Comment by sxa** [comment]
JDK11 pipeline is still running at the moment, so I was going to kick off 8 but they haven't failed in the same way ... The tests appear to have been ok on there

**Comment by gdams** [comment]
it's not the installer jobs. this was broken by https://github.com/AdoptOpenJDK/openjdk-build/pull/1668

**Comment by sxa** [comment]
The above revert does not appear to have fully resolved this as https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-hotspot/517/consoleFull still shows the failure despite the above revert going in

**Comment by M-Davies** [comment]
Regarding this issue, the builds look a lot happier this morning. Thanks for the help on this

**Comment by sxa** [comment]
For reference, the revert of https://github.com/AdoptOpenJDK/openjdk-build/pull/1687 resolved this
