### ISSUE TITLE
OpenJ9 jdk8u252-b09_openj9-0.20.0 Installers are not Notarized

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1684]
**Platform:** MacOS Catalina

An update is required to jdk8u252-b08_openj9-0.20.0 to enable MacOS Notarization

**Comment by andrew-m-leonard** [comment]
The OpenJ9 extensions repository only takes contributions merged direct from OpenJDK, or by IBM. So as such Adopt won't be able to produce an OpenJ9 jdk8 Notarized binary until we have the notarization patches, published to the OpenJDK jdkupdates-dev maillist under an Oracle Contribution agreement. It should be sufficient to get as far as posting the patch "diff" to the maillist, to then allow the OpenJ9 extensions repository to pull in that patch from OpenJDK.

@gdams @karianna Do we have a expected timeline for "publishing" the patch to OpenJDK maillist?

**Comment by karianna** [comment]
@andrew-m-leonard - we're a little gated on Apple's private review of the patch. It'll still be a week or so before it even lands in jdk8u-dev.

**Comment by gdams** [comment]
@karianna Simon Tooke updated the mailing list:

http://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-February/011283.html
http://cr.openjdk.java.net/~stooke/webrevs/jdk-8226288-jdk8u/01/

@andrew-m-leonard and myself are working on getting the builds running

**Comment by karianna** [comment]
Looks like Simon's patch stalled at the end of Feb though.  So we'll need to nudge him again to push it through (or ask if we can do so on his behalf)

**Comment by andrew-m-leonard** [comment]
@karianna given we do have all the "patches" published to the maillist, it does mean they are published under OCA, which means we can take those changesets and apply to openj9 extensions, so we're good for doing this .1 release for openj9. However, as you say, we need them contributing upstream for next quarterly...

**Comment by andrew-m-leonard** [comment]
jdk8 openj9 extensions branch openj9-0.20.0 has been updated with the MacOS Notarization fixes from the following openjdk changesets:
Porting of following openjdk jdk8u changes:

Main jdk8 Notarization changes:
-  http://cr.openjdk.java.net/~stooke/webrevs/jdk-8226288-jdk8u/01/01/
-  http://cr.openjdk.java.net/~stooke/webrevs/jdk-8226288-jdk8u/01/jdk.01/
Eclipse IDE Symlink notarization fixes:
-  http://cr.openjdk.java.net/~dcherepanov/openjdk8u/8235687/webrev.v0/
-  http://cr.openjdk.java.net/~dcherepanov/openjdk8u/8238225/webrev.v0/

**Comment by andrew-m-leonard** [comment]
@smlambert Test build & Tests passes all test suites:
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/jdk8u-mac-x64-openj9-notarized/20/

**Comment by gdams** [comment]
@andrew-m-leonard can this be closed now?

**Comment by andrew-m-leonard** [comment]
released
