### ISSUE TITLE
Two README inaccuracies

### ISSUE THREAD

**Issue by mstoodle** [AdoptOpenJDK/openjdk-build#169]
1. The first thing the README lists as present in this repo is the `ansible` directory. But there isn't such a directory...
2. Lower down, "Building in your local environment" mentions a script that doesn't appear to exist anymore `makejdk-local-env.sh` .

**Comment by smlambert** [comment]
A while ago, the openjdk-infrastructure repo was created and all the ansible scripts were moved there, so this README doc needs updating to reflect that move.

**Comment by gdams** [comment]
ansible got migrated to https://github.com/AdoptOpenJDK/openjdk-infrastructure/tree/master/ansible

**Comment by amczarny** [comment]
I would suggest to close the issue as the README has been already updated e.g. https://github.com/AdoptOpenJDK/openjdk-build/pull/261
