### ISSUE TITLE
Request to rebuild OpenJ9 Windows/Mac with openssl 1.1.1g

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#1693]
Although OpenJ9 does not appear to be affected by the security vulnerability fixed in openssl 1.1.g, @DanHeidinga pointed out that users may scan the Adopt build and find an openssl version that contains a known security vulnerability. They may be restricted from using the binary due to their company policies. To avoid this, Windows and Mac (Java 8, 11, 14) should be rebuilt to include openssl 1.1.1g.

**Comment by sxa** [comment]
This is in progress thanks to @Willsparker (Installed 1.1.1g on the Windows build machines) and @lumpfish at the following links (build script adjustments in https://github.com/AdoptOpenJDK/openjdk-build/pull/1697)
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/1003/
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/877/
- https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk14-pipeline/129/
