### ISSUE TITLE
jdk-11.0.7+10.1 for Windows binary is not signed by digital certification.

### ISSUE THREAD

**Issue by viewhero** [AdoptOpenJDK/openjdk-build#1694]
**Platform:**
Windows 

**Architecture:**
x64 and x86

jdk-11.0.7+10.1 for Windows binary  is not signed by digital certification.
previous release(11.0.6) binaries were signed completely.

Please, check it.
Thank you.

**Comment by viewhero** [comment]
Check JDK and JRE zip version.
all of dll and exe weren't signed.

**Comment by gdams** [comment]
@viewhero thanks for the bug report, will investigate right away

**Comment by gdams** [comment]
We have made a fix to the build scripts and aim to re-build all windows releases from the last cycle. Thanks again for raising the issue. Will leave this open to track progress until we've published all versions

**Comment by gdams** [comment]
- jdk-11.0.7+10.2 - hotspot has been shipped

**Comment by gdams** [comment]
openj9 rebuilds on Windows and macOS are now available:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u252-b09.1_openj9-0.20.0
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.7+10.1_openj9-0.20.0
https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/tag/jdk-14.0.1+7.1_openj9-0.20.0
