### ISSUE TITLE
Clarify use of adoptBuildNumber on release pipelines

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1696]
There has been some confusion over the use of the `adoptBuildNumber` parameter on the release pipelines. Traditionall it has been left blank for the initial GA releases, and then populated for re-releases starting at `1` to match the `.1` suffix we used.

Discussions today have brought out that `1` is the default if the field is left blank, therefore re-releases that we have done with `1` will have the same metadata as the GA releases. The code that implements this default is at https://github.com/AdoptOpenJDK/openjdk-build/blob/8328ed927fbcb79537e96359d0e1d3994127e2ed/pipelines/library/src/common/VersionInfo.groovy#L13

We need to be clear on what we want to use this field for, what the numbers should be for GA and subsequent releases to ensure the most consistent possible naming scheme to avoid confusing customers, and get this information into the RELEASING.md document in this repository if it needs to change.

**Comment by lumpfish** [comment]
It looks like AdoptBuildNumber is not present on the hotspot GA's but is on the openj9 GAs.

Also the openjdk_version metadata is different between hotspot GA and openj9 or a hotspot rebuild.

This can be seen by examining the metadata returned by https://api.adoptopenjdk.net/v3/assets/feature_releases/8/ga

**Comment by gdams** [comment]
both GA and `.1` jdk8 build have a build number of 1 and contain `.1` in the server version.

@johnoliver can you make this an empty adoptBuildNumber default to null and then we only use it for `.1` `.2` releases etc

**Comment by johnoliver** [comment]
Yes we can do that fine

**Comment by gdams** [comment]
@sxa are you happy with that solution.

To be clear a GA release will look like this:

```json
"version_data": {
"adopt_build_number": null,
"build": 9,
"major": 8,
"minor": 0,
"openjdk_version": "1.8.0_252-b09",
"security": 252,
"semver": "8.0.252+9"
}
```

**Comment by sxa** [comment]
Yep that seems like the right solution to me and I havent' seen anyone even vageuly objecting so let's go for it

**Comment by sxa** [comment]
Thanks to @austin0 for reminding me to close this now that the PR has gone in :-)
