### ISSUE TITLE
JDK archives include unwanted debug files

### ISSUE THREAD

**Issue by keithc-ca** [AdoptOpenJDK/openjdk-build#1698]
breun commented on slack:

> I noticed the AdoptOpenJDK 14 OpenJ9 JDK archives went from ~200 MB to ~250 MB with 14 to 14.0.1. Is it known what causes this +25% jump in archive size?

and Peter Shipton clarified:

> From a quick look I think we're talking about MacOS, which now has a number of .dSYM files in the build that weren't there in the last release.

We want debug information to be available, but not included in the main JDK archives.

**Comment by sxa** [comment]
I'm going to close this one as dup of mine even though this was first, as I have a bit more info on the sizes in my other issue. Hope that's ok :-)
