### ISSUE TITLE
macos and AIX OpenJ9 April releases are larger than expected

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1699]
HotSpot does not suffer the same problem - here are the macos download sizes:

jdk8u252 - 140Mb (JDK) 74MB (JRE)
jdk8u242 - 114MB (JDK) 49MB (JRE)
jdk-11.0.7 - 248MB (JDK) 95MB (JRE)
jdk-11.0.6 - 196MB (JDK) 39MB (JRE)

Initial investigation by @pshipton suggests this is related to extra debug symbols being added and various fixes for it such as https://github.com/AdoptOpenJDK/openjdk-build/issues/1636

AIX builds also seems to have got a lot bigger too ... A quick look suggests that other platforms are ok.

**Comment by sxa** [comment]
I've closed the duplicate issue https://github.com/AdoptOpenJDK/openjdk-build/issues/1698#issue-604826573 as this one has a bit more information on the affected downloads and their sizes. the slack conversation referenced in the other issue was https://adoptopenjdk.slack.com/archives/CBBHBD8G2/p1587208287005600 and initiated by @breun

**Comment by keithc-ca** [comment]
AIX archives still contain `.debuginfo` files, but #1715 should fix that.
