### ISSUE TITLE
Create "Updating Concurrent Pipeline Scripts" Documentation

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1701]
Although we have concurrent pipelines enabled, there is currently no documentation in place to instruct people on how to update the pipelines when the JDK HEAD changes.

- Create a doc with the following specs 
  - [x] How the job regenerator works
  - [x] Updating the [config_regeneration](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/config_regeneration.groovy) file. I.e:
    - [folder_name](https://github.com/AdoptOpenJDK/openjdk-build/blob/2041d51db738b741f2a630bc803ca1f038ef62b2/pipelines/build/common/config_regeneration.groovy#L359) will need to be changed when HEAD updates. 
    - [freebsd](https://github.com/AdoptOpenJDK/openjdk-build/blob/2041d51db738b741f2a630bc803ca1f038ef62b2/pipelines/build/common/config_regeneration.groovy#L234). We currently exclude `freebsd` from regeneration since there is no config in the `pipeline_config` files (needs to be removed if we want to build `freebsd` again in the future).
  - [x] Creating/Updating the [pipeline_config files](https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines/jobs/configurations) for each pipeline.
  - [x] Creating/Updating the [regeneration_scripts](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/regeneration) for each JDK version
  - [x] Updating the JDK-HEAD version in the [pipeline](https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines/build) files
  - [x] Creating/Updating the names and configs of the `pipeline_jobs_generator_jdkxx` files in the [utils](https://ci.adoptopenjdk.net/job/build-scripts/job/utils/) folder in jenkins.

**Comment by M-Davies** [comment]
Ideally the place to put this would be the wiki or the [docs](https://github.com/AdoptOpenJDK/openjdk-build/tree/master/docs) folder although there doesn't seem to be any docs in there. 

@karianna could I get editing access to the wiki please?

**Comment by sxa** [comment]
Part of this should be a minimal set of instructions to add to RELEASING.MD to tell people creating new releases what needs to be updated for new releases I.e. which new jobs to add. There's another issue specifically for updating that but it would be good to have it in there even if the full details you are describing in the checklist above go elsewhere.

**Comment by M-Davies** [comment]
Good point. At least these 
```
 - Updating the config_regeneration file. 
 - Creating/Updating the pipeline_config files for each pipeline.
 - Creating/Updating the regeneration_scripts for each JDK version
 - Updating the JDK-HEAD version in the pipeline files
 - Creating/Updating the names and configs of the pipeline_jobs_generator_jdkxx files in the utils folder in jenkins.
```
could be added to [RELEASING.md#steps-for-every-version](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md#steps-for-every-version) as they're all released related stuff. `How the job regenerator works` would be better suited somewhere else I imagine.

**Comment by M-Davies** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/1702 Addresses all the criteria save `How the job regenerator works`

**Comment by M-Davies** [comment]
Have now added a readme to [regeneration](https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines/build/regeneration) detailing `How the job regenerator works`

The PR is ready for review

**Comment by karianna** [comment]
@M-Davies - I think we can close this now
