### ISSUE TITLE
Set up dockerfiles to run jdk/jdk

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1706]
The issue of not being able to build "bleeding edge" jdk/jdk with docker came up in the OpenJ9 slack instance recently. We should look at adding suitable Dockerfiles to do this into the [DockerFileCheck](https://ci.adoptopenjdk.net/job/DockerFileCheck/) job.

**Comment by sxa** [comment]
> Would this not be better suited in `openjdk-build` as that's where the Dockerfiles are? :-)

Done

**Comment by Willsparker** [comment]
As of #1705 , this should be fixed :-)
They were already there, just under the name `jdk15`, so I've just gone through and renamed it, and once `jdk15` is released, we can make another set of Dockerfiles (and remove JDK14 from the `DockerfileCheck` job)
