### ISSUE TITLE
`Makejdk-any-platform.sh --docker` runs configure on host, before making container

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-build#1707]
When running `makejdk-any-platform.sh --docker`, the build scripts will run configure and attempt to set `JDK_BOOT_DIR` on the host machine before building the docker containers. This can lead to situations like this:
 https://ci.adoptopenjdk.net/job/DockerfileCheck/112/label=docker-aws-ubuntu1604-x64-1,variant=j9,version=jdk/console
where the machine doesn't have `javac` in the path, and https://github.com/AdoptOpenJDK/openjdk-build/blob/f9671c487711ab0ec8e8a8ce220572e30abb8d63/sbin/common/common.sh#L141 will fail.

**Comment by karianna** [comment]
@Willsparker - I think this might be a case where we we need to force the docker builds to set the boot-jdk parameter.  I noticed building today that my jdk8u docker build picked up jdk14 as the boot jdk because that's the Java it detected on my host.

Thoughts?

**Comment by Willsparker** [comment]
I agree - I would assume that configure build has to be run before the docker container is built to set some variables.
https://github.com/AdoptOpenJDK/openjdk-build/blob/c57ad18fb56e681892fbc662ee25aff117c0498b/makejdk-any-platform.sh#L53
From the looks, we could override the `JDK_BOOT_DIR` variable by adding it into the JDK specific Dockerfile configure script (i.e. https://github.com/AdoptOpenJDK/openjdk-build/blob/master/docker/jdk14/x86_64/ubuntu/dockerConfiguration.sh ) as the boot jdk will always be in a set place (i.e. `/usr/lib/jvm/jdkXX`).
However, that won't fix the issue I explained earlier, where a host machine may not have `java` or `javac` set- though that could probably be solved by adding an ` elif BUILD_CONFIG[docker] == "docker"` to https://github.com/AdoptOpenJDK/openjdk-build/blob/f9671c487711ab0ec8e8a8ce220572e30abb8d63/sbin/common/common.sh#L126
