### ISSUE TITLE
All build pipelines hung due to all pLinux slaves offline

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1710]
**Platform:**
pLinux

All weekend build pipelines hung due to pLinux slaves being offline:
build-osuosl-centos74-ppc64le-1
build-osuosl-centos74-ppc64le-2

**Comment by sxa** [comment]
There is some scheduled maintenance occurring on the hosting systems at OSUOSL that will take up to a couple more hours to complete. AIX machines at OSUOSL are offline too

**Comment by sxa** [comment]
Now all online again - there was some more maintenance last night
