### ISSUE TITLE
jpackage signing fails with Mac jdk-14.0.1+7

### ISSUE THREAD

**Issue by AdamCarroll** [AdoptOpenJDK/openjdk-build#1718]
**Platform:**

Mac OS Catalina v10.15.4

**Architecture:**

x86

**Description:**

This problem was seen using the `.tar.gz` version of AdoptOpenJDK 14.0.1+7, from [this download link](https://github.com/AdoptOpenJDK/openjdk14-binaries/releases/download/jdk-14.0.1%2B7/OpenJDK14U-jdk_x64_mac_hotspot_14.0.1_7.tar.gz).

Using the Mac signing option for `jpackage ... --mac-sign ...` I see the following error (extra path information removed):

````
/var/folders/rh/...../HelloFX.app: is already signed
````

However, if the `--mac-sign` option is removed, the build works without a problem.

**Reproducing the problem:**

I've created a [minimal, single-class JavaFX application](https://github.com/AdamCarroll/jdk14-jpackage-mac) along with the necessary scripts to reproduce the problem.

First clone the repo:
````
$ git clone git@github.com:AdamCarroll/jdk14-jpackage-mac.git
````

Checkout the tag:
````
$ git checkout 1.0.0
````

Run the build (very fast as there's only [one class](https://github.com/AdamCarroll/jdk14-jpackage-mac/blob/1.0.0/src/main/java/demo/HelloFX.java)):
````
$ ./gradlew clean build
````

Now run the `jpackage` command with the `--mac-sign` option as follows (this is included in the file [`bin/create-signed-dmg.sh`](https://github.com/AdamCarroll/jdk14-jpackage-mac/blob/1.0.0/bin/create-signed-dmg.sh)):
````
$ jpackage \
    --type dmg \
    --module-path 'build/modules' \
    --verbose \
    --add-modules javafx.controls \
    --input 'build/libraries' \
    --dest "build/bundle" \
    --name HelloFX \
    --main-jar 'jdk14-jpackage-mac.jar' \
    --main-class 'demo.HelloFX' \
    --mac-sign
````

You will now see a long error that includes the following:
````
/var/folders/rh/...jdk.incubator.jpackage..../HelloFX.app: is already signed
java.io.IOException: Command [codesign, -s, Developer ID Application: Your Name Here (XXXXXXXXXX), -vvvv, /var/folders/rh/...jdk.incubator.jpackage.../HelloFX.app] exited with 1 code
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Executor.executeExpectSuccess(Executor.java:73)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.IOUtils.exec(IOUtils.java:179)
	at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.IOUtils.exec(IOUtils.java:150)
	...
````

If you now run the same command but without the `--mac-sign` option (or alternatively use the script [`bin/create-unsigned-dmg.sh`](https://github.com/AdamCarroll/jdk14-jpackage-mac/blob/1.0.0/bin/create-unsigned-dmg.sh)), everything works without problems.

**Comment by karianna** [comment]
@gdams - I'm not sure this use case would work?

**Comment by gdams** [comment]
@AdamCarroll sounds like an issue with jpackage to me, They should provide an option to force sign and overwrite the existing codesign cert.

**Comment by karianna** [comment]
@AdamCarroll - you can report this at openjdk.java.net in the code-tools mailing list IIRC

**Comment by AdamCarroll** [comment]
The problem was forwarded by a list administrator to the Core Libs Dev list: https://mail.openjdk.java.net/pipermail/core-libs-dev/2020-May/066194.html
