### ISSUE TITLE
Hardened runtime issue, missing audio-input entitlement

### ISSUE THREAD

**Issue by adruiza** [AdoptOpenJDK/openjdk-build#1720]
**Platform:** macOS 10.15.4

**Architecture:** x86_64

Since upgrading to the hardened runtime version of the JDK, I can no longer access microphone input using the standard Java Sound API, only silence is captured when running my .jar file using the command line. While checking Console.app, I found that TCC is blocking microphone access in the background because of a missing entitlement:

> Prompting policy for hardened runtime; service: kTCCServiceMicrophone requires entitlement com.apple.security.device.audio-input but it is missing for ACC:{ID: net.java.openjdk.cmd, PID[2161], auid: 501, euid: 501, binary path: '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java'}, REQ:{ID: com.apple.tccd, PID[154], auid: 0, euid: 0, binary path: '/System/Library/PrivateFrameworks/TCC.framework/Versions/A/Resources/tccd'}

This causes microphone access to be blocked without any user action:

> Policy disallows prompt for ACC:{ID: net.java.openjdk.cmd, PID[2161], auid: 501, euid: 501, binary path: '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/java'}, REQ:{ID: com.apple.tccd, PID[154], auid: 0, euid: 0, binary path: '/System/Library/PrivateFrameworks/TCC.framework/Versions/A/Resources/tccd'}; access to kTCCServiceMicrophone denied

This does not happen with file access: a dialog to provide access to "Documents" and "Downloads" appears when trying to access a file there.

**Comment by gdams** [comment]
This will likely need to be raised upstream as the entitlements are defined there: https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/make/data/macosxsigning/entitlements.plist

It raises an interesting issue though, should a Java runtime come with all entitlements enabled by default?

**Comment by adruiza** [comment]
Yes, that will be an issue when sharing a JRE between applications (specially when it comes to running .jar files from the command line using a system-wide installation of the JRE). Accepting a request to access a resource for application A will inevitably mean that application B will have that permission too, as permissions are given to the whole "java" executable and not to application A or B.

I've seen this same issue while using Terminal.app. When running an executable like ffmpeg for recording microphone input, Terminal.app will ask for access to the microphone, and if you accept it, then every executable\* you run using Terminal.app will have access to the microphone. This is the same for file access, once you accept permission to access "Downloads" for Terminal.app, every executable that wants to write there and is ran using Terminal.app will have access without a prompt. So, at least for shared JRE installations, having all entitlements on will mean imitating this same behavior.

_\*Java doesn't apply here because it is not a "simple" executable like ffmpeg, but an individual app I guess? Or is it just because of the hardened runtime? No expert here._

**Comment by karianna** [comment]
@adruiza Can you raise this issue on the openjdk.java.net `build-dev` mailing list?

**Comment by adruiza** [comment]
@karianna I just sent an email with this issue, I'm not a member so a moderator has to review it first, meanwhile, if any other user is having this problem, I suggest reverting to jdk-11.0.6+10, as this version correctly shows the permission dialog.

**Comment by karianna** [comment]
> @karianna I just sent an email with this issue, I'm not a member so a moderator has to review it first, meanwhile, if any other user is having this problem, I suggest reverting to jdk-11.0.6+10, as this version correctly shows the permission dialog.

Ah yes, you have to sign up to the mailing list.  I'll keep an eye on it and see if it goes through.

**Comment by gdams** [comment]
okay so I spoke to some folks at Apple that suggested this:
```
If your app uses device cameras, include the NSCameraUsageDescription key in your app’s Info.plist file.

If your app uses device microphones, include the NSMicrophoneUsageDescription key in your app’s Info.plist file.
```

see https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos for more information.

**Comment by karianna** [comment]
> okay so I spoke to some folks at Apple that suggested this:
> 
> ```
> If your app uses device cameras, include the NSCameraUsageDescription key in your app’s Info.plist file.
> 
> If your app uses device microphones, include the NSMicrophoneUsageDescription key in your app’s Info.plist file.
> ```
> 
> see https://developer.apple.com/documentation/avfoundation/cameras_and_media_capture/requesting_authorization_for_media_capture_on_macos for more information.

Is that a change a user should make or something we should bake in?

**Comment by gdams** [comment]
it's possibly something that we should bake in (especially in our installers) but I want to confirm if that fixes things first

**Comment by adruiza** [comment]
This issue has now been resolved in OpenJDK, adding the links for further info on the exact changes:

https://bugs.openjdk.java.net/browse/JDK-8244951
https://hg.openjdk.java.net/jdk/jdk/rev/c86677114b24

**Comment by karianna** [comment]
Looks like it's been backported all the way through.
