### ISSUE TITLE
Inconsistent release filenames

### ISSUE THREAD

**Issue by kuhsaft** [AdoptOpenJDK/openjdk-build#173]
Packaged filenames do not match release name:

Release name `jdk-9+181`:
- binary name has a dot: `OpenJDK9_x64_Win_jdk-9.181.zip`
- checksum file has a dot: `OpenJDK9_x64_Win_jdk-9.181.sha256.txt`
- content of sha256 file has a plus: `68fa...d028 OpenJDK9_x64_Win_jdk-9+181.zip`

PS: The build bot re-released the same version/build# on GitHub. Is it supposed to do that?

**Comment by r15ch13** [comment]
Related to: https://github.com/AdoptOpenJDK/openjdk9-releases/issues/1

**Comment by gdams** [comment]
This looks like an issue with GitHub releases. I'll investigate

**Comment by karianna** [comment]
This is also really an API issue - we could provide the metadata via the API (source TBA) and greatly simplify the file names

**Comment by karianna** [comment]
Resolved with new build scripts

**Comment by Nklya** [comment]
Hello
@karianna if I understand correctly, all new builds now have the same naming scheme?

Because earlier it was not quite clear. For example jdk8u192-b12: `https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12/OpenJDK8U-jdk_x64_linux_openj9_8u192b12.tar.gz` and next release `https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u192-b12_openj9-0.11.0/OpenJDK8U-jdk_x64_linux_openj9_8u192b12_openj9-0.11.0.tar.gz`

**Comment by karianna** [comment]
I think it's consistent on semVer now.

**Comment by Nklya** [comment]
Thanks!

So there will be no more artifacts without semVer at the end of the filename, like `OpenJDK8U-jdk_x64_linux_openj9_8u192b12.tar.gz` ?

Also, I just noticed that there is a problem with naming for OpenJDK8 Linux x64 Large Heap builds.
All other builds use this template at the end`8u202b08_openj9-0.12.1.tar.gz`
But Large Heap builds have underscore after openj9. For example `8u202b08-openj9-0.12.1.tar.gz`

**Comment by Nklya** [comment]
Nice.
New builds have another naming template 🤦‍♂️ 😞 😭 😢 

* JDK8u202: `OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz`
* JDK8u212: `OpenJDK8U-jdk_x64_linux_openj9_jdk8u212-b03_openj9-0.14.0.tar.gz`

So there is a new **jdk** in the middle

**Comment by Nklya** [comment]
I had to add three regexps to Java cookbook to parse all combinations I found
https://github.com/sous-chefs/java/pull/540/files#diff-b4c010242f7f7f5c83ace89c9834a374R161

**Comment by gdams** [comment]
we are fixing this now. Hopefully, it should be back to normal by the end of the day. Thanks for noticing!

**Comment by Nklya** [comment]
Thank you @gdams !
