### ISSUE TITLE
Add Mac OS X 32bit x86 release

### ISSUE THREAD

**Issue by andreok** [AdoptOpenJDK/openjdk-build#1744]
I've noticed there is no Mac OS X 32bit x86 target from adoptopenjdk.
Do you have plans to add this?

**Comment by aahlenst** [comment]
[Apple removed 32 bit support throughout the system](https://support.apple.com/HT208436). Why should we do this and what for?

**Comment by karianna** [comment]
Unfortunately, we don't support OS's which are no longer supported.
