### ISSUE TITLE
Pass down Distribution to installers

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1751]
**Platform:**
All

**Architecture:**
All

As indicated by @aahlenst in https://github.com/AdoptOpenJDK/openjdk-build/issues/1712#issuecomment-630762333, we are not passing down the full spec of parameters to the openjdk-installer, resulting in a lot of errors from installer tarball parsing.

If we completed this list by passing down the full set of parameters to the installer jobs, it will result in a lot less backache later on for the installer guys. Installers are kicked off from https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L327

Missing parameters:
❌ Distribution type (JDK, JRE)
~❌ VM type (HotSpot, OpenJ9, OpenJ9 XL)~ See https://github.com/AdoptOpenJDK/openjdk-build/issues/1751#issuecomment-631331122

**Comment by douph1** [comment]
VM type is already passed to windows installer job as JVM parameter.
Still missing "Distribution type"
Currently Windows installer job don't know about "OpenJ9 XL" , there is only two VM type supported hotspot|openj9

**Comment by douph1** [comment]
and so we dont provide Windows msi openj9 xl installer ( I don't know if XL build is revelant for Windows and needed )

**Comment by aahlenst** [comment]
@douph1 According to our download page, we provide MSIs for OpenJ9 XL.

**Comment by M-Davies** [comment]
@douph1 I notice that we have a [variable for Distribution type in the installer](https://github.com/AdoptOpenJDK/openjdk-installer/blob/d8e0d038ca41d02de8dba008a9158150692706db/wix/Build.OpenJDK_generic.cmd#L10) but this doesn't appear in the [installer job configs](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/4110/parameters/)?

**Comment by douph1** [comment]
@M-Davies we always tries to build both "PRODUCT_CATEGORY" JRE/JDK : see https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/configure
and ignoring error on JRE with is less common now
>:BuildError
>@rem Looks like I didn't have a JRE.
>exit /b 0

This is far from perfect

**Comment by M-Davies** [comment]
Sorry @douph1 I'm still confused.

So we create two downstream jobs for the installer, one for JDK and one for JRE but we also sometimes ignore the JRE?

**Comment by douph1** [comment]
Actually there is only one downstream job which try both JDK and JRE.
I would like to split it into two downstream job as it seems that sometime there is no more JRE to build.

**Comment by M-Davies** [comment]
Ok so in that case, this should just be a matter of kicking off an installer for the JDK, check if the JRE exists and if it does, kick off an installer for the JRE. Would that be sufficient for this?
