### ISSUE TITLE
AIX 11.0.7+10 may not be able to load fontmanager library

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#1759]
**Platform:**
AIX
Most of the output shown below is from jdk-11.0.7+10.1_openj9-0.20.0 but the problem also occurs with the Hotspot build. There is a workaround, which is to `export LIBPATH=/opt/freeware/lib` before running Java.

**Architecture:**
PPC

The AIX jdk-11.0.7+10 builds may not be able to load the fontmanager (libfontmanager.so) library resulting in a Java UnsatisfiedLinkError, depending on machine configuration. The problem already seems resolved in 11.0.8 builds.

The simple Java testcase is as follows. When it doesn't work, an UnsatisfiedLinkError is printed, otherwise nothing is printed.
```
public class Test {
public static void main(String[] args) throws Throwable {
System.loadLibrary("awt");
System.loadLibrary("fontmanager");
}
}
```

The Hotspot output shows the problem that occurs on some machines.
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /home/jenkins/peter/jdk-11.0.7+10/lib/libfontmanager.so: /home/jenkins/peter/jdk-11.0.7+10/lib/libfontmanager.so, LIBPATH=/home/jenkins/peter/jdk-11.0.7+10/lib/server:/home/jenkins/peter/jdk-11.0.7+10/lib:/home/jenkins/peter/jdk-11.0.7+10/lib/jli:/home/jenkins/peter/jdk-11.0.7+10/../lib, LD_LIBRARY_PATH= :  0509-022 Cannot load module /opt/freeware/lib/libbz2.a(libbz2.so.1).
        0509-150   Dependent module libgcc_s.a(shr.o) could not be loaded.
        0509-022 Cannot load module libgcc_s.a(shr.o).
        0509-026 System error: A file or directory in the path name does not exist.
        0509-022 Cannot load module /home/jenkins/peter/jdk-11.0.7+10/lib/libfontmanager.so.
        0509-150   Dependent module /opt/freeware/lib/libbz2.a(libbz2.so.1) could not be loaded.
```

The fontmanager library contains the following LIBPATH, however this library has a dependency on libgcc_s.a, which is found in /opt/freeware/lib and /opt/freeware/lib64, neither of which are on the built in LIBPATH (output from `dump -X any -H libfontmanager.so`).
```
0      /opt/IBM/xlc/13.1.3/../../../../usr/lpp/xlC/lib:/opt/IBM/xlC/13.1.3/lib/aix61:/opt/IBM/xlC/13.1.3/lib:/opt/IBM/xlc/13.1.3/lib/aix61:/opt/IBM/xlc/13.1.3/lib:/usr/vac/lib/aix53:/usr/lib:/lib                                         
```

I've found that another prereq library of fontmanager, libbz2.a, may or may not fix the issue. On one machine I found the following prereqs for libbz2.a, which doesn't work. It's referring to the powerpc-ibm-aix6.1.0.0 folder which doesn't exist, so libgcc_s.a is not found.
```
0      /opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/ppc64:/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0:/opt/freeware/lib/gcc/powerpc-ibm-aix6.1.0.0/6.3.0/../../..:/usr/lib:/lib                                         
1                                    libgcc_s.a          shr.o               
2                                    libc.a              shr_64.o            
```

On another machine I found the following for libbz2.a. Since this refers to /opt/freeware/lib64,  libgcc_s.a is found and libbz2.a and libfontmanager.so are loaded.
```
0      /opt/freeware/lib64:/opt/freeware/lib:/usr/lib:/lib                                         
1                                    libgcc_s.a          shr.o               
2                                    libc.a              shr_64.o
```

Looking at a nightly build for 11.0.8+3, the libfontmanager.so contains the following LIBPATH. It contains `/opt/freeware/lib` so the problem does not occur.
```
0      /opt/IBM/xlc/13.1.3/../../../../usr/lpp/xlC/lib:/opt/IBM/xlC/13.1.3/lib/aix61:/opt/IBM/xlC/13.1.3/lib:/opt/IBM/xlc/13.1.3/lib/aix61:/opt/IBM/xlc/13.1.3/lib:/usr/vac/lib/aix53:/opt/freeware/lib:/home/sxa/jdk8u252-b09-jre/lib/ppc64/j9vm:/home/sxa/jdk8u252-b09-jre/lib/ppc64:/home/sxa/jdk8u252-b09-jre/lib/ppc64/jli:/home/sxa/jdk8u252-b09-jre/../lib/ppc64:/usr/lib                                         
```

**Comment by pshipton** [comment]
@zl-wang fyi. Any opinions on this?

**Comment by andrew-m-leonard** [comment]
@sxa any thoughts on above?

**Comment by zl-wang** [comment]
@pshipton  OSS packages installation on AIX can be discussed in this forum:
https://www.ibm.com/developerworks/community/forums/html/forum?id=2eb0f36d-9534-471b-8b27-c21e6c5b9b2b&ps=25

I supposed the libgcc_s.a dependency by fontmanager was dragged in because of switching to use xlC16 (?), since my java11 and java8 fontmanager didn't show gcc_s.a dependency. 

milan:[j2se] ldd ./openj9.11/jdk-11.0.7+10-jre/lib/libfontmanager.so
./openj9.11/jdk-11.0.7+10-jre/lib/libfontmanager.so needs:
         /usr/lib/libfreetype.a(libfreetype.so.6)
Cannot find libawt.so
Cannot find libjava.so
Cannot find libjvm.so
         /opt/IBM/xlc/13.1.3/../../../../usr/lpp/xlC/lib/libC.a(shr_64.o)
         /opt/IBM/xlc/13.1.3/../../../../usr/lpp/xlC/lib/libC.a(ansi_64.o)
         /usr/lib/libpthreads.a(shr_xpg5_64.o)
         /usr/lib/libc.a(shr_64.o)
         /usr/lib/libz.a(libz.so.1)
         /opt/IBM/xlc/13.1.3/../../../../usr/lpp/xlC/lib/libC.a(shrcore_64.o)
         /opt/IBM/xlc/13.1.3/../../../../usr/lpp/xlC/lib/libC.a(ansicore_64.o)
         /unix
         /usr/lib/libcrypt.a(shr_64.o)

milan:[j2se] ldd ./sdk64/jre/lib/ppc64/libfontmanager.so
./sdk64/jre/lib/ppc64/libfontmanager.so needs:
Cannot find libawt.so
Cannot find libawt_xawt.so
Cannot find libjava.so
Cannot find libjvm.so
Cannot find libdbgwrapper80.so
         /usr/lib/libC.a(shr_64.o)
         /usr/lib/libC.a(shr2_64.o)
         /usr/lib/libC.a(ansi_64.o)
         /usr/lib/libc.a(shr_64.o)
         /usr/lib/libC.a(shrcore_64.o)
         /usr/lib/libC.a(ansicore_64.o)
         /unix
         /usr/lib/libcrypt.a(shr_64.o)

 Most of freeware libraries are not shipped by default on AIX, and users need to install them explicitly. Plus, most of them don't have symbolic links under /usr/lib (if you wanted to not set LIBPATH and be able to run, it is better to create those symbolic links).

**Comment by zl-wang** [comment]
or, build-time you have -L/opt/freeware/lib64

**Comment by pshipton** [comment]
Thanks. Now I realize this isn't so much a jdk11 build problem as a problem with the freeware installed on the machines. My jdk11 and your jdk11 should be the same, both downloaded from AdoptOpenJDK.net.

ldd is showing prereqs included by prereqs. The problem is related to what the installed libfreetype.a needs. On the machines I'm looking at, libfreetype.a needs libbz2.a and libbz2.a needs gcc_s.a. On the machine where it doesn't work, libbz2.a doesn't have a proper LIBPATH.

I'll go ahead an close this, and request the installation on the machine be fixed.
