### ISSUE TITLE
PR test jobs are not working reliably

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1770]
Just realised we don't have an issue for this, but it's been broken since March, which impacts people submitting PRs who may think they've broken something.

Since we haven't fixed it I've disabled the webhook for now.

Ref: https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/

**Comment by sxa** [comment]
See also https://github.com/AdoptOpenJDK/openjdk-build/issues/1528 which is related to the PR tester possibly not always cleaning up after itself

**Comment by M-Davies** [comment]
@sxa Can you check the PR-tester now? I put in a fix for it at https://github.com/AdoptOpenJDK/openjdk-build/pull/1919
