### ISSUE TITLE
Handle cross-compilation builds where java -version cannot be run

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1773]
RISC-V bulids are currently failing because the end of the pipeline tries to pick up a `version.txt` file which is the output from `java -version` on the final build. In the cross-compile case, you cannot run `java -version` on the build machine. As a temporary workaround we have implemented a [fake version.txt](https://github.com/AdoptOpenJDK/openjdk-build/pull/1766) but this will likely cause complications on the API so we should look to implement something a little less "hacked together" to do something valid in the absence of being able to run the resulting executable.

**Comment by M-Davies** [comment]
Is there no chance of getting a riscv machine to run the builds on and print out the java version?

**Comment by sxa** [comment]
Yes but it would require connecting into a remote machine, copying the build over somewhere, running it and clearing up and the build scripts currently don't do that.

**Comment by M-Davies** [comment]
@sxa Do we have a riscv machine we can use to print out the java version? I could create new job that is tied to said machine which takes in a built jdk, prints out the java version to a file and returns it back to the main pipeline?

**Comment by sxa** [comment]
At the moment we only have one and it tends to be tied up for quite a long time due to the slowness of executing tests etc. so I'd be concerned that it would block the pipelines for long periods of time until a system became available. @Willsparker does `stage4` run `java -version` reliably?

**Comment by Willsparker** [comment]
I believe so, yes. Just checked and it seems okay!

**Comment by M-Davies** [comment]
@sxa Are there any chances of obtaining more riscv systems? Admittedly, my solution in https://github.com/AdoptOpenJDK/openjdk-build/issues/1773#issuecomment-645395878 is not ideal but would running a `java -version` on the machine slow down the pipelines a lot? If all the job would do is take in a artifact, run java -version on it, archive to a txt and exit, would it really take a long time?

**Comment by sxa** [comment]
Happy for you to give it a shot if you think it's easily doable. My only concern would be how much complexity it would add to the pipelines to support that. Otherwise I'm happy with giving it a shot. We're only building one release (JDK11/J9) at the moment so the RISC-V machines will generally be completely free during the builds (i.e. not running any tests)

**Comment by sxa** [comment]
Another option for this would be to use qemu to run it on the local machine, although building a suitable version for CentOS6 is rather non-trivial

**Comment by Willsparker** [comment]
Would it have to be CentOS6 ...?

**Comment by sxa** [comment]
No but iI mentioned it because that's what we have for the docker builds just now (We may also have C7 but that's likely to be the the same)
We could of course create more images with other OSs but it would be nice to keep them consistent
