### ISSUE TITLE
Windows JDK15 build pipeline failures

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1774]
**Platform: Windows**

**Architecture:x64**

https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-x64-hotspot/ has been failing for over a month now

**Comment by sxa** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/1764 is an initial proposed fix

**Comment by M-Davies** [comment]
https://github.com/AdoptOpenJDK/openjdk-installer/pull/212 is superseeding https://github.com/AdoptOpenJDK/openjdk-build/pull/1764. @douph1 is looking to implement the fixes on the installer side instead of build

**Comment by sxa** [comment]
Oddly JDK15/Windows isn't showing in the failed builds today despite the installer job failing, so while this superficially looks ok, it's not.

We seem to have lost the propagation of the error code which was added in https://github.com/AdoptOpenJDK/openjdk-build/pull/1692/files

**Comment by douph1** [comment]
this is because of this revert https://github.com/AdoptOpenJDK/openjdk-build/commit/db4f1583ca22087e857f61e96d4476d7ca759fc8

**Comment by sxa** [comment]
No it wasn't @douph1 - the PR I referenced was later than the one you mentioned and was intended to fix the problem properly. It has been correctly propogating the error code for the last month since it was merged. The culprit (as identified my Morgan) was seemingly https://github.com/AdoptOpenJDK/openjdk-build/pull/1755

**Comment by M-Davies** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/1782 should set upstream jobs as FAILED if the installer fails

**Comment by douph1** [comment]
It was because of the commit that I mentioned that added a try / catch.
If the exception hadn't been catch, construction would have failed (I hope)?

**Comment by M-Davies** [comment]
Resolved as part of many PR's (documented here https://github.com/AdoptOpenJDK/openjdk-installer/issues/211#issuecomment-639486898)
