### ISSUE TITLE
JDK8 Solaris/SPARC builds disabled

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1775]
I believe this was because they were taking over six hours to complete:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot/

**Comment by gdams** [comment]
I'm working on getting access to other solaris hardware. If we are able to get access to other hardware then we could re install a fresh version of Solaris on our sparc server and see if that fixes things.

**Comment by sxa** [comment]
The question is what's causing it to be slow? And can we re-enable it (despite it being slow) and have it complete before te other platforms have finished testing?

**Comment by sxa** [comment]
Re-enabled at https://github.com/AdoptOpenJDK/openjdk-build/pull/2222
Slowness raised at https://github.com/AdoptOpenJDK/openjdk-build/issues/2206
Fix to upstream build problem (which we backported into 8u271 and 8u275) has now been merged into the main JDK8 stream has [now gone in](https://github.com/AdoptOpenJDK/openjdk-build/issues/2065)
