### ISSUE TITLE
Several aarch64 builds failing

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1791]
Haven't looked at them all but [several are failing early on](https://ci.adoptopenjdk.net/view/Failing%20Builds/) in the gradle phase

**Comment by sxa** [comment]
Error is:
```
13:18:54  Running gradle with /usr/lib/jvm/jdk-11.0.2+7
13:18:54  Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip
13:18:58  ...............................
13:18:58  Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch!
13:18:58  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
13:18:58  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
13:18:58  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
13:18:58  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
13:18:58  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:129)
13:18:58  	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155)
13:18:58  	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125)
13:18:58  	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
13:18:58  	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290)
13:18:58  	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
13:18:58  	at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:134)
13:18:58  	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
13:18:58  	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3495)
13:18:58  	at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3488)
```

**Comment by sxa** [comment]
Relevant facts:
- Gradle is running with /usr/lib/jvm/jdk-11.0.2+7 on build-packet-centos74-armv8-1
- JDK11 builds are failing, JDK8 on the same machine with the same gradle JVM seems [unaffected](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-hotspot/511/consoleFull)

**Comment by sxa** [comment]
I'm running a new pipeline at https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/964/ - based on the fact that not all aarch64 builds have failed, and we've seen various build issuejs this week, I want to verify whether the issues today were just a glitch that happened to affect JDK11

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/347/console has passed the gradle phase

That one actually failed last night with a download error separate from the one described above:
```
01:11:11  To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.2.1/userguide/gradle_daemon.html.
01:11:14  Daemon will be stopped at the end of the build stopping after processing
01:11:25  
01:11:25  FAILURE: Build failed with an exception.
01:11:25  
01:11:25  * Where:
01:11:25  Build file '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/pipelines/build.gradle' line: 27
01:11:25  
01:11:25  * What went wrong:
01:11:25  Could not determine the dependencies of task ':uberjar'.
01:11:25  > Could not resolve all files for configuration ':compile'.
01:11:25     > Could not download groovy-swing.jar (org.codehaus.groovy:groovy-swing:2.5.6)
01:11:25        > Could not get resource 'https://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-swing/2.5.6/groovy-swing-2.5.6.jar'.
01:11:25           > Tag mismatch!
01:11:25     > Could not download groovy.jar (org.codehaus.groovy:groovy:2.5.6)
```

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-hotspot/543/console has passed successfully on the next run (that is the job that failed with the SSL `Tag mismatch` issue described above. Closing

**Comment by andrew-m-leonard** [comment]
Re-occurred this morning: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/350/console

**Comment by andrew-m-leonard** [comment]
I think we also need a "retry" facility on these gradle downloads....?

**Comment by sxa** [comment]
One of the three JDK11 builds has passed on each of the last two nightly runs.
Need the bulid processes to be stable again though before diagnosing this further ...
Interesting that it's only affecting one platform though

**Comment by andrew-m-leonard** [comment]
I am suspecting gradle is hitting a flakey network issue and the exception it gets it has decided no to retry... Several people wingeing at gradle here (https://github.com/gradle/gradle/issues/8264) about gradle retry not being optimum...
Not sure what the answer is that being the case, other than dump Gradle and create this shared-lib a different way...?

**Comment by andrew-m-leonard** [comment]
I reckon we can add our own retry in sbin/build.sh to re-try gradlew script if it returns bad rc:
https://github.com/AdoptOpenJDK/openjdk-build/blob/97855e556cf5a57df3cbfedf94ac508500810e93/sbin/build.sh#L441

**Comment by andrew-m-leonard** [comment]
I have a a PR for gradlew retries here: https://github.com/AdoptOpenJDK/openjdk-build/pull/1841

**Comment by andrew-m-leonard** [comment]
This PR https://github.com/AdoptOpenJDK/openjdk-build/pull/1841
adds a 3 times retry on the gradlew command

**Comment by andrew-m-leonard** [comment]
Merged..
