### ISSUE TITLE
OpenJDK build on PPC running on Fedora on Jenkins fails

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#18]
The PPC job on Jenkins - https://ci.adoptopenjdk.net/view/build/job/openjdk_build_plinux/ fails with the below error:

```
## Starting jdk
/usr/bin/find: '/home/jenkins/workspace/openjdk_build_plinux/openjdk/build/linux-ppc64-normal-server-release/hotspot/dist/lib': No such file or directory
BuildJdk.gmk:51: recipe for target 'import-only' failed
gmake[2]: *** No rule to make target '/home/jenkins/workspace/openjdk_build_plinux/openjdk/build/linux-ppc64-normal-server-release/corba/dist/lib/classes.jar', needed by '/home/jenkins/workspace/openjdk_build_plinux/openjdk/build/linux-ppc64-normal-server-release/jdk/classes/_the.CORBA.classes.imported'.  Stop.
gmake[1]: *** [import-only] Error 2
/home/jenkins/workspace/openjdk_build_plinux/openjdk//make/Main.gmk:115: recipe for target 'jdk-only' failed
make: *** [jdk-only] Error 2
```

See full logs - https://ci.adoptopenjdk.net/view/build/job/openjdk_build_plinux/11/console

Although the real cause is, `corba` does not compile to produce the jar ile `/home/jenkins/workspace/openjdk_build_plinux/openjdk/build/linux-ppc64-normal-server-release/corba/dist/lib/classes.jar` due to compiling of one of the class failing. 

** Strange why the build didn't fail, but that's another issue **

The `javac` command triggered by the `corba` build is as below (for the failing class):
```
/usr/lib/jvm/java-1.8.0-ibm-1.8.0.4.1-1jpp.2.el7.ppc64le/bin/java -Xms64M -Xmx1600M -XX:ThreadStackSize=1536 -XX:PermSize=32m -XX:MaxPermSize=160m -XX:-PrintVMOptions -XX:-UnlockDiagnosticVMOptions -XX:-LogVMOutput "-Xbootclasspath/p:/home/gromero/openjdk-jdk8u/build/linux-ppc64-normal-server-release/langtools/dist/bootstrap/lib/javac.jar" -cp /home/gromero/openjdk-jdk8u/build/linux-ppc64-normal-server-release/langtools/dist/bootstrap/lib/javac.jar com.sun.tools.javac.Main -source 7 -target 7 -bootclasspath "/usr/lib/jvm/java-1.8.0-ibm-1.8.0.4.1-1jpp.2.el7.ppc64le/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-ibm-1.8.0.4.1-1jpp.2.el7.ppc64le/lib/tools.jar" -Xlint:all,-deprecation,-unchecked,-serial,-fallthrough,-cast,-rawtypes,-static,-dep-ann   -implicit:none -sourcepath "/home/gromero/openjdk-jdk8u/corba/src/share/classes" -d /home/gromero/openjdk-jdk8u/build/linux-ppc64-normal-server-release/corba/btclasses/logutil_classes  @/home/gromero/openjdk-jdk8u/build/linux-ppc64-normal-server-release/corba/btclasses/logutil_classes/_the.BUILD_LOGUTIL_batch.tmp && /usr/bin/mv /home/gromero/openjdk-jdk8u/build/linux-ppc64-normal-server-release/corba/btclasses/logutil_classes/_the.BUILD_LOGUTIL_batch.tmp /home/gromero/openjdk-jdk8u/build/linux-ppc64-normal-server-release/corba/btclasses/logutil_classes/_the.BUILD_LOGUTIL_batch
```
Needs further investigation.

Failing on environment: PPC, Fedora, IBM JDK9 (`java-1.8.0-ibm-1.8.0.4.1-1jpp.2.el7.ppc64le` or `java-1.8.0-ibm-devel-1.8.0.4.1-1jpp.2.el7.ppc64le`)

One more log file from Gustavo Romero (@grromero) [Building OpenJDK on Fedora on PPC](https://hastebin.com/raw/utukatijih) - building `corba` only.

Originally reported and investigated by @gdams, further reproduced by @neomatrix369 and @gromero.

For the exact same environment (PPC, Fedora) but when OpenJDK is used as the Boot JDK, we have no issues, see https://hastebin.com/raw/dihomikuco  - building `corba` only.

**Comment by tellison** [comment]
The IBM JDK has a significantly different CORBA implementation (amongst other things), so I suggest building OpenJDK 8 with previous builds of OpenJDK 7.

**Comment by gdams** [comment]
I am unable to find an openjdk7 release for ppc64le, I will install it if someone can point me in the right direction

**Comment by neomatrix369** [comment]
@gdams its best to use a JDK and not an OpenJDK binary to build OpenJDK itself.

I think any of the jdk for ppc64le might bump into the same corba issue we have. Unless someone from the PPC team want to adopt the issue and work around it amending the OpenJDK build scripts.

**Comment by gromero** [comment]
@gdams You can also build OpenJDK 8 from source using OpenJDK 8 itself (instead of 7). It's readily available on Ubuntu (apt-get install openjdk-8-jdk) and from RHEL if subscription is OK to the RHN (yum install -y java-1.8.0-openjdk && yum install -y java-1.8.0-openjdk). Regarding OpenJDK 8 on Fedora, in any case, you can find the packages for FC <= 25 at https://ppc.koji.fedoraproject.org/koji/packageinfo?packageID=15550 and FC >= 26 at https://koji.fedoraproject.org/koji/packageinfo?packageID=15685) Please note the last released version of OpenJDK 8 is tag 121, so 1.8.0.121 is the last update. HTH.

**Comment by gromero** [comment]
@neomatrix369, as @tellison said, just move from IBM JDK to OpenJDK to solve that issue. Distros do exactly that. That's also my recommendation.

**Comment by tellison** [comment]
This is now fixed, for example see
https://ci.adoptopenjdk.net/job/openjdk_build_ppc64le_linux/16/
