### ISSUE TITLE
test-scaleway-ubuntu1604-x64-1: out of disk space

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1806]
Test job failures on test-scaleway-ubuntu1604-x64-1:
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.system_x86-64_linux/212/console
```
18:31:49  java.nio.file.FileSystemException: /tmp/resource-3979388526680510708: No space left on device
```

**Comment by Willsparker** [comment]
Ref: https://adoptopenjdk.slack.com/archives/C53GHCXL4/p1590658509194500

I did fairly recently clear it off. Having a look now, it looks like 3.2Gb is taken up from `gcov`, which hasn't been touched for since 2018.
```
root@test-scaleway-ubuntu1604-x64-1:/home/jenkins/workspace# du -ha --time | grep 2018 | sort -h
...
2.0G	2018-07-18 13:37	./gcov/openjdk-jdk8u/jdk/test
2.2G	2018-07-18 13:37	./gcov/openjdk-jdk8u/jdk
2.5G	2018-07-18 13:37	./gcov/openjdk-jdk8u
3.2G	2018-07-27 14:19	./gcov
```

**Comment by sxa** [comment]
Machine has a relatively low amoiunt of disk space compared to some of our others (50Gb) and 35Gb is being used by docker images

**Comment by Willsparker** [comment]
Ran `docker system prune` to ensure nothing of use was being deleted, freed up 22.6GB :-)

**Comment by sxa** [comment]
- [ ]
