### ISSUE TITLE
Rebuilding fails to validate existing openjdk git repo

### ISSUE THREAD

**Issue by sveitech** [AdoptOpenJDK/openjdk-build#1809]
This bug seems to be introduced as a side-effect of issue #1708.

When rebuilding from the top, I get the following error:

```
From https://github.com/AdoptOpenJDK/openjdk-build
 * branch            master     -> FETCH_HEAD
origin  https://github.com/adoptopenjdk/openjdk-jdk11u.git (fetch)
origin  https://github.com/adoptopenjdk/openjdk-jdk11u.git (push)
jdk11
Incorrect Source Code for jdk11u.  This is an error, please check what is in /home/foo/projects/openjdk_cross_levi9/openjdk-build/workspace/build and manually remove, exiting...
```

This seems to be introduced by that patch from issue #1708. 

The code for checking if the repository is valid is (from prepareWorkspace.sh):

```
checkoutAndCloneOpenJDKGitRepo() {

  cd "${BUILD_CONFIG[WORKSPACE_DIR]}/${BUILD_CONFIG[WORKING_DIR]}"

  # Check that we have a git repo, we assume that it is a repo that contains openjdk source
  if [ -d "${BUILD_CONFIG[OPENJDK_SOURCE_DIR]}/.git" ]; then
    set +e
    git --git-dir "${BUILD_CONFIG[OPENJDK_SOURCE_DIR]}/.git" remote -v
    echo "${BUILD_CONFIG[OPENJDK_CORE_VERSION]}"
    git --git-dir "${BUILD_CONFIG[OPENJDK_SOURCE_DIR]}/.git" remote -v | grep "origin.*fetch" | grep "${BUILD_CONFIG[OPENJDK_CORE_VERSION]}" | grep "${BUILD_CONFIG[REPOSITORY]} "
    local isValidGitRepo=$?
    set -e
```

The remote name ends in .git. For example:

origin  https://github.com/adoptopenjdk/openjdk-jdk11u.git (fetch)

When the ${BUILD_CONFIG[REPOSITORY]} variable is set to https://github.com/adoptopenjdk/openjdk-jdk11u, the grep fails when adding the space at the end.

So:

```
echo "origin  https://github.com/adoptopenjdk/openjdk-jdk11u.git (fetch)" | grep "https://github.com/adoptopenjdk/openjdk-jdk11u "
```

will never succeed, as the grep is looking for a space between jdk11u and .git.

**Comment by sxa** [comment]
ping @Willsparker

**Comment by Willsparker** [comment]
Good spot. I'll take a look :-)

**Comment by junyzheng** [comment]
I think this change introduced another issue. In our pipeline. our `REPOSITORY` is: `https://dev.azure.com/ms-juniper/Juniper/_git/shenandoah-jdk11`. So it breaks our existing pipeline. I will create another PR to fix this problem.

**Comment by junyzheng** [comment]
Just created a new PR: #1837

**Comment by Willsparker** [comment]
@junyzheng Thanks for the PRs ! Sorry about that
