### ISSUE TITLE
OpenJDK local disk check not working on AIX

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#181]
```bash
WARNING: Your build output directory is not on a local disk.
This will severely degrade build performance!
It is recommended that you create an output directory on a local disk,
and run the configure script again from that directory.
```

@sxa555 informs me that the check uses `df -l` which isn't a valid flag on AIX

**Comment by sxa555** [comment]
The simplest way to resolve this may be to modify the `PATH` to include `/usr/sysv/bin` before `/usr/bin` as that has a version of `df` that supports the `-l` option. A less drastic approach would be to set `DF='/usr/sysv/bin/df"` to force configure to use that

**Comment by gdams** [comment]
hmm okay, fancy submitting a PR to auto export that env var if we are on AIX?

**Comment by sxa555** [comment]
Hmm `/usr/sysv/bin/df` isn't quite working the same. Unless you specify the exact mount point as a directory (i.e. normally `.` or `$PWD` won't work as they're deeper down the file system) it doesn't give the expected result ... Still investigating

**Comment by sxa555** [comment]
https://bugs.openjdk.java.net/browse/JDK-8189619 raised to fix this upstream

**Comment by karianna** [comment]
@sxa555  - The patch has landed upstream - can this now be closed or does that patch need to be backported.

**Comment by gdams** [comment]
We are waiting for this to be backported to 8 and 9. Not sure if any progress has been made with that yet.

**Comment by sxa555** [comment]
@karianna Do you know if such things will get automatically backported by Oracle or will it need us to submit additional requests?

**Comment by karianna** [comment]
@sxa555 Separate back port requests will have to go into 8 and 9.  I know that 8 has an updates project, but under the new world I don't think 9 will be getting any more patches so that's one we'll have to put into the AdoptOpenJDK derivative (if I've read all of the rules correctly).

It's worth pinging Thomas Stuefe and asking if he's backport it to 8 for us (and 9 if that's possible, but see above).

**Comment by karianna** [comment]
@sxa555 Is this still important?

**Comment by gdams** [comment]
this bug has been fixed upstream
