### ISSUE TITLE
Job Regenerator prevents auto creation of downstream jobs

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1814]
**Platform:**
All
**Architecture:**
All

https://github.com/AdoptOpenJDK/openjdk-build/pull/1547 enabled concurrent pipelines but in doing so, we can no longer auto generate [downstream jobs](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/) when a pipeline executes them for the first-time (they have to be created manually). See https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1590139534275000 for recent grappling with this.

The reason it doesn't work is because we're using the API to query what jobs currently exist and ONLY generated DSL's for those, not accounting for new builds. We're not building all the dsl's each time we execute a pipeline anymore, so the job has no idea what to do with new builds.

I.e. if we wanted to add `jdk11u-linux-riscv64-openj9` to our nightlies, it would currently be impossible to auto generate because we only build the DSL's for existing platforms and variants returned in the [jdk11u job folder API query](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/api/json?tree=jobs[name]&pretty=true&depth=1). We would need a way of predicting what new builds need to be added and creating the jobs that way.

**Idea**
Amend the current job regenerators to sort through the [targetConfiguration files](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk11u.groovy) after finishing with the API to scan for new variants and key entry's (OS and archs) into the map. If it detects an OS, Arch or variant it hasn't seen before, it builds a DSL in the same way as the current method.

New builds are usually added by adding to these config files (see https://github.com/AdoptOpenJDK/openjdk-build/pull/1815) so it would enable the regenerators to instantly realise there is a new config on the block.

OR

Do the same as above but move it into it's own independent job seperate from the regenerators that use the API

**Comment by M-Davies** [comment]
@sxa @andrew-m-leonard I'd appreciate some feedback on the ideas above. Can you think of any more? What else would need to be done that I have not considered or missed?

**Comment by andrew-m-leonard** [comment]
For some reason I thought the job regenerator used the target Configuration files...hence would generate the correct jobs... Can we make it do that?

**Comment by M-Davies** [comment]
We could make it do it alongside the API. 

At the moment I'm thinking to keep the initial API stage but add a new stage right after that pulls each config file from the Github API, parses it to a job name (`jdk11u-linux-riscv-hotspot`) and checks to see if it has been regenerated using the API already. If it hasn't, it regenerates it in the same manner as the job regenerated using the API

**Comment by M-Davies** [comment]
One problem though, the Github API will reject access from unauthorized users after a few attempts

From https://developer.github.com/v3/#failed-login-limit:
> After detecting several requests with invalid credentials within a short period, the API will temporarily reject all authentication attempts for that user (including ones with valid credentials) with 403 Forbidden

So we would need to add an OAuth or Personal Access Token to the API Call to ensure we don't get blocked every few requests. @andrew-m-leonard Do we have a location to store PAC/OAuth tokens inside jenkins as I'd rather not hard code them in for obious reasons

**Comment by andrew-m-leonard** [comment]
Why do we do this?: The reason it doesn't work is because we're using the API to query what jobs currently exist and ONLY generated DSL's for those

Why query what jobs currently exist, can't we just go straight to the targetConfiguration?
what am I missing?

**Comment by M-Davies** [comment]
Good point. It would remove a lot of reliability on the parsing algorithms and would allow us to parse new platforms. I think all the platforms we currently build exist in targetConfiguration files
