### ISSUE TITLE
 javax.net.ssl.SSLException: Tag mismatch exception

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1816]
**Platform:**
jdk11u-linux-aarch64-hotspot
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-hotspot/548/console

**Architecture:**
00:31:54  {
00:31:54      "ARCHITECTURE": "aarch64",
00:31:54      "TARGET_OS": "linux",
00:31:54      "VARIANT": "hotspot",
00:31:54      "JAVA_TO_BUILD": "jdk11u",
00:31:54      "TEST_LIST": [
00:31:54          "sanity.openjdk",
00:31:54          "sanity.system",
00:31:54          "extended.system",
00:31:54          "sanity.perf"
00:31:54      ],
00:31:54      "SCM_REF": "",
00:31:54      "BUILD_ARGS": "",
00:31:54      "NODE_LABEL": "centos7&&build&&linux&&aarch64",
00:31:54      "CONFIGURE_ARGS": "--enable-dtrace=auto",
00:31:54      "OVERRIDE_FILE_NAME_VERSION": "",
00:31:54      "RELEASE": false,
00:31:54      "PUBLISH_NAME": "",
00:31:54      "ADOPT_BUILD_NUMBER": "",
00:31:54      "ENABLE_TESTS": true,
00:31:54      "CLEAN_WORKSPACE": false
00:31:54  }
Please describe the issue that you are having with our binaries and if possible how to recreate it.
`Downloading https://services.gradle.org/distributions/gradle-5.2.1-bin.zip 00:59:59 ........................................... 00:59:59 Exception in thread "main" javax.net.ssl.SSLException: Tag mismatch! 00:59:59 at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129) 00:59:59 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321) 00:59:59 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264) 00:59:59 at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259) 00:59:59 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:129) 00:59:59 at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155) 00:59:59 at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125) 00:59:59 at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823) 00:59:59 at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:290) 00:59:59 at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351) 00:59:59 at java.base/sun.net.www.MeteredStream.read(MeteredStream.java:134) 00:59:59 at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133) 00:59:59 at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3495) 00:59:59 at java.base/sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3488) 00:59:59 at org.gradle.wrapper.Download.downloadInternal(Download.java:73) 00:59:59 at org.gradle.wrapper.Download.download(Download.java:52) 00:59:59 at org.gradle.wrapper.Install$1.call(Install.java:62) 00:59:59 at org.gradle.wrapper.Install$1.call(Install.java:48) 00:59:59 at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69) 00:59:59 at org.gradle.wrapper.Install.createDist(Install.java:48) 00:59:59 at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107) 00:59:59 at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:62) 00:59:59 Caused by: javax.crypto.AEADBadTagException: Tag mismatch! 00:59:59 at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:580) 00:59:59 at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116) 00:59:59 at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053) 00:59:59 at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:941) 00:59:59 at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491) 00:59:59 at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:779) 00:59:59 at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730) 00:59:59 at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2497) 00:59:59 at java.base/sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1613) 00:59:59 at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:262) 00:59:59 at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190) 00:59:59 at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)`

**Comment by karianna** [comment]
Hmm, we're not getting the hostname where this build occurs.

**Comment by M-Davies** [comment]
This was likely a net issue in the maven repo where our dependancies come from. Now resolved. Closing
