### ISSUE TITLE
Please Provide ZGC Support on Windows build of AdoptOpenJDK 11

### ISSUE THREAD

**Issue by keffinbarnaby** [AdoptOpenJDK/openjdk-build#1817]
Hello,

I can see from #782 and #641 that ZGC has been enabled by default in AdoptOpenJDK builds for Linux, and I have verified that this is the case myself. However, I have installed the Windows build through the latest MSI (specifically `OpenJDK11U-jdk_x64_windows_hotspot_11.0.7_10.msi`) with all features selected, and it appears that ZGC has not been enabled. From cmd:

```
C:\Users\keffin.barnaby>java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)

C:\Users\keffin.barnaby>java -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -version
Error occurred during initialization of VM
Option -XX:+UseZGC not supported
```

Would it be possible to enable ZGC in future Windows builds?

FWIW I'm using `Windows 10 Pro Version 10.0.18363 Build 18363`. Whilst I don't have another Windows box to test on, from the error given I am not expecting this to be the issue.

**Comment by aahlenst** [comment]
Experimental ZGC support on Windows was introduced with OpenJDK 14 accoring to https://openjdk.java.net/jeps/365. And it is not supported before 1803 (OP has 1909).

**Comment by keffinbarnaby** [comment]
> Experimental ZGC support on Windows was introduced with OpenJDK 14 accoring to https://openjdk.java.net/jeps/365. And it is not supported before 1803 (OP has 1909).

Thank you for your input and for replying so quickly. I wasn't aware that it was missing in Windows for all Vendors JDK 11 builds, I only noticed whilst trying to locally sanity-check a migration to AdoptOpenJDK for my Linux servers. I'll go straight to testing on Linux.
