### ISSUE TITLE
Unable to locate tools.jar causing 2 build failures in x86-64_linux & x86-64_mac

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1818]
**Platform:**
Test_openjdk11_hs_sanity.openjdk_x86-64_linux
Test_openjdk11_hs_sanity.openjdk_x86-64_mac

https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/261/console

**Architecture:**
x86-64_linux
x86-64_mac

Please describe the issue that you are having with our binaries and if possible how to recreate it.
`09:50:24 Unable to locate tools.jar. Expected to find it in /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/lib/tools.jar 09:50:24 Buildfile: /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/scripts/build_tools.xml 09:50:25 09:50:25 build: 09:50:25 09:50:25 clean: 09:50:25 09:50:25 init: 09:50:25 [mkdir] Created dir: /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/bin 09:50:25 09:50:25 compile: 09:50:25 [echo] Ant version is Apache Ant(TM) version 1.10.5 compiled on July 10 2018 09:50:25 [echo] ============COMPILER SETTINGS============ 09:50:25 [echo] ===fork: yes 09:50:25 [echo] ===debug: on 09:50:25 [javac] Compiling 15 source files to /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/bin 09:50:25 09:50:25 BUILD FAILED 09:50:25 /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/scripts/build_tools.xml:56: The following error occurred while executing this line: 09:50:25 /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/openjdk-tests/TKG/scripts/build_tools.xml:35: Error running /home/jenkins/workspace/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/openjdkbinary/j2sdk-image/bin/javac compiler`

**Comment by karianna** [comment]
@archanaNogriya I think this is a test issue?  Thre is no tools.jar in Java 11 and the tests should not be looking for one...

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_x86-64_linux/ looks ok now. Closing...
