### ISSUE TITLE
Move xLinux build machines to CentOS7

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1819]
RHEL6/CentOS6 is not being supported beyond November 2020 (Source: https://wiki.centos.org/About/Product)

We currently build all our x64 JDKs on CentOS6

We need to look at whether we can reasonably swit4ch the building of this to e on CentOS7 or whether we need isolated (unpatched) systems to continue building the 8 and 11 streams that we have built on the old releases in order to avoid introducing incompatibilities.

On other Linux platforms, we already build on CentOS/RHEL7.

This will increase the GLIBC level on xlinux from 2.12 to 2.17 - we currently have this message on our [supported platforms page](https://adoptopenjdk.net/supported_platforms.html):

```
Note: Any other Linux distributions that have a minimum glibc
version 2.12 on x86 or version glibc version 2.17 on other
architectures are expected to function without problems.
```

**Comment by sxa** [comment]
FYI @AdoptOpenJDK/tsc:

SLES12 uses glibc 2.22
Ubuntu 14.04 is glibc 2.19
Debian 8 (jessie) is glibc 2.19

It seems highliy unlikely that anyone is using something earlier than those in production now (Debian 7/wheezy has 2.13, SLES11 2.11), but a move to 2.17 would break anything earlier than the versions above.

**Comment by pshipton** [comment]
@DanHeidinga fyi

**Comment by DanHeidinga** [comment]
I'm slightly concerned about this due to the changed glibc level.  Starting some discussions internally to determine how much of an issue this will (or won't) be for us

**Comment by DanHeidinga** [comment]
@sxa What's the timeline for making this change?  Trying to determine how long my stakeholders have to get back to me with concerns

**Comment by sxa** [comment]
I'm not proposing to do it immediately (though may be nice to switch JDK15 ...) so plenty of time for you to contact others. If that changes I will of course let you know

**Comment by pshipton** [comment]
Agreed that JDK15+ should at least change, even if jdk8-11 don't or use different techniques to keep compatibility with glibc 2.12.

**Comment by DanHeidinga** [comment]
@sxa Is there a blog post here at Adopt planned to communicate that builds will be drop support for CentOS6/RHEL6 and the corresponding glibc level change?  If not, I can help draft something to drive awareness of this in the broader community

**Comment by aahlenst** [comment]
@DanHeidinga Currently no plans for a dedicated blog post. If it's only for 15, it's probably going to be a part of the release announcement. If we want to switch across the board and are looking for feedback beforehand, we should do a separate blog post. If I recall the TSC discussion correctly, we haven't come to a conclusion, yet, what exactly we should do.

**Comment by sxa** [comment]
Some stats from the Fedora repositories - EPEL for v6 is still above v8, and about 1/6 of that of v7:
https://admin.fedoraproject.org/mirrormanager/statistics/2020-06-23/repositories

**Comment by sxa** [comment]
We have an alternative mitigation for this, therefore closing
