### ISSUE TITLE
mac-x64 build are failing: Invalid Boot JDK

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1824]
**Platform:**
jdk-mac-x64-openj9
jdk-mac-x64-hotspot

**Architecture:**
{
04:30:55      "ARCHITECTURE": "x64",
04:30:55      "TARGET_OS": "mac",
04:30:55      "VARIANT": "openj9",
04:30:55      "JAVA_TO_BUILD": "jdk",
04:30:55      "TEST_LIST": [
04:30:55          false
04:30:55      ],
04:30:55      "SCM_REF": "",
04:30:55      "BUILD_ARGS": "",
04:30:55      "NODE_LABEL": "macos10.14&&build&&mac&&x64",
04:30:55      "CONFIGURE_ARGS": "--enable-dtrace",
04:30:55      "OVERRIDE_FILE_NAME_VERSION": "",
04:30:55      "RELEASE": false,
04:30:55      "PUBLISH_NAME": "",
04:30:55      "ADOPT_BUILD_NUMBER": "",
04:30:55      "ENABLE_TESTS": true,
04:30:55      "CLEAN_WORKSPACE": false

Please describe the issue that you are having with our binaries and if possible how to recreate it.
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-x64-openj9/4/

`configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK`

**Comment by M-Davies** [comment]
Looks like `JAVA_HOME` was set to a JDK 8 binary
```
04:31:07  Required boot JDK version: 14
04:31:07  Setting JDK_BOOT_DIR to $JAVA_HOME
04:31:07  Boot jdk directory: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home:
04:31:07  BOOT JDK: openjdk version "1.8.0_252"
04:31:07  BOOT JDK: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
04:31:07  BOOT JDK: OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
04:31:07  JDK IN PATH: openjdk version "1.8.0_252"
04:31:07  JDK IN PATH: OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
04:31:07  JDK IN PATH: OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)
```
@Willsparker IIRC you have dealt with this sort of problem before? What is the procedure for when we have an invalid boot JDK?

**Comment by M-Davies** [comment]
Ah I see why. It looks like it failed to download a valid boot jdk
```
04:31:07  Downloading GA release of boot JDK version 14...
04:31:06   > git rev-parse origin/master^{commit} # timeout=10
04:31:06   > git config core.sparsecheckout # timeout=10
04:31:06   > git checkout -f 6a5ffb79321034b8a001aed7ef805a1dd40c57f2 # timeout=10
04:31:07  Downloading GA release of boot JDK version 14 failed.
```
This is related to https://github.com/AdoptOpenJDK/openjdk-build/issues/1825

**Comment by M-Davies** [comment]
[The API went down this morning so I'll let the builds go over the weekend and see if we see this again](https://adoptopenjdk.slack.com/archives/CFUJV9XV0/p1591342808199000)

**Comment by karianna** [comment]
I wonder if we should abort the byuild when that download fails with a clear message that we can't build due to a missing boot

**Comment by Willsparker** [comment]
@M-Davies AH, didn't know the API went down this morning. That would explain an issue I've been having :) What `JAVA_HOME` is set to shouldn't affect the `JDK_BOOT_DIR` (usually), but as you say, it looks like it just couldn't download one and so defaulted to `JAVA_HOME`.

**Comment by M-Davies** [comment]
> I wonder if we should abort the byuild when that download fails with a clear message that we can't build due to a missing boot

Created https://github.com/AdoptOpenJDK/openjdk-build/issues/1826 to follow up on that ;)

**Comment by sxa** [comment]
AdoptOpenJDK APi server fell over last night  and is now back so this is not arepeatable problem (although we should perhaps mention in it ithe intermittent failures issue)
