### ISSUE TITLE
linux-s390x is not able to download boot JDK version 14. 

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1825]
**Platform:**
jdk-linux-s390x-hotspot
jdk-aix-ppc64-openj9
jdk-aix-ppc64-hotspot

**Architecture:**
{
04:30:58      "ARCHITECTURE": "s390x",
04:30:58      "TARGET_OS": "linux",
04:30:58      "VARIANT": "hotspot",
04:30:58      "JAVA_TO_BUILD": "jdk",
04:30:58      "TEST_LIST": [
04:30:58          false
04:30:58      ],
04:30:58      "SCM_REF": "",
04:30:58      "BUILD_ARGS": "",
04:30:58      "NODE_LABEL": "build&&linux&&s390x",
04:30:58      "CONFIGURE_ARGS": "--disable-ccache --enable-dtrace",
04:30:58      "OVERRIDE_FILE_NAME_VERSION": "",
04:30:58      "RELEASE": false,
04:30:58      "PUBLISH_NAME": "",
04:30:58      "ADOPT_BUILD_NUMBER": "",
04:30:58      "ENABLE_TESTS": true,
04:30:58      "CLEAN_WORKSPACE": false
04:30:58  }

04:30:58  {
04:30:58      "ARCHITECTURE": "ppc64",
04:30:58      "TARGET_OS": "aix",
04:30:58      "VARIANT": "openj9",
04:30:58      "JAVA_TO_BUILD": "jdk",
04:30:58      "TEST_LIST": [
04:30:58          false
04:30:58      ],
04:30:58      "SCM_REF": "",
04:30:58      "BUILD_ARGS": "",
04:30:58      "NODE_LABEL": "xlc16&&aix715&&build&&aix&&ppc64",
04:30:58      "CONFIGURE_ARGS": "",
04:30:58      "OVERRIDE_FILE_NAME_VERSION": "",
04:30:58      "RELEASE": false,
04:30:58      "PUBLISH_NAME": "",
04:30:58      "ADOPT_BUILD_NUMBER": "",
04:30:58      "ENABLE_TESTS": true,
04:30:58      "CLEAN_WORKSPACE": false
04:30:58  }

Please describe the issue that you are having with our binaries and if possible how to recreate it.
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-s390x-hotspot/135/console

`04:31:14  Downloading GA release of boot JDK version 14...
04:31:14  
04:31:14  gzip: stdin: unexpected end of file
04:31:14  tar: Child returned status 1
04:31:14  tar: Error is not recoverable: exiting now
04:31:14  Downloading GA release of boot JDK version 14 failed.
04:31:14  Attempting to download EA release of boot JDK version 14 ...
04:31:15  
04:31:15  gzip: stdin: unexpected end of file
04:31:15  tar: Child returned status 1
04:31:15  tar: Error is not recoverable: exiting now
04:31:13   > /usr/local/bin/git rev-parse origin/master^{commit} # timeout=10
04:31:13   > /usr/local/bin/git config core.sparsecheckout # timeout=10
04:31:13   > /usr/local/bin/git checkout -f 6a5ffb79321034b8a001aed7ef805a1dd40c57f2 # timeout=10`

**Comment by M-Davies** [comment]
[The API went down this morning so I'll let the builds go over the weekend and see if we see this again](https://adoptopenjdk.slack.com/archives/CFUJV9XV0/p1591342808199000)

**Comment by sxa** [comment]
AdoptOpenJDK APi server fell over last night  and is now back so this is not arepeatable problem (although we should perhaps mention in it ithe intermittent failures issue

**Comment by sxa** [comment]
> [The API went down this morning so I'll let the builds go over the weekend and see if we see this again](https://adoptopenjdk.slack.com/archives/CFUJV9XV0/p1591342808199000)

I don't think that's the right approach going into the weekend - we need to re-run and try and be stable going into the weekend especially since this appears to be masking other problems that we need to fix at the moment (I have kicked off new JDK11 and 14 pipelines)
