### ISSUE TITLE
jdk11u-windows-x64-hotspot : Build failed in configuration 'windows-x86_64-normal-clientANDserver-release'

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1832]
**Platform:**
jdk11u-windows-x64-hotspot

**Architecture:**
{
00:31:52      "ARCHITECTURE": "x64",
00:31:52      "TARGET_OS": "windows",
00:31:52      "VARIANT": "hotspot",
00:31:52      "JAVA_TO_BUILD": "jdk11u",
00:31:52      "TEST_LIST": [
00:31:52          "sanity.openjdk",
00:31:52          "sanity.perf",
00:31:52          "sanity.system",
00:31:52          "extended.system"
00:31:52      ],
00:31:52      "SCM_REF": "",
00:31:52      "BUILD_ARGS": "--jvm-variant client,server",
00:31:52      "NODE_LABEL": "win2012&&build&&windows&&x64",
00:31:52      "CONFIGURE_ARGS": "",
00:31:52      "OVERRIDE_FILE_NAME_VERSION": "",
00:31:52      "RELEASE": false,
00:31:52      "PUBLISH_NAME": "",
00:31:52      "ADOPT_BUILD_NUMBER": "",
00:31:52      "ENABLE_TESTS": true,
00:31:52      "CLEAN_WORKSPACE": false
00:31:52  }

Please describe the issue that you are having with our binaries and if possible how to recreate it.
Running on build-azure-win2012r2-x64-2

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-hotspot/618/console

00:55:36  make[2]: *** [make/Main.gmk:203: jdk.internal.vm.compiler-java] Error 127
00:55:36  make[2]: *** Waiting for unfinished jobs....
01:02:00  
01:02:00  ERROR: Build failed for targets 'product-images legacy-jre-image test-image' in

**Comment by karianna** [comment]
Cleared itself up the following run.

**Comment by M-Davies** [comment]
This was also a dup of https://github.com/AdoptOpenJDK/openjdk-build/issues/1741
