### ISSUE TITLE
s390x build attempted to check out incorrect repository branch

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#1839]
Some s390x build jobs failed - e.g. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-linux-s390x-openj9-linuxXL/105/console failed because they tried to check out a repository branch which did not exist.  The branch name in error was supplied as a parameter to a previous job (which failed 'correctly') but not subsequent jobs.
Thanks to  @leonarda for working out the likely problem is in the build caching:
```
15:03:39  Resetting the git openjdk source repository at /home/jenkins/workspace/build-scripts/jobs/jdk14u/jdk14u-linux-s390x-openj9-linuxXL/workspace/build/src in 10 seconds...
15:03:50  Pulling latest changes from git openjdk source repository
15:03:50  Fetching origin
15:03:50  fatal: Couldn't find remote ref refs/heads/openj9-0.21.0-m1
15:03:50  error: Could not fetch origin
```
"The key is “Resetting the git(existing!) openjdk source repo at….”
The previous job ran on that machine and created the bad ref in the repo “cache”, which then caused the subsequent job to try and fetch it"

CLEAN_WORKSPACE is set to "false" for this job - could that be the reason?  (CLEAN_WORKSPACE is not a user supplied parameter).  But if it is, why have we not seen this error before (at least, I have not seen it before).

**Comment by lumpfish** [comment]
CLEAN_WORKSPACE is in fact a user supplied parameter - I'm just unable to spot it.  I'll rerun with that set and close if it fixes the issue.

**Comment by lumpfish** [comment]
Build ran OK with `cleanWorkspaceBeforeBuild` ticked.  But since that is not the default it is not clear to a user under what conditions it should / should not be set to "on".

**Comment by andrew-m-leonard** [comment]
@lumpfish fyi, working on making the checkout code more reslient and informative: https://github.com/AdoptOpenJDK/openjdk-build/pull/1843/files
