### ISSUE TITLE
prepareWorkspace.sh build workspace cache fails frequently

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1840]
Recent failures preparing workspace from previous build cache failures:
```
21:30:53  Fetching origin
21:30:54  fatal: Couldn't find remote ref refs/heads/openj9-0.21.0-m1
21:30:54  error: Could not fetch origin
```

https://github.com/AdoptOpenJDK/openjdk-build/issues/1809

Maybe we should remove this cache?

**Comment by karianna** [comment]
See #1839 as well

**Comment by andrew-m-leonard** [comment]
Making workspace more reslient and informative: https://github.com/AdoptOpenJDK/openjdk-build/pull/1843/files
