### ISSUE TITLE
archiving asmtools as jar file rather than zipping and tarring it and also provide a sha1 file

### ISSUE THREAD

**Issue by TianyuZuo** [AdoptOpenJDK/openjdk-build#185]
Hi,

Is that possible to provide the downloadable asmtools file as .jar or its original .zip file? Tarring it into tar makes it hard to integrate into an automation test process. 

The test automation need to untar it and unzip it, before getting the asmtools.jar file. If these two steps can be removed, it will make the test automation more adoptable to other platforms, without verifying platforms to check which cmd to untar and unzip file.

Also, I think a sha1 or sha256 file will be great help on verifying if the file is downloaded correctly.

**Comment by karianna** [comment]
Also see #28

**Comment by TianyuZuo** [comment]
Hi @karianna 

I also noticed that adopOpenJDK also provide download link from here https://adopt-openjdk.ci.cloudbees.com/job/asmtools/

Is that ci a copy of current jenkins ci or a totally different one? Which will be the main download source?

**Comment by neomatrix369** [comment]
@karianna https://github.com/AdoptOpenJDK/openjdk-build/issues/185#issuecomment-344081675 this issue is different from the sha256 referred to by @TianyuZuo, might not be related.

**Comment by karianna** [comment]
Ah OK.

**Comment by neomatrix369** [comment]
@TianyuZuo https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/ have a look at these artifacts, they should help you out, I have tied up the scripts a bit feel free to suggest any improvements.

**Comment by neomatrix369** [comment]
@TianyuZuo  Are you happy to close this issue if this helps your use case?

**Comment by TianyuZuo** [comment]
Thanks for your help mani. Closed this issue.
