### ISSUE TITLE
Build failed due to configuration failure for jdk14u-mac-x64

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1857]
**jdk14u-mac-x64-hotspot**
**jdk14u-mac-x64-openj9**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-mac-x64-hotspot/97/console

`ERROR: Build failed for targets 'product-images mac-legacy-jre-bundle test-image' in configuration 'macosx-x86_64-server-release' (exit
`

**Comment by M-Davies** [comment]
Looks ok now https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-mac-x64-hotspot/
