### ISSUE TITLE
Failed to copy artifacts - build-azure-win2012r2-x64-2 - jdk14u-windows-x64-openj9

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1858]
**jdk14u-windows-x64-openj9**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk14u/job/jdk14u-windows-x64-openj9/105/console

`Execution error: Failed to copy artifacts from build-scripts/release/create_installer_windows with filter: wix/ReleaseDir/OpenJDK*jdk_*_windows*.msi`

**Comment by M-Davies** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-build/issues/1834
