### ISSUE TITLE
jdk15 is created, JDK-Next must be changed to 16

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/openjdk-build#1866]
Failure : this job get PRODUCT_MAJOR_VERSION=15 but zip file contain jdk-16+0

https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/4623/

https://mail.openjdk.java.net/pipermail/jdk-dev/2020-June/004401.html
We’ve forked the main-line source repository, jdk/jdk, to the jdk/jdk15
stabilization repository.  Any changes pushed to jdk/jdk are now bound
for JDK 16, as noted previously [2].

**Comment by douph1** [comment]
the installer job was launched by  build-scripts » openjdk15-pipeline

**Comment by M-Davies** [comment]
To confirm what will be needed for this

- Create a [jdk16 config file](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk15.groovy) and [regeneration pipeline](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/regeneration/jdk15_regeneration_pipeline.groovy)
- Updating the [job regenerators](https://ci.adoptopenjdk.net/job/build-scripts/job/utils/) by creating a jdk15 regenerator and moving the current jdk-next regenerator to its own config file and regenerator

After https://github.com/AdoptOpenJDK/openjdk-build/pull/1849, we shouldn't have to make any changes to the code base itself as the `tip_version` has been updated in the api already https://api.adoptopenjdk.net/v3/info/available_releases.

I'll be following the instructions at https://github.com/AdoptOpenJDK/openjdk-build/blob/master/RELEASING.md#openjdk-new-release

**Comment by andrew-m-leonard** [comment]
openj9 jdk15 extensions now exist: https://github.com/ibmruntimes/openj9-openjdk-jdk15

**Comment by sxa** [comment]
Sounds goo to me - and it will be good to follow those instructions and add in any clarifications/missing parts as you see fit - any problems (e.g. things you can't do due to permissions) let us know in slack's #build :-)
