### ISSUE TITLE
UK mirrorservice is down, need another source for freemarker.jar

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1867]
https://www.mirrorservice.org/ is unavailable due to ppwer outage

**Comment by andrew-m-leonard** [comment]
Change to this one?
https://downloads.apache.org/freemarker/engine/2.3.30/binaries/apache-freemarker-2.3.30-bin.tar.gz

**Comment by sxa** [comment]
Dup of #1863
