### ISSUE TITLE
Regenerators are no longer getting kicked off automatically

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1876]
**Platform:**
All
**Architecture:**
All 

The [job regenerators](https://ci.adoptopenjdk.net/job/build-scripts/job/utils/) used to be kicked off whenever there was a commit to this repo however that doesn't seem to be the case anymore. I implemented the regenerators off the concept that we have a webhook installed on this repo (after following the instructions at https://www.youtube.com/watch?v=Z3S2gMBUkBo) but that has either been deleted since I created them or disabled.

@karianna @gdams Could you take a look at this repo's webhooks and see if we have a webhook similar to the one below?
<img width="902" alt="Screenshot 2020-06-08 at 11 37 56" src="https://user-images.githubusercontent.com/25231953/84511476-7a123a00-acbe-11ea-8291-8dffc4391985.png">

**Comment by karianna** [comment]
I've re-enabled the hook.

**Comment by karianna** [comment]
Over to @M-Davies to test

**Comment by M-Davies** [comment]
When the next commit goes in, I'll know 🙂

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk/91/console was kicked off by github push. Thanks @karianna
