### ISSUE TITLE
installer_mac issue with file permission issue.

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1879]
jdk11u-mac-x64-openj9
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/622/console

04:47:56  Starting building: build-scripts » release » create_installer_mac #3352
[Pipeline] copyArtifacts
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
05:04:38  Execution error: Unable to get file permissions
[Pipeline] }
looks like something went wrong in overwriting file ?, there is no other error or explanation I can see. Might require cleaning machine if it is not done auto clearing before build.

**Comment by M-Davies** [comment]
Mac looks ok now. Windows is still having issues with this https://github.com/AdoptOpenJDK/openjdk-build/issues/1878#issuecomment-644627546
