### ISSUE TITLE
Update docker file maintainer details to point to AdoptOpenJDK mailing list

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#188]
Our Dockerfiles currently list individuals as maintainers.  To ensure that the burden of maintenance and responding to queries etc doesn't fall on a single person, this e-mail address should be updated to refer to `adoption-discuss@openjdk.java.net`.

**Comment by amczarny** [comment]
should be resolve by https://github.com/AdoptOpenJDK/openjdk-build/pull/285
