### ISSUE TITLE
Missing prereq on xlinux jdk-next

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1882]
**Platform:**
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-hotspot/153/console

Seems we're missing a prereq, either `GLIBC_2.14` or the boot jdk as a whole is missing
```
04:31:11  Detecting boot jdk for: jdk
04:31:11  Found build version: 16
04:31:11  Required boot JDK version: 15
04:31:11  Setting JDK_BOOT_DIR to $JAVA_HOME
04:31:11  Boot jdk directory: :
04:31:11  BOOT JDK: ./build-farm/make-adopt-build-farm.sh: line 87: /bin/java: No such file or directory
04:31:11  JDK IN PATH: openjdk version "1.8.0_252"
04:31:11  JDK IN PATH: OpenJDK Runtime Environment (build 1.8.0_252-b09)
04:31:11  JDK IN PATH: OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
04:31:11  BRANCH:  (For release either BRANCH or TAG should be set)
04:31:11  TAG: 
04:31:11  Downloading GA release of boot JDK version 15...
04:31:12  
04:31:12  gzip: stdin: unexpected end of file
04:31:12  tar: Child returned status 1
04:31:12  tar: Error is not recoverable: exiting now
04:31:12  Downloading GA release of boot JDK version 15 failed.
04:31:12  Attempting to download EA release of boot JDK version 15 ...
04:31:21  /home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-x64-hotspot/jdk-15/bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/jenkins/workspace/build-scripts/jobs/jdk/jdk-linux-x64-hotspot/jdk-15/bin/../lib/libjli.so)
```

**Comment by sxa** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/1865 will have modified the lowest level of GLIBC that we can run on for xLinux but that shouldn't stop anything that needs 2.15 from running

**Comment by sxa** [comment]
Oh hang on - has head not been modified to take that change? It looks like HEAD has build on a CentOS6 box which has an earlier GLIBC - it needs to be built on RHEL7 too

**Comment by M-Davies** [comment]
@sxa Looks like it's using Centos according to our [config](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk16_pipeline_config.groovy#L14-L29)

**Comment by M-Davies** [comment]
Job regenerators are running red this morning too so they won't take any new changes that occured recently. Looks like a script approval issue https://ci.adoptopenjdk.net/job/build-scripts/job/utils/
```
ERROR: script not yet approved for use
```
