### ISSUE TITLE
centos build jdk8 debug

### ISSUE THREAD

**Issue by scikstack** [AdoptOpenJDK/openjdk-build#1886]
centos build jdk8 debug?

> --debug-docker
> debug OpenJDK build script in a docker container. Only valid if -D is selected.

**Comment by karianna** [comment]
No, the --debug-docker allows users to debug the Docker build whilst its executing, it does not create fast or slow debug build.

**Comment by scikstack** [comment]
How to create debug build

**Comment by karianna** [comment]
We don't support that (yet) at AdoptOpenJDK.

**Comment by scikstack** [comment]
Ok
