### ISSUE TITLE
Simplify build script by making the "u menace" a non-issue

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-build#189]
**Problem** 
Currently, the openjdk build forests have "u"s at the end of some forests, but not others. 

We currently forsee a future where "u"s will be added to forests at intervals, and we will need to continue modifying the build scripts each time.

We'll also need to tweak the build scripts whenever a new java version is released, even when there is no difference between building (e.g.) 9 and 10.

**Solution**
This issue proposes to fix that problem by making the user able to build any Java, regardless of "u" suffix or version number, by simply changing the jdk version string argument to the makejdk-any-platform.sh script.

**Solution Breakdown**
This requires us to make the following changes to the adopt build system:

1) Rename the AdoptOpenJDK/openjdk-jdk8u repository to AdoptOpenJDK/openjdk-jdk8 and stop adding "u"s to adopt build repositories in the future.

2) Recode the build scripts in AdoptOpenJDK/openjdk-build to allow the user to pass a "u" in or not, without breaking any functionality of version-string validation (Partly covered in PR https://github.com/AdoptOpenJDK/openjdk-build/pull/187 , but we need to change the adoptopenjdk REPOSITORY to use the OPENJDK_CORE_VERSION instead of OPENJDK_FOREST_NAME).

3) Recode the build scripts in AdoptOpenJDK/openjdk-build to use regular expression validation of the version strings (e.g. jdk[1-9]+[0-9]*u? ) instead of the current validation by comparison with a list of constants.

4) Recode any other version-9-specific stuff to use greater-thans instead of equals. e.g. replace "if VERSION == jdk9" with "if VERSION_INT >= 9".

5) Reach consensus on the variables names for the java version string inside the build scripts.
e.g. if -version=jdk8u
OPENJDK_FOREST_NAME = jdk8u
OPENJDK_CORE_VERSION = jdk8

**Comment by mstoodle** [comment]
Couple of comments.

Your 1. presupposes that no one will ever want to build jdkN as soon as there is a jdkNu? Is that definitely the case?

One comment I had from #187 post merge was to quibble a bit about the name OPENJDK_FOREST_NAME. Maybe we can discuss that as part of this issue as well? I've reproduced a slightly edited version of the comment below:

> I'm going to quibble a bit on the choice of OPENJDK_FOREST_NAME, just because in JDK10 the "forest" has actually been collapsed. I don't think that name is 100% accurate either. I would suggest something like OPENJDK_REPO_NAME or some other accurate description of what that name actually is.

**Comment by adamfarley** [comment]
Hi mstoodle,

-- Your 1. presupposes...
Yes. That is my assumption.

-- One comment I had...
Sure, we can discuss that. We should mention both variable names, if we're getting into this.
e.g. if -version=jdk8u
OPENJDK_FOREST_NAME = jdk8u
OPENJDK_CORE_VERSION = jdk8

**Comment by karianna** [comment]
This is now resolved as all things are pretty much `u` and we've refactored the scripts as well.
