### ISSUE TITLE
jdk(next) OpenJ9 builds fail as built with Hotspot JDK15 BootJDK

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1890]
**Platform:**
All OpenJ9 builds

```
05:20:11  * For target buildtools_interim_langtools_modules_java.compiler.interim__the.BUILD_java.compiler.interim_batch:
05:20:11  warning: unknown enum constant Feature.SEALED_CLASSES
05:20:11  warning: unknown enum constant Feature.SEALED_CLASSES
05:20:11  error: warnings found and -Werror specified
05:20:11  1 error
05:20:11  2 warnings
```

SEALED_CLASSES is not defined in openj9 extensions jdk(next) yet as it has not been merged.
Whereas, Hotspot jdk15 builds already have this, hence as this is used as boot JDK for openj9 the compiler uses the constant in the interim code, hence the error...

Q: Should we use a OpenJ9 boot jdk for OpenJ9 builds...?

**Comment by M-Davies** [comment]
@andrew-m-leonard What timescale are we looking at until OpenJ9 implement the missing classes? Could we wait until they implement rather than adding in a specific use case?

**Comment by andrew-m-leonard** [comment]
I can't say for sure, but I would estimate within a week

**Comment by M-Davies** [comment]
I've got a PR ready so we can put that in for now and then revert when they implement the classes 🙂
