### ISSUE TITLE
Cannot enable JFR on minimal1 VM or zero build

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1897]
**Platform:**
jdk8u-linux-s390x-hotspot

**Architecture:**
{
18:05:34      "ARCHITECTURE": "s390x",
18:05:34      "TARGET_OS": "linux",
18:05:34      "VARIANT": "hotspot",
18:05:34      "JAVA_TO_BUILD": "jdk8u",
18:05:34      "TEST_LIST": [
18:05:34          "sanity.openjdk",
18:05:34          "sanity.system",
18:05:34          "extended.system",
18:05:34          "special.openjdk"
18:05:34      ],
18:05:34      "SCM_REF": "",
18:05:34      "BUILD_ARGS": "",
18:05:34      "NODE_LABEL": "build&&linux&&s390x",
18:05:34      "CONFIGURE_ARGS": "",
18:05:34      "OVERRIDE_FILE_NAME_VERSION": "",
18:05:34      "RELEASE": false,
18:05:34      "PUBLISH_NAME": "",
18:05:34      "ADOPT_BUILD_NUMBER": "",
18:05:34      "ENABLE_TESTS": true,
18:05:34      "CLEAN_WORKSPACE": false
18:05:34  }

Please describe the issue that you are having with our binaries and if possible how to recreate it.
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-hotspot/593/console
`configure: error: cannot enable JFR on minimal1 VM or zero build`

Running on **build-marist-rhel77-s390x-1**

**Comment by karianna** [comment]
Fixed in last night's patch by @gdams
