### ISSUE TITLE
Set up a merge job to keep openjdk-jdk8u dev branch in sync with master

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#19]
This is a task that would be repeated for any new cloned forests we bring in later as well.

**Comment by tellison** [comment]
What's left to do here?  Apart from make the job run clean :-)

**Comment by karianna** [comment]
I haven't been keeping a close eye on this.  So I assume there's a job that merges hg master --> github master and a separate job that brings in the relevant changes to github dev?

**Comment by tellison** [comment]
I think this is stable now.  @karianna are you happy to close the issue?
