### ISSUE TITLE
Missing 'arm' nightly builds in JDK15

### ISSUE THREAD

**Issue by Willsparker** [AdoptOpenJDK/openjdk-build#1900]
There are `aarch64` nightly builds but no `arm` ones for Linux, in https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15/ .

**Comment by M-Davies** [comment]
@Willsparker Does arm require any specific config for jdk15? Or am I good to just copy the [configs over that we have for 14](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk14u_pipeline_config.groovy#L113-L120) (deleting the duplicate arm value at the same time of course)?

**Comment by Willsparker** [comment]
I can't say I know :-) Copy the configs for JDK14 and go from there, I would assume?

**Comment by karianna** [comment]
That will work yes
