### ISSUE TITLE
Pipeline timescales are messed up

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#1902]
Now that we have JDK15 running in the nightlies (and JDK16 as the new head), we have essentially doubled the amount of strain we put on the nightlies to finish on time. As a result, some pipelines are still running at 9am UK time despite initial changes to the [scheduling](https://github.com/AdoptOpenJDK/openjdk-build/issues/1549).

The goal of this issue is to find a suitable time for the [jdk15](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk15.groovy#L33) and [jdk16/head](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk16.groovy) pipelines to run that isn't at the same time as each other (currently they both run at `TZ=UTC\n30 03 * * *`).

@archanaNogriya IIRC you did some work on this initially? Is there a start time that pops into mind that would be ideal for JDK15 to slot into?

**Comment by archanaNogriya** [comment]
@M-Davies ,  This is the time slots we decided and agreed in,
JDK8	JDK11	JDK14	JDK15
0330	2330	2026	1705

I am looking at https://ci.adoptopenjdk.net/view/Build%20and%20Test%20Pipeline%20Calendar/#date=2020-06-19|view=week-view

I think the time has been slightly changed from what e decided for some of the pipelines..
JDK8 - 17:05-2:42 , 
JDK14: 20:26-3:16,  
JDK11: 23:30-5:40
JDK15: 3:30 - 6:14

looks like 8 and 15 has been Switched, which is ok as long as they are overlapping..  
The imp is to set the priority, based on what are the jobs matters for triaging,  8, 11, 14(short term), soon 15(this will replace 14), then java Next builds.

**Comment by M-Davies** [comment]
Thanks @archanaNogriya . Based off further slack conversations, it seems that it's not really a problem as all the builds are still finishing before 8:30
