### ISSUE TITLE
Build ppcle OpenJDK8s (OpenJ9 and Hotspot) with OpenJDK7

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-build#191]
Currently the Adopt ppcle machines only seem to have java 8, accessible through $JDK_BOOT_DIR.

Since the OpenJDK8 build docs strongly advises compiling with OpenJDK7 as the boot JDK, I advise this:

1) Either
     A) Locating the OpenJDK7 on the ppcle build machines.
     or
     B) Putting an OpenJDK7 on the ppcle build machines.

2) Setting up $JDK7_BOOT_DIR and $JDK8_BOOT_DIR on the ppcle machines, as is the case on the other build machines.

3) Change the jenkins build jobs to use these variables, with the OpenJDK8 builds using JDK7 and the OpenJDK9 builds using JDK8.

**Comment by gdams** [comment]
This issue may be of interest https://github.com/AdoptOpenJDK/openjdk-build/issues/18. It covers why we are currently using a JDK8 Boot JDK

**Comment by karianna** [comment]
Resolved.
