### ISSUE TITLE
SigTest code-tools job is failing

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#192]
Currently, the build job https://ci.adoptopenjdk.net/view/Dependencies/job/sigtest/ is failing due to the absence of Java 5, 6, and 9, and hence dependent on https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/46 - this means amending ansible scripts on the infra repo.

Previous to this, the `ubuntu` instances did have the required JDKs.

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/view/Dependencies/job/sigtest/ has been passing for a long time now.
