### ISSUE TITLE
target 'hotspot-server-libs' failed

### ISSUE THREAD

**Issue by archanaNogriya** [AdoptOpenJDK/openjdk-build#1931]
**Platform:**
jdk-linux-ppc64le-hotspot
jdk-aix-ppc64-hotspot
jdk-linux-s390x-hotspot

**Architecture:**

Please describe the issue that you are having with our binaries and if possible how to recreate it.
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-aix-ppc64-hotspot/148/console

`lib/CompileJvm.gmk:149: recipe for target '/ramdisk0/build/workspace/build-scripts/jobs/jdk/jdk-aix-ppc64-hotspot/workspace/build/src/build/aix-ppc64-server-release/hotspot/variant-server/libjvm/objs/interp_masm_ppc_64.o' failed 07:46:33 make/Main.gmk:259: recipe for target 'hotspot-server-libs' failed`

**Comment by sxa** [comment]
Possibly an upstream bug as this did not recur on subsequent builds.
