### ISSUE TITLE
AdoptOpenJDK Security Vulnerabilities

### ISSUE THREAD

**Issue by summved** [AdoptOpenJDK/openjdk-build#1933]
Hello, 
I am using OpenJDK and cant see any security vulnerabilities (Open / Close) associated with AdoptOpenJDK. Can someone please help me and guide me on this? Can someone redirect me with some links where I can see the reported vulnerabilities?

Kind Regards,
Summved

**Comment by karianna** [comment]
adoptopenjdk.net/release_notes.html

**Comment by summved** [comment]
@karianna thanks for your response. I am not sure if I am missing anything on the link but I can't see any security vulnerability or any information associated with it. Can you please help?

**Comment by aahlenst** [comment]
Click on the +/- button next to the titles, e.g. OpenJDK 8u252. There is a title "Security fixes" that lists the JBS issue numbers and CVEs. Enter the numbers in https://bugs.openjdk.java.net/secure/Dashboard.jspa to get details.

**Comment by summved** [comment]
@aahlenst thanks for your help. Really appreciate it. A few more questions
1. Can I also see open security vulnerabilities as well? All I can see is security fixes.
2. I saw a couple of security fixes CVEs, it seems to be relevant to Oracle OpenJDK and AdoptOpenJDK uses non-Oracle OpenJDK. Am I missing anything here? Are they related as they both serve JDK?

**Comment by aahlenst** [comment]
As far as I know, open security vulnerabilities are private and embargoed. We learn of them on the day when the CPU drops (closest Tuesday to the 17th of January, April, July, October).

Oracle JDK is nowadays usually OpenJDK plus Oracle secret sauce. Looking at CVEs alone might not be sufficient to see if OpenJDK is affected if only Oracle is mentioned. If there's a JBS entry, it is safe to assume that it is. AFAIK Oracle has a separate issue tracker for stuff that only affects them. Unfortunately, I'm not an expert here.

**Comment by summved** [comment]
Thank you for the explanation. As per my understanding, the different vendors have their vulnerabilities list published that contains open and closed issues. Most of them are also available on CVE sites. 
If anyone can provide more info on this will be appreciated.

**Comment by sxa** [comment]
Bear in mind that our code is no different in terms of function from the upstream openjdk code, therefore we wouldn't generally have any vulnerabilities specifically against the adoptopenjdk code (and attempting to replicate that information from the upstream project would seem a bit of a waste of effort!) so the upstream openjdk bug system would generally be applicable to ours too (subject to embargoes as @aahlenst mentioned.
