### ISSUE TITLE
create-windows-installer deletes wix/ReleaseDir before upstream build has copied artifacts

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1945]
Evidence from build failure: https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15/job/jdk15-windows-x64-openj9/27/console
```
[Pipeline] copyArtifacts
05:46:38  Copied 0 artifacts from "build-scripts » release » create_installer_windows" build number 5319
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] echo
05:46:38  Execution error: hudson.AbortException: Failed to copy artifacts from build-scripts/release/create_installer_windows with filter: wix/ReleaseDir/*
```
and the fact that #5320 the subsequent create_installer_windows job ran at 05:41 (5 mins before above job tried to copy artifacts from #5319): 
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/5320/console
and that the contents of the wix/ReleaseDir only contains the #5320 output:
```
OpenJDK15-jre_x64_windows_hotspot_2020-07-01-03-32.msi
```

**Comment by andrew-m-leonard** [comment]
So the problem was in the create_installer_windows job configuration:

  | Max # of builds to keep with artifacts 
was set to 1 !!!
So as soon as the next job started the previous artifact was deleted potentially bewfore it's upstream job had copied it...

I have changed it to 10

**Comment by sxa** [comment]
I'm not seeing any Windows failures overnight so let's close this and assume it's fixed until proven otherwise ;-)
