### ISSUE TITLE
git-hg-aarch32-jdk8u mirror Merge Conflict on .hgtags 

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1962]
https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-hg-aarch32-jdk8u/

**Comment by sxa** [comment]
@gdams assuming this is the thing you fixed last week can you close this with a comment clarifying what you did please?

**Comment by karianna** [comment]
I was involved with this.  So the mirroring script was falsely pulling in jdk8u ontop of the aarch32 forest (there was a hard coding left in)
