### ISSUE TITLE
Installer Creation Job Cannot Sign Msi File

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-build#1963]
**Platform:**

Windows x64

**Problem**

Recently, [an installer creation job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_windows/5590/console) failed because "The specified timestamp server either could not be reached or
returned an invalid response."

```
SignTool Error: The specified timestamp server either could not be reached or
returned an invalid response.
SignTool Error: An error occurred while attempting to sign: ReleaseDir\OpenJDK15-jdk_x64_windows_hotspot-15.0.0.30.msi
```

**This is not the bug.**

Connectivity issues with external servers happen, and I'm not raising a bug about that.

The issues that I'd like to solve here are:

1) That if this is encountered again, there should be a retry after a few seconds. Say, 15.

2) That the message before the failure (which seems to erroneously declares the signing a success), should be predicated on the success of the signing. 

```
Successfully signed: ReleaseDir\OpenJDK15-jdk_x64_windows_hotspot-15.0.0.30.msi
```

Since this doesn't appear to be a blocker, I raise this knowing it likely won't see attention until after the July release.

**Comment by aahlenst** [comment]
There's an open PR to solve that issue: https://github.com/AdoptOpenJDK/openjdk-installer/pull/178

**Comment by sxa** [comment]
ARGH! I had retries in for the EXEs and DLLs (https://github.com/AdoptOpenJDK/openjdk-build/pull/1553) but I uess there's a chance it'll fail on the final MSI as well ...

**Comment by gdams** [comment]
I have updated https://github.com/AdoptOpenJDK/openjdk-installer/pull/178 to fix this issue
