### ISSUE TITLE
keep (-k) option is broken

### ISSUE THREAD

**Issue by JamesKingdon** [AdoptOpenJDK/openjdk-build#198]
Attempting to run `./makejdk-any-platform.sh -k -v jdk9` fails with

> Using Docker to build the JDK
> No docker container found so creating 'openjdk_container' 
> Building docker container with docker/jdk9/x86_64/ubuntu  
> "docker build" requires exactly 1 argument.
> See 'docker build --help'.
> 
> Usage:  docker build [OPTIONS] PATH | URL | -
> 
> Build an image from a Dockerfile
> Unable to find image 'openjdk_container:latest' locally
> docker: Error response from daemon: pull access denied for openjdk_container, repository does not exist or may require 'docker login'.
> See 'docker run --help'.

**Comment by karianna** [comment]
Assigning to Mani and George as George has a PR to shift the docker stuff to openjdk-docker and Main needs to sanity check that which would include this.  #195

**Comment by JamesKingdon** [comment]
Looks like it's a first-run only issue. After a successful build without -k, subsequent runs with -k work ok. Possibly ${CONTAINER} isn't set on first run?

**Comment by neomatrix369** [comment]
@JamesKingdon I have had this but not when I used `-k`, do we need this flag really? And what purpose does it serve, maybe its not a functionality needed, unless someone can convince me about it.

@karianna about sanity checking scripts in `openjdk-docker` for a different reason(s) we might need to do that, as I have mentioned at https://github.com/AdoptOpenJDK/openjdk-build/pull/195#pullrequestreview-83690356, https://github.com/AdoptOpenJDK/openjdk-build/pull/195#issuecomment-351880647 and https://github.com/AdoptOpenJDK/openjdk-build/pull/195#issuecomment-351881450.
