### ISSUE TITLE
Mac JDK11 & JDK15 build failure: Timestamp not found

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-build#1987]
**Summary:**
Expected timestamp not found. Not sure what the cause is

**Details**
Error message:

```
[2020-07-23T23:51:31.822Z] /Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/workspace/build/src/build/macosx-x86_64-normal-server-release/support/modules_libs/jdk.jdwp.agent/libdt_socket.dylib: A timestamp was expected but was not found.
```

**Facts**

Has happened at least twice:
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/685/consoleText
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15/job/jdk15-mac-x64-openj9/40/consoleFull

These two instances were both on build-macstadium-macos1014-x64-1

**Comment by M-Davies** [comment]
`A timestamp was expected but was not found` is a [mac signing problem](https://developer.apple.com/forums/thread/8187) by the looks of it.

Regardless, later builds on this machine...
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/686/consoleFull
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/688/consoleFull
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15/job/jdk15-mac-x64-openj9/42/consoleFull
- https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15/job/jdk15-mac-x64-openj9/46/consoleFull
...pass and the pipeline is currently running green
