### ISSUE TITLE
Cannot override --with-jobs=x in makejdk-any-platform.sh -C

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#1990]
Seems to use the detected value regardless which can restrict build performance - it probably shouldn't be ignored if someone explicitly tries to override it.

**Comment by adamfarley** [comment]
Investigating.

**Comment by adamfarley** [comment]
I think this is a good fix for the underlying issue:

https://github.com/AdoptOpenJDK/openjdk-build/pull/2193

**Comment by adamfarley** [comment]
For the record: the underlying issue seems to be in build.sh. User args override general configure args, and platform-specific args override user args.

This seemed suboptimal to me. The user should be able to override whatever they choose. So I tweaked build.sh to give the users' options the highest priority.

**Comment by adamfarley** [comment]
Reopening this until we can prove it works.

**Comment by adamfarley** [comment]
It works: https://ci.adoptopenjdk.net/view/work-in-progress/job/adamf_aarch64_j9/2/console

In that job, I hard-coded --with-jobs=0 into the --configure-args (aka -C) argument for makejdk-any-platform.sh within make-adopt-build-farm.sh. See that the --with-jobs=0 option ends up almost at the very end of the configure command, and overrides the other --with-jobs options.

It also causes immediate failure. That was deliberate, I promise. 

That said, this fix has revealed what appears to be another problem. 

In the job below, I tried passing --with-jobs=0 into a regular build job. I received confirmation that the argument was going into the scripts, and then nothing. Will check to see if there's an issue open for this.

https://ci.adoptopenjdk.net/view/work-in-progress/job/adamf_aarch64_j9/1/consoleFull

**Comment by adamfarley** [comment]
Raised: https://github.com/AdoptOpenJDK/openjdk-build/issues/2194

Closing this issue as resolved.
