### ISSUE TITLE
pipeline_jobs_generator_jdkNNu jobs have hardcoded Jenkins URL

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#1994]
The "pipeline_jobs_generator_jdkNNu" generator jobs currently has a hardcoded Jenkins root URL:
https://github.com/AdoptOpenJDK/openjdk-build/blob/284447f950eac9391331cc56b0dd14a68d56069e/pipelines/build/common/config_regeneration.groovy#L450

**Comment by andrew-m-leonard** [comment]
I think we need an alternative way to set it?
Job parm? or env variable?

**Comment by M-Davies** [comment]
The reason for that is that https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/regeneration/jdk11_regeneration_pipeline.groovy#L50-L60 sets up the enviroment variables for the [config_regeneration](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/config_regeneration.groovy) script. You'll need to change the value that's in the regeneration pipeline file from `null` to whatever the target url is

**Comment by andrew-m-leonard** [comment]
Things like root URLs would be best obtained frmo the environment somehow?
