### ISSUE TITLE
Install cmake for aarch64 builds

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#1999]
cmake needs to be installed on the aarch64 build machines.

"Could not find required tool for CMAKE".
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/435/

**Comment by karianna** [comment]
@sxa More on an infra thing?

**Comment by pshipton** [comment]
Ya, seems a dup of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1462, I'll close this one.
