### ISSUE TITLE
Use folder names that match the archive name (Windows)

### ISSUE THREAD

**Issue by jawnsy** [AdoptOpenJDK/openjdk-build#2000]
## Summary

The AdoptOpenJDK release archives for Windows all use the same folder name, and the folder name does not match the archive name. This means that, if we extract multiple releases into the same directory, then they will conflict with each other. I would therefore suggest using the same folder name inside the archive as the archive is named:

![image](https://user-images.githubusercontent.com/52710/88859118-f6e56e80-d1ad-11ea-9fda-df8b1087a3c7.png)

## Steps to reproduce

Use 7-Zip's "Extract Here" context menu command with multiple different AdoptOpenJDK builds. This will result in conflicting directories, as several archives contain the same "jdk-11.0.8+10" folder inside.

*Workaround*: You can avoid this problem by extracting to a directory named for the archive, but then you get multiple nested folders (e.g. OpenJDK11U-jdk_x64_windows_hotspot_11.0.8_10\jdk-11.0.8+10).

## Triaging info

Java version:

What is your operating system and platform?

How did you install Java?

Did it work before?

Did you test with other Java versions?

**Comment by karianna** [comment]
@douph1 Is this a build or installer issue?

**Comment by M-Davies** [comment]
Extremely similar issue to https://github.com/AdoptOpenJDK/openjdk-build/issues/1066

**Comment by aahlenst** [comment]
This is a build issue. It concerns the ZIP files, not the MSIs.

**Comment by aahlenst** [comment]
I close this one because it's a duplicate.
