### ISSUE TITLE
Add flag to build pipelines to make installer step optional like is done for tests

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2011]
Currently it is not possible to run a build without invoking the `create_installer_*` jobs. For tests we have a flag to indicate whether we want to run them, but not for the installer job. This request is to turn the invocation of the installer into an optional flag in the top level `openjdkxx_pipeline` jobs.

**Comment by M-Davies** [comment]
I can probably implement this before I leave next week
