### ISSUE TITLE
jdk8u-linux-arm-hotspot can't print out the java version

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#2014]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-hotspot has been failing since the 31st July, starting with [this](https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-hotspot/342/) build. The error message has been the same since, with the build completing successfully but suffering a crash when trying to run 
https://github.com/AdoptOpenJDK/openjdk-build/blob/16a43ec831090cc76594317fb7d585a099e21186/sbin/build.sh#L533
at the end of the build.
```
19:48:15  =JAVA VERSION OUTPUT=
19:48:15  Error: dl failure on line 893
19:48:15  Error: failed /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-arm-hotspot/workspace/build/src/build/linux-aarch32-normal-client-release/images/j2sdk-image/jre/lib/aarch32/client/libjvm.so, because /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-arm-hotspot/workspace/build/src/build/linux-aarch32-normal-client-release/images/j2sdk-image/jre/lib/aarch32/client/libjvm.so: undefined symbol: __atomic_load_8
```
NOTE: There's only one arm build machine online at the moment (`build-scaleway-ubuntu1604-armv7-1`)

**Comment by gdams** [comment]
so far I've managed to run the command using:

```bash
$ LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.1.0 java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
OpenJDK Client VM (build 25.252-b09, mixed mode)
```

**Comment by gdams** [comment]
@sxa any idea what might be going on here? Presumably, we need to pass that path (`/usr/lib/arm-linux-gnueabihf/libatomic.so.1.1.0`) to the build somehow so it is linked?

**Comment by gkoudjou** [comment]
Hello,

I want to report that i encounter the same error on the last ARM distribution of the JDK.

```
yyyy@xxxx~/jdk8u275-b01/bin$ java -version
java: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

```

The fix test build mentionned here https://github.com/AdoptOpenJDK/openjdk-build/pull/2022 is no more available for review.

Thanks

**Comment by aahlenst** [comment]
@gkoudjou Install libatomic and you should be good. If that does not help, open a new ticket in https://github.com/AdoptOpenJDK/openjdk-support/issues.

**Comment by gkoudjou** [comment]
Hi @aahlenst ,

I'm on an armv7 off-internet device (os based on Yocto). Do you know where i can found this library or maybe you have it somewhere and could share it ?

Thanks

**Comment by aahlenst** [comment]
libatomic is a runtime library and part of GCC.
