### ISSUE TITLE
Provide ability to disable automated runs of nightly builds

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2016]
For other parties (such as those interested in alternate builds such as OpenJ9, Corretto, or SAP) or any others we may add in the future) attempting to run the adoptopenjdk scripts we should provide an option not to automatically schedule the nightly runs so that no attempt is made to automatically kick off all platforms defined the in the [jdkXX.groovy](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk11u.groovy) files from the build repository

For this to work, I feel the best option would be to provide an checkbox on the top level pipeline generation job to disable the timer on the generated openjdkXX-pipeline jobs with the default configuration (which a user could override, but it would get replaced on the next auto-generation cycle)

This would also allow anyone who wants to set up an alternate timer to do so by creating another job that invokes the main openjdkXX-pipeline jobs with the set of `targetConfigurations` that their business desires, while still taking advantage of the auto-regeneration to obtain updates from the AdoptOpenJDK/openjdk-build repository

**Comment by smlambert** [comment]
This relates to https://github.com/AdoptOpenJDK/openjdk-build/issues/1116 in that there are more requirements related to making the scheduling and what tests get launched more flexible.

**Comment by sxa** [comment]
Yeah this is just a fairly crude global on/off switch regarding starting the nightly pipelines to meet a separate requirement but I'm totally supportive of the stuff in that other issue too of course especially if Sophia is able to work on the implementation of it :-)
