### ISSUE TITLE
Add full version info (with build number) to RELEASE file

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/openjdk-build#2034]
Hello,

It turns out that `release` file at the root of the installation lacks build number info.

Currently we have only `Major`.`Minor`.`Security`, and not `+Build`, although `+Build` can be important (https://github.com/AdoptOpenJDK/openjdk-support/issues/163).

For instance, if I want to determine full release version, like 11.0.8+10, I currently have to query windows registry to get that '+10' (in case of windows) or run `java -version` and parse its output (which is kinda slow if I'm going multiple installations) in case installation was extracted from ZIP, and not MSI.

I suggest adding something like `SEMVER = "11.0.8+10"` to `release` file so It will be possible to get all version info from there.

Additionally, it would be great to have something about `hotspot`/`openj9` (and `openj9` heap size) in `release` as well without having to dig through the filesystem (https://github.com/AdoptOpenJDK/openjdk-support/issues/153).

**Comment by austin0** [comment]
The contents of the `release` file is almost entirely decided within the OpenJDK being built, this is why jdk8u/11u+ differ greatly in their contents, so adding new values might not be as clean as initially expected.

Currently `--with-vendor-version-string` / `IMPLEMENTOR_VERSION` is set to always be `AdoptOpenJDK` and could be easily changed to contain the full version+build number. However, this parameter only exists for jdk9+ so jdk8u would still need a separate patch.

Solution following this is to add a new section to the build scripts that adds values to the release file, this way https://github.com/AdoptOpenJDK/openjdk-support/issues/153, https://github.com/AdoptOpenJDK/openjdk-support/issues/163, and any future requests could be accommodated. Tagging @sxa on if this is a good/bad idea and for any info of why `--with-vendor-version-string` is set to a static `AdoptOpenJDK`.

**Comment by austin0** [comment]
Closing as https://github.com/AdoptOpenJDK/openjdk-build/pull/2049 has been merged.
