### ISSUE TITLE
openjdk8-openj9 java -version output incorrect

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#204]
java -version on openjdk8-openj9 is missing the 'based on' string:

java -version
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2018_01_12_13_02-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180112_45 (JIT enabled, AOT enabled)
OpenJ9   - e885f93
OMR      - 59522c8
OpenJDK  - 00e69f9 based on )

**Comment by andrew-m-leonard** [comment]
Is the Adopt clone of openj9-jdk8 fetching the tags?

**Comment by karianna** [comment]
See #93 as well, not sure if we're fetching tags and parsing them correctly.

**Comment by neomatrix369** [comment]
@karianna This might be lightly related to issue https://github.com/AdoptOpenJDK/openjdk-build/issues/98

**Comment by neomatrix369** [comment]
@judovana (Jiri Vanek) has kindly shared his scripts to get the tags out of a mercurial repo, which I have just run against JDK9 (older repo) and get these results:

I ran:
```
$ java MercurialTracker jdk9

```
and got 

```
jdk.9.153-8
  jdk9 2443:8d22611ffb65 tip
  langtools 3887:b670e95106f5 tip
  jdk 16477:f2325d80b37c tip
  jaxws 747:34af95c7dbff tip
  hotspot 12482:fc7e94cb7485 tip
  jaxp 1063:0908877116d1 tip
  nashorn 1865:a84b49cfee63 tip
  corba 826:d66f97a610a6 tip
```
Then I ran:
```
$ java MercurialTracker jdk9

```
and got 

```
java MercurialTracker -verbose jdk9
jdk-9+153: 2442:816a6d03a7c4
-----------------
jdk-9+153 2442:816a6d03a7c4 8162750
 * tip 2443:8d22611ffb65 Added tag jdk-9+153 for changeset 816a6d03a7c4
-----------------
most fresh tag: jdk-9+153
tip lines are (should be 1!): 
  jdk-9+153 2442:816a6d03a7c4 8162750
          jdk9 jdk9 jdk-9+153 1 2443:8d22611ffb65 2017-01-19_22:31:06_+0000 tip
Found 7
Trying langtools
jdk-9+153: 3886:03f48cd283f5
-----------------
jdk-9+153 3886:03f48cd283f5 8172262
 * tip 3887:b670e95106f5 Added tag jdk-9+153 for changeset 03f48cd283f5
-----------------
most fresh tag: jdk-9+153
tip lines are (should be 1!): 
  jdk-9+153 3886:03f48cd283f5 8172262
          jdk9 langtools jdk-9+153 1 3887:b670e95106f5 2017-01-19_22:31:09_+0000 tip
Trying jdk
jdk-9+153: 16476:1c4411322327
-----------------
jdk-9+153 16476:1c4411322327 8172957
 * tip 16477:f2325d80b37c Added tag jdk-9+153 for changeset 1c4411322327
-----------------
most fresh tag: jdk-9+153
tip lines are (should be 1!): 
  jdk-9+153 16476:1c4411322327 8172957
          jdk9 jdk jdk-9+153 1 16477:f2325d80b37c 2017-01-19_22:31:08_+0000 tip
Trying jaxws
jdk-9+153: 746:7a532a9a2271
-----------------
jdk-9+153 746:7a532a9a2271 Merge
 * tip 747:34af95c7dbff Added tag jdk-9+153 for changeset 7a532a9a2271
-----------------
most fresh tag: jdk-9+153
tip lines are (should be 1!): 
  jdk-9+153 746:7a532a9a2271 Merge
          jdk9 jaxws jdk-9+153 1 747:34af95c7dbff 2017-01-19_22:31:08_+0000 tip
Trying hotspot
jdk-9+153: 12481:217ba81b9a4c
-----------------
jdk-9+153 12481:217ba81b9a4c Added tag jdk-9+152 for changeset 31f1d26c60df
 * tip 12482:fc7e94cb7485 Added tag jdk-9+153 for changeset 217ba81b9a4c
-----------------
most fresh tag: jdk-9+153
tip lines are (should be 1!): 
  jdk-9+153 12481:217ba81b9a4c Added tag jdk-9+152 for changeset 31f1d26c60df
          jdk9 hotspot jdk-9+153 1 12482:fc7e94cb7485 2017-01-19_22:31:07_+0000 tip
Trying jaxp
jdk-9+153: 1062:1384504d2cd0
-----------------
jdk-9+153 1062:1384504d2cd0 8169631
 * tip 1063:0908877116d1 Added tag jdk-9+153 for changeset 1384504d2cd0
-----------------
most fresh tag: jdk-9+153
tip lines are (should be 1!): 
  jdk-9+153 1062:1384504d2cd0 8169631
          jdk9 jaxp jdk-9+153 1 1063:0908877116d1 2017-01-19_22:31:08_+0000 tip
Trying nashorn
jdk-9+153: 1864:19aaaf2d02b7
-----------------
jdk-9+153 1864:19aaaf2d02b7 Merge
 * tip 1865:a84b49cfee63 Added tag jdk-9+153 for changeset 19aaaf2d02b7
-----------------
most fresh tag: jdk-9+153
tip lines are (should be 1!): 
  jdk-9+153 1864:19aaaf2d02b7 Merge
          jdk9 nashorn jdk-9+153 1 1865:a84b49cfee63 2017-01-19_22:31:10_+0000 tip
Trying corba
jdk-9+153: 825:68a8e8658511
-----------------
jdk-9+153 825:68a8e8658511 Added tag jdk-9+152 for changeset ff8cb43c07c0
 * tip 826:d66f97a610a6 Added tag jdk-9+153 for changeset 68a8e8658511
-----------------
most fresh tag: jdk-9+153
tip lines are (should be 1!): 
  jdk-9+153 825:68a8e8658511 Added tag jdk-9+152 for changeset ff8cb43c07c0
          jdk9 corba jdk-9+153 1 826:d66f97a610a6 2017-01-19_22:31:06_+0000 tip
**************
1: (jdk9)
          jdk9 jdk9 jdk-9+153 1 2443:8d22611ffb65 2017-01-19_22:31:06_+0000 tip
1: (langtools)
          jdk9 langtools jdk-9+153 1 3887:b670e95106f5 2017-01-19_22:31:09_+0000 tip
1: (jdk)
          jdk9 jdk jdk-9+153 1 16477:f2325d80b37c 2017-01-19_22:31:08_+0000 tip
1: (jaxws)
          jdk9 jaxws jdk-9+153 1 747:34af95c7dbff 2017-01-19_22:31:08_+0000 tip
1: (hotspot)
          jdk9 hotspot jdk-9+153 1 12482:fc7e94cb7485 2017-01-19_22:31:07_+0000 tip
1: (jaxp)
          jdk9 jaxp jdk-9+153 1 1063:0908877116d1 2017-01-19_22:31:08_+0000 tip
1: (nashorn)
          jdk9 nashorn jdk-9+153 1 1865:a84b49cfee63 2017-01-19_22:31:10_+0000 tip
1: (corba)
          jdk9 corba jdk-9+153 1 826:d66f97a610a6 2017-01-19_22:31:06_+0000 tip
------------
jdk-9+153: 1
------------
jdk.9.153-8
  jdk9 2443:8d22611ffb65 tip
  langtools 3887:b670e95106f5 tip
  jdk 16477:f2325d80b37c tip
  jaxws 747:34af95c7dbff tip
  hotspot 12482:fc7e94cb7485 tip
  jaxp 1063:0908877116d1 tip
  nashorn 1865:a84b49cfee63 tip
  corba 826:d66f97a610a6 tip
```

**Comment by neomatrix369** [comment]
Are we interested in `jdk.9.153-8` in the above and the SHA of the tip? In the case of OpenJDK its hard to have one SHA as OpenJDK is made of up multiple repos and each on has its own SHA

**Comment by neomatrix369** [comment]
I also ran these:

```
○ $ java MercurialTracker -tipTagsOnly jdk8 
jdk8u162-b00
```
and

```
○ $ java MercurialTracker -tipTagsOnly jdk9
jdk-9+153
```

**Comment by judovana** [comment]
"re we interested in jdk.9.153-8 in the above and the SHA of the tip? In the case of OpenJDK its hard to have one SHA as OpenJDK is made of up multiple repos and each on has its own SHA.
But I did notice jdk9 2443:8d22611ffb65 tip, is this the SHA to the JDK9 repo, can we use this?"

In case of forest, you *have to* store the SHAs of all repos.  If you run that tracker of mine with  -outputDir=somePath, then you will recieve files, each named as  tag+changesets containing the list of SHAs of individual repos.

**Comment by judovana** [comment]
"which looks like what we would be initially interested in."

If we decide to use this tracker, I will move the code to github.
Also It will need to rework a bit for forests using specific tagging. Eg icedtea or aarch64 are inheriting upstream tags, but also add theirs own  tags for theirs own releaser. The tracker is dealing reasonably well with it, but current solution have bugs and limits. Still, for true multi-project infrastructure there is few steps to do...

**Comment by andrew-m-leonard** [comment]
Looks like there's a bit of confusion here, let me explain.

- Building OpenJDK for Eclipse OpenJ9 does not involve any mercurial repos. The following github repos are involved during the clone/build process:
    ==> https://github.com/ibmruntimes/openj9-openjdk-jdk8     "OpenJDK8 extensions for OpenJ9" this includes a "copy" of OpenJDK8
    ==> https://github.com/eclipse/openj9   "Eclipse OpenJ9" source repo
    ==> https://github.com/eclipse/openj9-omr  "Eclipse OpenJ9 OMR" source repo

- During an OpenJDK for OpenJ9 build the "version" is determined by a git query for the latest release "tag". It is this that is failing. You can check after running the "bash ./configure.sh" if the version has been correctly determined by looking at the following generated file:
   ==> build/linux-x86_64-normal-server-release/custom-spec.gmk
and looking for the lines:
```
    # for constructing version output
    OPENJDK_SHA             := 84153c75
    OPENJDK_TAG             := jdk8u152-b16
```
You will find in your failing builds that the OPENJDK_TAG is not set.

- Looking at the AdoptOpenJDK build script https://github.com/AdoptOpenJDK/openjdk-build/blob/master/makejdk.sh, I can see the reason it is failing, because it defaults to a git "shallow clone", thus when it clones the github repo it uses the command:
```
    git clone --depth=1 git@github.com:ibmruntimes/openj9-openjdk-jdk8.git
```
**The --depth=1 will mean no commit history nor the release "tag" will be cloned, hence no release tag version can be determined.**

**Comment by judovana** [comment]
This is one more confirmation of two of my suggestions:
- separate obtaining of sources form build. Really store sources snapshot  and then all builders can pull it.
- generate final (expanded) make call and keep them as build artifact

**Comment by neomatrix369** [comment]
@andrew-m-leonard good find :+1: 

Although we chose to use shallow git clone to speed up the cloning process. Back to the drawing board for us on that one. 

Any suggestions?

**Comment by neomatrix369** [comment]
@judovana I have already included the code for the mercurial tracker with PR #208, we can update that script once its makes into the repo

**Comment by neomatrix369** [comment]
@judovana Quoting on https://github.com/AdoptOpenJDK/openjdk-build/issues/204#issuecomment-358962130, can you show us some example scripts of maybe guide us using our current build scripts to show how we can achieve this?

**Comment by judovana** [comment]
Curent  build jdk scripts are doing simply to much. To get rid of pull will simplify a lot. However to work with sources as I keep suggesting needs storage (for source snapshots).  I'm working on it hard, but am constantly stuck on HW.  Once the HW is  on public netwok, it should be easy. The SW is done. Then I will contribute to build scripts  to work with this storage. 
The generated makefile should be easy thing, however before I posted that comment I looked into build scripts and did not ofund the palce where to put it.  I will sum up and publish  our build scritps to bring up some inspiration. 
Sorry for keeping jabbering and no work done.  But I rpomiss it will turn 180° once strorage for source snapshots is done.

**Comment by judovana** [comment]
Here are the prommised scritps:
https://github.com/judovana/OpenJdkBuilder
Plese feel free to email me for questions.

**Comment by mbvreddy** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/22 fix this issue.

java -version of latest overnight build looks like

openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-jenkins_2018_01_26_13_02-b00)
Eclipse OpenJ9 VM (build 2.9, JRE 1.8.0 Linux amd64-64 Compressed References 20180126_55 (JIT enabled, AOT enabled)
OpenJ9   - 5d59436
OMR      - ec2c3bf
OpenJDK  - ac9998c based on jdk8u152-b16)

**Comment by sxa555** [comment]
As far as I know everyone is happy with the current output, therefore closing
