### ISSUE TITLE
jdkXX_regeneration_pipeline does not support Jenkins with no anonymous read

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#2044]
I am trying to run the regeneration script on my Jenkins instance but the job fails with a 403 because I do not have anonymous read enabled.

This is the call that is failing
https://github.com/AdoptOpenJDK/openjdk-build/blob/9ec93a82080c41fd6a3a8eba3ef28cfdd20ad32b/pipelines/build/common/config_regeneration.groovy#L311
more specifically, this line
https://github.com/AdoptOpenJDK/openjdk-build/blob/9ec93a82080c41fd6a3a8eba3ef28cfdd20ad32b/pipelines/build/common/config_regeneration.groovy#L283

```
[Pipeline] stage
[Pipeline] { (Check jdk8u pipeline status)
[Pipeline] echo
00:00:05.235  [ERROR] Failure on jenkins api connection or parsing.
00:00:05.235  Error: java.io.IOException: Server returned HTTP response code: 403 for URL: https://****.com/job/build-scripts/api/json?tree=jobs[name]&pretty=true&depth1
```
In the meantime I just skipped this check and it passed, but I'm guessing the solution will be to add an option for authentication.

**Comment by M-Davies** [comment]
> guessing the solution will be to add an option for authentication

Thankfully, there is a way to add username and password infomation to both [Jenkins](https://www.jenkins.io/doc/book/system-administration/authenticating-scripted-clients/) and [Groovy](https://stackoverflow.com/a/496707). I'll have a look at both and see which is the more appropriate to use
