### ISSUE TITLE
Pipeline generation - allow user provided configurations

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#2045]
I would like the ability to use the generation jobs but provide my own config files so I only generate the jobs I am interested in with the configurations I desire. I could fork and modify my own stuff but then I'd have to ensure I keep in sync rather than just getting the updates for free.

https://github.com/AdoptOpenJDK/openjdk-build/tree/master/pipelines/jobs/configurations

**Comment by M-Davies** [comment]
I'd could probably implement both scenarios into the regeneration jobs:
1. A user only wants regenerate certain "default" configurations from this repository. Adding an excludes list to the regen job in a similar manner to the [dockerExcludes](https://github.com/AdoptOpenJDK/openjdk-build/pull/1998) param will allow this hypothetical user to only build the platforms they want to.
2. ~A user wants to use their own configurations that are in a forked or different repository and location than the default Adopt configs~ This has already been achieved with the merging of https://github.com/AdoptOpenJDK/openjdk-build/pull/1995 and the addition of the `JOB_ROOT` and `JENKINS_BUILD_ROOT` params.
