### ISSUE TITLE
Boot JDK guessing is not smart enough

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-build#2054]
According to our README, it should be enough to type `./makejdk-any-platform.sh jdk15u` to build a JDK, especially after having provisioned a machine with out playbooks. But it seldom is: 

https://github.com/AdoptOpenJDK/openjdk-build/blob/e9d3ebfc4c912bafa14ba47cad44c59d09f208e3/sbin/common/common.sh#L157-L182

This guesses the bood JDK by using whatever `java` points to. This is seldom the right choice and causes weird errors that are hard to diagnose for newcomers like

```
checking for cmd.exe... /cygdrive/c/Windows/system32/cmd.exe
checking build system type... Invalid configuration `Files/Java/jdk8u265-b01': machine `Files/Java/jdk8u265' not recognized
configure: error: /usr/bin/bash /cygdrive/c/Users/Administrator/openjdk-build/workspace/build/src/make/autoconf/build-aux/config.sub Files/Java/jdk8u265-b01 failed
configure exiting with result code 1
Error: No configurations found for /cygdrive/c/Users/Administrator/openjdk-build/workspace/build/src.
Please run 'bash configure' to create a configuration.
/cygdrive/c/Users/Administrator/openjdk-build/workspace/build/src/make/Init.gmk:124: *** Cannot continue.  Stop.
```

We know in almost every case (except Dragonwell 8) what version the boot JDK should have. So we should test if the boot JDK has the right version and fail the build (overriding that check should still be possible for experiments). Furthermore, we should investigate what else we could do, for example downloading a boot JDK. There is some code that should do that:

https://github.com/AdoptOpenJDK/openjdk-build/blob/e9d3ebfc4c912bafa14ba47cad44c59d09f208e3/build-farm/platform-specific-configurations/windows.sh#L29

Haven't investigated yet why that isn't triggered.

**Comment by sxa** [comment]
To clarify why it isn't triggered in your situation, the code you reference in `platform-specific-configurations` is only triggered via our jenkins pipelines which run `build-farm/make-adopt-build-farm.sh` which ultimately runs makejdk-any-platform.sh, but not when that is run in isolation
