### ISSUE TITLE
Command "run tests" has poor usability

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-build#2055]
If someone types "run test", PR comments should be added that provide diagnostics.

* If the person is not whitelisted to do "run tests", the user should be informed that they aren't allowed to run the command and be instructed how to fix this.
* If the request was queued, a link to the build should be provided.
* If the build was finished, a summary of the results should be provided.

**Comment by aahlenst** [comment]
Related: #2053

**Comment by M-Davies** [comment]
> If the person is not whitelisted to do "run tests", the user should be informed that they aren't allowed to run the command and be instructed how to fix this.

Unfortunately, this currently isn't possible with the plugin that we're using. It looks like there's a pull request in to attempt to make this change in the plugin's repo but even then I'm not confident much will happen seeing as it's 3 years old https://github.com/jenkinsci/ghprb-plugin/pull/495. We could try and do some hacky stuff with the bot but I don't currently have access to the code to run that (@johnoliver do you have any idea how @adoptopenjdk-github-bot works?)

> If the request was queued, a link to the build should be provided.

The plugin provides support for that by default. By setting the `Commit Status Build Triggered` and `Commit Status Build Started` configure settings in the pr-tester, we can customise the status that is displayed on Github. See below image for when a job is in the queue:
<img width="930" alt="Screenshot 2020-09-08 at 11 06 13" src="https://user-images.githubusercontent.com/25231953/92468111-8da04480-f1ca-11ea-8df2-dc48da7a42b9.png">
and this image for when the job is out of the queue and currently running (this may be defunct if I can get the [PR tester running concurrently](https://github.com/AdoptOpenJDK/openjdk-build/issues/2053) but it'll do for now)
<img width="933" alt="Screenshot 2020-09-08 at 12 13 11" src="https://user-images.githubusercontent.com/25231953/92469475-c5a88700-f1cc-11ea-87de-9561e5b4cdcc.png">


> If the build was finished, a summary of the results should be provided.

Again, the plugin can help us here. By setting the `Build Result Message` configure setting in the tester, we can get the adopt bot to comment when the build succeeds, fails or errors
<img width="997" alt="Screenshot 2020-09-08 at 12 15 01" src="https://user-images.githubusercontent.com/25231953/92469574-f092db00-f1cc-11ea-8657-47ac70f4812b.png">


I'll add documentation summarising all of this as part of https://github.com/AdoptOpenJDK/openjdk-build/issues/2056

**Comment by M-Davies** [comment]
This has been applied to both the [pipeline tester](https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-pr-tester/) but not the [groovy compiler](https://ci.adoptopenjdk.net/job/build-scripts-pr-tester/job/openjdk-build-compile-groovy/) as that takes about 30 seconds to run at max and I don't have the perms to modify it anyway
