### ISSUE TITLE
github repository naming

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#206]
I was just looking at our github area and coming to the adoptopenjdk github area as a "newbie" looks (at least to me) like it would be quite confusing. We have a number of `-releases`repositories with often inconsistent descriptions, and to me descriptions like `AdoptOpenJDK Build community location for OpenJDK releases` doesn't quite make it clear that these are fundamentally just pointers for the API, and not either the source code or the binaries themselves.

Would anyone object if I changed the description of the repositories to say, for example, `AdoptOpenJDK binary releases for OpenJDK 8/HotSpot` and similar? Likewise for the `-nightly` ones.

Also the source repositories have inconsistent descriptions and list them as "mirrors" but don't specify that they are source mirrors so I'd like to update that too. If someone is coming to our github repository for whatever reason I'd expect they'd be mostly interested in the source / build scripts etc. so we should make it as clear as possible which are the "interesting" ones from a developer perspective.

Thoughts / Strong feelings either way? Obviously I could have changed them all in the time it's taken to raise this issue, but this lets me keep a record of what it was before and opens it for discussion ;-)

| Repository  | Description |
| ------------- | ------------- |
| openjdk8-releases  | AdoptOpenJDK Build community location for OpenJDK releases |
| openjdk8-openj9-releases | <blank> |
| openjdk9-releases |  AdoptOpenJDK Build community location for OpenJDK releases  |
| openjdk9-openj9-releases | Eclipse Openj9 release repo |
| openjdk10-releases | <blank> |
| openjdk8-nightly |  AdoptOpenJDK Build Community location of OpenJDK Nightly builds  |
| openjdk8-openj9-nightly | <blank> |
| openjdk9-nightly |  AdoptOpenJDK Build Community location of OpenJDK Nightly builds  |
| openjdk9-openj9-nightly |  Eclipse openj9 nightly repo  |
| openjdk10-nightly | <blank> |
| openjdk-jdk8u |  OpenJDK jdk8u mirror on master, with selective patches on branch 'dev' |
| openjdk-jdk9 |  OpenJDK jdk9 mirror |
| openjdk-jdk10 | JDK10 mirror |

**Comment by gdams** [comment]
SGTM - We should aim to be consistent across all the repos

**Comment by sxa555** [comment]
I'll leave it a couple of days before changing anything to ensure that anyone who wants to can have a say (particularly @karianna)

**Comment by karianna** [comment]
@sxa555 I'm happy with those suggested changes.  Beats what I had put down there originally.

**Comment by sxa555** [comment]
scription |
| ------------- | ------------- |
| openjdk8-releases  |  AdoptOpenJDK main binary releases for OpenJDK 8 with HotSpot  |
| openjdk8-openj9-releases |  AdoptOpenJDK main binary releases for OpenJDK 8 with Eclipse OpenJ9  |
| openjdk9-releases | AdoptOpenJDK main binary releases for OpenJDK 9 with HotSpot |
| openjdk9-openj9-releases |  AdoptOpenJDK main binary releases for OpenJDK 9 with Eclipse OpenJ9  |
| openjdk10-releases | AdoptOpenJDK main binary releases for OpenJDK 10 with HotSpot |
| openjdk8-nightly | AdoptOpenJDK nightly binary releases for OpenJDK 8 with HotSpot  |
| openjdk8-openj9-nightly | AdoptOpenJDK nightly binary releases for OpenJDK 9 with Eclipse OpenJ9  |
| openjdk9-nightly | AdoptOpenJDK nightly binary releases for OpenJDK 9 with HotSpot |
| openjdk9-openj9-nightly |  AdoptOpenJDK nightly binary releases for OpenJDK 9 with Eclipse OpenJ9   |
| openjdk10-nightly |  AdoptOpenJDK nightly binary releases for OpenJDK 10 with HotSpot  |
| openjdk-jdk8u |  OpenJDK jdk8u source mirror on master, with selective patches on branch 'dev' |
| openjdk-jdk9 |   OpenJDK jdk9 source mirror  |
