### ISSUE TITLE
jdk8u build fails JVM_IsUseContainerSupport undefined

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2065]
**Platform:**
pLinux
zLinux
xLinux
Solaris

https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-hotspot/671/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-hotspot/685/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/736/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-x64-hotspot/441/consoleFull

```
18:22:01  /home/jenkins/workspace/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-hotspot/workspace/build/src/build/linux-s390x-normal-zero-release/jdk/objs/libjava/Metrics.o: In function `Java_jdk_internal_platform_cgroupv1_Metrics_isUseContainerSupport':
18:22:01  Metrics.c:(.text+0x12): undefined reference to `JVM_IsUseContainerSupport'
18:22:01  collect2: error: ld returned 1 exit status
18:22:01  lib/CoreLibraries.gmk:213: recipe for target '/home/jenkins/workspace/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-hotspot/workspace/build/src/build/linux-s390x-normal-zero-release/jdk/lib/s390x/libjava.so' failed
18:22:01  gmake[2]: *** [/home/jenkins/workspace/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-hotspot/workspace/build/src/build/linux-s390x-normal-zero-release/jdk/lib/s390x/libjava.so] Error 1
18:22:01  gmake[1]: *** [libs-only] Error 2
18:22:01  BuildJdk.gmk:70: recipe for target 'libs-only' failed
18:22:01  /home/jenkins/workspace/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-s390x-hotspot/workspace/build/src//make/Main.gmk:116: recipe for target 'jdk-only' failed
18:22:01  make: *** [jdk-only] Error 2
```

**Comment by andrew-m-leonard** [comment]
I am suspecting this is caused by the hg-git mirror for jdk8u having a merge conflict on hotspot:
https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-hg-jdk8u/855/console

**Comment by andrew-m-leonard** [comment]
Merge conflict fix has resolved the problem

**Comment by adamfarley** [comment]
@andrew-m-leonard - Please link the merge conflict fix. A Solaris build last night failed with the error message below, and it seems an unlikely coincidence. 

```
18:40:42  Undefined			first referenced
18:40:42   symbol  			    in file
18:40:42  Java_jdk_internal_platform_cgroupv1_Metrics_isUseContainerSupport /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/jdk/make/mapfiles/libjava/mapfile-vers
18:40:42  ld: fatal: symbol referencing errors. No output written to /export/home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-solaris-x64-hotspot/workspace/build/src/build/solaris-x86_64-normal-server-release/jdk/lib/amd64/libjava.so
```

**Comment by jerboaa** [comment]
See https://bugs.openjdk.java.net/browse/JDK-8250627 I'll try to have a look.

**Comment by jerboaa** [comment]
Sorry, I've looked into this and it seems a solaris only problem where `Java_jdk_internal_platform_cgroupv1_Metrics_isUseContainerSupport` is mentioned in the map file, but not built. The way to work-around this issue seems to be to trick the build machinery to not include it in the mapfile for solaris (or get the compiler to ignore this issue). It's low priority for me. If somebody gets a chance to fix it before me, feel free to.

**Comment by gdams** [comment]
@jerboaa anything I can do to help get a fix for this?

**Comment by jerboaa** [comment]
@gdams Feel free to hack up a patch for it. It'll likely entail generating a map file for solaris at build time which doesn't include `Java_jdk_internal_platform_cgroupv1_Metrics_isUseContainerSupport`.

**Comment by andrew-m-leonard** [comment]
I briefly looked at this last week, and it seems rather more tricky in jdk8, as the mapfiles are pretty static, whereas jdk11+ I think they are generated.
So as you say, it might mean putting in some thing "bespoke", although I suspect the community will want something a bit cleaner

**Comment by andrew-m-leonard** [comment]
Will be fixed once the following gets to jdk8u : https://bugs.openjdk.java.net/browse/JDK-8255003

**Comment by M-Davies** [comment]
Pipelines are not hitting this anymore and that bug is resolved. Closing...
