### ISSUE TITLE
ansible: ensure that all mac machines have the correct default keychain set

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-build#2071]
Due to the error message below, I suspect this may be connected to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1382. 

@Willsparker - Your opinion on this, please.

Example:
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_mac/4634/console

Error message:
```
+ bash pkgbuild/create-installer-mac.sh
Processing: /Users/jenkins/workspace/build-scripts/release/create_installer_mac/workspace/target/OpenJDK15U-jdk_x64_mac_openj9_macosXL_2020-09-09-20-27.tar.gz
running ./pkgbuild.sh --sign Developer ID Installer: London Jamocha Community CIC --major_version 15 --full_version 15+36-202009092033 --input_directory jdk-15+36 --output_directory /Users/jenkins/workspace/build-scripts/release/create_installer_mac/workspace/target/OpenJDK15U-jdk_x64_mac_openj9_macosXL_2020-09-09-20-27.pkg
error: The specified item could not be found in the keychain.
```

**Comment by Willsparker** [comment]
Well, it's running on the mac that was having the previous issues. I'll try running it manually

**Comment by Willsparker** [comment]
I don't think this is specific to the change I made yesterday, otherwise all the installer jobs would be failing on all machines. @gdams What would be the command in the `pkgbuild.sh` that's causing that error message?

**Comment by gdams** [comment]
fixed, it turns out that certain machines didn't have the default login keychain correctly set:

to check:
```bash
security default-keychain
# should return /Users/jenkins/Library/Keychains/login.keychain-db
```

to change:
```bash
security default-keychain -s /Users/jenkins/Library/Keychains/login.keychain-db
restart
```

You will likely need to import the codesign certificates after changing the default keychain.

I've checked all build/test machines and plan to make this an ansible role soon

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/create_installer_mac/ looks greener now
