### ISSUE TITLE
我能否编译 linux 下的 bug 版本？

### ISSUE THREAD

**Issue by bytestruct** [AdoptOpenJDK/openjdk-build#2079]
我能否编译 linux 下的 bug 版本？

Can I compile the bug version under linux?

**Comment by smlambert** [comment]
Is this a duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/146 ?

**Comment by sanhong** [comment]
yes, I guess so.

**Comment by sanhong** [comment]
> 我能否编译 linux 下的 bug 版本？
> 
> Can I compile the bug version under linux?

你说的是fastdebug版本吧，  你看下#146
