### ISSUE TITLE
Allow Docker machine label to be configurable

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#2095]
Currently hardcoded to `dockerBuild`. We would like to use our own label.
https://github.com/AdoptOpenJDK/openjdk-build/blob/ffbede7222000cf51eb96549b018166d20d11b48/pipelines/build/common/openjdk_build_pipeline.groovy#L685
Either via param or config file.
Related #2045

**Comment by M-Davies** [comment]
@AdamBrousseau When you say config file, I assume you're referring to [this](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk8u_pipeline_config.groovy) kind of file?

**Comment by AdamBrousseau** [comment]
Yes, but ideally I can point at a file in a different location at build time. Ie. Use my own instead of the default one in the main repo. This goes back to my other issue (#2045) about providing user's own configs. For now, being able to override in the build configs param like I do for the other values like node labels would work.
