### ISSUE TITLE
jdk-15+36 linux version can not run with glibc version 2.12

### ISSUE THREAD

**Issue by imweijh** [AdoptOpenJDK/openjdk-build#2097]
**Platform:**
CentOS 6.10

**Architecture:**
X64

Download page say linux version openjdk 15 work with "Linux glibc version 2.12 or higher"
BUT

```
jdk-15+36]# bin/java -version
bin/java: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/jdk-15+36/bin/../lib/libjli.so)
```

OpenJDK 15 build by Oracle works in Centos 6.

**Comment by AdamBrousseau** [comment]
JDK15 was changed to compile on Centos 7 (At Adopt).
#1819
#1865 
However I don't see any [release notes](https://adoptopenjdk.net/release_notes.html) on the website yet which would hopefully announce the change.

**Comment by aahlenst** [comment]
At the moment, you'd find such a change only in our release announcement: https://blog.adoptopenjdk.net/2020/09/adoptopenjdk-15-available/. I apparently missed that. The release notes so far have only been a dump of OpenJDK changes.

But we could still make it work with an older glibc. Oracle builds on 7 with headers/libs from 6: https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms.

**Comment by aahlenst** [comment]
CentOS/RHEL 6 support should be restored in this week's release of AdoptOpenJDK 15.

**Comment by pshipton** [comment]
The OpenJ9 project doesn't support CentOS 6 for Java 15 and later, only glibc level 2.17 and later i.e. CentOS 7.
CentOS 6 is out of support in Nov 2020.
