### ISSUE TITLE
Investigate documenting ENV vars used in build/bash scripts

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#21]
This was raised on the back of the code review on PR ( #20 ) by @karianna.

Applies to all the build/bash scripts created to run in native environments.

**Comment by wjam** [comment]
Adopting some of the Google Shell style guide might make this easier (https://google.github.io/styleguide/shell.xml) such as having variables be lower case and environment variables be upper case.

The scripts would benefit from setting various options to check for errors, etc such as the ones at the top of this script https://raw.githubusercontent.com/kvz/bash3boilerplate/master/main.sh

**Comment by neomatrix369** [comment]
@wjam Try taking small chunks of the scripts and apply the above and create a PR to see what everyone things about it. There is a tiny process after you have raised a PR - but we can talk about it then

**Comment by karianna** [comment]
Our README docs should point to the script where developers should look.
