### ISSUE TITLE
git-hg-10 jenkins job is successful despite failure in the final stages of the operation(s)

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#211]
After looking at the logs in https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-10/2635/console it appears that the job passes even though the operation has failed towards the end:
```
...
Merge 'jdk'
Already up-to-date.
Push
To git@github.com:AdoptOpenJDK/openjdk-jdk10.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:AdoptOpenJDK/openjdk-jdk10.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Finished: SUCCESS
```

Might be the same case with the other `git-xxx` jobs, advisable to investigate at all the scripts under https://ci.adoptopenjdk.net/view/git-hg/.

Hint: bash scripts need a `set -e` inserted in the header of each of the scripts, this will cause the builds to break due to any kind of exceptions when running the script.

**Comment by sxa555** [comment]
Not limited to jdk10 mirrors by the look of https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-8

**Comment by sxa555** [comment]
Note: The jobs are pulling from `updating-the-new-hg-for-jdk-10-repo` in `openjdk-build` so my fix isn't being picked up

**Comment by karianna** [comment]
@sxa555 Hmm, is updating-the-new-hg-for-jdk-10-repo something that needs to be merged into the regular script?

**Comment by sxa555** [comment]
@karianna I suspect so but I don't know anything about why that branch exists and is the live on. @gdams @neomatrix369 ?

**Comment by neomatrix369** [comment]
@sxa555 ` updating-the-new-hg-for-jdk-10-repo` is nw in master, that branch was related to fixing the build for jdk10/11, please change the job settings to point to master now.
