### ISSUE TITLE
Build JDK11u 11.0.9 (or a variant) with Shenandoah

### ISSUE THREAD

**Issue by bric3** [AdoptOpenJDK/openjdk-build#2114]
Hello,

Do you plan to release a jdk11u build with Shenandoah ? As you are certainly aware Shenandoah was back-ported this summer, it just need to be activated in the build.

While the modification in this [file](https://github.com/AdoptOpenJDK/openjdk-build/blob/b5941737145dfbe5c10030737f6c69bce6132749/pipelines/jobs/configurations/jdk11u_pipeline_config.groovy#L32-L36) is likely straightforward, it has certainly implications which I do not grasp. Wether to include Shanandoah in the _default_ build may be something up to debate, but in the case it's a no I think that shipping a JDK11u variant with Shenandoah could be appreciated, I certainly would.

Cheers,
Thank you for this project !!!

**Comment by karianna** [comment]
IMO we should include it as a default, it's mainline code, and fully supported there.

**Comment by aahlenst** [comment]
Agreed. Do we need to discuss that in a TSC call, @karianna?

**Comment by karianna** [comment]
I'll just make it a quick poll vote I think.

**Comment by kittylyst** [comment]
I would be in favour of Shenandoah being included as a default if you're looking for community opinions :)

**Comment by karianna** [comment]
So looking at this more closely, I think the nightlies just have this automatically.

@bric3 Can you try a https://adoptopenjdk.net/nightly.html build (Java 11) and let us know if that works for you?

**Comment by bric3** [comment]
@karianna Using the macOs build at least didn't. I'll test a linux one in a minute

```shell
$ tar xf OpenJDK11U-jdk_x64_mac_hotspot_2020-10-05-14-54.tar.gz
$ cd jdk-11.0.9+10/Contents/Home/bin
$ ./java --version
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment Hotspot (build 11.0.9+10-202010050013)
OpenJDK 64-Bit Server VM Hotspot (build 11.0.9+10-202010050013, mixed mode)
$ ./java -XX:+PrintFlagsFinal -XX:+UseShenandoahGC --version | less
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by orionll** [comment]
I'm sorry but I don't see Shenandoah in AdoptOpenJDK 11.0.9. What am I doing wrong?

```
C:\Soft\jdk-11\bin>java --version
openjdk 11.0.9 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

C:\Soft\jdk-11\bin>java -XX:+UseShenandoahGC --version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by aahlenst** [comment]
@orionll https://github.com/AdoptOpenJDK/openjdk-build/issues/2176
