### ISSUE TITLE
Allow regenerators to use custom configs from other repositories

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#2116]
It would be good to have the capability for the pipelines to both produce and run configurations from other repositories. This currently exists for the Adopt repository (https://github.com/AdoptOpenJDK/openjdk-build/pull/2048) but not for remote ones. It would be useful to add a parameter that points the script at a specific repository.

**Comment by AdamBrousseau** [comment]
These are the 3 types of configuration files I could find that would be benefit from this item. There may be more I am unaware of yet.
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk11u.groovy
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/jobs/configurations/jdk11u_pipeline_config.groovy
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/linux.sh
