### ISSUE TITLE
Make build/test "Queue" phase abort if no nodes online after X mins

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2118]
To better allow Nightly build pipelines to achieve a decent throughput and for immediate feedback rather than just "hanging", it would be useful to allow the configuration of a "timeout" for the Queue phase if there are "NO" nodes online, ie.it would just hang forever until such nodes are brought back online.
The no nodes timeout should default to 0, if the build parameter is not supplied, thus under normal nightly circumstances if there are no nodes online the build will immediately abort.

ref see: https://github.com/AdoptOpenJDK/openjdk-build/issues/2093

**Comment by adamfarley** [comment]
PR draft ready for review: https://github.com/AdoptOpenJDK/openjdk-build/pull/2130

Will post a message in Adopt Slack too.

Note this is my first time making significant Groovy code changes, so do expect beginner errors.
