### ISSUE TITLE
Update OpenJ9 builds to openssl 1.1.1h

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#2123]
There is a new version of openssl, 1.1.1h, which contains bug fixes. I don't think any of the fixes affect areas that OpenJ9 uses, but we should update to use the latest version anyway. This can occur after the Oct release.

**Comment by AdamBrousseau** [comment]
Related openjdk-infrastructure#1578 & #2122 
I thought that issue would cover the other platforms as well but looks like it's only targeting windows now.
https://github.com/AdoptOpenJDK/openjdk-build/pull/2124
