### ISSUE TITLE
Consider removing libfreetype from Linux binary builds

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-build#2133]
So far, we bundle libfreetype on Linux and probably other platforms where it isn't required (needs to be investigated; Windows requires is). The bundled libfreetype is not enough for font support. fontconfig and some fonts still need to be installed. But the JDK isn't really helpful in that case because you only get a NPE (see https://github.com/AdoptOpenJDK/openjdk-support/issues/70). If you install fontconfig and fonts on Linux, you get the operating system's version of libfreetype which might be a different version than the one we bundle. Removing libfreetype therefore seems to be the sensible option: Without libfreetype, the exception is more meaningful (`Exception in thread "main" java.lang.UnsatisfiedLinkError: /root/jdk-11/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory`). Furthermore, the download is smaller and we can get rid of a library that we have to update. We'd follow OpenJDK by doing so. Both Oracle's builds provided on jdk.java.net as well as Red Hat's builds for Linux come without libfreetype.

See https://github.com/AdoptOpenJDK/openjdk-support/issues/70#issuecomment-703103511 for further information.

**Comment by adamfarley** [comment]
--skip-freetype in the build args seems to work well enough.

https://ci.adoptopenjdk.net/view/work-in-progress/job/adamf-linux-hotspot-build/5/

Will create a basic PR to add that option to linux builds.

**Comment by aahlenst** [comment]
Fixed via #2226.
