### ISSUE TITLE
OpenJ9 JDK15 OSX build doesn't run out of the box

### ISSUE THREAD

**Issue by JasonFengJ9** [AdoptOpenJDK/openjdk-build#2134]
**Platform:**
OSX
**Architecture:**
AMD64

Please describe the issue that you are having with our binaries and if possible how to recreate it.
```
“java” cannot be opened because the developer cannot be verified.
macOS cannot verify that this app is free from malware.
Chrome downloaded this file today at 10:16 AM from adoptopenjdk.net.
```
This occurred to nightly & release builds.
JDK11 OSX works as usual.

**Comment by aahlenst** [comment]
That is expected if you downloaded the zip or tarball. Only PKGs are notarized (technical reasons). Furthermore, this happens only if an application adds the quarantine attribute. The browsers do this, curl or wget do not.

**Comment by JasonFengJ9** [comment]
yeah, `wget` worked around the issue.
Thanks your quick response.

**Comment by aahlenst** [comment]
https://blog.adoptopenjdk.net/2020/04/adoptopenjdk-8u252-1107-and-1401-available/ has additional information about the attributes. They can be added/removed with xattr.
