### ISSUE TITLE
Windows & Mac signing should be optional

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#2149]
I would like the ability to run nightly builds without having to sign the Windows and Mac binaries. I think this should be an optional step similar to what was done for test and installers. I can see in the Windows builds a separate sign_build is called (which I can't see). It appears on Mac it happens during compilation[1].

[1] https://github.com/AdoptOpenJDK/openjdk-build/blob/master/build-farm/platform-specific-configurations/mac.sh#L53-L62

**Comment by sxa** [comment]
@gdams Can you clarify the macos story here? I had a recollection that it wasn't possible (or desirable for notarization purposes?) to have some aspects of this switched off completely?

**Comment by AdamBrousseau** [comment]
On my end it won't be feasible to sign Mac nightlies (at the moment) so we'll need this configurable for the compile as well as the installer.
