### ISSUE TITLE
Add OpenJ9 XL builds to 16 pipeline

### ISSUE THREAD

**Issue by aahlenst** [AdoptOpenJDK/openjdk-build#2174]
For some reason, OpenJ9 XL builds are absent from the 16 pipeline. I've confirmed with the OpenJ9 folks that they aren't ready to abandon the XL variants in 16.

**Comment by adamfarley** [comment]
Odd. Will handle this.

**Comment by adamfarley** [comment]
Ok, I think this todo list will resolve this issue:

Step 1) Merge this and wait for the relevant build jobs to be automatically generated:
https://github.com/AdoptOpenJDK/openjdk-build/pull/2251
Step 2) Run this to generate test jobs for the new XL builds:
https://ci.adoptopenjdk.net/job/Test_Job_Auto_Gen
Step 3) Run this to regenerate the top-level pipeline job for jdk16:
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/build-pipeline-generator/

**Comment by M-Davies** [comment]
You'll also need to run https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/pipeline_jobs_generator_jdk/ to generate the new XL downstream jobs (once the top level pipeline one has completed).

**Comment by adamfarley** [comment]
@M-Davies - Does that job not run automatically once Step 1 is complete?

**Comment by M-Davies** [comment]
So does https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/build-pipeline-generator/ (at least, it should do).

**Comment by adamfarley** [comment]
Oh. What about test job auto gen? If that runs as well, it'd complete the set.

**Comment by M-Davies** [comment]
I don't think so as `GitHub hook trigger for SCM polling` isn't enabled. That would have to be executed manually by @smlambert or another member of the test team with access
