### ISSUE TITLE
jdk11u-linux-aarch64-openj9 InvalidModuleDescriptorException

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#2178]
**Platform:**
Linux
**Architecture:**
aarch64

Got this when running some test nightly builds:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/545/console
```
11:14:14  Compiling 4 files for BUILD_JIGSAW_TOOLS
11:14:14  java.lang.module.FindException: Error reading module: /home/ubuntu/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-openj9/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/modules/jdk.internal.le
11:14:14  Caused by: java.lang.module.InvalidModuleDescriptorException: Package jdk.internal.org.jline.reader not found in module
```
It's been failing since 25/10/2020 (all have been building inside docker containers). For reference, build `541` is the recent release, all others are nightlies.
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9
<img width="337" alt="Screenshot 2020-10-26 at 11 53 15" src="https://user-images.githubusercontent.com/25231953/97169443-fe52ee80-1781-11eb-8b95-cff309c4bdbf.png">
The commit hash for the openj9 repo between the last failing and first successfull build is https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/fd18c0317c3059188d00ba91a410d6c87415d0f2. Both the first failing and last successfull have this commit hash listed as the latest one. I cannot see the sources for the omr repo unfortunately.

Last passing openj9 version:
```
00:25:52  openjdk version "11.0.9" 2020-10-20
00:25:52  OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11-202010232344)
00:25:52  Eclipse OpenJ9 VM AdoptOpenJDK (build master-909c7ffdc, JRE 11 Linux aarch64-64-Bit Compressed References 20201023_542 (JIT enabled, AOT enabled)
00:25:52  OpenJ9   - 909c7ffdc
00:25:52  OMR      - cb68c30b7
00:25:52  JCL      - fd18c0317c based on jdk-11.0.9+11)
```

**Comment by M-Davies** [comment]
@pshipton

**Comment by pshipton** [comment]
@keithc-ca could this be related to your openjdk change?

**Comment by pshipton** [comment]
Sorry, I misread it. Last success build also has the openjdk change.

**Comment by M-Davies** [comment]
> Sorry, I misread it. Last success build also has the openjdk change.

I did just edit it to add that so it was my bad for not putting it in the first place

**Comment by keithc-ca** [comment]
> @keithc-ca could this be related to your openjdk change?

Do you mean ibmruntimes/openj9-openjdk-jdk11#355? I was willing to consider that it affected cross-compiling somehow, but as you say, it's in the last good build.

**Comment by pshipton** [comment]
I don't know what SHA's the broken build is building, but I see these OpenJ9 commits since the working one.

https://github.com/eclipse/openj9/pull/10731 - merged Oct 24 7:35am EDT.
https://github.com/eclipse/openj9/pull/10557 - merged Oct 25 11:09pm EDT.

For OMR this was, promoted Oct 23, 2020 7:53:25 PM EDT.
https://github.com/eclipse/omr/pull/5584

No record for when these were manually promoted, sometime after Oct 24, ~10am EDT is my guess.
https://github.com/eclipse/omr/pull/5441
https://github.com/eclipse/omr/pull/5583

Not sure of the timezone for these, it could be UK time.
Last success Oct 24, 2020 1:30:22 AM
First failure Oct 25, 2020 1:30:21 AM

@knn-k can you pls take a look.

**Comment by pshipton** [comment]
@0xdaryl @dsouzai fyi as well

**Comment by M-Davies** [comment]
> Not sure of the timezone for these, it could be UK time.
Last success Oct 24, 2020 1:30:22 AM - Oct 23 9:30pm EDT?
First failure Oct 25, 2020 1:30:21 AM - Oct 24 9:30pm EDT?

Looks like it's 1 hour ahead of UK time. UTC+1 is my guess

**Comment by M-Davies** [comment]
> Not sure of the timezone for these, it could be UK time.
Last success Oct 24, 2020 1:30:22 AM - Oct 23 9:30pm EDT?
First failure Oct 25, 2020 1:30:21 AM - Oct 24 9:30pm EDT?

I'm guessing UTC+1 as I just executed a test build and it's come up as `26-Oct-2020 16:05` (It's was 15:05 UK time when I executed it)

**Comment by knn-k** [comment]
https://github.com/eclipse/openj9/pull/11006 should fix this.

**Comment by knn-k** [comment]
eclipse/openj9#11006 was merged.

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/550/console is passing now. Thanks
