### ISSUE TITLE
Support building SAPmachine openjdk builds in the adoptopenjdk build farm

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#218]
SAP has their own version of the openjdk source (Java 10 only). See https://github.com/SAP/SapMachine

We wish to build and test this in the adoptopenjdk jenkins instance

Memo to self via George: Follow https://github.com/AdoptOpenJDK/openjdk-infrastructure/wiki/Adding-a-new-build-variant

**Comment by sxa555** [comment]
Job created at https://ci.adoptopenjdk.net/job/openjdk10_sap_build_x86-64_linux/ 

Caveat 1: It requires the disable shallow clone option due to the use of `git log HEAD^` in https://github.com/SAP/SapMachine/blob/sapmachine/make/SourceRevision.gmk

Caveat 2: The --jtreg option will cause the job to fail due to SAP's source tree not having a `jdk/test`directory which is used by the `applyingJCovSettingsToMakefileForTests()` method in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/jtreg.sh

**Comment by sxa555** [comment]
@gdams Ref your "Adding a new build variant" doc I don't have the access to create a new repository under AdoptOpenJDK

**Comment by karianna** [comment]
This appears to be up and running now (there are some test failures, but we have separate issues for that.
