### ISSUE TITLE
CONFIGURE_ARGS does not get passed to ./configure on arm

### ISSUE THREAD

**Issue by adamfarley** [AdoptOpenJDK/openjdk-build#2194]
**What are you trying to do?**
Use CONFIGURE_ARGS to pass arguments into a build pipeline's "bash ./configure" command.

**Expected behaviour:**
I expect this to work.

**Observed behaviour:**
I have observed the arguments simply vanishing after entering make-adopt-build-farm.sh

E.g. https://ci.adoptopenjdk.net/view/work-in-progress/job/adamf_aarch64_j9/1/consoleFull

**Any other comments:**

A simple way to fix this could be to concatenate CONFIGURE_ARGS onto CONFIGURE_ARGS_FOR_ANY_PLATFORM (after the latter is set) before passing the resultant string into makejdk-any-platform.sh inside make-adopt-build-farm.sh.

Note: The fix also prevents arm-specific code from blanking CONFIGURE_ARGS_FOR_ANY_PLATFORM and replacing it.

**Comment by adamfarley** [comment]
Change ready.

Test running: https://ci.adoptopenjdk.net/view/work-in-progress/job/adamf_aarch64_j9/3/console

**Comment by andrew-m-leonard** [comment]
@adamfarley  Problem is a "arm" specific issue due to this code: https://github.com/AdoptOpenJDK/openjdk-build/blob/82d3beb0678f5622e429b2f8f2442a318bfa240c/build-farm/platform-specific-configurations/linux.sh#L75

**Comment by andrew-m-leonard** [comment]
So to be clear this only affects jdk8u-linux-arm-hotspot

**Comment by andrew-m-leonard** [comment]
Luckily the Release builds for jdk8u-linux-arm-hotspot only specify --with-milestone=fcs which gets added automatically by the build scripts anyway, so it didn't matter it was lost...!

**Comment by adamfarley** [comment]
Good spot Andrew.

I've modified the fix to:
a) resolve the arm-specific problem.
and
b) add the user's options after we set CONFIGURE_ARGS_FOR_ANY_PLATFORM, so the user always has priority.
