### ISSUE TITLE
AIX builds failing due to running out of disk space

### ISSUE THREAD

**Issue by ben-walsh** [AdoptOpenJDK/openjdk-build#222]
See https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_ppc64_aix/70 ...

```
Caused by: hudson.plugins.git.GitException: Command "git init /ramdisk0/build/workspace/openjdk8_openj9_build_ppc64_aix" returned status code 128:
stdout: 
stderr: error: copy-fd: write returned There is not enough space in the file system.
fatal: cannot copy '/opt/freeware/share/git-core/templates/description' to '/ramdisk0/build/workspace/openjdk8_openj9_build_ppc64_aix/.git/description': There is not enough space in the file system.
```

**Comment by ben-walsh** [comment]
Looks like just build-osuosl-ppc64-aix-71-1 machine has the problem at the moment.
build-osuosl-ppc64-aix-71-2 seems fine.

**Comment by sxa555** [comment]
. o O (That's odd)

```
$ df -k /ramdisk0
Filesystem    1024-blocks      Free %Used    Iused %Iused Mounted on
/dev/ramdisk0    15728640         0  100%   134574    25% /ramdisk0
$ du -sk /ramdisk0/
2619676 /ramdisk0/
$ 
```

**Comment by sxa555** [comment]
Even after clearing it it's showing as only having 2.6Gb free - something's holding file handles open in there or ...

Hmmm ... after attempting a umount of `/ramdisk0` (which failed) it seems to now be showing the full amount of space free. Closing.

**Comment by sxa555** [comment]
(For reference this was the machine `140.211.9.10`)
