### ISSUE TITLE
JDK8/HotSpot/arm32 builds don't have AdoptOpenJDK in java -version

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2229]
**What are you trying to do?**

Run `java -version` on the JDK8/HotSpot builds on arm 320bit

**Expected behaviour:**

To see `AdoptOpenJDK` in the output as per other platforms e.g. here is Linux/s390x's equivalent output:
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_275-b01)
OpenJDK 64-Bit Zero VM (AdoptOpenJDK)(build 25.275-b01, interpreted mode)
```

**Observed behaviour:**

No `AdoptOpenJDK` string:

```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK Client VM (build 25.275-b01, mixed mode)
```

**Any other comments:**

**Comment by adamfarley** [comment]
Taking a look.

**Comment by adamfarley** [comment]
Ok, the vendor is being correctly passed in via "--with-vendor-name" in the configure step, so I'm currently googling and poking through jdk8 code to try and figure out why it doesn't end up in the -version output like it does in jdk8 zLinux and jdk11 arm.

**Comment by adamfarley** [comment]
All fixed as per this PR. 

https://github.com/AdoptOpenJDK/openjdk-aarch32-jdk8u/pull/1

Closing.
