### ISSUE TITLE
Skip step sign when installer disabled

### ISSUE THREAD

**Issue by joeyleeeeeee97** [AdoptOpenJDK/openjdk-build#2231]
All installer related jobs are private so we need to skip these steps when built on other Jenkins. So I propose we use "enableInstallers" to skip the signing step as well.
A failure example in ci.dragonwell : http://ci.dragonwell-jdk.io/view/build_scripts/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-dragonwell/48/

**Comment by M-Davies** [comment]
Related / Close to being a duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/2160
