### ISSUE TITLE
Empty SEMANTIC_VERSION in RELEASE file for 1.8.0_275-b01

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/openjdk-build#2236]
**What are you trying to do?**
I try to get `SEMANTIC_VERSION` value from `release` file  for 1.8.0_275-b01

**Expected line in `release` file:**
`SEMANTIC_VERSION="8.0.275+1"` or similar

**Observed line in `release` file:**
`SEMANTIC_VERSION=""`

**Any other comments:**
https://github.com/AdoptOpenJDK/openjdk-build/pull/2049

Full contents of `release` file for 1.8.0_275-b01
```
JAVA_VERSION="1.8.0_275"
OS_NAME="Windows"
OS_VERSION="5.2"
OS_ARCH="amd64"
SOURCE=" .:OpenJDK: f59514f7b2:"
IMPLEMENTOR="AdoptOpenJDK"
BUILD_SOURCE="git:c0a1a87c"
FULL_VERSION="1.8.0_275-b01"
SEMANTIC_VERSION=""
BUILD_INFO="OS: Windows Server 2012 R2 Version: 6.3"
JVM_VARIANT="Hotspot"
JVM_VERSION="25.275-b01"
IMAGE_TYPE="JRE"

```

**Comment by tushev** [comment]
Just checked the JDK (the data above is for JRE) - `SEMANTIC_VERSION=""` as well there.

**Comment by andrew-m-leonard** [comment]
Fixed by: https://github.com/AdoptOpenJDK/openjdk-build/pull/2259

**Comment by tushev** [comment]
thanks!
