### ISSUE TITLE
JDK16 pipelines not working

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2239]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/186/console
- **Which platforms (OS+arch) are affected:** All - it doesn't get as far as running the build jobs
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No, but it started a week ago
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** n/a

```
hudson.remoting.ProxyException: groovy.lang.MissingMethodException: No signature of method: java.lang.Boolean.clear() is applicable for argument types: () values: []
Possible solutions: sleep(long), sleep(long, groovy.lang.Closure), every(), collect(), grep(), or(java.lang.Boolean)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at 
```

This was split out from https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1688#issuecomment-729586891

**Comment by adamfarley** [comment]
Taking a look.

**Comment by adamfarley** [comment]
Ok, after looking at the openjdk-build PRs before the first failure, here's the most likely cause:

https://github.com/AdoptOpenJDK/openjdk-build/pull/2026/files

Investigating to find out why.

**Comment by adamfarley** [comment]
Ok, one theory is that groovy doesn't like comments inside its arrays.

Here's a build to test that:

https://ci.adoptopenjdk.net/view/work-in-progress/job/adam_farley_build_scripts_jdk16_pipeline/1/console

Failed. Same error.

**Comment by adamfarley** [comment]
Ok, the new failure could be related to the fact that we're building in a wip job.

Will briefly change the mainstream job over to use my branch, so we can see if this fix actually fixes things.

**Comment by adamfarley** [comment]
Ok, this seems to work fine. 

PR: https://github.com/AdoptOpenJDK/openjdk-build/pull/2240

Test: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk16-pipeline/187/console

Changing the job back to the master branch and posting this change in Slack for reviews.
