### ISSUE TITLE
Inconsistency in references to JDK_PATH and j2sdk-image in build scripts

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#224]
Build scripts in https://github.com/AdoptOpenJDK/openjdk-build and https://github.com/AdoptOpenJDK/openjdk-build/tree/master/sbin are referring to j2sdk-image and some are using JDK_PATH, but not consistently, the hard-coding should be replaced with the variable.

Different versions of the JDK artifact references them differently:
JDK8: `j2sdk-image`
JDK9 onwards: `jdk`

Also, check the `Dockerfile` files.

**Comment by karianna** [comment]
Refactored a long time ago.
