### ISSUE TITLE
OpenJ9 image missing debug symbols

### ISSUE THREAD

**Issue by ninja-** [AdoptOpenJDK/openjdk-build#2245]
looks like both JRE and JDK versions are missing native debug symbols. any chance to include them?
I am trying to debug a JVM crash and so far native callstacks are useless...

**Comment by sxa** [comment]
@ninja- Which platform are you looking for the symbols for? While I'll admit it doesn't seem to be particularly accessible on the web site if you go to e.g. [the 11.0.9+11.1 OpenJ9 release in Github](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.9%2B11_openj9-0.23.0) there are the `debugimage` downloads which likely contain what you need.

**Comment by ninja-** [comment]
@sxa isn't the newest openj9 version java13 instead of java11?

**Comment by sxa** [comment]
I pointed you to the latest LTS release which is 11 as I wasn't sure which version you wanted. The latest java release is 15. 13 is out of support for OpenJ9 (Only the in-support releases are listed on the front of https://adoptopenjdk.net)

**Comment by ninja-** [comment]
OK, I see the proper image would be here: https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk15u-2020-11-20-06-22/OpenJDK15U-debugimage_x64_linux_openj9_2020-11-19-20-27.tar.gz

**Comment by sxa** [comment]
If you're using the nightly build that's correct. If it's the latest 15 GA code then https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/jdk-15.0.1%2B9_openj9-0.23.0 is the place to pick it up from

**Comment by ninja-** [comment]
Oh there are nighly builds? Even better for me. thanks for the info :)

**Comment by sxa** [comment]
Yep they're at https://adoptopenjdk.net/nightly.html ... Standard disclaimers apply of course - they could be broken but they are built from the latest code. if you need the debug symbols make sure you're using the ones that match the build you're using. I'll close this for now but your issue has highlighted that the web page doesn't have the debug symbols easily accessible so I'll raise that separately in the website repo. Thanks and good luck debugging :-)

**Comment by ninja-** [comment]
@sxa these symbols don't work for me :/ they are still unresolved in javacore*.txt - expect a few ones

Stacktrace:
```
3XMTHREADINFO3           Native callstack:
4XENATIVESTACK               (0x00007FAC3A667992 [libj9prt29.so+0x58992])
4XENATIVESTACK               (0x00007FAC3A634D73 [libj9prt29.so+0x25d73])
4XENATIVESTACK               (0x00007FAC3A667A0E [libj9prt29.so+0x58a0e])
4XENATIVESTACK               (0x00007FAC3A667B04 [libj9prt29.so+0x58b04])
4XENATIVESTACK               (0x00007FAC3A634D73 [libj9prt29.so+0x25d73])
4XENATIVESTACK               (0x00007FAC3A66786B [libj9prt29.so+0x5886b])
4XENATIVESTACK               (0x00007FAC3A663BFF [libj9prt29.so+0x54bff])
4XENATIVESTACK               (0x00007FAC3BA243D0 [libpthread.so.0+0x143d0])
4XENATIVESTACK               pthread_cond_wait+0x1fa (0x00007FAC3BA1FA7A [libpthread.so.0+0xfa7a])
4XENATIVESTACK               (0x00007FAC3914DA48 [libj9jit29.so+0x164a48])
4XENATIVESTACK               (0x00007FAC3915E168 [libj9jit29.so+0x175168])
4XENATIVESTACK               (0x00007FAC3915E1FA [libj9jit29.so+0x1751fa])
4XENATIVESTACK               (0x00007FAC3A634D73 [libj9prt29.so+0x25d73])
4XENATIVESTACK               (0x00007FAC3915E654 [libj9jit29.so+0x175654])
4XENATIVESTACK               (0x00007FAC3AAAD2F2 [libj9thr29.so+0xe2f2])
4XENATIVESTACK               (0x00007FAC3BA18F00 [libpthread.so.0+0x8f00])
4XENATIVESTACK               clone+0x3f (0x00007FAC3B94445F [libc.so.6+0xfe45f])
```

A couple of working ones from the javacore:
```
4XENATIVESTACK               JLI_Launch+0x148b (0x00007F2D0B66391B [libjli.so+0x791b])
4XENATIVESTACK               omrthread_monitor_wait+0x287 (0x00007FAC3AAA77E7 [libj9thr29.so+0x87e7])
4XENATIVESTACK               Java_openj9_internal_tools_attach_target_IPC_waitSemaphore+0x55 (0x00007F2D03B41D25 [libjclse29.so+0x10d25])
4XENATIVESTACK               Java_java_lang_ClassLoader_defineClassImpl1+0x11e (0x00007F2D03B427DE [libjclse29.so+0x117de])
```
