### ISSUE TITLE
JDK8/HotSpot/arm32 builds not completing successfully

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2247]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:** https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-hotspot/
- **Which platforms (OS+arch) are affected:** Linux/arm32
- **If you look at the historic logs, does the problem appear to be specific to one machine?** 489 and 492 were on different Scaleway build boxes and both exhibit the problem
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** Initally recorded at https://github.com/AdoptOpenJDK/openjdk-build/issues/1450#issuecomment-731107791

SInce JDK8/aarch32 is build from a separate repository it may be a tagging issue in there. Since it has only just shown up it is unlikely to be a result of the changes that we put in to resolve issues related to the 11.0.9.1+1 release last week however https://github.com/AdoptOpenJDK/openjdk-build/pull/2234 was merged three days ago (FYA @andrew-m-leonard - although I think https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-hotspot/488/consoleFull went through with your latest change included so it superficially looks unlikely that's affected it)

```
12:57:53  WARNING: Failed to identify latest tag in the repository
12:57:54  From /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-arm-hotspot/workspace/./build//src
12:57:54   * branch                  HEAD       -> FETCH_HEAD
12:57:54  WARNING: Failed to identify latest tag in the repository
12:57:54  OpenJDK JDK path will be . JRE path will be -jre
12:57:54  Empty dir passed to be archived
```

**Comment by andrew-m-leonard** [comment]
It looks like the build is being repeated !!

**Comment by andrew-m-leonard** [comment]
ah getOpenJDKversion() gets called several times in build.sh

**Comment by andrew-m-leonard** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2252

**Comment by andrew-m-leonard** [comment]
Green: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-arm-hotspot/500/

**Comment by sxa** [comment]
Thanks @andrew-m-leonard :-D
