### ISSUE TITLE
? "semVer: unbound variable" in Windows builds (maybe more?)

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2256]
**What are you trying to do?** Build JDK8

**Expected behaviour:** No error messages

**Observed behaviour:** `18:19:13  /cygdrive/e/jenkins/tmp/sbin/build.sh: line 1022: semVer: unbound variable`

**Any other comments:** While this does not appear to be fatal, it was spotted while reporting https://github.com/AdoptOpenJDK/openjdk-build/issues/2255 but appears to have been in the previous night's successful build too so is unrelated and seemingly non-fatal in itself, but we should look at the cause and try to deal with the condition, or it's source problem, in a meaningful way.

The offending line is [here](https://github.com/AdoptOpenJDK/openjdk-build/blame/master/sbin/build.sh#L1024). I would imagine the changes to `addSemVer` in https://github.com/AdoptOpenJDK/openjdk-build/commit/433c6f2324d2b6f52a8fcf4611ab642c89ee77e3 (https://github.com/AdoptOpenJDK/openjdk-build/pull/2077) were incomplete and that `semVer` on that line perhaps just needs to be switched to `SEM_VER`? ping @austin0

**Comment by austin0** [comment]
Being fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2259 @andrew-m-leonard
