### ISSUE TITLE
Docker azure machines have "riscv64" label

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2267]
Since the x64 machines at https://ci.adoptopenjdk.net/label/riscv64/ are not capable of running RISC-V binaries, they should not have this label. For cross-compilation purposes we should be using `riscvcross` only.

Spun out from https://github.com/AdoptOpenJDK/openjdk-build/pull/2238#discussion_r530314651

**Comment by gdams** [comment]
I created a fix for this as part of my windows aarch64 PR https://github.com/AdoptOpenJDK/openjdk-build/pull/2117
