### ISSUE TITLE
AdoptOpenJDK compatible with TCK

### ISSUE THREAD

**Issue by Jan-Pleva** [AdoptOpenJDK/openjdk-build#2268]
Hello,
I have question, why AdoptOpenJDK is still not compatible with TCK (Java SE Technology Compatibility Kit )?
We would like to use AdoptOpenJDK for Liferay, but there is requirement TCK compatibility.

https://help.liferay.com/hc/en-us/articles/360028982631-Liferay-DXP-7-2-Compatibility-Matrix

**Comment by DanHeidinga** [comment]
This is probably best asked in the TSC (technical steering committee) repo: @AdoptOpenJDK/tsc

**Comment by Jan-Pleva** [comment]
It seems that I dont have access. -> 404

**Comment by keithc-ca** [comment]
Perhaps @DanHeidinga meant https://github.com/AdoptOpenJDK/TSC.

**Comment by Jan-Pleva** [comment]
#https://github.com/AdoptOpenJDK/TSC/issues/187
