### ISSUE TITLE
Incorrect VM classes in src.zip for OpenJDK+OpenJ9 builds

### ISSUE THREAD

**Issue by paulcheeseman** [AdoptOpenJDK/openjdk-build#227]
I was just playing around with this build:
```
openjdk version "1.8.0_162-internal"
OpenJDK Runtime Environment (build 1.8.0_162-internal-jenkins_2018_02_22_15_07-b00)
Eclipse OpenJ9 VM (build openj9-0.0M1, JRE 1.8.0 Linux amd64-64 Compressed References 20180222_85 (JIT enabled, AOT enabled)
OpenJ9   - 453326f7
OMR      - 1f7d88e0
JCL      - ce606dfd1f based on jdk8u162-b12)
```
and I noticed the source code provided in src.zip for classes such as `java/lang/System` and `java/lang/Object` doesn't match the binaries.

It looks like src.zip contains the OpenJDK versions of these classes instead of the OpenJ9 versions.

I verified with Xtrace that the binary is definitely using OpenJ9's version of `java/lang/System`:

```
> java "-Xtrace:print=mt,methods=java/lang/System.completeInitialization" -version
16:19:20.221*0x1809200              mt.3        > java/lang/System.completeInitialization()V bytecode static method
16:19:20.224 0x1809200              mt.9        < java/lang/System.completeInitialization()V bytecode static method
openjdk version "1.8.0_162-internal"
OpenJDK Runtime Environment (build 1.8.0_162-internal-jenkins_2018_02_22_15_07-b00)
Eclipse OpenJ9 VM (build openj9-0.0M1, JRE 1.8.0 Linux amd64-64 Compressed References 20180222_85 (JIT enabled, AOT enabled)
OpenJ9   - 453326f7
OMR      - 1f7d88e0
JCL      - ce606dfd1f based on jdk8u162-b12)

```
(The OpenJDK System class doesn't contain the `completeInitialization()` method.)

**Comment by DanHeidinga** [comment]
Mirrored this issue at OpenJ9: https://github.com/eclipse/openj9/issues/1264

**Comment by DanHeidinga** [comment]
JDK 8 extensions repo issue: https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/48

**Comment by DanHeidinga** [comment]
This has been fixed at the JDK 8 extensions repo.  Can a committer close this?
