### ISSUE TITLE
jdk8 sanity.openjdk hung Scheduling windows nodes

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2294]
https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows/403/console
```
[Pipeline] Start of Pipeline (hide)
[Pipeline] echo
SPEC: win_x86
[Pipeline] echo
LABEL: ci.role.test&&hw.arch.x86&&sw.os.windows
[Pipeline] stage
[Pipeline] { (Queue)
[Pipeline] nodesByLabel
Found a total of 6 nodes with the 'ci.role.test&&hw.arch.x86&&sw.os.windows' label
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on ‘ci.role.test&&hw.arch.x86&&sw.os.windows’
```

**Comment by M-Davies** [comment]
To broaden the scope, here's the full list of jobs that are hanging that are still in-progress:
- https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_sanity.openjdk_ppc64_aix/288/console
- https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_j9_sanity.openjdk_x86-64_mac/423/console
- https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk15_hs_sanity.openjdk_ppc64_aix/128/console
- https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk15_j9_sanity.openjdk_ppc64_aix/136/console
- https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk15_j9_sanity.openjdk_x86-64_windows/115/console
- https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/282/console
- https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_ppc64_aix/304/console
- https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_sanity.openjdk_x86-32_windows/403/console
- https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/421/console

@andrew-m-leonard , ref [your ping in slack](https://adoptopenjdk.slack.com/archives/C09NW3L2J/p1607422637208000?thread_ts=1607417207.206900&cid=C09NW3L2J) I haven't ran anything other than [one test pipeline I ran yesterday](https://ci.adoptopenjdk.net/view/work-in-progress/job/build-scripts-testing/job/openjdk8-pipeline/25/) for #2132 (and that was for linux, mac and windows and we have aix hangs here).

**Comment by M-Davies** [comment]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_j9_sanity.openjdk_x86-64_mac_xl/421/console and https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_ppc64_aix/282/console are starting to run now

**Comment by sxa** [comment]
The mac and AIX jobs were all correctly wiating on executors. Only the windows ones from the list should be getting scheduled as the machines are free.

**Comment by sxa** [comment]
Restarting jenkins on Tuesday appears to have resolved this - closing.
