### ISSUE TITLE
CleanWs at end of build should be runtime configurable

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#2296]
On AIX, there is a hardcoded `cleanWs` command at the end of the build [1]. According to the original commit [2], this was added because the Adopt AIX machines use a ramdisk for the build workspace. There is also a separate cleanWS that runs at the start of a build [3] that is configurable using the launch param `CLEAN_WORKSPACE`. The issue with the cleanWs at the end of the build is that it makes it harder for debugging build issues when the workspace cannot be saved.

I have 2 proposals.
1. My preference is to have a cleanWs at the end of the build. This leaves the machine in a cleaner state. It can either be toggled using the existing param CLEAN_WORKSPACE or a new one specifically meant for the "finally cleanup".
2. The forced AIX cleanup should either disappear into number 1 above, or it should be smart enough to only do the clean when it is actually using the ramdisk [4]. 

[1] https://github.com/AdoptOpenJDK/openjdk-build/blob/f201dc51895df819662f58a5d0066d546365fb12/pipelines/build/common/openjdk_build_pipeline.groovy#L968-L971
[2] https://github.com/AdoptOpenJDK/openjdk-build/pull/506/files
[3] https://github.com/AdoptOpenJDK/openjdk-build/blob/87f799024a58d392255eead1cd83d93515410b2e/pipelines/build/common/openjdk_build_pipeline.groovy#L881-L907
[4] https://github.com/AdoptOpenJDK/openjdk-build/blob/b5941737145dfbe5c10030737f6c69bce6132749/build-farm/platform-specific-configurations/aix.sh#L20

**Comment by karianna** [comment]
The challenge with the end of build cleanWs is if it is a one-off failure then the next run hits a dirty workspace.  I wonder if we need to go for the slightly over the top dual option of both.

**Comment by AdamBrousseau** [comment]
Sorry, maybe I misspoke, I don't want to remove the cleanWs form the start, that should stay, but we should additionally add an optional one at the end.

**Comment by sxa** [comment]
> The challenge with the end of build cleanWs is if it is a one-off failure then the next run hits a dirty workspace. I wonder if we need to go for the slightly over the top dual option of both.

I think over the last couple of months we've identified and cleaned up most situations where "dirty workspaces" are a problem, so in general we should be ok with that. We have been moving awafrom ramdisks on our AIX systems and changing this AIX behavior has definitely be on my wish list (at least as an option)

**Comment by karianna** [comment]
> Sorry, maybe I misspoke, I don't want to remove the cleanWs form the start, that should stay, but we should additionally add an optional one at the end.

I'm happy with a refactor where the existing flag is changed to CLEAN_WS_BEFORE_BUILD and a new one CLEAN_WS_AFTER_BUILD or something like that.

**Comment by M-Davies** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2416
