### ISSUE TITLE
Polish Dragonwell build

### ISSUE THREAD

**Issue by joeyleeeeeee97** [AdoptOpenJDK/openjdk-build#2316]
Including:

- Use a version file to determine the build Dragonwell version, like https://github.com/corretto/corretto-8/blob/develop/version.txt
- Pass BUILD_CONFIG[SCM_REF] to get_dragonwell_source.sh (Now Dragonwell 8 are several separate repos)
- Adjust outdated configure arguments, like ( --enable-jfr )  is not needed now
```
                        "dragonwell"  : '--enable-jfr --enable-unlimited-crypto --with-jvm-variants=server  --with-zlib=system',
```

**Comment by M-Davies** [comment]
Fixed by #2386
