### ISSUE TITLE
jkd8 win64 dragonwell mk-cacerts.sh: line 79: C:Program/bin/keytool: No such file or directory

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2328]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-dragonwell/3/console
```
17:12:54  Done (138 CA certs processed, 29 skipped).
17:12:56  Processing certificate with alias: subject=C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
17:12:56  ./mk-cacerts.sh: line 79: C:Program/bin/keytool: No such file or directory
```

**Comment by aahlenst** [comment]
The problem is higher up: 

```
18:06:57  Boot jdk directory: C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot\:
18:06:57  BOOT JDK: ./build-farm/make-adopt-build-farm.sh: line 118: C:\Program: command not found
18:06:57  JDK IN PATH: openjdk version "1.8.0_275"
```

**Comment by aahlenst** [comment]
So, the problem is somewhere in the build config for Dragonwell. The path to the boot JDK should be something like `/cygdrive/c/openjdk/jdk-7`, not `C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot\`. It's correctly set in

https://github.com/AdoptOpenJDK/openjdk-build/blob/b3fff8ed4e5a02035787726c745eee08af28c68e/build-farm/platform-specific-configurations/windows.sh#L22

and then turned into `JDK_BOOT_DIR` in

https://github.com/AdoptOpenJDK/openjdk-build/blob/b3fff8ed4e5a02035787726c745eee08af28c68e/build-farm/platform-specific-configurations/windows.sh#L206

but that may be too late.

**Comment by sxa** [comment]
Note that /dragonwell-bootstrap/jdk8u272-ga is the correct place to pick up the Dragonwell JDK8 boot JDK from. It will not bootstrap with another JDK7 unlike the other builds. Looks like something may be dereferencing a link somewhere to get to the path with spaces in it which is causing the problem.

FYI @joeyleeeeeee97

**Comment by sxa** [comment]
Looks to be passing that section for now, although it's tripping over somethign in the installer creation. Almost certainly an easy fix:

```
J:\jenkins\workspace\build-scripts\release\create_installer_windows>cd wix\SourceDir 

J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>call powershell.exe ./CreateSourceFolder.AdoptOpenJDK.ps1 
filename : OpenJDK8U-jdk_x64_windows_dragonwell_2020-12-23-17-07.zip doesn't match regex (?<jvm>hotspot|openj9)

J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>IF ERRORLEVEL 1 (
ECHO unzip failed  
 EXIT /b 2 
) 
unzip failed
Build step 'Execute Windows batch command' marked build as failure
```

**Comment by joeyleeeeeee97** [comment]
@sxa Thanks for digging into this. And I guess the error is caused when there is no such Dragonwell bootstrap image on the worker. 
In https://ci.adoptopenjdk.net/computer/build-alibaba-win2012r2-x64-1/ the build seems ok.
So maybe after download that for all windows build workers that problem should be resolved.

**Comment by sxa** [comment]
I believe this is ok now - we haven't had any problems on the other machines after deploying the Dragonwell boot JDK :-)
