### ISSUE TITLE
jdk11 win64 dragonwell 23:36:50  configure: error: --with--vendor-version-string contains non-graphical characters: (Alibaba Dragonwell)

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2329]
Dragonwell build is using a string containing a "space" for vendor-verison-string which is not valid
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-dragonwell/4/console
```
23:36:50  configure: error: --with--vendor-version-string contains non-graphical characters: (Alibaba Dragonwell)
23:36:50  configure exiting with result code 1
```

**Comment by sxa** [comment]
@andrew-m-leonard Have you confirmed it's the space and not the brackets and/or quotes which are specified?

https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L191 has
```
    BUILD_CONFIG[VENDOR_VERSION]="\"(Alibaba Dragonwell)\""
```
FYI @joeyleeeeeee97

**Comment by sxa** [comment]
Observation: Linux is ok with this using the same parameters
```
00:09:38  openjdk version "11.0.9" 2020-10-20
00:09:38  OpenJDK Runtime Environment (Alibaba Dragonwell) (build 11.0.9+10-202012212346)
00:09:38  OpenJDK 64-Bit Server VM (Alibaba Dragonwell) (build 11.0.9+10-202012212346, mixed mode)
```
so this is Windows specific

**Comment by sxa** [comment]
Interestingly this only seems to be a problem when run on the non-Alibaba build machines, so we may need to lock it to those for now.

However the installer job is failing once it goes through:

```

J:\jenkins\workspace\build-scripts\release\create_installer_windows>cd wix\SourceDir 

J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>call powershell.exe ./CreateSourceFolder.AdoptOpenJDK.ps1 
filename : OpenJDK11U-jdk_x64_windows_dragonwell_2020-12-24-10-26.zip doesn't match regex (?<jvm>hotspot|openj9)

J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>IF ERRORLEVEL 1 (
ECHO unzip failed  
 EXIT /b 2 
) 
unzip failed
Build step 'Execute Windows batch command' marked build as failure
```

**Comment by joeyleeeeeee97** [comment]
![image](https://user-images.githubusercontent.com/30545334/103164631-c67f2a80-4848-11eb-9511-8efaf856d44b.png)


> Interestingly this only seems to be a problem when run on the non-Alibaba build machines, so we may need to lock it to those for now.
> 
> However the installer job is failing once it goes through:
> 
> ```
> 
> J:\jenkins\workspace\build-scripts\release\create_installer_windows>cd wix\SourceDir 
> 
> J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>call powershell.exe ./CreateSourceFolder.AdoptOpenJDK.ps1 
> filename : OpenJDK11U-jdk_x64_windows_dragonwell_2020-12-24-10-26.zip doesn't match regex (?<jvm>hotspot|openj9)
> 
> J:\jenkins\workspace\build-scripts\release\create_installer_windows\wix\SourceDir>IF ERRORLEVEL 1 (
> ECHO unzip failed  
>  EXIT /b 2 
> ) 
> unzip failed
> Build step 'Execute Windows batch command' marked build as failure
> ```

![image](https://user-images.githubusercontent.com/30545334/103164632-cc750b80-4848-11eb-8ea1-121f1caeedff.png)
I notice the git repo we cloned is not right, so maybe we need to configure remove workspace true.
