### ISSUE TITLE
Enable nightly testing in JDK16

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2337]
**What are you trying to do?** Run nightly builds with testing enabled

**Expected behaviour:** We run tests as far as possible (excluding the functional ones which are apparently blocked for HotSpot/JDK16 due to a "sealed" issue

**Observed behaviour:** Only weekly tests are enabled, so the nightlies are not being run

**Any other comments:** This came out of a discussion while fixing the break resolved by https://github.com/AdoptOpenJDK/openjdk-build/pull/2336

**Comment by andrew-m-leonard** [comment]
jdk16 sanity.functional compile issue: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2136
