### ISSUE TITLE
signing job on windows is failing

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2346]
**What are you trying to do?** Run the sign_tool job within the nightly pipelines on Windows

**Expected behaviour:** Success of the job

**Observed behaviour:** Failure of the job - looks to be failing on any operation that contacts the timestamp server

```
find: 'basename' terminated by signal 13
find: 'basename' terminated by signal 13
Signing Windows release
Signing ./hotspot/jtreg/native/FPRegs.exe
Done Adding Additional Store

Number of errors: 1

SignTool Error: The specified timestamp server either could not be reached or
returned an invalid response.
SignTool Error: An error occurred while attempting to sign: ./hotspot/jtreg/native/FPRegs.exe

RETRYWARNING: Failed to sign ./hotspot/jtreg/native/FPRegs.exe at 22:16:56: Possible timestamp server error - RC 0 ... Retrying in 10 seconds
Done Adding Additional Store

Number of errors: 1

SignTool Error: The specified timestamp server either could not be reached or
returned an invalid response.
SignTool Error: An error occurred while attempting to sign: ./hotspot/jtreg/native/FPRegs.exe
```

**Any other comments:**

**Comment by karianna** [comment]
https://stackoverflow.com/questions/65541786/is-the-verisign-timestamp-server-down - we need a new timestamp server.  Checking alternatives...

**Comment by aahlenst** [comment]
@karianna Might make sense to align with https://github.com/AdoptOpenJDK/openjdk-installer/blob/master/wix/serverTimestamp.config and use the same logic incl. retry after doing the quick fix.

**Comment by karianna** [comment]
@aahlenst - Agreed - I'll leave this open so I can enhance it with the list (it'll take me a while because looping over a data structure in shell scripting takes time for this inexperienced shell scripter :-)).  In the mean time can you review/approve the interim PR - just so we can get the builds back up fro tonight?
