### ISSUE TITLE
macos builds are not clearing .pkg files from workspace

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2350]
**What are you trying to do?** Not have old files from previous builds retained

**Expected behaviour:** workspace directory (on master node specifically, but may be the case on the client ones too given what we're seeing.

**Observed behaviour:** `workspace/build-scripts/jobs/jdk15u/jdk15u-mac-x64-hotspot/workspace/target` is full of `old `pkg` files

**Any other comments:** Visible in the logs at e.g. https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-mac-x64-hotspot/156/consoleFull
```
10:22:46  ls: cannot access 'workspace/target/*.tar.gz': No such file or directory
10:22:46  ls: cannot access 'workspace/target/*.msi': No such file or directory
10:22:46  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-02-20-27.pkg
10:22:49  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-04-20-27.pkg
10:22:51  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-05-20-27.pkg
10:22:54  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-06-20-27.pkg
10:22:57  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-07-20-27.pkg
10:23:00  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-08-20-27.pkg
10:23:03  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-09-20-27.pkg
10:23:06  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-10-20-27.pkg
10:23:10  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-11-20-27.pkg
10:23:13  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-13-20-27.pkg
10:23:16  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-14-20-27.pkg
10:23:19  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-15-20-27.pkg
10:23:23  + sha256sum workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2020-12-16-20-27.pkg
```

**Comment by adamfarley** [comment]
Looking into this.

**Comment by adamfarley** [comment]
Still trying to figure out why cleanWs didn't remove these pkg files, using debug output and such. 

Slightly bottlenecked because there's only one active mac build machine, and others need to use it too. The other mac build machine is disabled at the moment.

**Comment by adamfarley** [comment]
Hmm, [this test](https://ci.adoptopenjdk.net/view/work-in-progress/job/adamf-mac-jdk15/5/consoleFull) (which has debug messages if you search for "DEBUG:") tells us that cleanWs is definitely cleaning the entire workspace, and makes no exception for pkg files in the "target" folder.

My next guess is that this is a permissions thing. I'll create a PR tomorrow morning that'll generate an error message and churn out a list of non-cleaned-up files (and their access permissions) if cleanWs fails to do what it says on the tin.

**Comment by adamfarley** [comment]
CleanWs only seems to happen on the build node, not the master node.

Here's a PR that ensures we clean up the packages on master (where needed) after they've been archived.

https://github.com/AdoptOpenJDK/openjdk-build/pull/2362

**Comment by adamfarley** [comment]
Ok, the JDK15 pipeline has been regenerated. [Here's a full nightly-style mac run.](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk15-pipeline/435/)

Also, thanks to @sxa for the merge. :)

**Comment by sxa** [comment]
NOTE: There are some files alongside the `.pkg` files which, while nowhere near as big, should probably also be cleared up in order to stop the sizes mounting up e.g.
```
rw-r--r-- 1 jenkins jenkins     19699 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2021-01-05-08-07.pkg.json
-rw-r--r-- 1 jenkins jenkins       135 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2021-01-05-08-07.pkg.sha256.txt
-rw-r--r-- 1 jenkins jenkins     19699 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2021-01-05-20-26.pkg.json
-rw-r--r-- 1 jenkins jenkins       135 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2021-01-05-20-26.pkg.sha256.txt
-rw-r--r-- 1 jenkins jenkins     19699 Jan  7 09:44 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2021-01-07-08-10.pkg.json
-rw-r--r-- 1 jenkins jenkins       135 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jdk_x64_mac_hotspot_2021-01-07-08-10.pkg.sha256.txt
-rw-r--r-- 1 jenkins jenkins     19699 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jre_x64_mac_hotspot_2021-01-05-08-07.pkg.json
-rw-r--r-- 1 jenkins jenkins       135 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jre_x64_mac_hotspot_2021-01-05-08-07.pkg.sha256.txt
-rw-r--r-- 1 jenkins jenkins     19699 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jre_x64_mac_hotspot_2021-01-05-20-26.pkg.json
-rw-r--r-- 1 jenkins jenkins       135 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jre_x64_mac_hotspot_2021-01-05-20-26.pkg.sha256.txt
-rw-r--r-- 1 jenkins jenkins     19699 Jan  7 09:44 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jre_x64_mac_hotspot_2021-01-07-08-10.pkg.json
-rw-r--r-- 1 jenkins jenkins       135 Jan  7 09:43 jdk15u/jdk15u-mac-x64-hotspot/workspace/target/OpenJDK15U-jre_x64_mac_hotspot_2021-01-07-08-10.pkg.sha256.txt
```
I'll reopen this until we've cleared them all up

**Comment by adamfarley** [comment]
Goot catch Stewart. [Here's an extra PR to remove the json and sha256 files as well.](https://github.com/AdoptOpenJDK/openjdk-build/pull/2363)
