### ISSUE TITLE
dragonwell8 requires jdk8 bootjdk

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2353]
dragonwell8 jdk8 requires a jdk8 bootjdk as it makes use of "::new" operator only found in jdk8+:
```
15:53:41  ## Starting langtools
15:53:42  Compiling 2 files for BUILD_TOOLS
15:53:43  e:\jenkins\tmp\workspace\build\src\langtools\src\share\classes\com\sun\tools\javac\file\ZipFileIndexCache.java:55: error: ')' expected
15:53:43                      .getFieldValue(ZipFileIndexCache.class, "sharedInstance", ZipFileIndexCache::new);
15:53:43                                                                                                 ^
15:53:43  e:\jenkins\tmp\workspace\build\src\langtools\src\share\classes\com\sun\tools\javac\file\ZipFileIndexCache.java:55: error: illegal start of expression
15:53:43                      .getFieldValue(ZipFileIndexCache.class, "sharedInstance", ZipFileIndexCache::new);
15:53:43                                                                                                  ^
```
dragonwell commit: https://github.com/alibaba/dragonwell8_langtools/commit/d09c9011a749833144a112172516274b50e4be5e

**Comment by sxa** [comment]
It requires a Dragonwell8 boot JDK, and the builds should be configured to pick that up - it's a mistake if it isn't ...

**Comment by andrew-m-leonard** [comment]
@sxa thanks. ah, ok it looks like the dragonwell11 builds are using the "dragonwell" label, but jdk8 is not hence it's picking any windows node... ok i'll create a PR to fix

**Comment by sxa** [comment]
I want to fix it so that we don't have to lock it but that may do in the mean time. I'd hope it would fail if it couldn't find the right one though so it's a worry if it doesn't abort

**Comment by andrew-m-leonard** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2354

**Comment by andrew-m-leonard** [comment]
It will now be consistent with jdk11
