### ISSUE TITLE
create_installer_mac timing out while Queueing

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2355]
It seems the create_installer_mac can get timed out while waiting in Queueing, which can easily happen if the installer node is busy build/testing...
Not sure we should be timing this out while Queuing, only when actually running the installer...?
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-hotspot/824/console

**Comment by karianna** [comment]
Did this get fixed by #2356 ?

**Comment by andrew-m-leonard** [comment]
Yes fixed
