### ISSUE TITLE
git-hg-jdk11u mercurial to git mirror not creating _adopt tags any more

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2361]
The git-hg-jdk11u mirror should create the <tag>_adopt tags in the mirror "release" branch.
This is failing due to the tag sorting going wrong with jdk-11.0.9.1 issue...

**Comment by sxa** [comment]
The mirroring machine was switched yesterday as it was hosted on a godaddy server and therefore is soon to be decomissioned. Is this is a new issue (in the last 24 hours)? The reference to jdk-11.0.9.1 suggests that it is not new.

Presumably this will be a bllcker for the quarterly release this month?

**Comment by andrew-m-leonard** [comment]
It's been like that since 11.0.9.1, we haven't noticed as the nightlies build dev. I only noticed from doing the "Release" test PR.

**Comment by andrew-m-leonard** [comment]
The current mirror sort logic thinks 11.0.9.1 is the latest tag, I need to update the logic like we did in sbin/build.sh

**Comment by sxa** [comment]
Excellent - I'll leave it with you then (needed to verify it wasn't something as a result of this week's changes)

**Comment by andrew-m-leonard** [comment]
Fixed by: https://github.com/AdoptOpenJDK/openjdk-build/pull/2364
