### ISSUE TITLE
bootjdk download from API intermittently failing

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2366]
```
23:30:55  + ./build-farm/make-adopt-build-farm.sh
23:30:55  BUILD TYPE: 
23:30:55  VERSION: jdk15u
23:30:55  ARCHITECTURE s390x
23:30:55  VARIANT: hotspot
23:30:55  OS: linux
23:30:55  SCM_REF: 
23:30:55  Detecting boot jdk for: jdk15u
23:30:55  Found build version: 15
23:30:55  Required boot JDK version: 14
23:30:55  Downloading GA release of boot JDK version 14...
23:30:55  
23:30:55  gzip: stdin: unexpected end of file
23:30:55  tar: Child returned status 1
23:30:55  tar: Error is not recoverable: exiting now
23:30:55  Downloading GA release of boot JDK version 14 failed.
23:30:55  Attempting to download EA release of boot JDK version 14 ...
23:30:56  
23:30:56  gzip: stdin: unexpected end of file
23:30:56  tar: Child returned status 1
23:30:56  tar: Error is not recoverable: exiting now
```
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-s390x-hotspot/156/console

**Comment by andrew-m-leonard** [comment]
These all failed at the start of jdk15 build pipeline, at exactly 23:30, could it be too many requests all at the same time?

**Comment by sxa** [comment]
Can you give the list of machines (or at least the jobs) that this is happening on?

**Comment by andrew-m-leonard** [comment]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-aix-ppc64-hotspot/165/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-linux-s390x-hotspot/156/console
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk15u/job/jdk15u-mac-x64-openj9-macosXL/163/console

**Comment by andrew-m-leonard** [comment]
Wondering if this is related? https://github.com/AdoptOpenJDK/openjdk-build/issues/1450#issuecomment-756835783
As API forards to the github API binaries URL

**Comment by karianna** [comment]
CC @johnoliver JIC this triggers any thinking with your investigation

**Comment by sxa** [comment]
NOTE: I've added the additional boot JDKs onto the zLinux build machines so those should no longer try to download. I suggest we make sure that is done universally. We can progress in https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/341

**Comment by andrew-m-leonard** [comment]
We've not seen this for a while now, any further api work can continue in https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/341
