### ISSUE TITLE
Geotrust SSL cert expired and need a deploy of new one

### ISSUE THREAD

**Issue by borja44** [AdoptOpenJDK/openjdk-build#2380]
Dear heroes,

Could you please rebuild your openjdk11 image for having the latest Geotrust certificate packaged into your docker image and then deploy it into https://hub.docker.com/r/adoptopenjdk/openjdk11

![image](https://user-images.githubusercontent.com/10860118/104489673-3115c180-55d0-11eb-9431-1ad1698184ab.png)

The certificate needs to be added to the keystore

New Certificate is attached as zip.

[GeoTrust TLS DV RSA Mixed SHA256 2020 CA-1.zip](https://github.com/AdoptOpenJDK/openjdk-build/files/5810294/GeoTrust.TLS.DV.RSA.Mixed.SHA256.2020.CA-1.zip)

Thanks in advance

Best Regards,
Borja

**Comment by aahlenst** [comment]
What exactly are you trying to do that does not work and where does that expired certificate come from? The screenshot doesn't look like a root or intermedia CA certificate.

If it's about the trust store bundled with OpenJDK, we're not the right place to complain. We do not have a trusted CA program. And even if we had one, we would only include certificates directly received from the respective CA. Late next week or early in the week after the next, AdoptOpenJDK 11.0.10 comes out including new container images that have a refreshed trust store. That's all we can offer in that case.

**Comment by segator** [comment]
Same issue here.
missing intermediate cert --> http://crl3.digicert.com/GeoTrustTLSDVRSAMixedSHA2562020CA-1.crl
is installed OS level but seems not on the java keystore.

Thanks,
Isaac

**Comment by aahlenst** [comment]
@segator Try any nightly build and report back: https://adoptopenjdk.net/nightly.html.

**Comment by aahlenst** [comment]
The information provided here is not enough for a proper diagnosis. Please describe at least what you're trying to do (for example: "Connect with Java client to https://example.com/").

https://www.geotrust.com/resources/root-certificates/ lists the GeoTrust root certificates. "GeoTrust RSA CA 2018" is not listed there and also not on the list of expired roots: https://www.geotrust.com/resources/root-certificates/retired.html. It's also too short lived for a root certificate. It would also be the shortest living intermediate CA certificate that I've ever seen. So my best guess is that it is a chain certificate that needs to be embedded on the server and served together with the server's certificate to be trusted by the client. In that case it would be a server misconfiguration. Please check your server with https://www.ssllabs.com/ssltest/.

**Comment by segator** [comment]
HI @aahlenst  you are right, after embeding this "short live" intermediate cert on the server all works fine, is that best practices for intermediate cert? I supose we are fine to close the issue.

Thanks 👍

**Comment by borja44** [comment]
> HI @aahlenst you are right, after embeding this "short live" intermediate cert on the server all works fine, is that best practices for intermediate cert? I supose we are fine to close the issue.
> 
> Thanks 👍

Yes, thanks, close the issue

**Comment by aahlenst** [comment]
> Is that best practices for intermediate cert?

Your CA usually tells you what to do and even includes chain certificates in the PEM or PFX file you receive. AFAIK certbot (the tool for Let's encrypt) does that automatically, too. Nginx, Apache and friends all have instructions that explain how to serve intermediate certificates.

Let's Encrypt has a nice illustration of their chain of trust: https://letsencrypt.org/certificates/. Let's Encrypt R3 comes as part of the certificate you install on the server and isn't embedded in trust stores.
