### ISSUE TITLE
Add support for macos/aarch64 to the build pipelines

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2383]
Suggest that since this is currnetly pre-release code and not in the mainlines we'd need to point it at https://github.com/openjdk/aarch64-port/tree/jdk-macos if we wanted to run it, but we should get the support in there. Similar to Linux/riscv64 and Windows/aarch64 we expect that this will be a cross-compile build for now, so will need to make use of the new job we have that runs the binary to capture the `java -version` output on a diferent machine from where it is built.

**Comment by gdams** [comment]
Work is complete - closing
