### ISSUE TITLE
Dragonwell nightly builds not detecting correct version tag

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2385]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-dragonwell/34/consoleFull

The jdk binary contains a detected jdk path of jdk-11.0.8+10, instead of the latest dragonwell tag determined from dragonwell-11.0.9.4_jdk-11.0.9+0

**Comment by andrew-m-leonard** [comment]
The sbin/build.sh tag logic is finding latest jdk tag:
 18:13:51  OpenJDK repo tag is jdk-11.0.8+10
Then building using build number "10"
The make config then creates a java -version string of jdk-11.0.9+10

**Comment by M-Davies** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2386
