### ISSUE TITLE
Update OpenJ11 builds to 1.1.1i

### ISSUE THREAD

**Issue by andrewRP01** [AdoptOpenJDK/openjdk-build#2389]
Update OpenJ9 builds to 1.1.1i #2297 incremented the version of openSSL to address security issues please could the same fix be rolled into the Java 11 builds

**Comment by AdamBrousseau** [comment]
I think there is some confusion here. The update would have been across all versions. J9 is the vm (OpenJ9) and does not refer to jdk9. Are you seeing a problem with the nightly builds?

**Comment by andrewRP01** [comment]
All of the JDK 9 images had their Open SSL versions updated but this has not affected the Java 11 builds i.e., https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jdk/alpine/Dockerfile.hotspot.releases.full

**Comment by AdamBrousseau** [comment]
Jdk9 is out of support for at least 2 years. I'm guessing you're looking for an updated jdk11 docker image. I'm not sure how often these are refreshed. But if you're not seeing 1.1.1i then I would have to guess they are only updated for releases. If that is the case then they should be rebuilt this week starting tomorrow.

**Comment by sxa** [comment]
@andrewRP01 The changes to OpenSSL are only relevant for the OpenJ9 variant as they specifically reship a version of OpenSSL on some platforms (Not Linux). HotSpot does not, so the PR you reference is not applicable. You will be seeing whichever version is supplied with the operating system in the Docker container, which will be supported by the container's distribution (Alping in this case)

Where have you seen that JDK9 has been updated? As Adam says we have not done any updates, build, or releases of JDK9 for a long time (But we do ship builds of 8, 11, and 15 with the OpenJ9 VM)

**Comment by sxa** [comment]
I'm going to close this since it seems like a misunderstanding between "OpenJ11" (which does not exist) and "OpenJDK 11". If there is any further concern it can be re-opened.

**Comment by andrewRP01** [comment]
Hi apologise for any confusion we cracked the open the container and it contained libcrypto library and therefore definitely has openssl baked into the container. Please can you confirm whether I should reopen  this issue in the adoptopenjdk docker git repository https://github.com/AdoptOpenJDK/openjdk-docker ?

The specific container we are using is FROM adoptopenjdk/openjdk11:jre-11.0.9.1_1-alpine

**Comment by sxa** [comment]
That will presumably be a `libcrypto` provided and supported by the by the distribution (Alpine in your case) so unless it was an OpenJ9 JDK11 container it was not provided by AdoptOpenJDK and would therefore not be updated by us, therefore this is as designed
