### ISSUE TITLE
adoptopenjdk8-openj9 bulids failing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#239]
At least AIX and xlinux are failing today because a parameter of ` --with-jvm-variants=:server` is being passed in which causes a problem with an unrecognised argument:

`Running ./configure with arguments ' --with-update-version= --with-build-number= --with-boot-jdk=/home/bootjdk/j2sdk-image/ --with-jvm-variants=:server --with-cacerts-file=/ramdisk0/build/workspace/openjdk8_openj9_build_ppc64_aix/cacerts_area/security/cacerts --with-alsa=/ramdisk0/build/workspace/openjdk8_openj9_build_ppc64_aix/alsa-lib-1.0.27.2 --with-freemarker-jar=/ramdisk0/build/workspace/openjdk8_openj9_build_ppc64_aix/freemarker-2.3.8/lib/freemarker.jar --with-x=/usr/include/X11 --with-debug-level=release --with-milestone=fcs --with-jobs=5 --with-memory-size=18000 --with-cups-include=/opt/freeware/include --with-extra-ldflags=-lpthread --with-extra-cflags=-lpthread --with-extra-cxxflags=-lpthread DF=/usr/sysv/bin/df'``

`checking which variants of the JVM to build... configure: error: The available JVM variants are: server, client, minimal1, kernel, zero, zeroshark, core`

May have been related to the change which went in at https://github.com/AdoptOpenJDK/openjdk-build/commit/050208136136b46f22288d4db4110409d3260e46

**Comment by adamfarley** [comment]
I found the problem. Here's the fix:

https://github.com/AdoptOpenJDK/openjdk-build/pull/240

**Comment by adamfarley** [comment]
Basically build.sh was ignoring the jvm_variant value given to it by makejdk.sh. My fix caused it to start paying attention, which revealed the bug. I've now fixed the bug that was exposed by my fix, and things should be ok once the aforementioned PR is merged.
