### ISSUE TITLE
Builds for jdk15 finished at the OpenJ9 project (after 15.0.2)

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#2391]
Just FYI. As of the release of 15.0.2, the OpenJ9 project will no longer be building jdk15, instead starting on regular builds of jdk16. No further changes will be made for the jdk15 version. This means jdk15 will start to rot and once there is some breaking change made for the other versions, jdk15 will no longer be build-able.

**Comment by pshipton** [comment]
@andrew-m-leonard @lumpfish fyi

**Comment by pshipton** [comment]
I didn't actually mean to create this with a `buildbreak` label, nothing is broken atm.

**Comment by sxa** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2403
