### ISSUE TITLE
jdk16-windows-aarch64-hotspot : IOException: Cannot run program "nohup"

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2407]
https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/cross-compiled-version-out/115/console
```
Caused: java.io.IOException: Cannot run program "nohup" (in directory "C:\Users\George\Jenkins\workspace\build-scripts\utils\cross-compiled-version-out\OpenJDKBinary"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
```

**Comment by gdams** [comment]
fixed, I didn't add git bash unix tools to the system PATH

**Comment by sxa** [comment]
I didn't think we normally did that on our systems - shouldn't that be picked up through cygwin?

**Comment by gdams** [comment]
I don't have cygwin installed on that machine. In fact it has nothing installed on it other than Java and Git Bash.
