### ISSUE TITLE
AIX builds seem relatively slow

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#241]
With the builds using a ramdisk and I believe using multi-core machines it's surprising to see that they are taking an hour to build compared to around 20 minutes or so on other platforms. Would be worth investigating if there are any other actions we can take to improve the performance since it significantly slows down the execution of the build pipeline

**Comment by karianna** [comment]
@sxa555 Is this still an issue?

**Comment by sxa555** [comment]
They are still slow compared to almost everything other than arm32, but it's no causing us any major problems at the moment, so let's clear it off the books for now.
