### ISSUE TITLE
Bug with RELEASE file for x86 version of OpenJ9 

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/openjdk-build#2412]
Hello!<br>Maybe all these my reports are a bit annoying, ...

But there is another bug with `release` file.<br>For x86 version of OpenJ9 variant, it contains `HEAP_SIZE="Large"` , while x86 version has only `normal` heap. 

Probably this is a minor bug in https://github.com/AdoptOpenJDK/openjdk-build/pull/2049 (?? not sure).
I also did the very same error in my updater in the past - because presence of `bin/default` dir for openj9-x64 means **large** heap, but in the same time for openj9-x86 it means **normal** heap. 

<hr>

Original report: tushev/aojdk-updatewatcher/issues/8

Contents of `release` file for `OpenJDK8U-jre_x86-32_windows_openj9_8u275b01_openj9-0.23.0`:
```
JAVA_VERSION="1.8.0_275"
OS_NAME="Windows"
OS_VERSION="5.1"
OS_ARCH="i586"
SOURCE=" .:OpenJDK: b52d2ff7ee:OpenJ9: 0394ef754:OMR: 582366ae5:"
IMPLEMENTOR="AdoptOpenJDK"
BUILD_SOURCE="git:5ba48d95"
FULL_VERSION="1.8.0_275-b01"
SEMANTIC_VERSION=""
BUILD_INFO="OS: Windows Server 2012 R2 Version: 6.3"
JVM_VARIANT="Openj9"
JVM_VERSION="openj9-0.23.0"
HEAP_SIZE="Large"
IMAGE_TYPE="JRE"
```

**Comment by aahlenst** [comment]
@austin0 agreed to have a look, thanks.
