### ISSUE TITLE
Add nightly build support for BishengJDK-11 risc-v

### ISSUE THREAD

**Issue by feilongjiang** [AdoptOpenJDK/openjdk-build#2420]
Hi, I'm a member of the RISC-V JDK development team from Huawei. We are very interested in building and distributing binaries of RISC-V JDK via AdoptOpenJDK. 

BishengJDK RISC-V port was based on OpenJDK 11, here is our open-sourced repo on Gitee:  
BishengJDK-11 risc-v: https://gitee.com/openeuler/bishengjdk-11/tree/risc-v. For more information, please refer to the [WIKI](https://gitee.com/openeuler/bishengjdk-11/blob/risc-v/README.md).
Mirror on Github :  https://github.com/isrc-cas/bishengjdk-11-mirror

How should we get started? Is there anything we can do?

**Comment by sxa** [comment]
Do you usually cross-compile this code on another system, or build natively on a RISC-V system? (Our OpenJ9 RISC-V builds are currently cross-compiled)

**Comment by aahlenst** [comment]
@feilongjiang Welcome, great to have you here. There are various steps to take:

* Update the build scripts to that they can build your branch. See #2051 for an example.
* If needed, enhance the playbooks that we use to provision the machines (https://github.com/AdoptOpenJDK/openjdk-infrastructure), for example, if you need a custom boot JDK or special compiler. AFAIK we're already building OpenJ9 on RISC-V, so you might look for riscv pointers in the repository
* If you need special test setups, please get in touch with our testing folks in https://github.com/AdoptOpenJDK/openjdk-tests.
* For integration in Jenkins, creation of upload space, @gdams can help.
* We might need additional machine capacity (cloud or 19" rackmountable machines).
* Please state the current level of TCK compliance and what your plans are in that area (incl. upstreaming of the changes to OpenJDK). I assume this was already discussed, but having a public record would be helpful nonetheless.

**Comment by sxa** [comment]
So most of the changes to support it will be in this repository. If you search the code in this repository for `dragonwell` you'll get an idea of what's required (`BishengJDK` would be added as a variant in the same way as `dragonwell` is). That should show you where things like the repositories are set for each variant (I'd propose using your git mirror for easier integration at least to begin with):

- Which compiler you want to use (We use GCC7.5 on /most/ Linux builds at the moment)
- Decide what you want in the `java -version` output and other properties like `java.vendor`
- Determining the version numbers (See https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L132)

Once we know whether we're going to cross-compile (so we can determine where will be able to run them) then we can move forward on the script modifications. I assume the codebase as it is just now is able to be built cleanly and is reasonable stable in that respect?

**Comment by feilongjiang** [comment]
> Do you usually cross-compile this code on another system, or build natively on a RISC-V system? (Our OpenJ9 RISC-V builds are currently cross-compiled)

We have tested cross-compile on x86 and native build on HiFive Unleashed with fedora risc-v (with gcc 10.2, native build usually cost a long time).

**Comment by sxa** [comment]
Sounds like your preference would be to do the same as we do for OpenJ9 then and use a cross-compile environment. That sounds good to me for consistency.

https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-riscv64-openj9/266/consoleFull is a log from one of out OpenJ9 cross-compiled builds so there are a couple of differences (as part of the process we capture the output from `java -version` so we copy it across to a native machine - an Unleashed board like yours - to do that when we're cross-compiling)

The RISC-V cross-compiler we have at the moment on our machines is `9.2.0` so unless there's something that specifically needs 10.2 I'd probably start with that and then potentially move later if we have a reason to, if that is ok for you.

**Comment by feilongjiang** [comment]
@sxa Sorry for the description is not clear enough,  GCC `10.2.0` is needed by the native build (with GCC `9.2.0`, cc1plus crashed when building JDK natively), `9.2.0` is ok for cross-compile. 
By the way, is there any test after the building finished?

**Comment by sxa** [comment]
> By the way, is there any test after the building finished?

Only the basic `java -version` is run on every build, but we have a **very** large set of test suites that we can run that we can look at later (See the [openjdk-tests](https://github.com/AdoptOpenJDK/openjdk-tests) repository as a starting point, although our ability to run those is obviously limited by our capacity on the real RISC-V hardware so we may not be able to regularly run all of them :-)

**Comment by feilongjiang** [comment]
> > `9.2.0` is ok for cross-compile
> 
> Thanks for clarifying - it sounds like our existing cross-compile environment should be ok :-)
> 
> > By the way, is there any test after the building finished?
> 
> Only the basic `java -version` is run on every build, but we have a **very** large set of test suites that we can run that we can look at later (See the [openjdk-tests](https://github.com/AdoptOpenJDK/openjdk-tests) repository as a starting point, although our ability to run those is obviously limited by our capacity on the real RISC-V hardware so we may not be able to regularly run all of them :-)

Sounds great! So maybe I should update the script first to make the building works😀.

**Comment by sxa** [comment]
That's certainly the first step we'll need, yes. It'll be a multi-stage process to get it working through all stages:

- [openjdk-build](https://github.com/AdoptOpenJDK/openjdk-build) changes to make it build on our machines in our jenkins with our scripts
- [openjdk-tests](https://github.com/adoptopenjdk/openjdk-tests) (may include other test repositories) to get the test jobs available
- [openjdk-api-v3](https://github.com/adoptopenjdk/openjdk-api-v3) to make the resulting nightly builds available through the API
- [openjdk-website](https://github.com/AdoptOpenJDK/openjdk-website/) (which uses the API to show the buids on the website
- [openjdk-installer](https://github.com/AdoptOpenJDK/openjdk-installer) (We optionally release rpm/deb versions in our yum/apt repositores

This looks like a lot of things, but the changes aren't too complicated ... Assuming you know where to make them. I'm very keen to make sure we capture properly what's involved in all of these as a "new variant" FAQ because I don't think it's been documented in a consumable way in the past, so hopefully we can use the addition of BishengJDK11 to improve that :-)

**Comment by yadongw** [comment]
> * Please state the current level of TCK compliance and what your plans are in that area (incl. upstreaming of the changes to OpenJDK). I assume this was already discussed, but having a public record would be helpful nonetheless.

For some non-technical reasons, we can't be licensed to use the tck for the time being, but we're doing this through partners. We have submitted an application to the OpenJDK community for creating the riscv port project and received some committers' responses. We will continue to push forward the upstream process. See https://mail.openjdk.java.net/pipermail/porters-dev/2021-January/000672.html.

**Comment by feilongjiang** [comment]
Can I cross-compile openj9 riscv64 by `makejdk-any-platform.sh`? Seems there is no option to set the target architecture.

**Comment by aahlenst** [comment]
Seems not to be super friendly. https://github.com/AdoptOpenJDK/openjdk-build/blob/4df4d1af9d0996fb1cdcaa75e155b0c96ee1fd98/pipelines/jobs/configurations/jdk11u_pipeline_config.groovy#L167_L173 shows the required arguments. And there's also https://github.com/AdoptOpenJDK/openjdk-build/blob/f68e90d8daef1cc597307b96dfc22cd68faf3aba/build-farm/platform-specific-configurations/linux.sh#L158-L174. I don't know how much you have to define from there.

**Comment by sxa** [comment]
Reopening this since it's not in the nightly builds yet (The two PRs above this should be adequate though)

**Comment by karianna** [comment]
@sxa PRs are closed - this OK to close as well?

**Comment by sxa** [comment]
Yes I think it's working ok now based on checking it earlier today, so I'll tentatively claim success and close
