### ISSUE TITLE
FYI some additional OpenJ9 builds are now using cmake

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#2424]
FYI additional OpenJ9 build are now using cmake by default (unless disabled in configuration). Not sure this affects anything at Adopt, considering all jdk11 builds already use cmake.

https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/474 - jdk8, all Linux, AIX, Mac
https://github.com/ibmruntimes/openj9-openjdk-jdk16/pull/11 - jdk16, all Linux, Mac
https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/276 - jdk17, all Linux, Mac

**Comment by sxa** [comment]
This will impact is significantly given that we know `cmake` builds use significantly more disk space (@andrew-m-leonard have you got the issue/comment where we looked at this - couldn't find it to link from here.
We have https://github.com/AdoptOpenJDK/openjdk-build/pull/2416 which will mitigate that but it is not yet merged,

**Comment by pshipton** [comment]
Well the jdk16, jdk17 changes occurred on Friday. The jdk8 change only occurred today.

**Comment by andrew-m-leonard** [comment]
@sxa https://github.com/AdoptOpenJDK/openjdk-build/issues/2299#issuecomment-748177179

**Comment by sxa** [comment]
This is implemented now but was only ever "for information" I believe. Closing
