### ISSUE TITLE
OpenJ9 heads up, mixed refs builds soon to be enabled for jdk11

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#2426]
FYI that OpenJ9 is soon ready to switch to use mixed refs builds for jdk11. These builds combine compressed and XL into a single build. Once the mixed refs build is enabled, the platform doesn't require a separate XL build.

The mixed ref build can be enabled via configure with the option `--with-mixedrefs`. The OpenJ9 project has enabled them for jdk11 nightly testing. Atm there is a problem to be resolved, https://github.com/eclipse/openj9/issues/11819, but once this is resolved then AdoptOpenJDK should enable these builds for jdk11 in time for the April 11.011 release.

Note a prereq to enabling mixed refs is cmake. Only jdk11 has cmake enabled for all platforms atm (see https://github.com/AdoptOpenJDK/openjdk-build/issues/2424).

**Comment by pshipton** [comment]
Note the mixed refs build could be enabled now for jdk11 if you like, but it will cause some special.system testing to fail as described in the previous comment. I will update here when the problem is resolved.

**Comment by smlambert** [comment]
We are not running special.system target currently (as its a lot of extra modes / resources) so we should be good to switch and not see those test failures.

**Comment by AdamBrousseau** [comment]
I can open ad PR the build script changes as I have already tested them. I assume there will be more changes required for website etc.

**Comment by AdamBrousseau** [comment]
I think work is complete.

**Comment by pshipton** [comment]
Yup, mixed refs builds were enabled by default for all platforms and versions. See https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/382 and the referenced PRs.
