### ISSUE TITLE
AdoptOpenJDK8 with OpenJ9 builds on Windows are failing

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#243]
Possible machine setup issue according to Peter Shipton - instructions for setting up an AO8/J9 Windows system are at: https://github.com/SueChaplain/openj9/blob/7ecf26014db64bb18cc23b7e214a48d3853ddbb6/buildenv/Build_Instructions_V8.md#windows

Ref: https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_windows/

```
copyright.c
wdbgext.c
wdbgglue.c
Microsoft (R) Windows (R) Resource Compiler Version 6.1.7600.16385

Copyright (C) Microsoft Corporation.  All rights reserved.


c:\users\jenkins\jdk8_j9\openjdk\build\windows-x86_64-normal-server-release\vm\windbg\wdbgext.h(52) : fatal error C1083: Cannot open include file: 'wdbgexts.h': No such file or directory
: integer expression expected
Built the JDK!

ls: cannot access '/cygdrive/c/Users/jenkins/jdk8_j9/openjdk/build/*/images/j2sdk-image': No such file or directory
'' does not exist, build might have not been successful or not produced the expected JDK image at this location.
Archiving artifacts
ERROR: No artifacts found that match the file pattern "OpenJDK*.zip, openjdk_*.zip". Configuration error?
ERROR: ‘OpenJDK*.zip’ doesn’t match anything
Build step 'Archive the artifacts' changed build result to FAILURE
Finished: FAILURE
```

**Comment by sxa555** [comment]
@vsebe is this an error you're familiar with (I heard a rumour you'd gone through the pain of setting up a Windows build system!)

**Comment by vsebe** [comment]
@sxa555 Please check if the the Windows SDK 7 Debugging tools are installed and the INCLUDE and LIB environment variables have been updated (see https://github.com/SueChaplain/openj9/blob/7ecf26014db64bb18cc23b7e214a48d3853ddbb6/buildenv/Build_Instructions_V8.md#1-prepare-your-system-2)

The error is:
```
c:\users\jenkins\jdk8_j9\openjdk\build\windows-x86_64-normal-server-release\vm\windbg\wdbgext.h(52) : fatal error C1083: Cannot open include file: 'wdbgexts.h': No such file or directory
: integer expression expected
Built the JDK!
```

**Comment by bblondin** [comment]
We are looking into ways to resolve this.
The issue is that this code is utilizing a SDK debugger. That was developed by the vendor under MSDN license. 

Currently at Adopt, we don't have the necessary license agreement in place to allow for its use.
We are working with Microsoft to aquire the correct licensing, until such time this code will fail.

**Comment by karianna** [comment]
@bblondin Let me know if you need any help convincing the MS folks - we know their Java team pretty well.

**Comment by bblondin** [comment]
Thanks @karianna _by we I meant_ @gdams

**Comment by gdams** [comment]
We should hopefully have an agreement with Microsoft shortly to have some machines

**Comment by sxa555** [comment]
@bblondin Do you believe there's an issue with using the download from https://www.microsoft.com/download/confirmation.aspx?id=8279 ? (Linked from https://github.com/SueChaplain/openj9/blob/7ecf26014db64bb18cc23b7e214a48d3853ddbb6/buildenv/Build_Instructions_V8.md#windows)

**Comment by bblondin** [comment]
@sxa555 I would err on the side of caution. A Visual Studio (MSDN) subscription appears to be required or at least that all users need to join the Dev Essentials program. There would have to be someway to track and ensure users have the correct approval to use it. I would defer this decision to Microsoft and/or legal.

**Comment by DanHeidinga** [comment]
@bblondin Can you point me at a link that indicates that?  

I was able to download the files (on my mac) without being prompted for any license / MSDN subscription.  Does the prompt occur during installation?

**Comment by sxa555** [comment]
MSDN-only downloads are hidden behind a log-in to the MSDN site, so this file (and I'm assuming it's what we would need to resolve the compile issue) is definitely available outside that.

**Comment by sxa555** [comment]
Agreed on this week's infrastructure call that we will look at downloading that package from Microsoft within the playbook to resolve this.

**Comment by sxa555** [comment]
I've downloaded it to experiment with, but it's not at all obvious how you can install it silently (i.e. in a form suitable for a playbook). Might be sensible to install it manually for now on the build machines if it's not simple to automate.

FYI @pnstanton - if you get a minute ;-)

**Comment by sxa555** [comment]
@vsebe I can't install the debugging tools as it insists that I uninstall the VC2010 redistributable (I hit this issue: https://support.microsoft.com/en-gb/help/2717426/windows-sdk-fails-to-install-with-return-code-5100) which I'm not overly keen on doing on the production machine right now.

**Comment by vsebe** [comment]
@sxa555 have you tried to install only the Debugging Tools?

**Comment by sxa555** [comment]
Yes

**Comment by sxa555** [comment]
If I install it onto another clean windows box and copy across the debugging SDK directory and point INCLUDE at it it seems to run through ok, but that's obviously not a sensible solution going forward.

I also had to do the same PATH fix I had to do for AO9/J9 (Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/267)

**Comment by vsebe** [comment]
@sxa555  it looks the PATH was missing C:\cygwin64\bin. 
The ansible playbook adds cygwin to the PATH see [cygwin role](https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/master/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/cygwin/tasks/main.yml)).

**Comment by sxa555** [comment]
See also https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/300

**Comment by sxa555** [comment]
Default install of the SDK appears to put `wdbgext.h` in place based on my installs for the openj9 machine

**Comment by sxa555** [comment]
The silent install parameters in https://support.microsoft.com/en-us/help/2498225/installing-windows-sdk-7-1-in-silent-mode don't appear to work but that might be due to the fact it pops up a dialog about it not liking the .net framework version.

**Comment by karianna** [comment]
Resolved.
