### ISSUE TITLE
OpenJ9 rc2 build has incorrect version information

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#244]
This build OpenJDK8-OPENJ9_x64_Linux_20180203.tar.gz has the following -version output. The OpenJDK build information is incorrect, I believe it should look more like `(build 1.8.0_162-b12)` and the configure parameter `--with-milestone=fcs` is required to change this.
@sxa555 @andrew-m-leonard 

openjdk version "1.8.0"
OpenJDK Runtime Environment (build 1.8.0-jenkins_2018_03_02_16_02-b00)
Eclipse OpenJ9 VM (build openj9-0.8.0-rc2, JRE 1.8.0 Linux amd64-64 Compressed References 20180302_106 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ed7328e5 based on jdk8u162-b12)

**Comment by karianna** [comment]
See #93 as an FYI

**Comment by andrew-m-leonard** [comment]
I have just done a build locally with a configure of:
bash ./configure --with-freemarker-jar=/home/admin/freemarker-2.3.8/lib/freemarker.jar --with-milestone=fcs
and I get a correct version output:
openjdk version "1.8.0_152"
OpenJDK Runtime Environment (build 1.8.0_152-b16)
Eclipse OpenJ9 VM (build openj9-0.8.0-rc2, JRE 1.8.0 Linux amd64-64 Compressed References 20180306_000000 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ed7328e5f5 based on jdk8u152-b16)

This would suggest the Adopt build script is not specifying --with-milestone=fcs correctly

**Comment by sxa555** [comment]
It's definitely getting as far as the top level `makejdk-any-platform.sh` based on https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/107/consoleFull - @adamfarley can you take a look and see why this may not be getting through properly, based on Andrew's comment above that it seems to work when you do it manually.

**Comment by sxa555** [comment]
The `--with-milestone=fcs` is definitely being passed in, but that doesn't appear to be setting the `OpenJDK Runtime Environment` line to what you're looking for - I've asked Adam to investigate further to see where that's being set.

**Comment by adamfarley** [comment]
Looks like the BUILD_TAG environment variable is the likely suspect here. Will see if we can blank it or ignore it.
```
BUILD_TAG
    String of "jenkins-${JOB_NAME}-${BUILD_NUMBER}". All forward slashes (/) in the JOB_NAME are replaced with dashes (-). Convenient to put into a resource file, a jar file, etc for easier identification.
```

**Comment by andrew-m-leonard** [comment]
The problem is caused by the Adopt build.sh scripts adding "--with-update-version= --with-build-number=" to the configure command. The updates to the extensions configure script will automatically put the correct release build and update versions in...

**Comment by adamfarley** [comment]
I've added a change to the build.sh script to avoid the problem Andrew mentioned above.

https://github.com/AdoptOpenJDK/openjdk-build/pull/246

@sxa555 - Can you review, when you have a moment?

**Comment by adamfarley** [comment]
Here's a build to check the change worked:

https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/110/

Won't exist for about 20 mins, as a timer build is in progress.

**Comment by adamfarley** [comment]
The change didn't work due to a typo. Here's the fix: https://github.com/AdoptOpenJDK/openjdk-build/pull/247

**Comment by adamfarley** [comment]
Ok, running the build again.

https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/111/console

**Comment by adamfarley** [comment]
@sxa555 @pshipton @andrew-m-leonard All seems fine now. :)

```
openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0-rc2, JRE 1.8.0 Linux amd64-64 Compressed References 20180306_111 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ed7328e5 based on jdk8u162-b12)
```

**Comment by sxa555** [comment]
Re-running nightly pipielines now to pick iup the fix.
