### ISSUE TITLE
Azure build agents fail to download docker build image (unauthorized)

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#2440]
Thank you for reporting a broken build! Please fill in the following details:
- **Jenkins link to the failing log:**
- **Which platforms (OS+arch) are affected:** All xLinux on tonight's JDK8 builds
- **If you look at the historic logs, does the problem appear to be specific to one machine?** No - my local machine can pull the image without problems
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))** n/a

Log: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-hotspot/901/console
```
18:10:28  + docker pull adoptopenjdk/centos6_build_image
18:10:28  Using default tag: latest
18:10:30  Error response from daemon: unauthorized: authentication required
```
Slightly different on the OpenJ9 ones: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9-linuxXL/lastFailedBuild/console
```
18:10:41  + docker build -t build-image --build-arg image=adoptopenjdk/centos6_build_image -f pipelines/build/dockerFiles/cuda.dockerfile .
18:10:41  Sending build context to Docker daemon  17.66MB

18:10:41  Step 1/6 : ARG image
18:10:41  Step 2/6 : FROM $image
18:10:44  latest: Pulling from adoptopenjdk/centos6_build_image
18:10:44  831490506c47: Pulling fs layer
18:10:44  c388bbfe10ff: Pulling fs layer
18:10:44  3f7414369ae3: Pulling fs layer
18:10:44  6d0337ea7090: Pulling fs layer
18:10:44  cacbb7d741ce: Pulling fs layer
18:10:44  1cb0e6973b2f: Pulling fs layer
18:10:44  ad5c9cab7f0c: Pulling fs layer
18:10:44  0a91c7f86643: Pulling fs layer
18:10:44  cacbb7d741ce: Waiting
18:10:44  0a91c7f86643: Waiting
18:10:44  ad5c9cab7f0c: Waiting
18:10:44  1cb0e6973b2f: Waiting
18:10:44  6d0337ea7090: Waiting
18:10:45  831490506c47: Downloading
18:10:45  3f7414369ae3: Verifying Checksum
18:10:45  3f7414369ae3: Download complete
18:10:45  6d0337ea7090: Download complete
18:10:46  1cb0e6973b2f: Verifying Checksum
18:10:46  1cb0e6973b2f: Download complete
18:10:46  ad5c9cab7f0c: Verifying Checksum
18:10:46  ad5c9cab7f0c: Download complete
18:10:46  0a91c7f86643: Verifying Checksum
18:10:46  0a91c7f86643: Download complete
18:10:48  c388bbfe10ff: Verifying Checksum
18:10:48  c388bbfe10ff: Download complete
18:11:15  cacbb7d741ce: Verifying Checksum
18:11:15  cacbb7d741ce: Download complete
18:11:44  unauthorized: authentication required
```

**Comment by gdams** [comment]
Hmm, I thought that we could still do anonymous pull. Let me check the details of this

**Comment by AdamBrousseau** [comment]
Doesn't appear to be the same as #2323 (rate limit) but I thought it was worth mentioning.

**Comment by gdams** [comment]
We can easily add a login but I'm trying to avoid that approach as it requires everyone who uses our codebase to have a credential stored in jenkins with the same credential id as what we use.

**Comment by gdams** [comment]
Looking at https://status.docker.com/pages/history/533c6539221ae15e3f000031 it seems that the issue was upstream at dockerhub rather than with us. I've kicked off a build this morning and it seems fine
