### ISSUE TITLE
jdk8u-linux-aarch64-dragonwell fails: package com.alibaba.tenant does not exist

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2444]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-dragonwell/1/
```
02:26:12  Compiling 2 files for BUILD_TOOLS
02:26:14  /home/jenkins/workspace/build-scripts/jobs/jdk8u/jdk8u-linux-aarch64-dragonwell/workspace/build/src/langtools/src/share/classes/com/sun/tools/javac/file/ZipFileIndexCache.java:28: error: package com.alibaba.tenant does not exist
02:26:14  import com.alibaba.tenant.TenantContainer;
```

**Comment by sxa** [comment]
FYI @joeyleeeeeee97

**Comment by joeyleeeeeee97** [comment]
It seems to be the bootstrap image failed to be found, but I tested in local Jenkins that seemed to work.

Could we add 2 aarach64 workers from Alibaba and see how it goes?

**Comment by M-Davies** [comment]
Looks to be fixed now https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-dragonwell/
