### ISSUE TITLE
Setup jenkins job for synchronising openjfx

### ISSUE THREAD

**Issue by tiainen** [AdoptOpenJDK/openjdk-build#245]
Setup Jenkins job for synchronising the official OpenJFX repository with a repository at AdoptOpenJDK.

The [openjdk-jfx repository](https://github.com/AdoptOpenJDK/openjdk-jfx) at AdoptOpenJDK has been created to be kept in sync with the [OpenJFX mercurial repository](http://hg.openjdk.java.net/openjfx/jfx-dev/rt). It is the idea that the git repository can then be used for building and publishing new releases of JavaFX.

We've already managed to setup a similar situation at https://github.com/javafxports/openjdk-jfx. We used the scripts available here to do the initial setup and execute the actual synchronisation process.

For the initial setup step only, the setup.sh script was run as follows:

    $ setup.sh jfx jfx open-jfx/jfx-dev/rt

From then on, the update can be called as follows:

    $ update-without-modules.sh openjfx/jfx-dev/rt

As I understood, it is possible to setup a jenkins job to execute this synchronisation script.

**Comment by karianna** [comment]
Hi @tiainen - I'm working through the documentation to hopefully self service on the build farm (with the only blocker being available hosts.  The docs will be in the TSC repo when I'm done.

If you don't see updates there - please do ping me again.

**Comment by karianna** [comment]
@johanvos Can you comment on where we should build or bundle OpenJFK from?

**Comment by karianna** [comment]
I suspect we should actually pull directly from the OpenJFX folks and we should kill our repo.

Needs some discussion with @johanvos because of OpenJFX 8.

**Comment by aahlenst** [comment]
https://adoptopenjdk.net/faq.html#openjfxfaq
