### ISSUE TITLE
jdk11u-linux-aarch64-dragonwell : /usr/bin/bash: line 1: 41820 Illegal instruction 

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2454]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-dragonwell/2/console
```
18:16:31  Creating support/modules_libs/jdk.hotspot.agent/libsaproc.so from 7 file(s)
18:17:34  Compiling 4 files for BUILD_JIGSAW_TOOLS
18:17:34  /usr/bin/bash: line 1: 41820 Illegal instruction     (core dumped) /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-dragonwell/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/bin/java -Xms64M -Xmx1600M -XX:ThreadStackSize=1536 -XX:+UseSerialGC -Xms32M -Xmx512M -XX:TieredStopAtLevel=1 -cp /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-dragonwell/workspace/build/src/build/linux-aarch64-normal-server-release/buildtools/tools_jigsaw_classes --add-exports java.base/jdk.internal.module=ALL-UNNAMED build.tools.jigsaw.AddPackagesAttribute /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-dragonwell/workspace/build/src/build/linux-aarch64-normal-server-release/jdk > >(/usr/bin/tee -a /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-dragonwell/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/_packages_attribute.done.log) 2> >(/usr/bin/tee -a /home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-dragonwell/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/_packages_attribute.done.log >&2)
18:17:34  ExplodedImageOptimize.gmk:40: recipe for target '/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-dragonwell/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/_packages_attribute.done' failed
18:17:34  gmake[3]: *** [/home/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-aarch64-dragonwell/workspace/build/src/build/linux-aarch64-normal-server-release/jdk/_packages_attribute.done] Error 1
18:17:34  make/Main.gmk:411: recipe for target 'exploded-image-optimize' failed
18:17:34  gmake[2]: *** [exploded-image-optimize] Error 1
18:17:34  gmake[2]: *** Waiting for unfinished jobs....
```

**Comment by karianna** [comment]
@joeyleeeeeee97 FYI

**Comment by sxa** [comment]
FWIW I can build dragonwell JDK11 on my CentOS7/aarch64 machine [build-packet-centos74-armv8-1](https://ci.adoptopenjdk.net/computer/build-packet-centos74-armv8-1x) without issues - build log attached. Here is the version output:
[dragonwell11.log.gz](https://github.com/AdoptOpenJDK/openjdk-build/files/5997240/dragonwell11.log.gz)

```
=JAVA VERSION OUTPUT=
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment (Alibaba Dragonwell) (build 11.0.9+0-202102171622)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell) (build 11.0.9+0-202102171622, mixed mode)
=/JAVA VERSION OUTPUT=
```

**Comment by joeyleeeeeee97** [comment]
Could we restrict this on Alibaba's recently donated machines and see how it goes? Thanks

**Comment by sxa** [comment]
Hmmm it does seem to work on the alibaba machine based on https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-dragonwell/16/ which initially makes me wonder if there's any hard-ware specific assembler in there.

Running `java -version` from that JRE tarball on a couple of other machines gives me a crash on four different types of machine.

**Comment by sxa** [comment]
I now believe this to be happening due to the `-march=armv8.2-a+crypto` flag on the compiler options which is presumably generating some hardware-specific instructions

**Comment by sxa** [comment]
@joeyleeeeeee97 Is this locking to certain types of aarch64 hardware intentional?

**Comment by sxa** [comment]
Reopening until we know what we want to target

**Comment by joeyleeeeeee97** [comment]
@sxa  This is not intentional. I think we need to remove that.
```
-march=armv8.2-a+crypt
```

**Comment by sxa** [comment]
> We will alter this to-march=armv8.1 later

Would you expect `armv8.1` work on most aarch64 systems? I had a quick test and it still seemed to give the illegal instruction on one of my servers when built with that. I presume you've seen performance improvements from using th `v8.2` option.

Also is there a timeline for switching?

**Comment by joeyleeeeeee97** [comment]
@sxa  After an internal discussion, we decided to keep that `-march=armv8.2-a+crypto` and only support some aarch64 systems.
So I will create an issue to limit all Dragonwell build & test on these machines.

**Comment by sxa** [comment]
That limit has already been done in https://github.com/AdoptOpenJDK/ci-jenkins-pipelines/pull/61/files - I was expecting that to be temporary but sounds like it'll need to stay there. We will need to carefully consider at adopt what we call this version since it's not a straight aarch64 port and we don't want to give false hope to people which might result in extra bug reports (bearing in mind it doesn't work on the four other `aarch64` systems I've tried) FYI @AdoptOpenJDK/tsc @andrew-m-leonard

**Comment by sxa** [comment]
Hmmm 7260 passed on test-azure-2 (after the earlier reboot) ... Trying again at https://ci.adoptopenjdk.net/job/Grinder/7266/

**Comment by sxa** [comment]
Closing since the immediate problem has been solved but I'll raise another one to discuss naming of any builds that target the updated version of the architecture
