### ISSUE TITLE
Split out jenkins pipeline codebase from shell build scripts

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#2455]
I'd like to make the initial changes in the jenkins generator to start using the split out ci-jenkins-pipelines repo. https://github.com/AdoptOpenJDK/ci-jenkins-pipelines

Steps:
- [x] Create a release to backup before splitting: https://github.com/AdoptOpenJDK/openjdk-build/releases/tag/3.0.0
- [x] Mirror pipelines scripts over to ci-jenkins-pipelines
- [x] Update Git repo in build-pipeline-generator
- [x] Update Git repo in openjdk-build-pr-tester
- [x] Update Git repo in pipeline_jobs_generator_*
- [x] Trigger pipelines (should update the jobs to use the new source repo
- [x] Remove all pipeline code from openjdk-build https://github.com/AdoptOpenJDK/openjdk-build/pull/2463
- [x] Transfer any pipeline issues to ci-jenkins-pipelines
- [x] Manually patch any open PR's to ci-jenkins-pipelines

**Comment by sxa** [comment]
As per slack TSC discussion ([restricted](https://adoptopenjdk.slack.com/archives/GFBKQ5ZUN/p1612531431044100)) let's hold off on this until the 8u282 releases for the two ARM platforms have been shipped.

**Comment by gdams** [comment]
work is complete - closing
