### ISSUE TITLE
Expose failure command logs and openj9 archives/dumps for debugging purposes

### ISSUE THREAD

**Issue by M-Davies** [AdoptOpenJDK/openjdk-build#2461]
*Spawned from https://github.com/eclipse/openj9/issues/11902*

It would be useful to archive these in the form of jenkins artifacts or downloadable archives for debugging purposes

**Comment by keithc-ca** [comment]
@M-Davies Is this a sign that you're planning to tackle it shortly?

**Comment by M-Davies** [comment]
Probably not until https://github.com/AdoptOpenJDK/openjdk-api-v3/issues/206 is resolved. I'll reevaluate afterwards depending on how far the openjdk-build code split has gone by then

**Comment by andrew-m-leonard** [comment]
@M-Davies i'll pick this up
