### ISSUE TITLE
cacerts alias names changed with 11.0.10_9

### ISSUE THREAD

**Issue by veita** [AdoptOpenJDK/openjdk-build#2469]
**What are you trying to do?**
`keytool -list -v -storepass changeit -keystore jdk-11.0.10+9/lib/security/cacerts`

**Expected behaviour:**
See old-fashioned CA alias names like
```
Alias name: actalisauthenticationrootca [jdk]
Alias name: addtrustexternalca [jdk]
Alias name: addtrustqualifiedca [jdk]
Alias name: affirmtrustcommercialca [jdk]
Alias name: affirmtrustnetworkingca [jdk]
Alias name: affirmtrustpremiumca [jdk]
Alias name: affirmtrustpremiumeccca [jdk]
Alias name: amazonrootca1 [jdk]
Alias name: amazonrootca2 [jdk]
```

**Observed behaviour:**
Saw DN style CA alias names like
```
Alias name: c=bm,o=quovadis limited,ou=root certification authority,cn=quovadis root certification authority
Alias name: c=ch,o=swisssign ag,cn=swisssign gold ca - g2
Alias name: c=ch,o=swisssign ag,cn=swisssign silver ca - g2
Alias name: c=ch,o=wisekey,ou=oiste foundation endorsed,cn=oiste wisekey global root gb ca
Alias name: c=ch,o=wisekey,ou=oiste foundation endorsed,cn=oiste wisekey global root gc ca
Alias name: c=cn,o=china financial certification authority,cn=cfca ev root
Alias name: c=cn,o=guang dong certificate authority co.,ltd.,cn=gdca trustauth r5 root
Alias name: c=cn,o=unitrust,cn=uca extended validation root
Alias name: c=cn,o=unitrust,cn=uca global g2 root
```

I could not find anything about the intention of this change. Please clarify if this is a bug or not.

**Comment by karianna** [comment]
It's not a deliberate change on our part - CC @aahlenst as our certs guru :-)

**Comment by aahlenst** [comment]
https://blog.adoptopenjdk.net/2021/01/adoptopenjdk-8u282-11010-and-1502-available/, section "New Trust Stores".

**Comment by aahlenst** [comment]
To elaborate, the objective of the change wasn't to change aliases. We completely changed the source and how the trust store is generated. Changed alias names are a side effect. Alias names are somewhat arbitrary. For example, the trust stores generated by the various Linux distributions use different aliases.

**Comment by veita** [comment]
@aahlenst Thank you for the link and clarification.
