### ISSUE TITLE
Problem building OpenJDK 11 on Windows - Visual Studio 2017 not found

### ISSUE THREAD

**Issue by igorrogov** [AdoptOpenJDK/openjdk-build#2470]
Hello everyone,

I'm trying to build JDK 11 on Windows 10 using Visual Studio 2017, but it keeps telling that it cannot locate Visual Studio. I was hoping that you could point into the right direction on how to solve it. I understand that VS2017 should be supported, but perhaps I didn't install or configure something properly.

The main reason I'm doing that is I need debug symbols for a Windows hotspot version in order to debug some issue in my app. I know that there is a OpenJ9 version with debug symbols, but it doesn't work with my app, so I need a hotspot version.

Here is what I'm doing:
 - I'm doing everything in a Windows 10 Sandbox, just so not to clutter my main system.
 - Install Cygwin 64-bit. Install packages: autoconf, make, zip, unzip, wget, git
 - Download and unzip OpenJDK 11 to be used as a "boot JDK" - C:\jdk-11.0.10+9
 - Install MS Visual Studio Community 2017 (latest available version 15.9.33) using web installer. Select "Desktop Development with C++". Leave everything else by default. Launch it to verify that it's working.
 - Visual Studio is installed into default folder: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community`
 - Launch cygwin terminal and create a root folder: `mkdir /cygdrive/c/openjdk-src`
 - `cd /cygdrive/c/openjdk-src`
 - `git clone https://github.com/AdoptOpenJDK/openjdk-build`
 - `cd openjdk-build`
 - `./makejdk-any-platform.sh --jdk-boot-dir /cygdrive/c/jdk-11.0.10+9 --configure-args "--disable-warnings-as-errors --disable-ccache" --build-variant hotspot jdk11u`

It fails with this error:
```
configure: Found Visual Studio installation at /cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2017/Community using well-known name
configure: Found Microsoft Visual Studio 2017
configure: Trying to extract Visual Studio environment variables
'C:/Program' is not recognized as an internal or external command,
operable program or batch file.
configure: Setting extracted environment variables
checking for Visual Studio variables... ok
checking for cl... no
configure: error: Could not find a C compiler.
```

Please see attached the full output.

Now the question is: what am I doing wrong? Am I using the wrong version of VS? What version do you guys use on your build farm?

[full_output.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/5985644/full_output.txt)

**Comment by AdamBrousseau** [comment]
I think the issue is that you don't have shortnames configured. Basically it doesn't like the whitespace in "Program Files (x86)". There's a step in the Ansible playbook for setting it up.
https://github.com/AdoptOpenJDK/openjdk-infrastructure/blob/a1df08e8292891c8730aaf07b559e89a9e5399a8/ansible/playbooks/AdoptOpenJDK_Windows_Playbook/roles/Common/tasks/main.yml#L31
```
fsutil file setshortname \"C:\\Program Files (x86)\" \"PROGRA~2\"
```

**Comment by AdamBrousseau** [comment]
Also,
>OpenJ9 version with debug symbols, but it doesn't work with my app

If you're saying OpenJ9 does not work with your app you should open an [OpenJ9 Issue](https://github.com/eclipse/openj9/issues/new/choose)

**Comment by igorrogov** [comment]
Hi Adam,

Thanks a lot! That was it. I added these commands and now it seems to be working fine. I also needed to install Universal CRT SDK which was not installed by default.

```
fsutil behavior set disable8dot3 0
fsutil file setshortname "C:\Program Files (x86)" "PROGRA~2"
fsutil file setshortname "C:\Program Files (x86)\Microsoft Visual Studio" "MSVS~1"
fsutil file setshortname "C:\Program Files (x86)\Windows Kits" "WINKIT~1"
```

With regards to the OpenJ9 issue, yes, I plan to do that a bit later. Thanks.
