### ISSUE TITLE
Freemarker download url 404 not found

### ISSUE THREAD

**Issue by AdamBrousseau** [AdoptOpenJDK/openjdk-build#2472]
OpenJ9 builds have started failing trying to download freemarker from
https://downloads.apache.org/freemarker/engine/2.3.30/binaries/apache-freemarker-2.3.30-bin.tar.gz

https://github.com/AdoptOpenJDK/openjdk-build/blob/cd0cddc9eb9179c44f9c59477e127306e68520cc/sbin/prepareWorkspace.sh#L386

First noticed on JDK11 Linux x64

**Comment by sxa** [comment]
Fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/2475
