### ISSUE TITLE
freemarker 2.3.30 now replaced by 2.3.31

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2474]
All openj9 builds failed to download freemarker 2.3.30 as it has been removed and replaced by 2.3.31
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-linux-x64-openj9/245/console

**Comment by sxa** [comment]
Duplicate of https://github.com/AdoptOpenJDK/openjdk-build/issues/2472
