### ISSUE TITLE
OpenJDK8 doesn't work on Catalina

### ISSUE THREAD

**Issue by k7295** [AdoptOpenJDK/openjdk-build#2491]
After building the jdk8u in MacOS (lion, xcode4), I was trying to use the binaries in Catalina (10.15.7) and I get this issue
![unnamed](https://user-images.githubusercontent.com/15851474/108901489-8afea380-75e0-11eb-98a5-a4e403539be2.png)
Does anyone know how I can fix this problem?

**Comment by aahlenst** [comment]
You need to build with a newer Xcode, at least for Catalina, maybe for Mojave, too. https://github.com/AdoptOpenJDK/openjdk-jdk8u has the necessary patch on the branches dev and release. You can the do `bash ./configure --with-boot-jdk=/... --with-toolchain-type=clang --disable-zip-debug-info --disable-debug-symbols` and build as normal.

**Comment by k7295** [comment]
> You need to build with a newer Xcode, at least for Catalina, maybe for Mojave, too. https://github.com/AdoptOpenJDK/openjdk-jdk8u has the necessary patch on the branches dev and release. You can then do `bash ./configure --with-boot-jdk=/... --with-toolchain-type=clang --disable-zip-debug-info --disable-debug-symbols` and build as normal.

and how can I avoid this issue? 
![Screen Shot 2021-02-23 at 15 02 55](https://user-images.githubusercontent.com/15851474/108907822-3828ea00-75e8-11eb-8b27-a50228cd98b8.png)

**Comment by aahlenst** [comment]
Please re-read what I wrote. It's all in there.

**Comment by andrew-m-leonard** [comment]
I can build and run using Xcode 11.5 on MacOS 10.15.7

**Comment by k7295** [comment]
> I can build and run using Xcode 11.5 on MacOS 10.15.7

Do you build it using the sources from https://github.com/AdoptOpenJDK/openjdk-jdk8u or  hg.openjdk.java.net?

**Comment by andrew-m-leonard** [comment]
I'm using https://github.com/AdoptOpenJDK/openjdk-jdk8u dev branch

**Comment by k7295** [comment]
I'm getting this issue 
```
formssel.cpp:3399:8: error: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true [-Werror,-Wundefined-bool-conversion]
  if( !this ) return;
      ~^~~~
1 error generated.
make[6]: *** [../generated/adfiles/formssel.o] Error 1
```
using Catalina with Xcode 4.5

**Comment by andrew-m-leonard** [comment]
@k7295 you need to use:
```
make images COMPILER_WARNINGS_FATAL=false 
```
