### ISSUE TITLE
AIX openj9 build failure: File libjvm.so is not an archive file

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2492]
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/926/console
```
20:11:32  ar: 0707-108 File libjvm.so is not an archive file.
20:11:32  gmake[6]: *** [runtime/redirector/CMakeFiles/jvm_redirect.dir/build.make:114: runtime/redirector/libjvm.so] Error 1
20:11:32  gmake[6]: *** Deleting file 'runtime/redirector/libjvm.so'
20:11:32  gmake[5]: *** [CMakeFiles/Makefile2:8295: runtime/redirector/CMakeFiles/jvm_redirect.dir/all] Error 2
20:11:32  gmake[5]: *** Waiting for unfinished jobs....
```

**Comment by sxa** [comment]
`cmake` is at 3.16 on the machine. The last passing build was done with `cmake` 3.14.3, however the AIX Toolbox repository seems to not be allowing me to properly downgrade back to that level :-(

**Comment by sxa** [comment]
OK managed to downgrade it by manually installing [cmake-rpm-macros](https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-7.1/cmake/cmake-rpm-macros-3.14.3-1.aix7.1.ppc.rpm) and [cmake-filesystem](https://public.dhe.ibm.com/aix/freeSoftware/aixtoolbox/RPMS/ppc-7.1/cmake/cmake-filesystem-3.14.3-1.aix7.1.ppc.rpm) then using `yum install cmake-3.14.3`. I've kicked off a new build at

Potentially we could also use the later version available from http://download.aixtools.net/tools/aixtools.cmake.3.18.4.0.I but I want to at least verify if the problems we're seeing is related to 3.16 by trying the version that previously completed the build successfully or if we have another problem to fix.

**Comment by gaolibj** [comment]
I found the same issue during AIX build.  How can i get cmake-3.14.3 package. Seems I can't access the link here. Thanks.

**Comment by gaolibj** [comment]
FYI. download the cmake-3.14.3 Thanks.
