### ISSUE TITLE
OpenJ9 version is missing from the latest build download page

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#250]
The OpenJ9 latest build download page https://adoptopenjdk.net/?variant=openjdk8-openj9 should show the OpenJ9 version once there is a versioned OpenJ9 build available. 

Currently the download page only shows the OpenJDK version (i.e. build jdk8u152-b16). 

The OpenJ9 version will be 0.8.0 for the next "Latest Build".

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-**0.8.0**-rc2, JRE 1.8.0 Linux amd64-64 Compressed References 20180306_112 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ed7328e5 based on jdk8u162-b12)

**Comment by karianna** [comment]
This may be a website or api project issue, but let's dig in and see.

**Comment by sxa555** [comment]
@pshipton Do you anticipate updating the level of OpenJ9 within an openjdk build level? I believe the next OpenJ9 level is not scheduled until the next quarterly update from Oracle?

(I'm not disputing that it would be beneficial to be there, just getting an understanding of the need to help envision the future implementation

**Comment by sxa555** [comment]
(Comment to reference https://github.com/AdoptOpenJDK/openjdk-website/issues/199 which is also related to providing version information on builds)

**Comment by pshipton** [comment]
It would be useful just to ensure people are aware that OpenJ9 has a version, and corresponding release notes for that version https://github.com/eclipse/openj9/blob/master/doc/release-notes/0.8/0.8.md

The OpenJ9 release plan calls for a new version every 3 months, but there will be milestone builds in the months between. A possible scenario, 0.8.1-m1 in March, 0.8.1-m2 in April, and then 0.8.1 in June.

**Comment by gdams** [comment]
Please take a look at our new release https://adoptopenjdk.net/?variant=openjdk8-openj9. It does now show the openj9 version

**Comment by sxa555** [comment]
@pshipton Are you happy with what's not shown and that this issue can now be closed? It's effectively fallen out automatically with some other actions we took when building the final release

**Comment by pshipton** [comment]
lgtm
