### ISSUE TITLE
jdk-17 windows aarch64 using wrong "build-jdk" (jdk-16), needs to be 17 for cross-compile

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#2511]
https://github.com/AdoptOpenJDK/openjdk-build/blob/63778e89ddf59b71a4c0148d4cdce88cd526ba19/build-farm/platform-specific-configurations/windows.sh#L224
Is not using the correct "**build**-jdk" : 
https://ci.adoptopenjdk.net/view/Failing%20Builds/job/build-scripts/job/jobs/job/jdk/job/jdk-windows-aarch64-hotspot/41/console
```
23:41:00  configure: Found potential Build JDK using configure arguments
23:41:00  configure: Potential Build JDK found at /cygdrive/c/workspace/openjdk-build/jdk-16 is incorrect JDK version (openjdk version "16" 2021-03-16
); ignoring
23:41:00  configure: (Your Build JDK must be version 17)
23:41:00  checking for Build JDK... no
23:41:00  configure: error: Could not find a suitable Build JDK
```
Build JDK should be the same as the one being built for cross-compile

**Comment by M-Davies** [comment]
Could utilise the `bootJDK` field inside the [pipeline configs](https://github.com/AdoptOpenJDK/ci-jenkins-pipelines#data-fields) to specify a specific boot jdk type? Unless you are also implying that a cross compile build also requires a cross compiled boot jdk? In which case, this would not work

**Comment by andrew-m-leonard** [comment]
This is not the "boot jdk" but a "build jdk" for cross compilation
