### ISSUE TITLE
Windows JDK Build failure due to VS2019

### ISSUE THREAD

**Issue by jacktraror** [AdoptOpenJDK/openjdk-build#2519]
Hello

I am trying to build the JDK on my 64 bit Windows 10 machine using Cygwin 3.1.7 and it worked fine until almost the end of the “make images” process where it always crashes with an error I don’t understand: 

```
c:\progra~2\micros~3\2019\commun~1\vc\tools\msvc\1428~1.299\include\utility(604): error C2440: '=': cannot convert from '_Other' to '_Ty'
        with
        [
            _Other=nullptr
        ]
        and
        [
            _Ty=unsigned long
        ]
c:\progra~2\micros~3\2019\commun~1\vc\tools\msvc\1428~1.299\include\utility(604): note: A native nullptr can only be converted to bool or, using reinterpret_cast, to an integral type
c:\progra~2\micros~3\2019\commun~1\vc\tools\msvc\1428~1.299\include\memory(3423): note: see reference to function template instantiation '_Ty std::exchange<_Ty2,nullptr>(_Ty &,_Other &&) noexcept(false)' being compiled
        with
        [
            _Ty=unsigned long,
            _Ty2=unsigned long,
            _Other=nullptr
        ]
```

I used the following commands:

1. git clone https://git.openjdk.java.net/jdk/
2. cd jdk
3. bash configure --with-boot-jdk=/cygdrive/c/Users/*****/boot-jdk-15 (freshly downloaded from http://jdk.java.net/)
4. make clean (each time I executed bash configure again)
5. make images

Here are the log files:
- [configure.log](https://github.com/AdoptOpenJDK/openjdk-jdk/files/6089671/configure.log)
- [make.log](https://github.com/AdoptOpenJDK/openjdk-jdk/files/6089673/make.log)

The logs of step 3 and 5 are in the attachment. I think the configure.log also contains all necessary information about my machine and environment (if not, feel free to ask for the required information).

In my understanding, it has to do with Visual Studio 2019 (v16.9.0), but I don’t know what. I used the same configuration on another machine and it worked fine (except that it was very slow since it is not the most performant one, that’s why I wanted to change machine). Is there a VS module missing, or a special version I have to use / avoid?

Best regards,
Jack

**Comment by aahlenst** [comment]
You probably need ` --disable-warnings-as-errors` if all you care about is getting it to compile. HEAD is also 17 AFAIK, so the expected boot JDK would be 16.

**Comment by jacktraror** [comment]
I've now tried using the boot-jdk-16 and adding the flag `--disable-warnings-as-errors` inside bash configure (cannot set this flag for make), but the error is still exactly the same and the build failed.

**Comment by jacktraror** [comment]
I managed to make it work by using:
- an older version of Visual Studio: 2017
- only installing the minimal necessary module (Visual C++ tools for CMake)
- using boot-jdk 16

So the problem either lied with the newest version of Visual Studio 2019 or with some of modules I had installed on the distribution.

**Comment by M-Davies** [comment]
> So the problem either lied with the newest version of Visual Studio 2019 or with some of modules I had installed on the distribution.

More likely as it's one of your modules as we build with VS2019 on JDK11+
