### ISSUE TITLE
Update OpenJ9 to use openssl 1.1.1k

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#2549]
OpenSSL 1.1.1k is released, pls update OpenJ9 builds to use it.
https://github.com/eclipse/openj9/issues/12291

FYI last openssl update https://github.com/AdoptOpenJDK/openjdk-build/issues/2471

**Comment by keithc-ca** [comment]
Windows was addressed by https://github.com/adoptopenjdk/openjdk-infrastructure/pull/2083.

I don't think openssl is bundled on other platforms, so what else is needed?

**Comment by sxa** [comment]
> I don't think openssl is bundled on other platforms, so what else is needed?

It needs to be put onto all machines ([There is one left](https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2085#issuecomment-808042302)) and then a PR to tell the build scripts to pick it up, then I can run a test to make sure it works.

(@keithc-ca semi-related: your opinion on https://github.com/AdoptOpenJDK/openjdk-build/pull/2550 wold also be appreciated if you have a minute)

**Comment by pshipton** [comment]
> I don't think openssl is bundled on other platforms, so what else is needed?

It's also bundled on Mac.
