### ISSUE TITLE
RPM install on ubi8-minimal fails with "package adoptopenjdk-xyz does not verify: no digest"

### ISSUE THREAD

**Issue by demus-nine** [AdoptOpenJDK/openjdk-build#2558]
**What are you trying to do?**
`microdnf install adoptopenjdk-11-hotspot-jre`

**Expected behaviour:**
rpm installs

**Observed behaviour:**
Running transaction test...
error: Error running transaction: package adoptopenjdk-11-hotspot-jre-11.0.10+9-3.x86_64 does not verify: no digest

**Any other comments:**
Apparently newer rhel distros don't accept md5 digests.

**Comment by karianna** [comment]
This may need to be moved to adoptium/installer

**Comment by danieldemus** [comment]
OK. I created https://github.com/adoptium/installer/issues/306 and will close this one.
