### ISSUE TITLE
Slackin badge in README returns 404 error

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#2559]
**What are you trying to do?**
Click on Slack link in [README](https://github.com/AdoptOpenJDK/openjdk-build#readme)

<img width="139" alt="Screen Shot 2021-04-07 at 2 51 59 PM" src="https://user-images.githubusercontent.com/2836948/113919092-2f176500-97b1-11eb-8f0d-33df9412c186.png">

**Expected behaviour:**
To click on Slack link and be taken to Slack or Slack invite page

**Observed behaviour:**
Click on link returns 404 error
<img width="687" alt="Screen Shot 2021-04-07 at 2 55 06 PM" src="https://user-images.githubusercontent.com/2836948/113919165-435b6200-97b1-11eb-8c26-d981d3bdfb45.png">

**Comment by M-Davies** [comment]
Dup of https://github.com/AdoptOpenJDK/openjdk-build/issues/2557
