### ISSUE TITLE
Freetype lib isn't bundled on Windows64

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#2568]
Smoke tests shows that freetype lib isn't bundled on Windows64 as expected.  #2226 shows that it should not be present on Linux or AIX while should be on windows.

```
19:46:15  FAILED: freetypeOnlyBundledOnWindowsAndMacOS
19:46:15  java.lang.AssertionError: Expected libfreetype to be bundled but is not. expected [true] but found [false]
19:46:15  	at org.testng.Assert.fail(Assert.java:96)
19:46:15  	at org.testng.Assert.failNotEquals(Assert.java:776)
```

@adamfarley could you confirm that freetype lib should be bundled on windows?

**Comment by sophia-guo** [comment]
I guess for window we need to update tests to find freetype.dll

**Comment by smlambert** [comment]
The test checks for multiple suffixes: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/test/functional/buildAndPackage/src/net/adoptopenjdk/test/BundledFreetypeTest.java#L51

**Comment by sophia-guo** [comment]
Multiple suffixes check `libfreetype`.  But window does have `freetype.dll` not `libfreetype.dll`.

> Is this actually showing a real problem with freetype not being bundled?
I've gone through #2133 #2226 no answer. @adamfarley may know that?

**Comment by adamfarley** [comment]
Heya @sophia-guo 

I can confirm that the test should be looking for freetype.dll, not libfreetype.dll. 

Given that the regex has a wildcard at the beginning already, we're probably safe if we simply remove "lib" from the start. It'll find both freetype.dll and libfreetype.dylib (mac).

See https://github.com/AdoptOpenJDK/openjdk-build/pull/2570
