### ISSUE TITLE
s390 : openjdk8 with hotspot nightly build sdk crashed

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#257]
nightly sdk:
wget https://github.com/AdoptOpenJDK/openjdk8-nightly/releases/download/jdk8u172-b00-20180803/OpenJDK8_s390x_Linux_20180803.tar.gz

running java -version:
```
jenkins@build-marist-ubuntu1604-s390x-1:~/test/jdk8u172-b03/jre/bin$ ./java -version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (os_linux_zero.cpp:254), pid=64869, tid=0x000003ffb2bff910
#  fatal error: caught unhandled signal 11
#
# JRE version:  (8.0) (build )
# Java VM: OpenJDK 64-Bit Zero VM (25.71-b00 interpreted mode linux-s390x )
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data/home/jenkins/test/jdk8u172-b03/jre/bin/hs_err_pid64869.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Aborted (core dumped)
```

**Comment by sophia-guo** [comment]
Looking at the build, build failed.
https://ci.adoptopenjdk.net/job/openjdk8_build_s390x_linux/159/console

Question: If build fails why it can still be accessed by https://github.com/AdoptOpenJDK/openjdk-api

**Comment by sxa555** [comment]
The publishing is totally independent (and I think possibly done in parallel) with the testing. I've seen this before and we really need to get a basic `java -version` test in place before publishing.

Looks like the latest build got further but still had a crash when starting the VM though. Currently the build machine is offline as far as jenkins is concerned. FYA @gdams since I don't know if these issues are things that are being addressed at present

**Comment by smlambert** [comment]
Very shortly, we will [incorporate test step into build pipelines](https://github.com/AdoptOpenJDK/openjdk-tests/issues/332), and gate publishing of the builds on certain test criteria (openjdk_regression and system).  We should put [a java -version check in place](https://github.com/AdoptOpenJDK/openjdk-tests/issues/333), as if that doesn't work, there is no reason to launch more testing.

**Comment by gdams** [comment]
okay so this is the build run where the failure occured: https://ci.adoptopenjdk.net/job/openjdk8_build_s390x_linux/157/consoleFull. Interestingly it was actually built on the ubuntu1604 machine. I will try a build on the rhel7 machine once it comes back and see if this fixes the issue

**Comment by sophia-guo** [comment]
referred to https://github.com/AdoptOpenJDK/openjdk-build/issues/264

**Comment by karianna** [comment]
We've been building these OK for some time now.
