### ISSUE TITLE
Fonts with contextual alternates are not correct rendered

### ISSUE THREAD

**Issue by BuZZ-dEE** [AdoptOpenJDK/openjdk-build#2576]
Pay attention to the e's, for example: 

**AdoptOpenJDK 8:** _**wrong**_ rendering for font size _**less**_ than _**101**_ and other _**wrong**_ rendering for font size _**greater**_ than _**100**_
![java-8_font_with_contextual_alternates_not_correct_rendering_below_font_size_100](https://user-images.githubusercontent.com/125954/115042211-8f09bc00-9ed3-11eb-8042-d628c9025378.png)

**AdoptOpenJDK 11:** _**wrong**_ rendering for font size _**less**_ than _**101**_ and **correct** rendering for font size **greater** than **100**
![java-11_font_with_contextual_alternates_not_correct_rendering_below_font_size_100](https://user-images.githubusercontent.com/125954/115042239-94670680-9ed3-11eb-874b-bedc9350c9b5.png)

**Example code:**
[FontRederingErrorDemo.zip](https://github.com/AdoptOpenJDK/openjdk-build/files/6325979/FontRederingErrorDemo.zip)

**Fonts with feature contextual alternates:**
- https://bboxtype.com/typefaces/Krikikrak
- http://www.glukfonts.pl/font.php?font=Kleymissky

**Comment by karianna** [comment]
@BuZZ-dEE - Can you please repost this to https://github.com/adoptium/adoptium-support ?

**Comment by BuZZ-dEE** [comment]
@karianna https://github.com/adoptium/adoptium-support/issues/291
