### ISSUE TITLE
Provide JRE packages in addition to JDK packages

### ISSUE THREAD

**Issue by DanHeidinga** [AdoptOpenJDK/openjdk-build#262]
There was a request at OpenJ9 to provide JRE packages in addition to JDK packages: https://github.com/eclipse/openj9/issues/1438

I think this is a great idea and would be beneficial if we could provide both packages.  Many deployments on need the JRE, not the full JDK.

For JDK9 this might just be a re-jlink of the SDK into the JRE configuration.  Likely more work for JDK8.

**Comment by karianna** [comment]
I'd hope we could produce this as part of our pipeline. I know you can produce both a JRE and JDK from the make, need to dig in what `make images` currently does ( I think it actually provides both.)

**Comment by DanHeidinga** [comment]
For JDK8, `make images` creates both a JRE and a JDK:
```
$ /build/build/linux-x86_64-normal-server-release/images# ls
_strip_jdk  _strip_jre  j2re-image  j2sdk-image  lib  sec-bin.zip  src  src.zip  symbols
```

**Comment by DanHeidinga** [comment]
I see a JRE package as being more important for Java 8 than for later releases as Java 9+ can use `jlink` to create a stripped runtime.

**Comment by sxa555** [comment]
> For JDK8, make images creates both a JRE and a JDK:

Hmmm they're not showing up in our build directories (e.g. https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/ws/openjdk/) and that does claim from [the log](https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/144/consoleFull) to be executing `make images`

**Comment by sxa555** [comment]
@karianna No it's not in the hotspot build at https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_linux/ws/openjdk/ either. Will need some investigation I feel.

**Comment by sxa555** [comment]
Ahhh we seem to have a `j2re-image` directory under `openjdk/build/linux-x86_64-normal-server-release/images` in the workspace so hopefully this won't be too difficult. We currently rename the `j2sdk-image` directory to something that matches the bulid name e.g. `jdk8u172-b03` but leave the `j2re-image` directory as-is ... Will continue to work this.

**Comment by ceejatec** [comment]
Why was this closed? There are still no JRE downloads available...

**Comment by gdams** [comment]
@ceejatec the website is hosting JDK and JRE packages and has been for a while

**Comment by ceejatec** [comment]
I've been hunting around https://adoptopenjdk.net/ for a while and I can't find any... am I missing something obvious?

**Comment by yamadamn** [comment]
@ceejatec You can download both JDK and JRE for OpenJDK 8 from https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot 
JRE are still not hosted for OpenJDK 11 with HotSpot, but instead, JRE are already hosted for OpenJDK11 with OpenJ9.

**Comment by ceejatec** [comment]
@yamadamn I could have sworn that wasn't there last night! And at the moment it does appear that there ARE HotSpot OpenJDK 11 JRE packages. Although the naming convention befuddles me - under jdk-11.0.1+13, the JRE download is https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11%2B28/OpenJDK11-jre_x64_linux_hotspot_11_28.tar.gz ... any idea what 11_28 is? Is that build in fact the "same JRE" as JDK 11.0.1+13 ?....

**Comment by yamadamn** [comment]
@ceejatec  I think 11_28 means "11GA build 28"; so, it's not same as 11.0.1+13.
You can see in the archive or tag as below.
https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=hotspot
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11%2B28

Is your concern related to #796? If so, you'd better to comment in #796.

**Comment by justinmahar** [comment]
It seems some of the JDK downloads have a companion JRE, some don't. If there's a particular JDK with no JRE available for download, you can use the following tool to create one easily using `jlink`:

https://justinmahar.github.io/easyjre/

This will give you the `jlink` command you need to create a standard JRE for any JDK, and allows you to customize the command from there.

**Comment by 030** [comment]
Could this issue be reopened? Oracle used to provide always a JRE for download. In my opinion this should be done as well as this can be automated.

**Comment by karianna** [comment]
We do provide JRE packages, I'm not sure what's missing?

**Comment by 030** [comment]
@karianna I misunderstood. Now I found the JRE https://adoptopenjdk.net/releases.html#x64_linux

**Comment by noelmcloughlin** [comment]
This is UI misdirection mind game ;-) A google search brought me here.

The attention of new visitors is diverted to word *jdk* on the left - **a heading**.  So we visually search for heading with word *jre* on the left but it cannot be found.  Not very obvious UI.

<img width="1063" alt="Screenshot 2020-04-27 at 12 13 54" src="https://user-images.githubusercontent.com/13322818/80366304-f83a8e80-8880-11ea-88f2-d6a234f008cb.png">

**Comment by aahlenst** [comment]
@noelmcloughlin Please file a new issue on https://github.com/adoptopenjdk/openjdk-website/issues.

**Comment by sxa** [comment]
Bear in mind it's questionable whether we wouldwish to do anythign about this - the name displayed on the web site is based on the tag in the openjdk project which is `jdk8u252-b09` for example - it's how the project names their code tags. So we are producing JDKs and JREs based on the source code at that tag. While I understand the confusion it would be rather odd to change the label shown on the web site (especially given the label is the name of the github repo)

**Comment by mbiebl** [comment]
I don't see any JRE downloads anymore at https://adoptium.net/releases.html?variant=openjdk8&jvmVariant=hotspot

Should this issue be reopenend or do I just need to wait a little longer?

**Comment by smlambert** [comment]
JREs will get published after the JDKs are all released, for status updates, best to watch the [release channel](https://adoptium.slack.com/archives/CLCFNV2JG) in the Adoptium Slack workspace (if not already joined, sign up [here](https://adoptium.net/slack.html)).
