### ISSUE TITLE
Print java version as a sanity check doesn't work as expected

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#264]
printJavaVersionString() in sbin/build.sh doesn't work as expected when invalid java has been built.

```
"$PRODUCT_HOME"/bin/java -version || (echo "${error} Error executing 'java' does not exist in '$PRODUCT_HOME'.${normal}" && exit -1)

```
https://ci.adoptopenjdk.net/job/openjdk8_build_s390x_linux/160/consoleFull

From this build we can see that 'exit -1' was not executed. Build process continued and exit normally, which caused  jenkins label the job as successful. 

On the build machine build-digitalocean-centos69-x64-1 I have manually reproduced this problem. However in my personal jenkins machine this works fine. 

build machine bash version:
GNU bash, version 4.1.2(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2009 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

my personal bash version:
jenkins@2f65ab2a93f8:~/workspace/freestyle$ /bin/bash -version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by gdams** [comment]
should this not be `exit 1` rather than `exit -1`? I might be wrong?

**Comment by sophia-guo** [comment]
It happened to AIX now. Looking at the recent AIX openjdk10-openj9 build: https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_ppc64_aix/

6 out of 8 successful builds are actually failure ones. 

Java version sanity check doesn't work as expected.
