### ISSUE TITLE
Build failure of JDK10 on AIX (disk space issue on /ramdrive0)

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#266]
Problem started with build #80 on https://ci.adoptopenjdk.net/job/openjdk10_build_ppc64_aix/

#79 decalred success despite running out of disk space:

```
Note: Recompile with -Xlint:deprecation for details.
Note: /ramdisk0/build/workspace/openjdk10_build_ppc64_aix/openjdk/src/demo/share/jfc/TableExample/TableExample4.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
java.io.UncheckedIOException: java.io.IOException: No space left on device
	at jdk.jlink/jdk.tools.jlink.builder.DefaultImageBuilder.lambda$storeFiles$1(DefaultImageBuilder.java:178)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
```
#80 failed and included this message which could also indicate disk space exceeded:
```
ld: 0711-224 WARNING: Duplicate symbol: Java_sun_awt_DebugSettings_setCTracingOn__ZLjava_lang_String_2
ld: 0711-224 WARNING: Duplicate symbol: Java_sun_awt_DebugSettings_setCTracingOn__Z
ld: 0711-344 See the loadmap file /ramdisk0/build/workspace/openjdk10_build_ppc64_aix/openjdk/build/aix-ppc64-normal-server-release/support/native/java.desktop/libawt_xawt/libawt_xawt.loadmap for more information.
cp: Requested a write of 131072 bytes, but wrote only 110592.
gmake[3]: *** [/ramdisk0/build/workspace/openjdk10_build_ppc64_aix/openjdk/build/aix-ppc64-normal-server-release/support/modules_libs/java.desktop/libfontmanager.so] Error 1
gmake[3]: *** Deleting file '/ramdisk0/build/workspace/openjdk10_build_ppc64_aix/openjdk/build/aix-ppc64-normal-server-release/support/modules_libs/java.desktop/libfontmanager.so'
gmake[2]: *** [java.desktop-libs] Error 1
gmake[1]: *** [main] Error 1
gmake: *** [images] Error 2
/ramdisk0/build/workspace/openjdk10_build_ppc64_aix/sbin/build.sh: line 297: [: Building target 'images' in configuration 'aix-ppc64-normal-server-release'
```
Both build jobs were executed on `build-osuosl-ppc64-aix-71-1` which appears to have an adequate amount of space in `/ramdisk0` just now (3Gb free).
However it appears to have nothing in it, suggesting there are open file handles on the box to deleted files. Think we've seen this once before ...

**Comment by sxa555** [comment]
From recollection this cleared last time when I attempted to umount/mount the filesystem - same happened this time - just the umount was enough to kick it into fixing itself:

```
# df -k .
Filesystem    1024-blocks      Free %Used    Iused %Iused Mounted on
/dev/ramdisk0    15728640   3333672   79%     1192     1% /ramdisk0
# umount /ramdisk0
df -k
umount: 0506-349 Cannot unmount /dev/ramdisk0: The requested resource is busy.
# df -k .
Filesystem    1024-blocks      Free %Used    Iused %Iused Mounted on
/dev/ramdisk0    15728640  15109288    4%        7     1% /ramdisk0
# 
```

**Comment by sxa555** [comment]
Agreement on today's infrastructure call to leave this open to be able to attempt to test and reproduce since it's been seen before.

**Comment by sxa555** [comment]
Same issue is happening on the second AIX machine `build-osuosl-ppc64-aix-2`. I'm going to avoid clearing it for now in case @bblondin wants to investigate further.

**Comment by sxa555** [comment]
Happened again to https://ci.adoptopenjdk.net/job/openjdk8_build_ppc64_aix/234/

**Comment by karianna** [comment]
shouldn't the build artifacts be cleared down between runs?

**Comment by sxa555** [comment]
@karianna The filesystems are showing as having nothing in them, but something is still chewing space. Normally that would indicate a file handle open, but that's not something you'd normally expect to be cleared by just _attempting_ to `umount` the filesystem

**Comment by sxa555** [comment]
@gdams Yeah that would likely mitigate the problem most of the time but it's more of a sticking plaster rather than solving it, and would require a bit more care to ensure that nothing was running on the boxes at the time. 

Am also interested about how much we're currently saving using the ramdrive given that each build is still taking about an hour on AIX https://github.com/AdoptOpenJDK/openjdk-build/issues/241(I suspect it's quite a lot based on previous experience)

**Comment by sxa555** [comment]
Kicked `-2` again. Wonder how long it's going to be before I set up a cron job to just run the umount command on a weekly (ish) basis ...

**Comment by sxa555** [comment]
https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_ppc64_aix/32/consoleFull failed - kicked `-2` again.

**Comment by karianna** [comment]
Resolved and no longer supporting 10 so closing
