### ISSUE TITLE
AdoptOpenJDK/Eclipse OpenJ9 (AO9/J9) failing on Windows

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#267]
Raised via @andrew-m-leonard

Nightly builds haven't published for a few days - it appears that the Windows builds at https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_x86-64_windows/buildTimeTrend have been failing. The first SoftLayer machine (https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-1/) is the only one that can currently build this as it has an `openj9` tag and the `-2` machine does not, yet the `-2` machine ran the first failing build on the 16th.

It would appear that @gdams was manually kicking off some builds around that time outside the nightly cycle, therefore assigning it to him on the assumption that he might know what changed around that time.

```
checking what kind of 'find' is first on the PATH... Windows
configure: Your path contains Windows tools (C:\Windows\system32) before your unix (cygwin or msys) tools.
configure: This will not work. Please correct and make sure /usr/bin (or similar) is first in path.
configure: error: Cannot continue
configure exiting with result code 1
```

**Comment by sxa555** [comment]
Added this to the jenkins jobs to "tactically unbreak" it for now
```
export PATH="/usr/bin:$PATH"
```

**Comment by karianna** [comment]
Converted to pipeline scripts and is working.
