### ISSUE TITLE
Some sort of an alert to notify build instance is out of resource

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#27]
(Not sure if this is the right repo for it)

But sometimes we run out of disk space or some other resource and it would be good to get an alert of a potential of this happening.

An email alert to the admin alerting about resources surpassing its threshold.

Its not an urgent need but good to have for medium to long run when we have even more resources to manage.

Has been discussed with @gdams and @tellison.

**Comment by tellison** [comment]
There are a number of packages that will monitor groups of machines that would be suitable (e.g. Nagios).
Looking for somebody with admin experience to suggest a good solution for us.

**Comment by karianna** [comment]
We use Zabbix at jClarity - but in all honesty it's been a bit of a P%^A.

**Comment by bblondin** [comment]
Nagios is a great tool for a complete monitoring solution. It will require a system to run on
(Linux, 2 core, 4GB of RAM, and 80GB of disk) and some additional configuration on the remote systems. (The Ansible playbooks can be updated to include this for new deployments)

Depending on the level of monitoring required, a simpler solution might suffice such as, using the customizable thresholds in Jenkins for basic monitoring of its nodes, for things like ‘Free Space’ and ‘Free Temp Space’ that will mark the node offline. Add a simple groovy script that gets invoked when an ‘offline’ event occurs, that sends an e-mail to interested parties. This could be enhanced by utilizing Slack’s e-mail integration feature to post these events directly to a Slack Channel.

Blog about monitoring Jenkins slaves with groovy:
http://www.donaldsimpson.co.uk/2013/06/07/monitoring-jenkins-slave-nodes-with-groovy/ 

Send e-mails to Slack:
https://get.slack.help/hc/en-us/articles/206819278-Send-emails-to-Slack

**Comment by karianna** [comment]
@bblondin Thanks - I'll see if I can secure another cheap box to run this if you're willing / able to set it up?

**Comment by bblondin** [comment]
@karianna Absolutely :)

**Comment by gdams** [comment]
@bblondin can we not run it on a 1cpu 1gb ram machine short term, I can easily spin up one of those for you

**Comment by bblondin** [comment]
@gdams That should be ok, lets try it. (I believe 1cpu 1gb ram is the bare minimum)

**Comment by gdams** [comment]
@bblondin I have sent you the aws details on slack

**Comment by gdams** [comment]
@karianna we have decided to use the existing ansible machine that you provisioned as that is still hosted on AWS with no issues

**Comment by karianna** [comment]
@gdams My wallet thanks you both :-)

**Comment by karianna** [comment]
Hmm actually, I think we should still split that out later for resiliency, but that can wait until we have more machine donations.

**Comment by karianna** [comment]
I think the Nagios install covers this fine.
