### ISSUE TITLE
Create pipeline for AdoptOpenJDK builds of openjdk10 + Eclipse OpenJ9

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#272]
Code was made available in https://github.com/ibmruntimes/openj9-openjdk-jdk10 yesterday so we should have a pipeline to build it.

**Comment by sxa555** [comment]
autoconf on RHEL69 is too old according to my first attempt. Will see if the non-x64 platforms with RHEL74 are happier later. Forcing x64 to Ubuntu machines for now
```
Warning: The generated configure file contains changes not present in the custom generated file.
Running autogen.sh to correct the situation
Using autoconf at /usr/bin/autoconf [autoconf (GNU Autoconf) 2.63]
Generating generated-configure.sh
stdin:33: error: Autoconf version 2.69 or higher is required
stdin:33: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
Generating custom generated-configure.sh
stdin:33: error: Autoconf version 2.69 or higher is required
stdin:33: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
Running custom generated-configure.sh
Configured the JDK
```

**Comment by sxa555** [comment]
x64 now working: https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_x86-64_linux/
s390x fails on Ubuntu 16.04 as there isn't a suitable java 9 boot JDK installed https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/324 and the RHEL74 box is offline https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/323 - tactical fix implemented to download adoptopenjdk 9 release to the workspace in the jenkins job and use that
ppc64le not working yet

**Comment by sxa555** [comment]
Steps at https://github.com/AdoptOpenJDK/TSC/wiki/Adding-a-new-build-variant need to be followed

**Comment by sxa555** [comment]
Steps all followed - pipeline now runnign successfully (all jenkins jobs have been modified to cope with the new release. Two PRs are in and awaiting approval:

https://github.com/AdoptOpenJDK/openjdk-website-backend/pull/9
https://github.com/AdoptOpenJDK/openjdk-website/pull/232

Initial support for JCK10 has also been added into the appropriate places and I'm trialling it on Linux/x86-64

The build pipeline is therefore in place, which should be enough to close this off when the pull requests have been merged to allow them to be published - JCK and other test execution can be covered in separate issues.

**Comment by sxa555** [comment]
AIX currently has a failure on one of the two build machines due to the lack of autoconf - PR is in to fix ther playbook - see https://github.com/AdoptOpenJDK/openjdk-build/issues/280

**Comment by andrew-m-leonard** [comment]
@sxa555 
Once PR https://github.com/ibmruntimes/openj9-openjdk-jdk10/pull/9
is merged, Adopt will need to specify the following "configure" parameters for "RELEASE" type builds:
JDK10:
```
--with-version-string="10+<build>" --with-version-date="<date>"
```
eg:
```
--with-version-string="10+46" --with-version-date="2018-03-29"
```

**Comment by sxa555** [comment]
Closing this as the initial pipeline creation has been completed and the nightly builds from it are appearing at https://github.com/adoptopenjdk/openjdk10-openj9-nightly

**Comment by smlambert** [comment]
(note: updated pipeline script here: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/openjdk10_openj9_nightly_pipeline.groovy - which Jenkins job now pulls directly from git)
