### ISSUE TITLE
Docker builds do not honour the --ssh flag being passed through

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#273]
Executing `./makejdk-any-platform.sh --keep --ssh --version jdk8u`

I'm still challenged for my username and password (https download challenge)

**Comment by amczarny** [comment]
Is the issue still valid? I was not able to reproduce it.

**Comment by karianna** [comment]
Yeah - private key doesn't get passed through to the Docker container.  But that said -ssh is really not required as all repos we pull from have https anon access (or should do)

**Comment by gdams** [comment]
This is because the docker container does not copy your private keys. We should probably just add a step to the docker container to copy your `id_rsa` if `--ssh` is specified

**Comment by amczarny** [comment]
This issue should be closed
