### ISSUE TITLE
AdoptOpenJDK10 with OpenJ9 builds on Windows are failing to locate headers

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#281]
There's a bit of a mess here (which I'm documenting for information so I remember when I come back to untangle it). There's a job https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_x86-64_windows which appears to call itself `openjdk10_openj9_build_x86-64_windows` (i.e. `jdk9` instead of `jdk10`) when you look at it's breadcrumb trail at the top of the screen. This means it's duplicating the [real `jdk9` job](https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_x86-64_windows/) in the views and so I can't separate them out. I suspect bad things might happen when I try to clear that up so I'm leaving it for now ...

Glossing over that, To avoid confusing mysefl further (maybe...) I've created another job with the same name but with `win` instead of `windows` at the end at https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_x86-64_win and it initially gave me a warm fuzzy feeling that it was going ok then fell over in a heap because it couldn't find basic stuff like `stdio.h` `string.h``stdarg.h` and `stdlib.h`. If anyone wants to take a look it this it would be good to sort it out ... I suspect it'll end up being something simple but my brain is too friend with other stuff today for me to fix it :-)

```
cl  -I.  -DUT_DIRECT_TRACE_REGISTRATION -I../../../include -I../../include_core -I../../nls -D_AMD64_=1 -DWIN64 -D_WIN64 -DWIN32 -D_WIN32 -DJ9HAMMER -D_CRT_SECURE_NO_WARNINGS -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -D_WIN95 -D_WIN32_WINDOWS=0x0500 /D_WIN32_DCOM -D_MT -D_WINSOCKAPI_  -D_WIN32_IE=0x0500 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -D_DLL  -Zm400 -MD /Ox -WX -W3 -FdTraceHeaderWriter.pdb /Zi   -c TraceHeaderWriter.cpp /Fo./
FileReader.cpp
Port.cpp
pugixml.cpp
DATMerge.cpp
FileUtils.cpp
FileUtils.cpp(23) : fatal error C1083: Cannot open include file: 'stdarg.h': No such file or directory
main.cpp(23) : fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
TraceGen.cpp
../../tools/tracegen/ArgParser.cpp(23) : fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
HookGen.cpp(23) : fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
main.cpp(23) : fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
Port.cpp(29) : fatal error C1083: Cannot open include file: 'string.h': No such file or directory
TraceHeaderWriter.cpp
cl  -I../../tools/tracegen  -DUT_DIRECT_TRACE_REGISTRATION -I../../../include -I../../include_core -I../../nls -D_AMD64_=1 -DWIN64 -D_WIN64 -DWIN32 -D_WIN32 -DJ9HAMMER -D_CRT_SECURE_NO_WARNINGS -DCRTAPI1=_cdecl -DCRTAPI2=_cdecl -nologo -D_WIN95 -D_WIN32_WINDOWS=0x0500 /D_WIN32_DCOM -D_MT -D_WINSOCKAPI_  -D_WIN32_IE=0x0500 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 -D_DLL  -Zm400 -MD /Ox -WX -W3 -FdStringUtils.pdb /Zi   -c ../../tools/tracegen/StringUtils.cpp /Fo./
../../tools/tracegen/FileReader.cpp(23) : fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
DATMerge.cpp(23) : fatal error C1083: Cannot open include file: 'string.h': No such file or directory
c:\users\jenkins\jdk9_j9\openjdk\build\windows-x86_64-normal-server-release\vm\omr\third_party\pugixml-1.5\pugixml.hpp(26) : fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
make[6]: Leaving directory '/cygdrive/c/Users/jenkins/jdk9_j9/openjdk/build/windows-x86_64-normal-server-release/vm/omr/tools/hookgen'
make[5]: Leaving directory '/cygdrive/c/Users/jenkins/jdk9_j9/openjdk/build/windows-x86_64-normal-server-release/vm/omr'
StringUtils.cpp
../../tools/tracegen/FileUtils.cpp(23) : fatal error C1083: Cannot open include file: 'stdarg.h': No such file or directory
TraceGen.cpp(23) : fatal error C1083: Cannot open include file: 'stdio.h': No such file or directory
TraceHeaderWriter.cpp(23) : fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory
make[6]: Leaving directory '/cygdrive/c/Users/jenkins/jdk9_j9/openjdk/build/windows-x86_64-normal-server-release/vm/omr/tools/tracegen'
../../tools/tracegen/StringUtils.cpp(23) : fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory
make[6]: Leaving directory '/cygdrive/c/Users/jenkins/jdk9_j9/openjdk/build/windows-x86_64-normal-server-release/vm/omr/tools/tracemerge'
make[5]: Leaving directory '/cygdrive/c/Users/jenkins/jdk9_j9/openjdk/build/windows-x86_64-normal-server-release/vm/omr'
make[4]: Leaving directory '/cygdrive/c/Users/jenkins/jdk9_j9/openjdk/build/windows-x86_64-normal-server-release/vm'
Creating support/symbols/ct.sym

ERROR: Build failed for targets 'images test-image' in configuration 'windows-x86_64-normal-server-release' (exit code 2) 
Stopping sjavac server

No indication of failed target found.
```

**Comment by karianna** [comment]
I've just looked at that project config and tried to force a rename with no luck.  I'm hoping a major Jenkins upgrade will clear this up (I'll fire this over Easter ready for everyone to panic about on Tuesday :-))

**Comment by sxa555** [comment]
Suspect it could be sorted by editing the job xml file directly on the server (Not sure if you tried that - I haven't so far)

**Comment by sxa555** [comment]
Well this is ridiculous:

```
configure: Found Visual Studio installation at /cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/ using VS120COMNTOOLS variable
configure: Found Microsoft Visual Studio 2013
configure: Rewriting VS_ENV_CMD to "/cygdrive/c/progra~2/micros~2.0/vc/bin/amd64/vcvars64.bat"
configure: Trying to extract Visual Studio environment variables
configure: Setting extracted environment variables
checking for Visual Studio variables... ok
configure: Rewriting ipath to "/cygdrive/c/progra~2/micros~2.0/vc/include"
configure: Rewriting ipath to "/cygdrive/c/progra~2/micros~2.0/vc/atlmfc/include"
configure: Rewriting ipath to "/cygdrive/c/progra~2/window~1/8.1/include/shared"
configure: Rewriting ipath to "/cygdrive/c/progra~2/window~1/8.1/include/um"
configure: Rewriting ipath to "/cygdrive/c/progra~2/window~1/8.1/include/winrt"
configure: Rewriting libpath to "/cygdrive/c/progra~2/micros~2.0/vc/lib/amd64"
configure: Rewriting libpath to "/cygdrive/c/progra~2/micros~2.0/vc/atlmfc/lib/amd64"
configure: Rewriting libpath to "/cygdrive/c/progra~2/window~1/8.1/lib/winv6.3/um/x64"
checking for cl... /cygdrive/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN/amd64/cl
configure: Rewriting CC to "/cygdrive/c/progra~2/micros~2.0/vc/bin/amd64/cl"
checking resolved symbolic links for CC... no symlink
configure: Using microsoft C compiler version 18.00.40629 [Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x64]
```
configure is trying to use the short version of the directories that vcvars would normally set as the `INCLUDE` and `LIB` vaitables. On the machine [build-softlayer-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-1) which that log is taken from `progra~2/micros~2.0` maps to the `Microsoft Visual Studio 9` directory which does not contain `vc/include` which is where all the headers should be so whatever's doing that translation superficially looks like it's making a complete hash of it.

**Comment by sxa555** [comment]
For reference, it still needs to be run on an `buildj9`tagged machine otherwiske ikt fails to locate `freemarker.jar`:
https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_x86-64_windows/5/console

**Comment by sxa555** [comment]
Previous statement wasn't accurate - `microso~2.0` is indeed the VC12.0 directory. `microso~3.0` is the VC9.0 one. Continuing to investigate ...

**Comment by sxa555** [comment]
Adding the correct directory into the `INCLUDE`  environment variable before running the build solved the issue, although it then failed to find `windows.h`

**Comment by vsebe** [comment]
@sxa555 please do port the PR.
What are the configure options you used?

**Comment by sxa555** [comment]
It's from this job: https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_x86-64_windows/
So at the moment it's these ones:

`--with-version-pre=adoptopenjdk --with-version-string=  --with-boot-jdk=/cygdrive/c/openjdk/jdk9 --with-freetype-src=/cygdrive/c/openjdk/freetype-2.5.3 --with-toolchain-version=2013 --with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --disable-ccache`

**Comment by vsebe** [comment]
This path is also missing: https://github.com/ibmruntimes/openj9-openjdk-jdk9/commit/5f21c78b772bb6fe5634c2d386bede28be07e25d#diff-617c26e9ef7bc8368ae2e2671aa0ae88

**Comment by sxa555** [comment]
@vsebe So I update the `.m4` file, run `autogen.sh` and check in the changes it'll make to the generated-configure.sh files?

**Comment by sxa555** [comment]
Update my PR with another commit to match the PR referred to two comments above

**Comment by sxa555** [comment]
PR merged and builds working. Also subsequent transient issue https://github.com/AdoptOpenJDK/openjdk-build/issues/294 has been resolved, therefore closing
