### ISSUE TITLE
Buliding from a tag in AO10/J9 does not work in all cases

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#282]
Seems there is a check being done on the tag name, which is used as the version identifier in the build process. Needs fixing one way or another.

```
checking if packaged modules are kept... yes (default)
configure: error: --with-version-string fails to parse as a valid version string: b6fe698
configure exiting with result code 1
```
Ref: https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_x86-64_linux/10

**Comment by karianna** [comment]
I'll try to pick this up in the refactor.  Status is that the refactor works well for linux users, not so much for Mac

**Comment by karianna** [comment]
Pretty sure this is resolved and we no longer support Java 10?
