### ISSUE TITLE
Extra configuration parameter required by Eclipse OpenJ9 v10 release builds

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#287]
Separated out from @andrew-m-leonard's comment on https://github.com/AdoptOpenJDK/openjdk-build/issues/272

Now that https://github.com/ibmruntimes/openj9-openjdk-jdk10/pull/9 is merged, Adopt will need to specify the following "configure" parameters for "RELEASE" type builds:
JDK10:

`--with-version-string="10+<build>" --with-version-date="<date>"`

eg:

`--with-version-string="10+46" --with-version-date="2018-03-29"`

**Comment by karianna** [comment]
Resolved and Java 10 no longer supported.
