### ISSUE TITLE
openjdk10-openj9 java -version output incorrect

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#289]
java -version on openjdk10-openj9 is missing the 'based on' string:

> java -version
openjdk version "10-adoptopenjdk" 2018-03-20
OpenJDK Runtime Environment (build 10-adoptopenjdk+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build master-093b330a, JRE 10 Linux amd64-64 Compressed References 20180403_18 (JIT enabled, AOT enabled)
OpenJ9   - 093b330a
OMR      - f5937ead
JCL      - f1e2849a04 based on )

Looks very similar to https://github.com/AdoptOpenJDK/openjdk-build/issues/204 - same thing on openjdk8-openj9

**Comment by andrew-m-leonard** [comment]
Please check the latest jdk10 builds, we changed the "OpenJ9 openjdk extensions" latest tag search logic just last week, that may fix this.

**Comment by lumpfish** [comment]
Fixed on latest build:

C:\openj9java\jdk-10+46\bin>java -version
openjdk version "10-adoptopenjdk" 2018-03-20
OpenJDK Runtime Environment (build 10-adoptopenjdk+0-adhoc..openjdk)
Eclipse OpenJ9 VM (build master-1fa41d71, JRE 10 Windows 7 amd64-64 Compressed R
eferences 20180416_28 (JIT enabled, AOT enabled)
OpenJ9   - 1fa41d71
OMR      - ef9dd6fd
JCL      - a91ffe0d9a based on jdk-10+46)
