### ISSUE TITLE
Windows build is currently failing

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#29]
Details TBA

**Comment by neomatrix369** [comment]
Some useful resources from our AdoptOpenJDK/OpenJDK/Java friends:
- http://royvanrijn.com/blog/2013/10/building-openjdk-on-windows/

**Comment by sunnychanwork** [comment]
How did you setup the build machine? What version of Windows, Visual Studio, cygwin, etc installed on the machine? I can replicate the setup at home and see whether I can find out what's wrong.

**Comment by karianna** [comment]
@sunnychanwork - I'm not 100% sure but I think @gdams can give you access to the box.

**Comment by gdams** [comment]
@sunnychanwork I'm happy to give you temporary access to the build machine if you think you know what may be wrong ?

**Comment by sunnychanwork** [comment]
@gdams I don't know - but if you let me know what the configuration you are running with I can try and replicate it at home and do some testing.

**Comment by tellison** [comment]
@sunnychanwork  The entirety of the Jenkins build job is:

```
export ANT_HOME=/cygdrive/C/Projects/OpenJDK/apache-ant-1.10.1
export ALLOW_DOWNLOADS=true
export PATH="/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/amd64/:$PATH"

git clone https://github.com/AdoptOpenJDK/openjdk-jdk8u.git openjdk
cd openjdk
bash configure MAKE=/cygdrive/C/Projects/OpenJDK/make-3.82/make.exe with_freetype=/cygdrive/C/Projects/OpenJDK/freetype --disable-ccache
/cygdrive/C/Projects/OpenJDK/make-3.82/make.exe images
```

and you can see what happens from [a recent build attempt](https://ci.adoptopenjdk.net/job/openjdk_build_x86-64_windows/22/consoleText)

Just let us know if you require more info.

**Comment by sunnychanwork** [comment]
I was able to reproduce it on my own machine but I have not found a solution yet. Once I have found the solution I will report back.

**Comment by sunnythepooh** [comment]
I have been able to reproduce the issue and it seems that the new grep in cygwin is causing the problem:

https://bugs.openjdk.java.net/browse/JDK-8179675

As suggested in the jdk bug report if you downgrade grep back to 2.72 it will work. I have verified this in my local machine.

So I have downgraded grep on the adoptopenjdk build machine and a new build is being launch to see whether it works.

**Comment by sunnythepooh** [comment]
Test build: https://ci.adoptopenjdk.net/job/openjdk_build_x86-64_windows/48/console

**Comment by karianna** [comment]
Looks like it built but then the final artifact name copy is misconfigured.

**Comment by karianna** [comment]
@neomatrix369 - makejdk-any-platform.sh needs to have add the config from https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L183-L205 ?

**Comment by sunnythepooh** [comment]
I have added the archiving and cleaning up steps to jenkins configuration and we now have a successful Windows build:

https://ci.adoptopenjdk.net/job/openjdk_build_x86-64_windows/51/
