### ISSUE TITLE
Enable openjdk10-openj9 systemtest build

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/openjdk-build#295]
This issue is create to track the work to automatically trigger system test builds once openjdk10-openj9 build jobs complete.

**Comment by Mesbah-Alam** [comment]
The following two openjdk10-openj9 systemtest builds were run manually in Adopt 
1) https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_j9_systemtest_x86-64_linux/
2) https://ci.adoptopenjdk.net/view/System%20tests/job/openjdk10_j9_systemtest_ppc64le_linux/

**Comment by Mesbah-Alam** [comment]
The following PR enables automatic triggering of systemtest one x64 and ppc64le linux platforms for openjdk10-openj9: https://github.com/AdoptOpenJDK/openjdk-build/pull/296

**Comment by smlambert** [comment]
Closing as completed (with merge of #296)
