### ISSUE TITLE
Contact page suggests slack, but isn't open to sign-ins

### ISSUE THREAD

**Issue by ctron** [AdoptOpenJDK/openjdk-build#299]
The contact page (https://adoptopenjdk.net/support.html) suggests slack as a medium to contact.

However the slack workspace seems to be closed off:

>  Don't have an account on this workspace yet? Contact the workspace administrator for an invitation

**Comment by karianna** [comment]
Closing and reopening over in https://github.com/AdoptOpenJDK/openjdk-website/issues/246
