### ISSUE TITLE
openjdk9_openj9_build_docker hung earlier today

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#312]
Ref: https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_docker/210 which @adamfarley killed earlier today.

Something similar happened last week on the openjdk10 docker job: https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_docker/16/console

Both appear to have got stuck while doing `g++` compilations.

**Comment by karianna** [comment]
Let's reopen this if it happens again with more info
