### ISSUE TITLE
Add aarch64 platform to the nightly/release pipelines.

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#314]
Relates to https://github.com/AdoptOpenJDK/openjdk-website/issues/251

We changed to incrementally release builds to the website (to ensure nightlies were regular, as we had some platforms that were failing to build for various issues, that would block all platforms from being released).  By doing so, the aarch64 build is no longer being pushed to the website, as the 
aarch64 platform is being built via a shell script at present, and was getting picked up for deployment prior to the pipeline and release tool changes.

We should add it to the pipeline scripts, so that the build/test/deploy story for all platforms is consistent.

**Comment by gdams** [comment]
@smlambert any updates on this?

**Comment by smlambert** [comment]
Sorry, I actually delayed to add them, because it wasn't clear whether @karianna build rewrite was going to use the build pipeline scripts or change up the underlying stuff radically.  But I will proceed with my PR and deal with any changes later.

**Comment by smlambert** [comment]
So an update, is that we did add it to the build pipelines, and the build and tests are triggering properly, the problem must lie with the checksum/release_tool step, investigating further now.

**Comment by smlambert** [comment]
fixed by #318
