### ISSUE TITLE
Remove "Release" build that are actually nightly builds

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#317]
There are multiple release builds on the website that are actually just nightly binaries from a long time ago. These should now be removed and we should plan proper releases. This will make the website look rather empty but I think that it must now be done! Once that has been done then I will update the website to be caled "Latest Release" rather than "Latest Build". FYI @tellison

**Comment by karianna** [comment]
Resolved some time ago
