### ISSUE TITLE
Images are out of date

### ISSUE THREAD

**Issue by agilob** [AdoptOpenJDK/openjdk-build#323]
I build my .war file on Debian testing:

```
~ # java -version 
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
```

then copy generated .war file to `adoptopenjdk/openjdk10:alpine` or `adoptopenjdk/openjdk10` and use generated docker image to start my service.

Application doesn't start:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 53.0
```

Do you have any image that supports class file version 54 or should I build own image and update java?

**Comment by karianna** [comment]
Hi @agilob - Is this an image you got from DockerHub?

**Comment by karianna** [comment]
Note to self - this is likely an issue for the openjdk-docker repo

**Comment by agilob** [comment]
>Is this an image you got from DockerHub?

yes.

**Comment by karianna** [comment]
Actually I'll leave open so @agilob can be notified when we resolve this.

**Comment by agilob** [comment]
I subscribed to the other issue :+1:
