### ISSUE TITLE
AIX test failures on AO8/J9

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#324]
From https://ci.adoptopenjdk.net/view/Weekly%20Tests/job/openjdk8_j9_openjdktest_ppc64_aix_weekly/lastCompletedBuild/#showFailuresLink

The following 57 tests are currently failing (first time we've run this on the current builds - some may of course be environmental. Logging here for reference and to cover what we've done to resolve them

    java/io/File/SetLastModified.java.SetLastModified
    java/io/FileInputStream/LargeFileAvailable.java.LargeFileAvailable
    java/io/FileOutputStream/ManyFiles.java.ManyFiles
    java/io/FileOutputStream/OpsAfterClose.java.OpsAfterClose
    java/io/FilePermission/SpecTests.java.SpecTests
    java/io/FilterOutputStream/BoundsCheck.java.BoundsCheck
    java/io/FilterOutputStream/Write.java.Write
    java/io/InputStream/OpsAfterClose.java.OpsAfterClose
    java/io/InputStream/ReadParams.java.ReadParams
    java/io/InputStream/Skip.java.Skip
    java/io/InputStreamReader/GrowAfterEOF.java.GrowAfterEOF
    java/io/InputStreamReader/NullCreate.java.NullCreate
    java/io/InputStreamReader/One.java.One
    java/io/InputStreamReader/ReadOffset.java.ReadOffset
    java/io/LineNumberInputStream/Available.java.Available
    java/io/LineNumberInputStream/MarkReset.java.MarkReset
    java/io/LineNumberInputStream/Skip.java.Skip
    java/io/LineNumberInputStream/SkipEOL.java.SkipEOL
    java/io/LineNumberReader/MarkReset.java.MarkReset
    java/io/LineNumberReader/Read.java.Read
    java/io/LineNumberReader/ReadReadLine.java.ReadReadLine
    java/io/LineNumberReader/Skip.java.Skip
    java/io/ObjectInputStream/ResolveProxyClass.java.ResolveProxyClass
    java/io/ObjectInputStream/TestObjectStreamClass.java.TestObjectStreamClass
    java/io/OutputStream/WriteParams.java.WriteParams
    java/io/OutputStreamWriter/BoundsCheck.java.BoundsCheck
    java/io/OutputStreamWriter/Encode.java.Encode
    java/io/OutputStreamWriter/NullCreate.java.NullCreate
    java/io/OutputStreamWriter/TestWrite.java.TestWrite
    java/io/OutputStreamWriter/WriteAfterClose.java.WriteAfterClose
    java/io/pathNames/unix/TrailingSlash.java.TrailingSlash
    java/io/pathNames/win32/BadDriveLetter.java.BadDriveLetter
    java/io/pathNames/win32/DriveOnly.java.DriveOnly
    java/io/pathNames/win32/DriveRelativePath.java.DriveRelativePath
    java/io/pathNames/win32/DriveSlash.java.DriveSlash
    java/io/pathNames/win32/bug6344646.java.bug6344646
    java/lang/ClassLoader/Assert.java.Assert
    java/net/MulticastSocket/SetGetNetworkInterfaceTest.java.SetGetNetworkInterfaceTest
    java/net/MulticastSocket/SetLoopbackMode.java.SetLoopbackMode
    java/net/MulticastSocket/Test.java.Test
    java/nio/channels/AsyncCloseAndInterrupt.java.AsyncCloseAndInterrupt
    java/nio/channels/FileChannel/LoopingTruncate.java.LoopingTruncate
    java/nio/channels/FileChannel/Size.java.Size
    java/nio/channels/Selector/RacyDeregister.java.RacyDeregister
    java/nio/file/Files/SBC.java.SBC
    java/rmi/activation/Activatable/downloadParameterClass/DownloadParameterClass.java.DownloadParameterClass
    java/rmi/activation/Activatable/extLoadedImpl/ext.sh.ext
    java/rmi/activation/Activatable/forceLogSnapshot/ForceLogSnapshot.java.ForceLogSnapshot
    java/rmi/activation/Activatable/inactiveGroup/InactiveGroup.java.InactiveGroup
    java/rmi/activation/Activatable/restartCrashedService/RestartCrashedService.java.RestartCrashedService
    java/rmi/activation/Activatable/restartLatecomer/RestartLatecomer.java.RestartLatecomer
    java/rmi/activation/Activatable/restartService/RestartService.java.RestartService
    java/rmi/activation/ActivateFailedException/activateFails/ActivateFails.java.ActivateFails
    java/rmi/activation/ActivationSystem/modifyDescriptor/ModifyDescriptor.java.ModifyDescriptor
    sun/net/www/http/HttpClient/MultiThreadTest.java.MultiThreadTest
    sun/nio/cs/Test4200310.sh.Test4200310
    sun/rmi/transport/tcp/blockAccept/BlockAcceptTest.java.BlockAcceptTest

**Comment by karianna** [comment]
Should be in tests repo?

**Comment by smlambert** [comment]
We have been reporting test issues in openjdk-tests, investigating, and if the failures belong upstream or are already raised upstream, we add/track them at the appropriate projects openj9, openjdk or other adopt repos where appropriate (related: [tests/345](https://github.com/AdoptOpenJDK/openjdk-tests/issues/345),  [tests/346](https://github.com/AdoptOpenJDK/openjdk-tests/issues/346) )

**Comment by karianna** [comment]
I'd prefer the test repo :-)

**Comment by sxa555** [comment]
Moved to https://github.com/AdoptOpenJDK/openjdk-tests/issues/418, therefore closing
