### ISSUE TITLE
openjdk8_openj9 linux builds are failing

### ISSUE THREAD

**Issue by ashu-mehra** [AdoptOpenJDK/openjdk-build#327]
openjdk8_openj9 linux builds have not promoted for almost a week - https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/. 
Latest build job reported this error:
```
Scanner.cpp: In member function 'bool Scanner::checkBlacklistedType(const std::string&) const':
Scanner.cpp:82: error: 'const struct std::basic_string<char, std::char_traits<char>, std::allocator<char> >' has no member named 'front'
gmake[6]: *** [Scanner.o] Error 1
gmake[5]: *** [ddr-scanner] Error 2
```

**Comment by ashu-mehra** [comment]
fyi - @sxa555

**Comment by sxa555** [comment]
@keithc-ca has indicated that this is due to the use of the gcc 4.4.7 compiler which is the default on CentOS 6.9. There is a 4.8.2 installed int he `/opt/rh/devtoolset-2/...` I'll modify the job to set the `CC`/`CXX` variables and see if that resolves it.

**Comment by keithc-ca** [comment]
There _were_ some obstacles to relying on environment variables CC and CXX (e.g. see https://github.com/eclipse/openj9/pull/1891); hopefully there aren't too many more.

**Comment by sxa555** [comment]
Yep this should be a good test ...

**Comment by sxa555** [comment]
That's odd:
```
checking for jtreg... no
checking for /opt/rh/devtoolset-2/root/usr/bin/gcc... no
configure: error: Could not find a C compiler. You might be able to fix this by running 'sudo yum groupinstall "Development Tools"'.
configure exiting with result code 1
```
Despite earlier in the job I do an `ls -l` on it:

```
+ ls -l /opt/rh/devtoolset-2/root/usr/bin/gcc /opt/rh/devtoolset-2/root/usr/bin/g++
-rwxr-xr-x 4 root root 754064 Mar 12  2014 /opt/rh/devtoolset-2/root/usr/bin/g++
-rwxr-xr-x 2 root root 750576 Mar 12  2014 /opt/rh/devtoolset-2/root/usr/bin/gcc
```
Any idea why @keithc-ca ?

**Comment by keithc-ca** [comment]
After the `ls` command, try adding `/opt/rh/devtoolset-2/root/usr/bin/gcc --version` and `/opt/rh/devtoolset-2/root/usr/bin/g++ --version` to get a better sense of whether to expect those compilers to work.

**Comment by sxa555** [comment]
`--version` certainly works when logged into the machine, but the error message seems to be suggesting it can't even find them

**Comment by sxa555** [comment]
Setting `PATH` to have `/opt/rh/devtoolset-2/root/usr/bin/` at the start [appears to allow it to get further](https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/179/console), although if there's an issue with setting the `CC`/`CXX` variables we should address that.

**Comment by keithc-ca** [comment]
The failures noted here are troubling (and confusing).
```
checking for gcc... /opt/rh/devtoolset-2/root/usr/bin/gcc
configure: Resolving CC (as /opt/rh/devtoolset-2/root/usr/bin/gcc) failed, using /opt/rh/devtoolset-2/root/usr/bin/gcc directly.
checking resolved symbolic links for CC... /opt/rh/devtoolset-2/root/usr/bin/gcc
```
likewise for g++
```
checking for g++... /opt/rh/devtoolset-2/root/usr/bin/g++
configure: Resolving CXX (as /opt/rh/devtoolset-2/root/usr/bin/g++) failed, using /opt/rh/devtoolset-2/root/usr/bin/g++ directly.
checking resolved symbolic links for CXX... /opt/rh/devtoolset-2/root/usr/bin/g++
```

**Comment by karianna** [comment]
Resolved
