### ISSUE TITLE
openjdk10/openj9 builds failing due to missing jdk9 release on the main web site

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#333]
There are a couple of reasons why they're failing but this one looks like it could have been the result of some release cleanup work that was done today.

From https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_ppc64le_linux/49/console

```
+ export JDK9_BOOT_DIR=/home/jenkins/workspace/openjdk10_openj9_build_ppc64le_linux/jdk-9+181
+ [ ! -r /home/jenkins/workspace/openjdk10_openj9_build_ppc64le_linux/jdk-9+181 ]
+ wget -O - https://github.com/AdoptOpenJDK/openjdk9-releases/releases/download/jdk-9%2B181/OpenJDK9_ppc64le_Linux_jdk-9.181.tar.gz
+ tar xpfz -
--2018-05-17 13:00:21--  https://github.com/AdoptOpenJDK/openjdk9-releases/releases/download/jdk-9%2B181/OpenJDK9_ppc64le_Linux_jdk-9.181.tar.gz
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-05-17 13:00:21 ERROR 404: Not Found.
```

**Comment by sxa555** [comment]
I'm going to put recent builds that appear ok into `~jenkins` on the following machines and set `JDK9_BOOT_DIR` in the environment of those machines to `/home/jenkins/jdk-9+181`:

build-osuosl-ubuntu1604-ppc64le-1: https://github.com/AdoptOpenJDK/openjdk9-nightly/releases/download/jdk-9%2B181-20180517/OpenJDK9_ppc64le_Linux_20180517.tar.gz
build-marist-ubuntu1604-s390x-[12]: https://github.com/AdoptOpenJDK/openjdk9-nightly/releases/download/jdk-9%2B181-20180517/OpenJDK9_s390x_Linux_20180517.tar.gz

**Comment by karianna** [comment]
This is resolved / no longer supported.
