### ISSUE TITLE
openjdk9/openj9 builds are aborting

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#335]
https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_s390x_linux/

Reasons currently unknown, but seem to be happening on multiple systems. I've adjusted the strategy for aborts a couple of times and have now disabled automatic aborts completely from build #193 so we'll see how it goes ...

**Comment by karianna** [comment]
Did this resolve itself?

**Comment by sxa555** [comment]
Since I removed the timout it hasn't recurred ... Have switched it back to "likely stuck" again for the next build (197)

**Comment by karianna** [comment]
No longer supporting 9 builds.
