### ISSUE TITLE
git-hg 2.0

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#339]
The various scripts in the `openjdk-build/git-hg` folder are being pared down to just 3:

* `updateforesttags.sh` (this will get renamed to `mirrorMercurialIntoGitForJava8And9.sh` - For Java 8 and 9 mirroring
* `mirrorMercurialIntoGit.sh` - For Java 10+ mirroring (including amber, valhalla etc)
* `import-common.sh` - Common Functionality between the two scripts

- [x] Rename _updateforesttags.sh_ to _mirrorMercurialIntoGitForJava8And9.sh_
- [x] Refactor _mirrorMercurialIntoGitForJava8And9.sh_ to use _import-commons.sh_ common functionality
- [x] In _mirrorMercurialIntoGitForJava8And9.sh_ Add mirroring of HEAD from `master` into `master` and `master` into `dev`
- [x] Cut over all git-hg jobs
- [x] Remove all old git-hg scripts

**Comment by karianna** [comment]
See also #349

**Comment by karianna** [comment]
New Plan:

- [ ] Make each module in mercurial have a submodule equivalent in git
- [ ] For tags - When applying a 'regular' patch simply apply it on each tag.  When applying a patch that's part of the generated build script set then rerun that script
- [ ] For nightlies - When applying any patch, un-apply the patch, merge code in from mercurial and then reapply the patch and any auto-generate script and see if the error code is 0.

**Comment by johnoliver** [comment]
this should be done
