### ISSUE TITLE
OpenJ9 Large Heap (noncompressedrefs) build

### ISSUE THREAD

**Issue by theresa-m** [AdoptOpenJDK/openjdk-build#341]
OpenJ9 has created a "Large Heap" package for the non-compressedrefs mode to support users that need > ~57 gig heaps. We would like to have these built & tested with AdoptOpenJDK for **xLinux** for **JDK8 and newer releases (JDK10+).**

We would like this to also be JCK certified, though we can live without it initially.

This is the OpenJ9 issue tracking this project: https://github.com/eclipse/openj9/issues/1669

**Comment by karianna** [comment]
@theresa-m do you or another OpenJ9 person know what the additional parameters are required to build this variant over and above the regular OpenJ9 build?

**Comment by karianna** [comment]
OK, it may be awhile before we pick this up - we have some underlying build script fixes we need to get out before we add more variants, do poke us if it's more than a few weeks!

**Comment by gdams** [comment]
thanks for creating this @theresa-m! I'll try and take a look at setting up a test build this week

**Comment by gdams** [comment]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_openj9_build_x86-64_linux_largeHeap/ has been created

**Comment by theresa-m** [comment]
thanks @gdams these look great! I'm running some tests on the jdk just to be thorough but the build looks right.

**Comment by smlambert** [comment]
If you are happy with the build @theresa-m, we can also enable some automated testing on it at ci.adoptopenjdk

**Comment by gdams** [comment]
we probably want to add a cron to it so that it builds perodically

**Comment by smlambert** [comment]
Do you want it on a weekly cadence?  We can add a schedule in the Jenkins config, and I will trigger test runs from the build directly (unless we go the route of adding to full nightly pipelines, but that may be overkill).

**Comment by theresa-m** [comment]
@DanHeidinga what do you think for Shelley's question?

**Comment by sxa555** [comment]
I think we're probably ok from a build machine perspective in terms of running these on a regular basis - our xLinux builds are reasonably performant and not currently a limiting factor in our pipeline times so unless there are any fundamental objections (tagging in @karianna as he probably hasn't been following this) I suspect we could contain it being run nightly at the moment.

@DanHeidinga Will this only ever be required for Linux/x64 or (do you envisage | is there support for) other platforms too?

**Comment by DanHeidinga** [comment]
We've been targeting this to xLinux only based on the initial interest for the larger heap builds.  

I can't rule out extending this to other platforms in the future if the demand is there but there are no immediate plans to do so.

**Comment by llxia** [comment]
Test Jenkins files need to be updated for noncompressedrefs
fyi @sophia-guo

**Comment by smlambert** [comment]
Working on a combined PR for this and Win32 build in https://github.com/smlambert/openjdk-build/tree/addNewSpecs and https://github.com/smlambert/openjdk-tests/tree/addMoreSpecs

**Comment by sophia-guo** [comment]
@gdams  The job https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_openj9_build_x86-64_linux_largeHeap/  is configured to @sxa555  personal branch create_jre. Probably need to update. I guess it was initially created by copy of https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/ .

**Comment by theresa-m** [comment]
According to @smlambert this can be closed now. Thanks to all who helped put the build together!

**Comment by smlambert** [comment]
Thanks @theresa-m !  And for sure, if we want to add more large heap builds for other versions or platforms, we can either reopen or create a new issue.  👍
