### ISSUE TITLE
Create Win32 release builds of openjdk8+openj9

### ISSUE THREAD

**Issue by ChengJin01** [AdoptOpenJDK/openjdk-build#342]
Given that we already provided support on JDK8 32bit + OpenJ9 at https://github.com/eclipse/openj9/blob/master/buildenv/Build_Instructions_V8.md#windows, we'd like to get the JDK8 builds (Windows 32bit) built and tested at AdoptOpenJDK for the next OpenJ9 release.

**Comment by DanHeidinga** [comment]
@ChengJin01 Was there additional machine configuration required to build the 32 bit JDK?  Can you highlight any differences here?

**Comment by ChengJin01** [comment]
Given that all issues with freeType were fixed, the remaining configuration should be fine with --target=x86 --with-target-bits=32 before compilation (we already made changes at Eclipse/OpenJ9 to get this mk/config work).

**Comment by sxa555** [comment]
Initial run now executing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_openj9_build_x86-32_windows

**Comment by gdams** [comment]
FYI you'll need to modify the release job here https://github.com/AdoptOpenJDK/openjdk-website-backend/blob/master/sbin/Release.sh#L48

**Comment by sxa555** [comment]
Initial builds created at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_openj9_build_x86-32_windows/

(Also hotspot job created but not yet succeeding at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_build_x86-32_windows/)

**Comment by ChengJin01** [comment]
[_sanity.functional_jdk8u172-b11_openjdk8_openj9_build_x86-32_windows.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/2037882/_sanity.functional_jdk8u172-b11_openjdk8_openj9_build_x86-32_windows.txt)

I ran sanity tests from functional/Java8andUp locally with the build created at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_openj9_build_x86-32_windows/  (via Cygwin on a Win 7 Pro 64-bit OS) and all tested buckets passed except one which doesn't exist as follows:

TOTAL: 38   EXECUTED: 28   PASSED: 27   FAILED: 1  SKIPPED: 10
 (the only failing buckets is AttachAPISanity_SE80_0 which doesn't exist)

So, the build functionally works good as expected.

**Comment by sxa555** [comment]
I have also verified that the builds work on a purely 32-bit OS (Well, they get a far as running `java -version` correctly :-)

**Comment by ChengJin01** [comment]
@smlambert  @llxia ,  is there any other test we are able to run to verify the 32-bit build created at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_openj9_build_x86-32_windows/ (not manually run) ?

**Comment by llxia** [comment]
No, I think that is the only one we have so far. @sophia-guo is working on wins builds. She maybe able to tweak something for you, but we do not have one ready to use. As far as I know, the win machine configuration is not finalized. AdoptOpenJDK and OpenJ9 wins machines are configured differently.

**Comment by ChengJin01** [comment]
The Win 32-bit has been added to the openjdk8_openj9 nightly build pipelines via https://github.com/AdoptOpenJDK/openjdk-build/pull/355

**Comment by smlambert** [comment]
Yes, though based on the build failure mentioned above, tonights run will fail, and not trigger any testing.  Once the build issue is corrected and build jobs complete successfully, a subset of ~2900 openjdk regression tests will be triggered against them (we can triage those, and later decide if we should add system tests to the set or not).

**Comment by smlambert** [comment]
openjdk8-openj9 Win32 nightly builds are now being published to the website, this can now be closed.
