### ISSUE TITLE
Add openjdk10 aarch64 builds to the pipelines

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#343]
As discussed with @smlambert in #build on slack the builds at https://ci.adoptopenjdk.net/job/openjdk10_build_arm64_linux/ aren't being run regularly via the pipelines and are not publishing so there are no regular nightlies popping up

**Comment by gdams** [comment]
should just be a case of adding some code to https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk8_build_arm64_linux/ws/build/buildoutput/

**Comment by smlambert** [comment]
buildMaps['arm64'] = [test:['openjdktest'], ArchOSs:'arm64_linux']

**Comment by vielmetti** [comment]
Thanks for looking at this.
