### ISSUE TITLE
openJDK9 with openJ9 seems to be missing jps binary files.

### ISSUE THREAD

**Issue by cwsolee** [AdoptOpenJDK/openjdk-build#345]
We're trying to use nightly but we notice something is missing in this https://github.com/AdoptOpenJDK/openjdk9-openj9-nightly/releases/download/jdk-9%2B181-20180523/OpenJDK9-OPENJ9_s390x_Linux_20180523.tar.gz , jps binary file is not included in this build. The open source package that we tried to build is elasticsearch. Hotspot is ok.

**Comment by sxa555** [comment]
@Andrew-m-leonard @DanHeidinga can one of you take a look at this one please?

**Comment by DanHeidinga** [comment]
OpenJ9 doesn't currently support the OpenJDK commandline tools like jps, jstack, etc.  Let's move this discussion to the OpenJ9 project in the existing issue: https://github.com/eclipse/openj9/issues/1621

@sxa555 Can you close this?
