### ISSUE TITLE
Binary download checksums should be SHA-2 not MD5

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#35]

**Comment by Joe-Brady** [comment]
https://github.com/AdoptOpenJDK/openjdk-nightly/releases/download/jdk8u152-b01-20170404/OpenJDK8_s390x_Linux_20170404.sha256.txt

That's an example of the checksums that George added.

I'm no expert, but isn't that the right type already? If yes, I think there was just some miscommunication on Slack!

**Comment by karianna** [comment]
@Joe-Brady You're totally right.
