### ISSUE TITLE
OpenJDK release level for OpenJ9 nightly builds incorrect

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#351]
On the OpenJ9 nightly build pages the release levels shown do not match the actual levels used in the builds.

https://adoptopenjdk.net/nightly.html?variant=openjdk8-openj9
For Java 8 the OpenJDK release level shows jdk8u162-b12 but its actually jdk8u172-b11

https://adoptopenjdk.net/nightly.html?variant=openjdk9-openj9
For Java 9 the OpenJDK release level shows jdk-9+181-20 but its actually jdk-9.0.4+12

https://adoptopenjdk.net/nightly.html?variant=openjdk10-openj9
For Java 10 the OpenJDK release level shows jdk-10+46-20 but its actually jdk-10.0.1+10

Strangely, the directory name in the tar files is correct.

**Comment by pshipton** [comment]
@sxa555 fyi

**Comment by sxa555** [comment]
[AO10/J9 pipeline](https://ci.adoptopenjdk.net/view/Pipelines/job/openjdk10_openj9_nightly_pipeline_scm/) updated to default to the correct tag too
