### ISSUE TITLE
Java 11+ JRE images - change in build targets

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#356]
From OpenJDK

> I would like to make everyone aware of an impending change to JDK 11 concerning the images we build. In [1], currently under review [2], the jre-image will no longer be built by the "images" make target. Oracle intends to no longer ship the JRE in its current form and so we do no longer wish to build it. It will still be possible to build it using the make target "legacy-jre-image" (and "mac-legacy-jre-bundle" for the macos specific image). This should serve the need of any OpenJDK distributor that still wants to produce the legacy jre, while making it clear that it is slated for complete removal in a future release. The "product-bundles" target will no longer produce bundles of the legacy jre.

**Comment by oakad** [comment]
@pbi-qfs That's what `jlink` is supposed to be for these days. If you want to ship a chopped down jvm with your app, just use `jlink` to leave the unnecessary modules out.

If you look at the JDK structure, the actual java compiler bit is not that large - not much is saved by simply shipping a "compiler-less" jvm (as opposed to carefully applied `jlink`).

**Comment by pbi-qfs** [comment]
@oakad Thanks, I know about `jlink`, but that unfortunately does not solve the missing JRE problem:
* Afaik you have to modularize your software, and in some situations, that's just not feasible (yet).
* If you allow user extensions via scripting, the user relies on having the full JRE available, not just the modules randomly required by the application core.

**Comment by oakad** [comment]
On the other hand, there is no option in the Openjdk build script which says "build jre". So by necessity, all builds are "jdk" whereupon you can cull that down to obtain a "jre".

So the question is: what exactly do you want to remove from the jdk tarball? If it's only the compiler, I assure you that the volume savings will be rather less than impressive. :-)

**Comment by karianna** [comment]
There's still a target to make legacy JRE in the 11 code stream, not sure if/when it will be removed.

**Comment by oakad** [comment]
I can't see it in `configure --help`, so while I trust you that it's there somewhere, it's clearly not made to be found easily. :-)

**Comment by karianna** [comment]
See my original comment, it's reportedly a hidden option :-)

**Comment by karianna** [comment]
Closed via #582
