### ISSUE TITLE
OpenJ9 s390x builds failing (all versions) - ccache-related issue

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#364]
Initially raised in the comments in https://github.com/eclipse/openj9/issues/1919
Then raised specifically against OMR at https://github.com/eclipse/omr/issues/2567
Affects all release (8, 9, and 10)
https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_s390x_linux/
https://ci.adoptopenjdk.net/job/openjdk9_openj9_build_s390x_linux/
https://ci.adoptopenjdk.net/job/openjdk10_openj9_build_s390x_linux/

```
checking build system type... s390x-ibm-linux-gnu
checking host system type... s390x-ibm-linux-gnu
checking OMR_HOST_OS... linux
checking OMR_HOST_ARCH... s390
checking for gcc... CCACHE_COMPRESS=1  CCACHE_SLOPPINESS=time_macros /usr/local/bin/ccache /usr/bin/gcc-4.8
checking whether the C compiler works... no
configure: error: in `/home/jenkins/workspace/openjdk8_openj9_build_s390x_linux/openjdk/build/linux-s390x-normal-server-release/vm/omr':
configure: error: C compiler cannot create executables
See `config.log' for more details
run_configure.mk:167: recipe for target 'CONFIGURE_SENTINEL_FILE' failed
gmake[3]: *** [CONFIGURE_SENTINEL_FILE] Error 77
buildtools.mk:158: recipe for target 'configure' failed
gmake[2]: *** [configure] Error 2
gmake[2]: *** Waiting for unfinished jobs....
```

**Comment by sxa555** [comment]
Have temporarily renamed `/usr/local/bin/ccache` to `/usr/local/bin/ccache-SXACRIPPLED` and likewise for `/usr/bin/ccache` on build-marist-ubuntu1604-s390x-2 and build-marist-ubuntu1604-s390x-3

**Comment by gdams** [comment]
you can add a configure arg that skips using ccache

**Comment by sxa555** [comment]
Not trivially as our scripts add in the enable-ccache flag if it detects that ccache is on the machine IIRC

**Comment by dnakamura** [comment]
Still waiting on java side  PRs to be merged, but in the mean time `export CONFIG_SHELL=bash` should resolve the issue

**Comment by sxa555** [comment]
IIRC I tried setting CONFIG_SHELL and it didn't work, but the PR that was put in appears good therefore closing
