### ISSUE TITLE
Building jdk8-with-graal on MacOS

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#369]
To help the [Graal/GraalVM](http://www.graalvm.org) community it would be a good idea to build `jdk8-with-graal` on the MacOS, as this will facilitate making such binaries available to the growing community. The binary will be based off the [JDK8 built by the Adopt OpenJDK build farm](https://adoptopenjdk.net/releases.html?variant=openjdk8).

Source codes to be used to create the build can be found at https://github.com/oracle/graal

Other know dependences:
- Make versions 3.8.1
- XCode 4.9.1
- Python 2.7

Scripts to build it on the MacOS are available, they have been so far tested to run on both local and docker environments. This should be a straightforward binary to build.

Instructions on how to build - https://github.com/oracle/graal/blob/master/compiler/README.md

*Note: this is not the same GraalVM suite we download from http://www.graalvm.org/downloads/ which is a couple more steps*

Next step: build the GraalVM suite

**Comment by neomatrix369** [comment]
I have been building JDK8 with graal on Linux, MacOS and inside the docker container on my local machine and it has worked fine when the specific versions of `make` and `xcode` are present.

**Comment by karianna** [comment]
Hi Mani,

I've assigned to you.  Some new build scripts are about to come in so you might want to build off that.  Ping @johnoliver for details

**Comment by neomatrix369** [comment]
Cool! Thanks

The graal build scripts are pretty small and simple, I'll first get it to build an artifact on Adopt and then lets take it from there

**Comment by neomatrix369** [comment]
On the current MacOS build box we need to install `xcrun`, based on the following error msg:
```
Generating precompiled header precompiled.hpp.pch
xcrun: error: unrecognized option: --show-sdk-path

Usage: xcrun [options] <utility> ... arguments ...
```

**Comment by karianna** [comment]
I think it's saying it didn't recognize the option, so perhaps the wrong version of that tool?

**Comment by neomatrix369** [comment]
`jenkins` user might not have access to that folder:
 
 ```0 drwxr-xr-x   5 wheel   170 12 Jul  2017 Xcode.app
 0 drwxr-xr-x   3 admin   102 13 Jul  2017 Xcode.app.7.2.1```

I'm thinking its access rights, the folder exists, when I ssh on the box

**Comment by neomatrix369** [comment]
Raised a couple of issues:
- https://github.com/AdoptOpenJDK/openjdk-build/issues/93#issuecomment-399652750
- https://github.com/AdoptOpenJDK/openjdk-docker/issues/32

**Comment by karianna** [comment]
This seems to be working on CI https://ci.adoptopenjdk.net/job/jdk8-with-graal_build_x86-64_macos/
