### ISSUE TITLE
Need for OpenJ9 Java 9 (0.9) Release at Adopt

### ISSUE THREAD

**Issue by babsingh** [AdoptOpenJDK/openjdk-build#370]
Previously, OpenJ9 Java 9 releases were available at AdoptOpenJDK.

To access OpenJ9 Java 9 releases, the following AdoptOpenJDK API is available: https://api.adoptopenjdk.net/openjdk9-openj9/releases/x64_linux/latest/binary (https://github.com/AdoptOpenJDK/openjdk-api).

In OpenJ9, DockerFile(s) to build Java 10 are dependent on Java 9 as the boot JDK. The above AdoptOpenJDK API was used to get OpenJ9 Java 9 from AdoptOpenJDK. 

Suddenly, AdoptOpenJDK removed all Java 9 releases. The above API can't be used. In OpenJ9, DockerFile(s) to build Java 10 don't work anymore (https://github.com/eclipse/openj9/issues/2152).

Even though, AdoptOpenJDK stopped supporting Java 9. Instead of removing all Java 9 releases, they should have a final/last release of Java 9 available. This way others who are dependent on AdoptOpenJDK API won't be impacted.

Nightly builds for Java 9 are still running. I would like to request a final release of Java 9 builds of OpenJ9, following which OpenJ9 will not make any efforts to keep Java 9 working.

**Comment by babsingh** [comment]
fyi - @pshipton

**Comment by pshipton** [comment]
@sxa555 fyi

**Comment by pshipton** [comment]
I expect OpenJ9 will drop all support and builds for Java 9 after the 0.9.0 release. The release at Adopt can be the final build, with no further nightly builds of Java 9 required afterwards.

**Comment by sxa555** [comment]
We are working on getting all the release builds back in place (although at the moment 9 is at the bottom of that list) - stay tuned :-)

Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/317

**Comment by sxa555** [comment]
The `java_util` one is interesting - difference in fr_FR vs fr:

```
ResourceBundleT200: Failed. FAIL-> Expected: greetings from Msgs_fr_FR.properties, Actual: greetings from Msgs_fr.properties
```
No issues with any of the other resource bundle tests, only the French one - will verify whether it happens on HotSpot builds as well as J9

**Comment by sxa555** [comment]
Now that OpenJ9 0.9 has been release I'll get this done over the next few days (We don't currently have a release pipeline for AO9/J9 so I'll need to put one together but that won't take long)

**Comment by sxa555** [comment]
Released and on the main download site - all platforms available from the archive page at https://adoptopenjdk.net/archive.html?variant=openjdk9&jvmVariant=openj9
