### ISSUE TITLE
Windows 64-bit build is actually 32-bit build

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#371]
I received a report from a user that the x64 Windows build in the Java 8 nightlies is actually a 32-bit build. It was unspecified exactly which one was tried, but guessing June 13.

https://adoptopenjdk.net/nightly.html?variant=openjdk8-openj9

@sxa555 @smlambert

**Comment by gdams** [comment]
this will be to do with the naming I imagine

**Comment by pradeep-b** [comment]
@pshipton Here is the build I used and later realized it actually has 32-bit binaries! 
```
OpenJDK8-OPENJ9_x64_Win_20180607
```

**Comment by smlambert** [comment]
The resolution of #381 should resolve this as the Release.sh script takes the OS from the artifact name, and publishes the release with it.

I will keep this open, until we see the results of the next openjdk9-openj9 nightly pipeline to confirm there are no other steps that need to occur to correctly publish this build.

**Comment by pradeep-b** [comment]
Earlier today I used build `OpenJDK8-OPENJ9_x64_Windows_201818061207` and it does have 64-bit binaries as expected.

**Comment by smlambert** [comment]
<img width="533" alt="screen shot 2018-06-19 at 11 07 46 pm" src="https://user-images.githubusercontent.com/2836948/41635544-5f80488a-7417-11e8-8448-3585cc6a14c7.png">

Confirmed that this has now been corrected on the website.

**Comment by pradeep-b** [comment]
I believe the info on the website was correct. The problem was in the contents of the x64 zip.

Anyway, as I mentioned [earlier](https://github.com/AdoptOpenJDK/openjdk-build/issues/371#issuecomment-398484137), the latest zip has the 64-bit binaries as expected.

**Comment by smlambert** [comment]
For 2 consecutive days, we were publishing win32 and win64 nightly builds and pushing them to the website as win64 builds (both in .zip files that had x64_win in the name).  If you happened to click on the slightly larger one (84MB), you would get the x64 build, if you clicked on the slightly smaller one (77MB) you'd get the x32 build.  They are now titled correctly and differentiated on the website and api.
