### ISSUE TITLE
Build configuration of openjdk8_build_aarch64_linux failed openjdk8 tests on aarch64_linux

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#378]
openjdk8 build on arm64 is using a separate build story( i.e, not the script from openjdk-build repo.
https://ci.adoptopenjdk.net/job/openjdk8_build_aarch64_linux/configure

Post action of archive the artifacts is also different from other builds. There are lots of different type of files are archived, which failed corresponding test build. https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_aarch64_linux/5/console . Test build get SDK artifacts by default.

**Comment by sophia-guo** [comment]
@gdams FYI

**Comment by karianna** [comment]
@sophia-guo Can you detail what you're missing or what is causing the test scripts to fail?

**Comment by sophia-guo** [comment]
I don't think [the build](https://ci.adoptopenjdk.net/job/openjdk8_build_aarch64_linux/) is active any more, which is replaced by [the new one](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-hotspot/). So we can just close this isse and better to delete [the old one.](https://ci.adoptopenjdk.net/job/openjdk8_build_aarch64_linux/)
