### ISSUE TITLE
Implement short expiry keys mechanism for those that need temporary admin access

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#38]
We have a growing number of Linux-based machines that require administering, and at present are sharing the secrets amongst a small set of people managing the infrastructure.

To ensure that the system remains stable and secure we prefer to grant limited time access to people (and bots/processes) who need machine access for administering them, and keep the master secrets to a very small group of owners.  The 'ownership' group tends to be people who are ultimately responsible for activity on those machines, i.e. through legal contract with the service provider / employer.

Proposal is to implement expiring ssh access as described here
https://linux-audit.com/granting-temporary-access-to-servers-using-signed-ssh-keys/

**Comment by tellison** [comment]
I've documented how this will work [on the wiki](https://github.com/AdoptOpenJDK/openjdk-build/wiki/[WIP]-Temporary-admin-access-to-build-machines).

I'd appreciate comments and scrutiny on the approach before trying it out on our machines.

I did consider having a CA chain for different owners, but figured we can move to that later if required, and for now we can likely live with one owner.

**Comment by karianna** [comment]
LGTM - Since a user will be in as the admin user and using sudo - are we able in logs to track actually *who* was working on a machine (via the temp pub key?).

**Comment by tellison** [comment]
yes, once you login with your signed key the authentication log will show the ID we baked in, i.e. you'll see a line something like

> Accepted publickey for admin from 128.66.3.42 port 123 ssh2: ECDSA-CERT ID karianna (serial 1) CA ECDSA fingerprint...

When an owner signs the user's key they will use the user's Github id to identify them this way.

**Comment by karianna** [comment]
Hmm, what about for non linux hosts?  Mac OS X we can probably do the same, not sure about the windows box...

**Comment by tellison** [comment]
agreed.  MacOS will be fine, but I'm not familiar with best practise for Windows.  Suggestions welcome.

**Comment by tellison** [comment]
OK, this procedure for Linux-based systems is described [in the wiki](https://github.com/AdoptOpenJDK/openjdk-build/wiki/[WIP]-Temporary-admin-access-to-build-machines)

Any further comments?

**Comment by karianna** [comment]
There's a plan in place for this in the security repo.
