### ISSUE TITLE
Windows 32 bit build files named incorrectly

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#381]
The Windows 32 bit build files contain "_x64_" in their name as opposed to something which denotes x86 32 bit - e.g. OpenJDK8_x64_Windows_201818061138.zip

**Comment by smlambert** [comment]
I've updated the jobs to create the artifact with the x32 name, not x64.
<img width="726" alt="screen shot 2018-06-19 at 1 29 37 pm" src="https://user-images.githubusercontent.com/2836948/41613903-ff0975dc-73c4-11e8-9db7-62597b4b8aec.png">

**Comment by smlambert** [comment]
I believe this will now be properly parsed by the [Release.sh script](https://github.com/AdoptOpenJDK/openjdk-website-backend/blob/master/sbin/Release.sh#L26)  and will then publish to the website as a correctly titled artifact (thus addressing issue #371 as well).
