### ISSUE TITLE
openjdk build version breaks maven-enforcer java version check & perhaps other tools

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#387]
Originally from: https://github.com/AdoptOpenJDK/TSC/issues/26

Summary - request version strings from adoptopenjdk builds are more similar to existing java builds and work properly with the maven enforcer plugin...

Detail.....

I have been working on Apache Atlas, and our work has now moved to the Linux Foundation->ODPi->egeria project. In both cases the code is java based and makes use of the maven enforcer plugin to check the Java level being used to build the code. This helps us with consistency and making sure developers are not using the wrong JDK version, and to a lesser extent, very back level update.

Until now most developers have been using the Oracle JDK on macOS/Windows, and the distribution provided openjdk variations under Linux (in some cases Oracle too). However with Oracle charging for 1.8 support soon, and not being ready to move we have decided to move to openjdk throughout as our recommended version, and ideally obtained from adoptopenjdk

Our top level maven pom is at https://github.com/odpi/egeria/blob/master/pom.xml - and you'll see at the base of this some enforcer rules including
<requireJavaVersion>
<level>ERROR</level>
<version>[1.8.0-151,)</version>

which means use JDK 1.8 update 151 or above

Docs on the maven enforcer plugin are at https://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html

However when using an adoptopenjdk jdk for macos/windows, this tool is not allowing us to pass the version check. Indeed when I run java version I find something interesting:

From OpenJDK8_x64_Mac_jdk8u172-b11.tar.gz I seem to get:

15:43 $ java -version
openjdk version “1.8.0-adoptopenjdk”
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_02_01-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Whilst oracle gives me

15:43 $ java -version
java version “1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
and an existing openjdk build from ubuntu:
meanwhile the openjdk install from my friendly ubuntu system (from their repo - not adoptopenjdk) - albeit u171 - is reporting:
14:59 $ java -version
openjdk version “1.8.0_171”
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

Both pass the checks fine!

It's alo worth noting that if I look at actual java properties, the oracle jdk has:
   java.vm.version = 25.171-b11
Whilst the adoptopenjdk build has
   java.vm.version = 25.71-b00

The IMPACT of this is that I cannot use adoptopenjdk builds as a 'slot in' replacement for this project - which was our plan! I *could* write a custom java version checker, but my questions would be

a) Why is the version string so different, and why in particular does it not include the update level (ie 171 or 172)
b) Why is the java.vm.version seemingly missing an entire digit

What I would LIKE is for the openjdk build to work properly with the maven-enforcer plugin out of the box - be it by updating that tool (we could contribute a patch if we have good reason) or by changing the version string openjdk provides and ensuring it can be parsed by the existing algorithm

I'll look at providing a simple test case/git (basically just that pom fragment & dependency & then running it with mvn enforcer:display-info) [note I'm using maven 3.5.3]

(Ref: original discussion at https://adoptopenjdk.slack.com/archives/C09NLQQAV/p1529678802000497 )

**Comment by karianna** [comment]
Test repo is at https://github.com/planetf1/adoptopenjdk-mvntest.git

Use maven 3.5.0 or above

Note that the .171/172 info is lost - and so the check will fail

✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:20 $ mvn enforcer:display-info
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme.tester:mvntest >-----------------------
[INFO] Building Adoptopenjdktest 0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:display-info (default-cli) @ mvntest ---
[INFO] Maven Version: 3.5.3
[INFO] JDK Version: 1.8.0_172 normalized as: 1.8.0-172
[INFO] OS Info: Arch: x86_64 Family: mac Name: mac os x Version: 10.13.6
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.535 s
[INFO] Finished at: 2018-06-22T23:20:42+01:00
[INFO] ------------------------------------------------------------------------
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:20 $ java -version
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:20 $ jenv versions
  system
  1.8
  1.8.0-adoptopenjdk
  1.8.0.172
  10.0
  10.0.1
  10.0.1-adoptopenjdk
  9.0
  9.0.4
  openjdk64-1.8.0-adoptopenjdk
  openjdk64-10.0.1-adoptopenjdk
* oracle64-1.8.0.172 (set by /Users/jonesn/.jenv/version)
  oracle64-10.0.1
  oracle64-9.0.4
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:21 $ jenv global 1.8
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:21 $ java -version
openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_02_01-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:21 $ cd adoptopenjdk-mvntest/
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]
23:21 $ mvn enforcer:display-info
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme.tester:mvntest >-----------------------
[INFO] Building Adoptopenjdktest 0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:3.0.0-M1:display-info (default-cli) @ mvntest ---
[INFO] Maven Version: 3.5.3
[INFO] JDK Version: 1.8.0-adoptopenjdk normalized as: 1.8.0
[INFO] OS Info: Arch: x86_64 Family: mac Name: mac os x Version: 10.13.6
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.480 s
[INFO] Finished at: 2018-06-22T23:22:08+01:00
[INFO] ------------------------------------------------------------------------
✔ ~/src/adoptopenjdk-mvntest [master|●1✚ 1…5]

**Comment by planetf1** [comment]
Is there any outlook on whether any change may get made, the direction the code may go in. WOuld it apply to 1.8?
This issue is preventing my project from moving to openjdk, but I could either slacken the check temporarily, or implement a custom maven enforcer rule as per https://maven.apache.org/enforcer/enforcer-api/writing-a-custom-rule.html using my own java version checker & based on the current strings (for example I may check java.version (ok for oracle and regular openjdk), but if that fails implement a fallback strategy of checking the date (ok for adoptopenjdk). How hard could it be ;-)

**Comment by karianna** [comment]
We'll likely 'fix' this for all builds going forwards.  Hopefully in the next few weeks.

**Comment by planetf1** [comment]
Is there any news on this?
Will this be done in time for the next java update 8. 181/182 ?

**Comment by karianna** [comment]
@johnoliver - Can we take a look at this as part of the 2.0.0 scripts?  I'm not sure we *can* change our version string to match, but we can still be a little flexible to help 3rd party tooling at this stage.

**Comment by johnoliver** [comment]
I do not believe I have changed anything in that area, so the current behaviour will not have changed. But I can take a look

**Comment by karianna** [comment]
Yeah I think we need to fix and old outstanding bug here - its the `configuringVersionStringParameter` function starting on line 169 in build.sh in the new build scripts.  I'm going to try one of your recent releases and see what it says.

**Comment by planetf1** [comment]
If it helps the algorithm that particular maven tool uses is documented here:
https://maven.apache.org/enforcer/enforcer-rules/requireJavaVersion.html

which seems reasonable. 

I had also thought java.vm.version could be an option - less preferable, but would at least then need the same algorithm for oracle+openjdk.. But for 171 at least the number is bad (71 instead of 171)

**Comment by karianna** [comment]
For reference the latest 10 builds from the new build scripts produce:

```
openjdk version "10.0.1-adoptopenjdk" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1-adoptopenjdk+10)
OpenJDK 64-Bit Server VM (build 10.0.1-adoptopenjdk+10, mixed mode)
```

**Comment by karianna** [comment]
The Java 8 logic is different so we'll need to check that as well

**Comment by karianna** [comment]
For java 9? and definitely 10+ we can use:

```
--with-version-string=<string> - Specify the version string this build will be identified with.
--with-version-<part>=<value> - A group of options, where <part> can be any of pre, opt, build, major, minor, security or patch. Use these options to modify just the corresponding part of the version string from the default, or the value provided by --with-version-string.
```

**Comment by planetf1** [comment]
Java 10 looks much closer.. One thing I did note. I think java.vendor.version may be mandatory now in the Java10 spec? Yet on the openjdk build I have (+10, 20180417) there is no such property visible from java -XshowSettings:properties (though that is non mandatory)

**Comment by planetf1** [comment]
I note there's a few subtle differences in formatting like use of quotes -- again this may not be a standards issue. Not checked with code yet

19,20c19,20
<     java.runtime.name = Java(TM) SE Runtime Environment
<     java.runtime.version = 10.0.1+10
---
>     java.runtime.name = OpenJDK Runtime Environment
>     java.runtime.version = 10.0.1-adoptopenjdk+10
27,28c27
<     java.vendor.version = 18.3
<     java.version = 10.0.1
---
>     java.version = 10.0.1-adoptopenjdk
32c31
<     java.vm.name = Java HotSpot(TM) 64-Bit Server VM
---
>     java.vm.name = OpenJDK 64-Bit Server VM
36,37c35,36
<     java.vm.vendor = "Oracle Corporation"
<     java.vm.version = 10.0.1+10
---
>     java.vm.vendor = Oracle Corporation
>     java.vm.version = 10.0.1-adoptopenjdk+10

**Comment by planetf1** [comment]
Here's differences for my Java 8
```
26,27c26,27
<     java.runtime.name = Java(TM) SE Runtime Environment
<     java.runtime.version = 1.8.0_172-b11
---
>     java.runtime.name = OpenJDK Runtime Environment
>     java.runtime.version = 1.8.0-adoptopenjdk-jenkins_2018_05_19_02_01-b00
34c34
<     java.version = 1.8.0_172
---
>     java.version = 1.8.0-adoptopenjdk
36c36
<     java.vm.name = Java HotSpot(TM) 64-Bit Server VM
---
>     java.vm.name = OpenJDK 64-Bit Server VM
41c41
<     java.vm.version = 25.172-b11
---
>     java.vm.version = 25.71-b00
```
which just confirms that bad java.vm.version plus the runtime.version string differences we've been referring to here

**Comment by karianna** [comment]
Perfect thanks for that - we'll keep digging here.

**Comment by karianna** [comment]
Should be resolved in the latest nightlies, please let us know if you get unexpected results!

**Comment by minhtran83** [comment]
@karianna do you know latest nightly build of openjdk8 included the fix? Thanks

**Comment by karianna** [comment]
I believe that the nightlies should have fixed it, we'd love to know if it hasn't and what the version string is that you're seeing / Maven is complaining about!

**Comment by minhtran83** [comment]
@karianna I will give it a try today and will update you later

**Comment by minhtran83** [comment]
@karianna I would say the latest binary **OpenJDK8U_x64_linux_hotspot_2018-09-30-17-14.tar.gz** fixed the problem

**Comment by karianna** [comment]
Great thank you!

**Comment by planetf1** [comment]
I can confirm this fixes my originally reported issue. (tested on the latest macos published 181 openjdk) . Thanks.
