### ISSUE TITLE
libfreetype causes link issue (segfault+UnsatisfiedLinkError) for SWT (Eclipse IDE) on Fedora 28

### ISSUE THREAD

**Issue by mickaelistria** [AdoptOpenJDK/openjdk-build#390]
This is a followup of the issue initially reported at https://github.com/eclipse/openj9/issues/2239.
The same issue happens with HotSpot and OpenJ9 flavors, for all versions of Java.

`libfreetype.so.6` shipped with AdoptOpenJDK builds seems to often conflicts with other libraries installed on a regular Linux workstation.
For example, when starting Eclipse IDE with any AdoptOpenJDK builds, we either see SegFaults or UnsatisfiedLinkError. This is caused by the SWT library (it's a .so file) trying to load `libharfuzz.so` (which is available on system, not in AdoptOpenJDK build) which itself requires a more recent version of `libfreetype.so` (the one installed in system) than the one shipped with AdoptOpenJDK.

This simply makes impossible to use any SWT/Eclipse-based application with AdoptOpenJDK build.
As a Linux user, I do have X and wayland and many graphical apps installed (which is I guess the case of most people who are using Linux for development or execution of Java-based graphical apps), I find it strange that AdoptOpenJDK ships such common libs as `libfreetype.so` with the risk (and currently it's more than a risk, it's a real effect) of breaking most Linux users.
Is there any use case of graphical java applications on Linux where the user wouldn't have libfreetype already installed?

**Comment by tellison** [comment]
Hi Mickael, fair questions.  Could you drop in on [our Slack](https://adoptopenjdk.net/slack.html) #build channel and say "hi" so we can discuss?

**Comment by DanHeidinga** [comment]
@sxa555 Can you take a look at this?  Thanks

**Comment by moschinski** [comment]
Any update? In fact, it is currently not possible to ship a Java desktop application for Linux bundled with AdoptOpenJDK unless you are willing to risk application crashes. Several Linux distributions used by our customers do not provide the needed libpng12.so.0 library. 

The libfreetype.so.6 library shipped with Azul Zulu 8u202 neither has the libpng12 dependency nor the one to libz.so.1 as it depends only on libc.so.6. Maybe, you could ship a libfreetype library with as few as possible dependencies as well?

**Comment by sxa555** [comment]
@smlambert Is this an issue that we have environments/tests available to detect?

**Comment by smlambert** [comment]
The jdk_awt/jdk_sound/jdk_swing tests should also be triaged for issues (to date those extended openjdk tests are still not fully triaged).  In past, there have been other issues with this library (https://github.com/AdoptOpenJDK/openjdk-tests/issues/136, https://github.com/AdoptOpenJDK/openjdk-build/issues/202, https://github.com/AdoptOpenJDK/openjdk-build/issues/354)

Additionally, we have not yet added the Eclipse tests, as there are some hurdles to automate them.  Those tests may detect this problem (https://github.com/AdoptOpenJDK/openjdk-tests/issues/1000).

**Comment by adamfarley** [comment]
Removal of the bundled freetype (from linux builds) is being covered here:

https://github.com/AdoptOpenJDK/openjdk-build/issues/2133

Will update after the release, once we've tested and merged.

**Comment by adamfarley** [comment]
Done.

@mickaelistria - We no longer include the Freetype Library in linux builds. Can you verify that your issue no longer exists in the latest nightly build?

Also, thank you for your patience. :)

**Comment by mickaelistria** [comment]
I'm not working on the specific case that brought me to open this bug anymore and don't plan to get back to it soon. So I won't be able to test it. Feel free to close this issue at your own convenience.

**Comment by adamfarley** [comment]
Will do.
