### ISSUE TITLE
JRE artifacts are no longer being produced in openjdk8-openj9 builds

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#397]
Previously the openjdk8-openj9 x64_linux builds were modified to produce both a JDK and JRE artifact.  The JRE artifact appears to no longer be found on the [Jenkins job](https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/)

**Comment by sxa555** [comment]
I believe I was temporarily setting the job to build off my branch from this pull request https://github.com/AdoptOpenJDK/openjdk-build/pull/331 in order for the change to only affect that platform, and it got subsequently switched back to the AdooptOpenJDK branch to pick up latest changes before the PR got merged. Once the PR is merged they should show up again.

**Comment by sxa555** [comment]
Now fixed under https://github.com/AdoptOpenJDK/openjdk-build/pull/331 - visible at https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-64_linux/
