### ISSUE TITLE
openjdk8_openj9 win32 builds aren't being published

### ISSUE THREAD

**Issue by DanHeidinga** [AdoptOpenJDK/openjdk-build#398]
The OpenJ9 win32 builds are missing from the nightly build pages.  The last published nightly win32 build was June 20th.  Recent builds are passing but aren't being published.  

It may be due to missing date info in the file name?
```
Your final .zip was created at /cygdrive/c/Users/jenkins/jdk8_j9/openjdk/build/windows-x86-normal-server-release/images
Moving the artifact to /cygdrive/c/Users/jenkins/jdk8_j9/OpenJDK8_x32_Windows_.zip
```
https://ci.adoptopenjdk.net/job/openjdk8_openj9_build_x86-32_windows/44/console

**Comment by DanHeidinga** [comment]
@smlambert @sxa555 This is the win32 builds not being published issue from this morning's OpenJ9 call.

**Comment by smlambert** [comment]
The last published [x32_win build is from June 28th](https://api.adoptopenjdk.net/openjdk8-openj9/nightly/x32_win/latest/).  As Stewart notes, this should now be addressed and fresh build being published shortly to the website or through the adoptopenjdk api.

**Comment by sxa555** [comment]
x32 build has shown up with the latest build :-)
