### ISSUE TITLE
Create AdoptOpenJDK Slack channel

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#4]
I know that there is already a google group for adopt open jdk but I feel that a slack channel would be really beneficial to the organization. CC @karianna

**Comment by karianna** [comment]
There is a slack team :-).  Can you try joining at: adoptopenjdk.slack.com and see if you can request?

**Comment by gdams** [comment]
says that I have to contact the team administrator for access

**Comment by gdams** [comment]
perhaps it's worth setting up https://auth0.com/authenticate/slack/github so that org members can sign up with their github id's

**Comment by gdams** [comment]
I'd be happy to set this up if you're interested

**Comment by gdams** [comment]
short term it would be good to get access to this though

**Comment by karianna** [comment]
Ok, so this became painful as we're not using the paid tier of Slack (therefore can't integrated alternative authentication modes).  I've sent out direct invites in the meantime.
