### ISSUE TITLE
Actions following OpenJDK code split for JDK11

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#402]
Quoting Muneer on the OpenJDK "adoption-discuss@openjdk.java.net" mailing list

On 02/07/2018 10:28, Muneer Kolarkunnu wrote:
> JDK 11 is now in Rampdown Phase one 
> The overall feature set is frozen. No further JEPs will be targeted to this release.We’ve forked the main-line source repository, jdk/jdk, to the jdk/jdk11 stabilization repository. Any changes pushed to jdk/jdk or jdk/client are now bound for JDK 12. 

We need to switch the source stream for our JDK11 work, e.g.
https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-11/

**Comment by M-Davies** [comment]
@karianna Any update on this? IIRC we're using our own branch of [11's code stream](https://github.com/AdoptOpenJDK/openjdk-jdk11/tree/dev)?

**Comment by karianna** [comment]
Oh gosh, this is ancient, we can close this.
