### ISSUE TITLE
Add OpenJDK with Hotspot builds for Windows 32-bit architecture

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#403]
Despite Win32 not being listed as a [supported build platform](https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms), there are Oracle builds of Win32 available for download, and the build notes state that platform is "Also for creating 32-bit builds."

If this assumption is correct then AdoptOpenJDK should produce Win32 builds.

**Comment by sxa555** [comment]
@tellison https://github.com/AdoptOpenJDK/openjdk-build/issues/384 is already kicking around which covers HotSpot/win32

**Comment by sxa555** [comment]
Done by @ali-ince on Sept 2 as per https://github.com/AdoptOpenJDK/openjdk-build/issues/384#issuecomment-417926977 therefore closing
