### ISSUE TITLE
Placeholder for JRE image creation on Java 11+

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#411]
$ make legacy-jre-image &&
build/linux-x86_64-normal-server-release/images/jre/bin/java --list-modules
Building target 'legacy-jre-image' in configuration
'linux-x86_64-normal-server-release'
Creating legacy jre image
Finished building target 'legacy-jre-image' in configuration
'linux-x86_64-normal-server-release'
make legacy-jre-image  9.82s user 2.09s system 145% cpu 8.183 total
java.base@12-internal
java.compiler@12-internal

**Comment by sxa555** [comment]
Asking the question since it was asked by someone today: Do we still need to produce a JRE package if Oracle aren't producing one in a default openjdk build?

**Comment by don-vip** [comment]
Maintaining a JRE package should help Linux distributions maintainers, see http://mail.openjdk.java.net/pipermail/distro-pkg-dev/2018-July/039894.html

**Comment by alexhass** [comment]
If you create a build I can create the Windows MSI installer for JRE, too.

**Comment by j-christ** [comment]
@sxa555 Yes, a JRE is still needed.  Many 3rd party tools expect a JRE but not necessarily a JDK.

**Comment by don-vip** [comment]
Even Oracle will finally provide a Server JRE for JDK 11, see https://twitter.com/DonaldOJDK/status/1044970153392427010

**Comment by karianna** [comment]
@johnoliver Can you give the instructions in the issue description a go for a Linux x86 Java 11 build and see if it just works out of the box?

**Comment by pbi-qfs** [comment]
Providing a Java-11 Desktop-JRE (as long as the build targets are available in the source) for download as s substantial added value in comparison to what Oracle offers.

**Comment by karianna** [comment]
Fixed via #582, but waiting to see if we need to do more to add it to the API/site

**Comment by karianna** [comment]
Should go all the way through to the website and API, so closing for now, please raise a bug if that's not the case within the next few days.
