### ISSUE TITLE
Please start building OpenJDK+OpenJ9 for jdk11

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#414]
The jdk11 repo is https://github.com/ibmruntimes/openj9-openjdk-jdk11

Steps needed now that initial prototyping has been done:
- [ ] Confirm from openj9 team that `--with-freetype=bundled` is the right option for JDK11
- [ ] Install suitable JDK10 boot jdk on each machine so each job doesn't need to pull down its own copy
- [x] Expand build jobs to other architectures (Linux ppcle and s390x)
- [ ] Expand build jobs to cover AIX
- [ ] Expand build jobs to cover Windows
- [ ] Set up test jobs
- [ ] Create pipelines
- [ ] Set up new release on the website

**Comment by sxa555** [comment]
I understand from @adamfarley that the branch names are now in sync with the other versions so this should "just" be a matter of duplicating the jenkins jobs which  we have for 10.

**Comment by pshipton** [comment]
:fingers crossed:

**Comment by sxa555** [comment]
Initial job created for Linux/x64 https://ci.adoptopenjdk.net/view/all/job/openjdk11_openj9_build_x86-64_linux/
Job is currently running from my fork pending integration of https://github.com/AdoptOpenJDK/openjdk-build/pull/419

**Comment by sxa555** [comment]
Within that job:
- Boot JDK being dynamically pulled from the hotspot adoptopenjdk release for now
- `FREETYPE_DIRECTORY=bundled` in the environment as the configure command doesn't accept a directory to `--with-freetype=` any more - insists on only `bundled` or `system`

**Comment by sxa555** [comment]
Added "Steps needed" to the original description

**Comment by smlambert** [comment]
Test jobs added:
https://ci.adoptopenjdk.net/view/all/job/openjdk11_j9_openjdktest_x86-64_linux/ 
https://ci.adoptopenjdk.net/view/all/job/openjdk11_j9_openjdktest_s390x_linux/
https://ci.adoptopenjdk.net/view/all/job/openjdk11_j9_openjdktest_ppc64le_linux/

**Comment by sxa555** [comment]
AIX job: https://ci.adoptopenjdk.net/view/JDK11%20WIP/job/openjdk11_openj9_build_ppc64_aix/2/console

Failure to build on AIX (seen by the OpenJ9 team already):
```
checking for readlink... no
configure: error: Could not find required tool for READLINK
```

**Comment by sxa555** [comment]
For reference, this tab shows all the current jdk11 "work in progress" builds: https://ci.adoptopenjdk.net/view/JDK11%20WIP/

**Comment by sxa555** [comment]
@smlambert @pshipton I presume you are both happy for this now to be closed :-)
I'm going to close it, please reopen if any concerns remain
