### ISSUE TITLE
AdoptOpenJDK 1.8 (u172) not reporting the Update number.

### ISSUE THREAD

**Issue by wfouche** [AdoptOpenJDK/openjdk-build#422]
Running "java -server -version" displays output:

    openjdk version "1.8.0-adoptopenjdk"
    OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-_2018_05_19_00_59-b00)
    OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

Nowhere does u172 appear. It is critical that the full version number be printed, otherwise it is not possible to determine which Update release of 1.8.0 is installed.

Oracle Java does display the Update number:

    java version "1.8.0_172"
    Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
    Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

Recommending that AdopOpenJDK be changed to display the Update number as shown below:

    openjdk version "1.8.0_172-adoptopenjdk"
    OpenJDK Runtime Environment (build 1.8.0_172-adoptopenjdk-_2018_05_19_00_59-b00)
    OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

There is also a redundant '_' character that should be removed before the 2018 date in the text above.

**Comment by karianna** [comment]
This is a duplicate of various others - we'll sweep this along with the others.

**Comment by wfouche** [comment]
Fix tested. Issue resolved. Thank you.
