### ISSUE TITLE
openjdk8_build_aarch64_linux publish story unexpected

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#425]
<img width="741" alt="screen shot 2018-07-30 at 12 29 08 pm" src="https://user-images.githubusercontent.com/18030625/43410490-0fed4216-93f5-11e8-80e9-9b4f177747b4.png">

Query OpenJDK 8 with Hotspot nightly got a bunch of Linux aarch64 jdk for same day. Looks like those JDK have a wrong timestamps?
The build itself has a different build story from others. 
https://ci.adoptopenjdk.net/job/openjdk8_build_aarch64_linux/configure

**Comment by sophia-guo** [comment]
@johnoliver correct, the job configuration didn't check `Delete workspace before build starts`. @gdams as you are the creator of this job can we just check `Delete workspace before build starts`?

**Comment by karianna** [comment]
I've checked that delete box on the job now.

**Comment by karianna** [comment]
And I've cleaned up the releases repo
