### ISSUE TITLE
$PATH doesn't include java binary in adoptopenjdk/openjdk10 docker image

### ISSUE THREAD

**Issue by jrivard** [AdoptOpenJDK/openjdk-build#430]
This makes it impossible to set an entry point as just 'java'.   I ran into this using jib-maven-plugin which has an opinionated build process that only allows 'java' as the entry point.

**Comment by karianna** [comment]
@jrivard I'm a it confused.  On your O/S do you not have to add $JAVA_HOME/bin to your $PATH?

**Comment by jrivard** [comment]
@karianna I'm not sure what your asking exactly.  I'm talking about inside the docker image, not on my own OS.  The final image entry point is just 'java' and because that is not in the image's path it won't execute.  This doesn't have anything to do with my O/S.

A test case would be, if you run /bin/bash inside the image, you should just be able to run 'java' without specifying the full path to the binary.

**Comment by jrivard** [comment]
@gdams the docker image 'adoptopenjdk/openjdk10'.  I don't know what homebrew is.

**Comment by dinogun** [comment]
@jrivard Can you please update your docker image, I'm suspecting it to a very old one.

```
$ docker run --rm -it adoptopenjdk/openjdk10:nightly java -version
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
openjdk version "10.0.2-adoptopenjdk" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
OpenJDK 64-Bit Server VM (build 10.0.2-adoptopenjdk+13, mixed mode)
```
```
$ docker run --rm -it adoptopenjdk/openjdk10 java -version
Picked up JAVA_TOOL_OPTIONS: -XX:+UseContainerSupport
openjdk version "10.0.1-adoptopenjdk" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1-adoptopenjdk+10)
OpenJDK 64-Bit Server VM (build 10.0.1-adoptopenjdk+10, mixed mode)
```

**Comment by jrivard** [comment]
Closing due to adoptopendjk11 release and this issue seems to be solved there.
