### ISSUE TITLE
Produce prototype builds of openjdk10/openj9 on ARM

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#434]
@JamesKingdon has been aiming to add ARM support to the openj9 "extensions" repository at https://github.com/JamesKingdon/openj9-openjdk-jdk10/tree/arm - it would be interesting to have builds at adoptopenjdk of that for people wishing to experiment with it.

NOTE: That repository may require cross-compliation unlike the current arm HotSpot builds

**Comment by M-Davies** [comment]
It looks like OpenJ9 are also trying to get arm supported https://github.com/eclipse/openj9/issues/53 on their side. With James looking like he's stopped work on the ARM support, is this still a relevant issue to have open here?

**Comment by karianna** [comment]
Paging @JamesKingdon and @sxa on that one

**Comment by sxa** [comment]
There is a port of OpenJ9 to aarch64, but there will not be one for openjdk10. I'm happy to close this, but this does not preclude adding things later ...

**Comment by JamesKingdon** [comment]
Yep, I dropped out of the arm work due to lack of available time to commit to it.
