### ISSUE TITLE
Eclipse OpenJ9 VM: Java OutOfMemoryError encountered when more than roughly 67M of Direct Byte Buffers are allocated.

### ISSUE THREAD

**Issue by machonerddude** [AdoptOpenJDK/openjdk-build#442]
Per J9 documentation (https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.vm.80.doc/docs/xxmaxdirectmemorysize.html), we were under the impression that the amount of memory reserved for Direct Byte Buffers is dynamically expanded from a "soft" limit of 64MB.  We are not finding this in practice.  When our application has allocated roughly 67M of direct memory we see the following exception:

java.lang.OutOfMemoryError: Direct buffer memory
at java.nio.Bits.reserveMemory(Bits.java:703) ~[?:1.8.0_181]
at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:126) ~[?:1.8.0_181]
at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_181]

We are using the option -XX:MaxDirectMemorySize=512m to work around the issue.

Note that we encountered this while migrating from a stable application that has been using a HotSpot VM.  This issue does not occur when using a HotSpot VM.

I can also recreate this issue using a very simple test program which simply allocates direct byte buffers:

        byte[] byteData = new byte[1024];
        Arrays.fill(byteData,(byte)1);
        ByteBuffer[] bbuffs = new ByteBuffer[70000];
        for (int i=0;i<70000;i++)
        {
            System.out.println("direct mem allocation: " + i * 1024);
            bbuffs[i] = ByteBuffer.allocateDirect(1024);
            bbuffs[i].put(byteData);
        }

**Comment by karianna** [comment]
I believe this is an upstream issue that should be raised at the Eclipse OpenJ9 project.

**Comment by smlambert** [comment]
I posted to the openj9 slack channel to ask if its a known issue, if not we could raise an [openj9 issue](https://github.com/eclipse/openj9/issues)

**Comment by DanHeidinga** [comment]
Please raise this at the OpenJ9 project.  It's more likely to get the "right" eyes on it there.

**Comment by machonerddude** [comment]
I just opened this issue at the OpenJ9 issue.

**Comment by sxa555** [comment]
Raised at https://github.com/eclipse/openj9/issues/2604 - closing this one.
