### ISSUE TITLE
OpenJ9 release pipelines publish without openj9 version by default

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#444]
Pipeline came out as `jdk8u181-b13` instead of `jdk8u181-b13_openj9-0.9.0` (although filenames correctly had the openj9 version included). Need to ensure a strategy for making this come out correctly through the automation. I puiblished manually this time (via the release tool job).

**Comment by M-Davies** [comment]
@sxa Is this still an issue?

**Comment by sxa** [comment]
Probably not - I thnk a lot of changes have gone in since now but no-one closed this when they made the changes. Might be useful to reference where it was fixed by otherwise I don't believe there's any follow-up work

**Comment by karianna** [comment]
> Probably not - I thnk a lot of changes have gone in since now but no-one closed this when they made the changes. Might be useful to reference where it was fixed by otherwise I don't believe there's any follow-up work

Yes this can be closed.
