### ISSUE TITLE
Inconsistent "release_name" for nightly builds

### ISSUE THREAD

**Issue by dinogun** [AdoptOpenJDK/openjdk-build#447]
Using this [API](https://api.adoptopenjdk.net/v2/info/nightly/openjdk8?openjdk_impl=openj9&os=linux&type=jdk) query, we see different results for the "release_name" string in the JSON. See examples below
``` "release_name": "jdk8u-2018-07-26-21-26" ```
``` "release_name": "jdk8u172-b11-201802081200" ```   ==>  Format expected by docker scripts.
``` "release_name": "201808151726" ```

**Comment by M-Davies** [comment]
Looks like these were a few buggy binaries that slipped past the net. Short of transferring this over to the API repo, this can probably closed since the related issue was closed after the release_name started to look better

@karianna FYI

**Comment by karianna** [comment]
> Looks like these were a few buggy binaries that slipped past the net. Short of transferring this over to the API repo, this can probably closed since the related issue was closed after the release_name started to look better [#259 (comment)](https://github.com/AdoptOpenJDK/openjdk-build/issues/259#issuecomment-417327787)
> 
> @karianna FYI

Agreed this was resolved on a 'going forward' basis.
