### ISSUE TITLE
Symantec Endpoint Protection quarantines adoptopenjdk Windows builds

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#449]
On unzipping the adoptopenjdk Windows release
https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/releases/download/jdk8u181-b13_openj9-0.9.0/OpenJDK8-OPENJ9_x64_Windows_jdk8u181-b13_openj9-0.9.0.zip Symantec Endpoint Protection quarantines all executables (.exe and .dll files), and so using the jdk requires that the files be restored from quarantine.

On my laptop it took about 2 hours for the files to be quarantined, so the first use experience for the new release was not a good one.

The quarantining seems to be due to the file not having had many downloads.  

Seems to be the same symptoms as https://github.com/AdoptOpenJDK/openjdk-build/issues/161, which was closed.

The executables' Properties show they are signed by "London Jamocha Community CIC"

**Comment by karianna** [comment]
Hmm, not sure we can do much about the fact that the package hasn't been downloaded often.  We do have a correctly signed binary as far as we're aware.

**Comment by lumpfish** [comment]
I just downloaded the new release for openjdk-hotspot from https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/jdk-10.0.2%2B13/OpenJDK10_x64_Windows_jdk-10.0.2.13.zip and that was not quarantined.
As far as I can tell the signatures are identical.  Any ideas why openjdk-hotspot and openjdk-openj9 might be treated differently?

**Comment by lumpfish** [comment]
Hmmm - sometime in the last hour the openjdk-hotspot build has started to be quarantined.  Strange that it first allowed it to be unzippeecuted.

**Comment by karianna** [comment]
Is it stating the reason for the quarantine? I know on Mac Os X you really have to dig in to get the reason.

**Comment by spgennard** [comment]
You might be able to use sigcheck/sysinternals in the build process to check the zip file with virustotal option.

https://blog.virustotal.com/2013/10/sigcheck-virustotal.html
https://docs.microsoft.com/en-us/sysinternals/downloads/sigcheck

**Comment by gdams** [comment]
@lumpfish is this still an issue? we should be code signing all windows builds.

**Comment by lumpfish** [comment]
I have downloaded the latest Windows release from https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u192-b12_openj9-0.11.0 and Symantec Endpoint Protection did not quarantine it.
