### ISSUE TITLE
Run hotspot tests after building OpenJDK artifact

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#46]
It has been noticed while discussing and investigating issue [7](https://github.com/AdoptOpenJDK/openjdk-build/issues/7), that `hotspot` tests do not get run when we run jtreg tests (currently setup to run `jdk_core` and `langtools`).

Ideally `hotspot` tests should also be run, as this does the sanity check on the JVM variant.

**Comment by karianna** [comment]
Covered by test pipelines
