### ISSUE TITLE
Implement proper file versions

### ISSUE THREAD

**Issue by alexhass** [AdoptOpenJDK/openjdk-build#463]
The current builds of OpenJDK compiled every version with 8.0.0.0, but Oracle Java uses proper file versions like 8.0.1810.13. This missing file version increase will cause serious issues with MSI installer https://github.com/AdoptOpenJDK/openjdk-build/issues/459. MSI has internal checks for version and requires that you change the file versions or the files are not updated on upgrades.

Can you increase file versions on every build, please?

**Comment by alexhass** [comment]
Any chance that this bug get some priority and get fixed soon? Version 11 also has files with 11.0.0.0 only.

**Comment by karianna** [comment]
Hi @alexhass - which files are these in particular?

**Comment by alexhass** [comment]
Every dll, exe and do on.

**Comment by karianna** [comment]
Thanks - we've just finished wrapping up the Mac installer and will start finishing the exe and your MSI next week.

**Comment by alexhass** [comment]
Great news. Thanks. I just have a lot of fixes pushed in https://github.com/AdoptOpenJDK/openjdk-installer/pull/11

**Comment by karianna** [comment]
I think the new Visual Stuido toolchain choices have fixed this yes.  Please do let us know if not!
