### ISSUE TITLE
Vendor properties incorrect?

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#465]
AdoptOpenJDK builds have the following properties (8u172 as an exampe).  Need to investigate which ones should change.

java.specification.vendor = Oracle Corporation
   java.vendor = Oracle Corporation
   java.vm.specification.vendor = Oracle Corporation
   java.vm.vendor = Oracle Corporation

**Comment by sxa555** [comment]
Initial gut feel would be `java.vendor` only

**Comment by sxa555** [comment]
For OpenJ9 (AdoptOpenJDK 8u181+b13 release build) we get:
```
java.specification.vendor=Oracle Corporation
java.vendor=Eclipse OpenJ9
java.vm.specification.vendor=Oracle Corporation
java.vm.vendor=Eclipse OpenJ9
```

**Comment by dashorst** [comment]
Using the command:

```
java -XshowSettings
```

I get the following list of vendor-related properties:

```
    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 11+28
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 11
    java.vendor = Oracle Corporation
    java.vendor.url = http://java.oracle.com/
    java.vendor.url.bug = http://bugreport.java.com/bugreport/
    java.vendor.version = AdoptOpenJDK
    java.version = 11
    java.version.date = 2018-09-25
    java.vm.compressedOopsMode = Zero based
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 11
    java.vm.vendor = Oracle Corporation
    java.vm.version = 11+28
```

IMO the following properties should note AdoptOpenJDK in some form:

- `java.vm.name` = AdoptOpenJDK OpenJDK 64-Bit Server VM
- `java.vm.vendor` = AdoptOpenJDK
- `java.vendor` = AdoptOpenJDK
- `java.vendor.url` = https://adoptopenjdk.net
- `java.vendor.url.bug` = https://github.com/AdoptOpenJDK/adoptopenjdk-build/issues

I'm not entirely convinced by a `java.vm.name` change TBH.

**Comment by Ganeshgautam** [comment]
Hi Team,

I have a use case to identify the JRE vendor for analytics in my software. It would be great if we can get the java.vendor or java.runtime.name or java.vm.vendor to tell AdoptOpenJDK. 
Do you plan to pick this bug in short-term?

Thanks,
Ganesh

**Comment by Ganeshgautam** [comment]
It would also be helpful if we can even get the proposed strings for the final properties. We will be able to put some code in our software which allows to stay compatible with AdoptOpenJDK.

**Comment by ecki** [comment]
With the new versioning infrastructure in Java11 things are much better (even for other vendors)- Here is an example from Zulu:

    java.runtime.name = OpenJDK Runtime Environment
    java.runtime.version = 10+46
    java.specification.name = Java Platform API Specification
    java.specification.vendor = Oracle Corporation
    java.specification.version = 10
    java.vendor = Azul Systems, Inc.
    java.vendor.url = http://www.azulsystems.com/
    java.vendor.url.bug = http://www.azulsystems.com/support/
    java.vendor.version = Zulu10.1+11
    java.version = 10
    java.version.date = 2018-03-20
    java.vm.compressedOopsMode = 32-bit
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 10
    java.vm.vendor = Azul Systems, Inc.
    java.vm.version = 10+46

Note especially the java.vendor.version which is not present in 8.

**Comment by karianna** [comment]
That Java vendor version will be useful, we may even backport that.

**Comment by gdams** [comment]
this got backported, closing
