### ISSUE TITLE
Missing cacerts file on Windows

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#469]
We've discussed this previously but since I can't find an issue regarding it I'm creating this one, mostly as it's just been raised on the OpenJ9 call. Here is theyr issue: https://github.com/eclipse/openj9/issues/2696

It would appear that it was explicitly disabled at some point but the discussions suggested no one was quite sure unless it was a technical limitation of being able to perform the download of the certs file in Windows. On the assumption that there is no good reason not to ship it, we need to resolve this.

FYI @neomatrix369 since we had a slack conversation recently on this:

Relevant code that excludes it: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/common-functions.sh#L155

**Comment by jefrajames** [comment]
Maybe you know it, but the issue remains with  jdku181-b13.

**Comment by karianna** [comment]
Closing this as a duplicate
