### ISSUE TITLE
Question regarding Java Compatibility Kit (JCK) Certifications

### ISSUE THREAD

**Issue by simonis** [AdoptOpenJDK/openjdk-build#470]
Hi,

on your support page at https://adoptopenjdk.net/support.html you mention:

"Furthermore, releases that have passed the Java Compatibility Kit (JCK) test suites are denoted by a blue shield containing a check mark in their download button. This build is JCK certified. We recommend you choose these releases for running your applications."

However, I couldn't find any such "blue shield containing a check mark" on the various releases available from your Download page (i.e. https://adoptopenjdk.net/index.html?variant=openjdk8&jvmVariant=hotspot). Is this an oversight, a display issue or haven't you started certifying binaries yet?

Could you please detail how I can easily identify JCK-certified binaries on your download site and which exact platform versions the certifications have been done for?

Thank you and best regards,
Volker

**Comment by AdamBrousseau** [comment]
I can't comment on the status of the certification of each build as I'm not involved with that process. However I think the above statement is correct, there just haven't been that many that have been certified yet.

One example that is certified would be the recent 0.9 release of OpenJ9:
https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9#x64_linux

**Comment by simonis** [comment]
Thanks a lot for the quick clarification, Adam!

Now I know what I have to look for.

Regards,
Volker

**Comment by karianna** [comment]
@AdamBrousseau Has hit the nail on the head.  We do intend to certify more builds going forwards but there's still quite a bit of infrastructure as code going into that so we can divide and conquer the manual tests in particular.
