### ISSUE TITLE
Commit reference for releases should be available via the /releases GitHub API

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#474]
_From @Joe-Brady on March 17, 2017 14:25_

Should be part of the automated process.

E.g. added as a tag, or by any method that makes it appear in this JSON:

api.github.com/repos/AdoptOpenJDK/openjdk-releases/releases

_Copied from original issue: AdoptOpenJDK/openjdk8-releases#2_

**Comment by M-Davies** [comment]
@karianna I'm guessing this is still relevant and a `help wanted` issue?

**Comment by karianna** [comment]
> @karianna I'm guessing this is still relevant and a `help wanted` issue?

Correct. the `scmRef` JSON key in our metadata still needs to be hooked up.

**Comment by M-Davies** [comment]
For some context on this, our current meta data is created without setting a scm reference
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L401

@karianna What exactly would the scm reference be? Would it be the latest commit hash that the binary was built with?

**Comment by karianna** [comment]
> For some context on this, our current meta data is created without setting a scm reference
> https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L401
> 
> @karianna What exactly would the scm reference be? Would it be the latest commit hash that the binary was built with?

Yes, in our openjdk-jdk<version> repos whatever the tagged commit in the `dev` branch was.
