### ISSUE TITLE
sun.* source code not included in src.zip

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#476]
_From @don-vip on October 6, 2017 20:43_

I have downloaded this binary:
https://github.com/AdoptOpenJDK/openjdk8-releases/releases/download/jdk8u144-b01/OpenJDK8_x64_Win_jdk8u144-b01.exe

Once installed, it appears `sun.*` source code is not included in `src.zip`.
As at least the class I'm interested in (`src/share/classes/sun/util/locale/provider/NumberFormatProviderImpl.java`) is licensed under GPLv2, coud you please include in src.zip all the source code we can find in OpenJDK repositories?

_Copied from original issue: AdoptOpenJDK/openjdk8-releases#9_

**Comment by karianna** [comment]
_From @gdams on October 7, 2017 12:0_

@neomatrix369 any ideas about this?

**Comment by karianna** [comment]
_From @neomatrix369 on October 7, 2017 21:10_

@gdams No idea why this would be the case, we are archiving the image folder as it is produced by the OpenJDK build process, see [src.zip](https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_windows/ws/openjdk/build/windows-x86_64-normal-server-release/images/jdk8u162-b01/src.zip) in https://ci.adoptopenjdk.net/job/openjdk8_build_x86-64_windows/ws/openjdk/build/windows-x86_64-normal-server-release/images/jdk8u162-b01/.

We do not amend the image, at all (apart from removing some demo folders to reduce the footprint of the original archive file).

**Comment by karianna** [comment]
_From @neomatrix369 on October 7, 2017 21:13_

@don-vip Can you please point us to OpenJDK Windows builds (produced anywhere else) in which the src.zip does contain the file you are looking for?

I'll also ask the OpenJDK team about this after doing some looking around.

**Comment by karianna** [comment]
_From @don-vip on October 7, 2017 21:38_

? There is not. I'm asking to include the missing files. If they were already included, I wouldn't have created the ticket :)

**Comment by karianna** [comment]
_From @neomatrix369 on October 7, 2017 21:45_

@don-vip Thanks for clarifying.

It would mean changing the build script, have a look at http://jdk.java.net/java-se-ri/8 and then the http://download.java.net/openjdk/jdk8u40/ri/openjdk-8u40-src-b25-10_feb_2015.zip, which does not contain the file you are talking about either.

@gdams @karianna what do you think about the request? Our build script will fork away from the standard OpenJDK one if we implement this, is this desirable for the medium/long run?

**Comment by karianna** [comment]
@neomatrix369 Worth asking upstream OpenJDK folks why this isn't included (for jdk8u).   I can't see any reason *not* to include it if it's GPLv2 with Classpath and not a closed Sun/Oracle class.

**Comment by karianna** [comment]
_From @tellison on October 9, 2017 9:34_

FYI it has been true 'forever' that src.zip does not contain all the library source code.  That zip file is produced to assist development tools display relevant source code.  IMHO it should contain *less* source than it already does.

Now that we are all connected, better still we should simply include coordinates to the git repo sources that produced the build so that dev tools can reach on-line the entire code from which the binaries are produced if they so choose.

**Comment by karianna** [comment]
@tellison Good point, we could provide the link to the tag in Github in the download.

**Comment by karianna** [comment]
So this was actually a 'bug' with OpenJDK itself.  Severin has submitted a RFR to add these sources for 8.  We may see this come in for 8u202

**Comment by don-vip** [comment]
Thanks a lot! [Link for reference](http://mail.openjdk.java.net/pipermail/jdk8u-dev/2018-September/007917.html).

**Comment by karianna** [comment]
I'll close this as our nightly builds will pick this up in due course.

**Comment by don-vip** [comment]
How can I get the fix?
* I downloaded [JDK8u202 b03](https://jdk.java.net/8/) from Oracle and src.zip is still 20Mb. I don't understand why, as JDK-8073327 is supposedly fixed in 8u202 b01
* AdoptOpenJDK 8u nightly refers to 8u192. I thought "nightly" meant master on jdk8u mercurial repository?
