### ISSUE TITLE
OpenJ9 Linux/s390x build 152 fails to initialize

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#477]
_From @sxa555 on November 30, 2017 14:25_

Running `java -version` on jdk8u152 gives:

`[...]/jre/lib/s390x/server/libjvm.so: No such file or directory`

_Copied from original issue: AdoptOpenJDK/openjdk8-releases#10_

**Comment by karianna** [comment]
@sxa555 Can you try on a later build?

**Comment by sxa555** [comment]
This was fixed somewhere along the line via `jvm.cfg` I think, therefore closing
