### ISSUE TITLE
sha256 file contains filename with + instead of .

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#479]
_From @r15ch13 on September 26, 2017 17:11_

Why is the file name in the `.sha256.txt` written with a plus instead of a dot like the actual file?
Simply running sha256sum to check the hash is not possible this way.
```
λ sha256sum -c OpenJDK9_x64_Win_jdk-9.181.sha256.txt
sha256sum: OpenJDK9_x64_Win_jdk-9+181.zip: No such file or directory
OpenJDK9_x64_Win_jdk-9+181.zip: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
```

_Copied from original issue: AdoptOpenJDK/openjdk9-releases#1_

**Comment by M-Davies** [comment]
@karianna Is this still an issue?

**Comment by karianna** [comment]
> @karianna Is this still an issue?

It seems to be resolved for JDK11+, so we'll close it.
