### ISSUE TITLE
Folder inside zip does not match build tag

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#484]
_From @se35710 on May 1, 2018 11:57_

In the build with tag [jdk8u172-b00-20180430](https://github.com/AdoptOpenJDK/openjdk8-nightly/releases/tag/jdk8u172-b00-20180430) ([OpenJDK8_x64_Win_20180430.zip](https://github.com/AdoptOpenJDK/openjdk8-nightly/releases/download/jdk8u172-b00-20180430/OpenJDK8_x64_Win_20180430.zip)), the folder inside the zip archive is named `jdk8u172-b03`.

_Copied from original issue: AdoptOpenJDK/openjdk8-nightly#9_

**Comment by karianna** [comment]
From @se35710 on May 1, 2018 12:6

In the build with tag jdk-10+23-20180430 (OpenJDK8_x64_Win_20180430.zip), the folder inside the zip archive is named jdk-10+46.

Copied from original issue: AdoptOpenJDK/openjdk10-nightly#1

**Comment by gdams** [comment]
this will be fixed by the work @johnoliver is doing with the metadata

**Comment by karianna** [comment]
This has been resolved (tag vs dir name)
