### ISSUE TITLE
OpenJ9 s390 - Build failure seen with block overrun error

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#486]
_From @namrata-ibm on May 17, 2018 6:44_

While building TensorFlow from source on s390x Ubuntu 16.04 with AdoptJDK facing below error:
```
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package  
.
.
.
ERROR: /root/tensorflow/tensorflow/tools/pip_package/BUILD:117:1: no such package '@nasm//': java.io.IOException: block overrun and referenced by '//tensorflow/tools/pip_package:licenses'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: no such package '@nasm//': java.io.IOException: block overrun
INFO: Elapsed time: 14.837s
FAILED: Build did NOT complete successfully (137 packages loaded)
    currently loading: tensorflow/core/kernels ... (2 packages)
```
It seems this is related to AdoptOpenJDK on s390x. I have verified that the build with OpenJDK 8 works.
Further, verified the `nasm` file is valid. More discussion can be found here:
https://issues.apache.org/jira/browse/COMPRESS-453   
https://github.com/tensorflow/tensorflow/issues/16862#issuecomment-388321934

Using Java binary from `https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/releases/download/jdk8u162-b12_openj9-0.8.0/OpenJDK8-OPENJ9_s390x_Linux_jdk8u162-b12_openj9-0.8.0.tar.gz`
```
java -version:

openjdk version "1.8.0_162"
OpenJDK Runtime Environment (build 1.8.0_162-b12)
Eclipse OpenJ9 VM (build openj9-0.8.0, JRE 1.8.0 Linux s390x-64 Compressed References 20180315_97 (JIT enabled, AOT enabled)
OpenJ9   - e24e8aa9
OMR      - 3e8296b4
JCL      - ee1e77df1d based on jdk8u162-b12)
```

Could someone please help in resolving the issue?
Any pointers would be helpful.  

_Copied from original issue: AdoptOpenJDK/openjdk8-openj9-releases#3_

**Comment by karianna** [comment]
_From @tellison on May 17, 2018 10:2_

Hi @namrata-ibm 

Hard to tell from the limited info in the error.

Can you clarify:
> I have verified that the build with OpenJDK 8 works.

Which build works OK for you?  From that we might start to narrow down wether it is a classes of JVM related issue, and then be able to ask you for more specific debug information.

**Comment by karianna** [comment]
_From @namrata-ibm on May 17, 2018 10:53_

@tellison , Thank you for your response.

I am able to build TensorFlow with Openjdk-8-jdk installed from Ubuntu repository.
```
java -version:  
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Zero VM (build 25.171-b11, interpreted mode)
```
Build had completed with `Openjdk-8-jdk` with earlier minor versions too like `8u162`/ `8u151`.

Here are Jenkins jobs for reference:
1. With AdoptOpenJDK(Failing): https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/73/consoleFull
2. With OpenJDK(Passing): https://ibmz-ci.osuosl.org/job/TensorFlow_IBMZ_CI/74/consoleFull

Let me know if any other information is needed.

**Comment by karianna** [comment]
_From @namrata-ibm on May 28, 2018 12:30_

After doing some more analysis on this issue, have below observations for further analysis:
While the nasm package is uncompressed using `Apache Commons Compress`, JIT shows some erroneous behavior as below:
For code snippet 
```
System.err.println("before loop s: " + s + ", lastShadow: " + lastShadow);
while (s-- >= 0) {
    ll8[++lastShadow] = ch;
}
System.err.println("after loop s: " + s + ", lastShadow: " + lastShadow);
```
when s=5, while loop should execute 6 times and exit. However due to some bug in JIT, it gets executed 7 times, as per below log output:
```
before loop s: 5, lastShadow: 899994
after loop s: -2, lastShadow: 900001
```
More reference in : https://issues.apache.org/jira/browse/COMPRESS-453

Attaching logs for OpenJDK as well as AdoptOpenJDK for comparison.
It can be seen from the log that, it first seems to work OK (lastShadow should get incremented by s + 1) but starts to go wrong at one point in time( from line number 599184 in the logs below).

[TestLog__AdoptJDK.txt](https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/files/2044994/TestLog__AdoptJDK.txt)

[TestLog__OpenJDK_truncated.txt](https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/files/2045040/TestLog__OpenJDK_truncated.txt)

**Comment by sxa555** [comment]
I would be tempted to try with the latest build from https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9#s390x_linux since there have been quite a lot of enhancements between openj9 0.8.0 and 0.9.0.

**Comment by karianna** [comment]
@namrata-ibm - Are you able to check with a newer build?

**Comment by namrata-ibm** [comment]
@karianna , @sxa555 , I tried building with 0.9.0, unfortunately it doesn't help, get similar build error:
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'REPOSITORY_DIRECTORY:@nasm'
Caused by: java.lang.IllegalArgumentException: Invalid EvalException:
java.lang.ArrayIndexOutOfBoundsException
```

Log file with details:

[Adoptjdk090_TensorFlowError.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/2366611/Adoptjdk090_TensorFlowError.txt)

**Comment by karianna** [comment]
@namrata-ibm Sorry to bounce you around but I suspect this needs to be reported upstream in [Eclipse OpenJ9](GitHub - eclipse/openj9: Eclipse OpenJ9: A Java Virtual Machine for ...) as its a JIT issue in the J9 VM.

**Comment by fjeremic** [comment]
@karianna it does sound like a JIT issue given that things start going wrong after a while. Likely a method got miscompiled somehow and the bug starts happening related to snippet of code posted in https://github.com/AdoptOpenJDK/openjdk-build/issues/486#issuecomment-419853972.

I suggest that you open an issue over at eclipse/openj9 for this. We will either need specific reproduction steps or a unit test that exhibits the issue to be able to debug. If you can provide us with either of those we can get a developer to take a look and produce a fix or quickly provide you with a workaround so as to unblock you.

**Comment by namrata-ibm** [comment]
Thanks, I'll create an issue with eclipse/openj9.

**Comment by M-Davies** [comment]
@karianna Since this has been reported upstream, can this now be closed on our end? We can always reopen it if the OpenJ9 guys want to us to change up our build scripts to fix this issue

**Comment by karianna** [comment]
> @karianna Since this has been reported upstream, can this now be closed on our end? We can always reopen it if the OpenJ9 guys want to us to change up our build scripts to fix this issue

Yes, we can close.
