### ISSUE TITLE
Access to https://adopt-openjdk.ci.cloudbees.com/

### ISSUE THREAD

**Issue by gdams** [AdoptOpenJDK/openjdk-build#5]
We have several build jobs that generate the nightly/release builds and also handle the mercurial to github conversion. Would someone be able to give me access to migrate the jobs? CC @karianna

**Comment by karianna** [comment]
@gdams - Mani and I are going to look over the weekend to see if Cloudbees will be suitable.  Not 100% sure we have enough rights/access to the service to be able to run these Docker based builds.

**Comment by gdams** [comment]
so we are hoping that cloudbees will give add our user to the docker group otherwise building could be interesting with sudo access to install dependencies

**Comment by neomatrix369** [comment]
@karianna @gdams just had a look at CloudBees' Docker support - they have some Jenkins plugins to help us do Docker builds, will have to go through the documentation to see how it all works and then adapt our scripts/jobs to do that. Not sure yet if this will work, from conversations with someone from Cloudbees in the past.

**Comment by gdams** [comment]
All we need to do is ensure that the username is in then docker group and you'll be able to run our makejdk script
 
 Sent from my iPhone using IBM Verse
 
 On 18 Mar 2017, 00:06:21, notifications@github.com wrote:

**Comment by gdams** [comment]
We already have a Jenkins job that works so if someone can give me access I can simply migrate the job and get it working :)

**Comment by karianna** [comment]
@gdams - Very happy to give you access.  I tried adding you as an admin, but you need to be a registered cloudbees user first.  LMK when you sign up and I'll add you.  @neomatrix369 kindly installed all of the Docker and Ansible plugins he could find so hopefully you'll have what you need.

**Comment by gdams** [comment]
@karianna okay think I now have an account

**Comment by karianna** [comment]
@gdams I've added you as an Admin.
