### ISSUE TITLE
`pull access denied` when building the openj9 variant of Linux jdk8u under Windows 10

### ISSUE THREAD

**Issue by karol-marcjan-gl** [AdoptOpenJDK/openjdk-build#502]
OS:
![image](https://user-images.githubusercontent.com/43201948/45418979-41c36f00-b686-11e8-8ccf-27a904a496fa.png)
Docker:
![image](https://user-images.githubusercontent.com/43201948/45417665-02dfea00-b683-11e8-8188-ef0b0e80a6bb.png)
Shell (Git Bash):
![image](https://user-images.githubusercontent.com/43201948/45417740-2c007a80-b683-11e8-892b-95c076fb8ed9.png)

1. I am tried to build an OpenJDK 8 with Openj9, from the `new_build_scripts` branch, but I go the following error

```bash
$ ./makejdk-any-platform.sh --build-variant openj9 --docker jdk8u
Starting ./makejdk-any-platform.sh to configure, build (Adopt)OpenJDK binary
Working dir is ./build/
Using Docker to build the JDK
No docker container for reuse was found, so creating 'openjdk_container'
Building docker container
Building DockerFile variant openj9
Sending build context to Docker daemon  1.471MB
Step 1/7 : FROM openjdk_container
pull access denied for openjdk_container, repository does not exist or may require 'docker login'
$ 
```

2. I decided to compare and see if the HotSpot version built, and got the following output. This time the build got further, but I still got an error.

```
$ ./makejdk-any-platform.sh --docker jdk8u 2>1 > hotspot.output.txt
$ tail hotspot.output.txt
BUILD_CONFIG[TARGET_DIR]="target/"
BUILD_CONFIG[TARGET_FILE_NAME]="OpenJDK"
BUILD_CONFIG[TMP_CONTAINER_NAME]="openjdk-copy-src"
BUILD_CONFIG[TMP_SPACE_BUILD]="false"
BUILD_CONFIG[USE_DOCKER]="true"
BUILD_CONFIG[USE_SSH]="false"
BUILD_CONFIG[USER_SUPPLIED_CONFIGURE_ARGS]=""
BUILD_CONFIG[WORKING_DIR]="./build/"
BUILD_CONFIG[WORKSPACE_DIR]="/openjdk/"
Target binary directory on host machine: /c/Users/karol.marcjan/src/github.com/AdoptOpenJDK/openjdk-build/target
```

For the full output, see [hotspot.output.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/2374654/hotspot.output.txt).

3. I noticed that this built the container the OpenJ9 build complained about, so I reran that:

```
$ ./makejdk-any-platform.sh --build-variant openj9 --docker jdk8u
Starting ./makejdk-any-platform.sh to configure, build (Adopt)OpenJDK binary
Working dir is ./build/
Using Docker to build the JDK
No docker container for reuse was found, so creating 'openjdk_container'
Building docker container
Building DockerFile variant openj9
Sending build context to Docker daemon  1.549MB
Step 1/7 : FROM openjdk_container
 ---> 260c5adf1759
Step 2/7 : MAINTAINER AdoptOpenJDK <adoption-discuss@openjdk.java.net>
 ---> Running in cc55c9fc5669
Removing intermediate container cc55c9fc5669
 ---> 6a85c7d28bee
Step 3/7 : RUN apt-get update     && apt-get install -qq -y --no-install-recommends        autoconf        ccache        cpio        file        g++-4.8        gcc-4.8        libdwarf-dev        libelf-dev        libfontconfig        libfreetype6-dev        libnuma-dev        pkg-config        ssh     && rm -rf /var/lib/apt/lists/*
 ---> Running in 5ee1d11c1e09
Reading package lists...
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
```

At this point I am not sure if I am skipping some implied steps, running on an unsupported environment or if this is a genuine issue.

**Comment by karianna** [comment]
Hmm, So docker on windows uses virtual box under the hood right?

**Comment by karol-marcjan-gl** [comment]
No, it uses Hyper-V.

**Comment by karianna** [comment]
OK, I'm trying locally (docker for Mac)

**Comment by karianna** [comment]
So I get further than you and hit the jdk8u github repo is empty issue - which makes sense as we're trying to rebuild it at the moment.  So you should see something like the output in the log attached
[jdk8u-openj9-docker-build.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/2374744/jdk8u-openj9-docker-build.txt)

**Comment by karianna** [comment]
I think you'll need to wait until we have that source repo back up - hopefully by the end of today.

**Comment by AdamBrousseau** [comment]
I'm not sure if you need to use the Adopt build scripts, but if you're just looking to build OpenJ9, there are instructions from the OpenJ9 project which have the option to use Docker.
https://github.com/eclipse/openj9/blob/master/buildenv/Build_Instructions_V8.md

**Comment by karianna** [comment]
@karol-marcjan-gl Source repo is back up - can you try again?

**Comment by M-Davies** [comment]
Ping @karol-marcjan-gl . Did you manage to resolve this issue?

**Comment by karol-marcjan-gl** [comment]
We did not investigate further at $WORK. By the time we got back to, suitable official builds were available.

**Comment by M-Davies** [comment]
Since no other users have reported this issue recently, the problem has likely been patched. Can this be closed?
