### ISSUE TITLE
Trying to set V=1 via MAKE_ARGS_FOR_ANY_PLATFORM fails

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#509]
Based on  trying it with the openjdk8_openj9 build:
```
Building the JDK: calling 'make V=1 '
Building OpenJDK for target 'default' in configuration 'linux-ppc64-normal-server-release'

## Starting langtools
Compiling 2 files for BUILD_TOOLS
Compiling 32 properties into resource bundles
Compiling 782 files for BUILD_BOOTSTRAP_LANGTOOLS
Build timed out (after 1 minutes). Marking the build as aborted.
gmake[1]: *** No rule to make target `all', needed by `default'.  Stop.
make: *** [langtools-only] Error 2
Failed to make the JDK, exiting
Build was aborted
Archiving artifacts
Recording test results
None of the test reports contained any result
Finished: ABORTED
```

**Comment by M-Davies** [comment]
@sxa is this still an issue? I can't see `MAKE_ARGS_FOR_ANY_PLATFORM` in this repo anymore?

**Comment by sxa** [comment]
If it doesn't, then the question is still outstanding as to how you enable `V=1`

**Comment by karianna** [comment]
> If it doesn't, then the question is still outstanding as to how you enable `V=1`

@sxa What is V=1 for? Is that an OpenJ9 only thing?

**Comment by karianna** [comment]
I'm able to run `make V=1` locally.  @sxa can you give us the full CL that you're using?

**Comment by sxa** [comment]
It was in [this job](https://ci.adoptopenjdk.net/job/openjdk8_j9_ppcle_centos_test/8/console) where I was trying to set `V=1` when using `makejdk-any-platform.sh`

**Comment by karianna** [comment]
> It was in [this job](https://ci.adoptopenjdk.net/job/openjdk8_j9_ppcle_centos_test/8/console) where I was trying to set `V=1` when using `makejdk-any-platform.sh`

I can't quite see how that got passed in.  The build config isn't being sent to stdout for that build - did you manually edit the makejdk-any-platform.sh file or ?

**Comment by sxa** [comment]
I can't seem to replicate what I was trying to do at the moment (or remember why I needed it during the build...) so I'll close this and reopen if/when I remember
