### ISSUE TITLE
Run CI tests on openjdk-build submissions

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#52]
Changes to the build scripts should be tested before merging.

Maybe we can use the PR builder to check that any proposed changes are not breaking the build before accepting them - provided the test runs are not producing artefacts that flow into pipeline.

**Comment by neomatrix369** [comment]
I do this manually atm but that would be great to spin it off on an instance between we merge it

**Comment by tellison** [comment]
As a start, I have submitted #57 to do some static testing of our scripts using Travis.

Further work required to fix output from shellcheck.  Any false positives can be flagged using structured comment,
```
# shellcheck disable=code[,code...]
statement_where_warning_should_be_disabled
```

**Comment by karianna** [comment]
New Pull Request Builder mechanism enables this.  Currently compiles the build scripts but does not yet kick off a test pipeline.

**Comment by M-Davies** [comment]
@karianna @tellison Any more progress on this? I'm looking to start cleaning up this repo

**Comment by karianna** [comment]
We actually had this running for some time (although it currently has a bug).  Closing this in favour of raising a new bug.
