### ISSUE TITLE
No version available for ppc64_linux (Big Endian)

### ISSUE THREAD

**Issue by illingtonFlex** [AdoptOpenJDK/openjdk-build#561]
Looks like OpenJDK had a port for ppc64_linux at one point, as listed here: http://cr.openjdk.java.net/~simonis/ppc-aix-port/index.html

Now the only ppc versions available are ppc64le_linux and ppc64_aix. Can we get binaries for ppc64_linux (non-le)?

**Comment by karianna** [comment]
We'll need to source a host for this and see if it's still supported.

**Comment by gdams** [comment]
@illingtonFlex would you be in a position to help us source ppcbe linux?

**Comment by gdams** [comment]
closing as no infra available
