### ISSUE TITLE
Consider using https://github.com/agl/extract-nss-root-certs as part of extracting CA certificates from the Mozilla ca bundle.

### ISSUE THREAD

**Issue by dbaxa** [AdoptOpenJDK/openjdk-build#563]
Consider using https://github.com/agl/extract-nss-root-certs as part of extracting CA certificates from the Mozilla ca bundle.

**Comment by dbaxa** [comment]
You might find https://github.com/asecurityteam/add-mozilla-ca-certs-to-java-keystore/blob/master/diff_java_keystores.py (I can change the licence if that is desired).

**Comment by karianna** [comment]
@johnoliver I think this is superseded now correct?

**Comment by johnoliver** [comment]
Possibly, currently we support shipping both the JEP319 certs and the mozilla cert list, we could go with only supporting the JEP319 list

**Comment by karianna** [comment]
We'll need to decide on our certs policy - TBD in the security team

**Comment by ccmtaylor** [comment]
it would be great to reach a decision on this. The cacerts that ship with adoptopenjdk-jdk8 don't allow successful requests to very common sites, e.g. https://google.com/. In the meantime, would it make sense to call out this difference from oracle's JDK more explicitly? I imagine many people will transition from oracle JDK-8 due to the expiring support timeframe.

**Comment by ccmtaylor** [comment]
Apparently there was a regression in jdk8u181-b13, see #676.

**Comment by johnoliver** [comment]
I think we should probably just remove support for non-JEP319 certs

**Comment by karianna** [comment]
> I think we should probably just remove support for non-JEP319 certs

Do we know what the diff between them are?

**Comment by gdams** [comment]
@johnoliver did this happen?

**Comment by gdams** [comment]
ping @johnoliver

**Comment by M-Davies** [comment]
@johnoliver Any update on this?

**Comment by johnoliver** [comment]
@M-Davies there has been no change in our certs, I would prefer to remain inline with the upstream certs unless there is a compelling reason not to

**Comment by aahlenst** [comment]
Let's see how https://github.com/AdoptOpenJDK/openjdk-support/issues/13 is going to turn out. There's currently a discussion on jdk-dev to improve the the status quo.

**Comment by karianna** [comment]
The discussion at OpenJDK has been interesting, but I'm not getting a sense that there's broad consensus to change.  So I think this goes back to the TSC to see if we add them regardless.

**Comment by aahlenst** [comment]
Superseded by https://github.com/AdoptOpenJDK/openjdk-build/pull/2033.
