### ISSUE TITLE
docker builds leave volumes behind even when cleaning

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#583]
Even when you pass in the --clean-docker-build flag it still uses the old volume.

Another side issue to think about is that even if you wanted to keep the volume, having used a volume for say jdk8u and then building jdk9u means you'll get errors.  So maybe we need to detect and warn about that.

Maybe the volume should only be kept if you use the --keep flag?

**Comment by karianna** [comment]
potential suggested fix is to suffix the volume with the version and variant of the build

**Comment by amczarny** [comment]
The -c will properly clean the voulmes and containers. Thera is also a suffix for diffrent jdk build. 
I sugguest to close the issue.
