### ISSUE TITLE
Do something to help with docker build not being able to copy back to host if UID!=1000

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#585]

**Comment by gdams** [comment]
@sxa555 was this fixed by https://github.com/AdoptOpenJDK/openjdk-build/pull/1353?

**Comment by sxa555** [comment]
Probably for @Willsparker to confirm

**Comment by Willsparker** [comment]
Yeah - Having the same UID in the container as the person that started the docker-build gives both permission to write to the shared folder, so this should be fixed.
