### ISSUE TITLE
JDK11 Release status page does not differentiate between largeHeap & not 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#588]
The test links on this page:
https://github.com/AdoptOpenJDK/openjdk-build/wiki/OpenJDK11-Release-Status

got to the [same location](https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_linux) for openjdk11_j9_openjdktest_x86-64_linux and openjdk11_j9_openjdktest_x86-64_linux_largeHeap tests (and also for systemtest, but I believe we need to enable systemtests for that 'flavour').

Also appears that we have not triggered the largeHeap tests since mid-Sept, will check if behaviour of top-level pipelines has changed.

**Comment by pshipton** [comment]
Not just the test links, but the JVM build as well.

**Comment by smlambert** [comment]
The build/compile jobs are linked to in the Platform column and those are different:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-linux-x64-openj9/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-linux-x64-openj9-linuxXL/

The Release job (which publishes the binaries to the website) are the same.  This one makes some sense as the 2 binaries are now stored together, and to fetch them you have to add an additional piece to the query you use:
"https://api.adoptopenjdk.net/v2/binary/${SDK_RESOURCE}/${OPENJDK_VERSION}?openjdk_impl=${JDK_IMPL}&os=${os}&arch=${arch}&release=${RELEASES}&type=${TYPE}&heap_size=${heap_size}"
where heap_size=large is set for retrieving the XL build.

**Comment by M-Davies** [comment]
@smlambert Is this still an issue?

**Comment by smlambert** [comment]
The new bigger issue is that none of the links on https://github.com/AdoptOpenJDK/openjdk-build/wiki/OpenJDK11-Release-Status go to a valid location (get 404 error for it).

<img width="455" alt="Screen Shot 2020-05-18 at 8 44 36 AM" src="https://user-images.githubusercontent.com/2836948/82214457-dbbfce00-98e3-11ea-8f54-7c13728081fd.png">

**Comment by M-Davies** [comment]
> Current link: `https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11/job/jdk11-linux-s390x-hotspot/`
> vs
> Fixed link: `https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-hotspot/`

This should be a pretty easy fix for those with Wiki access

**Comment by smlambert** [comment]
Yep, I have updated the build links on that page, please leave this issue open, as I will slowly update the table to contain the appropriate test links also (then I will close this issue once all updates are finished).

**Comment by smlambert** [comment]
I have updated the table on that wiki page, but also put a note to advise using trss.adoptopenjdk.net for a more complete view of test results, as this wiki is a static set of links to only the sanity level testing (not all of the testing that is triggered via the build pipelines, and is not the up-to-date set of platforms that are built.  As no one will want to keep updating this wiki page each time we add platforms or tests, recommended deprecation.

Also noted that if Jenkins API is slow to respond with states of the jobs, Github wiki pages must have a default timeout, where occasionally this page takes too long to render, and you get an error.
