### ISSUE TITLE
Should Website section in Wiki move to openjdk-website?

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#6]
Doesn't seem to fit here, although a link to it in the other repo would make sense?

**Comment by tellison** [comment]
Are you talking about the [build wiki](https://github.com/AdoptOpenJDK/openjdk-build/wiki) linked from the [get involved](http://adoptopenjdk.net/getinvolved.html) website page?

The intention is that developers who want to contribute to the adoptopenjdk infrastructure should be technical enough, and trusted well enough, to update the instructions trivially via the wiki.  The website is primarily focused on simplicity for Java users.

**Comment by karianna** [comment]
I just a wiki to wiki shift 🙂

**Comment by karianna** [comment]
I ended up just deleting that wiki page here since the openjdk-website had the same content in Contributing.md
