### ISSUE TITLE
Cache artifacts (pre-built or compiled) specific to build environments 

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#60]
I have been noticing that all our build jobs download the same artifacts again and again, some of them are build in the respective environment - and thrown away.

Would it be better to cache them via the build/CI tool itself - this would speed up our builds across all environments, especially the slower ones i.e. ARM.

This may overlap with the need for `ccache` - might need further investigation.

**Comment by tellison** [comment]
The scripts used to check for dependencies that will be built into the JDK (fonts, sound, certs, etc) and not download them multiple times.  Your observation sounds like a regression.

**Comment by neomatrix369** [comment]
ccache seems to be working since recent builds:
```
Build performance summary:
* Cores to use:   1
* Memory limit:   2021 MB
* ccache status:  installed and in use   <=====
```

We still need to look into other aspects of the build that can be cached.

**Comment by karianna** [comment]
Closing - folks can raise specific issues as needed.
