### ISSUE TITLE
Enable and bundle an openssl library with OpenJ9 0.11.0 builds

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#604]
The OpenJ9 0.11.0 release is coming in Oct, with final builds created for Oct 19.

One of the features [1] of the release is using the openssl 1.1.x library, which we'd like to bundle with the OpenJ9 Java 8 build for the time being.
[1] https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/112

There is a choice to use a pre-built openssl library installed on the build machines (including header files), however this means the machines will need to be updated every time there is a security fix required. This affects all platforms: Windows 32-bit, 64-bit, Linux, AIX, macOS (later).

If you use pre-built OpenSSL binary, then
- use the following configure option, --with-openssl=path_to_openssl_library and --enable-openssl-bundling

If you are building openssl binary with openJDK8, then
- use --openssl-version=1.1.XX with ‘bash get_source.sh’ command. (NOTE : For Windows platform, building openssl from source along with OpenJDK8 had a known issue and has to use pre-built openssl binary); and
- use the following configure option, --with-openssl=fetched and --enable-openssl-bundling

**Comment by pshipton** [comment]
@sxa555 @smlambert @DanHeidinga @enasser @mstoodle @mbvreddy

**Comment by pshipton** [comment]
I expect the openssl 1.1.1 should be used since it is the latest stable version and the LTS version.
https://www.openssl.org/source/

**Comment by pshipton** [comment]
fyi the openssl build instructions for Windows

Requirement are [ActivePerl](https://www.activestate.com/activeperl/downloads) and [nasm](https://www.nasm.us/pub/nasm/releasebuilds/2.13.03/) to build OpenSSL. Install it and add it to PATH.

**Windows 32-bit**
```
set PATH="C:\Program Files\NASM\";C:\Perl64\site\bin;C:\Perl64\bin;%PATH%
call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat"
cd openssl-src
perl Configure VC-WIN32 --prefix=C:\OpenSSL-1.1.1-x86_32
nmake
nmake install
```

**Windows 64-bit**
```
set PATH="C:\Program Files (x86)\NASM";C:\Perl64\site\bin;C:\Perl64\bin;%PATH%
call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
cd openssl-src
perl Configure VC-WIN64A --prefix=C:\OpenSSL-1.1.1-x86_64
nmake
nmake install
```

**Comment by pshipton** [comment]
Note only 1.1.0 works for zlinux at this time. https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/122

**Comment by sxa555** [comment]
zLinux issue covered and resolved under https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/527. Closing now that PRs have gone in to add the appropriate options to the JDK8/J9 bulids
