### ISSUE TITLE
IIOException "tEXt chunk length is not proper" on opening png file.

### ISSUE THREAD

**Issue by JanVomlel** [AdoptOpenJDK/openjdk-build#608]
When I try to read some png files, I get exception:

    at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:891)
    at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.getImageMetadata(PNGImageReader.java:1799)
    Caused by: javax.imageio.IIOException: tEXt chunk length is not proper
    at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.parse_tEXt_chunk(PNGImageReader.java:575)
    at java.desktop/com.sun.imageio.plugins.png.PNGImageReader.readMetadata(PNGImageReader.java:847)
    .. 28 more

I think there are errors in file PNGImageReader. For example on line 574:
    if (textLength <= 0) {
        throw new IIOException("tEXt chunk length is not proper");
    }
Right condition is: 
    if (textLength < 0) {
        throw new IIOException("tEXt chunk length is not proper");
    }
Similar problem is on a few other lines.

Bug can be tested on the image:
[matlabc1](https://user-images.githubusercontent.com/12710508/46531012-fc1c4f80-c89b-11e8-91ec-65a81ae63f0f.png)

**Comment by karianna** [comment]
@JanVomlel Can you give us the exact version of the AdoptOpenJDK binary that you are using?

**Comment by karianna** [comment]
@JanVomlel and is this also an issue with Oracle's OpenJDK 11 release (You can grab this from https://jdk.java.net).  I'm trying to ascertain if this is an overall OpenJDK problem that needs to be reported upstream.  Which O/S Platform are you running?

**Comment by JanVomlel** [comment]
Windows x64, OpenJDK 11 with Hotspot
On version 10 it is working well.

**Comment by karianna** [comment]
Hi @JanVomlel OK I think this is a genuine upstream bug.  Are you familiar with the OpenJDK mailing lists?

**Comment by sameer1sharma** [comment]
Thank you Karianna. 
**I have tested with 11.0.2 version (openjdk-11.0.2_windows-x64_bin), it is working fine.** Kudos. 
Is it stable version(11.0.2) release?

Thanks,
Sameer Sharma

**Comment by karianna** [comment]
> Thank you Karianna.
> **I have tested with 11.0.2 version (openjdk-11.0.2_windows-x64_bin), it is working fine.** Kudos.
> Is it stable version(11.0.2) release?
> 
> Thanks,
> Sameer Sharma

Yes it's the stable release
