### ISSUE TITLE
OpenJ9 0.9 releases are missing the xlinux large heap build

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#610]
The OpenJ9 0.9 releases are missing the xlinux large heap builds

https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9

https://adoptopenjdk.net/archive.html?variant=openjdk10&jvmVariant=openj9

**Comment by sxa555** [comment]
The good news is that it's still there at https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/releases/tag/jdk8u181-b13_openj9-0.9.0

**Comment by sxa555** [comment]
The solution in that PR is a bit of a "tactical fix" and is a result of the filenames being changed from `LinuxLH` to `LinuxXL`. The change in https://github.com/AdoptOpenJDK/openjdk-website/pull/319 was put in for JDK11 and is what caused it to disappear from the JDK8 release

@pshipton Hypothetically, would it be a problem if we left mt fix in place until we did a subsequent JDK8/J9 release with the "new" name and then undid it when we do the next JDK8.J9 release? - this would have the side effect of the 8u181 LH build not being visible on the web site but would still be available as part of the release downloadable on github?

**Comment by pshipton** [comment]
@sxa555 I'm a little fuzzy on the meaning of your comment, but I chatted with @DanHeidinga and we think the Java 8 0.9 release should have a large heap download, even if this breaks it for Java 11 until the October release.

**Comment by sxa555** [comment]
@pshipton The question is "Would you be ok with the Java 8 0.9 large heap release not being visible after we have done the next quarterly release of Java 8 0.11?" - The builds would still be available directly from the github release, but not necessarily from the web site.

**Comment by DanHeidinga** [comment]
I can live with that.  As long as the current release (what ever it is at any given moment) has a large heap download from the website.

**Comment by johnoliver** [comment]
I think the solution here is to identify large heap builds based on the "heap_size" property that the api returns rather than searching for strings in the filename. The heap_size returned is correct between 8/9/10 and binaries release before and after the script migration

**Comment by sxa555** [comment]
@johnoliver I believe https://github.com/AdoptOpenJDK/openjdk-website/pull/333 addresses the concerns therefore I'm closing this issue ... If I'm mistaken please reopen ;-)

**Comment by pshipton** [comment]
@sxa555 I cannot re-open this issue. The xlinux large heap build is still not being shown on the jdk8 archive page. https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9

**Comment by pshipton** [comment]
Opened a new issue #639
