### ISSUE TITLE
Name all versions the same way

### ISSUE THREAD

**Issue by alexhass** [AdoptOpenJDK/openjdk-build#611]
I feel stressed by the different version schemas you are using. Every release changes the version string. I have no idea why this is so inconsistent.

Could you build with "one" version schema that is always the same, please?

Not:

- jdk8u172-b11
- 10.0.2.13 (good)
- 10.0.2.13_openj9-0.9.0
- 11_28

But simply a semantic version like

- 8.0.172.11
- 10.0.2.13
- 11.0.0.28

Creating a setup builder with such a version string chaos is not funny and now every ZIP has additional "random" version numbers.

**Comment by karianna** [comment]
Hi @alexhass - unfortunately we have to follow the version strings that upstream OpenJDK and OpenJ9 projects provide.  This ensures that tooling in the ecosystem 'just works'.
