### ISSUE TITLE
Create JRE builds

### ISSUE THREAD

**Issue by alexhass** [AdoptOpenJDK/openjdk-build#616]
I have seen there have been some pulls to allow JRE builds, but I cannot download them. Can you build JRE versions, please?

I'd like to create a MSI setup for JRE asap.

**Comment by karianna** [comment]
@alexhass Which JRE's are you not seeing?  openjdk11-binaries repo has them for 11...

**Comment by alexhass** [comment]
Oh - I looked only at https://adoptopenjdk.net/

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11%2B28 looks good.

**Comment by ChristianCiach** [comment]
If not for this ticket, I would have never found the JRE downloads. I think the JRE releases should be offered at https://adoptopenjdk.net/

**Comment by karianna** [comment]
I'll open a website ticket

**Comment by lootkips** [comment]
Any updates? or if there are guides on how to build a .msi off the JRE publised on the site...
I found this guide: http://hg.openjdk.java.net/jdk8/jdk8/raw-file/tip/README-builds.html
but was wondering if it is applicable

**Comment by karianna** [comment]
> Any updates? or if there are guides on how to build a .msi off the JRE publised on the site...
> I found this guide: http://hg.openjdk.java.net/jdk8/jdk8/raw-file/tip/README-builds.html
> but was wondering if it is applicable

The work to build MSI is over at openjdk-installers repo.
