### ISSUE TITLE
OpenJ9 0.9 archive lists are missing the xlinux large heap build

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#639]
Opened #610 for this issue, which was closed although the issue is not fixed. I cannot reopen #610.

The OpenJ9 0.9 archive lists are missing the xlinux large heap builds

https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9

https://adoptopenjdk.net/archive.html?variant=openjdk10&jvmVariant=openj9

**Comment by karianna** [comment]
Suspect this is a website or API issue - https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9 does show a Linux Large Heap variant.

@johnoliver Is this the XL vs LH suffix issue we were discussing?  I think your new properties based solution should avoid that issue....
