### ISSUE TITLE
SHA file not correct

### ISSUE THREAD

**Issue by jsander128** [AdoptOpenJDK/openjdk-build#640]
In the SHA file from OpenJDK 11 with Hotspot is a wrong file name.
The tool "sha256sum" can not validate against this SHA file.

`sha256sum -c OpenJDK11-jdk_x64_linux_hotspot_11_28.tar.gz.sha256.txt
sha256sum: target/linux/x64/hotspot/OpenJDK11-jdk_x64_linux_hotspot_11_28.tar.gz: No such file or directory
target/linux/x64/hotspot/OpenJDK11-jdk_x64_linux_hotspot_11_28.tar.gz: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
`

**Comment by karianna** [comment]
@jsander128 Should now be resolved.
