### ISSUE TITLE
Provide a new platform linux-x64 with ZGC enabled

### ISSUE THREAD

**Issue by PierreZ** [AdoptOpenJDK/openjdk-build#641]
Hi !

Today, I wanted to play a bit with [ZGC](https://wiki.openjdk.java.net/display/zgc/Main). I downloaded the release `jdk8u172-b11` on [https://adoptopenjdk.net/](https://adoptopenjdk.net/), and I was surprised to see this log when starting my application:

```
Unrecognized VM option 'UseZGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

From what I can see [here](https://wiki.openjdk.java.net/display/zgc/Main), ZGC needs to be enabled with at compile time with a `sh configure --with-jvm-features=zgc`

I know that zGC is considered experimental, but I think it will help developers to be able to retrieve a linux-x64 platform with zGC enabled. As ZGC is currently only available on Linux/x64, we could only add a special platform target, something like OpenJDK11-jdk_x64_linux_hotspot_zgc for example?

**Comment by netroby** [comment]
Need zgc, jdk 11 now can use zgc

**Comment by gyakovlev** [comment]
looks like jdk 11.0.3+ builds will enable it by default according to this page
https://wiki.openjdk.java.net/display/zgc/Main

> If you are building early versions of JDK 11 (versions 11.0.0, 11.0.1 or 11.0.2), you need to supply the configure option `--with-jvm-features=zgc` to enable building of ZGC. This option is no longer needed (ZGC is built by default) as of JDK 11.0.3 and JDK 12.

**Comment by M-Davies** [comment]
@PierreZ Ref https://github.com/AdoptOpenJDK/openjdk-build/issues/641#issuecomment-458234964, can this be closed?

**Comment by PierreZ** [comment]
Yes, thanks 👍
