### ISSUE TITLE
Unclear issue when run makejdk-any-platform.sh on MacOsx

### ISSUE THREAD

**Issue by s50600822** [AdoptOpenJDK/openjdk-build#649]
Not sure if I'm doing it wrong but I wasn following the readme instruction, no idea what it means though:
_./makejdk-any-platform.sh jdk8u
Starting ./makejdk-any-platform.sh to configure, build (Adopt)OpenJDK binary
Working dir is ./build/
[debug] COPY_MACOSX_FREE_FONT_LIB_FOR_JDK_FLAG=false
[debug] COPY_MACOSX_FREE_FONT_LIB_FOR_JRE_FLAG=true
JDK Image folder name: j2sdk-bundle/jdk*.jdk
JRE Image folder name: j2re-bundle/jre*.jre
Searching for JDK_BOOT_DIR
usage: dirname path
usage: dirname path_

**Comment by karianna** [comment]
I'm unable to reproduce this. Do you have the very latest version of this repo cloned?

**Comment by karianna** [comment]
Ah OK, I think I see what the problem might be.

What version of OSX are you using and are you using the bash shell when you execute this?

**Comment by karianna** [comment]
Try manually running:

`$(dirname $(dirname $(readlink $(which javac))))` and see what the response is

**Comment by s50600822** [comment]
Hi I no longer have that msg. Currently if I ran that, it will bring me to:
➜  Current pwd
/System/Library/Frameworks/JavaVM.framework/Versions/Current

But yesterday after unable to build it from source I went ahead to switch from Oracle to Adopt with the method and distribution from https://adoptopenjdk.net/installation.html#x64_mac-jdk 

Now I no longer have that issue

I think it's no longer needed but my system was:
MacOSx High Sierra 10.13.6 (17G2307)
at the time I was using Oracle JDK 181

**Comment by karianna** [comment]
Hi @s50600822 - OK you'd need to set the boot JDK to be Java 7 and also have Xcode 4.2 installed.  So probably easiest to use the binary from the website :-).
