### ISSUE TITLE
Can the jdk come with jvisualvm

### ISSUE THREAD

**Issue by s50600822** [AdoptOpenJDK/openjdk-build#656]
Oracle JDK include https://visualvm.github.io/ among JAVA_HOME/bin
Recently I switched to AdoptOpenJDK and as a habit I invoke jsivualvm to poke my running JVM when it's running slow, only to realized it wasn't included. Would be cool if it is.

**Comment by karianna** [comment]
visualvm is no longer provided with OpenJDK but you can get it independently from https://visualvm.github.io/

**Comment by s50600822** [comment]
> visualvm is no longer provided with OpenJDK but you can get it independently from https://visualvm.github.io/

ah yeah that was what I ended up doing. I'm just saying it's kind of a nice "feature" to include. You meant it used to be included but removed for some reason?
