### ISSUE TITLE
OpenJDK8-OPENJ9_x64_Windows_jdk8u181-b13_openj9-0.9.0 has an empty cacerts

### ISSUE THREAD

**Issue by p0nder** [AdoptOpenJDK/openjdk-build#659]
Despite #478 being closed, the current latest release that can be downloaded via https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9 still contains an empty truststore. Are you planning to have an official release with a populated truststore anytime soon?

**Comment by p0nder** [comment]
Are you planning to publish a fixed release anytime soon?

**Comment by sxa555** [comment]
It'll be fixed when the 192 release comes out which should be in the next few days

**Comment by johnoliver** [comment]
If you are desperate, there are nightlys with the cacerts https://adoptopenjdk.net/nightly.html?variant=openjdk8&jvmVariant=openj9

**Comment by p0nder** [comment]
@johnoliver thank you for the alternative!
@sxa555 Thank you for giving me an estimate.

**Comment by ericparton** [comment]
Is this being fixed for OpenJDK11 as well? I have OpenJDK11U-jdk_x64_mac_hotspot_11.0.1_13 and I don't see a jre/lib/security/cacert file in the JAVA_HOME there either.

**Comment by karianna** [comment]
> Is this being fixed for OpenJDK11 as well? I have OpenJDK11U-jdk_x64_mac_hotspot_11.0.1_13 and I don't see a jre/lib/security/cacert file in the JAVA_HOME there either.

11 should have them, that's a bug.

**Comment by ericparton** [comment]
@karianna should I create a different issue for that?

**Comment by karianna** [comment]
> @karianna should I create a different issue for that?

Yes please.

**Comment by sxa555** [comment]
@ericparton Looks to me like Contents/Home/lib/security/cacerts is present in the mac JDK11/J9 downloads - can you clarify exactly which download you're using that doesn't appear to have it?

**Comment by ericparton** [comment]
@sxa555 It looks like it is there in at Contents/Home/lib/security. I'm on the mac, and I was trying to find it in the same location that the Oracle jdk used to have it at, which was jre/lib/security. Thanks for the clarification

**Comment by p0nder** [comment]
I forgot to answer here that I've downloadedOpenJDK8U-jdk_x64_windows_openj9_8u192b12 a couple of days ago and the truststore was populated. Thanks for fixing it!
