### ISSUE TITLE
Tarball paths start with a leading './'

### ISSUE THREAD

**Issue by cykl** [AdoptOpenJDK/openjdk-build#660]
Unlike Oracle JDK,  Oracle builds of OpenJDK and Zulu, AdoptOpenJDK tarballs contain paths with a leading './'

```bash
$ for f in *.tar.gz ; do echo ${f} ; tar tvf ${f} | head -n 1 ; done
jre-1.8.0_162-linux-x64.tar.gz
drwxr-xr-x java_re/java_re   0 2017-12-20 06:24 jre1.8.0_162/
openjdk-11.0.1_linux-x64_bin.tar.gz
-rwxr-xr-x mach5-one/mach5grp 12952 2018-10-06 14:17 jdk-11.0.1/bin/jaotc
OpenJDK11-jdk_x64_linux_hotspot_11_28.tar.gz
drwxrwxr-x jenkins/jenkins   0 2018-10-02 21:45 ./jdk-11+28/          <----- HERE
OpenJDK11-jdk_x64_linux_hotspot_2018-10-18-04-53.tar.gz
drwxrwxr-x jenkins/jenkins   0 2018-10-17 20:32 ./jdk-11+28/          <----- HERE
OpenJDK8U-jdk_x64_linux_hotspot_2018-10-17-11-36.tar.gz
drwxrwxr-x jenkins/jenkins   0 2018-10-17 05:45 ./jdk8u181-b13/       <----- HERE
zulu11.1+23-ea-jdk11-linux_x64.tar.gz
drwxrwxr-x tester/tester     0 2018-07-19 13:57 zulu11.1+23-ea-jdk11-linux_x64/
```

This is not an issue when you untar the archive using something like `tar xf`, all those JDKs create a subfolder and put their files in it.

Discrepancies appears when you strip top level directory. 

```bash
$ tar --extract -C /tmp/oracle/ -z --show-transformed-names --strip-components=1 -f /tmp/jre-1.8.0_162-linux-x64.tar.gz 
$ tar --extract -C /tmp/adoptopenjdk/ -z --show-transformed-names --strip-components=1 -f /tmp/OpenJDK11-jdk_x64_linux_hotspot_11_28.tar.gz 
$ ls -1 /tmp/adoptopenjdk/ | head -2
jdk-11+28                                   <---- EXTRA DIR HERE
$ ls -1 /tmp/oracle/ | head -2
bin
COPYRIGHT
```

As top level directory naming varies across JDKs, striping it is quite useful when you automatically install JDKs. Installer sets directory name rather than trying to guess it from the archive. As of now, AdoptOpenJDK is the only JDK I am aware requiring  `--strip-components=2`... which is quite annoying.

Would it be possible to align AdoptOpenJDK tarballs with the predominant behaviour?

**Comment by sxa555** [comment]
Interesting. When I tar stuff I usually automatically use `.` instead of `*` as the source to ensure it picks up any subdirs prefixed with `.` ... But yeah I can see why that would be a concern. Good spot!

**Comment by karianna** [comment]
I don't think we'll be impacting too many consumers at this stage.

I think we only use `--strip-components=2` when we pull in an AdoptOpenJDK 10 build in order to bootstrap an 11 build.  I'd go ahead and submit a PR and we can discuss it further.

**Comment by M-Davies** [comment]
@cykl Any update on this? I notice some progress has been made in the commits referenced above?

**Comment by sxa** [comment]
@M-Davies Can you check our current tarballs? I had it in my head that this was fixed

**Comment by M-Davies** [comment]
@sxa I couldn't see a leading `./` anymore (for the mac and linux tarballs at least)
```
(base) ➜  Downloads ls | grep Open
OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz
(base) ➜  Downloads for f in *.tar.gz ; do echo ${f} ; tar tvf ${f} | head -n 1 ; done
OpenJDK11U-jdk_x64_linux_hotspot_11.0.7_10.tar.gz
drwxr-xr-x  0 root   root        0 15 Apr 11:30 jdk-11.0.7+10/
```

**Comment by sxa** [comment]
LGTM - Let's close this :-)
