### ISSUE TITLE
./makejdk-any-platform.sh --docker fails on Fedora because of SELinux

### ISSUE THREAD

**Issue by cykl** [AdoptOpenJDK/openjdk-build#669]
Building a JDK using docker fails on Fedora because SELinux prevents the container to access `/openjdk/target`.

Adding a `Z` mount option fixed the issue. However, I am unsure what happens when `:Z` is set on systems that don't use SELinux or systems other than Linux. Any docker expert or guinea pig here?

**Comment by amczarny** [comment]
We use :Z with docker on Windows, Ubuntu and Fedora - no issues and Fedora can properly use -v

**Comment by cykl** [comment]
@amczarny Thanks for the feedback. I will open a PR then.

**Comment by sxa555** [comment]
Closing as PR669 should have fixed this
