### ISSUE TITLE
Win32 support split between build-softlayer-win2012r2-x64-1 (OpenJ9) and build-azure-win2008r2-x64-1 (HotSpot)

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#671]
OpenJ9 Win32 support was added in May under https://github.com/AdoptOpenJDK/openjdk-build/issues/342 and is built at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/ on [build-softlayer-win2012r2-x64-1](https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-1/)
Hotspot Win32 support was added in September under https://github.com/AdoptOpenJDK/openjdk-build/issues/384 and is built at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-hotspot/ on [build-azure-win2008r2-x64-1](https://ci.adoptopenjdk.net/computer/build-softlayer-win2012r2-x64-1/)

We need to unify these setups in order to allow multiple machines to build things so we don't have single points of failure.

@ali-ince What did you do to setup the Azure box for 32-bit HotSpot? Did you just put the 32-bit freetype on (so it's basically the same as the OpenJ9 setup) or were there other changes?

**Comment by ali-ince** [comment]
@sxa555 I've also downgraded `grep` on that machine and also on all other windows boxes. I'll pick up this after I complete JDK11 builds for windows 32-bit.

**Comment by sxa555** [comment]
@ali-ince So was it just downgrading grep and putting 32-bit freetype libs on the machines?

It looks like you've used a different directory for the freetype install. For the 32-bit hotpost freetype you're using  `--with-freetype-lib=/cygdrive/c/openjdk/freetype/lib32` whereas the openj9 builds were already configured to use `--with-freetype-lib=/cygdrive/c/openjdk/freetype-2.5.3/lib`

We need to unify those and not have duplication.

**Comment by ali-ince** [comment]
Having removed the requirement to have a pre-built freetype on build machines, and grep is already downgraded on all of the build agents (and it is also part of the playbook as well), I think it's now safe to close this.
