### ISSUE TITLE
The jdk8u192-b12 and jdk-11.0.1+13 links are not found

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#680]
Looking at https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=openj9 the link for "jdk8u192-b12" which is https://github.com/AdoptOpenJDK/openjdk8-openj9-releases/releases/tag/jdk8u192-b12 does not exist.

Similarly at https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=openj9 the link for "jdk-11.0.1+13" which is https://github.com/AdoptOpenJDK/openjdk11-openj9-releases/releases/tag/jdk-11.0.1+13 does not exist.

**Comment by sxa555** [comment]
The link is to the wrong repo - Should be openjdk11-binaries and openjdk8-binaries. Will look at sorting that.

**Comment by karianna** [comment]
@sxa555 probably an API code change?

**Comment by gdams** [comment]
closing as they now work for me
