### ISSUE TITLE
Launching JAR gives a registry error on Windows

### ISSUE THREAD

**Issue by xtbe** [AdoptOpenJDK/openjdk-build#685]
When launching a JAR via the command line on Windows x64 you might get this Warning/Error message. This was tested on a system without any Oracle JDK/JRE

“Could not open/create prefs root node Software/JavaSoft/Prefs at root. Windows RegCreateKeyEx(...) returned error code 5.

**Comment by xtbe** [comment]
The warning/error is gone if you manually create the key in the registry

**Comment by sxa555** [comment]
Which was the key you created to resolve this?

**Comment by xtbe** [comment]
HKLM/SOFTWARE/JavaSoft/**Prefs**

**Comment by gdams** [comment]
is this a build issue? Seems like something that could be added to the installers if needed?

**Comment by karianna** [comment]
> is this a build issue? Seems like something that could be added to the installers if needed?

@xtbe Are you able to provide a sample JAR?  Was this just `java -jar foobar.jar` you executed?

**Comment by xtbe** [comment]
Will test again with the latest available installer to verify if the problem still exist. If still the case will add more details to this issue

**Comment by xtbe** [comment]
Tested this again with the latest MSI and this works correctly now. I took a clean Windows 10 machine, installed AdoptOpenJDK 8 (msi) and SQLWorkbench. 
Running the command java -jar sqlworkbench.jar works so this is now resolved by the installer.

The wrapper (executable) around the JAR (SQLWorkbench64.exe/SQLWorkbench.exe) doesn't work. The wrapper is based on WinRun4J. Perhaps I should report this in a separate issue.

If you need additional info, just let me know!

**Comment by karianna** [comment]
@xtbe Great!  Yes, a separate issue would be appreciated.
