### ISSUE TITLE
Please add Large Heap OpenJ9 build for MacOS

### ISSUE THREAD

**Issue by pdbain-ibm** [AdoptOpenJDK/openjdk-build#686]
At present, Eclipse IDE is not compatible with MacOS compressed references builds, cf. https://github.com/eclipse/openj9/issues/3371. However, non-compressedrefs OpenJ9 works.  Please add the latter as a standard build for use with Eclipse IDE.

**Comment by sxa555** [comment]
Prototype job created at https://ci.adoptopenjdk.net/view/work in progress/job/SXA-build-macos-jdk11-LH. Hopefully something suitable will pop out soon :-)

**Comment by sxa555** [comment]
For completeness https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9-macosXL/ has the final build job for macos/ large heap

**Comment by sxa555** [comment]
Seems to be absent on the website - reopening ;-)

**Comment by pshipton** [comment]
We'd like to have a Mac Java 8 large heap build as well.

**Comment by gdams** [comment]
@sxa555 is this fixed now? I do now see large heap binaries on the website

**Comment by sxa555** [comment]
Yep I believe so
