### ISSUE TITLE
Add Win32 build of JDK11

### ISSUE THREAD

**Issue by mosi0815** [AdoptOpenJDK/openjdk-build#687]
Due to the fact that some JNI libraries are only available for 32 bit windows we are forced to use such a JDK for a couple of our projects. Currently we are using a JDK 10 Hotspot build from Azul. It would be really great to use AdoptOpenJDK builds in the future. Hotspot would be cool and OpenJ9 amazing. :)

**Comment by karianna** [comment]
Done, please see the nightly builds.

**Comment by mosi0815** [comment]
Really?
https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=hotspot

I don't see a 32 bit variant. Also not on Github.

**Comment by karianna** [comment]
Apologies - you'll see it appear in tonights nightly build.

**Comment by mosi0815** [comment]
Cool thanks!
