### ISSUE TITLE
Missing Amazon (Starfield) and Google (Globalsign) CA certificates for jdk8

### ISSUE THREAD

**Issue by henrik242** [AdoptOpenJDK/openjdk-build#694]
It looks like the jdk8 builds (at least hotspot) lacks CA certificates that are used for Amazon AWS / Starfield (e.g kinesis.eu-west-1.amazonaws.com) and Google / Globalsign (e.g oauth2.googleapis.com and accounts.google.com).  

Any plans on adding these?

The problem is not present with jdk10 and 11.  Also, Oracle's jdk8 builds work fine.

Example exception:
```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
```

**Comment by sxa555** [comment]
Probably dup of #676

**Comment by henrik242** [comment]
Yeah, looks like it.  Thanks for the heads up,  I'll just close this.
