### ISSUE TITLE
Guard against a sudden drop of certificates in the keystore

### ISSUE THREAD

**Issue by henrik242** [AdoptOpenJDK/openjdk-build#696]
jdk8u181-b13 was released lacking a lot of commonly used CA certificates, notably the ones used by Amazon AWS (Starfield CA, e.g kinesis.eu-west-1.amazonaws.com) and Google (Globalsign CA, e.g oauth2.googleapis.com and accounts.google.com).

The certificates are back in the nightly builds, but tests should be added that guard against this happening again in the future.

Ref: #694 #676 #688

**Comment by karianna** [comment]
Some background to this: OpenJDK 8 doesn't come with any certs and so at the time of the u181 release we backported the OpenJDK 10 cacerts (which didn't cover Amazon et al).  Now that OpenJDK 11 is out we backport its cacerts which do include the Amazon et al ones.

That said we could guard against certs dropping (e.g. when we backport from 12+)

**Comment by aahlenst** [comment]
Obsolete with https://github.com/AdoptOpenJDK/openjdk-build/pull/2033.
