### ISSUE TITLE
Missing jdk-11.0.1 releases including Hotspot JVM

### ISSUE THREAD

**Issue by ChristianCiach** [AdoptOpenJDK/openjdk-build#697]
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.1%2B13 offers only downloads including the OpenJ9 JVM. Downloads including Hotspot are missing.

**Comment by karianna** [comment]
Yep - we're aware of this one :-). Working on it this week.

**Comment by limes007** [comment]
Why did you remove the first 11 release (11.0.0) from the download page?

**Comment by karianna** [comment]
They shouldn't be removed - looking into it...

**Comment by limes007** [comment]
It's back, thanks. Now I'm hoping for a 11.0.1 hotspot verison... ;-)

**Comment by taku0** [comment]
JDK 11.0.1 with Hotspot JVM is available now, but JRE is not (i.e. `OpenJDK11-jre_x64_linux_hotspot_11.0.1_13.tar.gz` is missing at the [release page](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.1%2B13)). Is this temporary or JRE builds will not be provided anymore?
What does `U` in filename `OpenJDK11U-jdk_x64_linux_hotspot_11.0.1_13.tar.gz` means? Is it a *U*nified version of JDK and JRE? JREs with OpenJ9 are still available at GitHub but not at adoptopenjdk.net. Will JRE builds be discontinued?

**Comment by gdams** [comment]
closing as 11.0.2 came out.
