### ISSUE TITLE
libjvm.so: ELF file OS ABI invalid

### ISSUE THREAD

**Issue by gnobiron** [AdoptOpenJDK/openjdk-build#698]
Hello,

When I try to use AdoptOpenJDK 8u181-b13 on RHEL 5.5 (reproduceable with a simple "java -version") I get the following error:
> Error: dl failure on line 893
> Error: failed /vif/adoptopenjdk8u181-b13/jre/lib/amd64/server/libjvm.so, because /vif/adoptopenjdk8u181-b13/jre/lib/amd64/server/libjvm.so: ELF file OS ABI invalid

The previous version 8u172-b11 is working correctly.
The latest openJDK8 version 8u192 built by Oracle is also working without error.

I can't find a page containing the officialy supported os versions for AdoptOpenJDK. Have the support for RHEL 5 been Dropped ?

**Comment by karianna** [comment]
Hi @gnobiron can I ask you to try one of the nightlies?

**Comment by gnobiron** [comment]
> Hi @gnobiron can I ask you to try one of the nightlies?

Hi, I have the same error with nightly build OpenJDK8U-jdk_x64_linux_hotspot_2018-10-29-17-46.
ldd on jdk8u181-b13/jre/lib/amd64/server/libjvm.so returns "not a dynamic executable"

But version jdk8u181 is working on a newer kernel (Centos 6.5 with kernel 2.6.32). It looks like a compilation instruction have changed between jdk8u172 and jdk8u181. Or perhaps the binary was built on a newer os version.

**Comment by karianna** [comment]
@gnobiron We'll look into it but it won't be a major priority as RHEL 5.5 was EOL in May 2015.

**Comment by gnobiron** [comment]
@karianna That's OK, we will use the version 8u172 if we absolutely need to stay on RHEL5.
Thanks.

**Comment by 4ndrej** [comment]
> @gnobiron We'll look into it but it won't be a major priority as RHEL 5.5 was EOL in May 2015.
this https://stackoverflow.com/questions/7647818/glibc-elf-file-os-abi-invalid seems to be related through multiarch binaries. Maybe you can disable multiarch in version for RHEL5

**Comment by ghollies** [comment]
Still seeing this issue on 5.11
Tested using `RHEL-5.11_GA-20141003-x86_64-2-Hourly2-GP2 (ami-3268da5a)` on AWS
Pulled down the Linux x64 JDKs from https://adoptopenjdk.net/archive.html

```
[ ~]# jdk8u172-b11/bin/java -version
openjdk version "1.8.0-adoptopenjdk"
OpenJDK Runtime Environment (build 1.8.0-adoptopenjdk-jenkins_2018_05_19_01_00-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)

[ ~]# jdk8u181-b13/bin/java -version
Error: dl failure on line 893
Error: failed /root/jdk8u181-b13/jre/lib/amd64/server/libjvm.so, because /root/jdk8u181-b13/jre/lib/amd64/server/libjvm.so: ELF file OS ABI invalid

[ ~]# jdk8u192-b12/bin/java -version
Error: dl failure on line 893
Error: failed /root/jdk8u192-b12/jre/lib/amd64/server/libjvm.so, because /root/jdk8u192-b12/jre/lib/amd64/server/libjvm.so: ELF file OS ABI invalid

[ ~]# jdk8u202-b08/bin/java -version
Error: dl failure on line 893
Error: failed /root/jdk8u202-b08/jre/lib/amd64/server/libjvm.so, because /root/jdk8u202-b08/jre/lib/amd64/server/libjvm.so: ELF file OS ABI invalid

[ ~]# jdk8u212-b03/bin/java -version
Error: dl failure on line 893
Error: failed /root/jdk8u212-b03/jre/lib/amd64/server/libjvm.so, because /root/jdk8u212-b03/jre/lib/amd64/server/libjvm.so: ELF file OS ABI invalid
```
Environment info:
```
[ ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 5.11 (Tikanga)
[ ~]# uname -a
Linux ip-10-126-8-61 2.6.18-398.el5xen #1 SMP Tue Aug 12 06:30:31 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Sharkking** [comment]
Facing the same error. Every Version > jdk8u172-b11 showing the error. Redhat Enterprise 5.11 Final

**Comment by moschinski** [comment]
FYI: The RedHat OpenJDK support matrix states that RHEL 5 is neither supported for OpenJDK 8 nor 11. For RHEL 6, OpenJDK 8 is only supported starting with 6.6:

![rhel_support](https://user-images.githubusercontent.com/1095349/64601812-ebcef780-d3bd-11e9-8abf-29a2794e6faf.png)
See [here](https://access.redhat.com/articles/1299013)

**Comment by karianna** [comment]
I'm afraid this is a case of 'won't fix' as RHEL 5 is unsupported.
