### ISSUE TITLE
Question about applet and WebStart usage with AdoptOpenJDK

### ISSUE THREAD

**Issue by SzentnerTsIT** [AdoptOpenJDK/openjdk-build#699]
Dear OpenJDK community,

we plan to use the AdoptOpenJDK 8 Windows 32 and 64 bit Hotspot distribution, but ran into following open topic. We still have some legacy products using applets and Webstart. 

Our question: How can we run those using the above Adopt distribution?
Can we consider the post below as the suggested way?
https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk

Thanks a lot in advance for your help and kind regards,
Tamás

**Comment by karianna** [comment]
Yes, the way described in the blog post is the best way forward.
