### ISSUE TITLE
OpenJ9 switching to use Clang 7 instead of mingw

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#700]
As per https://github.com/eclipse/openj9/pull/2979, OpenJ9 will shortly be switching to use clang 7 instead of mingw to compile some of the VM files. Clang 7 needs to be installed on the Windows build machines. Also note AdoptOpenJDK/openjdk-infrastructure#514

**Comment by sxa555** [comment]
Installed on both windows openj9 build machines, merged https://github.com/AdoptOpenJDK/openjdk-build/pull/701 (now that https://github.com/eclipse/openj9/pull/2979 is in) and running a build at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/167/

**Comment by sxa555** [comment]
NOTE: I have **NOT**  removed the old compiler from the machines at the time of writing.
