### ISSUE TITLE
Missing Windows x64  (jre and jdk) in jdk8u192-b12 "OpenJDK 8 with Hotspot" release

### ISSUE THREAD

**Issue by kuglo** [AdoptOpenJDK/openjdk-build#703]
https://adoptopenjdk.net/installation.html?variant=openjdk8&jvmVariant=hotspot# offers only "Windows x32" option. Option for "Windows x64" is missing.
The same for https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=hotspot and the "jdk8u192-b12"-section on https://adoptopenjdk.net/archive.html?variant=openjdk8&jvmVariant=hotspot

**Comment by Ganeshgautam** [comment]
@kuglo I am not sure if you have checked the slack message board or not... but, as per the conversations, its should be released tomorrow.

"martijnverburg [5:12 AM]
Nice one - I’ll release again tonight with the full test suite actually might as well do the other platforms tonight as well

martijnverburg [6:31 AM]
Build has kicked off - for those waiting for the aarch64 port it’s going to be tomorrow at the earliest I’m afraid.
"

**Comment by karianna** [comment]
Yep - Win64 failed we're looking into it

**Comment by karianna** [comment]
Released
