### ISSUE TITLE
Support for OpenJ9 milestone builds

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#704]
The [Eclipse handbook](https://www.eclipse.org/projects/handbook/) suggests doing milestone builds before a release. This is a pre-release build that is distinguished from typical nightly builds. It would be built from a branch and not the main line. It gives users a chance to try out a pre-release driver containing new features and report any problems. Which provides development a chance to fix the reported problems before the release is finalized.

For the OpenJ9 0.12.0 release in January 2019, milestone builds are scheduled in the [plan](https://projects.eclipse.org/projects/technology.openj9/releases/0.12.0/plan) for Dec 17 and Jan 7.

The milestone build would be named similar to a release but contain M1 in the name, i.e. _openj9-0.12.0M1. FYI the outstanding 0.11.0 naming problem #678

The OpenJ9 [release process](https://github.com/eclipse/openj9/blob/master/doc/processes/release_process.md) describes the format of the OpenJ9 milestone release tags, although since AdoptOpenJDK builds from an OpenjDK extensions branch, this part would be invisible to the Adopt build.

**Comment by pshipton** [comment]
Edited the description to add the Dec 17 OpenJ9 milestone date.

**Comment by sxa555** [comment]
Related: https://github.com/AdoptOpenJDK/openjdk-website/issues/217 (Could handle both under the same concept of "significant prerelease build")

**Comment by pshipton** [comment]
> Could handle both under the same concept of "significant prerelease build"

Works for me.

**Comment by gdams** [comment]
@pshipton can we close this?

**Comment by gdams** [comment]
@lumpfish @andrew-m-leonard do you know if this is good to be closed?

**Comment by andrew-m-leonard** [comment]
@pshipton are we happy with the current way we handle milestone builds?

**Comment by pshipton** [comment]
I would like the milestone builds to be more prominent on the Adopt web site, so users can easily notice and find them.

**Comment by pshipton** [comment]
@DanHeidinga

**Comment by pshipton** [comment]
> I would like the milestone builds to be more prominent on the Adopt web site, so users can easily notice and find them.

I guess this is covered by https://github.com/AdoptOpenJDK/openjdk-website/issues/217 so this issue can be closed.
