### ISSUE TITLE
jdk8u192-b12 Windows x64 Build doesn't work on my Windows 10 Enterprise machine

### ISSUE THREAD

**Issue by datallah** [AdoptOpenJDK/openjdk-build#706]
When I try to run java.exe (or anything else that use the jvm), I run into the following error:
```
Error: loading: C:\Temp\jdk8u192-b12\jre\bin\server\jvm.dll
```
jdk8u181-b13 works on the same machine

I confirmed that the checksum of the downloaded zip file is correct.

The version of Windows 10 Enterprise is Version 1803 (OS Build 17134.376)

I have been able to successfully run the same binary on a Windows Server 2008r2 machine.

@karianna suggested that I report the bug.
Please let me know what other information I can provide to help debug this.

**Comment by karianna** [comment]
@datallah Can you test the binary at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/74/ please

**Comment by datallah** [comment]
> @datallah Can you test the binary at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/74/ please

That build works

**Comment by karianna** [comment]
resolved!
