### ISSUE TITLE
Don't use extended attributes for MacOS

### ISSUE THREAD

**Issue by slandelle** [AdoptOpenJDK/openjdk-build#712]
On MacOS, extracting from `OpenJDK8U-jdk_x64_mac_hotspot_8u192b12.tar.gz` generates a directory with extended attributes. As is, this directory can't be open in Finder and can't be accessed by eclipse (can't find compatible JRE in `Execution Environments`).
Workaround is to `xattr -c` on the directory.

**Comment by karianna** [comment]
This might be Mac OS X's automatic quarantine kicking in.  Will need to check the Apple code signing.  Can you tell us what the attribs are?

**Comment by slandelle** [comment]
Indeed

```
$ xattr jdk8u192-b12/
com.apple.FinderInfo
com.apple.quarantine
```

**Comment by gdams** [comment]
When you open the directory in finder what error do you get? Mine opens a terminal shell but that's expected behaviour.

**Comment by gdams** [comment]
ping @slandelle ?

**Comment by slandelle** [comment]
Sorry, I missed your previous message. The behavior I expect is to open and navigate in the directory, just like the Oracle distribution (that doesn’t have those attributes), not get a directory in quarantine.

**Comment by gdams** [comment]
This is a difficult one. We previously did  ship the tarball like this but when we started creating installers we had to switch to get the macOS layout.

**Comment by karianna** [comment]
> This is a difficult one. We previously did ship the tarball like this but when we started creating installers we had to switch to get the macOS layout.

It's actually more subtle than that.  When you sign a mac bundle correctly it gets past quarantine.

@slandelle Are you able to try one of our Mac installers?

**Comment by slandelle** [comment]
@karianna Indeed, the new installer now no longer generates a quarantined folder. Thanks a lot for your great work!

One small nit though: it's not very convenient that the folder is simply named adoptopenjdk-8, without at least the update version. When upgrading, I tend to keep previous update around for some times, so it's easier to rollback should a regression occur.
Do you want me to open a dedicated issue?

**Comment by gdams** [comment]
@slandelle we've had people argue both ways on this one. Some people want to overwrite and some people don't.

**Comment by gdams** [comment]
this is also how Oracle handle their installations: https://github.com/Homebrew/homebrew-cask-versions/blob/master/Casks/java-beta.rb#L9

**Comment by slandelle** [comment]
> this is also how Oracle handle their installations

But `version.before_comma` would be `12` and then `12.0.1` and then `12.0.2`, not always `12` like you have just `8` for all the updates.
