### ISSUE TITLE
OpenJ9 release jdk8u192-b13-0.11.0 misnamed

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#714]
Somebody created a second OpenJ9 release build jdk8u192-b13-0.11.0 on October 26.
This build is misnamed, as it is not jdk8u192-b13 but jdk8u192-b12

Also, to match the previous releases (0.8.0, 0.9.0), it should have the extension "_openj9-0.11.0" not "-0.11.0".

The difference from the previous release build is https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/159

**Comment by sxa555** [comment]
Yep that was me running a test and it took way longer than I expected to come out so I didn't handle it on Thursday. Going to delete it now which will revert it to the previous (non-suffixed) name then we can get another one out with the correct name

**Comment by sxa555** [comment]
Will close this since we still have https://github.com/AdoptOpenJDK/openjdk-build/issues/678 around which this was a test fix for.
