### ISSUE TITLE
Missing CA certificates in jdk8u192-b12 for OpenJ9 only (Hotspot build fixed by #676)

### ISSUE THREAD

**Issue by jamiekrug** [AdoptOpenJDK/openjdk-build#719]
I ran into this error, which should have been fixed by #676:

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

I downloaded the jdk8u192-b12 with OpenJDK 8 and the OpenJ9 JVM option, but the problem persisted. I tried downloading the jdk8u192-b12 build with the Hotspot JVM option, and the problem was resolved. The Hotspot version's cacerts file contains 92 entries, while the OpenJ9 version has only 80, so it seems #676 only resolved that issue with the Hotspot build, not OpenJ9.

**Comment by sxa555** [comment]
Thanks for the report :-)

PR https://github.com/AdoptOpenJDK/openjdk-build/pull/688/files is the PR that provided the HotSpot fix and was done on 24th October. The OpenJ9 8u192 build was created on 20th October so pre-dated the fix. I'm working on a full set of newer builds at the moment for 8u192/OpenJ9 for other reasons and these have the updated file. All platforms except Windows which I'm working on are already available as the primary download on the site now (Or directly via https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u192-b12_openj9-0.11.0)

**Comment by jamiekrug** [comment]
No problem. Sounds good. Thanks, @sxa555 .
