### ISSUE TITLE
Windows/JDK8/J9 production 0.11.0 builds currently failing

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#725]
Reason unclear but the resulting java execution is resulting in:

`The application has failed to startt because it's side-by-side configuration is incorrect. Please see the application event log or use the command line sxstrace.exe tool for more detail`

In the build log when trying to execute it we get:

```
Finished building OpenJDK for target 'images'
'/tmp/tmp.kJ76onEiGA/workspace/./build//src/build/windows-x86_64-normal-server-release/images/j2sdk-image' found
/cygdrive/c/Users/jenkins/workspace/SXA-jdk8_j9_win64_build/sbin/build.sh: line 353: /tmp/tmp.kJ76onEiGA/workspace/./build//src/build/windows-x86_64-normal-server-release/images/j2sdk-image/bin/java: Accessing a corrupted shared library
 Error executing 'java' does not exist in '/tmp/tmp.kJ76onEiGA/workspace/./build//src/build/windows-x86_64-normal-server-release/images/j2sdk-image'.
Relocating workspace from /tmp/tmp.kJ76onEiGA to /cygdrive/c/Users/jenkins/workspace/SXA-jdk8_j9_win64_build/workspace
Data at: /cygdrive/c/Users/jenkins/workspace/SXA-jdk8_j9_win64_build/workspace
```

**Comment by sxa555** [comment]
Related issues: https://github.com/AdoptOpenJDK/openjdk-build/issues/719 https://github.com/AdoptOpenJDK/openjdk-build/issues/690
Related PRs: https://github.com/AdoptOpenJDK/openjdk-build/pull/726
Doing test builds under https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk8_j9_win64_build/3/console for now

**Comment by sxa555** [comment]
Worked ok at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk8_j9_win64_build/3 with
```
TAG: jdk8u192-b12
configure_args: --with-milestone=fcs
BRANCH: openj9-0.11
```

**Comment by sxa555** [comment]
Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk8_j9_win64_build/4 with
```
TAG: jdk8u192-b12_openj9-0.11.0
configure_args: --with-milestone=fcs
BRANCH: openj9-0.11
```

**Comment by sxa555** [comment]
Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk8_j9_win64_build/5 with just ADDITIONAL_FILENAME_TAG set

**Comment by sxa555** [comment]
Testing at https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk8_j9_win64_build/6 with
```
TAG: jdk8u192-b12_openj9-0.11.0
configure_args:
BRANCH: openj9-0.11
```

**Comment by sxa555** [comment]
Testing at  https://ci.adoptopenjdk.net/view/work%20in%20progress/job/SXA-jdk8_j9_win64_build/9 with
```
TAG: 
configure_args: --with-milestone=fcs
BRANCH: openj9-0.11
ADDITIONAL_FILENAME_TAG: jdk8u192-b12_openj9-0.11.0
```

**Comment by sxa555** [comment]
Parameter has been added to expose `ADDITIONAL_FILENAME_TAG` which we will use for the production builds https://github.com/AdoptOpenJDK/openjdk-build/pull/732

**Comment by sxa555** [comment]
Re-opening as I'm still hitting issues:
```

configure: Found Microsoft Visual Studio 2010
configure: Rewriting VS_ENV_CMD to "/cygdrive/c/progra~2/micros~4.0/vc/bin/amd64/vcvars64.bat"
configure: Trying to extract Visual Studio environment variables
Setting environment for using Microsoft Visual Studio 2010 x64 tools.
configure: Setting extracted environment variables
/cygdrive/c/cygwin64/tmp/tmp.UD5miaHsOB/workspace/build/src/build/windows-x86_64-normal-server-release/vs-env/set-vs-env.sh: line 2: syntax error near unexpected token `('
/cygdrive/c/cygwin64/tmp/tmp.UD5miaHsOB/workspace/build/src/build/windows-x86_64-normal-server-release/vs-env/set-vs-env.sh: line 2: `VS_INCLUDE="c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE;c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\ATLMFC\INCLUDE;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include;C:\Program Files\Debugging Tools for Windows (x64)\sdk\inc; "'
configure exiting with result code 2
Relocating workspace from /tmp/tmp.UD5miaHsOB to /cygdrive/c/Users/jenkins/workspace/SXA-jdk8_j9_win64_build/workspace
Data at: /cygdrive/c/Users/jenkins/workspace/SXA-jdk8_j9_win64_build/workspace
total 8.0K
```
This appears to only be the case when the `TAG` variable is set, which we may not need any more now that we're using the `ADDITIONAL_FILE_NAME_TAG`

**Comment by sxa555** [comment]
11 was built with the `pre` branch of my openjdk-build repo. 14 will be built with what was hopefully the same as 9

**Comment by sxa555** [comment]
I think the variable issue with the `)` was down to having the jenkins agent started as the wrong user. Now passing that point running as jenkins

**Comment by sxa555** [comment]
Since we've shipped it I'm going with this now having finished successfully. Closing

**Comment by sxa555** [comment]
Still issues - currently the builds are producing filenames of `OpenJDK8U-jdk_x64_mac_openj9_jdk8u202-b08_openj9-0.12.0_8u202b08.tar.gz` when building with:
```
TAG: jdk8u202-b08
configure_args: 
BRANCH: openj9-0.12
ADDITIONAL_FILENAME_TAG: jdk8u202-b08_openj9-0.12.0
```

**Comment by M-Davies** [comment]
@sxa Can this be closed?

**Comment by sxa** [comment]
The build pipelines are now passing, so I'd say yes
