### ISSUE TITLE
Set up 32-bit ARM pipeline on Packet

### ISSUE THREAD

**Issue by vielmetti** [AdoptOpenJDK/openjdk-build#73]
See also #72  for 64-bit ARM on Packet.

- [x] Wait for 32-bit server availability

**Comment by karianna** [comment]
Do they even support 32-bit ARM?

**Comment by gdams** [comment]
we are able to build 32-bit ARM using https://ci.adoptopenjdk.net/computer/build-scaleaway-armv7-centos7/. It's just a very slow machine so a more powerful machine would be great

**Comment by karianna** [comment]
Opened https://github.com/AdoptOpenJDK/openjdk-build/issues/78 for the better build.
