### ISSUE TITLE
--with-milestone=fcs not valid for JDK11

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#742]
All JDK11 build logs currently have:
```
configure: WARNING: Option --with-milestone is deprecated and will be ignored.
```
Should probably be removed for JDK11 from https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L134 (Use is in https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/common/autoconf/spec.gmk.in#L179)

Based on the [openj9 release document](https://github.com/eclipse/openj9/blob/master/doc/processes/release_process.md), the `--without-version-pre --without-version-opt` options may serve a similar purpose.

**Comment by beckje01** [comment]
This looks like it was done via #917 @gdams can this be closed?
