### ISSUE TITLE
More accurately identify macOS builds in Info.plist

### ISSUE THREAD

**Issue by breun** [AdoptOpenJDK/openjdk-build#745]
I think it might be a good idea to use more precise descriptions in `Contents/Info.plist` for the macOS builds that show AdoptOpenJDK and indicate the included JVM (HotSpot/OpenJ9).

Currently I see this on my machine:

```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    11.0.1, x86_64:    "OpenJDK 11.0.1"    /Library/Java/JavaVirtualMachines/openjdk11-openj9/Contents/Home
    11.0.1, x86_64:    "OpenJDK 11.0.1"    /Library/Java/JavaVirtualMachines/openjdk11/Contents/Home
    1.8.0_192, x86_64:    "OpenJDK 8"    /Library/Java/JavaVirtualMachines/openjdk8/Contents/Home

/Library/Java/JavaVirtualMachines/openjdk11-openj9/Contents/Home
```

Currently both the HotSpot and OpenJ9-based OpenJDK 11.0.1 builds from AdoptOpenJDK show up with the same description.

I think output like this would be more helpful:

```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    11.0.1, x86_64:    "AdoptOpenJDK HotSpot 11.0.1"    /Library/Java/JavaVirtualMachines/openjdk11-openj9/Contents/Home
    11.0.1, x86_64:    "AdoptOpenJDK OpenJ9 11.0.1"    /Library/Java/JavaVirtualMachines/openjdk11/Contents/Home
    1.8.0_192, x86_64:    "AdoptOpenJDK HotSpot 8u192"    /Library/Java/JavaVirtualMachines/openjdk8/Contents/Home

/Library/Java/JavaVirtualMachines/openjdk11-openj9/Contents/Home
```

I'm not exactly what the semantics of all fields in `Contents/Info.plist` are, and therefor I also don't know if it makes sense to repeat the version in this description.

**Comment by gdams** [comment]
We are currently overriding this in the brew casks. We should probably do this as part of the build. FYI https://github.com/AdoptOpenJDK/homebrew-openjdk/blob/master/Casks/adoptopenjdk10.rb#L24-L42

**Comment by gdams** [comment]
@johnoliver this is what I was talking about yesterday. Once we can accurately pull the metadata from nightlies then we should be able to do this.

**Comment by gdams** [comment]
this work is complete. Here is my output for confirmation:

```
/usr/libexec/java_home -V%                                                      ➜  ~ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    11.0.5, x86_64:	"AdoptOpenJDK (OpenJ9, JRE) 11"	/Library/Java/JavaVirtualMachines/adoptopenjdk-11-openj9.jre/Contents/Home
    11.0.4, x86_64:	"AdoptOpenJDK 11"	/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
    1.8.0_222, x86_64:	"AdoptOpenJDK 8"	/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Ho
```
