### ISSUE TITLE
Linux/PPCLE+AARCH64 missing libfreetype

### ISSUE THREAD

**Issue by a-roberts** [AdoptOpenJDK/openjdk-build#754]
I want to switch from openjdk 8 to the adoptopenjdk binaries, specifically https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9/tags/ and ppc64le-ubuntu-jdk8u192-b12, for Jenkins performance.

I have an existing openjdk 8 based image and it performs terribly slow on my Power LE ICP 3.1 stack. 

So slow that my readiness probes (the ones by default in the real Jenkins chart) fails repeatedly. I know a bit about Java performance and this project... and when I created the build scripts last year, in the configure stage I pulled in a libfreetype binary. 

I see changes have been made since, and now in my Docker image I don't see libfreetype at all at the place I expected it. 

As such, Jenkins isn't starting.

```
adams-mbp:microclimate-devops aroberts$ k logs microclimate-jenkins-5f54c6b5-knhv8 | grep freetype
hudson.util.AWTProblem: java.lang.UnsatisfiedLinkError: fontmanager (libfreetype.so.6: cannot open shared object file: No such file or directory)
Caused by: java.lang.UnsatisfiedLinkError: fontmanager (libfreetype.so.6: cannot open shared object file: No such file or directory)
```

```
root@microclimate-jenkins-5f54c6b5-knhv8:/opt/java# find . | grep libfreetype
root@microclimate-jenkins-5f54c6b5-knhv8:/opt/java#
```

it's not in the image (and nothing like it under jre/lib/ppc64, which I thought would be named ppc64le...).

My Jenkins container is at adamroberts/test-jenkins-mc-ppc64le-adopt:latest.

@dinogun 

It's not in jdk8u192-b12_openj9-0.11.0 (so the tarball) which I just downloaded for Power either. Is there on x86-64...

**Comment by sxa555** [comment]
@a-roberts Build seems to have completed without issues and tarball has the freetype lib in it - can you grab it and check if it looks ok for you?

**Comment by a-roberts** [comment]
@sxa555 thanks, confirmed it's in your tarball and looks ok 👍
