### ISSUE TITLE
Get num processors as opposed to hard coding for ARM (and maybe other builds)

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#76]
`export CONFIGURE_ARGS_FOR_ANY_PLATFORM=${CONFIGURE_ARGS_FOR_ANY_PLATFORM:-"--with-jobs=4"` is hardcoded to 4...

**Comment by neomatrix369** [comment]
Hmm not a bug @karianna, more a tech debt, we can always override `CONFIGURE_ARGS_FOR_ANY_PLATFORM` by passing in a new sting `--with-cores=10`
