### ISSUE TITLE
Missing checksums for 11.0.1+13 builds

### ISSUE THREAD

**Issue by io7m** [AdoptOpenJDK/openjdk-build#766]
Hello!

The following checksum files are missing (GitHub gives 404 errors):

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jdk_ppc64_aix_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jdk_ppc64le_linux_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jdk_s390x_linux_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jdk_x64_linux_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jdk_x64_linux_openj9_linuxXL_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jdk_x64_mac_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jdk_x64_windows_openj9_11.0.1_13.zip.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jre_ppc64_aix_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jre_ppc64le_linux_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jre_x64_linux_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jre_x64_linux_openj9_linuxXL_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jre_x64_mac_openj9_11.0.1_13.tar.gz.sha256.txt
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11-jre_x64_windows_openj9_11.0.1_13.zip.sha256.txt

These are all taken from the current `releases.json` file in the [openjdk11-binaries](https://github.com/AdoptOpenJDK/openjdk11-binaries) repos.

**Comment by karianna** [comment]
@sxa555 One for you I think

**Comment by sxa555** [comment]
@io7m The 11.0.1+13 build was rebuilt and re-released and the older files were removed - those SHA files were from the old release and have therefore gone to avoid confusion (although I still have a backup of them all!) . The release now has updated files and corresponding SHA sum files are present. Had you stored a direct link to the old ones?

https://adoptopenjdk.net/archive.html?variant=openjdk11&jvmVariant=openj9 has all the current release of 11.0.1+13 available.

**Comment by io7m** [comment]
> The release now has updated files and corresponding SHA sum files are present.

Are you sure? The current `releases.json` file is actually completely empty...

https://github.com/AdoptOpenJDK/openjdk11-binaries/blob/master/releases.json

For that file, I just see `[]`.

> Had you stored a direct link to the old ones?

Nope. I `GET` https://raw.githubusercontent.com/AdoptOpenJDK/openjdk11-binaries/master/releases.json and then parse the results each time. Is it possible that GitHub is doing some sort of caching?

**Comment by karianna** [comment]
I'm pretty sure that `releases.json` file is no longer used.

**Comment by io7m** [comment]
Er... If the `releases.json` file isn't used, how am I expected to get a list of releases from the git repository? From where is the API sourcing release data?

**Comment by karianna** [comment]
I believe the API is sourcing directly from the GitHub API.  So you should use openjdk-api v2.

**Comment by io7m** [comment]
The problem is that the v2 API doesn't provide sufficient metadata, and it also means I'm going through another layer of indirection when it comes to bug fixes and updates. I don't mean to be disparage anyone, but I waited over eight months for what should have been a simple bug fix on the v1 API. I would rather grab the data directly from source myself and cut out all of the middlemen. If I need to go via the GitHub API, I'll do that.

**Comment by sxa555** [comment]
If you really want to bypass the AdoptOpenJDK API you can get the info from e.g. https://api.github.com/repos/adoptopenjdk/openjdk11-binaries/releases

Further details on their APi is at https://developer.github.com/v3/repos/releases/

@karianna We should probably do something with that file to indicate to anyone browsing it that it's now obsolete

**Comment by io7m** [comment]
> What extra info was it you were looking for on that API? I haven't been involved in the development of that so haven't been monitoring API issues too closely myself

Primarily these:

https://github.com/AdoptOpenJDK/openjdk-api/issues/75
https://github.com/AdoptOpenJDK/openjdk-api/issues/118

But to be honest, I'd rather just get hold of the raw data myself and do all of the interpretation/filtering/searching locally rather than go through another layer of JSON and Javascript. That way I can get the exact semantics I want. Going through "someone else's Javascript" means that I'm subject to issues such as:

https://github.com/AdoptOpenJDK/openjdk-api/issues/112
https://github.com/AdoptOpenJDK/openjdk-api/issues/113

And of course the original (unsolved) issue that basically killed the Java v1 API:

https://github.com/AdoptOpenJDK/openjdk-api/issues/48

I understand that the current JS API is geared towards serving the website. The code I'm writing, however, has more in common with a traditional package manager like `apt` and so I'm happy to bulk-download large blobs of data and do everything locally. An intermediate API is more of a hindrance than a help. :slightly_smiling_face:

**Comment by sxa555** [comment]
I understand, although bear in mind there are other package management tools out there and I'd generally prefer them to use our API since if we ever move away from storing releases in github to our own servers then such tools will keep working :-)

**Comment by io7m** [comment]
The original `releases.json` file... Where was that file coming from? It looked to be a straightforward dump of the GitHub API data.

**Comment by gdams** [comment]
@io7m it was a dump of the GitHub API. Does this need to be open still or can I close it now?

**Comment by io7m** [comment]
I think you can close this now.
