### ISSUE TITLE
Provide a OpenJDK 10 Mac build with the correct layout for completeness

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#769]
See https://github.com/AdoptOpenJDK/homebrew-openjdk/pull/46

**Comment by gdams** [comment]
I'm going to try and kick off a build today

**Comment by gdams** [comment]
closing https://github.com/AdoptOpenJDK/openjdk10-binaries/releases/tag/jdk-10.0.2%2B13
