### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION and SIGSEGV with 11.0.1+13

### ISSUE THREAD

**Issue by Horcrux7** [AdoptOpenJDK/openjdk-build#776]
We have a crash in our test system on Linux and Windows on the same code position. Attached are crash dumps for both platforms.
[hs_err_pid590.log](https://github.com/AdoptOpenJDK/openjdk-build/files/2628221/hs_err_pid590.log)
[hs_err_pid11476.log](https://github.com/AdoptOpenJDK/openjdk-build/files/2628223/hs_err_pid11476.log)

The crash is reproducible on our docker based test system of every run of this test.

**Comment by karianna** [comment]
@Horcrux7 And do you get the same crash if you run the Oracle OpenJDK build from jdk.java.net?  I'm trying to identify if this is an issue with our build process or an OpenJDK upstream bug.

**Comment by Horcrux7** [comment]
The tests ran before with Oracle JDK 8, which work. Currently we switch to JDK 11 and switch the JDK vendor because known reasons.

I will try to run the test with Oracle JDK 11 and post the result here.

Currently it is confusing where bug reports should be published. In the crash, this site is suggested.

**Comment by Horcrux7** [comment]
Yes, it crash also with the Oracle JDK: `JRE version: OpenJDK Runtime Environment (11.0.1+13) (build 11.0.1+13)`

**Comment by karianna** [comment]
@Horcrux7 Thank you for testing!  That confirms the bug report should be passed upstream (we triage her first).

The place to report this is In the HotSpot group at OpenJDK --> https://mail.openjdk.java.net/mailman/listinfo/hotspot-dev 

You can send them your original bug report and the 2 hs files (OpenJDK mailing lists sadly do not support attachments, so I recommend hosting them on Pastebin).  You can mention that this happens on an Adopt build and the Oracle build which should make it clear to them that it's likely an issue at the source.

If you have any troubles with all of this let me know and I'll help!

**Comment by karianna** [comment]
> If I understand https://mail.openjdk.java.net/pipermail/hotspot-dev/2019-January/036015.html well, posting to hotspot-dev is not the right way to report bug like this. Just in case somebody (like me) would want to use this report as a pattern for another report.

Correct, going forwards we will be triaging here and we now have a JBS team who can open bugs directly.
