### ISSUE TITLE
Exception in thread "Swing-Shell" java.lang.InternalError: Could not initialize COM: HRESULT=0x80010106 

### ISSUE THREAD

**Issue by shannah** [AdoptOpenJDK/openjdk-build#778]
**Platform:**
Windows 10

**Architecture:**
x64

opening JFileChooser deadlocks the Swing EDT and freezes the application, drag-n-drop not working, etc. 

This bug https://bugs.openjdk.java.net/browse/JDK-8189938 is present in the jdk-11.0.1+13 Win64 builds in OpenJDK.  It is not present in the jdk-11.0.1 win64 builds on https://jdk.java.net/11/

The fix:

> This problem should go away once JDK updates the official build compiler from Visual Studio 2013 SP4 to VS2017 for jdk11 to be released this September. 

So it looks like the toolchain for building AdoptOpenJDk builds needs to be updated.

**Comment by karianna** [comment]
So basiucally use Visual Studio 2017 toolchain for our 11u build.  I think that's now the case.  But we can check.

**Comment by M-Davies** [comment]
@shannah @karianna We are [currently using Toolchain 2017](https://github.com/AdoptOpenJDK/openjdk-build/blob/2041d51db738b741f2a630bc803ca1f038ef62b2/build-farm/platform-specific-configurations/windows.sh#L172) for our x-Windows JDK11+ builds. Can this be closed?

**Comment by karianna** [comment]
> @shannah @karianna We are [now using Toolchain 2017](https://github.com/AdoptOpenJDK/openjdk-build/blob/2041d51db738b741f2a630bc803ca1f038ef62b2/build-farm/platform-specific-configurations/windows.sh#L172) for our x-Windows JDK11+ builds. Can this be closed?

Yes.
