### ISSUE TITLE
JDK 11 ZGC needed.

### ISSUE THREAD

**Issue by netroby** [AdoptOpenJDK/openjdk-build#782]
JDK 11 ZGC needed.
The current build not ship with ZGC , please enable it . thanks

**Comment by netroby** [comment]
ping @karianna would you  please provided us ZGC?
I read the source code of JDK 11, seems zgc include in the source code, but adoptopenjdk not built with zgc

**Comment by karianna** [comment]
We're currently triaging our build issues and will put everything into milestones, realistically we're unlikely to do this one until Jan 2019 unless another volunteer picks it up.

**Comment by gyakovlev** [comment]
looks like jdk 11.0.3+ builds will enable it by default according to this page
https://wiki.openjdk.java.net/display/zgc/Main

> If you are building early versions of JDK 11 (versions 11.0.0, 11.0.1 or 11.0.2), you need to supply the configure option `--with-jvm-features=zgc` to enable building of ZGC. This option is no longer needed (ZGC is built by default) as of JDK 11.0.3 and JDK 12.

**Comment by jerboaa** [comment]
```
$ ./jdk-11.0.3+7/bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```

This is fixed in the build from:

https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.3%2B7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.3_7.tar.gz

**Comment by netroby** [comment]
Thanks a  lot ,great works
