### ISSUE TITLE
openjdk-jdk mirror is out of date

### ISSUE THREAD

**Issue by dougxc** [AdoptOpenJDK/openjdk-build#786]
I find this mirror of http://hg.openjdk.java.net/jdk/jdk very useful for searching and linking to JDK code. However, it seems like the mirror was last updated Sept 3rd. Is that just some issue in the mirroring process?

**Comment by karianna** [comment]
Yes, it's a git-hg bug for sure

**Comment by gdams** [comment]
this is resolved, last update in the repo was 12 hours ago https://github.com/adoptopenjdk/openjdk-jdk
