### ISSUE TITLE
Add jdk8u202-b01

### ISSUE THREAD

**Issue by don-vip** [AdoptOpenJDK/openjdk-build#787]
**Platform:**
All
**Architecture:**
All

Can you please build `jdk8u202-b01`? It contains fix for https://github.com/AdoptOpenJDK/openjdk-build/issues/476 / https://github.com/AdoptOpenJDK/openjdk8-releases/issues/9

**Comment by gdams** [comment]
we've just shipped jdk8u202-b08

**Comment by don-vip** [comment]
Thank you, I confirm #476 is fixed !
