### ISSUE TITLE
job openjdk11_j9_openjdktest_x86-64_linux_largeHeap was not triggered by upstream project 

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#790]
Job openjdk11_j9_openjdktest_x86-64_linux_largeHeap is not triggered by upstream project . Job openjdk11_j9_openjdktest_x86-64_linux are triggered twice per upstream project. 

Details 
https://github.com/AdoptOpenJDK/openjdk-tests/issues/724

**Comment by llxia** [comment]
Test job [openjdk11_j9_openjdktest_x86-64_linux](https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_linux/) is triggered by both compressedrefs and non-compressedrefs JDK upstream build: 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9-linuxXL/

**Comment by sophia-guo** [comment]
Same to systemtest: [openjdk11_j9_systemtest_x86-64_linux](https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_linux/198/) , which is triggered twice by upstream jobs Started by upstream project jdk11u-linux-x64-openj9-linux and large heap jdk11u-linux-x64-openj9-linuxXL.

**Comment by smlambert** [comment]
Raising importance of this bug, as its effectively blocking proper testing of XL builds.
