### ISSUE TITLE
RELEASE_TAG is not passed to test pipeline

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#791]
According to console output RELEASE_TAG is not passed to test pipeline. 
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_hs_openjdktest_x86-64_linux/91/consoleFull

Suspect that should use value of  releaseTag instead of TAG in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/openjdk_build_pipeline.groovy#L83  ?

**Comment by sophia-guo** [comment]
@karianna

**Comment by karianna** [comment]
@sophia-guo That's correct, we were only setting that for release jobs.  It seems the wrong naming convention to set that value for nightly builds.  If tag/value is required then maybe it needs to be renamed as something like `testVersion`?  Maybe there's a better name?

**Comment by sophia-guo** [comment]
@karianna  I think releaseTag is fine. I've opened an issue in https://github.com/AdoptOpenJDK/openjdk-tests/issues/739, will close this one.
