### ISSUE TITLE
JRE distribution for commercial use

### ISSUE THREAD

**Issue by GitHubHans1** [AdoptOpenJDK/openjdk-build#792]
Hello,
We are planning to distribute the JRE from AdoptOpenJDK (OpenJDK 8, Hotspot, Windows x32) with a commercial purpose.
In our understanding, this scenario should be license-compliant, since it is based on the GPL2withClasspathexception license.
However, we found the file named "THIRD_PARTY_README" in the downloaded zip file. In this file, however, many more licenses are listed. Now we ask ourselves whether these license terms are relevant for our scenario?

**Comment by karianna** [comment]
It's GPLv2+CE so you're safe to use it as you describe.

**Comment by GitHubHans1** [comment]
Hi karianna,

Thank you very much for your quick answer.
We still don't know what relevance this file has. However, your answer strengthens us in our approach.
