### ISSUE TITLE
Higher memory consumption with AdoptOpenJDK

### ISSUE THREAD

**Issue by GitHubHans1** [AdoptOpenJDK/openjdk-build#793]
Hello,
We are currently planning to switch our product from Oracle JRE to AdoptOpenJDK. Here we use the following variants:
Oracle JRE: Version 8u192, Windows x32
AdoptOpenJDK JRE: Version 8u192, Hotspot, Windows x32

If we analyze the memory consumption and the performance of the main use case in our product with these two runtimes, we get the following values:
Oracle JRE: 
- Performance: 47 seconds
- Memory: 195 MB
AdoptOpenJDK JRE:
- Performance: 38 seconds
- Memory: 520 MB

We then looked at the possible starting parameters of the two JREs. Here we found the switch "-Xincgc" (activating incremental garbage collection) at the Oracle JRE. If we activate this switch, we get the same performance and the same memory consumption as with AdoptOpenJDK. However, we could not find this switch in the JRE of AdoptOpenJDK.

In our scenario, performance is important, but memory consumption is more important. Therefore we would like to ask if there is a setting possibility of the AdoptOpenJDK JRE, with which it behaves like the Oracle JRE?

**Comment by karianna** [comment]
@GitHubHans1 The `-Xincgc` should work for the AdoptOpenJDK JRE - what occurs if you use that?

**Comment by GitHubHans1** [comment]
Hi karianna,

Thank you very much for your quick answer.
In the meantime we have done further tests with various parameters.
Unfortunately, if we use this switch, the memory consumption will increase even further.

Can you help us to get memory consumption to a level similar to Oracle JRE?

**Comment by karianna** [comment]
Can you run `-XX:+PrintFlagsFinal` for both the Oracle JDK and the AdoptOpenJDK and attach them here?

**Comment by GitHubHans1** [comment]
[OracleJDK8_AllFlags.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/2694943/OracleJDK8_AllFlags.txt)
[OpenJDK8_AllFlags.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/2694944/OpenJDK8_AllFlags.txt)

Thank you very much for your fast answer.

Attached you will find the Flags.

**Comment by kthaya** [comment]
Hi @karianna 
I'm also seeing higher memory consumption in Ubuntu OS with 8u192. I can pass more information if you want. Is this known issue? (I'm trying to understand "Waiting on OP" means). Thanks

**Comment by tmancill** [comment]
Possibly related to this thread...  We're starting to dig into differences in memory consumption between the Alpine Linux package of 8u222 (which is linked against musl) and AdoptOpenJDK running on the same Alpine base.  Based on our testing so far, AdoptOpenJDK does use more memory for the same code.

A co-worker pointed out that **musl** is optimized to reduce memory footprint whereas **glibc** is optimized for CPU utilization.  We're not seeing the same delta reported by @GitHubHans1 , but the fact that the AdoptOpenJDK test had higher performance matches that.

I'd also be interested to hear if anyone has seen increased memory usage on applications that run large numbers of threads.  https://wiki.musl-libc.org/functional-differences-from-glibc.html documents a different default thread stack size when using musl.

**Comment by kthaya** [comment]
Thanks @tmancill ,
Our application has large number of threads and we relatively see more memory usage with 8u212 (compared with same version of oracle JDK).
I have analyzed few heap dumps using MAT and I can see sun.security.ssl.SSLSocketImpl doesn't garbage collected (or takes very long time to GC) compare to oracle JDK. I think it is because of finalize() method in sun.security.ssl.BaseSSLSocketImpl (but I assume both AdoptOpenJDK and Oracle JDK has same implementation for this class). This is still puzzle for me to understand why oracle JDK can do GC faster than AdoptOpenJDK?
Our application heavily use SSLSocketImpl. Any thoughts on this please?

**Comment by karianna** [comment]
I finally got around diff the two text files, it's pretty clear that the Oracle GC settings are different from what you're getting from OpenJDK.  You'll need to set your GC settings explicitly

**Comment by GitHubHans1** [comment]
Thank you very much for analyzing the two text files. Could you please name the relevant settings that make the difference?

**Comment by nE0sIghT** [comment]
@GitHubHans1 

Just sort and diff. This is one minute task

**Comment by iamakashk** [comment]
@GitHubHans1  
Were you managed to resolve this issue ? I am getting somewhat similar issue with my microservice.
