### ISSUE TITLE
Nightly JDK11U builds are not being published...?

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#794]
There have been no nightly jdk11u builds published for 2 days here: https://adoptopenjdk.net/nightly.html?variant=openjdk11&jvmVariant=openj9

**Comment by sxa555** [comment]
Not specific to OpenJ9 - also true for HotSpot/JDK11, but not JDK8

**Comment by sxa555** [comment]
I think this may be a side effect of https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/612 as some of the arm jobs were blocked. Will get things freed up ...

**Comment by sxa555** [comment]
Killed the following which were stuck at `Cannot contact build-scaleway-armv7-ubuntu16-04-[12]: java.lang.InterruptedException`
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-arm-hotspot/9/
- https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-arm-hotspot/12/
Machines had fallen over for the second time in the last few days - possibly a result of extra testing being enabled on the platform - and this seems to have stopped the flows from completing and the publish job not being triggered.

Machines now recovered and will keep an eye on them. The jobs from the 3rd onwards are still in progress - the one from the 3rd has just published (dated the 6th on the nightly pages) and the others will likely follow in due course later today

**Comment by sxa555** [comment]
Seems to have now caught up - closing
