### ISSUE TITLE
Handle Leak on Windows - OpenJDK 10, 11

### ISSUE THREAD

**Issue by jeffgeek2018** [AdoptOpenJDK/openjdk-build#798]
**Platform: ** Windows 64 bit

**Architecture:** Intel

I have a multi-threaded long running Java application. This works fine with Oracle JRE 1.8. However, when i use OpenJDK 10.0.2 or 11.0.1+13, i see the number of handles used by the Java process constantly growing (100 handles every 5 mins). My application creates a number of short lived threads as it performs its tasks.

When i check with the Microsoft "handle" tool from SysInternals, i see that handles of type "File" are increasing continuously. 

Any help with this is much appreciated. 

Regards,

Jeff

**Comment by karianna** [comment]
@jeffgeek2018 Can you try with an OpenJDK build by Azul or Amazon as well?  I'm trying to figure out if this is an upstream issue.

**Comment by jeffgeek2018** [comment]
Yes, will check and report. I had tried the download from https://openjdk.java.net/ and that has the same issue as well.

**Comment by jeffgeek2018** [comment]
Tested with Azul. Same issue.

**Comment by jeffgeek2018** [comment]
[test.zip](https://github.com/AdoptOpenJDK/openjdk-build/files/2670695/test.zip)

Here is the code that i am having an issue with.  Run this code and check handle leaks in Windows task manager.

**Comment by jeffgeek2018** [comment]
![handles_used](https://user-images.githubusercontent.com/45798507/49860003-e7da5e80-fdc6-11e8-966b-3ba7880c1513.png)
Comparison of handles used with JDK 1.8 and 10.0.2 for the same test program. JDK 1.8 seems to reclaim the handles, whereas JDK 10 does not.

**Comment by karianna** [comment]
OK this needs to be reported upstream then - you'll want to report it at the jdk-dev list:  https://mail.openjdk.java.net/mailman/listinfo/jdk-dev - you can point them to this issue if they need to see the screenshot etc.
