### ISSUE TITLE
How to make an openjdk to an jre?

### ISSUE THREAD

**Issue by XenoAmess** [AdoptOpenJDK/openjdk-build#801]
I downloaded your jdk11 x64 version here.
https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot
Really thanks.
But I wanna know if there be some way to make it an jre, in order to reduce the size.
In short, what files can I safely delete without affecting the JVM's functions for users?

**Comment by karianna** [comment]
See #792
