### ISSUE TITLE
docker adoptopenjdk/openjdk11-openj9 latest sets obsolete JAVA_VERSION

### ISSUE THREAD

**Issue by pshipton** [AdoptOpenJDK/openjdk-build#805]
The "latest" docker file contains `ENV JAVA_VERSION jdk-11+28` however this is the GA release. The last and current "latest" release is jdk-11.0.1+13 and the next release in Jan will be jdk-11.0.2+ something.

**Comment by pshipton** [comment]
@dinogun

**Comment by B0BAI** [comment]
Setting the `Environment` dynamically too (as an argument) will be great.

**Comment by pshipton** [comment]
Moving this to https://github.com/AdoptOpenJDK/openjdk-docker/issues/94
