### ISSUE TITLE
HotSpot error on 11.0.1+13, libjvm.dylib

### ISSUE THREAD

**Issue by neilstevenson** [AdoptOpenJDK/openjdk-build#814]
I get a HotSpot error consistenly on Mac with

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000104853d23, pid=23222, tid=953467
#
# JRE version: OpenJDK Runtime Environment (11.0.1+13) (build 11.0.1+13)
# Java VM: OpenJDK 64-Bit Server VM (11.0.1+13, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# V  [libjvm.dylib+0x20dd23]  ClassLoaderData::loader_name_and_id() const+0x7
#
```

Occurs on iOS 10.14.2, on i386 i5, not managed to make it recur on other hardware yet.

See https://github.com/hazelcast/hazelcast/issues/14319

Steps to recreate
```
git clone https://github.com/hazelcast/hazelcast.git
cd hazelcast
mvn -Dtest=com.hazelcast.internal.usercodedeployment.impl.filter.UserCodeDeploymentBasicTest test
```
(Maven 3.6.0)

**Comment by karianna** [comment]
Hi Neil, thanks for sending this in.  Does that same issue occur with Azul's Zulu? Trying to ascertain if this is an upstream issue.

**Comment by tezc** [comment]
@karianna yes, it occurs with Zulu as well.

**Comment by karianna** [comment]
@neilstevenson Can you report this upstream at OpenJDK in that case? The correct mailing list is probably hotspot-dev.
