### ISSUE TITLE
OpenJDK 11 JDK Builds Have Inconsistent Root

### ISSUE THREAD

**Issue by nebhale** [AdoptOpenJDK/openjdk-build#815]
**Platform:**
Linux (at least)

**Architecture:**
x64 (at least)

Currently, the tarball containing JDK 11 (both Hotspot and OpenJ9) are rooted at a different directory than the JRE 11 and JRE/JDK 8 tarballs:

```shell
$: tar tf OpenJDK8U-jre_x64_linux_hotspot_8u192b12.tar.gz  | sort | head -n 2
./jdk8u192-b12-jre/
./jdk8u192-b12-jre/ASSEMBLY_EXCEPTION

$: tar tf OpenJDK8U-jdk_x64_linux_hotspot_8u192b12.tar.gz | sort | head -n 2
./jdk8u192-b12/
./jdk8u192-b12/ASSEMBLY_EXCEPTION

$: tar tf OpenJDK11-jre_x64_linux_hotspot_11_28.tar.gz  | sort | head -n 2
./jdk-11+28-jre/
./jdk-11+28-jre/bin/

$: tar tf OpenJDK11U-jdk_x64_linux_hotspot_11.0.1_13.tar.gz  | sort | head -n 2
jdk-11.0.1+13/
jdk-11.0.1+13/bin/
```

Note that most of the archives have two levels (e.g. `.` and `jdk8u192-b12-jre`) where JDK 11 has only one level (e.g. `jdk-11.0.1+13`).  This makes handling all AdoptOpenJDK archives consistently impossible and an exception case needs to be written for this one binary.

The JDK 11 build should produce an artifact consistent with the rest.  While the most obvious change would be to move JDK 11's directory structure down one, I'd actually prefer moving the rest up a level.  It's not a strong preference though, so I'd much rather have _any_ consistency.

**Comment by karianna** [comment]
@johnoliver can you comment on this?  IIRC we changed the layout recently on purpose and so I *think* the 11.0.1+13 case should be canonical going forwards.

**Comment by tkrzeminski** [comment]
Same for me, this makes automated deployment a bit tricky.

**Comment by johnoliver** [comment]
Looking at the latest builds they all look consistent

**Comment by nebhale** [comment]
If you’re up for it, I’d like to wait for a round of OpenJ9 builds to be generated as well just to double check consistency there.  If everything matches up, then I thin we can close out the issue.

**Comment by karianna** [comment]
> If you’re up for it, I’d like to wait for a round of OpenJ9 builds to be generated as well just to double check consistency there. If everything matches up, then I think we can close out the issue.

Sounds good!

**Comment by nebhale** [comment]
Verified OpenJ9 Java 8 and 11 are consistent as well.  Feel free to close as complete.
