### ISSUE TITLE
Fix Jenkins setup for jcov tests

### ISSUE THREAD

**Issue by stooke** [AdoptOpenJDK/openjdk-build#823]
The jcov tests keep failing [1] (note especially the "override ignored" lines), because the Jenkins script downloads and specifies ASM-6.0 [2].
However, this commit [3] in OpenJDK modifies jcov to require ASM 7.0:
The fix is to change the Jenkins script to specify ASM-7.0 as appropriate.

[1] https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jcov/144/console
[2] https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jcov/configure
[3] http://hg.openjdk.java.net/code-tools/jcov/rev/18b0a143e1c2

(moved from https://github.com/AdoptOpenJDK/openjdk-tests/issues/779 )

**Comment by smlambert** [comment]
@stooke - the script that is used for the jcov build can be found here: https://github.com/smlambert/openjdk-build/blob/jcov/sbin/jcov.sh

I have not had time to look at what needs to change, if you have guidance (which asm7 files map to existing asm6 ones?), I can update it.

**Comment by smlambert** [comment]
@sophia-guo - you asked about this...

I may have time later in the week.  I am not sure if we have all of the asm7 files we need in the asmtools job or not: https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/lastSuccessfulBuild/artifact/

**Comment by sophia-guo** [comment]
Jtreg tests are actually using asm6, which may cause some tests failures. Functional tests updated with both asm6 and 7 available and test itself sets required asm version.

I've updated the job configuration and looks good https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jcov/, which also triggered a new build of jtreg https://ci.adoptopenjdk.net/job/jtreg/. Will wait and see if everything is good.

**Comment by sophia-guo** [comment]
[asmtools job](https://ci.adoptopenjdk.net/view/Dependencies/job/asmtools/lastSuccessfulBuild/artifact/) directly build from http://hg.openjdk.java.net/code-tools/asmtools, which defines the build process and includes all source codes. If the build is green it should be good. @smlambert

**Comment by smlambert** [comment]
Thanks for fixing this @sophia-guo !  Yesterday's jcov build looks good. 
https://ci.adoptopenjdk.net/view/Build%20Monitor/job/jcov/151/

I will close this issue now.
