### ISSUE TITLE
Create openjdk8-openj9 0.12 milestone 2 builds

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#832]
eclipse/openj9 have created a milestone branch which includes the features targeted for the Jan 2019 0.12 openj9 release to be incorporated into the Jan 2019 quarterly update.
This issue is to create a build from that branch to provide users with early access to a jdk8 which will be close in content to the actual quarterly release.

Links to nightly builds:
win_x86-32: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-01-15-07-42/OpenJDK8U-jdk_x86-32_windows_openj9_2019-01-15-07-42.zip
win_x86-64: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-01-15-07-42/OpenJDK8U-jdk_x64_windows_openj9_2019-01-15-07-42.zip
linux_x86-64LH: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-01-15-07-42/OpenJDK8U-jdk_x64_linux_openj9_linuxXL_2019-01-15-07-42.tar.gz
linux_x86-64: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-01-15-07-42/OpenJDK8U-jdk_x64_linux_openj9_2019-01-15-07-42.tar.gz
linux_390-64: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-01-15-07-42/OpenJDK8U-jdk_s390x_linux_openj9_2019-01-15-07-42.tar.gz
linux_ppc-64: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-01-15-07-42/OpenJDK8U-jdk_ppc64le_linux_openj9_2019-01-15-07-42.tar.gz

**Comment by lumpfish** [comment]
Pipeline kicked off to build the openj9-openjdk-jdk8 repository openj9-0.12 branch which fetches the required eclipse/openj9 0.12-m2 branch.

Pipeline job:
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/159/

win_x86-32:
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x86-32-openj9/95/consoleFull
openjdk tests (non executed): https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-32_windows/109/console

win_x86-64:
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-openj9/225/console
openjdk tests (runs only math): https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/385/

aix_ppc-64:
Build (fails): https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-aix-ppc64-openj9/179/console

linux_x86-64LH
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9-linuxXL/168/console
openjdk tests (fail due to -Xcompressedrefs): https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-64_linux/415/console
system tests (fail due to -Xcompressedrefs): https://ci.adoptopenjdk.net/job/openjdk8_j9_systemtest_x86-64_linux/407/console

osx_x86-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-openj9/110/console
openjdk tests: https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-64_macos/71/console
system tests (did not build - odd output): https://ci.adoptopenjdk.net/job/openjdk8_j9_systemtest_x86-64_macos/71/console

linux_ppcle-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-ppc64le-openj9/159/console
openjdk tests: https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_ppc64le_linux/284/console
system tests (crash running daa load test): https://ci.adoptopenjdk.net/job/openjdk8_j9_systemtest_ppc64le_linux/318/console

linux_x86-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-openj9/176/console
openjdk tests: https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_x86-64_linux/416/console
system tests (did not complete, Jenkins timeout): https://ci.adoptopenjdk.net/job/openjdk8_j9_systemtest_x86-64_linux/408/consoleFull
external test extended (failed, no tests run): https://ci.adoptopenjdk.net/job/openjdk8_j9_externaltest_extended_x86-64_linux/115/console
perftest: https://ci.adoptopenjdk.net/job/openjdk8_j9_perftest_x86-64_linux/283/console
external test (failed, no tests run): https://ci.adoptopenjdk.net/job/openjdk8_j9_externaltest_x86-64_linux/305/console

linux_390-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-s390x-openj9/182/console
openjdk tests: https://ci.adoptopenjdk.net/job/openjdk8_j9_openjdktest_s390x_linux/181/console
system tests (did not complete, Jenkins timeout): https://ci.adoptopenjdk.net/job/openjdk8_j9_systemtest_s390x_linux/171/console

**Comment by lumpfish** [comment]
Updated description with nightly build links

**Comment by gdams** [comment]
@lumpfish is this done?

**Comment by lumpfish** [comment]
Yes, closing
