### ISSUE TITLE
Create openjdk11-openj9 0.12 milestone 2 builds

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#833]
eclipse/openj9 have created a milestone branch which includes the features targeted for the Jan 2019 0.12 openj9 release to be incorporated into the Jan 2019 quarterly update.
This issue is to create a build from that branch to provide users with early access to a jdk11 which will be close in content to the actual quarterly release.

Links to nightly builds:
win_x86-64: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-01-15-07-37/OpenJDK11U-jdk_x64_windows_openj9_2019-01-15-07-37.zip
osx_x86-64: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-01-15-07-37/OpenJDK11U-jdk_x64_mac_openj9_2019-01-15-07-37.tar.gz
linux_x86-64LH: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-01-15-07-37/OpenJDK11U-jdk_x64_linux_openj9_linuxXL_2019-01-15-07-37.tar.gz
linux_x86-64: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-01-15-07-37/OpenJDK11U-jdk_x64_linux_openj9_2019-01-15-07-37.tar.gz
linux_390-64: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-01-15-07-37/OpenJDK11U-jdk_s390x_linux_openj9_2019-01-15-07-37.tar.gz
aix_ppc-64: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-01-15-07-37/OpenJDK11U-jdk_ppc64_aix_openj9_2019-01-15-07-37.tar.gz
linux_ppcle-64: https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk11u-2019-01-15-07-37/OpenJDK11U-jdk_ppc64le_linux_openj9_2019-01-15-07-37.tar.gz

**Comment by lumpfish** [comment]
Pipeline kicked off to build the openj9-openjdk-jdk11 repository openj9-0.12 branch which fetches the required eclipse/openj9 0.12-m2 branch.

Pipeline job:
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/249/

linux_x86-64LH
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9-linuxXL/86/console
openjdk tests (fail due to -Xcompressedrefs): https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_linux/236/console
system tests (fail due to -Xcompressedrefs): https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_linux/211/console

linux_x86-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-openj9/94/console
perftest: https://ci.adoptopenjdk.net/job/openjdk11_j9_perftest_x86-64_linux/101/console
system tests (did not complete, Jenkins timeout): https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_linux/210/console
external test extended (all failed - setup issues?): https://ci.adoptopenjdk.net/job/openjdk11_j9_externaltest_extended_x86-64_linux/89/console
external test: https://ci.adoptopenjdk.net/job/openjdk11_j9_externaltest_x86-64_linux/97/console
openjdk test: https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_linux/235/console

aix_ppc-64:
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/87/
No test jobs

linux_ppcle-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-ppc64le-openj9/88/console
openjdk tests: https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_ppc64le_linux/101/console
system tests (did not complete, Jenkins timeout): https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_ppc64le_linux/100/console

win_x86-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-openj9/88/console
openjdk tests: https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_windows/101/console

linux_390-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9/100/console
openjdk test: https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_s390x_linux/112/console
system tests (did not complete, Jenkins timeout): https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_s390x_linux/103/console

osx_x86-64
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/90/console
system tests: https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_macos/132/console
openjdk tests: https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_macos/134/console

osx_x86-64LH
Build: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9-macosXL/86/console
openjdk tests (fail due to -Xcompressedrefs): https://ci.adoptopenjdk.net/job/openjdk11_j9_openjdktest_x86-64_macos/135/console
system tests (fail due to -Xcompressedrefs): https://ci.adoptopenjdk.net/job/openjdk11_j9_systemtest_x86-64_macos/133/console

**Comment by lumpfish** [comment]
Updated description with nightly build links.

**Comment by gdams** [comment]
@lumpfish is this done?

**Comment by gdams** [comment]
ping @lumpfish

**Comment by M-Davies** [comment]
@lumpfish @karianna Can this be closed?

**Comment by karianna** [comment]
> @lumpfish @karianna Can this be closed?

Yes.
