### ISSUE TITLE
SplashScreen-Image in Manifest not working with OpenJDK 11.0.1+13 on x86

### ISSUE THREAD

**Issue by chrixm** [AdoptOpenJDK/openjdk-build#838]
Platform: Windows 7 x64

Architecture: OpenJDK 11.0.1+13 x86 running on Windows 7 x64

I have a JAR file that uses a SplashScreen-Image within the MANIFEST.MF file defined as follows:
SplashScreen-Image: images/splash.png

The image is within the JAR at the above location.

If I attempt to run this using OpenJDK 11.0.1+13 x64 (main distribution and not jlink created runtime) with the following command line then the splash screen is displayed:

java -jar MyApp.jar

However, if I try running the same JAR with OpenJDK 11.0.1+13 x86 then it fails to show the splash screen although the JAR is still loaded.

Should be easy to recreate but I can provide an example JAR if required.

**Comment by karianna** [comment]
If you can supply a JAR that would be most helpful thanks.

**Comment by sunnythepooh** [comment]
I ran the jar against:

openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode)

And it come up with a grey, blank splashscreen. 

If I run with Oracle Java 8 Update 111 it behaves the same

**Comment by chrixm** [comment]
Try running it against the 32-bit version and you won't get the Splash screen but you will on the 64-bit.
I have just tried on the following and see the same behaviour as 11.0.1:

C:\Local\Tools\jdk-11.0.2-x86\bin>java --version
openjdk 11.0.2 2018-10-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+7)
OpenJDK Server VM AdoptOpenJDK (build 11.0.2+7, mixed mode, emulated-client)

**Comment by teras** [comment]
Hello
Any news about this issue, or how to overpass it?
Thank you!

**Comment by M-Davies** [comment]
@chrixm Does switching to the latest JDK11 version resolve your issue? https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot

**Comment by cmason3** [comment]
Yes it does. I have retested on AdoptOpenJDK 11.0.7 and a splash screen appears on both the x64 and x86 runtimes. Thanks, I guess this issue can be closed.

**Comment by chrixm** [comment]
Yes it does. I have retested on AdoptOpenJDK 11.0.7 and a splash screen appears on both the x64 and x86 runtimes. Thanks, I guess this issue can be closed.
