### ISSUE TITLE
openjdk11-binaries latest_release.json is broken

### ISSUE THREAD

**Issue by rainbowgoblin** [AdoptOpenJDK/openjdk-build#843]
The latest_release.json file in the root of the openjdk11-binaries repo currently contains only the word "undefined" instead of the JSON list of latest releases for each platform. It looks like it was broken on November 24th.

We use this file in a cron script to maintain local updated versions of Adopt for the platforms we're interested in.

Sorry, I know this isn't the right place to report this, but issues are disabled for openjdk11-binaries. This seemed like the next best place.

**Comment by rainbowgoblin** [comment]
releases.json is just an empty list, as well. If you're not using these files anymore I'd appreciate knowing so I can come up with a new solution for my shell script.

**Comment by gdams** [comment]
We no longer used this JSON file. I didn't realise that people depended on it. You can either use the github API on the binaries repo to get the same JSON back, or consider using api.adoptopenjdk.net

**Comment by rainbowgoblin** [comment]
That's much easier, thanks for the tip. I'm going to close this issue now.
