### ISSUE TITLE
jdk8u202-b08 broken on ubuntu 18.04 LTS missing libpng12.so.0

### ISSUE THREAD

**Issue by webtomyfd** [AdoptOpenJDK/openjdk-build#851]
Hello Team,

Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
Linux x06-usudai01 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

jdk8u202-b08 does not work because of missing libpng12.so.0. 
The previous release jdk8u192-b12 worked (with libpng16)

Good Job Guys :-)

Thomas

**Comment by karianna** [comment]
Respun and resolved.

**Comment by pwagland** [comment]
Will a "8u202b09" be released with this fix?

**Comment by johnoliver** [comment]
as far as I can tell there is no `jdk8u202-b09` tag. `jdk8u202-b08` is still tagged as the `ga`

**Comment by victornoel** [comment]
@johnoliver @karianna I'm not clear: is this fix available in the latest image available on docker hub?

**Comment by johnoliver** [comment]
jdk8u202-b08 on docker hub claims to have been updated 14 hours ago, the re-release of the jdk8u202-b08 binary happened 2 days ago, so I presume it does have the updated version. The ci job also looks like it should have pulled in the latest.

**Comment by victornoel** [comment]
@johnoliver that's what I thought but I couldn't make it work :/
Neither with `adoptopenjdk/openjdk8:latest` nor the `adoptopenjdk/openjdk8:alpine` one (which is the one I would ultimately want to use), I still get this error:
```
java.lang.UnsatisfiedLinkError: /opt/java/openjdk/jre/lib/amd64/libfontmanager.so: libpng12.so.0: cannot open shared object file: No such file or directory
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
    at sun.font.SunFontManager$1.run(SunFontManager.java:339)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
    at java.lang.Class.forName0(Native Method)
    at ....
```

**Comment by johnoliver** [comment]
Out of interest if you manually download extract and run https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz inside the docker, does it still happen?

**Comment by johnoliver** [comment]
I just ran the adoptopenjdk/openjdk8:latest docker and it ran fine. I would check to see if you have something cached

**Comment by victornoel** [comment]
@johnoliver I am double-checking everything right now :)

**Comment by victornoel** [comment]
@johnoliver indeed, my bad, I got mixed up in errors: this error does not happen anymore but I'm seeing a variant of https://github.com/docker-library/openjdk/issues/73 with both images.
This is out of scope of this issue though, so I will open an issue if I think this should be fixed in this project.

**Comment by johnoliver** [comment]
There is another issue about this that we need to address, the version number `jdk8u202-b08` is controlled by the upstream project so we cannot change/bump it when we need to re-release it to fix packaging mistakes. The issue here is we need to add our own version number in somewhere that we can bump on re-releases

**Comment by karianna** [comment]
> There is another issue about this that we need to address, the version number `jdk8u202-b08` is controlled by the upstream project so we cannot change/bump it when we need to re-release it to fix packaging mistakes. The issue here is we need to add our own version number in somewhere that we can bump on re-releases

And @johnoliver Has helpfully opened a PR on this which should land after some discussions around how our metadata file is going to work.
