### ISSUE TITLE
Tests failing on openjdk-build scripts

### ISSUE THREAD

**Issue by tellison** [AdoptOpenJDK/openjdk-build#86]
As [shown via Travis](https://travis-ci.org/AdoptOpenJDK/openjdk-build), there are problems introduced recently that flag up script warnings.

These should be reviewed and fixed / ignored as appropriate (via  pull request ;-)

**Comment by gdams** [comment]
fixed in https://github.com/AdoptOpenJDK/openjdk-build/pull/85
