### ISSUE TITLE
AdoptOpenJDK (build 11+28) doesn't include jdk.internal.jvmstat in lib/modules

### ISSUE THREAD

**Issue by adalton** [AdoptOpenJDK/openjdk-build#862]
**Platform:**
Linux

**Architecture:**
x86_64

Please describe the issue that you are having with our binaries and if possible how to recreate it.

I have an application that uses `sun.jvmstat.monitor.MonitoredHost`.  I can build that application with the latest nightly JDK, but I cannot run it with the latest nightly JRE.

# Example Program

    $ cat Example.java
    import sun.jvmstat.monitor.MonitoredHost;

    public class Example {
        public static void main(String[] args) throws Exception {
            MonitoredHost host = MonitoredHost.getMonitoredHost("localhost");
        }
    }

# JDK/JRE Versions

    $ ./jdk-11.0.2+9/bin/java -version
    openjdk version "11.0.2" 2019-01-15
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9-201901241311)
    Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.12.0-rc1, JRE 11 Linux amd64-64-Bit Compressed References 20190124_106 (JIT enabled, AOT enabled)
    OpenJ9   - 22576592a
    OMR      - c0caded4
    JCL      - 208c8f977b based on jdk-11.0.2+9)

    $ ./jdk-11.0.2+9-jre/bin/java -version
    openjdk version "11.0.2" 2019-01-15
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9-201901241311)
    Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.12.0-rc1, JRE 11 Linux amd64-64-Bit Compressed References 20190124_106 (JIT enabled, AOT enabled)
    OpenJ9   - 22576592a
    OMR      - c0caded4
    JCL      - 208c8f977b based on jdk-11.0.2+9)

# Comple/Run with JDK

    $ ./jdk-11.0.2+9/bin/javac --add-exports jdk.internal.jvmstat/sun.jvmstat.monitor=ALL-UNNAMED Example.java 
    $ ./jdk-11.0.2+9/bin/java Example
    $ # No failure

# Attempt to Run Same Program with JRE

    $ ./jdk-11.0.2+9-jre/bin/java Example
    Exception in thread "main" java.lang.NoClassDefFoundError: sun.jvmstat.monitor.MonitoredHost
            at Example.main(Example.java:5)
    Caused by: java.lang.ClassNotFoundException: sun.jvmstat.monitor.MonitoredHost
            at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
            at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
            at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
            ... 1 more

# Potential Cause

It looks like the module set differs between the JDK and the JRE.  Most of the differences seem legitimate (e.g., the JRE doesn't include `jdk.compiler`), but it seems like the JRE should include some of the ones that are missing (e.g., `jdk.internal.jvmstat`, `jdk.jstatd`).

    $ ./jdk-11.0.2+9/bin/jimage list ./jdk-11.0.2+9/lib/modules  | grep Module: | sort -u > jdk.modules
    $ ./jdk-11.0.2+9/bin/jimage list ./jdk-11.0.2+9/lib/modules  | grep Module: | sort -u > jre.modules

    $ diff jdk.modules jre.modules 
    ...
    < Module: jdk.internal.jvmstat
    ...

Was `jdk.internal.jvmstat` intentionally omitted from the JRE, and if so, is there a work-around for running applications that uses that (admittedly internal) API with a JRE?

**Comment by karianna** [comment]
Access to those internal modules was deliberately removed with Java 9.  You may find the following SO Q&A helpful for the --add-exports workaround: 

https://stackoverflow.com/questions/51440683/java-10-replacement-for-sun-monitoredhost-class

Alternatively you'll need to look into the jlink tool to provide that module in your own custom jlinked 'JRE'
