### ISSUE TITLE
Add a 12u cloned repo and produce Java 12 binaries

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#883]
Features that impact the whole project (e.g. Adding a new OpenJDK distribution)are made over at the [TSC](https://github.com/AdoptOpenJDK/TSC/).

We can now clone and build http://hg.openjdk.java.net/jdk-updates/jdk12u/

- [x] Mirror job created
- [x] Diff job created

**Comment by gdams** [comment]
Mirror job created: https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-jdk12u/

**Comment by sophia-guo** [comment]
Job has failed ever since from created.  https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-jdk12u/

**Comment by karianna** [comment]
> Looks like job has failed ever since from creation? https://ci.adoptopenjdk.net/view/git-hg/job/git-hg-jdk12u/

I suspect it was mirroring from the wrong place.  We'll take a look after we finish ironing out the new release process

**Comment by gdams** [comment]
@johnoliver can we close?

**Comment by karianna** [comment]
I am not John but No - we still need to build and test these
