### ISSUE TITLE
Add "release publish" checkbox on the top level build pipelines

### ISSUE THREAD

**Issue by sxa555** [AdoptOpenJDK/openjdk-build#884]
In order to be able to properly test release pipelines I think we should modify the top level pipeline jobs so that `releaseTag` isn't what causes the release to be published as a release build.

If we use a separate checkbox then we can test adjustments to the production release process without making the releases live, and we can "elevate it" to full release status retrospectively. This would avoid many of the problems we've seen during the current AdoptOpenJDK OpenJ9 release cycle (Ref: https://github.com/AdoptOpenJDK/openjdk-build/issues/882)

**Comment by sxa555** [comment]
Also have a separate releaseName separate from releaseTag to avoid #725 until we understand #690

**Comment by johnoliver** [comment]
his has been reworked and we no longer publish automatically
