### ISSUE TITLE
pipeline job "releaseTag" has multiple uses that don't currently align

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#886]
**Platform:**
ALL

**Architecture:**
ALL

The pipeline build job has a "releaseTag" parameter which has multiple purposes:
  - Defines what level of code to checkout to build
  - Defines what level of openj9 extensions to checkout for openjdk-test jobs
  - Defines the "label" to be used for the published "released" build on the website

This currently means for openj9 we cannot specify a releaseTag of say "jdk-11.0.2+9_openj9-0.12.0" so we can label the published release appropriately, as this does not exist as a git "tag", and as a result all the test jobs fail.

**Comment by sxa555** [comment]
Can't remember where else I've already mentioned this but could do with being here too - adding a `releaseName` in addition to `releaseTag` to separate out the publish label would be useful until the issues with Windows tagging are resolved.

Ref the test jobs, potentially the same switch which we have in the build scripts (Ref: https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/prepareWorkspace.sh#L80), which is to check out a branch if specified, and avoid checking out the tag when on openj9 would be preferable logic (FYI @smlambert)

**Comment by M-Davies** [comment]
@andrew-m-leonard I don't think `releaseTag` exists in our pipelines anymore, it's been replaced with `releaseType` and `scmReference`. This should be good to close

**Comment by karianna** [comment]
> @andrew-m-leonard I don't think `releaseTag` exists in our pipelines anymore, it's been replaced with `releaseType` and `scmReference`. This should be good to close

Correct, we resolved this in overhaul v3 IIRC
