### ISSUE TITLE
Consider using hidden Bitbucket Hg repos as our source of truth

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#888]
Given that we regularly battle the git / hg ecosystem it may be worth building from bitbucket hg repos and only providing the GitHub repos as a read only location

**Comment by johnoliver** [comment]
Had discussion with @karianna closing as our git is fairly stable and working at the moment. Can reopen if we have any more impedance mismatch between HG and git in the future
