### ISSUE TITLE
Mount folder with build scripts for docker container 

### ISSUE THREAD

**Issue by neomatrix369** [AdoptOpenJDK/openjdk-build#89]
Currently, the docker builds copy the script into the docker image each time and any changes to the script mean rebuilding the image.

This can be error-prone and tedious, time-consuming as we have to rebuild the image each time.

A better option is to mount the folder as a volume at run-time (script it into the Dockerfile).

Note: the last time trying the above approach caused the container to prematurely terminate at run-time so it needs some investigation/testing, to find out why this happens and fix it.

Discussed with @johnoliver while reviewing and test changes via PR #82

**Comment by tellison** [comment]
> This can be error-prone and tedious, time-consuming as we have to rebuild the image each time.

On the other hand, once we have a stable build environment we can publish the Docker image that allows people to build OpenJDK trivially without requiring checking out the scripts in our openjdk-build repo.

I think we can agree that the source to be compiled should be mounted at build time, as that will be specific to each person's build; but the build scripts should be baked into the builder environment IMHO.

**Comment by neomatrix369** [comment]
Good point @tellison, in fact, we had two views on this, either to keep it the way it is (which is also where you are swaying) or to do it as this issue says. Although for testing purposes we need to find a quicker better way, may a script that copies the update scripts into the running container.
