### ISSUE TITLE
Missing checksum file in jdk-11.0.2+9_openj9-0.12.1 release

### ISSUE THREAD

**Issue by davehobbs** [AdoptOpenJDK/openjdk-build#891]
**Platform:**
linux
**Architecture:**
x64
Please describe the issue that you are having with our binaries and if possible how to recreate it.
The release https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/tag/jdk-11.0.2%2B9_openj9-0.12.1 is missing a checksum file for the linux x64 build. 

This also shows up in the JDK checksum link at: https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9#x64_linux which links to https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9.

The checksum file is also not available via the api i.e using https://api.adoptopenjdk.net/v2/info/releases/openjdk11?release=jdk-11.0.2%2B9_openj9-0.12.1&openjdk_impl=openj9&os=linux&arch=x64&type=jdk&heap_size=normal

**Comment by davehobbs** [comment]
I believe the pipeline https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/288/console created the checksum. Not sure what happened after that.

**Comment by davehobbs** [comment]
The checksum file has been manually recreated and added back into the release. So this is fixed for now. However we don't understand the underlying error. We couldn't see any errors in the job that copies the file across (I believe it's a refactoring job in Jenkins, that I don't have visibility of).

**Comment by davehobbs** [comment]
This has happened again in the jdk8u202-b08_openj9-0.12.1 release. The checksum file for the AIX jre is also missing - https://adoptopenjdk.net/releases.html?variant=openjdk8&jvmVariant=openj9#ppc64_aix. @lumpfish

**Comment by sxa555** [comment]
Deleted and regenerated/re-uploaded the `sha256.txt` manually. It was showing when I tried to edit the release with a red warning triangle beside it inviting me to delete and upload the file again ... So I did. Hopefully it will show up on the website soon and I'll download/verify it

**Comment by sxa555** [comment]
LGTM - closing
