### ISSUE TITLE
Copy jdk8u202-b08_openj9-0.12.1 release builds to openjdk8-binaries

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#892]
The jdk8u202-b08_openj9-0.12.1 release has now been built and tested.

The following build pipeline parameters were used to work around the build issues already raised:
releaseTag: jdk8u202-b08
branch: openj9-0.12.1
additionalFileNameTag: openj9-0.12.1

Some platforms needed two attempts due to the first build failing.  Also MacXL was added to the second attempt.

So the builds are attached to these two Jenkins pipelines, together making a full set of platforms:
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/443/
https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/444/

Tests run against MacXL failed (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/988/console) - so we are not is a position to release this build yet.

The remaining builds (not MacXL) now need to be copied manually to the openjdk8-binaries repository to
1. Specify the correct release name as required (jdk8u202-b08_openj9-0.12.1)
2. To rename the linuxXL build so that the linuxXL part appears earlier in the filename so that it is recognised correclty by the AdoptOpenJDK release download page.

The sha files may need to be updated / recreated.

Please can we update this issue with what needed to be done in case it needs to be repeated before the underlying issues are fixed.

**Comment by lumpfish** [comment]
The MacXL jdk_math_jre_0 tests failed because both the jdk and the jre URLs should have been passed as CUSTOMIZED_URLs to the grinder job, but only the jdk URL was.
The test has been rerun with the extra URL and now passes, so the MacXL builds can be added to the release.

**Comment by lumpfish** [comment]
@sxa555 - please could you upload the build to openjd8-binaries?

**Comment by sxa555** [comment]
Done (yesterday). Closing.
