### ISSUE TITLE
Java 8 with OpenJ9 (Large Heap) build doesn't have cacerts

### ISSUE THREAD

**Issue by akrus** [AdoptOpenJDK/openjdk-build#895]
**Platform:**
N/A
**Architecture:**
N/A

jre/lib/security/cacerts contains:
```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>GitHub — Unexpected problem serving your request</title>
    <style type="text/css" media="screen">
```

Should be actual cacerts instead.
Links:
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_linux_openj9_linuxXL_8u202b08-openj9-0.12.1.tar.gz
https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jre_x64_linux_openj9_linuxXL_8u202b08-openj9-0.12.1.tar.gz

**Comment by lumpfish** [comment]
The cacerts file actually contains this response from github:
![image](https://user-images.githubusercontent.com/26970658/52648296-2e8b2880-2ede-11e9-87dd-4bdd316e3c84.png)

**Comment by lumpfish** [comment]
Looks like a serious case of bad luck

**Comment by sxa555** [comment]
New version now available with `0.12.1a` in the tarball version number for openj9. Still identifies itself as `0.12.1` in the version output as the ONLY change is the cacerts correction. 

Ref: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u202-b08_openj9-0.12.1

**Comment by sxa555** [comment]
Going to leave this option until we've got something in place that will trap the issue in the future.

**Comment by aahlenst** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/pull/2033 builds it locally and if it's missing, the build fails.
