### ISSUE TITLE
Build IcedTea-Web at AdoptOpenJDK

### ISSUE THREAD

**Issue by charliegracie** [AdoptOpenJDK/openjdk-build#898]
When moving to AdoptOpenJDK JDK8 builds from other providers like Oracle JDK8 users lose some functionality due to features not be available in OpenJDK.

One of the biggest issue is that lack of WebStart functionality. The [IcedTea-Web](https://icedtea.classpath.org/wiki/IcedTea-Web) project provides an OpenSource replacement for WebStart. It would be great if the AdoptOpenJDK project provided builds for IcedTea-Web to help smooth the transition to AdoptOpenJDK builds.

**Comment by charliegracie** [comment]
Is this something that the AdoptOpenJDK community thinks is a good idea? If the answer is yes I would like to help get this work moving.

**Comment by smlambert** [comment]
related: https://github.com/AdoptOpenJDK/TSC/issues/41

**Comment by charliegracie** [comment]
Thanks @smlambert I couldn't find that to link it!

**Comment by bryandx** [comment]
Applet support (on Windows with Java 8) is also needed by our organization for some older EMC Documentum apps.  I believe IcedTea-Web does have that support

**Comment by karianna** [comment]
We now have a repo https://github.com/AdoptOpenJDK/icedtea-web and the icedtea team are working on getting the CI pipeline up and running.  Then we'll look to build releases here and bundle with Adopt Binaries as an optional extra.

**Comment by gdams** [comment]
closing, ITW 1.8.1 is released!
