### ISSUE TITLE
openjdk11_j9_openjdktest_x86-64_linux_linuxXL build was triggered by wrong format of releasetag

### ISSUE THREAD

**Issue by sophia-guo** [AdoptOpenJDK/openjdk-build#899]
openjdk11_j9_openjdktest_x86-64_linux_linuxXL build was triggered by unexpected releasetag. 

```
13:26:36 getOpenjdk:
13:26:36      [echo] git clone --depth 1 -q --branch jdk-11.0.2+9_openj9-0.12.1 https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
13:26:36      [exec] warning: Could not find remote branch jdk-11.0.2+9_openj9-0.12.1 to clone.
13:26:36      [exec] fatal: Remote branch jdk-11.0.2+9_openj9-0.12.1 not found in upstream origin
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux_linuxXL/20/

My understanding is this was triggered by WIP  https://github.com/AdoptOpenJDK/openjdk-build/pull/881 and any failure may be expected. Just note that tests are using RELEASE_TAG to sync openj9 jdk product code and test code. If RELEASE_TAG is expanded with extra information like jdk-11.0.2+9_openj9-0.12.1 those extra information should be removed before passing down to test builds.

**Comment by karianna** [comment]
@johnoliver I think your PR resolves this...

**Comment by sophia-guo** [comment]
This is fixed https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk11_j9_openjdktest_x86-64_linux_linuxXL/
