### ISSUE TITLE
Checksum files for builds should not contain a path 

### ISSUE THREAD

**Issue by breun** [AdoptOpenJDK/openjdk-build#900]
**Platform:** macOS

**Architecture:** x64

Verifying the SHA256 checksum of the AdoptOpenJDK 8 with OpenJ9 build fails:

```
$ shasum --algorithm 256 --check OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz.sha256.txt 
shasum: target/linux/x64/openj9/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz: 
target/linux/x64/openj9/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz: FAILED open or read
shasum: WARNING: 1 listed file could not be read
```

The cause seems to be that the checksum file contains a path (`target/linux/x64/openj9/`) before the filename. When I remove this path the checksum check succeeds.

The checksum file for the HotSpot build does not contain this path prefix and works without having to modify the file.

**Comment by breun** [comment]
There are more checksum files that contain paths.

* JDK 11.0.2+9 with HotSpot VM: [OK](
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.2_9.tar.gz.sha256.txt)
* JDK 11.0.2+9 with OpenJ9 VM: [Not OK](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_linux_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz.sha256.txt)
* JDK 11.0.2+9 with OpenJ9 VM with Large Heap support: [OK](https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_linux_openj9_linuxXL_11.0.2_9_openj9-0.12.1-openj9-0.12.1.tar.gz.sha256.txt)
* JRE 11.0.2+9 with HotSpot VM: [OK](
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jre_x64_linux_hotspot_11.0.2_9.tar.gz.sha256.txt)
* JRE 11.0.2+9 with OpenJ9 VM: [Not OK](
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jre_x64_linux_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz.sha256.txt)
* JRE 11.0.2+9 with OpenJ9 VM with Large Heap support: [OK](
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jre_x64_linux_openj9_linuxXL_11.0.2_9_openj9-0.12.1-openj9-0.12.1.tar.gz.sha256.txt)
* JDK 8u202b08 with HotSpot VM: [OK](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u202b08.tar.gz.sha256.txt)
* JDK 8u202b08 with OpenJ9 VM: [Not OK](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz.sha256.txt)
* JDK 8u202b08 with OpenJ9 VM with Large Heap support: [Not OK](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jdk_x64_linux_openj9_linuxXL_8u202b08-openj9-0.12.1.tar.gz.sha256.txt)
* JRE 8u202b08 with HotSpot VM: [OK](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08/OpenJDK8U-jre_x64_linux_hotspot_8u202b08.tar.gz.sha256.txt)
* JRE 8u202b08 with OpenJ9 VM: [Not OK](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jre_x64_linux_openj9_8u202b08_openj9-0.12.1.tar.gz.sha256.txt)
* JRE 8u202b08 with OpenJ9 VM with Large Heap support: [Not OK](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u202-b08_openj9-0.12.1/OpenJDK8U-jre_x64_linux_openj9_linuxXL_8u202b08-openj9-0.12.1.tar.gz.sha256.txt)

**Comment by gdams** [comment]
@breun is this still an issue? I believe that all the checksums don't contain directories anymore for new releases

**Comment by gdams** [comment]
closing

**Comment by AdamBrousseau** [comment]
I found this issue because in my builds, my checksums contain the paths. I see the Temurin ones don't, but looking at the pipeline code I don't see how the Temurin ones don't.
https://github.com/adoptium/ci-jenkins-pipelines/blob/921d48a4ad3d5f167f58a327b37147f697252be7/pipelines/build/common/build_base_file.groovy#L764
```
context.sh 'for file in $(ls target/*/*/*/*.tar.gz target/*/*/*/*.zip); do sha256sum "$file" > $file.sha256.txt ; done'
```
The artifacts are copied back to the parent pipeline in folders on my builds. I don't have permissions to see the Adopt ones.
Hopefully someone can tell me what I'm failing to see.

**Comment by AdamBrousseau** [comment]
Just to reply to my previous comment. The files are modified when they are uploaded to GitHub here
https://github.com/adoptium/github-release-scripts/blob/d5d642b2535e82fb6975ec4022945940ff92319d/sbin/Release.sh#L64

**Comment by AdamBrousseau** [comment]
Just to reply to my previous comment. The files are modified when they are uploaded to GitHub here
https://github.com/adoptium/github-release-scripts/blob/d5d642b2535e82fb6975ec4022945940ff92319d/sbin/Release.sh#L64
