### ISSUE TITLE
Refactor JTReg Build

### ISSUE THREAD

**Issue by shurymury** [AdoptOpenJDK/openjdk-build#914]
Such as in https://ci.adoptopenjdk.net/job/jtreg.

See this for more info: https://mail.openjdk.java.net/pipermail/jtreg-use/2019-February/000683.html

**Comment by sophia-guo** [comment]
Current job is triggered by related upstream jobs, periodically and SCM pull. Looks like the build actually doesn't depends on upstream jobs, which is a bit confused shell script. Probably need to revisit the story and do some clean up?

**Comment by smlambert** [comment]
Yes, ideally would be good to get the script into git repo, but even a cleanup and update of existing setup will be good.

**Comment by karianna** [comment]
Yeah, it's a will modularised script but it's not clear how it's getting the version.  I've kicked off a manual build to see if it'll 'do the right thing' in the mean time

**Comment by karianna** [comment]
OK so it's built the latest version, folks can grab that now.

**Comment by M-Davies** [comment]
@karianna Ref https://github.com/AdoptOpenJDK/openjdk-build/issues/914#issuecomment-466196571, can this be closed?

**Comment by karianna** [comment]
> @karianna Ref [#914 (comment)](https://github.com/AdoptOpenJDK/openjdk-build/issues/914#issuecomment-466196571), can this be closed?

yep
