### ISSUE TITLE
Add jdk12 to build pipelines

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#916]
Amend scripts as required to build openjdk12-hotspot and openjdk12-openj9.

**Comment by lumpfish** [comment]
1. Changed https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/build-pipeline-generator/ to generate a pipeline for jdk12
2. Changed the generated https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk12-pipeline/ to point at a fork of openjdk-build (this will be overwritten overnight when the generate pipeline job runs again).
3. Added a JDK12_CORE_VERSION definition and included it in various if statements, similar to jdk11
4. Added stanzas to change the JDK_BOOT_DIR to jdk11 for jdk12 and HEAD
5. Fixed the wgets for jdk11 for JDK_BOOT_DIR to identofy a single AdoptOpenJDK build
6. Changed the openssl build options for openj9 (they are no longer required as openj9 loads openssl dynamically in jdk12)

With these changes linux_x86-64 for openjdk12-openj9 now builds.  ppcle build is still running as this is being written.

Known issues:
1. For Windows, setting the JDK_BOOT_DIR is not done (can't see where it's done)
2. For Mac the downloaded bott jdk does not have the directory structure the build scripts assume
3. AIX build machine has unrelated issues
4. Linux S390x: build machine may be missing some X11 prereqs

**Comment by lumpfish** [comment]
Created https://github.com/AdoptOpenJDK/openjdk-build/pull/917 with the work achieved so far.

**Comment by lumpfish** [comment]
Support for openssl has now been added for openjdk12-openj9.  I've updated the relevant builds args in the jdk12_support branch in https://github.com/AdoptOpenJDK/openjdk-build/pull/917.

**Comment by lumpfish** [comment]
Raised https://github.com/AdoptOpenJDK/openjdk-build/issues/924 for the macos jdk boot dir issue.

**Comment by lumpfish** [comment]
Issue with X11 prereqs on Linux should be fixed by https://github.com/AdoptOpenJDK/openjdk-infrastructure/pull/640.

**Comment by lumpfish** [comment]
Raised https://github.com/AdoptOpenJDK/openjdk-build/issues/938 for the missing X11 prereqs.  Change to ansible scripts in AdoptOpenJDK/openjdk-infrastructure#640 did not fix the issue because those scripts are not running successfully on s390x and ppcle Linux.

**Comment by sxa555** [comment]
Adding some PR references for historic completeness: https://github.com/AdoptOpenJDK/openjdk-build/pull/917 https://github.com/AdoptOpenJDK/openjdk-build/pull/923 https://github.com/AdoptOpenJDK/openjdk-build/pull/943

There have been some subsequent queries over version strings: https://github.com/AdoptOpenJDK/openjdk-build/issues/935 https://github.com/AdoptOpenJDK/openjdk-build/issues/935 but these are unlikely to be directly related to the changes to enable JDK12.

On that basis I am closing this issue.
