### ISSUE TITLE
Missing an AIX Java 11 Hotspot release build

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#922]
https://ci.adoptopenjdk.net/view/all/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-openj9/163/console as an example, looks like a bad boot jdk

**Comment by sxa555** [comment]
I deployed a java10 boot JDK (and java11) on the AIX machines as per the playbooks, therefore the "dynamic" boot JDK download code failing on this platform (which I want to get rid of going forward anyway) is no longer an issue.

We should now do a release of HotSpot/JDK11/AIX though.

**Comment by aahlenst** [comment]
AIX releases of 11 have become available.
