### ISSUE TITLE
Mixed-case string: java.vendor returns "AdoptOpenJdk" 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#935]
**Platform:**
All

**Architecture:**
All

Please describe the issue that you are having with our binaries and if possible how to recreate it.

Should probably correct the  java.vendor string to return "AdoptOpenJDK" rather than "AdoptOpenJdk" which looks like a typo

https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk8_hs_openjdktest_extended_x86-64_linux/lastCompletedBuild/testReport/runtime_6981737_Test6981737/java/Test6981737/
Checking java.vendor: "AdoptOpenJdk".matches("Oracle Corporation")... no.  

(as an aside, a fix to this java.vendor test needs to be backported to not fail if not Oracle, https://bugs.openjdk.java.net/browse/JDK-8195153 )

**Comment by jerboaa** [comment]
Note that the vendor test fix has been backported and is coming with 8u212:
https://bugs.openjdk.java.net/browse/JDK-8220047

**Comment by karianna** [comment]
Yes, see #1020

**Comment by jerboaa** [comment]
#1020 seems related to https://bugs.openjdk.java.net/browse/JDK-8189761 and https://bugs.openjdk.java.net/browse/JDK-8193764. JDK-8195153 (and 8u bug JDK-8220047) is a test-only fix.

**Comment by austin0** [comment]
This has been fixed, current output is:
```
    java.vendor = AdoptOpenJDK
    java.vendor.url = https://adoptopenjdk.net/
    java.vendor.url.bug = https://github.com/AdoptOpenJDK/openjdk-support/issues
    java.vendor.version = AdoptOpenJDK
```
