### ISSUE TITLE
Windows jdk12 build fails

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#937]
**Platform:**

Windows

**Architecture:**

x86

The first attempt at a jdk12 Windows build fails early on accompanied by a worrying message:
```
WARNING: The toolchain version used is known to have issues. Please
consider using a supported version unless you know what you are doing.
```
See: 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-windows-x64-hotspot/5/console

**Comment by karianna** [comment]
```
    elif [ "${JAVA_TO_BUILD}" == "${JDK12_VERSION}" ]
    then
      TOOLCHAIN_VERSION="2017"
      export CONFIGURE_ARGS_FOR_ANY_PLATFORM="${CONFIGURE_ARGS_FOR_ANY_PLATFORM} --with-freemarker-jar=/cygdrive/c/openjdk/freemarker.jar --with-openssl=/cygdrive/c/progra~1/OpenSSL --enable-openssl-bundling"
    fi
```

Perhaps a bug in windows.sh - logic above looks fairly sane though.

**Comment by lumpfish** [comment]
Elsewhere in the output it says:
```
/cygdrive/c/cygwin64/tmp/openjdk-jdk12u-windows-x64-hotspot/workspace/build/src/build/windows-x86_64-server-release
using configure arguments '--verbose --with-version-opt=201903030947 --without-version-pre --with-version-build=30 --with-vendor-version-string=AdoptOpenJDK --with-vendor-url=https://adoptopenjdk.net/ --with-vendor-name=AdoptOpenJDK --with-vendor-vm-bug-url=https://github.com/AdoptOpenJDK/openjdk-build/issues --with-boot-jdk=/cygdrive/c/openjdk/jdk11 --disable-warnings-as-errors --with-toolchain-version=2013
```
Note the --with-toolchain-version=2013

**Comment by lumpfish** [comment]
Looks like TOOLCHAIN_VERSION=2017 is only set for openj9 builds.  TOOLCHAIN_VERSION=2013 is set for hotspot.

**Comment by lumpfish** [comment]
Similar failure on openj9 build though (with TOOLCHAIN_VERSION=2017): https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-windows-x64-openj9/5/console
```
Building targets 'product-images legacy-jre-image test-image' in configuration 'windows-x86_64-server-release'
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
Could not start process!  Failed with error 2: The system cannot find the file specified.


make[3]: *** [ToolsLangtools.gmk:40: /cygdrive/c/cygwin64/tmp/openjdk-jdk12u-windows-x64-openj9/workspace/build/src/build/windows-x86_64-server-release/buildtools/langtools_tools_classes/_the.BUILD_TOOLS_LANGTOOLS_batch] Error 126
make[2]: *** [make/Main.gmk:73: buildtools-langtools] Error 2
```

**Comment by ali-ince** [comment]
So, the main reason for the hotspot failure was a typo in the script file that doesn't pick the expected variables and even it was the build was not assigned to the correct build machine with VS2017 installed.  

Those should be fixed by #940.

**Comment by ali-ince** [comment]
openj9 issue seems to be a completely different problem - maybe we should create another issue for that?

**Comment by lumpfish** [comment]
Raised https://github.com/AdoptOpenJDK/openjdk-build/issues/941 for the second issue.
