### ISSUE TITLE
Gradle build fails with "Too many open files" on OpenJ9

### ISSUE THREAD

**Issue by mcs6502** [AdoptOpenJDK/openjdk-build#939]
**Platform:**
openj9-0.12.1 on Mac OS X 10.14.2

**Architecture:**
x86_64 (amd64)

_Please describe the issue that you are having with our binaries and if possible how to recreate it._

I tried to do a gradle build of a project using OpenJDK with OpenJ9 VM. The build failed right at the start, whilst analysing build scripts. The underlying error was "Too many open files".

The same OpenJDK version but with HotSpot VM ran a test gradle build without errors. This could be a Gradle/Groovy issue but I felt it might be worth reporting here.

Please see attached file [OpenJ9-TooManyOpenFiles.txt](https://github.com/AdoptOpenJDK/openjdk-build/files/2928539/OpenJ9-TooManyOpenFiles.txt) for version numbers and other details.

**Comment by DanHeidinga** [comment]
This looks very similar to https://github.com/eclipse/openj9/issues/4717 with the underlying discussion being in OMR: https://github.com/eclipse/omr/issues/3579

fyi @pdbain-ibm

**Comment by pdbain-ibm** [comment]
@mcs6502 

We are working on a solution.  In the meantime, the workaround is to increase the soft limit on open files.  You can get the system limit like so:

> $ sysctl kern.maxfilesperproc
> kern.maxfilesperproc: 24576

and change the soft limit like so:

> $ ulimit -Sn 24000

You can check your soft limit by omitting the value.

**Comment by mcs6502** [comment]
Thanks for the OMR pointer, Dan, and for the workaround, Peter.
Confirming that the problem disappears after `ulimit -Sn 500` upping the file handle limit to 500 from the default 256.
(Gradle users note that you'd also need to stop the existing daemon for the ulimit change to take effect.)

**Comment by pshipton** [comment]
eclipse/omr#3579 is resolved now, so this should work with an updated JVM build, without the ulimit workaround. It will require a nightly build dated March 8 or later (there isn't one right now), or the next release, which is 0.14 scheduled for April 26.

**Comment by karianna** [comment]
I'll bravely close this early :-)
