### ISSUE TITLE
Windows jdk12 build fails #2

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#941]
**Platform:**
Windows

**Architecture:**
x64

Originally raised as part of #937, but there were two different issues.

The first attempt at an jdk12 Windows build fails with 
```
Building targets 'product-images legacy-jre-image test-image' in configuration 'windows-x86_64-server-release'
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
Could not start process!  Failed with error 2: The system cannot find the file specified.


make[3]: *** [ToolsLangtools.gmk:40: /cygdrive/c/cygwin64/tmp/openjdk-jdk12u-windows-x64-openj9/workspace/build/src/build/windows-x86_64-server-release/buildtools/langtools_tools_classes/_the.BUILD_TOOLS_LANGTOOLS_batch] Error 126
make[2]: *** [make/Main.gmk:73: buildtools-langtools] Error 2
```
Full log at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-windows-x64-openj9/5/console

**Comment by lumpfish** [comment]
Same error also on hotspot builds: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-windows-x64-hotspot/7/console (though at the moment hotspot is still building with VS2013, waiting for the merge of PR #940).

**Comment by karianna** [comment]
> Same error also on hotspot builds: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-windows-x64-hotspot/7/console (though at the moment hotspot is still building with VS2013, waiting for the merge of PR #940).

@lumpfish #940 has landed - can you run again?

**Comment by lumpfish** [comment]
Same error building hotspot with VS2017: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-windows-x64-hotspot/8/console

**Comment by lumpfish** [comment]
Could it be similar to this: https://github.com/AdoptOpenJDK/openjdk-build/issues/452?

**Comment by sxa555** [comment]
> Could it be similar to this: #452?

Assuming so I've now fixed it on `-1` and `-2` so please reopen if this recurs
