### ISSUE TITLE
Fonts with embedded bitmaps are not always rotated

### ISSUE THREAD

**Issue by myamamoto** [AdoptOpenJDK/openjdk-build#945]
**Platform:**
All

**Architecture:**
Windows

I would like you to also make the following fix to jdk 8
https://github.com/AdoptOpenJDK/openjdk-jdk11u/commit/f1bf238b695e0b4d49b8264b83228317ee75ebd3#diff-5c6198e34c46737fc7bf8f0eb5fff8d0

**Comment by karianna** [comment]
Hi @myamamoto I assume this is an issue with all OpenJDK 8 builds (from Oracle, Azul etc as well?). In that case you will need to make a backport request to the OpenJDK project (We can help you through that process).

**Comment by myamamoto** [comment]
Hi, @karianna Could you tell me how to request to the OpenJDK project?

**Comment by karianna** [comment]
> Hi, @karianna Could you tell me how to request to the OpenJDK project?

The first step is to find the bug in the JBS bug database that covers this fix.

You'll want to search on https://bugs.openjdk.java.net/

Once you find that bug post back here and we'll take the next step :-)

You can also join our slack to do this all in real time

**Comment by myamamoto** [comment]
This is the bug I told.
https://bugs.openjdk.java.net/browse/JDK-8204929

**Comment by myamamoto** [comment]
Hi, @karianna This is the bug I told.
https://bugs.openjdk.java.net/browse/JDK-8204929

**Comment by karianna** [comment]
OK, that bug report seems to indicate that there is no issue with Java 8?

**Comment by myamamoto** [comment]
This is the issue for Java8. https://bugs.openjdk.java.net/browse/JDK-8163278
This issue is closed as duplicated...

**Comment by karianna** [comment]
Hi @myamamoto - have you tested this with the latest 8u build?

If it's still an issue there then I would post to the 2d-dev mailing list on OpenJDK and ask if someone is willing to apply https://bugs.openjdk.java.net/browse/JDK-8163278 as a backport of https://bugs.openjdk.java.net/browse/JDK-8204929

**Comment by myamamoto** [comment]
I tested it and confirmed this bug is not fixed in 8u202.

**Comment by karianna** [comment]
> I tested it and confirmed this bug is not fixed in 8u202.

OK, so the next step will be to post on the 2d-dev mailing list - (you can sign up via http://mail.openjdk.java.net/mailman/listinfo/2d-dev).  And ask if someone is willing to sponsor a backport of https://bugs.openjdk.java.net/browse/JDK-8204929 (and tell them that you think https://bugs.openjdk.java.net/browse/JDK-8163278 could perhaps be the right issue to reopen for this.).

Let us know if you don't get a positive response in 72 hours or so and we'll see if we can find a sponsor at Adopt.

**Comment by myamamoto** [comment]
I am confused.
I do not know who will solve this problem.

This is the reply from the 2nd-dev mailing list.
1) Issues are NOT re-opened to be backported. That is not how JBS works
2) The issue is not in Oracle JDK 8, it is only in OpenJDK 8.
So long as you use Oracle JDK 8 you should not be seeing this.
3) This is not a bug report or support alias.
Problems with a binary product should be sent to whoever provided you
with the binary product.

**Comment by karianna** [comment]
Hi @myamamoto - Sorry you didn't have good experience in the upstream project.  Let me drop a note to our JBS team and see what can be done.

**Comment by myamamoto** [comment]
Hi @karianna Could you tell me the status about this issue? Thank you in advance.

**Comment by karianna** [comment]
Hi @myamamoto - So a better approach is to create a patch (you can create a .patch file =based off our `openjdk-jdk8u` repo) and then send the contents of that patch to the jdk8u mailing list https://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev - does that make sense?

**Comment by myamamoto** [comment]
Hi @karianna Thanks for your advice.
I do not know if that will do well or not.
I expect that adoptOpenJDK will do that including patch file creation and this bug will be fixed.

**Comment by karianna** [comment]
> Hi @karianna Thanks for your advice.
> I do not know if that will do well or not.
> I expect that AdoptOpenJDK will do that including patch file creation and this bug will be fixed.

AdoptOpenJDK has a "Patches must be applied upstream policy".  If you'd like a company to do this on your behalf then both IBM and jClarity provide commercial support - see https://adoptopenjdk.net/support.html

**Comment by myamamoto** [comment]
What does upstream policy mean?

**Comment by karianna** [comment]
> What does upstream policy mean?

AdoptOpenJDK only hosts its own patches in extreme circumstances.  All patches should be patch upstream at OpenJDK (ore Eclipse OpenJ9) as appropriate.  You can opt to make these patches yourself or engage in a commercial support arrangement to have it done for you.

**Comment by M-Davies** [comment]
Hi @myamamoto . Just looking for an update on this. Did you get a response from the mailing lists?

**Comment by myamamoto** [comment]
Hi @M-Davies 
Nothing was known from the mailing lists, but I confirmed that it was fixed
https://bugs.openjdk.java.net/browse/JDK-8225334

**Comment by M-Davies** [comment]
Ah excellent. Does the patch work for you? If so, if there's nothing else you need, this can probably be closed 🙂
