### ISSUE TITLE
11.0.x Windows 32bit splashscreen failure

### ISSUE THREAD

**Issue by illumi** [AdoptOpenJDK/openjdk-build#946]
**Platform:**
Windows

**Architecture:**
32bits

Compile and run the demo from https://docs.oracle.com/javase/tutorial/uiswing/misc/splashscreen.html 
64bit release executes successfully, 32bits the call to SplashScreen.getSplashScreen() always returns null.

**Comment by karianna** [comment]
@ali-ince Have you got a Win-32 system to replicate this on?

**Comment by illumi** [comment]
32bit package will work on a Win64 system and also displays this bug. This isn't exclusive to a Windows 32bit OS installation, only the 32bit release from AOJDK.

**Comment by ali-ince** [comment]
This is probably related to the patch being discussed at https://mail.openjdk.java.net/pipermail/build-dev/2019-March/025213.html.

The bug report is available at bug: https://bugs.openjdk.java.net/browse/JDK-8217707.

I'll follow up the backport of the fix to 11u and 12u after the initial patch is merged.

**Comment by ali-ince** [comment]
I've just requested the backport of the fix into 11u and 12u.

**Comment by M-Davies** [comment]
Hi @illumi . A issue recently closed seems similar to this (https://github.com/AdoptOpenJDK/openjdk-build/issues/838), the solution being to [update to the latest binary](https://github.com/AdoptOpenJDK/openjdk-build/issues/838#issuecomment-630607609). Could you give this another try using a [newer release](https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=hotspot)? Thanks in advance

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.
