### ISSUE TITLE
Enable openssl feature on aix and remove bundling on linux

### ISSUE THREAD

**Issue by lumpfish** [AdoptOpenJDK/openjdk-build#948]
The code to enable openssl to be dynamically linked has been enabled for openjdk8-openj9, openjdk11-openj9 and openjdk12-openj9.

This means that openssl no longer needs to be bundled with the AdoptOpenJDK openj9 builds.

We plan to continue to bundle for Windows and MacOS because it is less likely that openssl will be installed on those operating systems.

This means removing the
```
--enable-openssl-bundling
```
option from the linux builds and adding
```
--with-openssl=fetched
```
to the aix builds (which did not have the openssl option previously).

**Comment by pshipton** [comment]
The jdk8 changes to support dynamic linking haven't been delivered yet.

AIX will also need the getsource option `--openssl-version=1.1.1b` (or 1.1.1x - any of 1.1.1, 1.1.1a, 1.1.1b would be fine) .

**Comment by lumpfish** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/prepareWorkspace.sh already runs bash get_source.sh --openssl-version=1.1.1a (even on aix).
I'll leave jdk8 alone until the code is merged.

**Comment by lumpfish** [comment]
Submitted https://github.com/AdoptOpenJDK/openjdk-build/pull/949 for aix enablement.

**Comment by M-Davies** [comment]
Hi @lumpfish . What is the current status on this? IIRC there was some talk on this recently in Slack:#build

**Comment by pshipton** [comment]
This was resolved long ago and can be closed.

**Comment by M-Davies** [comment]
@karianna Do your thing 😄 https://github.com/AdoptOpenJDK/openjdk-build/issues/948#issuecomment-630810103
