### ISSUE TITLE
Hotspot JDK12 binaries are building jdk-updates/jdk12u and not jdk/jdk12

### ISSUE THREAD

**Issue by andrew-m-leonard** [AdoptOpenJDK/openjdk-build#954]
It seems the JDK12 Hotspot builds have openjdk jdk12u bug fixes in which are not present in the jdk12 repo. For example JDK-8219650 which is targetted for 12.0.2.
I am thus guessing the JDK12 Hotspot builds are cloning jdk-updates/jdk12u rather than jdk/jdk12 ?
jdk-updates/jdk12 is for updates to jdk12 12.0.1, 12.0.2, including merges from the jdk/jdk12.

**Comment by karianna** [comment]
John and I are having fun trying to figure this out.

**Comment by karianna** [comment]
Your assumptions are correct.  12.0.0-ga will get released from jdk12 and 12.0.1+ will get released from jdk12u
