### ISSUE TITLE
jdk11u-mac-x64-openj9 failing 

### ISSUE THREAD

**Issue by smlambert** [AdoptOpenJDK/openjdk-build#958]
platform: macos

Last successful nightly build is from Feb 27th, 

Build failure from recent build: 
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/160/console

checking for version string... 11.0.3+2-201903111910
configure: Found potential Boot JDK using configure arguments
configure: error: The path given by --with-boot-jdk does not contain a valid Boot JDK
configure exiting with result code 1
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] }
[Pipeline] // stage
[Pipeline] echo
Execution error: script returned exit code 2

**Comment by sxa555** [comment]
For reference this is on https://ci.adoptopenjdk.net/computer/build-macstadium-macos1010-2/ and it's using `--with-boot-jdk=/Users/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-mac-x64-openj9/jdk-10/Home`

**Comment by sxa555** [comment]
Shouldn't have `/Home` on the end ... I think someone was making changes in that area at one point recently since it's using a dynamically fetched JDK - will investigate. I want to move away from anything using a pre-fetched one regardless ...

**Comment by sxa555** [comment]
Recent updates in this area: https://github.com/AdoptOpenJDK/openjdk-build/pull/930 https://github.com/AdoptOpenJDK/openjdk-build/pull/932

**Comment by lumpfish** [comment]
Looks like we need to revert the changes for Mac in the PRs referenced above.  What I don't understand is how the fix appeared to fix the JDK12 Mac builds.  The current JDK12 Mac builds are using a boot jdk from a different location - see https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-mac-x64-openj9/20.
It would be good to have a policy of either always downloading the boot_jdk or always overriding it (e.g. using an Ansible installed boot JDK) for consistency.

**Comment by lumpfish** [comment]
Submitted PR https://github.com/AdoptOpenJDK/openjdk-build/pull/959 to revert the change. @sxa555 - please could you review?

**Comment by sxa555** [comment]
Done -  feel free to merge once the checks are complete, then we can kick off another mac build to test

**Comment by sxa555** [comment]
Initiated https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/161/ now that 959 is merged

**Comment by johnoliver** [comment]
I dont think 959 is merged

**Comment by sxa555** [comment]
Have forced through https://github.com/AdoptOpenJDK/openjdk-build/pull/962 and https://github.com/AdoptOpenJDK/openjdk-build/pull/963 to do different things for JDK10 and JDK11. Build now running successfully at https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-mac-x64-openj9/168
