### ISSUE TITLE
Add aarch64 linux build of openj9+openjdk11

### ISSUE THREAD

**Issue by knn-k** [AdoptOpenJDK/openjdk-build#966]
The aarch64 linux build of openj9+openjdk11 is wanted.
It can be built manually now using a cross-compiling environment by following the build instructions, and runs in the interpreter mode.

**Comment by karianna** [comment]
If OpenJ9 is supporting this upstream then we're happy to assist in getting this up and running.  I've put it in the Backlog as it needs volunteers

**Comment by smlambert** [comment]
OpenJ9 is supporting this upstream.

FYI @sxa555 - I cc-ed you on a note from @knn-k so you have context.
 
We have also completed preliminary testing against developer builds.

**Comment by sxa555** [comment]
@knn-k Can it be built natively instead of with a cross compiler? That would make our setup and implementation easier.

**Comment by knn-k** [comment]
Unfortunately, no.  The build configuration for aarch64 in OpenJ9 assumes cross-compilation at this point.
I will take a look if I can change it for building natively.

**Comment by sxa555** [comment]
Changes https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/149 and https://github.com/eclipse/openj9/pull/5321 should enable native compilation

**Comment by sxa555** [comment]
Note, the build will run to completion using `--with-openssl=system` on Ubunt4un 16.04 with the `libssl-dev` package installed

**Comment by sxa555** [comment]
Almost there - I've temporarily patched the machine to resolve https://github.com/eclipse/openj9/pull/5451 but once that's in I'll undo that but it's now live on https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9/

**Comment by sxa555** [comment]
Working other than the fact the build currently needs `--disable-warnings-as-errors-openj9` as per https://github.com/eclipse/openj9/issues/4486 - am hoping we can use another option in production.

**Comment by sxa555** [comment]
The "other option" is now submitted under https://github.com/eclipse/openj9/pull/5508
I have validated that the `ar` fix works
