### ISSUE TITLE
Provision a Windows Test box

### ISSUE THREAD

**Issue by karianna** [AdoptOpenJDK/openjdk-build#99]

**Comment by gdams** [comment]
provisioned test-packet-x64-windows-2012-1. @bblondin will hopefully set it up

**Comment by bblondin** [comment]
- host has been renamed: test-packet-x64-windows-2012r2-1 (the r2 is new)
- Installed required apps: git, jq, ant, ant-contrib, wget, perl, Text_CSV
- Enabled in jenkins: https://ci.adoptopenjdk.net/computer/test-packet-x64-windows-2012r2-1
- @smlambert will test and let me know if anything else is required

**Comment by bblondin** [comment]
All looks good.
Confirmed in: https://github.com/AdoptOpenJDK/openjdk-tests/issues/40#issuecomment-303491009
