### ISSUE TITLE
Allow marist-1 build box to build openj9/jdk12

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#990]
The job https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk12u/job/jdk12u-linux-s390x-openj9/ (and maybe others) is locked to the https://ci.adoptopenjdk.net/computer/build-marist-rhel74-s390x-2/ machine and therefore won't run on https://ci.adoptopenjdk.net/computer/build-marist-rhel74-s390x-1/ - this is not ideal for redundancy and we need to verify why and remove the lock to that machine.

**Comment by M-Davies** [comment]
@sxa Since both the marist machine and JDK12 job have been removed/disabled (unless they have been renamed to `build-marist-rhel77-s390x-1, build-marist-rhel77-s390x-2`?), can this be closed?

**Comment by sxa** [comment]
Disabled as all the machines were recereated on new hosting hardware in December, so yeah might as well close this.
