### ISSUE TITLE
Stop $HOME/.gradle being used

### ISSUE THREAD

**Issue by sxa** [AdoptOpenJDK/openjdk-build#991]
Ideally everything for a build should be inside the `WORKSPACE` directory, or possibly directly under `JENKINS_HOME` if we want it shared but on the workspace file system.

If there's a variable we can use to control gradle's location we should look at setting it in our environment scripts.

```
 > git rev-list --no-walk aeacae9b2a97989b636477596ad98bef51767213 # timeout=10
Running in Durability level: PERFORMANCE_OPTIMIZED
ERROR: Could not find any definition of libraries [local-lib@master]
ERROR: Could not find any definition of libraries [local-lib@master]
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed

WorkflowScript: Loading libraries failed

2 errors
```

**Comment by M-Davies** [comment]
@sxa https://mrhaki.blogspot.com/2010/09/gradle-goodness-changing-gradle-user.html
We could set `GRADLE_USER_HOME` to `$WORKSPACE/.gradle`?

**Comment by M-Davies** [comment]
Also found https://stackoverflow.com/questions/16169638/where-should-i-put-gradle-properties-in-jenkins

**Comment by sxa** [comment]
Hmmm we do already set it in https://github.com/AdoptOpenJDK/openjdk-build/blob/master/sbin/build.sh#L447
