### ISSUE TITLE
Update policies

### ISSUE THREAD

**Issue by oderaita** [AdoptOpenJDK/openjdk-build#995]
Dear Sir,

If you look at the version of Oracle Java 8, two versions are always released. I understand that 191 is a critical patch (eg 191, 192) and 192 is an extension.

However, some critical patches,you  have not been released. Why is this.
Also, is the critical patch installer not including past enhancements?

**Comment by karianna** [comment]
Hi @oderaita - AdoptOpenJDK has decided to go for a PSU release policy, that is we release the later number (e.g. 192) which includes the CPU security fixes from (e.g. from 191).  Our consumers have overwhelmingly voted to have both the security fixes as well as the extra stability fixes.

Is there a particular need by your organisation to have the CPU build only?

**Comment by M-Davies** [comment]
Hi @oderaita. Does Martijn's answer [above](https://github.com/AdoptOpenJDK/openjdk-build/issues/995#issuecomment-477545265) answer your question? Thanks in advance

**Comment by aahlenst** [comment]
Closing due to lack of requested feedback. We're happy to reopen the issue if feedback is provided by the OP (or anybody else) at a later date.

**Comment by karianna** [comment]
Yeah the TSC voted that we'd only be doing PSU releases.  We've had no users asking for CPU only releases.
