### ISSUE TITLE
Cannot build jdk8 on kernel 5.x

### ISSUE THREAD

**Issue by grzesuav** [AdoptOpenJDK/openjdk-build#999]
**Platform:**
Dockerfile - ubuntu 16.04 official docker image
**Architecture:**
x86_64

https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/master/hotspot/make/linux/Makefile#L236

It seems ubuntu:16.04 image was updated recently, and it have kernel in version 5, which makes jdk8 not able to compile. 

```
*** This OS is not supported: Linux e5acbc255ebb 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
/openjdk/build/workspace/build/src/hotspot/make/linux/Makefile:242: recipe for target 'check_os_version' failed
/openjdk/build/workspace/build/src/hotspot/make/linux/Makefile:263: recipe for target 'linux_amd64_compiler2/debug' failed
Makefile:230: recipe for target 'generic_build2' failed
Makefile:177: recipe for target 'product' failed
HotspotWrapper.gmk:44: recipe for target '/openjdk/build/workspace/build/src/build/linux-x86_64-normal-server-release/hotspot/_hotspot.timestamp' failed
make[5]: *** [check_os_version] Error 1
make[4]: *** [linux_amd64_compiler2/debug] Error 2
make[3]: *** [generic_build2] Error 2
make[2]: *** [product] Error 2
make[1]: *** [/openjdk/build/workspace/build/src/build/linux-x86_64-normal-server-release/hotspot/_hotspot.timestamp] Error 2
/openjdk/build/workspace/build/src//make/Main.gmk:109: recipe for target 'hotspot-only' failed
make: *** [hotspot-only] Error 2
``` 
Solution : 
* downgrade kernel in dockerfile to latest 4.20 (need to dig out how to do in ubuntu)
* use fixed version of ubuntu 16.04 image (need to find one)

**Comment by grzesuav** [comment]
Will try to make PR when find easier of two proposed solutions

**Comment by grzesuav** [comment]
After digging - there is no kernel in image - kernel on my laptop is 5.0.4. Actually cannot do anything with that (well, besides downgrading of kernel, which is not suitable). 

Actually what stops from adding support for kernel 5.x in jdk 8 makefiles ?

**Comment by karianna** [comment]
I'd look at `/openjdk/build/workspace/build/src/hotspot/make/linux/Makefile:242` and see if there's an easy fix (adding 5 as a supported version)

**Comment by grzesuav** [comment]
I would try to add there 5.x as compatible version. But to which repository ? 
Origin is http://hg.openjdk.java.net/jdk8/jdk8 - could you point me how it should be done ?
(like do I need create bug report first, and how to mae PR there ? )

**Comment by karianna** [comment]
> I would try to add there 5.x as compatible version. But to which repository ?
> Origin is http://hg.openjdk.java.net/jdk8/jdk8 - could you point me how it should be done ?
> (like do I need create bug report first, and how to mae PR there ? )

The project page you want is: https://openjdk.java.net/projects/jdk8u/ and I'd report the issue here: https://mail.openjdk.java.net/mailman/listinfo/jdk8u-dev and see if anyone else has run across it.  If so then perhaps offer to work on a patch (but ask for a sponsor)

**Comment by grzesuav** [comment]
Posted information https://mail.openjdk.java.net/pipermail/jdk8u-dev/2019-April/009034.html , will see how it goes

**Comment by karianna** [comment]
> Got response :) it was quick - @karianna it seems that fix is already in master (http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/rev/5af8ec63c21c) but AdoptOpenJDK repo was synced 28 days ago - there are changes not being visible.

That's a bug in our jdk8u repo then possibly - @johnoliver Our diff seems OK so not sure what's going on here

**Comment by sxa555** [comment]
We can build on Ubuntu 16.04 docker images (which is what our Dockerfiles are are based on) at https://ci.adoptopenjdk.net/view/Tooling/job/DockerfileCheck/label=infra-vagrant-1,variant=hotspot,version=jdk8u successfully so I beleive this is no longer a problem, therefore closing. If that is not the case, please feel free to reopen ...

**Comment by Nick9980** [comment]
| ++ uname -a
| + echo '*** This OS is not supported:' Linux 968123be7f41 5.15.0-91-generic '#101~20.04.1-Ubuntu' SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
| *** This OS is not supported: Linux 968123be7f41 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
| + exit 1
| make[5]: *** [/opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/jdk8u-4be07cb28b21/hotspot/make/linux/Makefile:242: check_os_version] Error 1
| make[4]: *** [/opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/jdk8u-4be07cb28b21/hotspot/make/linux/Makefile:263: linux_amd64_compiler2/debug] Error 2
| make[3]: *** [Makefile:231: generic_build2] Error 2
| make[2]: *** [Makefile:177: product] Error 2
| make[1]: *** [HotspotWrapper.gmk:45: /opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/build/hotspot/_hotspot.timestamp] Error 2
| make: *** [/opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/jdk8u-4be07cb28b21//make/Main.gmk:109: hotspot-only] Error 2
| ERROR: oe_runmake failed
| WARNING: /opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/temp/run.do_compile.1218160:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at /opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/temp/log.do_compile.1218160)
ERROR: Task (/opt/PHYTEC_BSPs/yocto_imx7/sources/meta-java/recipes-core/openjdk/openjdk-8-native_162b12.bb:do_compile) failed with exit code '1'

below is my kernel version showing, i am trying to compile for custom board in docker with ubuntu 16.04
if any one have faced this issue can help
please let me know

nayan@968123be7f41:/opt/PHYTEC_BSPs/yocto_imx7/sources/meta-java/recipes-core$ uname -a
Linux 968123be7f41 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
nayan@968123be7f41:/opt/PHYTEC_BSPs/yocto_imx7/sources/meta-java/recipes-core$ uname -r
5.15.0-91-generic

**Comment by karianna** [comment]
> | ++ uname -a | + echo '*** This OS is not supported:' Linux 968123be7f41 5.15.0-91-generic '#101~20.04.1-Ubuntu' SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux | *** This OS is not supported: Linux 968123be7f41 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux | + exit 1 | make[5]: *** [/opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/jdk8u-4be07cb28b21/hotspot/make/linux/Makefile:242: check_os_version] Error 1 | make[4]: *** [/opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/jdk8u-4be07cb28b21/hotspot/make/linux/Makefile:263: linux_amd64_compiler2/debug] Error 2 | make[3]: *** [Makefile:231: generic_build2] Error 2 | make[2]: *** [Makefile:177: product] Error 2 | make[1]: *** [HotspotWrapper.gmk:45: /opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/build/hotspot/_hotspot.timestamp] Error 2 | make: *** [/opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/jdk8u-4be07cb28b21//make/Main.gmk:109: hotspot-only] Error 2 | ERROR: oe_runmake failed | WARNING: /opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/temp/run.do_compile.1218160:1 exit 1 from 'exit 1' | ERROR: Function failed: do_compile (log file is located at /opt/PHYTEC_BSPs/yocto_imx7/build/tmp/work/x86_64-linux/openjdk-8-native/162b12-r0/temp/log.do_compile.1218160) ERROR: Task (/opt/PHYTEC_BSPs/yocto_imx7/sources/meta-java/recipes-core/openjdk/openjdk-8-native_162b12.bb:do_compile) failed with exit code '1'
> 
> below is my kernel version showing, i am trying to compile for custom board in docker with ubuntu 16.04 if any one have faced this issue can help please let me know
> 
> nayan@968123be7f41:/opt/PHYTEC_BSPs/yocto_imx7/sources/meta-java/recipes-core$ uname -a Linux 968123be7f41 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux nayan@968123be7f41:/opt/PHYTEC_BSPs/yocto_imx7/sources/meta-java/recipes-core$ uname -r 5.15.0-91-generic

Can you go more modern that 16.04 - that's likely the challenge here (out of support OS)
